### ISSUE TITLE
PtrToString Behavior Differs on PS 7 Linux vs Windows

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/PowerShell#12125] opened 2020-03-13 23:03 UTC
# Steps to reproduce

```powershell
$ss = ConvertTo-SecureString -String 'TestString' -AsPlainText -Force
$bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($ss)
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
```

# Expected behavior

```none
Should return 'TestString'
```

# Actual behavior

On PS 7 on Linux:
```none
Returns 'T' - Incorrect Behavior.
```

![image](https://user-images.githubusercontent.com/7589164/76665147-9a612880-65eb-11ea-938f-df469c6c1b21.png)

On PS 7 on Windows 10:
```none
Returns 'TestString' - Correct Behavior.
```

![image](https://user-images.githubusercontent.com/7589164/76665077-671e9980-65eb-11ea-9952-3747426e8d9c.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.4.0-19582-Microsoft #1001-Microsoft Thu Mar 06 16:40:00 PST 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This is a minor issue as the above code can usually be replaced with `ConvertFrom-SecureString` on PS 7/PS Core 6, but not on PS 5.1.

**Comment by mklement0** [comment] 2020-03-13 23:21
This is a duplicate of #12114; for a summary, see https://github.com/PowerShell/PowerShell/issues/12114#issuecomment-598347725

**Closed** 2020-03-14 03:25 UTC
Labels: Issue-Question, Resolution-Duplicate
