### ISSUE TITLE
Unable to rename or move file on linux whose name contains 'C:\'

### ISSUE THREAD

**Issue by soul4soul** [PowerShell/PowerShell#11315] opened 2019-12-10 21:47 UTC
# Steps to reproduce
I ended up with a file on Linux named `'C:\users\engineer\Release\regression_log.txt'`. I tried to use Move-Item and then Rename-Item to fix the name of the file but was unable to due so. As can be see in the log even Get-ChildItem struggled with displaying the file appropriately. gci mistakenly thought the file was in a subfolder. Using mv from bash I was able to fix the file name. I would never intentionally create a file with such a name but It should still be possible to fix the name when it does happen.
```powershell
engineer@se206:~/Downloads/5603/windows/factory/bu$ pwsh-preview 
PowerShell 7.0.0-preview.6
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/engineer/Downloads/5603/windows/factory/bu> gci


    Directory: /home/engineer/Downloads/5603/windows/factory/bu

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxrwxr-x engineer         engineer           12/10/2019 12:07           4096 docs
drwxrwxr-x engineer         engineer           12/10/2019 12:07           4096 package
drwxrwxr-x engineer         engineer           12/10/2019 12:07           4096 uvn

    Directory: /home/engineer/Downloads/5603/windows/factory/bu/C:/users/engineer/Release

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rw-r--r-- engineer         engineer           12/10/2019 15:53          35228 C:\users\engineer\Release\regression_log.txt

    Directory: /home/engineer/Downloads/5603/windows/factory/bu

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rw-r--r-- engineer         engineer           12/10/2019 16:23          35342 regression_log.txt
-rw-r--r-- root             root               12/10/2019 16:20            949 setup.iss
-rw-rw-r-- engineer         engineer           12/10/2019 16:19           9723 test.ps1

PS /home/engineer/Downloads/5603/windows/factory/bu> Move-Item "C:\users\engineer\Release\regression_log.txt" "regression_log.txt"
Move-Item: Cannot find drive. A drive with the name 'C' does not exist.
PS /home/engineer/Downloads/5603/windows/factory/bu> Move-Item ".\C:\users\engineer\Release\regression_log.txt" "regression_log.txt"
Move-Item: Cannot find path '/home/engineer/Downloads/5603/windows/factory/bu/C:/users/engineer/Release/regression_log.txt' because it does not exist.
PS /home/engineer/Downloads/5603/windows/factory/bu> Rename-Item "C:\users\engineer\Release\regression_log.txt" "regression_log.txt"  
Rename-Item: Cannot find drive. A drive with the name 'C' does not exist.
PS /home/engineer/Downloads/5603/windows/factory/bu> Rename-Item ".\C:\users\engineer\Release\regression_log.txt" "regression_log.txt"
Rename-Item: Cannot find path '/home/engineer/Downloads/5603/windows/factory/bu/C:/users/engineer/Release/regression_log.txt' because it does not exist.
PS /home/engineer/Downloads/5603/windows/factory/bu> ls
'C:\users\engineer\Release\regression_log.txt'	 docs   package   regression_log.txt   setup.iss
PS /home/engineer/Downloads/5603/windows/factory/bu> exit
engineer@se206:~/Downloads/5603/windows/factory/bu$ ls
'C:\users\engineer\Release\regression_log.txt'   docs   package   regression_log.txt   setup.iss   test.ps1   uvn
engineer@se206:~/Downloads/5603/windows/factory/bu$ mv 'C:\users\engineer\Release\regression_log.txt' reg.txt
engineer@se206:~/Downloads/5603/windows/factory/bu$ ls
docs  package  regression_log.txt  reg.txt  setup.iss  test.ps1  uvn
```
I missed capturing the results but `Rename-Item .\*regression_log.txt reg.txt` failed too.

# Expected behavior
I expect to be able to cleanly list the contents of a directory which contains a file whose name starts with `C:\`. I expect to be able to call Move-Item and Rename-Item with a file whose name starts with `C:\`

# Actual behavior
See log from steps to reproduce section.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment] 2019-12-12 17:55
Good find, but it is a duplicate of #9244, which lists all required changes to support interchangeable use of `\` and `/` on Unix-like platforms.

**Comment by vexx32** [comment] 2019-12-12 18:01
In the meantime, try targeting the file with `./C:\...` (i.e., explicit relative path or possibly full absolute path).

As long as there is a prefix making it clear you're not targeting an actual drive, you may be able to work around the issue.

**Comment by mklement0** [comment] 2019-12-12 18:17
Unfortunately, that doesn't work:

```powershell
PSonUnix> touch 'c:\a\b'; ri './c:\a\b'
Remove-Item: Cannot find path '/Users/jdoe/c:/a/b' because it does not exist.
```

Note how the `\` were converted to `/` and are interpreted as directory separators.

**Closed** 2023-11-23 12:07 UTC
Labels: Issue-Bug, WG-Cmdlets-Management, WG-Engine-Providers, Area-FileSystem-Provider, Resolution-No Activity
