### ISSUE TITLE
Invoke-RestMethod  Command fails on PS 6.0 beta and alpha releases on windows 10 , server 2012 , 2008 r2

### ISSUE THREAD

**Issue by amal-khalaf** [PowerShell/PowerShell#3817] opened 2017-05-18 23:15 UTC
Steps to reproduce
------------------
download
 •	PowerShell-6.0.0-alpha.18-win7-win2008r2-x64.msi 
•	PowerShell-6.0.0-alpha.18-win7-win2008r2-x64.zip 

when running below ps cmdlet it fails with below exception on ps6.0 
..
$headers = @{
      'Authorization' = "Bearer $Token"
    }

Expected behavior
-----------------
to execute successfulluy

Actual behavior
---------------
  Invoke-RestMethod : InvalidAuthenticationInfoAuthentication information is not
given in the correct format. Check the value of Authorization header.
RequestId:13bd701c-0001-0057-7551-cf5369000000
Time:2017-05-17T21:09:19.1268565Z

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment] 2017-05-18 23:34
Dupe of https://github.com/PowerShell/PowerShell/issues/2227

**Closed by SteveL-MSFT** 2017-05-18 23:34 UTC
Labels: Resolution-Duplicate
