### ISSUE TITLE
Provide a way to stop "Register-ArgumentCompleter -Native" from falling back to suggesting files when there are no suggestions

### ISSUE THREAD

**Issue by michaeljones** [PowerShell/PowerShell#18233] opened 2022-10-07 08:13 UTC
### Summary of the new feature / enhancement

I am writing a completion hook for a native command and there are situations where there are no reasonable suggestions to make for a particular point on the command line. Either the position on the command line requires something that cannot be reasonably suggested - eg. the version number for some report that is being generated or something - or there is no good suggestion for what the user has already written - eg. wanting to suggest a subcommand name but they've already typed 'b' and there are no subcommands beginning with 'b'.

In that case, my script block doesn't generate any suggestions and so PowerShell falls back to suggesting files in the current directory. Either the first file or any files matching the partial string already written.

In this situations described, suggesting files is less useful than suggesting nothing. Is there a way I can turn off the file suggestions? And if not, could that be treated as a feature request?

If it is possible then I would have thought it would be documented on https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.2 but I don't think it is.

**Comment by MartinGC94** [comment] 2022-10-07 15:56
Duplicate of this: https://github.com/PowerShell/PowerShell/issues/7215

**Comment by michaeljones** [comment] 2022-10-07 16:07
Looks like it! Sorry, I didn't find that. I searched for `Register-ArgumentCompleter` before making this.

**Closed** 2022-10-08 17:01 UTC
Labels: Resolution-Duplicate, Issue-Enhancement, Needs-Triage
