### ISSUE TITLE
write-host ForegroundColor color wrong both windows and linux

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2210] opened 2016-09-08 16:17 UTC
Write-Host  '████████'  -ForegroundColor DarkYellow #  return wrong color on windows.

Write-Host  '████████'  -ForegroundColor Yellow #
Write-Host  '████████'  -ForegroundColor DarkYellow #
Write-Warning  '████████' #
return color is same on linux.

notice:
i have  already searched windows powershell bug report use 'ForegroundColor'.Did not find the same bug report.
https://windowsserver.uservoice.com/forums/301869-powershell

Steps to reproduce
------------------
Write-Host  '████████'  -ForegroundColor Yellow
Write-Host  '████████'  -ForegroundColor DarkYellow

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------
win:

Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

centos 7.2:

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-alpha                                                                                                       
PSEdition                      Core                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   3.0.0.0                                                                                                           
GitCommitId                    v6.0.0-alpha.9                                                                                                    
CLRVersion                                                                                                                                       
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1 

i use xshell terminal software,choose 'ansi colors on black' color schemes.

**Comment by ealexjordan** [comment] 2016-09-09 21:04
Was able to repro this on Windows. 
For American troubleshooters the repro is the following: 
1. Install Microsoft Chinese (simplified) keyboard 
2. Change Region>location to China
3. Change Region>Administrative>Language for non-Unicode programs to Chinese
4. Open PowerShell and type `Write-Host '你好' -ForegroundColor DarkYellow. (nihao is the single quoted text in pinyin)
Text is correctly printed, but is not colored. 
![capture](https://cloud.githubusercontent.com/assets/5847981/18402788/07764d04-7696-11e6-9730-e0f163afd0f5.PNG)

**Comment by ealexjordan** [comment] 2016-09-09 21:48
Works fine on Linux as far as I can see with pinyin input and all regional settings set to simplified chinese. 
![capture](https://cloud.githubusercontent.com/assets/5847981/18403945/82891c28-769c-11e6-9e3b-14749f7e2163.PNG)

**Comment by ealexjordan** [comment] 2016-09-09 22:37
It's only happening on DarkYellow, it appears: 
![capture](https://cloud.githubusercontent.com/assets/5847981/18405023/5998d1e4-76a3-11e6-8986-ba7f67d08927.PNG)

**Comment by ealexjordan** [comment] 2016-09-09 23:10
Operating as expected as per: http://stackoverflow.com/questions/21941606/why-does-powershell-display-darkyellow-text-improperly

**Comment by andschwa** [comment] 2016-09-09 23:40
Closing as it's existing PowerShell behavior.

**Closed by andschwa** 2016-09-09 23:40 UTC

**Comment by chuanjiao10** [comment] 2016-09-10 07:13
ealexjordan: 
1 It has nothing to do with Chinese.
2 My point of view is "Yellow ,DarkYellow, return sam color on linux."
--------------------------------------
andschwa:
what is "existing PowerShell behavior" ?

**Comment by chuanjiao10** [comment] 2016-09-10 07:40
![wcolor001](https://cloud.githubusercontent.com/assets/8968667/18408794/7c303da4-776c-11e6-93b5-23c1d9d8d07d.jpg)
centos7.2 + powrshell + putty

**Comment by andschwa** [comment] 2016-09-12 20:06
@chuanjiao10 your original issue:

> Write-Host '████████' -ForegroundColor DarkYellow # return wrong color on windows.

Is [existing and intended behavior](https://stackoverflow.com/questions/21941606/why-does-powershell-display-darkyellow-text-improperly).

> Write-Warning '████████' #return color is same on linux.

The color that the ASCII keycode for your terminal's DarkYellow is entirely dependent on your setup; PowerShell has no control over this.

You also did not fill in the "Expected behavior" or "Actual behavior", so we're grasping at straws as to what you're trying to report.

> PSEdition Desktop

This forum is for Core PowerShell bugs, specifically the packages available on GitHub. You're attempting to file a bug for Desktop PowerShell (i.e. the in-box PowerShell on Windows), please use the user voice forums for this.

**Comment by ealexjordan** [comment] 2016-09-12 20:06
@chuanjiao10 - I assumed the original issue was an unknown char set causing an issue, like an encoding problem of some kind.
So far I cannot repro this on Ubuntu, Windows, or CentOS. I'm using Putty 0.67 with out of box settings using SSH and seeing no problems.

**Comment by andschwa** [comment] 2016-09-12 20:31
This has *nothing to do with PowerShell*.

```sh
$ dotnet new
$ dotnet restore
```

Edit `Program.cs` to be:

```c#
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.WriteLine("yellow");
        Console.ResetColor();

        Console.ForegroundColor = ConsoleColor.DarkYellow;
        Console.WriteLine("dark yellow");
        Console.ResetColor();
    }
}
```

```sh
$ dotnet run
Project color-test (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling color-test for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.9961751
 

yellow
dark yellow
```

The colors will be whatever you have setup in your terminal emulator; which completely depends on you. For instance, with my default `TERM=xterm` I don't even *have* 16 bit color support.

![yellow](https://cloud.githubusercontent.com/assets/2226434/18451453/de0259e2-78eb-11e6-8d39-62d01ae6fa14.PNG)

But I can fix that! Again, this has nothing to do with PowerShell. It's a Linux terminal emulator thing.

```sh
export TERM=xterm-256color
```

![darkyellow](https://cloud.githubusercontent.com/assets/2226434/18451732/f85227c2-78ec-11e6-8dc6-1b2978fc3c03.PNG)

@chuanjiao10 you do not have your terminal emulator setup properly. I highly recommend following [this article](https://sanctum.geek.nz/arabesque/putty-configuration/) to do so. But as this has nothing to do with PowerShell, I'm not re-opening the issue.

Moreover, `DarkYellow` doesn't correspond to any of the default [ANSI colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). It's a Windows-ism in C# that didn't map properly. If you'd like to open an issue with this, the proper location is [CoreFX](https://github.com/dotnet/corefx).

But a [really quick search](https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=darkyellow) tells us that [they already know](https://github.com/dotnet/corefx/blob/5e36ca02d2594f715da829aafaf7af2b554dfcdf/src/System.Console/src/System/ConsolePal.Unix.cs#L578).

**Comment by chuanjiao10** [comment] 2016-09-13 08:26
en,
for windows: i report to user voice forums.
for linux: i thanks to @andschwa share knowledge.
@ealexjordan :  For thanks reply

**Comment by nightroman** [comment] 2017-06-25 15:04
The behavior might be by design. That is the issue is not a bug. But the design might be poor (usability suffers, the least surprise principle is violated, etc.). I find this design poor.

**Comment by SteveL-MSFT** [comment] 2017-06-25 19:26
I agree the original design may not have been thought through as it's reasonable to expect DarkYellow to be a specific color and not an index into a color table.  If we change this, it would be a breaking change.  It also seems like using vt100 directly for color is preferred (assuming Win10 and Linux).

**Comment by andschwa** [comment] 2017-06-26 00:10
@SteveL-MSFT what does this mean?

> It also seems like using vt100 directly for color is preferred (assuming Win10 and Linux).

The `TERM` setting of `vt100` is completely arbitrary and not actually even used much any more. I _think_ you're meaning "using ANSI escape codes directly" (as in, bypass .NET's mapping), but `vt100` is just one particular possible terminal emulator out of many that users could be using (probably `xterm` and `screen` (and their 256 color variants) being the most popular).

**Comment by andschwa** [comment] 2017-06-26 00:12
> I agree the original design may not have been thought through as it's reasonable to expect DarkYellow to be a specific color and not an index into a color table.

Totally agree here. But at the least, PowerShell is one of many (many, many) console applications suffering from the same problem, all arising from a time when there were only 16 colors to use. What would be really cool is if we could get PowerShell to natively support the true color modes of modern terminals.

**Comment by chuanjiao10** [comment] 2017-06-26 06:01
Does anyone discuss this question? 
Since andschwa told me the answer, my color obsessive-compulsive disorder all good friends.
I have also developed more:  not need change the powershell source

How to use 256 colors, **together** with the keyboard num pad:
Export TERM = putty-256color
Or
Export TERM = Eterm-256color
Or
Export TERM = st-256color

Now, i share to anyone, which document should we put in?

**Comment by SteveL-MSFT** [comment] 2017-06-26 17:01
@andschwa yes, meant ANSI escape codes
