### ISSUE TITLE
PowerShell Core Beta 5 - Enter-PSSession error impacting Ubuntu terminal session.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4514] opened 2017-08-07 01:23 UTC
PowerShell Core 'Enter-PSSession' error is impacting the Ubuntu Bash console badly to the point that I'm force to close the terminal session

Steps to reproduce
------------------
Exit powershell and keep working in linux. 
refer to: https://github.com/PowerShell/PowerShell/issues/4513 

Expected behavior
-----------------
Linux terminal to work normally.

Actual behavior
---------------
After exiting powershell the console terminal cursor long delay to not responding

Environment data
----------------
Ubuntu 16.04.3
PowerShell Core Beta 5

```powershell
PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-beta                                                                              
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.0-beta.5                                                                           
OS                             Linux 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017                     
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0

```
![enterpssession_err_02](https://user-images.githubusercontent.com/19892435/29009001-3bac29de-7aed-11e7-9045-c6cf6356dfd6.png)

**Comment by iSazonov** [comment] 2017-08-07 04:47
It seems we already have such Issue.

**Comment by PaulHigin** [comment] 2017-08-07 16:48
This looks like a duplicate of #4513.  If I am incorrect then please re-activate with clarification.
As mentioned in #4513 the error message is from SSH is telling us that it cannot write to the known_hosts file, I suspect because of permission issues.

Enter-PSSession -HostName uses the SSH.exe client installed on the machine.  You would probably see the same error if you used ssh.exe directly:
```powershell
PS /home/maxt> ssh.exe max_t@earth2
```

**Closed by PaulHigin** 2017-08-07 16:48 UTC

**Comment by MaximoTrinidad** [comment] 2017-08-07 18:00
Hi @PaulHigin,

The issue only exist with Enter-PSSession.  The SSH.exe works fine Linux to Windows 10 as I stated in #4513. 

By the way, #4531 issue is about te Ubuntu Terminal stop working. It is forcing me to close the terminal session after 'exit' powershell.

**Comment by iSazonov** [comment] 2017-08-08 04:44
@MaximoTrinidad Maybe related https://github.com/PowerShell/PowerShell/issues/2804
