### ISSUE TITLE
Custom prompt displays incorrectly on macOS

### ISSUE THREAD

**Issue by gavinmorrison** [PowerShell/PowerShell#2094] opened 2016-08-27 10:57 UTC
Steps to reproduce
------------------
Configure a custom prompt on macOS:
```powershell
function Prompt {
    Write-Host -ForegroundColor Green -Object "[$((Get-Date).ToString())]"
    Write-Host -ForegroundColor Cyan -Object "$($PWD)"
}
```

Expected behavior
-----------------
**macOS**
```powershell
[27/08/2016 11:45:20]
/Users/gavin
PS>
```
**Windows**
```powershell
[27/08/2016 11:45:20]
C:\Users\gavin
PS>
```
Actual behavior
---------------
**macOS**
Prompt is duplicated:
```powershell
[27/08/2016 11:45:34]
/Users/gavin
PS>[27/08/2016 11:45:34]
/Users/gavin
```
After typing, the first line of the second prompt disappears:
```powershell
[27/08/2016 11:45:34]
/Users/gavin
PS>Get-Date
/Users/gavin
```
**Windows**
Prompt displays correctly:
```powershell
[27/08/2016 11:45:20]
C:\Users\gavin
PS>
```

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Tested on Mac OS X 10.11.4 using:

- Apple Terminal Version 2.6.1 (361.1)
- iTerm2 Build 3.0.7

**Comment by lzybkr** [comment] 2016-08-27 19:35
Duplicate of #1897.

**Closed by lzybkr** 2016-08-27 19:35 UTC
