### ISSUE TITLE
Resolve UTF-8, UTF-16, ASCII inconsistencies

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#707] opened 2016-03-20 16:21 UTC
PS> ls > test
BASH> ls >> test
BASH> cat test  # Content looks correct
PS> cat test # Content is wrong at the end

**Comment by GeeLaw** [comment] 2016-10-04 22:02
The issue is related to binary pipelines.

After you call a native utility (e.g., `ls`) in PowerShell, the output is converted to a `string` -- it's no longer a byte stream. You cannot expect anything good now.

The best you can do is to use PowerShell utilities since they don't produce byte streams, but objects. And the expected binary pipeline will solve these problems.

Q: Why guessing the encoding is a bad idea?
A: Guessing encoding can be wrong. And it can be NOT EVEN WRONG. Imagine a utility that produces binary stream that cannot be interpreted as a `string`, e.g., it contains what will be interpreted as `0`, or it is a bitmap.

See #1908 and #1975.

**Comment by JamesWTruher** [comment] 2017-02-02 23:13
to handle simple redirection, the following would be possible:
```powershell
$PSDefaultParameterValues['out-file:encoding'] = "ascii"
```
then the following works just fine (on linux)
```powershell
gci > test
bash -c 'ls >> test'
bash -c "cat test"
gci test
```
having different settings on Linux and Windows would solve the problem, since most linux apps are just going to output ascii. I don't believe there's any hope for combinations of apps which emit unicode ascii when attempting to do redirection
  85 gc test

**Comment by joeyaiello** [comment] 2017-02-08 23:04
I think we probably need an RFC of some kind for this behavior that answer some of my open questions (although I think they're worth discussion today because the answer to a few of them may determine the level of abstraction at which that RFC should be written):

* Given the scarcity of BOM usage w/ UTF-8 text files on Linux, should we have different behavior for `*-Content` cmdlets? 
* Related: are there any scenarios where reading an ASCII file as a UTF-8 file without a BOM is incorrect? 
* What are some cross-platform scenarios/demos that demonstrate success in this space?
* Can we break existing Windows behavior here? 
* Do we need some sort of `$EncodingPreference` (or something like that)? 
* Do redirection operators need to do something special here based on said `$EncodingPreference`
* Should we pull in `Invoke-WebRequest`/`Invoke-RestMethod` as part of this work? 
* Do we have an uber-level of platform-specific design behavior that we need to abstract behind some global setting (potentially w/ different platform-specific defaults)?

**Comment by joeyaiello** [comment] 2017-02-09 00:45
Other:
* `$OutputEncoding` is only used for pipes of native commands currently. It also requires that you do `$outputencoding = [System.Text.Encoding]::UTF8` in order to change it. That's not an awesome UX. 
* On Windows, `Set-Content` uses ASCII by default, `Out-File` uses UTF-16 by default. 

Open still:
* Do we use a cmdlet or a preference variable? 

Closed on:
* Okay to have different default behaviors on different systems. 
* Right default behavior on Linux is UTF-8 with no BOM. 
* Okay to change the all encoding behavior on a single machine (like `$OutputEncoding`) 
* No change to current default Windows behavior. 
* Need some way to change back to the "WindowsDefault" Encoding value that mixes default behavior for Set-Content and Out-File.

**Comment by dahlbyk** [comment] 2017-03-17 16:33
Came here looking for issue related to this because `>` producing UTF-16 by default is maddening.

> Do we need some sort of $EncodingPreference (or something like that)?

Please!

> Can we break existing Windows behavior here?

Less necessary if there's a preference, IMO, though I have never seen a developer respond positively to a file being encoded with UTF-16. If PowerShell 6+ can lead the charge on moving Windows toward UTF-8-without-BOM everywhere that would be amazing.

> Do redirection operators need to do something special here based on said $EncodingPreference

This seems to me to be the primary purpose of `$EncodingPreference` in the first place: changing the encoding used by `>`. Changing the default encoding for `Out-File`, `Set-Content`, etc. is a bonus, but at least those support a parameter (unlike `>`).

Not sure if `>>` already delegates to `Add-Content`, but it should behave the same: preserve encoding for an existing file, otherwise create a file with the specified (or default) encoding.

**Comment by joeyaiello** [comment] 2017-03-20 23:53
We have an [RFC open for this work](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0020-DefaultFileEncoding.md) (please [add your comments in the issue dicussion](https://github.com/PowerShell/PowerShell-RFC/issues/71) @dahlbyk) but it will likely not land in beta1.

**Comment by regs01** [comment] 2017-05-16 22:51
My humble opinion shares some other opinions above. Default for Out-File should be UTF8 without BOM in every system.

**Comment by SteveL-MSFT** [comment] 2017-09-30 17:20
For 6.0.0 release we'll be doing a reduced scope version of this https://github.com/PowerShell/PowerShell/issues/4878

**Comment by joeyaiello** [comment] 2017-12-19 18:34
@JamesWTruher could you clarify here what *wasn't* achieved by the implementation that we're shipping in 6.0?

**Comment by SteveL-MSFT** [comment] 2018-01-02 20:47
The original issue from @jpsnover no longer repros with RC2 with @JamesWTruher's [changes](https://github.com/PowerShell/PowerShell/pull/5369).  I believe the change from Jim is that we default `$OutputEncoding` to utf-8 NoBOM instead of ASCII.

**Closed** 2018-01-31 04:29 UTC
Labels: Area-Engine, Area-Portability, Committee-Reviewed, Issue-Enhancement, Resolution-Fixed
