### ISSUE TITLE
PowerShell prompt on mac is displayed twice

### ISSUE THREAD

**Issue by Abhik11** [PowerShell/PowerShell#2079] opened 2016-08-26 19:01 UTC
Steps to reproduce
------------------
Put the following in the profile.ps1 file: 
function prompt
{
    Write-Host ("PS " + $($PWD) + ":" + $(Get-Content /Users/chat/fbsource/.hg/bookmarks.current) + ")]>") -nonewline -foregroundcolor White
    return " "
}

Expected behavior
-----------------
Something like the following is displayed:PS PS /Users/chat/fbsource/fbandroid:TestsForLoggingCallbacks)]>

Actual behavior
---------------
The prompt text is displayed twice and upon typiing any command, the prompt text disappears
PS /Users/chat/fbsource/fbandroid:TestsForLoggingCallbacks)]> PS /Users/chat/fbsource/fbandroid:TestsForLoggingCallbacks)]>

(Type something)
                                                              hello
(Prompt text is gone)

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lzybkr** [comment] 2016-08-26 20:02
Duplicate of #1897.

**Closed by lzybkr** 2016-08-26 20:02 UTC
