### ISSUE TITLE
Explain Scriptblock GetnewClosure and StrictMode "design"

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#21045] opened 2024-01-11 07:31 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

As your bot doesn't allow me to ask a simple follow up question before closing the ticket I probably have to open a new one just to ask this follow up question...

See #20812 for context.
/cc @JamesWTruher 

------
Ok, so breaking the assurance of StrictMode is a feature then? Sounds odd...

The issue is not that it doesn't copy the strictmode setting, but rather that it will cause strictmode to be ignored on invokation time. And it just sounded reasonable to me to have GetNewClosure copy in the strictmode setting.
The alternative is that invoking a scriptblock that had getnewclosure called upon it before will honer strictmode. But that sounded like another can of worms previously because of how it is implemented (it being like a module).

Example code:
```
PS /> Set-StrictMode -version $PSVersionTable.PSVersion
PS /> $a = { Write-Host "$nonExisting"}                
PS /> $a.Invoke()                      
MethodInvocationException: Exception calling "Invoke" with "0" argument(s): "The variable '$nonExisting' cannot be retrieved because it has not been set."
PS /> $a.GetNewClosure().Invoke()

PS /> 
```

As one can see the issue is that the scriptblock appears to have executed successfully even though it should have failed because of the StrictMode.

### Expected behavior

```console
StrictMode at least at some point causing the ScritBlock to throw an exception. Either when GetNewClosure is called or when it is Invoked.
```

### Actual behavior

```console
No exception. StrictMode is silently ignored and error going undetected.
```

### Environment data

```powershell
.
```

**Comment by fMichaleczek** [comment] 2024-01-11 11:41
Do not hesitate to read this document so that you increase your level of understanding. The PowerShell team's answer is correct.
https://mdgrs.hashnode.dev/scriptblock-and-sessionstate-in-powershell

**Comment by mklement0** [comment] 2024-01-11 19:00
Pragmatically speaking:

* You cannot enforce strict-mode settings at the time of calling `.GetNewClosure()`, as only _invocation_ (execution) of the script block will surface any strict-mode violations, given that the runtime conditions aren't knowable ahead of time (e.g., if a _global_ `$nonExisting` variable happens to exist at invocation time, no strict-mode violation would occur).

* The stated design rationale is: The mandate of `.GetNewClosure()` is _solely_ to capture copies of the _local variables_ - and nothing else.

* Changing this behavior now would amount to an unacceptable breaking change.

* However, you cold open a _feature request_ for introducing a new `.GetNewClosure()` overload  - i.e. an _opt-in_ way to support copying the effective strict mode to the dynamic module that underlies the script block returned.
  * Obviously, there's no guarantee that such a feature will be implemented, but in my estimation it is your only realistic chance to get the behavior you want.

**Comment by agowa** [comment] 2024-01-11 20:39
Pragmatically speaking it should just fail on invocation time the same way as it does without GetNewClosure...

(Also there is no global $nonExisting variable in this case, just run the few lines of example code and see for yourself)

**Comment by mklement0** [comment] 2024-01-11 21:03
Pragmatically speaking, you can continue to be cantankerous, which ensures that you're even less likely to be heard.

> Also there is no global `$nonExisting` variable in this case

Yes, but that is unrelated to the point I made.

**Comment by agowa** [comment] 2024-01-12 00:15
I'd like to apologize. It wasn't my intent to be cantankerous. I'm just a little bit annoyed by how the process and interaction within these tickets changed recently. Esp. the bot closing unresolved tickets and the process in itself having become "suboptimal". Or specifically in this case the bot closing the initial ticket before it was actually fully addressed. It kinda felt like bug reports aren't taken seriously anymore...

The initial ticket was closed by saying that a suggested alternative implementation that would address the issue is not going to change as it is "by design" and then also marking the ticket as "resolved" even though it wasn't, just felt kinda condescending. However it probably was not that productive to let the emotions write the follow up ticket...


Coming back to the topic.
> Yes, but that is unrelated to the point I made.

Ok, but what did you mean with your very first point then? I understood it the lines of "the .Invoke() already causes an exception", but that's not the case and that's exactly the issue.


(The part ".GetNewClosure should throw an exception with strict mode" was just a crude hacky workaround for the feedback of it not being possible to throw an exception when calling .Invoke, as the new ScriptBlock will be considered similar like a module and modules are treated special in regards to strict mode in order to "protect" libraries.)

**Comment by mklement0** [comment] 2024-01-12 03:06
Thank you, @agowa - I appreciate your being accountable.

Speaking merely as a fellow user - who just happens to have been around for many years - I empathize with getting frustrated with closure of issues and/or lack of / curt feedback - the recently introduced bot action to auto-close issue certainly doesn't help, and - as of this writing - [428 of my own issues](https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+author%3A%40me+is%3Aclosed+label%3A%22Resolution-No+Activity%22) have fallen victim to this.

Unquestionably, this state of affairs is deplorable.

That said, in any given case, it is worth focusing on a productive way forward, which I've tried to guide you toward here.

---

> Ok, but what did you mean with your very first point then? I understood it the lines of "the .Invoke() already causes an exception"

No, my point was that PowerShell's _dynamic scoping_ (for better or - arguably - worse) makes it fundamentally impossible to _statically_ reason about the runtime behavior of a given piece of code.  
Therefore, it is categorically impossible to enforce the strict mode currently in effect on a script block _at the time `.GetNewClosure()` is called_.

Yes, you could argue that the _implementation detail_ of using dynamic modules to implement closures has unwanted side effects / does not exhibit the behavior you expect, but, as argued in my previous comment, the only sensibly way to change that now - without breaking existing code - is by way of an _opt-in_ mechanism - hence my suggestion to create a feature request (which may or may not see the light of day - that is just a fact of life).

**Comment by SeeminglyScience** [comment] 2024-01-18 18:14
I was in the discussion and for what it's worth I also agree that "by design" feels incorrect. The logic was that its design was purely to capture locals, which is technically true but I think it's way more likely they just weren't thinking about strict mode.

That said, I was arguing for `wontfix` so the result is the same and thus I didn't fight much. The change would be risky, and tbh it's one in a long list of inconsistencies with strict mode. Separate dialects (like strict mode) are notoriously difficult to maintain, especially when the dialect is less frequently used. My personal opinion is that strict mode was a mistake, a good example of why dialects are not ideal, and that we should not put more work into it.

I know it can be frustrating to get a negative response to a suggestion, especially when it doesn't appear to make sense. It's worth noting however that even for that response, there was 4-8 people on a call talking for at least 15 minutes debating the merits. We don't do a good enough job conveying the amount of effort that went into a decision, but it is a lot more than it appears.

**Comment by agowa** [comment] 2024-01-19 15:54
Tbh, strict mode should have been the default state, and the mistake was not making it the default state. Same for allowing automatic module imports for non unique function names (as well as encouraging AGAINST explicit imports declarations). However that ship is sailed.

A way to fix this issue without breaking existing code would by to bump the strict mode version and only then enforce it when Invoking "getnewclosure"-ed script blocks. That way it would throw an exception where expected, not break existing code, but probably cause some ugly code within the underlying ".Invoke" function within C# code to actually know and check for the strict mode and "on the fly" modify the strict mode within the provided script block, but not modules.

Also @SeeminglyScience just to clarify I wasn't "frustrating to get a negative response", that is fine. The issue was within the communication itself (and there in particular with the "auto close as resolved" without having a final answer through the bot). As the one in the original ticket left too many things open for interpretation (like if you actually talked about the entire problem or just "jep, GetnewClosure not including strict mode works as intended, and not noticing that it also hides the exception"). But anyway, thanks for taking time to explain this in more details. However, as "just wontfix" doesn't help anyone, can we at least settle at "acknowledged limitation that needs to be added to the docs" or something?

**Closed** 2024-01-20 17:37 UTC
Labels: Issue-Question, Resolution-Answered

**Comment by mklement0** [comment] 2024-01-20 17:58
@agowa, documenting the behavior sounds like a good idea:

* The SDK docs are notoriously terse - definitely in [this case](https://learn.microsoft.com/en-US/dotnet/api/System.Management.Automation.ScriptBlock.GetNewClosure) - because they are auto-generated from _comments in the source code_.
  * Thus, to add details would require a PR _here_.
  * Not sure what the policies are around that.

* A bit more detail can be found in [chapter 11](https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-11?view=powershell-7.4#118-closures) of the PowerShell language spec (which hasn't been updated since v3):
  * The `Open a documentation issue` link at the bottom of the page allows you to directly create an issue in the docs repo.
  * Again, I'm not sure if there are policies around updating the - clearly outdated - spec.
