### ISSUE TITLE
System locale | Strings translated in output 

### ISSUE THREAD

**Issue by Ricky-Tigg** [PowerShell/PowerShell#20038] opened 2023-07-28 12:16 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello. _Background_:
- OS  installed observing the system locale _fi-FI_.
- At this moment the active system locale as set in GUI is _en-GB_; Windows GUI displayed accordingly.
- Support for locale _fi-Fi_ attested in PowerShell hence the outputs whose strings were translated for it are shown accordingly (`(GET-WinSystemLocale).Name`).
```powershell
> GET-WinSystemLocale
LCID             Name             DisplayName
----             ----             -----------
1035             fi-FI            Finnish (Finland)
> Get-UICulture
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
> Get-Culture
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

### Expected behavior

```console
Output strings displayed according to source strings.

> whoami /priv
(...)
SeShutdownPrivilege           #text_as_source_string#                 Disabled
```

### Actual behavior

```console
Output strings displayed according to translated strings.

> whoami /priv
(...)
SeShutdownPrivilege           Järjestelmän sammuttaminen                 Disabled
```
```


### Error details

```console
_
```

### Environment data

```powershell
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_

**Comment by mklement0** [comment] 2023-07-28 12:28
As of this writing, PowerShell (Core) has not been localized (unlike Windows PowerShell).

Your issue is a duplicate of:

* #666

**Closed** 2023-07-28 13:01 UTC
Labels: Needs-Triage
