### ISSUE TITLE
Invoke-WebRequest switch SkipHttpErrorCheck is ignored on response code 407

### ISSUE THREAD

**Issue by HUMBERP** [PowerShell/PowerShell#16414] opened 2021-11-09 09:23 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In version 7.1.5 if calling Invoke-WebRequest i get a webresponse object if parameter -SkipHttpErrorCheck is set and the request leads to an error. With version 7.2.0 i get no response object instead an exception.

### Expected behavior

```console
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> $RequestUri
https://api.github.com/repos/PowerShell/PowerShell/releases/latest
PS C:\> Invoke-WebRequest -Uri $RequestUri -SkipHttpErrorCheck

StatusCode        : 407
StatusDescription : ProxyAuthenticationRequired
Content           : <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
                    <html><head>
                    <meta type="copyright" content="Copyright (C) 1996-2021 The Squid Software Foundation and contri…
RawContent        : HTTP/1.1 407 ProxyAuthenticationRequired
                    Server: squid
                    Mime-Version: 1.0
                    Date: Tue, 09 Nov 2021 09:15:10 GMT
                    X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
                    Proxy-Authenticate: Negotiate
                    Proxy-Authenti…
Headers           : {[Server, System.String[]], [Mime-Version, System.String[]], [Date, System.String[]],
                    [X-Squid-Error, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {@{outerHTML=<a href="https://api.github.com/*">https://api.github.com/*</a>; tagName=A;
                    href=https://api.github.com/*}, @{outerHTML=<a href="mailto:no-reply@domain.com?subject=CacheErrorInfo%
                    20-%20ERR_CACHE_ACCESS_DENIED&amp;body=CacheHost%3A%20ER0322F002.epit.cc%0D%0AErrPage%3A%20ERR_CACH
                    E_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Tue,%2009%20Nov%202021%2009%3A15%3A10%
                    20GMT%0D%0A%0D%0AClientIP%3A%2010.222.111.175%0D%0A%0D%0AHTTP%20Request%3A%0D%0ACONNECT%20%20HTTP%2
                    F1.1%0AUser-Agent%3A%20Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Microsoft%20Windows%2010.0.14393%3
                    B%20de-DE)%20PowerShell%2F7.1.5%0D%0AHost%3A%20api.github.com%3A443%0D%0A%0D%0A%0D%0A">cache
                    administrator</a>; tagName=A; href=mailto:no-reply@domain.com?subject=CacheErrorInfo%20-%20ERR_CACHE_AC
                    CESS_DENIED&amp;body=CacheHost%3A%20ER0322F002.epit.cc%0D%0AErrPage%3A%20ERR_CACHE_ACCESS_DENIED%0D
                    %0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Tue,%2009%20Nov%202021%2009%3A15%3A10%20GMT%0D%0A%0D%0AC
                    lientIP%3A%2010.222.111.175%0D%0A%0D%0AHTTP%20Request%3A%0D%0ACONNECT%20%20HTTP%2F1.1%0AUser-Agent%
                    3A%20Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Microsoft%20Windows%2010.0.14393%3B%20de-DE)%20Power
                    Shell%2F7.1.5%0D%0AHost%3A%20api.github.com%3A443%0D%0A%0D%0A%0D%0A}}
RawContentLength  : 147948
RelationLink      : {}


PS C:\>
```

### Actual behavior

```console
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> $RequestUri = 'https://api.github.com/repos/PowerShell/PowerShell/releases/latest'
PS C:\> Invoke-WebRequest -Uri $RequestUri -SkipHttpErrorCheck
Invoke-WebRequest: The proxy tunnel request to proxy 'http://proxyserver/' failed with status code '407'."
PS C:\>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2021-11-09 10:20
I guess it is how .Net now works. I am not sure whether we name this a regression.

**Comment by HUMBERP** [comment] 2021-11-09 10:26
From a PowerShell point of view, the Cmdlet behaves now completely different as before. For my purpose i rely on the webresponse object and use this extensively.
I think this should be fixed in the way the cmdlet works as before.

**Comment by iSazonov** [comment] 2021-11-09 11:31
The error reported is _proxy_ related. So first question is - is this .Net regression or it is by-design? If it is a regression it must be fixed in .Net.

**Comment by HUMBERP** [comment] 2021-11-09 11:59
I can't answer your question, because i'am just using powershell .

I tested a different case and SkipHttpErrorCheck is honored when the response got ErrorCode 401 (Cmdlet not used behind a proxy).
May be this helps to classify the issue correct.
I changed the title to be more precise.

**Comment by iSazonov** [comment] 2021-11-09 15:11
@HUMBERP Thanks! I found https://github.com/dotnet/runtime/issues/48679 This says the behavior is by-design. We can not change this because it is security related.

**Comment by HUMBERP** [comment] 2021-11-09 15:42
Ok, is there a suggestion how to get the statuscode?
If i catch the exception which is thrown, there is no field to see that it's StatusCode 407 ProxyAuthentication Required. To make a string search within the exception message seems to me error prone.

**Comment by iSazonov** [comment] 2021-11-09 15:50
I see it returns HttpRequestException with a status code. Get-Error should show you all fields.

**Comment by iSazonov** [comment] 2021-11-09 15:52
I wonder if you use a proxy why don't you set proxy credentials in the request?

**Comment by HUMBERP** [comment] 2021-11-09 16:07
After further investigation, for our regular process proxy credentials are always present and this should have no impact. 

It's more on a manual basis, when I use my own written cmdlets and there is an opportunity to make requests to the cloud or wihtin the internal network. The own cmdlets have the parameter for proxy and if given, everything works fine, but if I forget to pass the proxycredentials the cmdlet should just inform and not throw an exception ...
I updated powershell to 7.2.0 on some servers to see if there is no issue ...

Thank you for your support.

**Closed** 2021-11-11 00:00 UTC
Labels: Issue-Question, Resolution-Answered, WG-Cmdlets-Utility, Needs-Triage
