### ISSUE TITLE
PowerShell 6.2.1 invoke-webrequest completely ignores content-type

### ISSUE THREAD

**Issue by yar05** [PowerShell/PowerShell#10029] opened 2019-06-28 19:11 UTC
# Steps to reproduce

```powershell
Invoke-WebRequest -Uri "http://httpbin.org/headers" -ContentType 'application/json'
```

# Expected behavior

```json

                      "headers": {
                        "Content-Type": "application/json",
                        "Host": "httpbin.org",
                        "User-Agent": "Mozilla/5.0 (Windows NT; Windows NT 10.0; en-GB) WindowsPowerShell/5.1.18922.1000"
                      }
                    }

```

# Actual behavior

```json
{
                      "headers": {
                        "Host": "httpbin.org",
                        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.18922; en-GB) PowerShell/6.2.1"
                      }
                    }
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18922
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2019-06-28 19:14
duplicate of #9473

**Closed by markekraus** 2019-06-28 19:14 UTC
Labels: Issue-Question
