### ISSUE TITLE
`?.` operator treats `DBNull` as null causing the methods to not execute

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#11084] opened 2019-11-15 19:48 UTC
Since the implementation of `?.` operator treats DBNull, NullString and AutomationNull as null, we cannot call any method on them using `?.` operator. The concern is only for DBNull as for other types we truly consider them as null.

# Steps to reproduce

```powershell
[System.DBNull]::Value?.GetTypeCode()
```

# Expected behavior

```none
DBNull
```

# Actual behavior

```none
null
```

# Environment data

```none
Build after PR https://github.com/PowerShell/PowerShell/pull/10960 is merged
```

**Comment by vexx32** [comment] 2019-11-15 19:52
This will also affect `NullString.Value` -- if you are referencing `LanguagePrimitives.IsNullLike()` anywhere in the implementation of `?.` or `[]` you definitely want to switch to `LanguagePrimitives.IsNull()`

**Comment by rjmholt** [comment] 2019-11-15 23:32
Yes I think we either agree that `?.` uses `IsNullLike()`, in which case I think this is by design, or we use `IsNull()`, in which case there's a change to make.

**Comment by SteveL-MSFT** [comment] 2019-11-16 00:36
I feel we've already crossed this bridge once we decided awhile back that `[System.DBNull]::Value -eq $null` so usage expects it to act like it was `$null` (current design) otherwise it'll confuse users with the inconsistency.  They can always workaround this by not using this operator.

**Comment by iSazonov** [comment] 2020-01-31 11:25
@SteveL-MSFT Can we close the issue? It seems we revert PR for DBNull.

**Comment by iSazonov** [comment] 2021-01-15 18:55
@SteveL-MSFT Up

**Closed** 2023-11-23 12:08 UTC
Labels: Issue-Question, Resolution-No Activity
