### ISSUE TITLE
'Split-Path "/" -Leaf' returns empty string instead of "/" on Ubuntu1804/Linux/Wsl

### ISSUE THREAD

**Issue by SeidChr** [PowerShell/PowerShell#14393] opened 2020-12-11 09:32 UTC
## Steps to reproduce
On WSL Ubuntu 1804 or probably any other linux distro
```powershell
Split-Path "/" -Leaf
```

## Expected behavior
return a slash
```none
/
```

## Actual behavior
returns an empty string

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeidChr** [comment] 2020-12-11 09:33
on windows it returns a "C:\" which is correct imo

**Comment by mklement0** [comment] 2020-12-11 12:58
Agreed that returning `/` is the right thing to do on Unix-like platforms.

However, note that the Windows behavior is debatable, in that `Split-Path` seems to perform resolution _to a full path_ in this case (based on the current drive), which it otherwise doesn't do (by definition). That is, on Windows path `/` (`\`)  is _drive_-relative, and converting it to an absolute path based on the state of the session (current location) is not `Split-Path`'s mandate. In other words: it would make more sense to me if `\` were returned on Windows.

**Comment by SeidChr** [comment] 2020-12-11 21:41
True.

If you pass only a slash on windows, it should not resolve it to include a drive. 🤝🏼
When you pass the drive however, it should.

**Comment by mklement0** [comment] 2020-12-11 21:49
It's definitely an edge case, but I would expect `Split-Path C:\` to return just `\` also: The purpose of the `-Leaf` switch is to return only the leaf component, which in the case of a directory path is the  _directory name_, and the name of the root directory is just `\`, not including a drive spec.

**Comment by SeidChr** [comment] 2020-12-11 22:53
well I think that's subjective. 
for me it's just as logical to see the slash as a separator only. 
but I'm not the one to decide what exactly it should be.

the behavior should be logical and equal on any os. that's all I'm asking 😅

**Comment by mklement0** [comment] 2020-12-11 23:08
Agreed re having predictable behavior across platforms governed by an as-simple-as-possible rationale.

Even if you see the `\` as a separator, that doesn't make a _drive specification_ the leaf component.

Conceptually, the leaf component is unequivocally the _root directory_ in this case - sans drive, on Windows.

The challenge - which is as old as the hills and affects Unix-like platforms and Windows equally - is that the root directory has no name other than the path separator, which has given us decades of programmatically constructed paths such as `C:\\foo`, resulting from code such as `$path + '\' + $file`, where `$path` happens to be the root dir. This is presumably why both Unix and Windows accept such duplicated path separators.

**Comment by mklement0** [comment] 2020-12-12 02:55
Conversely, if we accept that the first `\` / `/` is a path separator _only_, you can make the argument that the root directory argument is the _empty string_, in which case `Split-Path -Leaf C:\` and `Split-Path -Leaf /` should return `''`.

While this works well when _building_ paths (e.g., `'' + '/' + 'foo'` to construct `/foo`), it is inherently _ambiguous_ in other contexts, as `Split-Path -Parent /foo` and `Split-Path -Parent foo` would then yield the same result, for instance - the empty string.

On balance, conceiving of the root directory name as `\` / `/` is the better choice.

**Comment by SeidChr** [comment] 2020-12-12 10:02
I guess every logic is manageable when hidden behind a well designed api. Which is why I use join-path and split-path extensively with the hopes, that it will just handle this for me on all platforms.

from my personal standpoint, paths that start with a separator are just an indication for them to be absolute and thus relative to the root directory, which has no name. so I would agree to your first point.
even the second part actually sounds fine to me.
passing only a single path segment to split-path and retrieving no parent and the segment as leaf seems just logical.
it basically means that an empty path '' just points to root. just as '/' or '\\'

resolving such a path would then result in a 'C:\\' or '/'

however, im not sure how I would handle a split-path on an 'C:\'. But I assume just returning 'C:' as parent and '' as leaf would just work fine

**Comment by mklement0** [comment] 2020-12-12 16:04
Just a terminology quibble:

> paths that start with a separator are just an indication for them to be _absolute_

* On Window, they are _rooted_ (`[IO.Path]::IsPathRoot()` returns `$true`), but _not absolute_ (`[IO.Path]::IsPathFullyQualified()` returns `$false`)

* On Unix, they are both rooted and absolute.

Using `Join-Path` and `Split-Path` is good practice: `Join-Path` avoids the `C:\\foo` problem (though `Split-Path` doesn't correct it).

However, another reason not to treat `''` as the root directory is that `Join-Path '' foo` simply fails.

Also, as stated, if you made `Split-Path /foo -Parent` return `''` (even though on Unix it currently does, but that's a variation of the bug at hand), you couldn't distinguish it from `Split-Path foo -Parent` - at least not without introducing a serious breaking change (such as to return `.` in the latter case).

Similarly, for consistency, you'd have to then allow `Get-ChildItem ''` to list the _root_ directory, whereas it currently lists the _current_ one.

In short: It is generally problematic to refer to a _specific_ something (the root dir.) with nothing (the empty string), and using `\`/ `/` as the name of the root dir. is the best compromise.

As for how `Split-Path C:\ -<switch>` _should_ be handled:

* `Split-Path C:\ -Leaf`  on Windows and `Split-Path / -Leaf` on Unix should return the _name of the root dir_, and therefore `\` an `/`, respectively

    * On Windows, it currently returns `C:\`, which strikes me as incorrect - but fixing it would be a breaking change.

    * On Unix - which is the bug at hand - it returns `''` (which by the (to me ill-advised) logic of considering `''` the root dir.'s name would actually be correct). 

* `Split-Path C:\ -Parent`  on Windows and `Split-Path / -Parent` on Unix  are tricky:

   * The root directory by definition has no parent, and `[IO.Path]::GetDirectoryName()` indicates this by returning `$null` - as opposed to the `''` returned for something like `[IO.Path]::GetDirectoryName('foo')`

   * This is too subtle a distinction for PowerShell, where `[string]` values usually do not contain`$null`:
       * On Windows , `Split-Path C:\ -Parent` currently returns `''` - changing that would be a breaking change.
       * On Unix, `Split-Path / -Parent` is currently _broken_, as you reported in #14392, which is a duplicate of #10092; for consistency, absent a breaking change, it should also return `''`.

      * The upshot is that if you call `Split-Path -Parent $path`  on an unknown path `$path` and get `''` back, you'll need further investigation (`[IO.Path]::IsPathRooted()`) to infer whether `$path` refers to the root dir. (with or without a drive spec.) or is a mere file or directory name such as `foo`.
        * Note that `Split-Path -IsAbsolute` isn't suitable for this distinction, because `Split-Path \ -IsAbsolute` is `$false` on Windows.
        * As an aside: It is `Test-Path` that should have this switch - it never made sense on `Split-Path`. Also, to handle the distinction between a rooted and an absolute (fully qualified) path, an `-IsRooted` switch should be added.

**Comment by SeidChr** [comment] 2020-12-12 20:53
Don't get me wrong. I agree to you on how this should be handled.
I was just giving a different point of view. Doesn't mean it was the proposed way to fix it.

**Closed** 2023-11-23 11:23 UTC
Labels: Issue-Question, WG-Cmdlets-Management, WG-Engine-Providers, Area-FileSystem-Provider, Resolution-No Activity
