### ISSUE TITLE
PS Get-ChildItem -Exclude still not working as described

### ISSUE THREAD

**Issue by AlfiCode** [PowerShell/PowerShell#15270] opened 2021-04-19 12:18 UTC
## Steps to reproduce

```powershell
[System.IO.FileInfo[]]$Files=Get-ChildItem -Path $RootDir -Include  "packages.config" -Exclude "out" -Recurse -Force

Search for specific files and exclude one directory eg. -Exclude "out".
A file with the name in -Include "packages.config" is also listed even from dir "out"
```

## Expected behavior
The file under "out"-out shall not be listed

```

## Actual behavior
The file under "out"-dir is listed

```

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment] 2021-04-19 16:40
Perhaps surprisingly, this is not how `-Exclude` works: it does _not_ exclude entire directory _subtrees_.

Instead, the exclusion pattern is applied _at every level of the subtree hierarchy_.

`-Exclude out` therefore means directories named `out` are _themselves_ omitted from the output (as `[System.IO.DirectoryInfo]` instances), _their content_ is not (unless items there also match the pattern).

#15159  suggests adding a _new parameter_ for subtree exclusion.

**Comment by AlfiCode** [comment] 2021-04-19 16:48
Thanks, any proposal would be fine for me but how could we get it in one of the next releases?
Is their any possibility to vote for?

**Comment by mklement0** [comment] 2021-04-19 17:00
You can give the proposal a thumbs-up. In the aggregate, I would expect the number of such votes to matter.

Additionally, if you have a compelling use case to share, I encourage you to leave a comment there.

Eventually, the assigned [working group](https://github.com/PowerShell/PowerShell/pull/14603) (`WG-Engine-Providers`) will take a look at the suggestion, but I don't think there's a guaranteed time frame.

**Comment by daxian-dbw** [comment] 2021-05-04 23:07
@AlfiCode I will close this issue as a duplicate of #15159. Please go ahead and up vote that issue.

**Closed by daxian-dbw** 2021-05-04 23:07 UTC
Labels: Needs-Triage
