### ISSUE TITLE
Random Unhandled Exception after using ipconfig /all

### ISSUE THREAD

**Issue by Jo-Jo-Mojo** [PowerShell/PowerShell#24044] opened 2024-07-11 07:19 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am not an expert in PowerShell, programming, scripting, or even GitHub itself, so please excuse any inaccuracies in my formatting of this report.

I was simply trying to diagnose an internet issue by using ipconfig /all, when out of nowhere this "unhandled exception" comes flying in and closes my elevated PowerShell window shortly thereafter. I believe that my internet issue was/is some parental control type s*** if that helps. The thing that may be the most important is that my PC still believed that it had a complete internet connection (wired btw), but was just unable to access anything through the internet. Please note that after switching from a wired connection to a wireless connection (using Window's built-in Random Hardware Address feature to bypass the perceived restrictions), the internet access is restored and the PowerShell error does not occur. The error also did not occur in the built-in version of PowerShell on Windows 10 Pro. I did not test to see if the error occurs by simply opening an elevated PowerShell window and leaving it there (I just realized the ipconfig /all could possibly be irrelevant).

This is no emergency, as I am running fine now, but I really just wanted to bring this to your attention so that people can use this more advanced version of PowerShell to troubleshoot issues like the one I faced, as well as others.

### Expected behavior

```console
Nothing, as no commands were being entered or were processing. The ipconfig /all had successfully completed.
```

### Actual behavior

```console
An unhandled exception appears, and PowerShell closes soon after. See image.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image_2024-07-11_023138954](https://github.com/PowerShell/PowerShell/assets/175287398/c16a479d-8a09-4bb6-b1d5-a892940b17dd)

**Comment by jborean93** [comment] 2024-07-11 08:03
This looks to be a duplicate of https://github.com/PowerShell/PowerShell/issues/23877, https://github.com/PowerShell/PowerShell/issues/23998, https://github.com/PowerShell/PowerShell/issues/23885 which is caused by a provider installed with powertools related to winget.

While the issue is unrelated to this repo potentially the pwsh team should keep this issue open as a feedback provider shouldn’t be crashing the shell like this. Potentially there’s some improvements to be made in how feedback providers work.

**Comment by RokeJulianLockhart** [comment] 2024-07-15 19:51
> https://github.com/PowerShell/PowerShell/issues/24044#issuecomment-2222291119

@jborean93, I agree, but it's probably better to create a separate issue with a description and title of a larger scope, then.

**Comment by daxian-dbw** [comment] 2024-08-09 18:04
It looks the issue was already fixed in the [winget-command-not-found](https://github.com/microsoft/winget-command-not-found) repo via https://github.com/microsoft/winget-command-not-found/issues/9

**Closed by daxian-dbw** 2024-08-09 18:04 UTC
Labels: Needs-Triage
