### ISSUE TITLE
ConvertFrom-Json converts an JSON object with key "clone:" to  System.Management.Automation.PSMethod

### ISSUE THREAD

**Issue by mobil11** [PowerShell/PowerShell#24233] opened 2024-08-30 09:48 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

C:\Users\me> $json = @"
>>  {
>>     "records": [
>>       {
>>         "clone":
>>          {
>>           "something": false
>>         },
>>       }
>>     ]
>> }
>> "@
C:\Users\me> $convertedObject = $json | ConvertFrom-Json
C:\Users\me> $convertedObject.records.clone

OverloadDefinitions
-------------------
System.Object Clone()
System.Object ICloneable.Clone()

C:\Users\me> $convertedObject.records.clone.gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    PSMethod`1                               System.Management.Automation.PSMethod

### Expected behavior

```console
C:\Users> $convertedObject.records.clone.gettype() | ft

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    PSMethod`1                               System.Management.Automation.PSMethod

C:\Users>
C:\Users> $json = @"
>>  {
>>     "records": [
>>       {
>>         "notclone":
>>          {
>>           "something": false
>>         },
>>       }
>>     ]
>> }
>> "@
C:\Users> $convertedObject = $json | ConvertFrom-Json
C:\Users> $convertedObject.records.notclone

something
---------
    False

C:\Users> $convertedObject.records.notclone.gettype() | ft

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object
```

### Actual behavior

```console
see below
```

### Error details

```console
C:\Users\me> $convertedObject.records.clone

OverloadDefinitions
-------------------
System.Object Clone()
System.Object ICloneable.Clone()


C:\Users\me> $convertedObject.records.clone.gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    PSMethod`1                               System.Management.Automation.PSMethod
```

### Environment data

```powershell
C:\Users> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment] 2024-08-30 10:58
ConvertFrom-Json is working, the problem is a clash names. The following sees the clone property, and shows it being round-tripped with ConvertTo-Json

```
$json = @"
{
   "records": [
   {
       "clone":
       {
           "something": false
       }
    }
    ]
}
"@
$convertedObject = $json | ConvertFrom-Json -Depth 5

$convertedObject.records | Select-Object -Property 'clone'

$convertedObject | ConvertTo-JSON -Depth 10

```

**Comment by mklement0** [comment] 2024-08-30 11:06
* `$o.records` contains an _array_ (`[object[]]`), which itself has no `clone` property, but has a `Clone` _method_.

* When you access a method member _without parentheses (`(...)`)_, PowerShell by design prints the method _overloads_ (signatures), which is what you're seeing.

* To see the `clone` property value of the _first array element_ in `$o.records`, use `$o.records[0].clone`

Note that if you wanted to extract the `clone` property values across _multiple_ array elements,  [member-access enumeration](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration) is _not_ an option in this case, because the type-native member (the `.Clone()` method in this case) takes precedence.

You can work around this via the [intrinsic `.ForEach()` method](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Arrays#foreach): `$o.records.ForEach('clone')`

**Comment by mobil11** [comment] 2024-08-30 14:12
The problem for me, as a "normal" PowerShell user is, that I had no clue, that some words in a JSON file or a REST API respond, that are the same as a method name, triggers this method. And I think most of the Powershell users are not aware of this, for me, strange behavior.

**Comment by kilasuit** [comment] 2024-08-30 21:29
To most users they would be aware of this ad this is expected behaviour, even if it may not seem like it should be. Now you know it, it's hopefully no longer strange 🙂

I try and recommend PowerShell users (new and long time users) to read through the documentation available on https://learn.microsoft.com/en-us/powershell/ & come back and re-read it from time to time too. 

The following articles are useful which each also have additional articles to read too.
 
about_objects
about_members
about_properties
Get-Command
Get-Help
Get-Module
Get-Member
Select-Object

As this is expected behaviour I am closing this issue as by design

**Closed by kilasuit** 2024-08-30 21:29 UTC
Labels: Resolution-By Design
