### ISSUE TITLE
ValueFromPipelineByPropertyValue not working for Select-String's -LiteralPath parameter

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17188] opened 2022-04-24 16:03 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Binding full file-system item paths to `Select-String`'s `-LiteralPath` parameter (via its alias name, `-PSPath`) based in input objects' `.PSPath` property values works via provider-decorated `System.IO.FileInfo` instances, such as `Get-ChildItem`, but not with `[pscustomobject]` instances, for example:

```powershell
'zzz' > ($tmpFile = New-TemporaryFile) # Create temp. file with sample content.

$o = [pscustomobject] @{ PSPath = $tmpFile.FullName }

# OK: Get-Content binds the .PSPath property to -LiteralPath, as expected.
$o | Get-Content

# !! BROKEN: Select-String doesn't bind to -LiteralPath and instead searches the
# !!                  stringified object.
$o | Select-String .

Remove-Item $tmpFile # cleanup
```

### Expected behavior

```console
zzz

/path/to/tmpfile.tmp:1:zzz
```

### Actual behavior

```console
zzz

@{PSPath=/path/to/tmpfile.tmp}
```

That is, `Select-String` unexpectedly searched the `.ToString()` representation of the input object that was bound to `-InputObject`.

### Environment data

```powershell
PowerShell Core 7.3.0-preview.3
```

**Comment by vexx32** [comment] 2022-04-24 21:17
Interestingly Select-String _does_ appear to have the correct `PSPath` alias defined for its `LiteralPath` parameter. I'm unsure what would cause this, in that case, perhaps a bug in the parameter binder?

**Comment by SeeminglyScience** [comment] 2022-04-25 19:26
I'm thinking it's the argument transformation attribute. Curious how that interacts with `ValueFromPipelineByPropertyName`.

**Comment by jhoneill** [comment] 2022-04-26 02:45
> I'm thinking it's the argument transformation attribute. 
I'd put money on that.  Specifically I'd bet that it transforms the path of a FileInfo object but an identical member of (in this case) a PSCustom object. And if the object just goes through a normal string conversion you'd get the reported string.

**Comment by SeeminglyScience** [comment] 2022-04-26 03:30
Yes I suspect that as well. Should be fixed in `Select-String` either way you slice it.

That said, still should be left open to engine to decide if that's the correct order for parameter binding. Should argument transformation overtake `ValueFromPipelineByPropertyName` completely? Or should the property value be passed to the transformation attribute.

**Comment by jhoneill** [comment] 2022-04-26 14:50
> Yes I suspect that as well. Should be fixed in `Select-String` either way you slice it.
> 
> That said, still should be left open to engine to decide if that's the correct order for parameter binding. Should argument transformation overtake `ValueFromPipelineByPropertyName` completely? Or should the property value be passed to the transformation attribute.

Agree on the first part.  On the second I think the order should go, 

- Get the value from the parameter or the Pipeline
- Then apply any transformation
- Finally apply any validation

and it probably does already, because anything that means some input _is_ successfully transformed when supplied as a command line argument but _isn't_ when it comes down the pipeline appears perverse, which was I think was the original point :-)  Here we think the point is the transformer is badly written rather than a problem with the order. If the transformer is used in other cmdlets there may be other cases waiting to be discovered.

**Comment by SeeminglyScience** [comment] 2022-05-27 15:25
The engine WG discussed this yesterday. We're marking this issue as up for grabs *specifically* for fixing the argument transformation attribute. If the `FileInfo` type check fails but it is a `PSObject` it should simply check for the property.

On the subject of changing how `ArgumentTransformationAttribute` works, we feel there is a lot of risk in changing it's current behavior, and could very easily break any folks who have already worked around it. A change to it's behavior would not be accepted.

**Comment by iSazonov** [comment] 2022-05-28 05:58
There `FileinfoToStringAttribute` attribute works and it returns unchaged `inputData` if it is not `FileInfo`. This returns us at start position - how `ValueFromPipelineByPropertyValue` interacts with `PSPath` alias processing. Also perhaps  a root of the issue is that `LiteralPath` has `string[]` array (not singleton) type while `PSPath` is a singleton.

**Closed** 2023-11-22 11:02 UTC
Labels: Issue-Bug, Up-for-Grabs, WG-Engine-ParameterBinder, Resolution-No Activity
