### ISSUE TITLE
Get-ChildItem -Recurse searches EVERYTHING when the -Path doesn't exist.

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#6637] opened 2018-04-12 17:09 UTC
Steps to reproduce
------------------

```powershell
Set-Location C:\
Get-ChildItem -Path "C:\Nonexistent\Path\v-1" -Recurse
```

Expected behavior
-----------------

```none
System.IO.DirectoryNotFoundException - The specified path could not be found.
```

Actual behavior
---------------

```none
get-childitem : Access to the path 'C:\inetpub\history' is denied.
At line:1 char:1
+ get-childitem c:\nonexist -r
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\inetpub\history:String) [Get-ChildItem], UnauthorizedAccessException
+ FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

get-childitem : Access to the path 'C:\inetpub\temp\appPools' is denied.
At line:1 char:1
+ get-childitem c:\nonexist -r
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\inetpub\temp\appPools:String) [Get-ChildItem], UnauthorizedAccessException
+ FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

# Several AccessDenied errors for folders that were located elsewhere, and a lengthy search for something that doesn't exist, through (seemingly) every folder on the hard disk.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This is some pretty odd behaviour when it should (probably) stop as soon as it realises the specified path doesn't exist at all. Does *not* happen without `-Recurse` being specified.

Issue is also present in Windows PowerShell 5.1.

**Comment by SteveL-MSFT** [comment] 2018-04-12 17:26
Duplicate of https://github.com/PowerShell/PowerShell/issues/5699

**Closed by SteveL-MSFT** 2018-04-12 17:26 UTC
Labels: Resolution-Duplicate
