### ISSUE TITLE
[Feature] Implement `Test-Command` cmdlet

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#8755] opened 2019-01-27 00:57 UTC
# Summary

A `Test-Command` cmdlet should be implemented to test whether or not a specified command can be found.

# Context

As per issue #7562, more `Test-` cmdlets should be implemented, specifically `Test-Command` and `Test-Module`, as this functionality is desired both generally and for use in the PowerShell tests and build module.

# Examples

```
PS C:\> Test-Command -Name pwsh -CommandType Application
True
```

```
PS C:\> Test-Command -Name doesnotexist -CommandType All
False
```

```
PS C:\> Test-Command -Name Get-NonexistentFeature, Get-Help -CommandType Cmdlet
False
True
```

# Syntax

```
Test-Command [-Name] <string[]> [-CommandType <CommandTypes>] [<CommonParameters>]
```

**Comment by xtqqczze** [comment] 2019-01-27 00:57
Get-Command [[-Name] <string[]>] [[-ArgumentList] <Object[]>] [-Module <string[]>] [-FullyQualifiedModule <ModuleSpecification[]>] [-CommandType <CommandTypes>] [-TotalCount <int>] [-Syntax] [-ShowCommandInfo] [-All] [-ListImported] [-ParameterName <string[]>] [-ParameterType <PSTypeName[]>] [<CommonParameters>]

**Comment by xtqqczze** [comment] 2019-01-28 17:58
@iSazonov A common pattern is to use the `Get-Command` cmdlet with the `ErrorAction` parameter set to `SilentlyContinue`, although this hides all errors:
```powershell
[bool](Get-Command -Name git -CommandType Application -ErrorAction SilentlyContinue)
```
Alternatively, the specific exception can be caught:
```powershell
try {
    [bool](Get-Command -Name git -CommandType Application -ErrorAction Stop)
}
catch [System.Management.Automation.CommandNotFoundException] {
    $false
}
```

**Comment by iSazonov** [comment] 2019-02-02 16:03
@SteveL-MSFT My suggestion is to close as Won't-Fix - what is your conclusion?

**Comment by SteveL-MSFT** [comment] 2019-02-06 04:53
@iSazonov well, if you look at the original linked issue https://github.com/PowerShell/PowerShell/issues/7562, I opened it :)

The discussion in the @PowerShell/powershell-committee on a different topic acknowledged that PowerShell should have had more `Test-*` cmdlets rather than having scripts rely on `Get-*` with error handling and checking against `$null`.  Also, with more `Test-*` cmdlets, it would make it feasible to use cmdlets directly as DSC resources (Get/Set/Test).  It's unlikely the PowerShell team would spend the time implementing this.  However, this specific cmdlet should be relatively easy and straightforward and would encourage the community to pick it up.

**Comment by iSazonov** [comment] 2019-02-06 06:12
@SteveL-MSFT Thanks for remainder! So the issue is a duplicate and we can track in #7562.

**Comment by JamesWTruher** [comment] 2021-06-01 19:27
duplicate of #7562, this is a great discussion with some good detail. We'll refer to it from #7562 when it's time for implementation.

**Closed by JamesWTruher** 2021-06-01 19:27 UTC
Labels: Issue-Enhancement
