### ISSUE TITLE
Connect-SPOService : Could not connect to SharePoint Online. At line:4 char:1

### ISSUE THREAD

**Issue by PKHEDE** [PowerShell/PowerShell#15460] opened 2021-05-26 12:11 UTC
## Steps to reproduce

```powershell

```

## Expected behavior

Successful connection to SPOservice

## Actual behavior

```
"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --disable-gpu --disable-gpu-compositing

Connect-SPOService : Could not connect to SharePoint Online.
At line:4 char:1
+ Connect-SPOService -Url $AdminUrl -credential $SPOServiceCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-SPOService], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Online.SharePoint.PowerShell 
   .ConnectSPOService

```

## Environment data

```
Name             : Windows PowerShell ISE Host
Version          : 5.1.14409.1018
InstanceId       : f509a0d6-6c10-42ef-8dc1-6721187ca6e9
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.Host.ISE.ISEOptions
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


```

**Comment by vexx32** [comment] 2021-05-26 14:09
@PKHEDE I'm not able to determine what exactly you're trying to do here. Please fill out the issue template, especially the steps to reproduce and the expected/actual behaviour, so we can properly triage this and help you out. 🙁

**Comment by rjmholt** [comment] 2021-05-26 15:08
From the output of `$PSVersionTable`, this seems to be occurring in Windows PowerShell in the ISE, so likely out of scope for this repo.

**Comment by PKHEDE** [comment] 2021-05-26 15:21
Any Idea where should I seek help, My automation is badly impacted.

**Comment by rjmholt** [comment] 2021-05-26 19:01
Looks like this is part of the [SharePointOnlinePowerShell module](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice). There's a feedback link at the bottom of that page.

The PowerShell docs also have some [links to community resources](https://docs.microsoft.com/en-us/powershell/#community-resources) where you might be able to find more immediate help. The Discord group in particular is very active.

Also, some users in the past have gotten support for modules like this through their Microsoft Support partners I think (but that's not something I know much about I'm afraid).

**Closed** 2022-05-18 00:01 UTC
Labels: Resolution-Answered
