### ISSUE TITLE
Unable to Add-Type when hosting with Microsoft.PowerShell.SDK NuGet package

### ISSUE THREAD

**Issue by normj** [PowerShell/PowerShell#7739] opened 2018-09-07 22:59 UTC
Steps to reproduce
------------------

When I run the following C# .NET Core 2.1 code which hosts the PowerShell runtime the new type fails to be created. In my example I'm trying to create a .NET exception class to throw but I get the same error for any type I try to add via the hosting package.

```csharp
using System;

using System.Management.Automation;

namespace PSHostAddTypes
{
    class Program
    {
        const string SCRIPT =
@"
$exceptionSource = @""
public class MyException : System.Exception
        {
            public MyException() : base(""Test"")
            {

            }
        }
""@

Add-Type -TypeDefinition $exceptionSource -ErrorAction Stop
$exception = New-Object MyException
throw $exception
";
        static void Main(string[] args)
        {
            var ps = PowerShell.Create();

            EventHandler<DataAddingEventArgs> handler = (sender, e) =>
            {
                Console.WriteLine(e?.ItemAdded?.ToString());
            };

            ps.Streams.Verbose.DataAdding += handler;
            ps.Streams.Information.DataAdding += handler;
            ps.Streams.Warning.DataAdding += handler;
            ps.Streams.Error.DataAdding += handler;

            ps.AddScript(SCRIPT);
            var result = ps.BeginInvoke();
            result.AsyncWaitHandle.WaitOne();

            if (ps.InvocationStateInfo.State == PSInvocationState.Failed)
            {
                Console.WriteLine(ps.InvocationStateInfo.Reason.Message);
            }
        }
    }
}
```

Expected behavior
-----------------

The new exception type is created.

Actual behavior
---------------

I get the following error in either 6.0.4 or 6.1.0-rc.1. The script does work correctly from a PowerShell Core shell.

```
Could not find a part of the path 'C:\Users\normj\.nuget\packages\system.management.automation\6.1.0-rc.1\runtimes\win-x64\lib\netstandard2.0\ref'.
Cannot find type [MyException]: verify that the assembly containing this type is loaded.
```

Environment data
----------------

I'm hosting PowerShell Core using Microsoft.PowerShell.SDK in a .NET Core 2.1 console application. The error has reproduced on Windows and Linux.

**Comment by iSazonov** [comment] 2018-09-10 05:41
@normj Could you output full `ps.InvocationStateInfo.Reason` ?

**Comment by LunicLynx** [comment] 2019-06-12 12:27
Solution i found was to copy the `ref` directory from the powershell installation, to the path that does not exist. 

`C:\Program Files\PowerShell\6\ref`

There should be a better solution i guess.

**Comment by iSazonov** [comment] 2019-06-13 04:26
@LunicLynx Thanks!  
This seems to be a known problem.
/cc @adityapatwardhan @SteveL-MSFT @daxian-dbw

**Comment by daxian-dbw** [comment] 2019-06-13 15:51
This is a duplicate of #9587. I'm closing this in favor of the existing issue.

**Closed by daxian-dbw** 2019-06-13 15:51 UTC
Labels: Area-Build
