### ISSUE TITLE
-replace does something .replace() will not

### ISSUE THREAD

**Issue by B-Art** [PowerShell/PowerShell#7621] opened 2018-08-23 15:45 UTC
Steps to reproduce
------------------

```powershell
$str1='<a href="/bla/string">string</a>'
$str2=$1str -replace '<[^>]+>',''
$str3=$1str.replace('<[^>]+>','')
```

Expected behavior
-----------------
```none
$str2='string'
$str3='string'
```

Actual behavior
---------------

```none
$str2='string'
$str3='<a href="/bla/string">string</a>'
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.2430
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2430
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by PetSerAl** [comment] 2018-08-23 15:56
`-replace` do regular expression replacement by default.

**Comment by BrucePay** [comment] 2018-08-23 15:56
@B-Art `[string].Replace()` just does simple string replacement. The `-replace` operator uses regular expressions like `[regex]::replace()`.

**Comment by chuanjiao10** [comment] 2018-08-23 17:36
It's by design . beginner Question .
This is where the powershell is fascinating. 
If you want to support the regularity，use  -replace
If you not like regularity,use  .replace().
Don't forget to close the issue.

**Comment by vexx32** [comment] 2018-08-23 17:47
If any more clarity is required...

* `.Replace()` is a string method build into the `[string]` data type by the .NET designers.
* `-replace` is a string operator implemented by the PowerShell team utilising the `[RegEx]::Replace()` .NET method behind the scenes in order to give additional, easy to access functionality to PowerShell itself.

**Closed** 2018-08-28 13:53 UTC
Labels: Area-Language, Issue-Question, Resolution-Answered

**Comment by B-Art** [comment] 2018-08-30 20:38
Thanks for all your answers!

**Comment by BrucePay** [comment] 2018-09-01 20:30
@B-Art Are you ok if we close this issue? Thanks.
