### ISSUE TITLE
Scoop Complete does not work after installing powershell 7.4 or later versions

### ISSUE THREAD

**Issue by nahid6970** [PowerShell/PowerShell#21069] opened 2024-01-14 09:31 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

https://github.com/Moeologist/scoop-completion
here is the scoop package that i installed and after installing it should auto complete the package like 
scoop install rcl and click ctrl+ space and it will find the available package and show suggestion but  after installing pwsh 7.4 or later its not working  its also happening to my other pcs or laptops

Also here are some people discussing the same issue about it
https://github.com/Moeologist/scoop-completion/issues/35

### Expected behavior

```console
when i typle scoop install and then some random character and and then click ctrl + space it should show some suggestion of application list and i can select. Also this is not scoop autocomplete proble its pwsh problem and i tried it on many hardwaare and its always same its just doesnt work after version 7.4 or later . it will only work below 7.4
```

### Actual behavior

```console
not working
```

### Environment data

```powershell
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2024-01-14 17:45
See also:

* #20930

**Comment by nahid6970** [comment] 2024-01-16 05:58
so i guess pwsh developer wont fix it neither the scoop developer??

**Comment by mklement0** [comment] 2024-01-18 00:05
Please see https://github.com/PowerShell/PowerShell/issues/20930#issuecomment-1897472499

**Comment by StevenBucher98** [comment] 2024-01-19 21:48
Closing as this is a duplicate of https://github.com/PowerShell/PowerShell/issues/20930.

**Closed** 2024-01-21 00:20 UTC
Labels: Resolution-Duplicate
