### ISSUE TITLE
Appx module no longer imports in Powershell Core

### ISSUE THREAD

**Issue by jfro** [PowerShell/PowerShell#14057] opened 2020-11-12 13:45 UTC
## Steps to reproduce

```powershell
Import-Module Appx
```

## Expected behavior
Successfully imports & can run Add-AppxPackage etc. This worked in 7.0.3, but now forces me to switch to Windows Powershell for some scripts.

## Actual behavior

```none
Import-Module: Operation is not supported on this platform. (0x80131539)
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment] 2020-11-12 13:51
The APPX module can be loaded like this:

```powershell
Import-Module -Name Appx -UseWIndowsPowershell
```

**Comment by doctordns** [comment] 2020-11-12 13:51
and should the deny list be updated???

**Comment by fMichaleczek** [comment] 2020-11-12 13:54
dupe of https://github.com/PowerShell/PowerShell/issues/13138

**Closed** 2020-11-13 17:00 UTC
Labels: Issue-Question, Resolution-Duplicate

**Comment by samus-a** [comment] 2021-11-22 02:46
> The APPX module can be loaded like this:
> 
> ```powershell
> Import-Module -Name Appx -UseWIndowsPowershell
> ```

PowerShell 7.2 (Windows 11):

PS > Import-Module -Name Appx -UseWIndowsPowershell
WARNING: Module Appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.

**Comment by doctordns** [comment] 2021-11-22 11:07
@samus-a - that is the (currently) expected result. The impact is that all objects returned by the cmdlets in the module are serialised (and lose all their methods). And no object formatting XML is imported.

**Comment by samus-a** [comment] 2021-11-22 11:20
@doctordns Ok thanks, so no reason to bother with the -SkipEditionCheck flag?

**Comment by doctordns** [comment] 2021-11-22 16:27
Unless you really know what you are doing - no. This module is not compatible with .NET 6 but runs so I believe, using the compatibility mechanism. In theory, this module _should_ be loaded that way by default but isn't.
