### ISSUE TITLE
Outputing Exceptions is not honoring no_color and leaves red color on

### ISSUE THREAD

**Issue by simonsabin** [PowerShell/PowerShell#18050] opened 2022-09-07 13:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

either run in powershell
```
$env:no_color="on";pwsh  -noninteractive -Command "$errorview='NormalView';throw 'an Error'"
```
or run this in a command prompt
```
set no_color=on&pwsh  -noninteractive -Command "$errorview='NormalView';throw 'an Error'"
```

### Expected behavior

```console
Error is output but in the consoles forecolor
```

### Actual behavior

```console
Error is output in red AND the console prompt stays in red
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/1209963/188887945-b06a6800-075c-4866-a3eb-c18771af828a.png)

**Comment by simonsabin** [comment] 2022-09-07 13:18
Related to https://github.com/PowerShell/PowerShell/issues/16643 in trying to get powershell to not output ANY ansi escape characters.

**Comment by jhoneill** [comment] 2022-09-07 14:24
The red in error isn't done with ANSI , see below for the issue and what's being done. 
https://github.com/PowerShell/PowerShell/issues/17886#issuecomment-1229015174 

Hopefully when it is done with ANSI then it will honour no_color etc.  (AIUI no color only applies to ansi, not `Write-Host -Foregound ... ` and error is currently doing the equivalent of that.)

**Comment by simonsabin** [comment] 2022-09-07 15:00
Duplicate of https://github.com/PowerShell/PowerShell/issues/17886

**Comment by simonsabin** [comment] 2022-09-07 16:04
> The red in error isn't done with ANSI , see below for the issue and what's being done.

Looking at this, not sure this fixes exceptions occuring when pwsh runs such as incorrect script passed to -Command, given PsStyle won't have been set.

**Comment by daxian-dbw** [comment] 2022-09-08 00:43
This is a duplicate of https://github.com/PowerShell/PowerShell/issues/17885, which was fixed.

**Closed by daxian-dbw** 2022-09-08 00:43 UTC
