### ISSUE TITLE
[System.Tuple] cannot be destructured

### ISSUE THREAD

**Issue by dkaszews** [PowerShell/PowerShell#19913] opened 2023-07-09 19:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`[System.Tuple]` cannot be destructured into its component items like `[Object[]]` can, despite it supporting indexing operator. This makes it a hassle to work with functions returning tuples, which are common in C# and preferable to returning an untyped array. Trying to destructure it just leads to assigning it to first variable, leaving rest `$null`.

```powershell

function Test-Destructure($a) {
    Write-Host "Type: $($a.GetType().Name)"
    Write-Host "a[0]: $($a[0])"
    Write-Host "a[1]: $($a[1])"
    ($x, $y) = $a
    Write-Host "x: $x"
    Write-Host "y: $y"
}

Test-Destructure (1, 2)
Test-Destructure ([System.Tuple]::Create(1, 2))
```

### Expected behavior

```console
> Test-Destructure (1, 2)
Type: Object[]
a[0]: 1
a[1]: 2
x: 1
y: 2

> Test-Destructure ([System.Tuple]::Create(1, 2))
Type: Tuple`2
a[0]: 1
a[1]: 2
x: 1
y: 2
```

### Actual behavior

```console
> Test-Destructure (1, 2)
Type: Object[]
a[0]: 1
a[1]: 2
x: 1
y: 2

> Test-Destructure ([System.Tuple]::Create(1, 2))
Type: Tuple`2
a[0]: 1
a[1]: 2
x: (1, 2)
y:
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Ubuntu 22.04.2 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment] 2023-07-09 21:02
Duplicate of #7471

**Comment by SeeminglyScience** [comment] 2023-07-09 21:03
Thanks for the report! Tracking the issue above (I've marked it as Needs-Triage so it'll actually make it to a WG)

**Comment by dkaszews** [comment] 2023-07-10 05:43
@SeeminglyScience thanks, I searched for such issue but could not find anything due to slight differences in wording 🙄

**Comment by SeeminglyScience** [comment] 2023-07-10 14:20
Oh yeah no worries, plus it made me realize the other issue wasn't being tracked properly 😁 

But I'd *always* rather have a duplicate issue than none at all so absolutely no worries!

**Closed** 2023-07-11 17:00 UTC
Labels: Resolution-Duplicate, Issue-Enhancement
