### ISSUE TITLE
$env:PSModulePath is not updated if you change the location of the document folder

### ISSUE THREAD

**Issue by chantisnake** [PowerShell/PowerShell#2968] opened 2017-01-06 17:44 UTC
Steps to reproduce
------------------
change the location of your document folder by right click `document` folder select `property` and then got to `location` tab, to change the location
and then input `$env:PSModulePath` the variable still points to you original document folder

Expected behavior
-----------------
For powershell 5.1 the `PSModulePath` variable change with the location of the documents folder:
![capture](https://cloud.githubusercontent.com/assets/10100995/21727072/60eb1582-d437-11e6-9ac4-0767542e7829.PNG)

Actual behavior
---------------
on powershell core, `PSModulePath` will point to `~/Documents` regardless of the location of the document folder
![capture](https://cloud.githubusercontent.com/assets/10100995/21727112/900d6b9e-d437-11e6-8fad-707afbd54f43.PNG)

Environment data
----------------

```powershell
> $PSVersionTable
PS C:\Users\zcsxo> $PSVersionTable                      
                                                        
Name                           Value                    
----                           -----                    
CLRVersion                                              
BuildVersion                   3.0.0.0                  
GitCommitId                    v6.0.0-alpha.14          
PSVersion                      6.0.0-alpha              
PSRemotingProtocolVersion      2.3                      
SerializationVersion           1.1.0.1                  
WSManStackVersion              3.0                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}  
PSEdition                      Core                     
```

**Comment by SteveL-MSFT** [comment] 2017-03-18 04:52
We should get the Documents folder programmatically

**Comment by iSazonov** [comment] 2017-03-18 09:59
Step by step:
1. Run PowerShell.
2. $env:PSModulePath` - Document
3. Change `Document` location on `C:\temp`
4. $env:PSModulePath` - Document
5. Run **new** PowerShell - here $env:PSModulePath` already is with  `C:\temp`

It is expected behavior for environment variables.

**Comment by SteveL-MSFT** [comment] 2017-03-18 21:36
If the issue is that within the same powershell session the env var isn't being updated, then as @iSazonov noted, that is expected and `by design`

**Comment by iSazonov** [comment] 2017-04-10 03:48
@SteveL-MSFT Could we close the Issue?

**Comment by chantisnake** [comment] 2017-04-10 05:32
the original issue is not within the same powershell session, I don't really know that is fixed or not?

**Comment by SteveL-MSFT** [comment] 2017-04-10 15:55
@chantisnake after changing the location, if you start a new powershell.exe does it point to the correct location?

**Comment by chantisnake** [comment] 2017-04-10 23:48
I don't think it happens on 6.0.0.17.

**Comment by chantisnake** [comment] 2017-04-12 09:18
no, no, no, I mean it still don't work in 6.0.0.17

**Comment by chantisnake** [comment] 2017-04-12 12:50
Yes, my document location is set to `~/Onedrive/surface-documents` before I installed powershell 6.0.0.17.

I tried resetting the document location to default, and then do a `$env:PSModulePath` and then set it back to `~/Onedrive/surface-documents`. It still uses the default.

**Comment by SteveL-MSFT** [comment] 2017-04-12 16:28
I was able to repro this, I think I found the issue

**Comment by SteveL-MSFT** [comment] 2017-04-12 16:37
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/CoreCLR/CorePsExtensions.cs#L1118 is hard coding `Documents` as the folder, probably because `Environment.GetFolderPath()` and `Enviroment.SpecialFolder enum` isn't available in the current version of coreclr we're building against.  Looks like these api's should be available in .Net Std 2.0.  Will revisit this once that work is complete.

**Comment by iSazonov** [comment] 2017-04-13 06:20
@SteveL-MSFT Yes, you are right.

**Comment by SteveL-MSFT** [comment] 2017-04-21 20:25
Just checked this and it appears to be fixed as part of the move to .Net Std 2.0 as that code which hardcoded the value was removed.

**Closed by SteveL-MSFT** 2017-04-21 20:25 UTC
Labels: Area-Console, Issue-Discussion, Resolution-Fixed, Waiting - NetStandard20

**Comment by chantisnake** [comment] 2017-04-22 16:15
Thank you guys. You guys are great

**Comment by iSazonov** [comment] 2017-04-22 17:28
@chantisnake Thanks for your report!
