### ISSUE TITLE
Remote execution DISKPART

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12732] opened 2020-05-20 05:33 UTC
# Steps to reproduce

```powershell
[administrator@167.xxx]: PS C:\Users\Administrator\Documents> cmd /c diskpart
```

# Expected behavior

```none
DISKPART>
```

# Actual behavior

```none
DISKPART>
[administrator@167.xxx]: PS C:\Users\Administrator\Documents>
```

# Environment data

```none
ps7.1
```

**Comment by iSazonov** [comment] 2020-05-20 05:55
Do you use a remote session?

**Comment by he852100** [comment] 2020-05-20 06:02
yes

**Comment by DHowett** [comment] 2020-05-21 13:02
This is a dupe of #12453 (sane root cause: tempted applications aren’t in an interactive session)

**Closed** 2020-05-22 17:00 UTC
Labels: Area-Remoting, Issue-Question, Resolution-Duplicate
