### ISSUE TITLE
PowerShell Class: .net type takes precedence  of my local type defined in a ps module. 

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#3251] opened 2017-03-03 21:28 UTC
Steps to reproduce
------------------
1. define a class in ps as below
```powershell
class Environment 
{
    Environment()
    {
    } 
    Environment([string]$name)
    {
    }
    [object] FooBar()
    {
        return get-process powershell
    }
 }
```
2. save it as temp.psm1
3. Import-Module .\temp.psm1
4. $mod=get-module temp
5. &($mod){[Environment]::new('Hello')}

Expected behavior
-----------------
An instance of Environment type defined in the Temp module should be created.

Actual behavior
---------------
```
Cannot find an overload for "new" and the argument count: "1".
At line:1 char:9
+ &($mod){[Environment]::new('hello')}
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

Initial Analysis:
---------------
Somehow PowerShell, Run()/DynamicInstruction<T0,T1,TRet>class,  picks up System.Environment type first.  Should PowerShell  search the local module first?

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.16-35-g669a34a27bd51756e49f50dc627cd4a89fd8244a
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.3
PSEdition                      Core
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
BuildVersion                   3.0.0.0

```

**Comment by BrucePay** [comment] 2017-03-04 00:33
Use 
`    using module .\temp.psm1` 
instead of Import-Module and then you can reference the type either using the short name
`     [environment]::New("hello")`
or the module-qualified name:
`    [myclassmodule.environment]::New("hello")`

**Comment by SteveL-MSFT** [comment] 2017-03-04 23:04
@jianyunt this appears to be `by design` in terms of order of precedence in resolving types.  changing this would be breaking and @BrucePay has provided supported ways around this

**Comment by jianyunt** [comment] 2017-03-06 02:18
@BrucePay @SteveL-MSFT ,  the following generates an error:

$mod=get-module temp
&($mod){[Environment]::new('something')}
using module $mod.Path


At line:1 char:1
+ using module $mod.Path
+ ~~~~~~~~~~~~~~~~~~~~~~
'$mod.Path' is not a valid value for using name.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidValueForUsingItemName

what's the correct syntax? I need to call it from C# and I do not think I have the module path other than via $mod.

**Comment by SteveL-MSFT** [comment] 2017-03-06 04:10
@jianyunt it should just be the module name

**Comment by joeyaiello** [comment] 2017-03-06 17:29
@SteveL-MSFT then why does @BrucePay reference `.\temp.psm1` in his example above? 

Isn't it that `using` needs parse-time values?

**Comment by SteveL-MSFT** [comment] 2017-03-06 17:40
Actually, I think both syntax is supported.  `module name` if it's in `PSModulePath` or directly to the `.psm1`

@jianyunt your example doesn't work as .Path points to the `.psd1`.  We should fix that.

**Comment by SteveL-MSFT** [comment] 2017-03-06 17:40
Keeping this issue resolved as `by-design` in terms of precedence.  @jianyunt you should open a new issue to support path to .psd1 for `using module`

**Comment by jianyunt** [comment] 2017-03-06 17:47
But I need workaround for this precedence issue.
 Case 1 - using module - fail
``` PowerShell
PS E:\test> dir .\temp.psm1


    Directory: E:\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/6/2017   9:34 AM            351 temp.psm1


PS E:\test> Import-Module .\temp.psm1
PS E:\test> $mod=get-module temp
PS E:\test> $mod.Path
E:\azure\PSCloudConsole\test\temp.psm1
PS E:\azure\PSCloudConsole\test> using module $mod.Path
At line:1 char:1
+ using module $mod.Path
+ ~~~~~~~~~~~~~~~~~~~~~~
'$mod.Path' is not a valid value for using name.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidValueForUsingItemName

```
Case 2: using FQ module name - Fail

``` PowerShell
PS E:\test> &($mod){[temp.Environment]::new('Hello')}
Unable to find type [temp.Environment].
At line:1 char:9
+ &($mod){[temp.Environment]::new('Hello')}
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (temp.Environment:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

```

Any workaround?

**Comment by SteveL-MSFT** [comment] 2017-03-06 18:23
`using module` requires a static name for the module as it's a parse time check

**Comment by jianyunt** [comment] 2017-03-06 18:26
It looks like the workaround is to add path to psmodulepath.  The following works.
``` PowerShell
create temp.psd1 and move both temp.psm1 and temp.psd1 under e:\test
$env:PSModulePath+=";E:\test\"
get-module temp -list
import-module temp
using module temp
$mod=get-module temp
&($mod){[temp.Environment]::new('Hello')}
```

**Comment by jianyunt** [comment] 2017-03-06 18:30
Regarding using module takes static name only, should we fix that?    Using module should take variable like ipmo?
$a="E:\test\temp.psm1"
import-module $a

**Comment by SteveL-MSFT** [comment] 2017-03-06 18:43
I believe that was a specific design decision so that you would get errors only through parsing without executing code

**Comment by lzybkr** [comment] 2017-03-06 19:19
Using is a static construct, it should mean the same thing every time you run a script.

If you could use a non-constant variable, the script could change behavior unexpectedly.

It was a conscious design choice to be more static with classes.

**Closed** 2017-03-06 19:28 UTC
Labels: Area-Language, Resolution-By Design
