### ISSUE TITLE
Case mismatch with the $profile and the directory automatically created

### ISSUE THREAD

**Issue by k-takai** [PowerShell/PowerShell#2187] opened 2016-09-05 11:43 UTC
Case doesn't match with the path value of profile and the directory that is automatically created at startup.
For this reason, if the profile script is deployed to the directory that is automatically created at powershell startup, that isn't invoked.

Steps to reproduce
------------------
1. $ rm -rf ~/.config/PowerShell
2. $ ls -lhad ~/.config/PowerShell

  > check directory isn't exist.

3. $ powershell
4. PS> exit
5. $ ls -lhad ~/.config/PowerShell

  > check directory is created automatically.

6. $ echo "Get-Date" > ~/.config/PowerShell/profile.ps1
7. $ powershell

  > check profile.ps1 isn't invoked.

8. PS /home/takai> exit
9. $ mkdir ~/.config/powershell

  > create lower case directory.

10. $ mv ~/.config/PowerShell/profile.ps1 ~/.config/powershell/
11. $ powershell

  > check profile.ps1 is invoked.

Expected behavior
-----------------
One of the following : 
- $profile is set "PowerShell" instead of "powershell"
- create "powershell" directory instead of "PowerShell" at startup

And the profile script which is deployed to the directory that is automatically created at startup is invoked correctly.

Actual behavior
---------------
Directory that is automatically created at startup : `~/.config/PowerShell`
$profile CurrentUserAllHosts path : `~/.config/powershell/profile.ps1`

Environment data
----------------
Commands and outputs are following.

```
takai@ubuntu1604:~$ rm -rf ~/.config/PowerShell
takai@ubuntu1604:~$ ls -lhad ~/.config/PowerShell
ls: cannot access '/home/takai/.config/PowerShell': No such file or directory
takai@ubuntu1604:~$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS /home/takai> exit
takai@ubuntu1604:~$ ls -lhad ~/.config/PowerShell
drwxrwxr-x 2 takai takai 4.0K Sep  5 20:06 /home/takai/.config/PowerShell
takai@ubuntu1604:~$ echo "Get-Date" > ~/.config/PowerShell/profile.ps1
takai@ubuntu1604:~$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS /home/takai> exit
takai@ubuntu1604:~$ mkdir ~/.config/powershell
takai@ubuntu1604:~$ mv ~/.config/PowerShell/profile.ps1 ~/.config/powershell/
takai@ubuntu1604:~$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.


Monday, September 5, 2016 8:08:31 PM


PS /home/takai> $PROFILE | Get-Member | ? MemberType -eq NoteProperty | fl *


TypeName   : System.String
Name       : AllUsersAllHosts
MemberType : NoteProperty
Definition : string AllUsersAllHosts=/opt/microsoft/powershell/6.0.0-alpha.9/profile.ps1

TypeName   : System.String
Name       : AllUsersCurrentHost
MemberType : NoteProperty
Definition : string AllUsersCurrentHost=/opt/microsoft/powershell/6.0.0-alpha.9/Microsoft.PowerShell_profile.ps1

TypeName   : System.String
Name       : CurrentUserAllHosts
MemberType : NoteProperty
Definition : string CurrentUserAllHosts=/home/takai/.config/powershell/profile.ps1

TypeName   : System.String
Name       : CurrentUserCurrentHost
MemberType : NoteProperty
Definition : string CurrentUserCurrentHost=/home/takai/.config/powershell/Microsoft.PowerShell_profile.ps1

```

```powershell
PS /home/takai> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment] 2016-09-19 21:35
Closing as duplicate of #1823 and already resolved by #2036.

**Closed by andschwa** 2016-09-19 21:35 UTC
Labels: Area-Portability, Issue-Bug, OS-Linux, OS-macOS
