### ISSUE TITLE
Having to click twice to close

### ISSUE THREAD

**Issue by sefacan** [PowerShell/PowerShell#12144] opened 2020-03-17 19:02 UTC
Steps to reproduce:

* Open powershell in any folder
* Write to powershell "code ." //open the folder with visual studio code
* Click to powershell window close button one time. Window will not close. 
* Click a second time, windows will close.

I think it should close when I first click. This problem is just "code . " Occurs when I run the command.
I guess when powershell is unfocus when it opens another window it can't detect the first shutdown.

**Comment by mklement0** [comment] 2020-03-18 17:30
That's an interesting find (in the future, please provide details about your environment, as suggested in the issue template; in the case at hand, it would have been helpful to know that the problem only occurs (in regular console windows) _on Windows_).

However, the problem is not related to PowerShell, it is the behavior of regular console windows (`conhost.exe`) on Windows, as evidenced by the fact that a regular `cmd.exe` console window exhibits the same behavior.

Therefore, please close this issue and report it at https://github.com/microsoft/terminal/issues.

Also interesting to note that [Windows Terminal](https://aka.ms/windowsterminal) is not affected.

**Closed** 2020-03-24 07:00 UTC
Labels: Issue-Question, Resolution-External
