### ISSUE TITLE
 Update-Help -UICulture en-US

### ISSUE THREAD

**Issue by prepstarr** [PowerShell/PowerShell#17534] opened 2022-06-17 01:53 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Update-Help -UICulture en-US

### Expected behavior

```console
Downloads and installs the newest help files on your computer.
```

### Actual behavior

```console
Update-Help: Failed to update Help for the module(s) '7zip-Archive' with UI culture(s) {en-US} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 'https://github.com/stadub/PowershellScripts/blob/master/7Zip/README.md' does not resolve to a container..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

### Error details

```console
Exception             :
    Type    : System.Exception
    Message : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).).
              English-US help content is available and can be installed using: Update-Help -UICulture en-US.
    HResult : -2146233088
CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
InvocationInfo        :
    MyCommand        : Update-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : Update-Help -UICulture en-US
    PositionMessage  : At line:1 char:1
                       + Update-Help -UICulture en-US
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Update-Help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/65930206/174206787-05523ec6-047b-413b-b194-6ef57923eb74.png)

**Comment by ehmiiz** [comment] 2022-06-17 11:02
I remember trying to solve this issue before:

https://answers.microsoft.com/en-us/windows/forum/all/updateing-powershell-user-help-files/07afd880-c543-4e56-9446-1e9eb509003d

People suggest running get-help with -Force -ErrorAction SilentlyContinue - however this will not update the failing modules, only hide the errors

I would suspect the issue lies either in naming rules of blobs:
https://docs.microsoft.com/en-us/rest/api/storageservices/Naming-and-Referencing-Containers--Blobs--and-Metadata?redirectedfrom=MSDN

and since you have the issue (FR) and I have the same (Swedish layout) it seems to be cause by Thread.CurrentUICulture property

**Comment by ehmiiz** [comment] 2022-06-17 12:32
After some digging I found this:
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2247
Seems to be a known issue with Get-Help / Update-Help that causes this

As described here by Sean:
https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/
a work-around is to rename the module folder that you need to update help for, just tested for the module PKI (renamed to the new module name lowercase: pki), "update-help pki" worked fine

**Comment by ehmiiz** [comment] 2022-06-21 11:34
> After some digging I found this: [MicrosoftDocs/windows-powershell-docs#2247](https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2247) Seems to be a known issue with Get-Help / Update-Help that causes this
> 
> As described here by Sean: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/ a work-around is to rename the module folder that you need to update help for, just tested for the module PKI (renamed to the new module name lowercase: pki), "update-help pki" worked fine
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e68e34fec82df597ef2257f5c1caf66389261e928d626d20543a46464430cf65/68747470733a2f2f646576626c6f67732e6d6963726f736f66742e636f6d2f706f7765727368656c6c2f77702d636f6e74656e742f75706c6f6164732f73697465732f33302f323031382f30392f506f7765727368656c6c5f3235362e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/51145e85e7e07991fb2b235b9306ab50d9e4843dd1c5dc1bed7f3b5821707a53/68747470733a2f2f646576626c6f67732e6d6963726f736f66742e636f6d2f706f7765727368656c6c2f77702d636f6e74656e742f75706c6f6164732f73697465732f33302f323031392f30322f506f7765727368656c6c5f323536312e706e67"> PowerShell Team**[Updating help for the PSReadLine module in Windows PowerShell 5.1](https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/)**Describes how to workaround the error when you try to update help for PSReadline in Windows PowerShell 5.1.

As this thread talks about the 404 error, In my case it seems to fail because what is displayed and stored in the module path is actually folders with incorrect names, either the module author/owner/microsoft changed name completely or casing (PKI>pki)

PKI should be pki
Dism should be DISM
ConfigDefenderPerformance should be (even more strange) Defender
Kds should be KDS
And so on

A work-around is to rename them with their newer name as described here:
https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

Note that this will probably only work well for modules with the "wrong" casing, some modules like ConfigDefenderPerformance actually have dead links in their HelpInfoURI in their manifest, so it's an actual case of 404

**Comment by dkaszews** [comment] 2022-07-30 17:49
I'll take a look at it as part of PR #17780 , I saw something that may suggest the error hint about `en-US` being available does not actually take into account the real culture of the module.

Can you please provide link to the 7-zip module that gives you trouble and paste output of `Get-UICulture`?

**Comment by dkaszews** [comment] 2022-08-01 11:21
I found an issue in `UpdatableHelpCommandBase:EndProcessing`: even though original exceptions contain a list of supported cultures: `"The specified culture is not supported: en-GB. Specify a culture from the following list: {en-US}."`, when we fold them over multiple modules we ignore it and just assume it was `en-US`: `"Failed to update Help for the module(s) '{0}' with UI culture(s) {{{1}}} : {2}.\nEnglish-US help content is available and can be installed using: Update-Help -UICulture en-US."`

This can lead to situation where `Update-Help -UICulture en-US` fails because the help is actually available in let's say `en-GB` or `fr-FR` or whatever, then tell you to use `en-US` again regardless.

**Comment by theJasonHelmick** [comment] 2023-01-18 21:13
Thank you @prepstarr for reporting this -- this is a duplicate of an existing issue https://github.com/PowerShell/PowerShell/issues/13591

**Closed** 2023-01-19 23:00 UTC
Labels: Resolution-Duplicate, WG-Interactive-HelpSystem

**Comment by sdwheeler** [comment] 2023-12-11 21:13
Adding a summary of answers for this issue is being before closing out comments.

The 7zip-Archive module is not from Microsoft. Contact the vendor for support.

The error is expected for the following Windows modules. 

- ConfigDefenderPerformance
- Dism
- Get-NetView
- Kds
- NetQos
- PcsvDevice
- PKI
- StartLayout
- Whea
- WindowsSearch
- WindowsUpdate

The Windows modules are not maintained by the PowerShell team. To prevent the error, the module owners on the Windows team must fix the modules. For modules that ship in Windows, open a support case with Windows Support or send feedback via the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
