### ISSUE TITLE
Need Get-ComputerInfo on Linux

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2693] opened 2016-11-16 17:22 UTC
Ubuntu 16.04 LTS

PS /home/lit/src/t> Get-ComputerInfo                                                                    
Get-ComputerInfo : The term 'Get-ComputerInfo' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:1
+ Get-ComputerInfo
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ComputerInfo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS /home/lit/src/t> $PSVersionTable                                                                     

Name                           Value                                                                       
----                           -----                                                                       
PSVersion                      6.0.0-alpha                                                                 
PSEdition                      Core                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                     
BuildVersion                   3.0.0.0                                                                     
GitCommitId                    v6.0.0-alpha.12                                                             
CLRVersion                                                                                                 
WSManStackVersion              3.0                                                                         
PSRemotingProtocolVersion      2.3                                                                         
SerializationVersion           1.1.0.1

**Comment by Liturgist** [comment] 2017-06-27 15:47
It would be great if someone from Red Hat or Ubuntu would pick this up. Are there any contacts like this here on github?

**Comment by SteveL-MSFT** [comment] 2017-06-27 15:58
I think this port could be done in stages and it doesn't have to be all or nothing.  Some of the info should be relatively easy to get from the Linux filesystem parsing text files.

**Comment by Liturgist** [comment] 2017-06-27 16:20
I agree with stages. Whatever it is needs to be open to the variety of vendors and distros. The OsOrganization member should be able to return 'Red Hat', 'Ubuntu', 'Arch', 'Mint', 'Centos', etc.

It has always been frustrating to me that `uname -a` only returns a kernel version number. As important as that is, `uname` should (in my opinion) reveal the distro name.

**Comment by iSazonov** [comment] 2017-06-27 17:44
We can use /etc/release https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by jeffbi** [comment] 2017-06-27 17:49
There are a number of place we can get info on Linux. Very few of which will work on mac os, by the way.

**Comment by SteveL-MSFT** [comment] 2019-03-01 20:10
Dupe of https://github.com/PowerShell/PowerShell/issues/419

**Closed by SteveL-MSFT** 2019-03-01 20:10 UTC
Labels: Area-Cmdlets, Issue-Enhancement, Resolution-Duplicate
