### ISSUE TITLE
Can't cd to path copied from Windows Explorer

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#21013] opened 2024-01-06 13:14 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1) `mkdir "$HOME\[TEST] Directory"`
2) Do "copy as path" from Windows Explorer on this directory.
3) Do `cd "C:\Users\user\[TEST] Directory"`

### Expected behavior

```console
Directory changed to "C:\Users\user\[TEST] Directory"
```

### Actual behavior

```console
❯ cd "C:\Users\user\[TEST] Directory"
Set-Location: Cannot find path 'C:\Users\user\[TEST] Directory' because it does not exist.
```

### Error details

```console
❯ Get-Error

Exception             :
    Type                 : System.Management.Automation.ItemNotFoundException
    ErrorRecord          :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find path 'C:\Users\user\[TEST] Directory' because it does not exist.
            HResult : -2146233087
        TargetObject          : C:\Users\user\[TEST] Directory
        CategoryInfo          : ObjectNotFound: (C:\Users\user\[TEST] Directory:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PathNotFound
    ItemName             : C:\Users\user\[TEST] Directory
    SessionStateCategory : Drive
    TargetSite           :
        Name          : SetLocation
        DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message              : Cannot find path 'C:\Users\user\[TEST] Directory' because it does not exist.
    Source               : System.Management.Automation
    HResult              : -2146233087
    StackTrace           :
   at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context, Boolean literalPath)
   at Microsoft.PowerShell.Commands.SetLocationCommand.ProcessRecord()
TargetObject          : C:\Users\user\[TEST] Directory
CategoryInfo          : ObjectNotFound: (C:\Users\user\[TEST] Directory:String) [Set-Location], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
InvocationInfo        :
    MyCommand        : Set-Location
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : cd 'C:\Users\user\[TEST] Directory'
    Statement        : cd 'C:\Users\user\[TEST] Directory'
    PositionMessage  : At line:1 char:1
                       + cd 'C:\Users\user\[TEST] Directory'
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : cd
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
❯ echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/5204968/a2f4ed74-824a-469b-84b9-03a372205a47)

**Comment by rhubarb-geek-nz** [comment] 2024-01-06 13:34
I expect it is due to the square brackets being interpreted differently in PowerShell.

Either escape the square brackets or use 

```
cd -LiteralPath "C:\Users\user\[TEST] Directory"
```

**Comment by mklement0** [comment] 2024-01-06 14:10
To flesh out @rhubarb-geek-nz's comment a bit:

The `-Path` (`-FilePath`) parameter of provider (file-handling) cmdlets (which the first _positional_ argument implicitly binds to), expects _wildcard_ expressions. 

Because PowerShell's [wildcard language](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Wildcards) also supports expressions such as `[a-z]` (to match any English letter), paths meant to be _literal_ ones are misinterpreted if they happen to contain `[` chars. 

To pass a literal path as such, use the `-LiteralPath` parameter explicitly. 

Alternatively, pass a file-information object such as produced by `Get-ChildItem` _via the pipeline_ to a provider cmdlet, which also binds to `-LiteralPath`.

That said, the latter technique should _not_ be used with `Set-Location` (`cd`), specifically, because it inexplicably prefixes the then-current location's path with `Microsoft.PowerShell.Core\FileSystem::` - see #10522

**Comment by kilasuit** [comment] 2024-01-06 20:12
Just as an FYI in interactive use tab completion to that path already takes care of this for you as shown below

![image](https://github.com/PowerShell/PowerShell/assets/6355225/13358cc7-98e8-4987-ad8e-68e450fbab15)

This could perhaps as a way to fix it in code have some validation checks on the path parameter and if the path contains a `[` or `]` then it reruns it with literalpath automatically for you.

As such passing this to the Cmdlets WG to review and discuss

**Comment by rhubarb-geek-nz** [comment] 2024-01-06 20:39
> This could perhaps as a way to fix it in code have some validation checks on the path parameter and if the path contains a `[` or `]` then it reruns it with literalpath automatically for you.

I don't like the idea of code automatically double guessing you and saying that you meant something different to what you specified. These are supposed to be predictable and deterministic systems. If would be worse if the behaviour in the command line is different to how it behaves in a script. If tab-completion fixes the problem, that is fine because you explicitly pressed tab and saw the result.

**Comment by kilasuit** [comment] 2024-01-06 20:50
It was a possible suggestion, the other is to throw a warning with recommended action to use the `LiteralPath` parameter instead which I don't think would be hard to do. 

But sometime in future, as a configurable setting, you could specify which recommended actions could just automatically run for you in instances like this, making you quicker in interactive & non-interactive scenarios, which wouldn't be `automatically double guessing you` but you actively saying `ah ok thanks for reminding me that I meant to do this but I forgot/didn't know about it, so do it for me anyway` which could be provided to new users by IT Admins likely via a settings module as well as advanced users making their overall experience better.

**Comment by mklement0** [comment] 2024-01-06 21:16
@kilasuit, that sounds like a job for a  [feedback provider](https://devblogs.microsoft.com/powershell/what-are-feedback-providers/) - and it is worth debating whether to include it in the built-in one or recommend implementation of a custom one (which would then by definition be opt-in).

**Comment by jdhitsolutions** [comment] 2024-09-17 17:51
Add to the Cmdlet Working Group to-do list.

**Comment by kilasuit** [comment] 2024-10-22 21:07
Worth remembering that we can set a RecommendedAction already (even in v5) in the ErrorDetails object

We don't make use of this that well in the community from what I've seen & doing so may be a Quick Win here in adding a recommended action to the ErrorDetails in this instance especailly as this is exposed when `$ErrorView = 'ConciseView' ` as per @JustinGrote adding that in #20826 

We also don't seem to surface it either from using Get-Error from what I could work out on a quick play around

**Comment by JustinGrote** [comment] 2024-10-22 21:24
Surfacing it in `Get-Error` would be pretty simple as the formatting is script-driven. I would recommend populating it in RecommendedAction if the problem is always surfaced when an error occurs.

**Comment by SteveL-MSFT** [comment] 2024-11-06 17:40
Duplicate of https://github.com/PowerShell/PowerShell/issues/12168

**Closed** 2024-11-07 19:59 UTC
Labels: Resolution-Duplicate, WG-Cmdlets-Management
