### ISSUE TITLE
Powershell.sln does not build in Visual Studio

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2714] opened 2016-11-17 23:33 UTC
Steps to reproduce
------------------
Open PowerShell.sln in visual studio 2015
Build Solution

Expected behavior
-----------------
Project builds and enables F5 debugging, at least for FullClr

Actual behavior
---------------
Lots of reference errors

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by lzybkr** [comment] 2016-11-18 02:25
Duplicate of #1895.

**Closed by lzybkr** 2016-11-18 02:25 UTC
