### ISSUE TITLE
Invoke-Command returns incomplete data

### ISSUE THREAD

**Issue by Borkason** [PowerShell/PowerShell#13693] opened 2020-09-25 07:32 UTC
## Steps to reproduce

```powershell
$option = New-PSSessionOption -NoMachineProfile
$s = New-PSSession $dc -SessionOption $option -Credential $c
Invoke-Command -Session $s -Command { Get-ChildItem "C:\Windows\sysvol\domain\policies\policydefinitions" | select -First 5 }
```

## Expected behavior

Working in PowerShell 5.1

```none
    Directory: C:\Windows\sysvol\domain\policies\policydefinitions


Mode                LastWriteTime         Length Name                                                      PSComputerName
----                -------------         ------ ----                                                      --------------
d-----       27.05.2020     13:44                de-DE                                                     [redacted]
d-----       27.05.2020     13:44                en-US                                                     [redacted]
-a----       10.10.2018     13:37         117860 access16.admx                                             [redacted]
-a----       18.03.2019     21:21           4717 ActiveXInstallService.admx                                [redacted]
-a----       18.03.2019     21:21           4714 AddRemovePrograms.admx                                    [redacted]
```
![image](https://user-images.githubusercontent.com/2971735/94239600-580d9200-ff12-11ea-92f6-5cb9eb03d587.png)

## Actual behavior

Broken in PowerShell 7.0.3

```none
    Directory: C:\Windows\sysvol\domain\policies\policydefinitions

Mode                 LastWriteTime         Length Name                                                     PSComputerName
----                 -------------         ------ ----                                                     --------------
                                                                                                           [redacted]
                                                                                                           [redacted]
                                                                                                           [redacted]
                                                                                                           [redacted]
                                                                                                           [redacted]
```

![image](https://user-images.githubusercontent.com/2971735/94239654-69569e80-ff12-11ea-90d1-9ba596540e03.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2020-09-25 17:15
Duplicate of #11400

**Closed** 2020-09-26 20:00 UTC
Labels: Issue-Question, Resolution-Duplicate
