### ISSUE TITLE
`ls` is not self-consistent

### ISSUE THREAD

**Issue by LqkUWp** [PowerShell/PowerShell#17990] opened 2022-08-30 14:21 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a file `.\o\abc [defg].pdf`, then I try all commands below to `ls` it. The first char y/x represents that the corresponding command works or not, i.e. prints the file or nothing without any error. 

```
y ls 'abc `[defg`].pdf' -Recurse
y ls 'abc `[defg`].pdf' -Recurse -File | ls
x ls (ls 'abc `[defg`].pdf' -Recurse).FullName
x ls "$((ls 'abc `[defg`].pdf' -Recurse).FullName)"
x ls (ls 'abc `[defg`].pdf' -Recurse -File).ToString()
   ```

### Expected behavior

```console
All commands above should works exactly the same way.
```

### Actual behavior

```console
Just as the first char y/x in each command line shows. Output of `ls` can't be recognized by `ls` itself when the output is not passed via pipeline. 
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by dkaszews** [comment] 2022-08-30 15:52
I don't understand this `x/y` notation. Please either show the output of each command, or write them as tests using `| Should -Be $null` or `| Should -Not - Be $null`.

Also, this is not a bug, but the result of treating filename as a glob. Minimal test case would be a file named `[.txt`. ``` ls '`[.txt' ``` will work, but ``` ls '`[.txt' | ls``` with through an error about mismatched `[`. This is solved by using `-LiteralPath` whenever you pipe in filenames.

**Comment by iSazonov** [comment] 2022-08-31 04:12
It seems this mix some issues and such issue were already opened.

**Comment by jhoneill** [comment] 2022-09-07 11:29
This and #17992  and #17991 are basically the same issue.  There are pain points around the use of `[`  and  `]` filenames because they can be treated as wild cards. 
The advice is 
1. Avoid using these characters. 
2. If you **must** use them specify -LiteralPath  - there are places where the  `[` and `]` can be escaped with a `` ` `` but this is not reliable.  See #17992  and #18038  among other places.

In all three failing examples above  the inner command  ```  ls  'abc `[defg`].pdf' ``` works because the string is treated as -Path and escaping works  as desired.    
The full name - which is what the file object gives when converting to a string - does _not_ escape the name so the outer command runs `ls 'abc [defg].pdf' ` un-escaped, which fails.    
If the outer command may need to deal with names that contain wildcard chars it _must_ use `-literalpath`

**Comment by mklement0** [comment] 2022-09-07 16:05
On a side note, @LqkUWp: Please use the true names of PowerShell cmdlets in your issues, not aliases, especially if those aliases aren't defined on all platforms due to referring to a native utility there. Specifically, `ls` refers to `/bin/ls` on Unix-like platforms, not `Get-ChildItem`, so if someone tries your repro steps there, they won't work as intended.

---

While https://github.com/PowerShell/PowerShell/issues/17992 and https://github.com/PowerShell/PowerShell/issues/17991 show true problems (which may ultimately be resolved by #7999), I see only _by-design_ behavior here (to paraphrase  your explanation, @jhoneill):

* `Get-ChildItem`'s first _positional_ argument binds to the wildcard-supporting `-Path` parameter.
* To provide a _literal_ path (as implied by a `[System.IO.FileInfo]` instance), either use `-LiteralPath` explicitly or (as shown in the initial post), provide the `[System.IO.FileInfo]` instance _via the pipeline_, where it also binds to the `-LiteralPath` parameter (via the `.PSpath` property, thanks to `-PSPath` being a parameter alias).

#18038 is actually unrelated, because it refers to the _native globbing_ feature for _external programs_, which is distinct from how providers handle wildcards.

**Comment by jhoneill** [comment] 2022-09-07 18:35
@mklement0   yes 18038 is only another example of escaped wildcards not being processed correctly, there seems to be independent code in multiple places making similar errors, so a fix for 18038 wouldn't fix 17992 and vice versa. 

As another example, on Windows ```dir | out-file -path 'files [Sept].txt'``` gives a "file does not exist", but ```dir | out-file -path 'files `[Sept`].txt'``` will create a file with ``` ` ``` in the name, I think this is another distinct bit of code.

**Comment by mklement0** [comment] 2022-09-08 05:06
Your other example is the subject of:
*  https://github.com/PowerShell/PowerShell/issues/9475

**Comment by jhoneill** [comment] 2022-09-08 08:14
@mklement0  I brought this up at the cmdlet working group yesterday. Things are being looked at again, although we may get the same conclusion as before. The point you make in 9475 that `Set-Content` and `Out-File`  work differently _suggests_ "cmdlet thing which is relatively easy to fix", rather than "provider minefield"

**Closed** 2023-11-22 10:59 UTC
Labels: Needs-Triage, Resolution-No Activity
