### ISSUE TITLE
Sign the macOS .pkg installer

### ISSUE THREAD

**Issue by anurse** [PowerShell/PowerShell#1881] opened 2016-08-18 16:44 UTC
First off, congrats on the release!! Super excited!

The macOS pkg on the download page is not signed which means it can't be "double-clicked" on macOS, you have to right click and choose Open. Also, signing in general is goodness :). I know we did it for the .NET Core SDK package, so I might be able to point you at folks who have done it (email is [github user name]@microsoft.com)
## Steps to reproduce
1. Download macOS PKG from repo home page
2. Run `pkgutil --check-signature ~/Downloads/powershell-6.0.0-alpha.9.pkg`
## Expected behavior

Something like:

```
Package "powershell-6.0.0-alpha.9.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. blah blah blah...
```
## Actual behavior

```
Package "powershell-6.0.0-alpha.9.pkg":
   Status: no signature
```
## Environment data

Not relevant, not an issue in PowerShell itself :)

**Comment by felixmc** [comment] 2016-08-19 16:05
+1

I would love to install PowerShell on my work macbook and try it out, but our security policy prevents me from installing unsigned packages, so I can't install it until this issue is resolved.

**Comment by johnczerwiec** [comment] 2016-10-19 17:08
Seems to have left off of most current release --

pkgutil --check-signature powershell-6.0.0-alpha.11.pkg 
Package "powershell-6.0.0-alpha.11.pkg":
   Status: no signature

**Comment by joeyaiello** [comment] 2017-05-24 19:59
I think we *have* to do this before we ship a GA/RTM build.

**Comment by TravisEz13** [comment] 2017-11-18 20:34
duplicate of #5496

**Closed** 2017-11-18 20:34 UTC
Labels: Area-Build, OS-macOS
