### ISSUE TITLE
Unicode character displaying as escape sequence for exception

### ISSUE THREAD

**Issue by kenhia** [PowerShell/PowerShell#10395] opened 2019-08-20 17:43 UTC
# Steps to reproduce

```powershell
throw "this string is long enough to reproduce it"
```

# Expected behavior

```none
this string is long enough to reproduce it
At line:1 char:1
+ throw "this string is long enough to reproduce it"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (this string is ...to reproduce it:String) [], RuntimeException
    + FullyQualifiedErrorId : this string is long enough to reproduce it
```

# Actual behavior

```none
this string is long enough to reproduce it
At line:1 char:1
+ throw "this string is long enough to reproduce it"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (this string is long\u2026ugh to reproduce it:String) [], RuntimeException
+ FullyQualifiedErrorId : this string is long enough to reproduce it
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
Console Font: Consolas (which does have the 2026 char)
```

**Comment by iSazonov** [comment] 2019-08-21 05:57
I can not repo on latest build.

**Comment by KalleOlaviNiemitalo** [comment] 2019-08-21 07:10
It's a duplicate of #9586.

**Comment by iSazonov** [comment] 2019-08-21 11:18
@kenhia Thanks for your report! The issue was fixed. It is already in 7.0 Preview.

**Closed by iSazonov** 2019-08-21 11:18 UTC
Labels: Issue-Question, Resolution-Duplicate
