### ISSUE TITLE
get-winevent inside invoke-command can't handle arrays inside filterhashtable

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#13108] opened 2020-07-05 14:42 UTC
## Steps to reproduce

```powershell
# elevated prompt
start-service winrm
invoke-command localhost { get-winevent @{logname = 'application'; level = 1,2,3} }  
```

## Expected behavior

```none
# many events
```

## Actual behavior

```none
Get-WinEvent: No events were found that match the specified selection criteria.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Workaround, define an array variable first inside the scriptblock.  Note that passing in an array as a param() to invoke-command is notoriously difficult.
```powershell
invoke-command localhost { $levels = 1,2,3; get-winevent @{logname = 'application'; level = $levels} }
```

**Comment by iSazonov** [comment] 2020-07-06 11:46
Can you confirm that you use PS7 remote point (not Windows PowerShell remote point)?

**Comment by jszabo98** [comment] 2020-07-06 13:02
No, as is likely, the remote endpoint is PS 5.  How do you enable a PS 7 endpoint?  Running enable-psremote in PS 7 doesn't seem to do anything.   Get-PSSessionConfiguration doesn't return anything.

```powershell
Enable-PSRemoting

WARNING: PowerShell remoting has been enabled only for PowerShell 6+ configurations and does not affect Windows PowerShell remoting configurations. Run this cmdlet in Windows PowerShell to affect all PowerShell remoting configurations.
WinRM is already set up to receive requests on this computer.
Set-WSManQuickConfig:
Line |
 121 |                  Set-WSManQuickConfig -force
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="localhost"><f:Message><f:ProviderFault provider="Config provider" path="%systemroot%\system32\WsmSvc.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="mycomputer.com"><f:Message>WinRM firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again. </f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>

Get-PSSessionConfiguration # no output
```

**Comment by iSazonov** [comment] 2020-07-06 15:22
@PaulHigin Could you please comment the issue?

**Comment by PaulHigin** [comment] 2020-07-06 16:42
This is not a regression since it can be repro'd in WindowsPowerShell 5.1.  This looks like another bug in the 'GetPowerShell' method that tries to convert script text into equivalent PowerShell command/parameters.  The above workaround works because it causes the conversion to fail and the script text is sent to the target computer as is.  A fix for this may involve detecting a hash table parameter argument like this and failing the conversion.

**Comment by daxian-dbw** [comment] 2020-07-06 22:57
It looks `GetPowerShell` method is working as expected, but the problem lies in the serialization/deserialization layer -- the `object[]` (1,2,3) got deserialized into an `ArrayList` on the remote side, and hence `Get-WinEvent` couldn't understand the filter hashtable.

```powershell
PS> $s = New-PSSession .
PS> Enter-PSSession $s
[localhost]: PS> function bar { param([hashtable] $h) $h; $type = $h['level'].GetType().FullName; "`nType of level's value: $type" }
[localhost]: PS> exit
PS> invoke-command $s { bar @{logname = 'application'; level = 1,2,3} }

Name                           Value
----                           -----
level                          {1, 2, 3}
logname                        application

Type of level's value: System.Collections.ArrayList
```

If you use `ArrayList` locally, you will get the same error.
```
PS> $al = [System.Collections.ArrayList]::new()
PS> $al.Add(1) > $null
PS> $al.Add(2) > $null
PS> $al.Add(3) > $null
PS> Get-WinEvent @{ logname = 'application'; level = $al}
Get-WinEvent: No events were found that match the specified selection criteria.
```

**Comment by PaulHigin** [comment] 2020-07-06 23:09
I would argue that GetPowerShell is not working correctly, if its conversion to command/parameters fails, even if the failure is in the serialization system.  I doubt we can safely change serialization behavior so I feel the best fix is to not perform conversion for hashtable argument cases, if they can't be transferred correctly.

**Comment by daxian-dbw** [comment] 2020-07-06 23:21
The failure can happen in a different form, where `GetPowerShell` is not involved:
```
PS:45> Invoke-Command $s { param($h) $h.GetType(); Get-WinEvent $h } -ArgumentList @{logname = 'application'; level = 1,2,3}

IsPublic IsSerial Name                                     BaseType                                 PSComputerName
-------- -------- ----                                     --------                                 --------------
True     True     Hashtable                                System.Object                            localhost
Get-WinEvent: No events were found that match the specified selection criteria.
```

**Comment by PaulHigin** [comment] 2020-07-06 23:30
Yes, definitely this is broken and we should look at fixing it if possible.  But the script version works just fine and is probably much more common.  I feel we are compounding the problem by gratuitously converting the working script to a broken command form.  We may be able to fix it in the serialization system, but I am a little worried about making changes there.  But I agree that if it can be fixed there, that would be ideal.

**Comment by SteveL-MSFT** [comment] 2020-07-08 22:41
@PowerShell/powershell-committee discussed this in relation to another issue, we agreed that remoting should not be using `GetPowerShell` and instead should be passing the scriptblock as text to be handled by the target

**Closed** 2023-11-23 11:58 UTC
Labels: Issue-Bug, WG-Remoting, Committee-Reviewed, Resolution-No Activity
