### ISSUE TITLE
Invoke-RestMethod doesn't handle HTTP chunked responses

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#7824] opened 2018-09-20 00:45 UTC
Steps to reproduce
------------------

```powershell
Invoke-RestMethod -Uri https://dweet.io/listen/for/dweets/from/trevor -Method Get -ContentType application/json
```

Expected behavior
-----------------

Invoke-RestMethod returns chunked HTTP content

Actual behavior
---------------

Invoke-RestMethod hangs

```none
PS /Users/tsulli/reinvent-powershell-workshop> Invoke-RestMethod -Uri https://dweet.io/listen/for/dweets/from/someobjectnamegoeshere -Method Get -ContentType application/json -TransferEncoding chunked -Body asdf

^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chuanjiao10** [comment] 2018-09-24 16:03
Webcmdlet has -TimeoutSec, I often use -TimeoutSec 30, also available in the lower version, I hope to help you.

**Comment by markekraus** [comment] 2018-10-22 23:15
Duplicate of  #3829

It is a none limitation that streaming type endpoint points are currently not supported. We would need a separate set of cmdlets to work with stream/chunked responses.

**Closed** 2018-10-22 23:15 UTC
Labels: Area-Cmdlets-Utility, Issue-Discussion, Resolution-Duplicate
