### ISSUE TITLE
Cannot use longPathAware assembly from PowerShell

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#13954] opened 2020-10-31 08:06 UTC
## Steps to reproduce

Take this crude C# code (derived from [code in this StackOverflow thread](https://stackoverflow.com/questions/554010/how-to-get-the-actual-size-on-disk-of-a-file-from-powershell)):

````
using System;
using System.Linq;
using System.Runtime.InteropServices;

namespace NTFS
{
    public class ExtendedFileInfo
    {
        [DllImport("kernel32.dll", SetLastError = true, EntryPoint = "GetCompressedFileSizeW")]
        static extern uint GetCompressedFileSizeAPI([MarshalAs(UnmanagedType.LPWStr)] string lpFileName, out uint lpFileSizeHigh);
        public static ulong GetCompressedFileSize(string filename)
        {
            uint high;
            uint low;
            low = GetCompressedFileSizeAPI(filename, out high);
            int error = Marshal.GetLastWin32Error();
            if (high == 0 && low == 0xFFFFFFFF && error != 0)
            {
                throw new System.ComponentModel.Win32Exception(error);
            }
            else
            {
                return ((ulong)high << 32) + low;
            }
        }
    }
}

namespace GetFileSizeOnDisk
{
    class Program
    {
        static void Main(string[] args)
        {
            bool verbose = false;
            string fullname = "foobar.txt";
            if (args.Length != 0)
            {
                fullname = args[0];
                if (args.Length >= 2)
                {
                    if (args[1] == "-v")
                    {
                        verbose = true;
                    }
                }
            }
            if (verbose)
            {
                Console.WriteLine("FullName: '{0}'", fullname);
                int pathlen = fullname.Length;
                Console.WriteLine("Path length: {0}", pathlen);
                var fi = new System.IO.FileInfo(fullname);
                long size = fi.Length;
                Console.WriteLine("Size: {0}", size);

            }
            ulong sizeondisk = NTFS.ExtendedFileInfo.GetCompressedFileSize(fullname);
            if (verbose)
            {
                Console.WriteLine("Size on disk: {0}", sizeondisk);

            }
            else
            {
                Console.WriteLine("{0}", sizeondisk);
            }
        }
    }
}
````

Compiled with an assembly manifest that includes

````
  <!-- application is long pathname aware -->
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
      <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
  </application>
````

this gives you an executable that is able to process files whose absolute pathname is longer than 256 characters:

````
PS> $p='C:\Users\steph\OneDrive\test\test01\test02\test03\test04\test05\test06\test07\test08\test09\test10\test11\test12\test13\test14\test15\test16\test17\test18\test19\test20\test21\test22\test23\test24\test25\test26\test27\test28\test29\test30\test31\test32\test33\test34\test35\test36\test37\test38\test39\test40\test.txt'

PS> .\GetFileSizeOnDisk.exe $p -v
FullName: 'C:\Users\steph\OneDrive\test\test01\test02\test03\test04\test05\test06\test07\test08\test09\test10\test11\test12\test13\test14\test15\test16\test17\test18\test19\test20\test21\test22\test23\test24\test25\test26\test27\test28\test29\test30\test31\test32\test33\test34\test35\test36\test37\test38\test39\test40\test.txt'
Path length: 317
Size: 6
Size on disk: 6
````

This also gives you a DLL for an assembly that exposes a method that can be called from PowerShell:

````
PS> System.Reflection.Assembly]::LoadFile("....\GetFileSizeOnDisk.dll")

GAC    Version        Location
---    -------        --------
False  v4.0.30319     ....\GetFileSizeOnDisk.dll


PS> [NTFS.ExtendedFileInfo]::GetCompressedFileSize("c:\windows\system32\notepad.exe")
202240
````

But invoking that method from PowerShell does not support pathnames longer than 256 characters:

````
PS> $p='C:\Users\steph\OneDrive\test\test01\test02\test03\test04\test05\test06\test07\test08\test09\test10\test11\test12\test13\test14\test15\test16\test17\test18\test19\test20\test21\test22\test23\test24\test25\test26\test27\test28\test29\test30\test31\test32\test33\test34\test35\test36\test37\test38\test39\test40\test.txt'

PS> [NTFS.ExtendedFileInfo]::GetCompressedFileSize($p)
MethodInvocationException: Exception calling "GetCompressedFileSize" with "1" argument(s): "The system cannot find the path specified."

````

## Expected behavior

Invoking the method in the `longPathAware` assembly should be `longPathAware`.

## Actual behavior

Invoking the method is not `longPathAware`, resulting in "path not found" errors for arguments > 256 characters long.

## Environment data
```
> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment] 2020-10-31 13:08
Does `Get-Item $p` works for you?

**Comment by sba923** [comment] 2020-10-31 17:10
Yes it does:

````
PS> $i=get-item $p
PS> $i.FullName
C:\Users\steph\OneDrive\test\test01\test02\test03\test04\test05\test06\test07\test08\test09\test10\test11\test12\test13\test14\test15\test16\test17\test18\test19\test20\test21\test22\test23\test24\test25\test26\test27\test28\test29\test30\test31\test32\test33\test34\test35\test36\test37\test38\test39\test40\test.txt
PS> $i

    Directory:  C:\Users\steph

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
la---        2020-10-31     08:44        6   test.txt
````

but of course that's because I have set `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` to 1

**Comment by fMichaleczek** [comment] 2020-11-03 01:03
@sba923 

This code failed because it depends on the "longPathAware" setting defined in the Win32 application manifest.
https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests

The RID of PowerShell for Windows is still Windows 7, and Long Path support is I believe a Windows 10 cleaning effort, so I don't know if it could apply for all windows release. If you want to ask the PowerShell team to activate longPathAware, it's something to take in consideration.

I take this source code as an universal reproductible sample.
```
$filePath = "$env:USERPROFILE\test\test01\test02\test03\test04\test05\test06\test07\test08\test09\test10\test11\test12\test13\test14\test15\test16\test17\test18\test19\test20\test21\test22\test23\test24\test25\test26\test27\test28\test29\test30\test31\test32\test33\test34\test35\test36\test37\test38\test39\test40\test.txt"

New-Item -Path $filePath -Value "1" -Force

Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
using System.ComponentModel;

namespace NTFS
{
    public class ExtendedFileInfo
    {
        [DllImport("kernel32.dll", SetLastError=true, EntryPoint="GetCompressedFileSize")]
        static extern uint GetCompressedFileSizeAPI(string lpFileName, out uint lpFileSizeHigh);

        public static ulong GetCompressedFileSize(string filename)
        {
            uint high;
            uint low;
            low = GetCompressedFileSizeAPI(filename, out high);
            int error = Marshal.GetLastWin32Error();
            if (high == 0 && low == 0xFFFFFFFF && error != 0)
				throw new Win32Exception(error);
            else
				return ((ulong)high << 32) + low;
        }
    }
}
'@

[NTFS.ExtendedFileInfo]::GetCompressedFileSize($filePath)
```

Failed with "**The system cannot find the path specified.**"

This code activate the "longPathAware" in the current process, so the method GetCompressedFileSize works. ( See the link bellow for more details ).
https://stackoverflow.com/questions/58563335/make-maf-addinprocess-exe-long-path-aware

```
Add-Type -CompilerOptions "/unsafe" -TypeDefinition @'
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;

public class ApplicationHelper
{
	// Adapted from https://www.pinvoke.net/default.aspx/ntdll.ntqueryinformationprocess
	public static void SetIsLongPathAwareProcess()
	{
		var currentProcess = Process.GetCurrentProcess();
		IntPtr hProc = currentProcess.Handle;

		IntPtr pPbi = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(Native.PROCESS_BASIC_INFORMATION)));
		IntPtr outLong = Marshal.AllocHGlobal(sizeof(long));

		int status = Native.NtQueryInformationProcess(hProc, 0, pPbi, (uint)Marshal.SizeOf(typeof(Native.PROCESS_BASIC_INFORMATION)), outLong);

		Marshal.FreeHGlobal(outLong);

		//STATUS_SUCCESS = 0
		if (status == 0)
		{
			var pbi = Marshal.PtrToStructure<Native.PROCESS_BASIC_INFORMATION>(pPbi);
			var pPeb = pbi.PebBaseAddress;

			var peb = Marshal.PtrToStructure<Native.PEB_Beginning>(pPeb);

			var bitField1 = peb.BitField1;
			peb.BitField1 = bitField1 | Native.PEBBitField1.IsLongPathAwareProcess;
			Marshal.StructureToPtr<Native.PEB_Beginning>(peb, pPeb, false);
		}

		//Free allocated space
		Marshal.FreeHGlobal(pPbi);
	}

	static class Native
	{
		// http://pinvoke.net/default.aspx/Structures/PROCESS_BASIC_INFORMATION.html
		[StructLayout(LayoutKind.Sequential, Pack = 1)]
		internal struct PROCESS_BASIC_INFORMATION
		{
			public IntPtr ExitStatus;
			public IntPtr PebBaseAddress;
			public IntPtr AffinityMask;
			public IntPtr BasePriority;
			public UIntPtr UniqueProcessId;
			public IntPtr InheritedFromUniqueProcessId;

			public int Size
			{
				get { return (int)Marshal.SizeOf(typeof(PROCESS_BASIC_INFORMATION)); }
			}
		}

		[Flags]
		internal enum PEBBitField1 : byte
		{
			None = 0,
			ImageUsesLargePages = 1 << 0,
			IsProtectedProcess = 1 << 1,
			IsImageDynamicallyRelocated = 1 << 2,
			SkipPatchingUser32Forwarders = 1 << 3,
			IsPackagedProcess = 1 << 4,
			IsAppContainer = 1 << 5,
			IsProtectedProcessLight = 1 << 6,
			IsLongPathAwareProcess = 1 << 7
		}

		// Note: this only contains the "beginning" of the PEB structure
		// but that is all we need for access to the IsLongPathAwareProcess bit
		// Used as a guide: https://github.com/processhacker/processhacker/blob/master/phnt/include/ntpebteb.h#L75
		// Related: https://docs.microsoft.com/en-us/windows/win32/api/winternl/ns-winternl-peb
		[StructLayout(LayoutKind.Sequential, Pack = 1)]
		internal struct PEB_Beginning
		{
			Byte InheritedAddressSpace;
			Byte ReadImageFileExecOptions;
			Byte BeingDebugged;
			public PEBBitField1 BitField1;
		};

		// https://www.pinvoke.net/default.aspx/ntdll.ntqueryinformationprocess
		[DllImport("ntdll.dll", SetLastError = true)]
		internal static extern int NtQueryInformationProcess(IntPtr processHandle, int processInformationClass, IntPtr processInformation, uint processInformationLength, IntPtr returnLength);

		// The below is for test purposes only:
		// Include CreateDirectory for testing if the long path aware changes work or not.
		// Requires SECURITY_ATTRIBUTES
		// http://pinvoke.net/default.aspx/kernel32/CreateDirectory.html?diff=y
		[DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Auto, BestFitMapping = false)]
		internal static extern bool CreateDirectory(String path, SECURITY_ATTRIBUTES lpSecurityAttributes);


		// https://www.pinvoke.net/default.aspx/Structures/SECURITY_ATTRIBUTES.html
		[StructLayout(LayoutKind.Sequential)]
		internal class SECURITY_ATTRIBUTES
		{
			internal int nLength = 0;
			// don't remove null, or this field will disappear in bcl.small
			internal unsafe byte* pSecurityDescriptor = null;
			internal int bInheritHandle = 0;
		}
	}
}
'@
[ApplicationHelper]::SetIsLongPathAwareProcess()
[NTFS.ExtendedFileInfo]::GetCompressedFileSize($filePath)
```
Return 1

**Comment by iSazonov** [comment] 2020-11-03 03:27
Great example! But we cannot use this until it will be documented or used somewhere in Windows SDK.

**Comment by fMichaleczek** [comment] 2020-11-03 13:18
@iSazonov I don't understand what should be documented. 
I'm sorry, I only write a POC, see more advanced diagnostics bellow :

A quick summary :
- @sba923 want to use the Win32 function [_GetCompressedFileSizeW_](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getcompressedfilesizew) 
- On _Windows 10 1607 and more_, it's failed on long path because PowerShell doesn't have a _Win32 application manifest_ which include the [_longPathAware_](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getcompressedfilesizew)

The method _SetIsLongPathAwareProcess_ in my previous sample was a simple hack to test the dependency between _GetCompressedFileSizeW_ /_longPathAware_ and provide a workaround for @sba923 

Because the requirement of _longPathAware_ is Win10 1607+, I'm not sure how it should be enabled in netcore/Win32/msbuild component without separate Win7/Win10 projects.

I hope I help to clarify, I don't think it's urgent because [net5.0 design](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#why-are-the-os-specific-flavors-not-versioned-by-the-os) about Windows and _Minimum OS API Level_ had changed, so net6.0 should be a better branch to cover these scenarios.


So, this issue should depend on a root issue which could be called "_Manage Win32 Application Manifest abroad all Windows release in net6.0_". I'm not sure but the change should be driven by [PowerShell/GraphicalTools/issues/101](https://github.com/PowerShell/GraphicalTools/issues/101)  /cc @TylerLeonhardt

**Comment by sba923** [comment] 2020-11-03 18:32
What's weird is that PowerShell **itself** (e.g. `Get-Item`) has no problem dealing with those long pathnames. The problem arose when I wanted to use code in a compiled assembly or code compiled dynamically via `Add-Type`.

**Comment by fMichaleczek** [comment] 2020-11-04 10:14
@sba923 no it's not weird, it's more a long story in the Microsoft area. This issue will not be closed in 5 minutes, so your workarounds are the one to activate the longPathAware at runtime or .. you have to deal with \\?\ (see the docs 
  https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces)

**Comment by iSazonov** [comment] 2021-01-18 12:59
Close as stale issue. Feel free to continue discussion.

**Closed by iSazonov** 2021-01-18 12:59 UTC
Labels: Issue-Question, WG-Engine-Providers
