### ISSUE TITLE
No completion for Properties of $Error[n]

### ISSUE THREAD

**Issue by nbros** [PowerShell/PowerShell#16941] opened 2022-03-01 08:09 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/141089/156128492-903addd4-dcb4-47e5-bbd7-30ca68228254.png)

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 245
BufferHeight: 67
```

### Steps to reproduce

```
> Write-Error "an error"
> $Error[0]. <-- type <tab> or Ctrl+Space to try to complete Properties of System.Management.Automation.ErrorRecord
```

### Expected behavior

Powershell should return completions of `System.Management.Automation.ErrorRecord`

### Actual behavior

Powershell apparently returns completions of `Array` instead of `ErrorRecord`.

**Comment by MartinGC94** [comment] 2022-03-02 02:25
If you unload PSReadline and try tab completing or invoke TabExpansion2 manually you get the expected results. I think the issue is that PowerShell looks at the current scope, and I guess $error exists but is empty in the PSReadline module scope.

**Comment by iSazonov** [comment] 2022-03-02 08:09
See #3568 for no success history.

**Comment by MartinGC94** [comment] 2022-03-02 22:30
He said:
> The original fix I made had a bad assumption as there is a valid $script:error variable.

If that's true then I don't see how this can be fixed without some sort of hack, PowerShell is correctly finding the $Error variable in the PSReadline scope.  
So the question becomes, how should the hack be implemented? Should the completion code have a special case for $Error if no results are found? Should the Safe Expression Value code have a special case for $Error within the PSReadline scope? Should PSReadline provide its own completions for $Error?

**Comment by iSazonov** [comment] 2022-03-03 05:59
If I understand correctly current status is that the issue presents **only** if PSReadline is loaded. If so maybe @daxian-dbw advice.

**Comment by sdwheeler** [comment] 2023-08-16 17:47
Completion of `$global:Error[0].Fu<tab>` works with PSReadLine loaded.

**Comment by daxian-dbw** [comment] 2023-09-13 20:42
The above fix could work, but there is also possibility that the `PSConsoleHostReadLine` function from PSReadLine will depend on state in the module in future, and in that case the function won't work properly if it's disconnected with the PSReadLine session state.

So, maybe the fix needs to happen in the tab completion code, for example, `CommandCompletion.CompleteInput` offers an additional parameter to allow the caller to choose running it with the top-level session state.

**Closed** 2024-03-19 11:15 UTC
Labels: Issue-Bug, WG-Interactive-IntelliSense, Resolution-No Activity
