### ISSUE TITLE
PowerShell should tell me how to install missing commands

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#3309] opened 2017-03-10 23:31 UTC
Steps to reproduce
------------------
run a command which doesn't come by default in the distribution but the package manager knows about such as `kvm-ok` on ubuntu

Expected behavior
-----------------
```
The program 'kvm-ok' is currently not installed. You can install it by typing:
sudo apt install cpu-checker
```

Actual behavior
---------------
```
kvm-ok : The term 'kvm-ok' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ kvm-ok
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (kvm-ok:String) [], CommandNotF 
   oundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                          
----                           -----                                          
PSVersion                      6.0.0-alpha                                    
PSEdition                      Core                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                        
BuildVersion                   3.0.0.0                                        
GitCommitId                    v6.0.0-alpha.17                                
CLRVersion                                                                    
WSManStackVersion              3.0                                            
PSRemotingProtocolVersion      2.3                                            
SerializationVersion           1.1.0.1    
```

**Comment by SteveL-MSFT** [comment] 2017-03-10 23:51
Would be great to have this capability with cmdlets from PSGallery

**Comment by andschwa** [comment] 2017-03-13 17:58
I believe this is a duplicate of #1982.

**Comment by SteveL-MSFT** [comment] 2017-03-13 18:04
@andschwa agree

**Closed by SteveL-MSFT** 2017-03-13 18:04 UTC
Labels: Issue-Enhancement, OS-Linux, Resolution-Duplicate
