### ISSUE TITLE
Fix Here-String Indentation

### ISSUE THREAD

**Issue by dustindortch** [PowerShell/PowerShell#8085] opened 2018-10-19 12:41 UTC
With a Here-String, one must align the content and the close to the left without whitespace for it to work properly. It would be great if the close didn't require no indentation (but could be required to be on its own line, minus the whitespace). Then, however far it is indented, remove that leading whitespace from the content.

As an example, the dashes would be whitespace:

```powershell
Function Name {
  Param()
  $Message = @"
  String value
  Other value
    More indentation
  "@
}
```

It would be awesome if the value of $Message would be:
```none
String value
Other value
  More indentation
```

**Comment by vexx32** [comment] 2018-10-19 13:00
For a more lengthy difference sample, I submit my [Write-MeditationPrompt](https://github.com/vexx32/PSKoans/blob/master/PSKoans/Private/Write-MeditationPrompt.ps1) function from PSKoans.

Without this change, I have to keep my here-strings in a hashtable to contain the chaos:
```powershell
    #region Prompt Text
    $Prompts = @{
        Welcome        = @"
    Welcome, seeker of enlightenment.
    Please wait a moment while we examine your karma...
"@
        Describe       = @"
Describing '$DescribeName' has damaged your karma.
"@
        TestFailed     = @"
    You have not yet reached enlightenment.
    The answers you seek...
"@
        Expectation    = $Expectation
        Meditate       = @"
    Please meditate on the following code:
"@
        Subject        = @"
[It] $ItName
$Meditation
"@
        Wisdom         = @"
    $($Koan -replace "`n","`n    ")
    Your path thus far:
"@
        OpenFolder     = @"
You may run 'Measure-Karma -Meditate' to begin your meditation.
"@
        Completed      = @"
    Congratulations! You have taken the first steps towards enlightenment.
    You cast your gaze back upon the path that you have walked:
"@
        BookSuggestion = @"
    If you would like to further your studies in this manner, consider investing in
    'PowerShell by Mistake' by Don Jones - https://leanpub.com/powershell-by-mistake
"@
    }
    #endregion Prompt Text
```

Although, granted, the reason this screws with indentation so much is because here-strings take all things, even whitespace, literally. 😕 

It's handy to be able to do in cases like this, but... simple things like this suggestion might make them more workable, perhaps?

**Comment by lzybkr** [comment] 2018-10-19 16:59
This is a duplicate of https://github.com/PowerShell/PowerShell/issues/2337

**Closed** 2018-10-19 18:50 UTC
Labels: Resolution-Duplicate
