### ISSUE TITLE
Send-MailMessage changes attachment file name on Linux

### ISSUE THREAD

**Issue by Peperud** [PowerShell/PowerShell#6564] opened 2018-04-04 21:34 UTC
Steps to reproduce
------------------

```powershell
Send-MailMessage -Priority High `
-From $NotificationFrom ` 
-To $NotificationTo ` 
-SmtpServer $SMTPServer ` 
-Subject "Attachment renamed in linux" ` 
-Body 'Test' `
-Attachments @('something.zip')

```

Expected behavior
-----------------
<pre>
Receive an attachment, named <b>'something.zip'</b>
</pre>

Actual behavior
---------------
<pre>
Received an attachment named <b>folder1folder2folder3something.zip</b>
where <b>/folder1/folder2/folder3</b> is the current folder

Issue present on Linux only.
</pre>

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment] 2018-04-05 09:17
The problem is in [corefx](https://github.com/dotnet/corefx/blob/abc007cbd6ef6180f1e044547d6441058122203a/src/System.Net.Mail/src/System/Net/Mail/Attachment.cs#L15) where they determine just the filename incorrectly expecting Windows directory separators.

**Comment by SteveL-MSFT** [comment] 2018-04-13 14:30
Fix in corefx was merged, so we should get this when we pick up future corefx after 2.1 Preview2

**Comment by SteveL-MSFT** [comment] 2018-05-05 17:12
This should be fixed in latest nightly build w/ dotnetcore2.1-rc1

**Closed by SteveL-MSFT** 2018-05-05 17:12 UTC
Labels: Area-Cmdlets-Utility, Issue-Bug, Resolution-Fixed, Waiting - DotNetCore
