### ISSUE TITLE
"Failed to create CoreCLR, HRESULT: 0x80004005" on Ubuntu 20.04.1 LTS ARM 64-bit  in Docker

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#13953] opened 2020-10-30 23:59 UTC
## Summary

I tried to run PowerShell 7.1.0 RC2 on Ubuntu 20.04.1 LTS 64-bit, on a Raspberry Pi 3 B+, in a Docker container. PowerShell fails to launch.

## Steps to reproduce

1. Obtain a Raspberry Pi 3 B+
1. Install Ubuntu Server 20.04.1 LTS on a microSD card
1. Install Docker
1. Pull the `arm64v8/ubuntu` container image, and run a container
1. Download PowerShell ARM64 `powershell-7.1.0-rc.2-linux-arm64.tar.gz`
1. Extract the archive
1. Try to run `./pwsh`

```
docker run --rm -it arm64v8/ubuntu:focal
apt update && apt install wget --yes
wget 'https://github.com/PowerShell/PowerShell/releases/download/v7.1.0-rc.2/powershell-7.1.0-rc.2-linux-arm64.tar.gz'
tar -xzvf powershell-7.1.0-rc.2-linux-arm64.tar.gz
./pwsh
```

## Expected behavior

PowerShell runs

## Actual behavior

```none
root@30010574f698:/# ./pwsh
Failed to create CoreCLR, HRESULT: 0x80004005
```

## Notes

I tried the suggestion here, but it didn't change the behavior. https://github.com/PowerShell/PowerShell/issues/13166

**Comment by iSazonov** [comment] 2020-10-31 13:04
@pcgeek86 Please collect and share log as suggested in #13166.

**Comment by alexei-matveev** [comment] 2021-04-23 14:52
I bet it cannot write to TMPDIR, see https://github.com/dotnet/runtime/issues/46462

**Comment by daxian-dbw** [comment] 2021-11-15 19:30
Close as a duplicate of #13166

**Closed by daxian-dbw** 2021-11-15 19:30 UTC
Labels: Issue-Question, Area-Maintainers-Build
