### ISSUE TITLE
MetadataError when assigning null to nullable type

### ISSUE THREAD

**Issue by jantari** [PowerShell/PowerShell#13651] opened 2020-09-17 22:20 UTC
## Steps to reproduce

It is very simple:

```powershell
[Nullable[bool]]$variable = if ($false) { 1 }
```

## Expected behavior

It should just assign `$null` to the variable:

```powershell
PS> # This doesn't work, it's just for illustration what SHOULD happen
PS> [Nullable[bool]]$variable = if ($false) { 1 }
PS> $variable -eq $null
True
```

## Actual behavior

The assignment fails with an error, it's apparently getting a PSCustomObject from somewhere (?) and trying to cast that to a bool.

```powershell
PS> [Nullable[bool]]$variable = if ($false) { 1 }
MetadataError: Cannot convert value "System.Management.Automation.PSCustomObject" to type "System.Nullable`1[System.Boolean]". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
```

Worth noting however, that these work as expected:

With dynamic typing:

```powershell
PS> $variable = if ($false) { 1 }
PS> $variable -eq $null
True
```

Directly assigning `NULL` without shenanigans:

```powershell
PS> [Nullable[bool]]$variable = $null
PS> $variable -eq $null
True
```

## Environment data

Both stable and preview PowerShell 7 affected:

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.20215
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.7
PSEdition                      Core
GitCommitId                    7.1.0-preview.7
OS                             Microsoft Windows 10.0.20215
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Possibly worth noting, Windows PowerShell 5.1 is also affected.

**Comment by vexx32** [comment] 2020-09-17 23:01
This is _probably_ because assigning the result of `if ($false) { ... }` to anything results in assigning the value from `[System.Management.Automation.Internal.AutomationNull]::Value` to the variable.

I get the same error doing that directly:
```
PS C:\Users\joelp> [nullable[bool]]$var = [System.Management.Automation.Internal.AutomationNull]::Value
MetadataError: Cannot convert value "System.Management.Automation.PSCustomObject" to type "System.Nullable`1[System.Boolean]". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
```

This is something we should probably handle in the LanguagePrimitives conversion methods; we do checks that treat null and automation null the same, but we should be doing similar when the expected type result is Nullable<bool> that we're probably only doing for just plain bool.

**Comment by mklement0** [comment] 2020-09-17 23:23
Indeed,  @vexx32. 

More generally speaking, the problem is that type-constraining to `[bool]` - whether nullable or not - applies _parameter_ semantics, not _expression_  semantics:

```powershell
# OK - assigns $true
PS> $var = [bool] 'convert-me-too-bool'

# !! BREAKS
PS> [bool] $var = 'convert-me-too-bool'
```

In other words: this is a duplicate of #10426,

**Closed** 2020-09-19 20:00 UTC
Labels: Issue-Question, Resolution-Duplicate
