### ISSUE TITLE
Please support Ubuntu 24.04 as soon as possible，thku

### ISSUE THREAD

**Issue by eccsatan** [PowerShell/PowerShell#21548] opened 2024-04-29 02:02 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Can't install on ubuntu 24.04，feel anxious。

### Expected behavior

```console
Can't install on ubuntu 24.04，feel anxious。
```

### Actual behavior

```console
Can't install on ubuntu 24.04，feel anxious。
```

### Error details

```console
Can't install on ubuntu 24.04，feel anxious。
```

### Environment data

```powershell
Can't install on ubuntu 24.04，feel anxious。
```

**Comment by rhubarb-geek-nz** [comment] 2024-04-29 05:39
```
 wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb

$ sudo dpkg -i powershell_7.4.2-1.deb_amd64.deb
Unpacking powershell (7.4.2-1.deb) ...
dpkg: dependency problems prevent configuration of powershell:
 powershell depends on libicu72 | libicu71 | libicu70 | libicu69 | libicu68 | libicu67 | libicu66 | libicu65 | libicu63 | libicu60 | libicu57 | libicu55 | libicu52; however:

$ dpkg -l| grep libicu
ii  libicu74:amd64                     74.2-1ubuntu3                     amd64        International Components for Unicode
```

Current deb does not work on ubuntu 24.04

**Comment by StevenBucher98** [comment] 2024-04-29 16:52
Duplicate of https://github.com/PowerShell/PowerShell/issues/21385

**Closed** 2024-04-30 17:44 UTC
Labels: Resolution-Duplicate, Distribution-Request

**Comment by JAMIL8051** [comment] 2024-06-29 03:41
# Easy Workaround Unitll dear Microsoft upgrades their **_libicu_** for Ubuntu 24.04 LTS
First download the Ubuntu Manitc package for libicu72 from this link:
https://mirror.it.ubc.ca/ubuntu/pool/main/i/icu/

Steps to run :
$ sudo apt get update
$ wget https://mirror.it.ubc.ca/ubuntu/pool/main/i/icu/libicu72_72.1-3ubuntu3_amd64.deb
$ sudo dpkg -i libicu72_72.1-3ubuntu3_amd64.deb
$ wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/powershell_7.4.3-1.deb_amd64.deb
$ sudo dpkg -i powershell_7.4.3-1.deb_amd64.deb
$ pwsh
Final Output:
PowerShell 7.4.3
PS /home//
These commands will install Pwsh 7.4.3. A similar process can be followed to install 7.4.2.
The main trick is installing the libicu72 package from the Ubuntu package website because Microsoft is still using the old libicu72. So until Microsoft Updates Libicu on their end, it will always throw an error: So this workaround can be used for now

**Comment by notNullThen** [comment] 2024-07-12 17:33
You can use snap:
```bash
snap install powershell --classic
```
Works well on my Ubuntu 24.04 LTS

**Comment by Giantvince1** [comment] 2024-09-25 07:11
> You can use snap:
> 
> ```shell
> snap install powershell --classic
> ```
> 
> Works well on my Ubuntu 24.04 LTS

We are here explicitly to avoid using snap. At least, I am. I'm running Linux Mint 22, based on Ubuntu 24.04, and ever since snap's inception, they've had it disabled by default (which is a GOOD thing IMO). I was hoping their own repo would hold PowerShell 7.4.5 by now for 24.04, but no luck.

**Comment by srbrills** [comment] 2024-10-15 17:59
Verified this works for PowerShell v7.4.5 as well, on Ubuntu 24.04.1 LTS WSL.
