### ISSUE TITLE
Segmentation fault 11 on macOS M1 machine running pwsh -c or -file

### ISSUE THREAD

**Issue by rkeithhill-keysight** [PowerShell/PowerShell#18998] opened 2023-01-21 05:22 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm not entirely sure this would be easily reproducible on somebody else's M1. My M1 build machine was working just fine as a Jenkins build agent until I rebooted it this evening.  Then my builds started hanging on this node where it first tries to run a PowerShell script.  After some debugging, I found out that trying to launch `pwsh -c '<command>'` causes a segmentation fault.  Same with `-file`.  What's odd is that I can start `pwsh` just fine:

![image](https://user-images.githubusercontent.com/103770981/213844695-9e53ab18-38dc-4294-a8cf-a043cdd1e26b.png)

### Expected behavior

```console
Well, PowerShell should not crash, right?
```

### Actual behavior

```console
I'm seeing a segmentation fault.
```

### Error details

```console
% pwsh -nop -c 'get-date'
zsh: segmentation fault  pwsh -nop -c 'get-date'
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:29:57 PST 2022; root:xnu-8020…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Also:

 % which pwsh
/usr/local/bin/pwsh

% ls -al /usr/local/bin/pwsh
lrwxr-xr-x  1 root  wheel  38 Jan 20 21:42 /usr/local/bin/pwsh -> /usr/local/microsoft/powershell/7/pwsh

# I also have several versions of the .NET SDK and Runtime installed on this system. That shouldn't matter, right?

% dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]
  6.0.404 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Visuals

![image](https://user-images.githubusercontent.com/103770981/213844837-3b1dfca9-3b65-49d3-9769-f9cd72fc2202.png)

**Comment by rkeithhill-keysight** [comment] 2023-01-21 05:34
BTW I tried `-nop` and still get a seg fault:

![image](https://user-images.githubusercontent.com/103770981/213845233-302cdcfc-acf4-4bb6-8e3f-abef9a15a1aa.png)

**Comment by rkeithhill-keysight** [comment] 2023-01-21 06:17
FYI, downgrading to 7.3.0 has fixed this issue.

**Comment by bobrozelle** [comment] 2023-01-24 15:53
Same behavior as https://github.com/PowerShell/PowerShell/issues/18958

**Comment by rkeithhill-keysight** [comment] 2023-01-25 17:51
After 4 days of using 7.3.0 in my Jenkins pipeline (pwsh -c), 7.3.0 is now seg faulting on this command!

![image](https://user-images.githubusercontent.com/103770981/214642476-be398ae2-2c3c-4c3c-b91c-f3a5a1130d37.png)

WTF?  @SteveL-MSFT Any suggestions on a potential workaround - other than uninstalling and installing a different version? That only seems to work for a few days.  This is impacting our product devops because we use PowerShell to orchestrate build & test on Mac M1.

**Comment by rkeithhill-keysight** [comment] 2023-01-25 17:57
I removed 7.3.0 and installed 7.3.2 (that must be pretty new) and now `pwsh -c` works again.  Let's see how long 7.3.2 can go before it starts seg faulting. :-)

**Comment by SteveL-MSFT** [comment] 2023-01-27 20:06
Unfortunately, not able to repro this.  Was able to find two PRs in dotnet/runtime that is related to the area given the stacktrace (thanks!) https://github.com/dotnet/runtime/search?q=issharedbygenericinstantiations&type=issues.  Need to look deeper next week.

**Comment by daxian-dbw** [comment] 2023-01-30 19:04
The puzzling part in the report is that the crash doesn't happen consistently -- it started to happen after using 7.3.0 for 4 days.

The stack trace suggests the crash happened when [JIT start profile](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.profileoptimization.startprofile?view=net-7.0) kicks in, which does early compilation on the methods that were used the last time `pwsh` going through the same code path -- in this case for `pwsh -c` or `pwsh -file`, non-interactive execution ([_ProfileOptimization.StartProfile("StartupProfileData-NonInteractive")_](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L262)).

So, it makes sense that running `pwsh` itself works, because that will be interactive execution, which will be using a different profile: [_ProfileOptimization.StartProfile("StartupProfileData-Interactive")_](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#LL252C25-L252C91).

@rkeithhill-keysight Can you please try the following when `pwsh -c "get-date"` results in segment fault, and see if the next run of `pwsh -c` works:
- remove the `StartupProfileData-NonInteractive` file under `/home/<user-name>/.cache/powershell`

Having this file removed will make CLR not attempt to do the early method compilation, so if this theory is correct, the next run of `pwsh -c "get-date"` should work again. If you can verify this is the case, I will open an issue on this in the .NET repo.

**Comment by rkeithhill-keysight** [comment] 2023-01-30 19:07
@daxian-dbw Yes, I'll give that a try if/when we encounter the seg fault again.

**Comment by daxian-dbw** [comment] 2023-02-07 23:59
.NET issue opened: https://github.com/dotnet/runtime/issues/81799

**Comment by rkeithhill-keysight** [comment] 2023-06-03 18:48
And now 7.3.2 has started to gen seg faults ~5 1/2 months after installing 7.3.2. 🤷‍♂️ 

I tried @daxian-dbw suggestion to remove the `StartupProfileData-NonInteractive` file and that fixes it. Not sure how long the fix will last but my CI/CD builds are running again on this M1 mini.

**Comment by daxian-dbw** [comment] 2023-06-05 16:19
@rkeithhill-keysight The root cause is in .NET, see https://github.com/dotnet/runtime/issues/81799. Please try collecting a dump when the crash happens, and share the dump in the .NET issue -- they need a dump to further investigate the issue (see https://github.com/dotnet/runtime/issues/81799#issuecomment-1486151122).

**Comment by rkeithhill-keysight** [comment] 2023-06-05 16:43
I read the .NET issue **after** I had fixed it. 🤦‍♂️  Next time this happens, I'll collect a dump and post it there.

**Comment by GordonVi** [comment] 2023-07-12 15:43
Just ran into this after updating powershell on CentOS:

pwsh 7.3.5 (old was 7.3.4)

commands:

# update powershell
sudo yum update powershell 

# Set permissions for powershell to run commands
sudo setcap cap_net_raw=eip /opt/microsoft/powershell/7/pwsh   # real binary, not symlink

# rename offending config file
 mv /home/user/.cache/powershell/StartupProfileData-NonInteractive /home/user/.cache/powershell/StartupProfileData-NonInteractive.disable

**Closed** 2024-01-16 12:40 UTC
Labels: Issue-Bug, Area-Maintainers-Build, 7.3-Triage, Resolution-No Activity

**Comment by rkeithhill-keysight** [comment] 2024-09-20 21:01
FWIW it appears this issue was fixed in .NET.  Here's the [.NET issue](https://github.com/dotnet/runtime/issues/81799) and here's the [PR that fixes it](https://github.com/dotnet/runtime/pull/98825).

**Comment by pregress** [comment] 2025-02-25 08:15
Can this be re-opend please?
I had the same issue on 7.5.0. 

Disabling the file: `mv ~/.cache/powershell/StartupProfileData-NonInteractive ~/.cache/powershell/StartupProfileData-NonInteractive.disable` solved it, as suggested by @GordonVi 

```
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Ubuntu 22.04.5 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
