### ISSUE TITLE
Pathological behavior of += / -= operators with file attributes.

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16478] opened 2021-11-16 14:43 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is the recommended method of setting and removing the `hidden` attribute on a file, and in the normal case this works correctly, for example:

```console
v ~
rkitover@woobie > ni foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi foo).attributes += 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-h-          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/16/2021  2:32 PM              0 foo
```

Now observe what happens when the attribute modification operation is repeated:

```console
v ~
rkitover@woobie > gi foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi foo).attributes += 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-h-          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes += 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a--s          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes += 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-hs          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes += 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/16/2021  2:32 PM              0 foo
```

The behavior of the `-=` operator is even worse:

```console
v ~
rkitover@woobie > gi foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
---hs          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
----s          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
---h-          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-----          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a-hs          11/16/2021  2:32 PM              0 foo

v ~
rkitover@woobie > (gi -fo foo).attributes -= 'hidden'
v ~
rkitover@woobie > gi -fo foo

    Directory: C:\Users\rkitover

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a--s          11/16/2021  2:32 PM              0 foo
```

### Expected behavior

I expect that adding the attribute would add it if it doesn't exist, and either do nothing or throw an error if it already exists.

Likewise, I expect that removing the attribute would remove it if it exists, and either do nothing or throw an error if it doesn't exist.

### Actual behavior

It seems to be flipping bits on the file metadata randomly.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22499
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment] 2021-11-16 16:02
`System.IO.FileAttributes` is an enum type:
```
 > [enum]::GetValues([io.FileAttributes]) | % { '{0,-17}: {1}' -f $_, [int]$_ }
ReadOnly         : 1
Hidden           : 2
System           : 4
Directory        : 16
Archive          : 32
Device           : 64
Normal           : 128
Temporary        : 256
SparseFile       : 512
ReparsePoint     : 1024
Compressed       : 2048
Offline          : 4096
NotContentIndexed: 8192
Encrypted        : 16384
IntegrityStream  : 32768
NoScrubData      : 131072
```
2 + 2 = 4 (system)

**Comment by jborean93** [comment] 2021-11-16 19:05
Adding to the above you are not meant to add or subtract flag enums together as that causes invalid values. While the raw value is an integer which is why `+=` and `-=` just adds or subtracts the value of that flag it won't result in the same value. You should use `-bor` to add flags and `-band -bnot` to remove flags;

```powershell
[IO.FileAttributes]::Directory -bor [IO.FileAttributes]::Hidden

[IO.FileAttributes]"Directory, Hidden" -band -bnot [IO.FileAttributes]::Hidden
```

In these examples `Hidden` is equal to `0x2` and `Directory` is equal to `0x10

```
# Hex == Binary == Decimal
0x02 == 0000 0010 == 2
0x10 == 0001 0000 == 16

# Bitwise OR will set bits that are present in both the LHS and RHS
0001 0000 -bor 0000 0010 == 0001 0010 == 0x12 == 18

# Bitwise AND will set bits only present in both sides
# Bitwise NOT will reverse the bits of it's RHS
# Combine both together and you can remove a flag
-bnot 0000 0010 == 1111 1101 == 0xFFFFFFFD == -3
0001 0010 -band 1111 1101 == 0001 0000 == 0x10 == 16
```

The beauty of bitwise operations is you can run them multiple times as they operate on the bits set rather than addition or subtraction which always adds or removes the value.

**Comment by rkitover** [comment] 2021-11-16 20:49
I'm sorry, but from my perspective as a user and casual script writer, if this simple operation corrupts the file system that is definitely wrong and definitely a bug.

**Comment by jborean93** [comment] 2021-11-16 21:12
From a perspective of a casual/new to PowerShell/Programming script writer I can somewhat sympathize but using bitwise operations is how this stuff is done. You can't really use general addition/subtraction on these values and while it works in some cases it will most likely cause problems.

To me this is a feature request to have `+=` and `-=` act like the bitwise operators which I'm unsure whether PowerShell could or could not do. It's not a bug as it's working as intended but it might be a good idea to implement such a functionality to help people new to this concept going forward.

**Comment by rkitover** [comment] 2021-11-16 21:33
In this particular case, how would you even know that any of this involves bits, and why would you care? The interface is adding a string attribute to a file. And since there is no modifying operator for `-bor`, the "correct" way to do this would be something like this:

```powershell
$attr = (gi -fo foo).attributes; (gi -fo foo).attributes = $attr -bor 'hidden';
```

which is extremely tedious for what should be the extremely simple operation of making a file hidden.

There is probably a nicer way to do this that I don't know, but it will probably also suck.

Also I have to say that I'm probably not the only person offended by the quick marking of everything in this project as a "question" even when the answer is far from adequate.

**Comment by SeeminglyScience** [comment] 2021-11-16 21:55
> The interface is adding a string attribute to a file.

It's not really a string, that's sort of a case of PowerShell already making it a bit easier behind the scenes.  The string is converted to a call like `[IO.FileAttributes]::Parse('hidden')` by the binder.
 
> which is extremely tedious for what should be the extremely simple operation of making a file hidden.

It is a simple operation, but it doesn't come up often. It'd be nice to have a `-bor` and `-band` assignment operator but outside of this it probably wouldn't get a lot of use.

**Comment by jborean93** [comment] 2021-11-16 21:57
> In this particular case, how would you even know that any of this involves bits, and why would you care? 

When it's an enum with flags (an enum with multiple values) then it will use bits. While I know `Attributes` itself is an enum this because I've dealt with it before you can determine this dynamically

```powershell
> Get-Item $pwd.Path | Get-Member -Name Attributes

   TypeName: System.IO.DirectoryInfo

Name       MemberType Definition
----       ---------- ----------
Attributes Property   System.IO.FileAttributes Attributes {get;set;}
```

I can see it's not a string and by deduction based on the purpose I can usually come to the conclusion it's an enum. When in doubt a quick check online on [System.IO.FileAttributes](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-5.0) type or doing `$obj.Attributes -is [Enum]` tells me definitively.

> And since there is no modifying operator for -bor, the "correct" way to do this would be something like this:

In your particular use case you need to pass it by type rather than just the string

```powershell
$file = Get-Item -Path foo -Force
$file.Attributes = $file.Attributes -bor [IO.FileAttributes]"Hidden"
```

This is because bitwise operations work on numerical values and the operator doesn't know how to cast the string to the possible enum on the LHS. The only thing I find that sucks is that you need to do `$obj.Attributes = $obj.Attributes -bor` rather than the equivalent to `+=` (in bitwise terms other languages use `|=` to bitwise OR and set at the same time. For example in C# you can do the following to replicate adding and removing a flag (what `-bor` and `-band -bnot` does) to an existing value:

```csharp
file.Attributes |= FileAttributes.Hidden
file.Attributes &= ~FileAttributes.Hidden
```
But in PowerShell this isn't possible today which can be annoying.

> Also I have to say that I'm probably not the only person offended by the quick marking of everything in this project as a "question" even when the answer is far from adequate.

Let me preface the following by saying I am no way affiliated with Microsoft or the PowerShell team and am just a community user of PowerShell who tries to help out where I can.

First off I am sorry that this your experience and can totally understand how closing issue reports quickly can bring across a negative experience. On the flip side you have to understand that this repository is very large with a lot of issues being reported and thus is is very important to try and filter out what are bugs and what might just be misunderstandings or general questions. 

Now this comes to the tricky question of what constitutes a bug and while you may think it is a bug because it doesn't do what you expect the truth of the matter is this is the expected behaviour based on the code shared and there is a proper method to achieve what you want. Personally I would think this is a feature request but even then I am doubtful it would be implemented as this could break existing code that might rely on the current `+=` and `-=` behaviour. PowerShell as a whole is mostly adverse to making breaking changes (5 -> 6 jump being abnormal). An alternative is having 2 methods `AddFlag` and `RemoveFlag` that could do this but you still need the assignment on the LHS so you only really gain a slightly simpler interface.

I apologise for being blunt but in the end this repo has 3000+ issues and I think getting an actual reponse, even if it's a no or working as intended, is better than receiving nothing at all or having it just left to stagnate over time with no action at all.

**Comment by rkitover** [comment] 2021-11-16 22:38
> I apologise for being blunt but in the end this repo has 3000+ issues and I think getting an actual reponse, even if it's a no or working as intended, is better than receiving nothing at all or having it just left to stagnate over time with no action at all.

I'm sorry but I don't agree with your assessment here of this interface as "working as intended" for all the reasons I already mentioned, and I'm sure I'm not the only one. This is of course very subjective, intended by whom for what?

Whether the classification of the issue is a bug report or a feature request is merely a question of labeling.

What I find offensive is the implication that I am doing something wrong when I am pointing out an actual usability or design flaw.

Here is another issue that I opened recently that was also marked as a question:

https://github.com/PowerShell/PowerShell/issues/16345
.

I got some very useful suggestions and information, however, none of them resolve the actual issues I reported.

If the issue was closed as say, WILLNOTFIX, that would be more accurate and less offensive.

I like PowerShell a lot, I care about this project and I have a PR in it, and will probably write more.

I have also been working on this guide the past few years which has its own repo now, and has been well received at least by some people:

https://github.com/rkitover/windows-dev-guide

**Comment by iSazonov** [comment] 2021-11-17 04:43
> I like PowerShell a lot, I care about this project and I have a PR in it, and will probably write more.

In that case, you should not be offended by this `question` label. It is placed not _on you_ but on the issue to mark the beginning of the workflow. You should be more concerned about whether the blue label is the right one, which means which working group will consider the issue. Have you read about workgroups on MSFT team blog?
The purpose of working groups is to analyze issues and PRs _in depth_.
Right now these groups are too small to work actively. Joining these groups is welcome - this is something fans of this project could do to develop the project more rapidly.

**Comment by dwtaber** [comment] 2021-11-17 07:01
> This is the recommended method of setting and removing the `hidden` attribute on a file

Where is this method recommended?

I agree that the way PowerShell presents the `FileAttributes` enum makes it easy to get the impression that `$File.Attributes += <attribute>` is an idempotent operation.  C# doesn't allow explicitly overloading `+=` or `-=`; I haven't checked yet whether PowerShell follows suit.  Since modifying the behavior of those operators would be a breaking change in any case, how about adding `AddAttribute` and `RemoveAttribute` script methods to `FileInfo` objects?

**Comment by lukeb1961** [comment] 2021-11-17 07:58
https://devblogs.microsoft.com/scripting/use-a-powershell-cmdlet-to-work-with-file-attributes/
Ed Wilson 2011
and the enum is detailed in 
https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-5.0

I agree that for a normal Powershell user, things are not always as easy/simple/intuitive as they could be.
The fact the repro has 3k open issues says they don't have the staff, rather than the will, to improve things.
But for this one I'm thinking they'll be saying Won't Fix.

**Comment by rkitover** [comment] 2021-11-17 09:14
I understand that this is your workflow, but I don't agree with it and would not do things this way, for reasons above.

Regardless, I will continue to do PowerShell related work.

As for this particular issue, making `+=` / `-=` overloadable on specific types would not be a breaking change. And

```powershell
$attributes += 'attribute'
```

has the semantic meaning of adding an attribute, the implementation is irrelevant. If such an interface corrupts your filesystem, that is very bad.

As for the problem of making files hidden or not hidden on Windows, the best solution right now is:

```powershell
attrib +h file
attrib -h file
```
.

Linux does not have hidden files, so portability is not an issue.

**Comment by iSazonov** [comment] 2021-11-17 14:26
> I understand that this is your workflow, but I don't agree with it and would not do things this way, for reasons above.
> 
> Regardless, I will continue to do PowerShell related work.

It is _our_ workflow 😸 . You can discuss it (in GH Discussions) with community and MSFT team and make the process better.
As only WGs will work actively every day by day I will haven't to do pre-classification :-)

**Comment by rkitover** [comment] 2021-11-17 14:42
@iSazonov And I appreciate all of your work for this project, even if I see this process as flawed from my perspective.

**Comment by dwtaber** [comment] 2021-11-17 16:44
@lukeb1961, was this
> https://devblogs.microsoft.com/scripting/use-a-powershell-cmdlet-to-work-with-file-attributes/ Ed Wilson 2011 and the enum is detailed in https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-5.0

in reply to me asking where `+=` and `-=` operations were recommended for `FileInfo.Attributes`?  Both of those sources discuss performing bitwise operations.

@rkitover,
> As for this particular issue, making `+=` / `-=` overloadable on specific types would not be a breaking change. And
> 
> ```powershell
> $attributes += 'attribute'
> ```
> 
> has the semantic meaning of adding an attribute, the implementation is irrelevant. If such an interface corrupts your filesystem, that is very bad.

I agree that the current behavior of `+=`/`-=` isn't exactly surprise-minimizing.  I also think it's pretty unlikely that anyone is relying on the current behavior for `FileAttributes` and maybe for flag enums in general—probably [Bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).  I'm going to look into the possibility/palatability of overloading the `+` and `-` operators for `FileAttributes`, which would implicitly overload `+=` and `-=`.  If that turns out not to be an option (technically or otherwise), I'm going to submit a PR to add `AddAttribute` and `RemoveAttribute` script methods to `FileInfo` to provide a somewhat more apparent way to idempotently modify `FileInfo.Attributes`.

**Comment by daxian-dbw** [comment] 2021-11-17 18:00
@dwtaber Before doing all the work, I suggest you to first open an issue to describe what you want to do and see if that's blessed by the corresponding working group. Just don't want you to waste too much time in case it's rejected.

**Comment by dwtaber** [comment] 2021-11-17 18:45
> @dwtaber Before doing all the work, I suggest you to first open an issue to describe what you want to do and see if that's blessed by the corresponding working group. Just don't want you to waste too much time in case it's rejected.

I appreciate that, @daxian-dbw.  For me, it's largely an excuse to explore parts of the code I might not otherwise, so it won't be wasted time either way.  That said, the script methods I mentioned above turned out to be pretty straightforward to implement; since I have code ready to go, do you still recommend that I open an issue, or should I just go ahead with a PR?

**Comment by daxian-dbw** [comment] 2021-11-17 20:04
> do you still recommend that I open an issue, or should I just go ahead with a PR?

You should always start with an issue.

**Comment by rkitover** [comment] 2021-11-18 04:50
@dwtaber Thank you for looking into this.

> in reply to me asking where += and -= operations were recommended for FileInfo.Attributes? Both of those sources discuss performing bitwise operations.

Let me explain my motivation and reasoning here.

I am not an advanced PowerShell user, I never read a book and just learned from experimentation and looking up bits of info on the internet.

So I googled "powershell make file hidden" and the result that came up was:

https://social.technet.microsoft.com/Forums/en-US/33665b03-d383-41ed-a836-fd83c217b3f1/making-files-hidden-with-powershell?forum=ITCG

which gave me this syntax.

Out of curiosity, I tried using this syntax on an already hidden file and noticed the behavior I reported.

Now, consider this from the perspective of a C++ programmer. I do some C++ although I'm by no means very good at it.

The operation:

```powershell
$attributes += 'attribute'
```

is **ALREADY** overloaded to take a string. No reasonable person would expect such an operation with a string on the RHS to be arithmetic addition to a bitmask. If only numeric values were allowed, this would be far more obvious.

So while it's no surprise that the code on an internet forum was wrong, it looked completely fine to me.

I'm glad you see my perspective here.

**Comment by 237dmitry** [comment] 2021-11-18 06:41
Why do not just set attributes you want? This is a one time task.
```
(Get-Item file -Force).Attributes = 34   # Hidden, Archive
(Get-Item file -Force).Attributes = 32   # Archive
```

**Comment by rkitover** [comment] 2021-11-18 06:59
@237dmitry the issue here is that string values are allowed and they do not exhibit the behavior a user would expect.

As for setting a file hidden, it's far easier to just use the `attrib` command, at least with the current state of things.

**Comment by SeeminglyScience** [comment] 2021-11-18 13:45
> @237dmitry the issue here is that string values are allowed and they do not exhibit the behavior a user would expect.

In PowerShell there is an expectation that for a binary expression, the RHS is converted implicitly to the same type as the LHS.  There's also an expectation that conversion paths are a lot more forgiving, for example an implicit conversion my call a static `Parse` method if it exists (like in the case of an enum).

I can definitely agree that adding two bit flag enum values together can be very unintuitive if you don't know that's what it is doing. That said, being able to use string values as short hand for enum values is a feature that is heavily depended on. This is one of the very few instants where it's slightly problematic.

**Closed** 2021-11-20 00:00 UTC
Labels: Issue-Question, Resolution-Answered, Needs-Triage
