### ISSUE TITLE
Executing scripts by relative path without a leading `./` results in a limited command search.

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#9256] opened 2019-03-30 21:48 UTC
# Steps to reproduce using wildcards (verified on macOS and Windows)

```powershell
new-item -ItemType Directory -Path repro2
'repro' | Out-File -Path repro/1.ps1
& 'repro/[1].ps1'
```

# Expected behavior

```none
repro
```

# Actual behavior

```none
repro\1.ps1 : The module 'repro' could not be loaded. For more information, run 'Import-Module repro'.
At line:1 char:1
+ repro\1.ps1
+ ~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (repro\1.ps1:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoLoadModule
```

# Actual behavior for wildcard case

```none
repro/[1].ps1 : The term 'repro/[1].ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ repro/[1].ps1
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (repro/[1].ps1:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

# Environment data

```none
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# By design failure, as it overlaps with Module Qualified syntax, which should take precedence

```powershell
new-item -ItemType Directory -Path repro2
'repro' | Out-File -Path repro/1.ps1
repro\1.ps1
```

**Comment by msftrncs** [comment] 2019-12-01 05:35
See #10997 for a related issue with commands in `PATH` failing to be found if they contain wildcard's.  Both issues have the same root cause, fixed in #11008.

**Closed** 2023-11-23 12:47 UTC
Labels: Issue-Question, WG-Engine, Resolution-No Activity
