### ISSUE TITLE
Write-Host output duplicated in prompt

### ISSUE THREAD

**Issue by theaquamarine** [PowerShell/PowerShell#1993] opened 2016-08-21 13:05 UTC
Steps to reproduce
------------------
Create a function which uses `Write-Host`, then use it in `$Function:prompt`.

Expected behavior
-----------------
Output of `Write-Host` is displayed once.

Actual behavior
---------------
Output of `Write-Host` is displayed twice, once before `PS>` and once after. The second appearance disappears on input.
<img width="296" alt="screen shot cropped" src="https://cloud.githubusercontent.com/assets/111144/17837300/c164434a-67a7-11e6-9b67-7a1773002f62.png">

Environment data
----------------

PowerShell 6.0.0-alpha.9 on OS X 10.11.5

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Expected behaviour is seen on PSVersion 5.1.14393.0 and 6.0.0-alpha.9 on Windows 10 14393.51

**Comment by theaquamarine** [comment] 2016-08-21 13:13
Expected behaviour is also seen on 6.0.0-alpha.9 on Windows.
![image](https://cloud.githubusercontent.com/assets/111144/17837365/52a7c7a4-67a9-11e6-9fba-f6fbd1442a57.png)

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSRemotingProtocolVersion      2.3
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.9
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
CLRVersion
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
```

**Comment by jpsnover** [comment] 2016-08-21 14:01
I don't know if that is a bug not but the problem is that the host calls the prompt function to **get a string** to use as a prompt.  Your function is NOT returning a string which is why the prompt is still "PS>".

Just to be clear - it is totally fine to do all sorts of processing in your prompt function.  
It is just that at the end, you need to return a string if you want the prompt to be different.

**Comment by lzybkr** [comment] 2016-08-21 15:17
This is a definite bug, it's quite common to use Write-Host in prompt.

Before Windows 10 Nov update, the only way to use color in your prompt was to use Write-Host, or another terminal emulator like ConEmu that supported ANSI escape sequences.

With the latest Win10 builds, or on Linux/Mac, prompts can return a string with ANSI escape sequences, so they can avoid Write-Host.

**Comment by lzybkr** [comment] 2016-08-21 15:27
Closing - this is a dupe of #1897.

**Closed by lzybkr** 2016-08-21 15:27 UTC
Labels: Resolution - Duplicate
