### ISSUE TITLE
A "hybrid" bareword command argument that is parsed as a number unexpectedly behaves like a string with -f (format operator)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17199] opened 2022-04-26 19:58 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Passing a bareword argument to a parameter that isn't type-constrained is parsed as a number if it looks like one.

The resulting value self-identifies _as a number_ and _mostly_ acts as such, but it is wrapped in an invisible `[psobject]` instance in which the original string representation is cached.

In the context of `-f`, this string representation surfaces unexpectedly, meaning that the value is unexpectedly not treated as a number:

```powershell
& { param($p) $p.GetType().FullName; '{0:N2}' -f $p } 0x1a
```

### Expected behavior

```console
System.Int32
26.00
```

### Actual behavior

```console
System.Int32
0x1a
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.3
```

**Comment by vexx32** [comment] 2022-04-28 21:38
WG-Engine discussed this today, and the consensus is that this is by design. It may be a little unintuitive that the value behaves like multiple types depending on how it's used, but this is necessary to avoid overcomplicating the command syntax and allowing bare strings that look like numbers to be entered, without losing their original representation if that is desirable.

The fix for this is to cast the value to the type you want to treat it as (for example `[int]` in this instance) either in the `param` block or immediately before using it.

If we were to remove this behaviour, there would be no way to get it back for the cases that _do_ find this desirable, so our conclusion was that it would be much riskier to change the behaviour than leave it as-is.

**Comment by mklement0** [comment] 2022-04-28 21:43
@vexx32, there is no need to remove the behavior as such; the only fix that is needed is to make `-f` not pay attention to the cached string representation.

**Closed** 2022-04-30 09:00 UTC
Labels: Resolution-By Design, WG-Engine-ParameterBinder

**Comment by MatejKafka** [comment] 2024-07-07 00:20
If you need to preserve the actual type (e.g. distinguish between `int` and `long`), the following may come in handy to strip the PSObject metadata:
```powershell
$Value = [System.Management.Automation.LanguagePrimitives]::ConvertTo($Value, $Value.GetType())
```

I'd hope there's an easier way, but I did not find it.
