### ISSUE TITLE
Parallel Xunit tests seems to have a race condition causing random failures

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#8715] opened 2019-01-23 00:14 UTC
We have seen failures in PR as well as Nightly builds.

# Steps to reproduce

Failures on PR or Nightly builds.

# Expected behavior

No intermittent failures

# Actual behavior

Intermittent failures:
https://powershell.visualstudio.com/PowerShell/_build/results?buildId=10731&view=ms.vss-test-web.test-result-details

https://powershell.visualstudio.com/PowerShell/_build/results?buildId=10643

# Environment data

GitHub master

**Comment by iSazonov** [comment] 2019-01-23 17:25
There is race condition issues with access to powershell.config.json. 
One can be fixed by means of fallback to default/current values if the config is not readable. I believe it should be described in RFC.
Second is in cleanup code of xUnit tests and can be fixed too.

**Comment by adityapatwardhan** [comment] 2019-01-24 19:04
Another instance: https://powershell.visualstudio.com/PowerShell/_build/results?buildId=10967&view=logs

**Comment by iSazonov** [comment] 2019-01-25 03:38
@adityapatwardhan Last link is green.

**Comment by adityapatwardhan** [comment] 2019-01-25 18:34
@iSazonov Switch to Attempt 1 to see error:

![image](https://user-images.githubusercontent.com/12820925/51765485-bf63a680-208c-11e9-99a1-0e687a839ab8.png)

**Comment by iSazonov** [comment] 2019-01-26 08:14
@adityapatwardhan Thanks! I don't know root cause for this (3-d) issue. :-(

**Comment by PaulHigin** [comment] 2019-01-30 17:07
We have a new error in the same test "TestRunspaceWithPowerShellAndInitialSessionState"
https://powershell.visualstudio.com/PowerShell/_build/results?buildId=11528
It seems to be due to a malformed file path:
```
System.Management.Automation.CmdletInvocationException : The filename, directory name, or volume label syntax is incorrect : 'C:\	mp\20190130'
2019-01-30T11:16:06.6867227Z ---- System.IO.IOException : The filename, directory name, or volume label syntax is incorrect : 'C:\	mp\20190130'
```

**Comment by iSazonov** [comment] 2019-01-30 17:13
@PaulHigin I saw this earlier and I believe that after #8779 it will be more clear where the issue come from.

**Closed** 2023-11-23 12:49 UTC
Labels: WG-Quality-Test, Resolution-No Activity
