### ISSUE TITLE
Get-Help does not recognize documentation comments in PS 7.2.3

### ISSUE THREAD

**Issue by agaace** [PowerShell/PowerShell#17297] opened 2022-05-09 23:11 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When there are comments adjacent to documentation comments, documentation comments are not recognized by `Get-Help`. This doesn't work:
```powershell
# Regular comment
<#
.SYNOPSIS
My documentation.
#>
```

When an empty line is added between these comments, `Get-Help` works correctly. This works:
```powershell
# Regular comment

<#
.SYNOPSIS
My documentation.
#>
```

Powershell version: 7.2.3
Windows version: 11
File encoding: UTF8 (no BOM)
File endings: LF

For a demo, save the following file as `BugDemo.ps1`:

```powershell
# This comment makes the documentation comments below stop being recognized by Get-Help.
# Add an empty line below this comment (in line 3) and Get-Help works well again.
<#
.SYNOPSIS
Says hi.

.DESCRIPTION
Greets you politely.

.PARAMETER name
Your name.
#>
function SayHi
{
  [OutputType([void])]
  param
  (
    [Parameter(mandatory=$true, position=0, valueFromPipeline=$true)]
    [string]
    $name
  )

  Write-Host "Hi, $name! Nice to meet you!"
}

SayHi Fred
Get-Help SayHi
```

[BugDemo.ps1.txt](https://github.com/PowerShell/PowerShell/files/8655919/BugDemo.ps1.txt)

### Expected behavior

```console
PS> ./BugDemo.ps1
Hi, Fred! Nice to meet you!

NAME
    SayHi

SYNOPSIS
    Says hi.


SYNTAX
    SayHi [-name] <String> [<CommonParameters>]


DESCRIPTION
    Greets you politely.


RELATED LINKS

REMARKS
    To see the examples, type: "Get-Help SayHi -Examples"
    For more information, type: "Get-Help SayHi -Detailed"
    For technical information, type: "Get-Help SayHi -Full"
```

### Actual behavior

```console
PS> ./BugDemo.ps1
Hi, Fred! Nice to meet you!

NAME
    SayHi
    
SYNTAX
    SayHi [-name] <string> [<CommonParameters>]
    

ALIASES
    None
    

REMARKS
    None
```

### Environment data

```powershell
PS> $PsVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment] 2022-05-10 11:52
I think this has been the same over the whole life of comment based help. 

The rule seems to be 
1. Comments before the function declaration are merged.. If the result starts with .Synopis, .Description, etc it is treated as help text and  help inside the function is ignored. (white space around comments and before the first . is ignored).
2. If there is no valid comment based help before the function, comments at the start of the block (before any [cmdletbinding()] or similar) are merged  If the result starts with .Synopis, .Description, etc it is treated as help text and any help at the end of the block is ignored.
3. If 1 & 2 don't provide help, comments at the end of the block are merged  If the result starts with .Synopis, .Description, etc it is treated as help text 
4. For a parameter if no help is defined by 1,2 or 3comment(s) on the parameter  (merged if there are 2 or more) become its help.

Although inserting a comment before a comment _shouldn't_ change things, the combination of allowing the comment based help to be split, and quick and simple recognition of the help text leads to what we have.

**Comment by SeeminglyScience** [comment] 2022-05-10 15:10
True it's always been like that, but it might be able to skip line comments that don't fit if there's a trailing block comment that does. Opening to `WG-Interactive-HelpSystem`

**Comment by SeeminglyScience** [comment] 2022-05-10 21:31
> It might also be worth asking if there would be benefit in unifying help found outside, at the start and end, and allowing help to the be other side of [cmdletbinding()]

I'm not sure if that's strictly related to this issue, could you open a new one for discussion?

**Comment by jhoneill** [comment] 2022-05-11 09:39
@SeeminglyScience  

I was thinking if the way help was merged and selected was going to change, then merging help from two or all three of the possible locations could be part of the same piece of work.  Thinking a bit more my feeling is keeping the help in one place is better practice, so we shouldn't be adding support for fragmenting it.

**Comment by doctordns** [comment] 2022-05-11 09:53
If the help system could provide flexibility here and aggregate comment based help, that would be good. That said, I have the sense that doing so might impact the code leading to higher code size and complexity.  Just asking the question: is this worth 'fixing'??

**Comment by jhoneill** [comment] 2022-05-11 11:17
@doctordns   My first thought was aggregating was (potentially) good, but the more I thought about it the more the more I thought fragmenting the help was bad - though I'm torn between parameter help in the main help block, and parameter help on the parameters where PowerShell gives me a choice.  If aggregation had always been there, as a matter of style we'd tell people to keep the help text together, wouldn't we ?

**Comment by SeeminglyScience** [comment] 2022-05-11 16:08
> I was thinking if the way help was merged and selected was going to change, then merging help from two or all three of the possible locations could be part of the same piece of work. Thinking a bit more my feeling is keeping the help in one place is better practice, so we shouldn't be adding support for fragmenting it.

I'm not sure what you mean. The OP is saying they have an unrelated-to-help comment above their CBH that breaks CBH parsing. I'm saying we can probably just skip that comment when looking for CBH

**Comment by jhoneill** [comment] 2022-05-11 18:43
@SeeminglyScience 

Yes. 
Right now what happens is comments get merged.  If you have 
```
# foo
<#
.synopsis
 blah
#>
```
OR 
```
<#
foo

.synopsis
 blah
#>
```

CBH breaks.

If there is work to be done, after merging the pieces of help out any lines before the first CBH tag should be filtered and any CBH is left it gets used. . 
But if the merge and filter process is to be "fixed", should merge cast its net a bit wider? I thought "maybe" now I think "probably not". So Ignore what I suggested yesterday

**Comment by sdwheeler** [comment] 2023-07-12 14:53
This is documented behavior.

https://learn.microsoft.com/powershell/scripting/developer/help/syntax-of-comment-based-help#syntax-description

> All the lines in a comment-based Help topic must be contiguous. If a comment-based Help topic follows a comment that isn't part of the Help topic, there must be at least one blank line between the last non-Help comment line and the beginning of the comment-based Help.

**Comment by theJasonHelmick** [comment] 2023-07-12 20:29
Thank you @agaace for the issue.  As described by @sdwheeler this is by design.

**Closed** 2023-07-14 02:04 UTC
Labels: WG-Interactive-HelpSystem, Resolution-By Design
