### ISSUE TITLE
Support password prompt caused by sudo over PSRP

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#13379] opened 2020-08-07 15:48 UTC
I didn't see an existing issue on this (which is odd cause we've talked about it in the past) and I just ran into a situation where I needed this. I need to run a command with `sudo`... but when I try running it over a PSRP session, it doesn't prompt me... instead it fails.

If I disable the sudo prompt the command works but we don't wanna be in the business of telling folks to disable passwords.

## Steps to reproduce

```powershell
Enter-PSSession -Session $myUbuntuVM
sudo cat /etc/shells
```

## Expected behavior

The shells are printed out like normal

## Actual behavior

```none
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TylerLeonhardt** [comment] 2020-08-07 15:49
cc @PaulHigin I'd love your thoughts on this.

**Comment by SteveL-MSFT** [comment] 2020-08-07 15:49
Dupe of https://github.com/PowerShell/PowerShell/issues/1527

**Closed** 2020-08-08 01:11 UTC
Labels: Issue-Question, Resolution-Duplicate
