### ISSUE TITLE
problem with set-location after passthru 

### ISSUE THREAD

**Issue by khoshroomahdi** [PowerShell/PowerShell#13754] opened 2020-10-07 09:09 UTC
i use this command to set-location
Get-ChildItem | Out-GridView -PassThru |Set-Location
but in powershell go to 
Microsoft.PowerShell.Core\FileSystem::~\Desktop 
and this make some problem for example i want to open file explorer in this location but explorer open in quick access not in this location

PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment] 2020-10-07 11:05
Please share PSVersionTable as requested in the issue template.

**Comment by jhoneill** [comment] 2020-10-07 23:52
`get-item .. | select -expand fullname |  set-location ` 
Will work 
`get-item .. | set-location`  passes a directoryInfo object with a `PSPath` property, cmdlets usually prefer to use this rather name or full name,  and we don't see it . For `set-location` it's a bit ugly, but it is still the same place. 
Same thing on Win PowerShell 5.1 and on 7.0.3

**Comment by iSazonov** [comment] 2020-10-08 03:20
It is seem dup #3307.

**Comment by jhoneill** [comment] 2020-10-08 14:39
No,  #3307 says "name" <> "fullname",  but  `$x | cat`  uses PSPath so isn't affected. 

This one is "Set-location accepts both path and literalpath, and literalpath / pspath takes predence" 
So you can do 
```
> Set-Location -LiteralPath (get-item .).pspath
>$Pwd   
Path
----
Microsoft.PowerShell.Core\FileSystem::C:\Users\James\Documents\Stuff
```
And connect to the PSProvider instead of the drive, which is  counter intuitive.   drive-less CD - for example
`set-location Microsoft.PowerShell.Core\Registry::HKEY_CLASSES_ROOT\`
Is quite legal, and useful, though not very often . It would be possible to change which property was picked up by default.

**Comment by vexx32** [comment] 2020-10-08 15:34
That would involve changing and possibly breaking quite a few other cmdlets / use cases that work with the pspath/literalpath pipeline binding.

This is as far as I ever got to fixing this, the proper "fix" is still not clear to me, there'a a fair bit of discussion in this PR: #9294

The other issue we've seen around this is #9293, which I guess this one is essentially a duplicate of. Might be more productive to continue discussion in that issue?

**Comment by jhoneill** [comment] 2020-10-08 23:50
@vexx32  Yes I think you had the the right idea in #9294 - i.e. it's not something which should be changed generally; Strictly speaking  set-location is doing the correct thing but it _feels_ wrong, and seems like a bug to the OP.

**Comment by vexx32** [comment] 2020-10-08 23:54
Aye. In the specific case of Set-Location I do think we should fix it as best we can, but I'm unsure of the best way to approach that at the moment.

**Closed** 2020-10-10 02:00 UTC
Labels: Issue-Bug, Resolution-Duplicate
