### ISSUE TITLE
Remove-Module doesn't care about casing, but Import-Module does care

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3573] opened 2017-04-15 23:37 UTC
PowerShell Core on Linux.

Steps to reproduce
------------------
```
# this works
Remove-Module psreadline
# this fails
Import-Module psreadline
# you need to run
Import-Module PSReadLine 
```
Expected behavior
-----------------
Consistent behavior for both cmdlets.

Actual behavior
---------------
```
# this works
Remove-Module psreadline
# this fails
Import-Module psreadline
```
Environment data
----------------

```powershell
PS /home/aleksandar> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by iSazonov** [comment] 2017-04-16 13:07
@alexandair Thanks for your report!

I believe if on Unix we allow import different modules `modulename` and `Modulename` we should be case-sensitive in `Remove-Module` and `Get-Module` too.

**Comment by rkeithhill** [comment] 2017-04-16 22:47
Is it a good idea to allow case-sensitive module names considering that Windows will not support such module names as its file system is case-insensitive?  Seems like PowerShell should treat modules as case-insensitive.  I don't see any value in allowing posh-git, Posh-Git and Posh-GIT to be different modules.  I think that would just lead to confusion.  IMO all of the module-related commands should be case-insensitive.  And if on Linux someone has both mymodule and MyModule dirs. and is trying to import Mymodule, PowerShell should warn the user about the conflict.

**Comment by iSazonov** [comment] 2017-04-17 05:19
If we consider the module names as case-insensitive, then should we do the same in relation to the names of scripts and other PowerShell files?

**Comment by rkeithhill** [comment] 2017-04-17 06:04
I don't think so.  Script filename casing should following the OS's casing rules.  That said, the PowerShell Gallery should consider warning (or rejecting) when publishing scripts that would stomp a different script with the same name on a case-insensitive file system.  Either that or use some other means of disambiguation (author name, pub-date, version, etc).

**Comment by iSazonov** [comment] 2017-04-17 08:06
I expect that this will amaze users that .psm1 is case-insensitive and .ps1 case-sensitive.

**Comment by joeyaiello** [comment] 2017-04-17 18:31
I believe this is an application of the question raised in #706. Ideally, we should address this all up.

**Comment by chuanjiao10** [comment] 2017-06-15 06:36
agree rkeithhill
 
Today, case sensitive, let me cry:

**Net or net**

install-module winscp #   normal
Import-Module WinSCP
```
Import-Module : Could not load file or assembly '/opt/microsoft/powershell/6.0.0-beta.2/Modules/WinSCP/5.9.5.6/lib\WinSCPNet.dll' or one of its d
ependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-Module WinSCP
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

PS /root> test-path /opt/microsoft/powershell/6.0.0-beta.2/Modules/WinSCP/5.9.5.6/lib/WinSCPnet.dll                                               
True

PS /root> test-path /opt/microsoft/powershell/6.0.0-beta.2/Modules/WinSCP/5.9.5.6/lib\WinSCPnet.dll                                               
True


PS /root> test-path /opt/microsoft/powershell/6.0.0-beta.2/Modules/WinSCP/5.9.5.6/lib\WinSCPNet.dll                                               
False
PS /root> test-path /opt/microsoft/powershell/6.0.0-beta.2/Modules/WinSCP/5.9.5.6/lib/WinSCPNet.dll                                               
False

**Comment by SteveL-MSFT** [comment] 2017-10-12 23:47
Dupe of https://github.com/PowerShell/PowerShell/issues/1621

**Closed by SteveL-MSFT** 2017-10-12 23:47 UTC
Labels: Area-Cmdlets-Core, Issue-Discussion, Resolution-Duplicate
