### ISSUE TITLE
Intellisense DSC LCM configuration not working on Ubuntu when using DscLocalConfigurationManager attribute

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PowerShell#2120] opened 2016-08-29 21:01 UTC
I’ve noticed an inconsistency in the PS Extension intellisense results between different platforms.
I’m using the latest and greatest 0.7.1 of the PS extension on both Windows and Ubuntu and I’m trying to create a meta configuration for the LCM using v2 syntax (DscLocalConfigurationManager attribute).
I’ve installed the latest OMI and DSC packages as well as PS alpha 9 on Ubuntu.
## Steps to reproduce

Use Ubuntu 16
Install VS Code 1.4 and PS Extension 0.7.1
Install PowerShell 6.0.0-Alpha.9
Install OMI 1.1.0
Install DSC Package 1.1.1-281
Write a meta config and use the DscLocalConfigurationManager attribute to decorate.
## Expected behavior

When using the DscLocalConfigurationManager attribute to decorate a configuration to create a meta.mof, the Settings entry should be suggested by intellisense and the possible properties should be displayed.
## Actual behavior

Works on Win10, Not on Ubuntu. 
Intellisense does not suggest Settings entry and doesn't suggest possible properties and values.
![result](https://cloud.githubusercontent.com/assets/10071039/18067076/88187904-6e3b-11e6-9c3f-b449f14e80f6.png)
(On CentOS DSC intellisense doesn't work at all because of missing libmi.so library).

**Comment by KrisBash** [comment] 2016-08-29 21:11
For a workaround on CentOS, link the missing libmi.so to /opt/omi/lib/libmi.so
`sudo ln -s /opt/omi/lib/libmi.so /opt/microsoft/powershell/6.0.0-alpha.9/libmi.so`

**Comment by bgelens** [comment] 2016-08-29 21:16
Thanks @KrisBash!

**Comment by joeyaiello** [comment] 2017-05-25 17:44
Assigning to myself to try and repro again after I reboot into my CentOS partition.

**Comment by SteveL-MSFT** [comment] 2018-07-22 00:39
@joeyaiello is this still an issue?

**Comment by joeyaiello** [comment] 2019-07-09 23:32
@SteveL-MSFT still repros

/cc @nitinbps @amitsara

**Comment by ThomasNieto** [comment] 2023-08-18 15:02
@andyleejordan can this issue be closed or moved to the vs code extension repo?

**Comment by andyleejordan** [comment] 2023-08-18 19:13
I'm going to close it as it was reported in 2016, last reported as reproducing in 2019, and the extension has been significantly overhauled since then.

**Closed by andyleejordan** 2023-08-18 19:13 UTC
Labels: Issue-Bug, WG-Interactive-IntelliSense, Area-DSC
