### ISSUE TITLE
Support spawning cmdlets under sudo

### ISSUE THREAD

**Issue by borgdylan** [PowerShell/PowerShell#5765] opened 2017-12-30 11:48 UTC
Please support temporary privileged mode for powerhsell. Bash allows temporary privileged mode by prefixing a command with sudo. In powershell, this entails spawning the whole shell under sudo which means that all commands run privileged which an anti-pattern for shell use in the UNIX world. Usage of sudo should be intercepted so that sudo starts a powershell process that runs the command/cmdlet then exits immediately instead of letting sudo start just a bash shell which would not support cmdlets.

Steps to reproduce
------------------

```sudo Update-Help```

Expected behavior
-----------------

```The Update-Help cmdlet runs in admin privilege in a temporary powershell instance```

Actual behavior
---------------

```The sudo command ends up spawning a privileged bash instance which obviously knows nothing about PWSH cmdlets```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-rc.2                                      
PSEdition                      Core                                            
GitCommitId                    v6.0.0-rc.2                                     
OS                             Linux 4.14.10-041410-generic #201712291810 SM...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0 
```

**Comment by markekraus** [comment] 2017-12-30 12:53
Hi @borgdylan! Thanks for reporting the issue. however, this appears to be a duplicate of  #3232. Please go to that issue and comment/vote.

**Closed by markekraus** 2017-12-30 12:53 UTC
Labels: Issue-Enhancement, OS-Linux, OS-macOS, Resolution-Duplicate
