### ISSUE TITLE
Table View of [PSCustomObject]

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#19139] opened 2023-02-12 07:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This issue is a continuation of [#19107]( https://github.com/PowerShell/PowerShell/issues/19107) and [#18492]( https://github.com/PowerShell/PowerShell/issues/18492), which are closed as resolved. But this is not true.

The pscustomobject table representation of non-integer numbers rounds them up or down, regardless of the user's preference.

Values are rounded to two or three decimal places, depending on the System.Globalization.CultureInfo.CurrentCulture used.

For example user want to see five digits after decimal separator of property `one` and one digit of property `two`:

```powershell
[pscustomobject] @{

     one = [math]::Round(0.1234567,5)
     two = [math]::Round(1.1234567,1)
     }

 one  two
 ---  ---
0.12 1.10
```
As you can see, the result was shocking. The user can format the output himself (as a string), but this effort looks strange.

### Expected behavior

```console
- The output values should match the user's preferences.
- The user does not have to make additional efforts to obtain the expected result.
```

### Actual behavior

```console
The user is forced to change the type of the resulting values and reformat their output to obtain the desired result.
```

### Error details

```console
It's not a bug. This is a change in the behavior of the classic table view.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment] 2023-02-12 16:23
**Please just close this one as well.**   @237dmitry  Enough. Please, your wasting your own time and that of normally patient people 

1. It is working as designed.  
2. Format table should _not_ be making exceptions for a single type if `round` is being used to format strings. If the object is commonly used it should be labelled with a type and given proper formatting, if it is a 1 off, format what you want to display as a string.  
3. `(1/2), (2/3), (3/4) , (4/5), (5/6)| % {    [pscustomobject][ordered]@{"Scale"=$_; "Diameter"=($_*144); "Circumference"=($_*144*[math]::pi) }}`  should not produce a mess like 
```
            Scale Diameter    Circumference
            ----- --------    -------------
              0.5       72 226.194671058465
0.666666666666667       96  301.59289474462
             0.75      108 339.292006587698
              0.8    115.2 361.911473693544
0.833333333333333      120 376.991118430775
```

**Comment by 237dmitry** [comment] 2023-02-12 18:45
> It is working as designed.

No, not working. See my example. And this is yours, no difference, the mess of trailing zeroes:

```powershell
PS > & {
     (1/2), (2/3), (3/4) , (4/5), (5/6)| % {
     [pscustomobject][ordered] @{
                "Scale"=$_
                "Diameter"=($_*144)
                "Circumference"=($_*144*[math]::pi)
     }}}

Scale Diameter Circumference
----- -------- -------------
0.500   72.000       226.195
0.667   96.000       301.593
0.750  108.000       339.292
0.800  115.200       361.911
0.833  120.000       376.991
```

User have to format to strings:
```powershell
PS > & {
          
   $res =                                  
   (1/2), (2/3), (3/4) , (4/5), (5/6) | % {
   [pscustomobject][ordered] @{                    
              "Scale"= [string] [math]::Round($_,2)         
              "Diameter"= [string] [math]::Round(($_*144),2)                
              "Circumference"= [string] [math]::Round(($_*144*[math]::pi),2)
   }}
                                                                                                     
       $res | ft @{ e='Scale'; a='right' },@{ e='Diameter'; a='right' },@{ e='Circumference'; a='right' }
   }

Scale Diameter Circumference
----- -------- -------------
  0.5       72        226.19
 0.67       96        301.59
 0.75      108        339.29
  0.8    115.2        361.91
 0.83      120        376.99
```
And now suppose that the user needs the table only as an option, for example, so that he can receive only one parameter, moreover, of a given type, which means that, in addition to the table, he will need to organize branching in the script. But, sorry, Powershell is a scripting language, which means it should be as efficient as possible for writing scripts in “three lines”.

**Comment by jhoneill** [comment] 2023-02-12 22:16
Just about anywhere in the world, the decimal points, 1s, 10s and 100s are expected to line up. What you have shown is unacceptable.  

As I said before, stop using round() as a string formatter, then you'll be fine.

**Comment by 237dmitry** [comment] 2023-02-13 06:02
> stop using round() as a string formatter

I want the user to get the result he expects.
Difference:

![difference](https://user-images.githubusercontent.com/78153320/218381865-55bb92b8-a394-4309-983d-a60cea27b056.png)

**Comment by jhoneill** [comment] 2023-02-13 09:45
I also want a user to get what he _or she_ expects that decimal points line up, and multiple rows have the same number of decimals. 

Single and Double always store the same number of bytes for the mantissa and exponent in your screen show `round` is converting `1.11111100000000` to `1.11110000000000`  (14 places of decimals) 
Your left screen shot is showing `1.11110000000000`  correctly. 

Your example of what you expect only works if you know the values going it,  tell me  what this will produce 

``` [pscustomobject] @{ "aa" = [math]::round($a,4) ; "bb" = [math]::round($b,5)}```


**Go on**. How many decimal places be shown in columns  aa and bb display ?    (Tip try `[math]::round($null,2)`)

If you type  "11.1111" and "22.22222" and want to print  "11.1111" and "22.22222" put quotes round them :-)  If you don't know what the number will be, you don't 
 
In my example about if $a is 5.1 it _doesn't_ show to 4 places.  As long use cite round, I'll keep repeating  that `round()` is **not** a string formatter as asking to round 5.10000000000000  shows. 

**The smart thing to request would be NOT applying this formatting to the decimal type.** 
1.10d  is stored as a different number from 1.1d.   
The whole column is NOT formatted the same by `format-table` if one psobject contains an INT and one contains a float, but formatting _all floats_ the same is the least wrong way to deal with things - it is not perfect, "N" format is is a poor choice for numbers bigger than say 10^20 or smaller than 10^-2   
**Not** formatting decimals they are _already_ preformatted (but numbers not strings) would seem like a valid thing to do.

**Comment by 237dmitry** [comment] 2023-02-13 12:33
> If you type "11.1111" and "22.22222" and want to print "11.1111" and "22.22222" put quotes round them :-) If you don't know what the number will be, you don't

Again. One more time. Especially for you. And for them who are 20 years in a bomb shelter. I WANT AS IS, as the user decides, and should be output to the console. Is it really incomprehensible to you, or maybe you are interested in something, maybe you are paid extra for closed issues? I do not understand YOUR personal interest.

For an ordinary person, my request is absolutely obvious and understandable. I just want to get the result and not look for workarounds to implement it. I think this is a normal human desire. But you did everything to make life difficult. Thank you for your stupid initiatives.

**Comment by jhoneill** [comment] 2023-02-13 14:07
I'm not paid anything, I left Microsoft in November 2010.  And learn some manners, or at some point you'll get banned from commenting here.  You've ignored everything you have been told - including how to frame a request for a change which could work - and now are just being obtuse and rude.  There's an old saying "Don't try to teach a pig to sing - it wastes your time and annoys the pig". Well my time is being wasted, you're getting annoyed, so I'll not to respond to you in future. 

What you say about "as the user decides" is wrong, and your use of Round() for string formatting is also wrong   `[pscustomobject] @{ "aa" = [math]::round($a,4) ; "bb" = [math]::round($b,5)}` 
**Does not output 4 decimal places if $a is e.g, 3.1**  If I want two decimal places and with aligned decimal points and do it your way, what do I get in PS5 ? 
```
 > [pscustomobject] @{ "aa" = 1.000 ; "bb" = 2.300};    [pscustomobject] @{ "aa" = 3.450; "bb" = 4.567}

  aa    bb
  --    --
   1   2.3
3.45 4.567
```
It's amazing we had rows of output NOT aligning the columns of numbers for so long.   
Your argument is because you **typed** the value of $a as 1.23 it should be printed as 1.23;  it doesn't work if you type 1.00 though, does it ?  Round doesn't do that, does it.?  If the number is  **not** something you typed and it might internally be 1.0000000000, 1.2000000000, or 1.2300000000, you're saying that users  _want_
```
Row     Value
-----    ------  
1             1
2           1.2
3          1.23
```
Not only do they not want that, dozens and dozens of types through the history of PowerShell have had to create format files just to apply the "N" formatting.  .NET does have not have ability excel has to say "Display a digit but NOT a trailing 0", so you can't align the digits in 1, 1.2 and 1.23 without the trailing 0s. 
 
I'm sure you'll want the last word. I'm going to try not to be goaded into replying.

**Comment by 237dmitry** [comment] 2023-02-13 14:58
My suggestion is not to find a workaround, but to find a classic table view. This is important for backwards compatibility and common sense.

_And yet, if you do not want to answer me, then I will survive it._

**Comment by SteveL-MSFT** [comment] 2023-02-13 17:40
@237dmitry I understand you're frustrated, but please keep the discussion professional.  I think you'll find it easier to convince others if they don't feel like they are being attacked (and the same would go for others as well).

Formatting changes are NOT consider breaking changes as the original values are not being modified, just how they are displayed on screen.  If you know the shape of the object, you can already define your own custom formatting however you'd like, so we're only discussing the default formatting.  

Using CurrentCulture to affect decimal formatting makes sense as users would expect that even within the console as that is the purpose of that configuration.

I guess the question is whether it makes sense to consider a way to either suppress using CurrentCulture or apply decimal formatting "globally" in a table rather than require defining it for each property.  Unless there's a larger part of the user base that wants such a feature, I don't know if it's worth building it when we could be fixing other issues.

**Comment by 237dmitry** [comment] 2023-02-13 18:55
> but please keep the discussion professional.

I'm already tired, how long can I endure? Everyone is looking for some workarounds to solve the problem. But I myself know perfectly well how to get around them. My request is not about workarounds, but about the very essence of the problem.

> Formatting changes are NOT consider breaking changes as the original values are not being modified, just how they are displayed on screen.

This is exactly what I'm trying to get you to change this behavior, revert everything back to how it was up until version 7.3+. If I'm not mistaken in the versions.

> so we're only discussing the default formatting.

So you are suggesting that everyone rewrite their scripts so that their work is no different? An excellent approach, you just warn in advance, otherwise you get situations similar to `$PSStyle.OutputRendering`. Who here said that tables are only for the console? Hello?

Please answer this question -- why are the displayed values in a tabular form rounded both up and down? Why do you do experiments like this on people?

**Comment by IISResetMe** [comment] 2023-02-13 19:22
Can someone detail when/where this was changed? I can't seem to find the responsible PR...

**Comment by 237dmitry** [comment] 2023-02-13 19:36
> Can someone detail when/where this was changed?

I think from 7.3.1, maybe early.

**Comment by daxian-dbw** [comment] 2023-02-13 19:39
The PR was https://github.com/PowerShell/PowerShell/pull/17650, to address the issue #17544.
conceptually, I think it makes sense to adhere to the decimal formatting configured in the current culture.

**Closed** 2023-02-15 00:00 UTC
Labels: Resolution-Answered, Needs-Triage
