### ISSUE TITLE
PowerShell in Windows BASH display issues

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#1829] opened 2016-08-16 14:25 UTC
Steps to reproduce
------------------
I just want this to be noted.  I see some interest with Windows 10 include BASH.
I try to run PowerShell in Windows Bash cmd. I installed it using the Ubuntu version 14.04.

$ sudo apt-get install libunwind8
$ sudo apt-get install libicu52
$ cd Downloads
$ sudo dpkg -i powershell_6.0.0-alpha.8-1_amd64-ubuntu.14.04-x64.deb

![poshbash_01](https://cloud.githubusercontent.com/assets/19892435/17702183/d4ab03aa-639a-11e6-9c4b-66632f0889b9.jpg)

![poshbash_02](https://cloud.githubusercontent.com/assets/19892435/17702306/666d507c-639b-11e6-9b8d-524cf67ad947.jpg)

Commands seem to execute but the screen refresh after running the command won't clear. Also, when you start typing, the prompt is gone and start typing at the top of the screen.

Expected behavior
-----------------
Normal console behavior after running command the return to the next line of the prompt

Actual behavior
---------------
See attached images.

![poshbash_03](https://cloud.githubusercontent.com/assets/19892435/17702309/6ab10e58-639b-11e6-882d-dde931c35511.jpg)
![poshbash_04](https://cloud.githubusercontent.com/assets/19892435/17702313/6c623b50-639b-11e6-9f67-a3d661b84bfe.jpg)

Environment data
----------------

Bash - Windows 10 Pro Insider Preview 14901.rs_prerelease.160805-1700
powershell_6.0.0-alpha.8-1_amd64-ubuntu.14.04-x64.deb

```powershell
> $PSVersionTable

```

**Comment by Jaykul** [comment] 2016-08-21 16:47
Dupe of #1088 -- but good detail...

**Comment by MaximoTrinidad** [comment] 2016-08-21 17:15
Hey Jaykul, #1088 not a duplicate because its specific to Linux issue and not the Bash on Windows 10.  Although I see that the console issue looks identical.  

I hope this could be fix some time soon.
:)

**Comment by andschwa** [comment] 2016-08-24 19:23
@MaximoTrinidad would you please file a bug with [BashOnWindows](https://github.com/Microsoft/BashOnWindows), and reference your issue here? Thanks.

**Comment by MaximoTrinidad** [comment] 2016-08-24 19:54
@andschwa ... It's done! I logged the issue in BashOnWindows:
PowerShell in Windows BASH display issues when typing cmdlets #980 [https://github.com/Microsoft/BashOnWindows/issues/980](url)

**Comment by lzybkr** [comment] 2016-08-24 21:16
The conhost guys took a look - they think #1877 might be contributing the problem.
I'm working of changing the rendering for multiple reasons, hopefully they're right and my changes will just fix it.

**Comment by andschwa** [comment] 2016-08-24 21:50
My *quick* hypothesis is it looks like `CursorTop` is always zero. We definitely ran into this early on with xterm-like emulators on Linux; perhaps it's recurring with conhost.

**Comment by lzybkr** [comment] 2016-10-07 17:15
With some help from @zadjii-msft and @stephentoub, this looks like a CLR issue: https://github.com/dotnet/corefx/issues/12452

**Closed by lzybkr** 2016-10-07 17:15 UTC
Labels: Area-Console, OS-WSL

**Comment by lypanov** [comment] 2017-01-09 09:05
I understand that this is meant to be a CLR issue, and that the issue itself is external. But it would for people waiting on this (at least me ;) ) be really nice if we knew when to retry Powershell. Right now it's of no use to me due to these issues alas.

**Comment by MaximoTrinidad** [comment] 2017-01-09 15:01
I have to admit that it is sad that this is stalled.  The work around still applies and I hope to see this working sometime soon. This is a good opportunity for Windows users using Windows Bash to learn Linux and try PowerShell with it without dealing with building a Linux OS from scratch.

:)

**Comment by iSazonov** [comment] 2017-01-09 15:26
The corefx issue flagged as `Up for Grabs`. So don't expect its a quick fix. 😕

**Comment by andschwa** [comment] 2017-01-09 19:20
@MaximoTrinidad, @iSazonov, if you want to try out PowerShell on Linux without installing Linux from scratch, perhaps our Linux containers will be of interest to you.

1) Install [Docker for Windows](https://docs.docker.com/docker-for-windows/) (this should be a fairly straightforward MSI installation)
2) Open an administrative PowerShell prompt
3) `docker run --interactive --tty microsoft/powershell`
4) You're now in PowerShell, in the Ubuntu 14.04 container, on Windows; try `$PSVersionTable`

[Here are our Docker images](https://hub.docker.com/r/microsoft/powershell/).

**Comment by MaximoTrinidad** [comment] 2017-01-09 21:56
Thanks @andschwa!  I got my laptop running Linux with PowerShell since day one.  I'm just looking to create awareness with Windows 10 Bash which I already got the workaround doing its magic.  No pretty but at least is workable! 

I will take your information provided to play with containers later.  This is an area I need to tackle soon.
:)

Thanks,
Maximo Trinidad

**Comment by iSazonov** [comment] 2017-01-10 04:29
Thanks @andschwa! The main problem is that one Microsoft product (Powershell Core) does not work with other Microsoft product (WSL) harms the reputation of the company despite the fact that the product is still alfa.

**Comment by glennsarti** [comment] 2017-03-28 18:28
Confirmed still in an issue in PS 6.0.0-alpha17

**Comment by glennsarti** [comment] 2017-03-28 18:29
https://github.com/dotnet/corefx/issues/12452 is still open
