### ISSUE TITLE
Should Test-Connection parameter -Continues be -Continuous ?

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#9235] opened 2019-03-27 10:47 UTC
I can't say grammatically why it should be, but it feels like it should be.

And aliased with `Continues` for compatibility.

**Comment by mklement0** [comment] 2019-03-27 11:17
Honestly, it sounds `-Continuous` was intended and simply misspelled.

(If you conceived of it as a _verb_ in the imperative mood, it would have to be `-Continue`, without the `s`).

**Comment by GeeLaw** [comment] 2019-03-28 03:17
As a side note, the switch is exhibiting strange behavior when turned off on PowerShell Core 6.1.2 for macOS.

```powershell
test-connection -continues:$false localhost | foreach-object { "hello $_" }
# the output is written to the host, not the output pipe

test-connection -continues localhost | foreach-object { "hello $_" }
# the output is passed to the output pipe and produces expected result

# also, & { test-connection localhost } pollutes
# the console/terminal/screen buffer before
# returning the object result.
```

The reason is the cmdlet is coded s.t. somehow it only looks at the parameter set (or forgets to look at the parameter set, or resolves the "overload" in an otherwise incorrect way)? (The same mistake is made for `Get-AppxPackage -Online:$false`, which crashes the process; but that's Windows-specific.) I guess this is worth another issue?

**Comment by vexx32** [comment] 2019-03-28 03:28
It's not to do with this parameter. The PS Core implementation of `Test-Connection` writes a majority of its data to the host stream, and then submits a rather less useful object to the output stream. We have another issue on that somewhere, @iSazonov might know where. Too sleepy at the present to dig that one up.

I've been looking at fixing it and am happy to work on it, but we need to come to some consensus on what exactly the inner workings of that fix need to be first. 🙂

**Comment by iSazonov** [comment] 2019-03-28 03:35
After we move to .Net Core 3.0 we get some updates related to the cmdlet. Not all bugs was fixed there but we could review the cmdlet.
And main question is still how balance interactive and script experience.

**Comment by iSazonov** [comment] 2019-10-17 04:13
@vexx32 Can we close this?

**Comment by vexx32** [comment] 2019-10-17 04:17
I can reference it in #10697 so this closes when that is merged, since that's not merged just yet. 🙂

**Closed** 2019-11-18 19:33 UTC
Labels: Area-Cmdlets-Management, Issue-Question
