### ISSUE TITLE
Preference variables don't propagate to script block of ForEach-Object -Parallel

### ISSUE THREAD

**Issue by vojtech-vit-deltatre** [PowerShell/PowerShell#14672] opened 2021-01-27 08:40 UTC
## Steps to reproduce

```powershell
$ErrorActionPreference = 'Stop'
$WhatIfPreference      = 'True'
$DebugPreference       = 'Continue'
$VerbosePreference     = 'Continue'
$WarningPreference     = 'Ignore'
$ConfirmPreference     = 'None'

@(1) | ForEach-Object -Parallel {
    [PSCustomObject] @{ Variable = 'ErrorActionPreference'; Expected = $using:ErrorActionPreference; Actual = $ErrorActionPreference }
    [PSCustomObject] @{ Variable = 'WhatIfPreference'; Expected = $using:WhatIfPreference; Actual = $WhatIfPreference }
    [PSCustomObject] @{ Variable = 'DebugPreference'; Expected = $using:DebugPreference; Actual = $DebugPreference }
    [PSCustomObject] @{ Variable = 'VerbosePreference'; Expected = $using:VerbosePreference; Actual = $VerbosePreference }
    [PSCustomObject] @{ Variable = 'WarningPreference'; Expected = $using:WarningPreference; Actual = $WarningPreference }
    [PSCustomObject] @{ Variable = 'ConfirmPreference'; Expected = $using:ConfirmPreference; Actual = $ConfirmPreference }
}

@(1) | ForEach-Object -Parallel {
    [CmdLetBinding()] Param()
    [PSCustomObject] @{ Variable = 'ErrorActionPreference'; Expected = $using:ErrorActionPreference; Actual = $ErrorActionPreference }
    [PSCustomObject] @{ Variable = 'WhatIfPreference'; Expected = $using:WhatIfPreference; Actual = $WhatIfPreference }
    [PSCustomObject] @{ Variable = 'DebugPreference'; Expected = $using:DebugPreference; Actual = $DebugPreference }
    [PSCustomObject] @{ Variable = 'VerbosePreference'; Expected = $using:VerbosePreference; Actual = $VerbosePreference }
    [PSCustomObject] @{ Variable = 'WarningPreference'; Expected = $using:WarningPreference; Actual = $WarningPreference }
    [PSCustomObject] @{ Variable = 'ConfirmPreference'; Expected = $using:ConfirmPreference; Actual = $ConfirmPreference }
}
```

## Expected behavior

```none
Variable              Expected           Actual
--------              --------           ------
ErrorActionPreference     Stop             Stop
WhatIfPreference          True             True
DebugPreference       Continue         Continue
VerbosePreference     Continue         Continue
WarningPreference       Ignore           Ignore
ConfirmPreference         None             None
```

## Actual behavior

```none
Variable              Expected           Actual
--------              --------           ------
ErrorActionPreference     Stop         Continue
WhatIfPreference          True            False
DebugPreference       Continue SilentlyContinue
VerbosePreference     Continue SilentlyContinue
WarningPreference       Ignore         Continue
ConfirmPreference         None             High
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment] 2021-01-27 11:19
Looks to be a duplicate of https://github.com/PowerShell/PowerShell/issues/14602 and https://github.com/PowerShell/PowerShell/issues/12240

**Comment by TravisEz13** [comment] 2021-04-28 21:22
remoting working group: https://github.com/PowerShell/PowerShell/issues/12240

**Closed** 2021-04-29 23:00 UTC
Labels: Issue-Enhancement, Resolution-Duplicate, WG-Remoting
