### ISSUE TITLE
DIR and LS behave differently

### ISSUE THREAD

**Issue by 1RedOne** [PowerShell/PowerShell#1870] opened 2016-08-18 15:46 UTC
Steps to reproduce
------------------
Connect to a PS-Drive, like ENV:
Execute DIR
See a list of all the environmental variables.
![Yay, all my ENVs](http://i.imgur.com/gqE0okU.png)

Run the 'LS' command
![Aww, it still shows the root of the drive](http://i.imgur.com/77kAl2f.png)
Aww, it still shows the root of the drive
Expected behavior
-----------------
`LS` and `DIR` should really do the same thing within PowerShell, as both are traditionally aliases of Get-ChildItem with the PoSH Shell.  However `LS` still operates in the original mode, which is weird.

Actual behavior
---------------
When running `LS` from a PS Drive like ENV:, it seems that LS is executed outside of PowerShell's directory context. 

Checking here...
![](http://i.imgur.com/pxinW3S.png)

It seems LS isn't mapped as an alias as it normally is within PowerShell.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                                                                                      
----                           -----                                                                                                                                                      
PSVersion                      6.0.0-alpha                                                                                                                                      
PSEdition                      Core                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                    
BuildVersion                   3.0.0.0
CLRVersion                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                                    



```

**Comment by jdhitsolutions** [comment] 2016-08-18 15:52
All of the Linux aliases like ls are removed. So you are actually running the ls command and not an alias for Get-Childitem. This is an open issue that Microsoft will be pursuing with community input.

**Comment by andschwa** [comment] 2016-08-18 16:23
Please see [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#missing-command-aliases) and #929. What we do about the conflicting aliases is a very open question, and we need the community's feedback!

**Comment by andschwa** [comment] 2016-09-19 23:01
I'm going to close this as a duplicate of #929. It is currently operating as intended; while the intention may or may not be what the community desires, further discussion should take place in that issue (as this is really much broader than just ls vs dir). Thanks for the feedback!

**Closed by andschwa** 2016-09-19 23:01 UTC
Labels: Area-Cmdlets, OS-Linux
