### ISSUE TITLE
Invoke-Command - Unable to load DLL 'libpsrpclient'

### ISSUE THREAD

**Issue by PROnICT** [PowerShell/PowerShell#2209] opened 2016-09-08 09:23 UTC
Steps to reproduce
------------------
OS: CentOS 7
Command: Invoke-Command -ScriptBlock {Get-Help} -ComputerName <ComputerName> -Credential

Expected behavior
-----------------
Need to connect to a remote server and get execute the Get-Help command. 

Actual behavior
---------------

Invoke-Command : Unable to load DLL 'libpsrpclient': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by JumpingYang001** [comment] 2016-09-12 03:30
@PROnICT , yes,  'libpsrpclient' is in progress, so you cannot remote directly from one Linux now to another Linux box now.
You can see [Known Issues - Remoting]
[Known Issues - Remoting]:https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support

BTW, temporary workaround is: search "remote over SSH" in this article:http://www.powershellmagazine.com/2016/08/18/open-source-powershell-on-windows-linux-and-osx/

**Comment by andschwa** [comment] 2016-09-19 22:05
Per the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support), this is **not yet supported**.  Please follow the progress on the [PSRP on Linux repo](https://github.com/PowerShell/psl-omi-provider). Closing as duplicate of #942.

**Closed by andschwa** 2016-09-19 22:05 UTC
Labels: Area-Remoting
