### ISSUE TITLE
`using module test` doesn't load the powershell class defined in 'test' if 'test.psd1' has 'FunctionToExport' or 'CmdletToExport' specified

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#4112] opened 2017-06-26 23:42 UTC
Summary
----------
When test.psd1 file has 'FunctionToExport' or 'CmdletToExport' specified, the module script analyzer will skip parsing the module scripts and thus no type definitions would be retrieved back. and [`PSModuleInfo.GetExportedTypeDefinitions`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/PSModuleInfo.cs#L553) doesn't handle this scenario well.

Repro
------
Structure of the module 'test'
```
PS:146> tree.com F:\tmp\test /F
F:\TMP\TEST
    test.psd1
    test.psm1
```
Content of 'test.psd1'
```
@{
ModuleVersion = '1.0'
GUID = 'e812e452-6a43-4fe7-9738-375c2fbdd577'
NestedModules = @("test.psm1")
FunctionsToExport = @('Get-Name')
CmdletsToExport = @()
VariablesToExport = '*'
AliasesToExport = @()
}
```
Content of 'test.psm1'
```
class Foo
{
    [string] $Name = "Foo"
}

function Get-Name
{
    return "Name"
}
```
Content of `run.ps1`
```
using module F:\tmp\test

class Bar{
    [Foo] $foo = [Foo]::new()

    [void] Print()
    {
        Write-Host ($this.foo.Name)
    }
}
```
Run `run.ps1`
```
.\run.ps1
```

Expected Behavior
--------------------
Running `run.ps1` should be successful.

Actual Behavior
-----------------
It failed
```
PS:14> .\run.ps1
At F:\tmp\run.ps1:4 char:6
+     [Foo] $foo = [Foo]::new()
+      ~~~
Unable to find type [Foo].
At F:\tmp\run.ps1:4 char:19
+     [Foo] $foo = [Foo]::new()
+                   ~~~
Unable to find type [Foo].
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TypeNotFound
```

Environment
--------------
```
PS:15> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.2-48-g598cebf7b2f0b5bb0b0add97c6393ccfaaa792f5-dirty
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment] 2017-06-27 00:05
I believe this was part of a perf optimization @lzybkr made to avoid parsing scripts.  We need a `TypesToExport` to continue to enforce explicit exports and maintain perf

**Comment by lzybkr** [comment] 2017-06-27 00:16
Actually this was a design issue - the intent was to not require specifying exported types in the manifest at all because, well, it's annoying.

I didn't implement this aspect of classes, but I thought we intended to compute exported types on demand, and cache the results to avoid redundant parsing.

**Comment by iSazonov** [comment] 2017-06-28 09:15
Was it a breaking change? Was it ported to Windows PowerShell?

**Comment by SteveL-MSFT** [comment] 2017-06-28 22:54
@iSazonov I believe the changes being discussed happened during Windows PowerShell and ended up in PSCore6

**Comment by mklement0** [comment] 2018-07-14 21:30
Since it may not be obvious, let me point out that the problem only surfaces if you use the `NestedModules` entry to reference the `*.psm1` file.

In the given scenario it would be more typical to use  the `RootModule` entry, however, in which case everything works as expected.

**Comment by Jaykul** [comment] 2018-12-05 18:54
Only classes in the **RootModule** are _supposed_ to be available.
This is NOT a bug. This is a design choice, or a duplicate of #2964

**Closed** 2023-11-23 14:07 UTC
Labels: WG-Language, Resolution-No Activity
