### ISSUE TITLE
PowerShell MSI uninstallation issues

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell#3341] opened 2017-03-15 22:50 UTC
- [ ] Leaves old entry under Start menu
- [ ] Leaves empty older version folder on disk

Steps to reproduce
------------------
1. Install an older version of PowerShell (say 6.0.0-alpha16) using MSI
2. Install latest version of PowerShell (6.0.0-alpha17) using MSI
3. Uninstall older version of PowerShell using `Progams and Features` in Control Panel
4. Search for PowerShell in Start menu
5. Look under `C:\Program FIles\PowerShell` path

Expected behavior
-----------------
4. above should have only 1 entry
5. above should only show latest version of PowerShell

Actual behavior
---------------
4. shows multiple entries for PowerShell (see attached image)
![uninstall-entry](https://cloud.githubusercontent.com/assets/11988952/23974203/378a96aa-0997-11e7-8424-6d123017ded4.JPG)
5. shows multiple version folder under the path (see attached image)
![uninstall-fileleft](https://cloud.githubusercontent.com/assets/11988952/23974202/377b1234-0997-11e7-97aa-47a049a3d2a2.JPG)

**Comment by HemantMahawar** [comment] 2017-03-15 22:55
Could be dup/related to #2881

**Comment by bergmeister** [comment] 2018-01-06 21:51
@SteveL-MSFT I remember seeing those issues in the old Alpha days as well but at the end of the Beta phase they started to disappear. My best guess is that it was the rename to `pwsh.exe`. Can you or some one else confirm that they stopped seeing those problems as well? P.S. Yes, this is a duplicate of #2881 in terms of symptoms.

**Comment by SteveL-MSFT** [comment] 2018-01-08 19:48
I'm going to close this as I believe the original issue is addressed.

**Closed by SteveL-MSFT** 2018-01-08 19:48 UTC
Labels: Area-Build, Resolution-Fixed
