### ISSUE TITLE
Test-ModuleManifest: the PSModuleInfo is not updated

### ISSUE THREAD

**Issue by jozefizso** [PowerShell/PowerShell#2216] opened 2016-09-09 20:21 UTC
Cmdlet `Test-ModuleManifest` does not reload the module information when I modify a manifest file and call the `Test-ModuleManifest` again on the same manifest file. Calling `Test-ModuleManifest` again returns cached `PSModuleInfo` instance.

First reported by Dardenne Laurent at 7/13/2015 10:27:31 AM on MS Connect https://connect.microsoft.com/PowerShell/feedback/details/1541659/test-modulemanifest-the-psmoduleinfo-is-not-updated
## Steps to reproduce

Create module manifest `module.psd1` with GUID **9dd7e9a4-8525-4fd1-aa13-3a063df4b264** and run `Test-ModuleManifest`.

``` powershell
> $Manifest = Test-ModuleManifest .\module.psd1
> $Manifest.Guid
9dd7e9a4-8525-4fd1-aa13-3a063df4b264
```

Change the GUID in `module.psd1` manifest to new value (eg. **4714e36a-6e90-47e6-87a7-4637c60e9021**) and run `Test-ModuleManifest` again.

``` powershell
> $Manifest2 = Test-ModuleManifest .\module.psd1
> $Manifest2.Guid
9dd7e9a4-8525-4fd1-aa13-3a063df4b264
```
## Expected behavior

`Test-ModuleManifest` should reload module information and return actual changed module data.

``` powershell
> $Manifest2 = Test-ModuleManifest .\module.psd1
> $Manifest2.Guid
4714e36a-6e90-47e6-87a7-4637c60e9021
```
## Actual behavior

`Test-ModuleManifest` returns cached module information. This will not change for the active PS session.
## Environment data

``` powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by daxian-dbw** [comment] 2016-10-04 17:51
@jozefizso I couldn't reproduce this issue. Here is what I did:
1 - create `module.psd1` using `New-ModuleManifest`
```
New-ModuleManifest -Path module.psd1
```
2 - update the `GUID` property in module.psd1 to be **9dd7e9a4-8525-4fd1-aa13-3a063df4b264**, and save the file.
3 - run `Test-ModuleManifest`
```
[F:\temp]
PS:15> $Manifest = Test-ModuleManifest .\module.psd1
[F:\temp]
PS:16> $Manifest.Guid

Guid
----
9dd7e9a4-8525-4fd1-aa13-3a063df4b264
```
4 - update the `GUID` property in module.psd1 to be **4714e36a-6e90-47e6-87a7-4637c60e9021**, and save the file.
5 - run `Test-ModuleManifest` again
```
[F:\temp]
PS:17> $Manifest2 = Test-ModuleManifest .\module.psd1
[F:\temp]
PS:18> $Manifest2.Guid

Guid
----
4714e36a-6e90-47e6-87a7-4637c60e9021
```

I tried this in the following environments:
```
PS:19> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS F:\temp> $PSVersionTable

Name                           Value
----                           -----
PSEdition                      Core
WSManStackVersion              3.0
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.10-103-g13455204a46f688937369967d0b886598cf7c6e5
```

Maybe the reported issue has been fixed. Could you please double check with the latest powershell core to see if `Test-ModuleManifest` works as expected?

**Comment by daxian-dbw** [comment] 2016-10-05 21:19
Hi @jozefizso and @LaurentDardenne, I cannot reproduce this issue in the latest powershell core and windows powershell 5.1, please see my comment above.
Could you please try the latest powershell core and windows powershell 5.1 to see if the issue is still present?

**Comment by jozefizso** [comment] 2016-10-05 21:33
I have PowerShell version `5.1.14393.206` on my machine. I don't know how to update it.

**Comment by daxian-dbw** [comment] 2016-10-05 22:36
@jozefizso then you can try on the latest powershell core and the windows powershell built from Github. See [here](https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-full.md) for instructions to build FullCLR powershell. After building FullCLR powershell, run `Start-DevPowerShell -FullCLR` to start the FullCLR powershell from your build.

I tried on powershell-6.0.0-alpha.10-win10-x64 and the FullCLR powershell built from Github, and the reported issue doesn't reproduce.

**Comment by daxian-dbw** [comment] 2016-10-20 05:27
@jozefizso Have you got a chance to try on the latest powershell core (e.g. alpha.11 release) or the FullCLR powershell built from GitHub?
It's possible that the issue has already been fixed in the open sourced powershell, but please let us know if you still find it repro.

**Comment by kilasuit** [comment] 2016-10-29 23:59
@daxian-dbw - I can repo this in Ps Version 5.1.14955.1000 - however not with GUID but with Referenced Assemblies and only after an error in the Manifest occurs - raised by @ctrbold

If you have an error in the manifest then you have to close the PowerShell session to run another test with out it seemingly spitting out the errors from the previous run.

Simple repo - add a non-existent Referenced Assembly (just name not a path) to the psd1 and then run Test-ModuleManifest and it will error as it's expecting a path to the assembly which isn't really clear that it what it expects.
After that remove or comment out the Referenced Assembly key and then re run Test-ModuleManifest and it will still error

**Comment by daxian-dbw** [comment] 2016-10-31 23:13
@kilasuit do you mean `RequiredAssemblies` field in module manifest? I tried the repro you described, but I'm still not able to repro it.
[test.ps1.txt](https://github.com/PowerShell/PowerShell/files/563031/test.ps1.txt)
The `test.ps1.txt` contains a pester test with the steps you described, but it always pass when running in the latest powershell core:
```powershell
PS F:\tmp> Invoke-Pester .\test.ps1

Describing Test-ModuleManifest
 [+] Test-ModuleManifest twice 245ms
Tests completed in 245ms
Passed: 1 Failed: 0 Skipped: 0 Pending: 0

PS F:\tmp> $PSVersionTable

Name                           Value
----                           -----
SerializationVersion           1.1.0.1
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.11-54-g44eb20dc8f71d84f604c41f0f7e3a900d5e1ec59
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion
PSRemotingProtocolVersion      2.3
```

Can you please come up with a similar test that can repro the issue?

**Comment by joeyaiello** [comment] 2017-05-25 18:07
This does not repro on `6.0.0-beta.1`

**Closed by joeyaiello** 2017-05-25 18:07 UTC
Labels: Area-Engine, Issue-Bug, Resolution-Fixed
