### ISSUE TITLE
Test-Connection cmdlet is missing from PowerShell Core 6.0.1 release

### ISSUE THREAD

**Issue by oschroeder8** [PowerShell/PowerShell#6300] opened 2018-03-02 23:37 UTC
`Test-Connection` cmdlet is missing from PowerShell Core 6.0.1 release. It is available and working fine in PowerShell 5.1.

Supposedly this was addressed in issue [1146](https://github.com/PowerShell/PowerShell/issues/1146) and the issue was marked as closed. The cmdlet does not seem to exist though, as you can see below:

Steps to reproduce
------------------

```powershell
Get-Command Test-Connection
```

Expected behavior
-----------------

```None
CommandType     Name                                               Version    Source                                                                                     
-----------     ----                                               -------    ------                                                                                     
Cmdlet          Test-Connection                                    3.1.0.0    Microsoft.PowerShell.Management
```

Actual behavior
---------------

```none
Get-Command : The term 'Test-Connection' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Command Test-Connection
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Test-Connection:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
```

Environment data
----------------
```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by oschroeder8** [comment] 2018-03-03 00:16
Here is a link to the documentation which seems to indicate that this command should work with PowerShell 6:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-6

**Comment by markekraus** [comment] 2018-03-03 00:27
Dupe of #4240 and #6076. It is being worked on in PR #5328

**Closed** 2018-03-03 00:28 UTC
Labels: Area-Cmdlets-Management, Resolution-Duplicate

**Comment by enekux** [comment] 2018-05-03 13:59
There is a workaround here. You can use the .Net Ping Class instead and until the Test-Connection cmdlet is ported.
More info here:
http://ilovepowershell.com/2010/04/13/powershell-how-to-ping-computers/

**Comment by enekux** [comment] 2018-05-04 08:07
For the record it has been ported and you can get it from the very latest build (v6.1.0-preview.2 - 2018-04-27)
https://github.com/PowerShell/PowerShell/pull/5328#issuecomment-386310136

**Comment by NSETH18** [comment] 2019-06-24 07:09
I can't use Test-connection   to probe the ports.Is there a way to use Test-connection for ports
