### ISSUE TITLE
PS Update-Help fails with 404 error running as admin or user

### ISSUE THREAD

**Issue by casterle** [PowerShell/PowerShell#18064] opened 2022-09-10 05:45 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running PowerShell 7.2.6 as Admin, Update-Help fails:

Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, DefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'IISAdministration' with UI culture(s) {en-US} : Help content cannot be found. Make sure the server is available and the help content location is properly defined in the HelpInfo XML..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
, noting that "English-US help content is available and can be installed using: Update-Help -UICulture en-US."

Following the instructions to add '-UICulture en-US" to the Update-Help command also fails with the exact same error.

### Expected behavior

```console
Help updates correctly.
```

### Actual behavior

```console
Update fails.
```

### Error details

```console
get-error

Exception             :
    Type    : System.Exception
    Message : Failed to update Help for the module(s) 'IISAdministration' with UI culture(s) {en-US} : Help content
cannot be found. Make sure the server is available and the help content location is properly defined in the HelpInfo
XML..
              English-US help content is available and can be installed using: Update-Help -UICulture en-US.
    HResult : -2146233088
CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
FullyQualifiedErrorId : HelpContentNotFound,Microsoft.PowerShell.Commands.UpdateHelpCommand
InvocationInfo        :
    MyCommand        : Update-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : update-help
    PositionMessage  : At line:1 char:1
                       + update-help
                       + ~~~~~~~~~~~
    InvocationName   : update-help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/4976282/189470956-9d92a97e-a255-4f88-bfe1-c906b365074d.png)

**Comment by dkaszews** [comment] 2022-09-10 07:11
The `"English-US is available"` is a stupid hardcoded message that always appears, it's the next thing I want to fix in `Update-Help` after #17696 and #18037 .

Please change the issue title to be more specific, e.g. "Update-Help fails with 404 error running as admin", otherwise it's impossible to sort the issues.

You specifically mention that you're running it as admin, does running as regular user work? I see all failing modules to be non-builtins, can you check `Update-Help -Module 'Microsoft.Powershell.Core' -Force` to see if the PowerShell's own help servers work? Are you connecting via VPN or have other proxy settings that may cause Internet connection issues.

**Comment by SteveL-MSFT** [comment] 2022-09-12 18:04
I believe this is a dupe of https://github.com/PowerShell/PowerShell/issues/13591

**Comment by casterle** [comment] 2022-09-12 20:40
> Here's what I get when I try a regular PS shell:

 Update-Help -Force
Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, DefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'IISAdministration' with UI culture(s) {en-US} : Help content cannot be found. Make sure the server is available and the help content location is properly defined in the HelpInfo XML..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

I've changed the title per your suggestion.

**Comment by casterle** [comment] 2022-09-12 20:41
> I believe this is a dupe of #13591

Yes, I believe so. Strange it didn't come up in the list of suggested reports.

**Closed** 2022-09-13 23:01 UTC
Labels: Resolution-Duplicate, Needs-Triage
