### ISSUE TITLE
Wait-Process -InputObject $P where $P= Start-Process with credentials, Passtru and no -Wait results is Access Denied

### ISSUE THREAD

**Issue by jjsmeets** [PowerShell/PowerShell#19410] opened 2023-03-27 17:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

#I can not use Wait-Process  to wait for a process started with Start-Process -PassTru -Credials $credential (other user)

$Script_Str ='D:\_DATA\_PUBLIC_DATA\_f_shared\_batch\_scripts\Slideshow_runAndWait_sub2.ps1'
$Process1 =Start-Process pwsh.exe -PassThru   -credential $Credentials  -ArgumentList "-file $Script_Str" 
wait-Process -InputObject $Process1

### Expected behavior

```console
The applet Wait-Process should continue as soon as the started process has ended
```

### Actual behavior

```console
I get Access Denied and also timeout message
```

### Error details

```console
Wait-Process: 
Line |
   3 |  wait-Process -InputObject $Process1
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command stopped operation of "pwsh (3844)" because of the following error: Toegang geweigerd..
Wait-Process: 
Line |
   3 |  wait-Process -InputObject $Process1
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command stopped operation because process "pwsh (3844)" is not stopped in the specified time-out.

get_error reports only last error:

Exception             : 
    Type    : System.TimeoutException
    Message : This command stopped operation because process "pwsh (3844)" is not stopped in the specified time-out.
    HResult : -2146233083
TargetObject          : System.Diagnostics.Process
CategoryInfo          : CloseError: (System.Diagnostics.Process:Process) [Wait-Process], TimeoutException
FullyQualifiedErrorId : ProcessNotTerminated,Microsoft.PowerShell.Commands.WaitProcessCommand
InvocationInfo        : 
    MyCommand        : Wait-Process
    ScriptLineNumber : 3
    OffsetInLine     : 1
    HistoryId        : 37
    Line             : wait-Process -InputObject $Process1
    Statement        : wait-Process -InputObject $Process1
    PositionMessage  : At line:3 char:1
                       + wait-Process -InputObject $Process1
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : wait-Process
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo :
```

### Environment data

```powershell
[32;1mName                          [0m[32;1m Value[0m
[32;1m----                          [0m [32;1m-----[0m
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

remarks: in powershell 7.4 preview 2 the same kind of problem was solved which involved
$p =Start-Process -PassTru -Credentials and -Wat.
That works now but Wait-Process -InputObject -$p does still not work.
($p.waitforExit however was already working in powershell 5 en 7)

**Comment by jborean93** [comment] 2023-03-27 19:30
This is essentially a duplicate of https://github.com/PowerShell/PowerShell/issues/19411#issuecomment-1485747707

**Comment by jjsmeets** [comment] 2023-03-27 21:04
I do not agree that it is a duplicate. Perhaps the background reason is the same .Net issue but it are completely different powershell issues.
The same .Net problem were mentioned as the background reason for the -Wait problem on the start-process, but that was solved, so why can these issues not be solved used the same (interrnal) technique?

**Comment by jborean93** [comment] 2023-03-27 21:16
It is, the process object you get back from `Start-Process` is very limited in what you can do as your user does not have permissions to work with that token.

> The same .Net problem were mentioned as the background reason for the -Wait problem on the start-process, but that was solved, so why can these issues not be solved used the same (interrnal) technique?

Using `Start-Process -Credential ... -Wait` was solved because internally it still had access to the full process token where it could do things like wait until it was done ("synchronization rights"). Unfortunately that full process token is discarded and dotnet has no way to say hey give me a [System.Diagnostics.Process](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-7.0) object from that process handle. It is forced to use `[System.Diagnostics.Process]::GetProcessById($newProcId)` to get a new process object but now it's subject to the same access checks that user normally would have when inspecting other processes.

The ultimately fix is to stop doing the work manually in `Start-Process` to spawn the new process and just use the dotnet API directly. This was not possible before as dotnet didn't expose all the options that pwsh has but with the merging off https://github.com/dotnet/runtime/pull/82662 it should now be possible to do so.

**Comment by jjsmeets** [comment] 2023-03-28 11:12
Ok I understand that during start-process the solution could be different (because of the internal available token), But why does $p.WaitForExit be different then Wait-Process while they both only wait for the process itself (while start-process -Wait should/will wait for the full process-tree (also started child processes!)

**Comment by jborean93** [comment] 2023-03-28 20:48
The process object you get back from `Start-Process -PassThru` doesn't have enough rights on the process itself. to do things like waiting for it to exit or checking the exit code. This is because your user account doesn't have permissions over the new process that is running as another user. It's like doing:

```powershell
Start-Process pwsh.exe -Credential $cred
$proc = Get-Process -Name pwsh
$proc.WaitForExit()
```

Windows does give the creator of the new process a handle to that process with full access to do whatever they want but the way PowerShell starts it and how dotnet works it is unable to embed that token in the `Process` object returned by `Start-Process`.  The only way around this is to have dotnet create the process as another user as in that scenario the process object contains that full access handle.

**Closed** 2023-03-29 23:00 UTC
Labels: Resolution-Duplicate, Needs-Triage
