### ISSUE TITLE
Select-String with multiple patterns doesn't apply the -AllMatches switch as expected

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7765] opened 2018-09-11 22:33 UTC
The `-Pattern` parameter is `[string[]]`-typed and passing multiple patterns means that an input string matching _any_ of them is reported as a match, in order.

If you additionally specify `-AllMatches`, however, it seems that only the _first_ matching pattern's matches are reported.

Steps to reproduce
------------------

```powershell
"foo baar" | Select-String -Pattern 'a', 'o'  -AllMatches | % { $_.Matches.value }
```

Expected behavior
-----------------

```none
a
a
o
o
```

Note: Outputting the matched strings in the order in which they are encountered on each input line is arguably better, as happens if you use  single `-Pattern`  `'a|o'` - see below.

Actual behavior
---------------

```none
a
a
```

That is, the second pattern's matches were not reported.

By contrast, using a _single_ `-Pattern` argument with a regex that uses _alternation_  - `'a|o'` - finds all matches, as expected:

```powershell
PS> "foo baar" | Select-String -Pattern 'a|o'  -AllMatches | % { $_.Matches.value  }
o
o
a
a
```

Note that the order of the patterns separated with `|`  is not reflected in the _output_ order - instead, the output order reflects the order in which the matching substrings were found in the input.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-rc.1 on macOS 10.13.6
PowerShell Core v6.1.0-rc.1 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-rc.1 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
Windows PowerShell v5.1.17134.165 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

**Comment by mklement0** [comment] 2018-09-12 14:19
Thanks for labeling, @iSazonov.

It probably doesn't matter much in the grand scheme of things, but I would consider this a _bug_, not an enhancement, given that nothing in the help topic suggests that combining multiple patterns with `-AllMatches` isn't supported.

**Comment by iSazonov** [comment] 2018-09-12 15:39
I thought that this was probably "by design" for "AllMatch". If not, we can always change the label. I already fixed something like this in `Get-WinEvent` and the fix was more an enhancement than a bug fix.

**Comment by mklement0** [comment] 2018-09-12 15:45
Again, it's probably fine labeled either way, but I can't  even come up with a speculative design rationale for this behavior (but perhaps there is - do tell us), not least because it amounts to quietly ignoring arguments.

**Comment by iSazonov** [comment] 2018-09-12 17:40
We often implement the simplest version and leave the rest until feedback is received.

**Comment by mklement0** [comment] 2018-09-12 17:46
I would call leaving things unimplemented and then _quietly ignoring attempts to call unimplemented features_ a bug.

**Comment by animasc** [comment] 2020-02-28 15:20
I just found the same issue today, and here I am :)
Any chance this will be fixed? It seems it hasn't move in a while
Thanks

**Comment by iSazonov** [comment] 2020-02-28 17:00
> Any chance this will be fixed?

Yes :-)

**Closed** 2023-11-23 12:52 UTC
Labels: Issue-Enhancement, WG-Cmdlets-Utility, Resolution-No Activity
