### ISSUE TITLE
Update-Help Failing to Update on Windows 11 PowerShell version 7.3.1

### ISSUE THREAD

**Issue by WhiteC95** [PowerShell/PowerShell#18869] opened 2022-12-30 02:06 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I am running the Update Help command I am returned error: Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, DefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

When running the suggest command above it returns the same error

### Expected behavior

```console
Updated information for Get-Help modules
```

### Actual behavior

```console
Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, DefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

### Error details

```console
Exception             :
    Type    : System.Exception
    Message : Failed to update Help for the module(s) 'ConfigDefenderPerformance, DefenderPerformance, Dism, Get-NetView, Kds,
NetQos, PcsvDevice, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status
code does not indicate success: 404 (The specified blob does not exist.).).
              English-US help content is available and can be installed using: Update-Help -UICulture en-US.
    HResult : -2146233088
CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
InvocationInfo        :
    MyCommand        : Update-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : update-help -force
    PositionMessage  : At line:1 char:1
                       + update-help -force
                       + ~~~~~~~~~~~~~~~~~~
    InvocationName   : update-help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/121649597/210027377-7986c220-aaff-4b8c-85c4-0b035292f09a.png)

**Comment by SteveL-MSFT** [comment] 2022-12-31 12:40
All the modules listed are part of Windows and not PowerShell itself so the issue that the help content isn't being found seems to be a dupe of https://github.com/PowerShell/PowerShell/issues/13591.  However, the part about en-us help being available is clearly wrong and we should update that part of the error message (probably just remove it) is a dupe of https://github.com/PowerShell/PowerShell/issues/13591

**Closed** 2023-01-01 14:00 UTC
Labels: Resolution-Duplicate
