### ISSUE TITLE
& operator launches commands differently in 7.3.0

### ISSUE THREAD

**Issue by wasker** [PowerShell/PowerShell#18568] opened 2022-11-15 21:18 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

[Program.cs.txt](https://github.com/PowerShell/PowerShell/files/10016244/Program.cs.txt)
[test.ps1.txt](https://github.com/PowerShell/PowerShell/files/10016245/test.ps1.txt)

1. Build C# app called blah.exe using Program.cs, make sure it's on the path.
2. Run `pwsh -f test.ps1` and observe the output.

### Expected behavior

```console
On 7.2.7:

Something will happen: working...
Something will happen: done.
--set
deployment.environment=blah
--set
deployment.region=blah
--set
deployment.image.repository=blah
```

### Actual behavior

```console
On 7.3.0:

Something will happen: working...
Something will happen: done.
--set
deployment.environment="blah"
--set
deployment.region="blah"
--set
deployment.image.repository="blah"
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2022-11-15 21:57
This is ultimately a duplicate of #18554, but let me add some context:

* v7.3 introduced a breaking change with respect to how *arguments with embedded `"` characters* are passed to _external programs_: a longstanding bug was fixed, fully on Unix, partially on Windows.

* Existing workarounds that build on the old, broken behavior now _break_ - except in calls to batch files and WSH scripts, where the legacy workarounds will continue to work by default.
  * To make such legacy workarounds work in v7.3+, you need to set the [`$PSNativeCommandArgumentPassing` preference variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Preference_Variables#psnativecommandargumentpassing) (temporarily) to `'Legacy'` 

* The fixed behavior now correctly escapes embedded `"` characters as `\"` on the process command line PowerShell constructs behind the scenes, which is the [most widely observed convention on Windows](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args#parsing-c-command-line-arguments).

  * Thus, an argument such as ``"deployment.environment=`"blah`""``, which from PowerShell's perspective has a _verbatim_ value of `deployment.environment="blah"` is now placed as follows on the target process' command line: `"deployment.environment=\"blah\""`, and if the target process observes the aforementioned convention, it ends up parsing that again as _verbatim_ `deployment.environment="blah"`, which is what you saw.

There's additional background information in [this Stack Overlfow answer](https://stackoverflow.com/a/74440425/45375).

**Comment by wasker** [comment] 2022-11-15 22:53
Thank you for the links!

There's no mention of this behavior change in relnotes for 7.3.0 - https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0

**Comment by mklement0** [comment] 2022-11-15 23:37
My pleasure, @wasker.

> There's no mention of this behavior change in relnotes for 7.3.0 -https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0

That GitHub link doesn't provide a _cumulative_ view of what changed in that release - it just shows whatever changed in the _final commit_ that led to the release.

* While you _could_ infer the cumulative changes from https://github.com/PowerShell/PowerShell/releases,
**the official what's-new summary for a given release _should_ be at https://learn.microsoft.com/en-us/powershell/scripting/whats-new/overview**

* However, as of this writing, https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-73 does _not_ contain the relevant information.

* The **[PowerShell Team blog](https://devblogs.microsoft.com/powershell/)** at https://devblogs.microsoft.com/powershell/powershell-7-3-general-availability/ at least _mentions_ the feature that caused the breaking change, but, to my mind, that description is inadequate, given that the fact that it is _breaking_ isn't even mentioned.
  * As an aside: The post also suggests that the _experimental_ `PSNativeCommandErrorActionPreference` was made  stable, but from what I can tell that isn't actually the case.

**Comment by mklement0** [comment] 2022-11-16 02:16
See also:
 * https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5152

**Closed** 2022-11-17 12:00 UTC
Labels: Resolution-Answered
