### ISSUE TITLE
$PSStyle cause issues in the PowerShell  Console

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#14435] opened 2020-12-16 05:59 UTC
## Simple repro

```
Write-Verbose -verbose "verbose";Write-Output "out"
```

## expected output

![image](https://user-images.githubusercontent.com/10873629/106670455-e7cae900-6561-11eb-89b5-651fefb64e0d.png)

## Actual results

![image](https://user-images.githubusercontent.com/10873629/106670499-fca77c80-6561-11eb-8bcc-5f71b64be524.png)

## VSCode reproduce

```powershell
$PSVersionTable
```

```
$PSStyle.Formatting.Warning = $PSStyle.Background.Magenta + $PSStyle.Foreground.Yellow + $PSStyle.Bold + $PSStyle.Italic
Write-Warning "Colours!"
```

## Expected behavior

![image](https://user-images.githubusercontent.com/7009879/102310645-412e7880-3f20-11eb-973d-4822c3453b15.png)

and something like this:

![image](https://user-images.githubusercontent.com/7009879/102310657-4ab7e080-3f20-11eb-8010-38dddabe2faa.png)

## Actual behavior

Notice the yellow:

![image](https://user-images.githubusercontent.com/7009879/102310845-a08c8880-3f20-11eb-8575-3513e96ee437.png)

![image](https://user-images.githubusercontent.com/7009879/102310875-b306c200-3f20-11eb-8d34-4d5f7cfd48d2.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TylerLeonhardt** [comment] 2020-12-16 06:58
Also worth looking at .NET Interactive - another pshost.

**Comment by SeeminglyScience** [comment] 2020-12-16 15:41
Hmm I can't repro the color leaking.  As for the style not taking effect, yeah every custom host will need to implement this themselves.

It would be nice if `ConsoleHost` was redesigned somewhat to be inheritable. That doesn't really help PSES and such right now unless it's polyfilled but it would save a lot of headache in the future.

**Comment by rjmholt** [comment] 2020-12-16 17:14
> As for the style not taking effect, yeah every custom host will need to implement this themselves.

I think we need a bit more platform-oriented thinking here

**Comment by SeeminglyScience** [comment] 2020-12-16 17:37
> I think we need a bit more platform-oriented thinking here

Yeah I'm with ya there. I'm not really sure how though, those streams don't make it to anything like the formatter where this could be processed in a host agnostic way.  In most cases `MshCommandRuntime.WriteVerbose` goes directly to `PSHostUserInterface.WriteVerboseLine`.

Another challenge is that escape sequences do not do much to describe what a GUI host should do.  I didn't see the PR at the time, but if I did I would have recommended removing the customizations of the other streams until this was fleshed out a little bit more.

**Comment by SteveL-MSFT** [comment] 2021-08-04 21:29
This seems to be working fine with 7.2-preview.8

**Comment by SteveL-MSFT** [comment] 2021-08-04 22:17
I think this is a dupe of https://github.com/PowerShell/PowerShell/issues/14506 which was already fixed

**Comment by rjmholt** [comment] 2021-08-04 23:24
> ```
> $PSStyle.Formatting.Warning = $PSStyle.Background.Magenta + $PSStyle.Foreground.Yellow + $PSStyle.Bold + $PSStyle.Italic
> Write-Warning "Colours!"
> ```

This doesn't produce the magenta background, but otherwise things seem to be working.

![image](https://user-images.githubusercontent.com/7009879/128268035-de777b17-3590-40d7-ad98-124e817a9377.png)

**Closed** 2021-08-04 23:24 UTC
Labels: Issue-Bug, Resolution-Duplicate, WG-Interactive-Console
