### ISSUE TITLE
Get-Command does not correctly parse SemVer2 version strings

### ISSUE THREAD

**Issue by peterwald** [PowerShell/PowerShell#9621] opened 2019-05-16 21:45 UTC
msbuild.exe in this example has `AssemblyInformationalVersion` in [SemVer2](https://semver.org/) format

```csharp
[assembly: AssemblyInformationalVersion("16.2.0-preview.19264.2+c3389964cd55d027344584a70cc8f3f9e0fb348b")]
```

# Steps to reproduce

```powershell
(Get-Command "msbuild.exe").Version
``` 

# Expected behavior

```
16.2.0
```

# Actual behavior

```
0.0.0.0
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18898
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2019-05-17 12:07
Please share output:
```powershell
Get-Command "msbuild.exe" | fl -Force
```

**Comment by rainersigwald** [comment] 2019-05-17 13:43
This is with a local build from `master` of https://github.com/microsoft/msbuild:

```
PS C:\src\msbuild> Get-Command "artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe" | fl -Force

Name            : MSBuild.exe
CommandType     : Application
Definition      : C:\src\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe
Extension       : .exe
Path            : C:\src\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe
FileVersionInfo : File:             C:\src\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe
                  InternalName:     MSBuild.exe
                  OriginalFilename: MSBuild.exe
                  FileVersion:      16.200.19.26501
                  FileDescription:  MSBuild.exe
                  Product:          Microsoft® Build Tools®
                  ProductVersion:   16.2.0-dev.19265.1+6fb715ffc05160f2374550e546162df16b8d8d1b
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:         Language Neutral



PS C:\src\msbuild> (Get-Command "artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe").Version

Major  Minor  Build  Revision
-----  -----  -----  --------
0      0      0      0
```

Same results on pwsh 6.2.0 (pasted here) and inbox 5.1.18362.1.

**Comment by iSazonov** [comment] 2019-05-17 14:08
I think it is .Net Core issue. We use [System.Diagnostics.FileVersionInfo]::GetVersionInfo("path") - can you  repo?

**Comment by peterwald** [comment] 2019-05-17 15:16
Here is the output from `GetVersionInfo()`

```
PS> [System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\MSBuild\Current\Bin\MSBuild.exe") | fl

OriginalFilename  : MSBuild.exe
FileDescription   : MSBuild.exe
ProductName       : Microsoft® Build Tools®
Comments          : MSBuild.exe
CompanyName       : Microsoft Corporation
FileName          : C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\MSBuild\Current\Bin\MSBuild.exe
FileVersion       : 16.200.19.26402
ProductVersion    : 16.2.0-preview.19264.2+c3389964cd55d027344584a70cc8f3f9e0fb348b
IsDebug           : False
IsPatched         : False
IsPreRelease      : False
IsPrivateBuild    : False
IsSpecialBuild    : False
Language          : Language Neutral
LegalCopyright    : © Microsoft Corporation. All rights reserved.
LegalTrademarks   :
PrivateBuild      :
SpecialBuild      :
FileVersionRaw    : 16.200.19.26402
ProductVersionRaw : 0.0.0.0
```

**Comment by peterwald** [comment] 2019-05-17 15:28
Similarly:

```csharp
var fv = FileVersionInfo.GetVersionInfo(@"C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\MSBuild\Current\Bin\MSBuild.exe");
Console.WriteLine($"ProductVersion: {fv.ProductVersion}");
Console.WriteLine($"ProductMajorPart: {fv.ProductMajorPart}");
Console.WriteLine($"ProductMinorPart: {fv.ProductMinorPart}");
Console.WriteLine($"ProductBuildPart: {fv.ProductBuildPart}");
Console.WriteLine($"ProductPrivatePart: {fv.ProductPrivatePart}");
```
produces

```
ProductVersion: 16.2.0-preview.19264.2+c3389964cd55d027344584a70cc8f3f9e0fb348b
ProductMajorPart: 0
ProductMinorPart: 0
ProductBuildPart: 0
ProductPrivatePart: 0
```

**Comment by iSazonov** [comment] 2019-05-17 15:32
@peterwald Thanks! It is .Net Core issue. Please report in CoreFX repo.

**Comment by KalleOlaviNiemitalo** [comment] 2019-05-17 16:05
<https://github.com/PowerShell/PowerShell/blob/v6.2.0/src/System.Management.Automation/engine/ApplicationInfo.cs#L97> constructs the value of the `Version` property from `ProductMajorPart` etc..

<https://github.com/dotnet/corefx/blob/v2.1.0/src/System.Diagnostics.FileVersionInfo/src/System/Diagnostics/FileVersionInfo.Windows.cs#L156> copies `_productMajor` etc. from the `PRODUCTVERSION` numbers of the [VERSIONINFO resource](https://docs.microsoft.com/windows/desktop/menurc/versioninfo-resource). It never parses the `ProductVersion` string in the [StringFileInfo block](https://docs.microsoft.com/en-us/windows/desktop/menurc/stringfileinfo-block), just copies that as is. I think that is OK and CoreFX should not be changed. Win32 does not specify the format of the `ProductVersion` string, so the party providing the file should set both the `PRODUCTVERSION` numbers and the `ProductVersion` string.

If getting zeroes as the version is a problem, I think that should be fixed in how MSBuild is built. microsoft/msbuild#1249 looks related and added a test but `ProjectCollection.Version` was changed again in microsoft/msbuild#1311 so the `PRODUCTVERSION` numbers may have regressed after that without causing the test to fail.

**Comment by rainersigwald** [comment] 2019-05-17 16:30
@KalleOlaviNiemitalo I was chasing the same thing:

![image](https://user-images.githubusercontent.com/3347530/57941616-462ed000-7884-11e9-844a-9c22e1d3f997.png)

The recent change that caused this is https://github.com/microsoft/msbuild/pull/4318; the two issues you looked at were about different versions.

**Comment by peterwald** [comment] 2019-05-17 16:40
Sure enough the ProductVersion resource itself is all zeroes. I hadn't noticed that. @rainersigwald do you want me to open an corresponding issue in msbuild?

**Closed** 2019-05-17 16:41 UTC
Labels: Issue-Question, Resolution-External

**Comment by rainersigwald** [comment] 2019-05-17 16:45
@peterwald at the moment I'm not sure which layer the problem is in, chasing it now.

**Comment by rainersigwald** [comment] 2019-05-17 20:58
The root cause turned out to be all the way down in Roslyn: https://github.com/dotnet/roslyn/issues/35793.
