### ISSUE TITLE
Write-Host problem:'_' in a string,the setting of anti - human thinking

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#4516] opened 2017-08-07 06:17 UTC
who can tell me what is wrong?
Is it bug?

Steps to reproduce
------------------
$a = 'aaa'
$b = 'bbb'
Write-Host "$a_$b" #return bbb
Write-Host "$a____$b" #return bbb
Write-Host "$azzzzzzzz_yyyyyyyyy$b" #return bbb， zzz = any string ,yyy = any string 
Write-Host "$a_cccccccc" #return empty string
Write-Host "$addddddd_eeeeee" #return empty string
#==============================
Write-Host "$a'_$b" #return aaa'_bbb, return is right        
Write-Host "$a-$b" #return aaa-bbb,return is right
Write-Host "$a+$b" #return aaa+bbb,return is right
Write-Host "$a~!@#$%^&*()-$b" #return aaa~!@#$%^&*()-bbb,return is right

Environment data
----------------
windows 10 14393 (powershell 5.1)
centos 7.3  + powershell core 6.0 beta5

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by jeffbi** [comment] 2017-08-07 06:38
Not a bug, I think. In your examples, the underscore (`_`) is part of the variable name (`$a_`, `$a____`, etc.). Those variable names don't exist yet and evaluate to `$null`, which is then concatenated within the string with the variable `$b` which does exist, resulting in `bbb`

**Comment by chuanjiao10** [comment] 2017-08-07 06:43
$azzzzzzzz_yyyyyyyyy is 'Those variable names don't exist yet' ?

**Comment by jeffbi** [comment] 2017-08-07 06:53
Yes.
```PowerShell
PS >$a = "aaa"
PS >$b = "bbb"
PS >$azzzzzzzz_yyyyyyyyy -eq $null
True
PS >"$azzzzzzzz_yyyyyyyyy$b"
bbb
PS >"$null$a"
aaa
```

**Comment by chuanjiao10** [comment] 2017-08-07 09:47
I understand,
with "_",write-Host can not split the string,get the correct variable.
with "+","-",write-Host can split the string,get the correct variable.

**Comment by mklement0** [comment] 2017-08-07 13:39
@chuanjiao10: Because you created this issue, you have the ability to close it yourself.

Also note that you can always enclose the variable name in `{...}` in order to disambiguate it from subsequent characters:

```powershell
Write-Host "${a}_$b" # returns 'aaa_bbb'
```

**Closed** 2017-08-07 13:57 UTC
Labels: Issue-Question, Resolution-Answered
