### ISSUE TITLE
stop parsing symbol: double-quotes parse first, before variable substitution

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#7635] opened 2018-08-27 04:36 UTC
Steps to reproduce
------------------
I am describing a wild use case here, but noticed this while reading about_Parsing doc, referring to the stop-parsing symbol.  The doc states that %% environment variable substitution occurs as well, as well as supports the pipe character to end the command.  I quickly determine that double quotes are also included in the parsing past the stop-parsing symbol.  The double quote parsing seems to apply before the variable substitution.

```powershell
${env:hello" } = $env:homepath
cmd --% /k %hello" % | write-host
```

Never mind the /k, this was so I could see the result and test environment variables in CMD.  Funny thing, CMD destroyed the %CMDCMDLINE% dynamic variable, instead filling it with the error message instead of the command line.

Expected behavior
-----------------

I expected CMD to get called, echo my home path, and then powershell would pipe the result back to write-host, all just for an example.  I expect the double-quote in the variable name to be treated only as part of the variable name, and not for string parsing through the rest of the command line.

Actual behavior
---------------

Instead, CMD tells me that `write-host is not recognized as an internal or external command, operable program, or batch file.`

Task manager indicates the command line to CMD was `/k echo \Users\[user] | write-host`

This indicates the double-quote in the environment variable expression was treated as capturing the pipe character.

I was attempting to provide support for the pipe handling in a fork of VS Code's PowerShell syntax scoping tmLanguage document, but this makes it really difficult to do right.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by msftrncs** [comment] 2018-08-27 04:49
Now, this said, I can understand why what I expect is not what I get, but that doesn't help me not expect it.  

When I first read about the stop-parsing symbol, I had the understanding that no more parsing occurred past it, and that is how VS Code's PowerShell syntax scoping treats it, but now I know that is not the case, and I actually think the --% symbol is worse at providing the solution than the problem it solves, because there is still behavior I cannot always account for.   

At least in CMD scripting when I need to MAKE SURE a '%' gets passed, I can use two '%%', and the variable substitution is not conducted, but that doesn't even happen here; instead I got the substitution surrounded with '%'s.  

At least using a regular native command construct in PowerShell, I know exactly how to escape it, and I know I have to do it if I move the command from another scripting engine, but the --% stop parsing symbol doesn't assure me that I can just not translate at all, and in some cases, may not even work.

So, I am not sure there is anything that can be fixed here, as its much more complicated than it would first seem.

**Comment by rjmholt** [comment] 2018-08-27 05:38
Looks like this is the behaviour in Windows PowerShell too.

Compare the following:
```powershell
> $env:banana = "Hi"
> cmd /c --% echo %banana% | Write-Output -OutVariable x
Hi
> $x
Hi
```

And
```powershell
> ${env: " banana} = "Hi"
> cmd /c --% echo % " banana% | Write-Output -OutVariable x
'Write-Output' is not recognised as an internal or external command, operable program or batch file.
```

If you enter this interactively with PSReadLine enabled you can see that the insertion of a quote before the pipe causes the `Write-Output` to not register as a command name, so I'm guessing this is a bug where the tokeniser is still looking for a closing quote rather than being in "stop-parsing" mode and looking only for a `|` or a newline.

**Comment by BrucePay** [comment] 2018-08-28 18:56
If you look in [tokenizer.cs:2017](https://github.com/PowerShell/PowerShell/blob/358e8abefef5973b7e1f9608a38240846f620a59/src/System.Management.Automation/engine/parser/tokenizer.cs#L2017) you will see that '"' is processed explicitly to allow '|' and '&&' to be included in the args to `cmd.exe`.  So there is still some level of processing going on after `--%`. This is easy enough (but breaking)  to change but is it worth it to lose the ability to use `|` and `&&` in `cmd` cmds in favour of allowing double quotes in variables? (Is that really a common thing?). Certainly this is a docs issue as there is nothing about this behaviour in the docs at all: [about_Parsing](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-6) Overall, the doc'ed behaviour - consumes everything up to a newline might be better. You wouldn't be able to stream the output of the command into a pipeline, but you could still capture it in a variable. And `|` and `&&` would still work for `cmd.exe`.

**Comment by BrucePay** [comment] 2018-08-28 18:58
I've marked it as Issue-Discussion. Technically it's working as by design. Whether we want to keep that design is an open question. Perhaps this is a candidate for an `Experimental` flag.

**Closed** 2023-11-23 12:53 UTC
Labels: WG-Interactive-Console, WG-Language, Issue-Discussion, Resolution-No Activity
