### ISSUE TITLE
can't pass urls with wildcard characters to curl

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#4675] opened 2017-08-25 19:35 UTC
Steps to reproduce
------------------

```powershell
PS> curl http://zip.zap.zop/zup?zep                                                                                                         

```

Expected behavior
-----------------
`http://zip.zap.zop/zup?zep` is passed to curl

Actual behavior
---------------

```none
Cannot find drive. A drive with the name 'http' does not exist.
At line:1 char:1
+ curl http://zip.zap.zop/zup?zep
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (http:String) [], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound
 

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                       
----                           -----                                                                                                       
PSVersion                      6.0.0-beta                                                                                                  
PSEdition                      Core                                                                                                        
GitCommitId                    v6.0.0-beta.5                                                                                               
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X...
Platform                       Unix                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                         
SerializationVersion           1.1.0.1                                                                                                     
WSManStackVersion              3.0   

```

**Comment by SteveL-MSFT** [comment] 2017-08-25 19:45
Dupe of https://github.com/PowerShell/PowerShell/issues/3931 (see most recent repro at bottom)

**Closed by SteveL-MSFT** 2017-08-25 19:45 UTC
Labels: Resolution-Duplicate
