### ISSUE TITLE
Powershell 6.0.0 AppImage crashes after a few seconds on CentOS Linux 7.4

### ISSUE THREAD

**Issue by Chaz6** [PowerShell/PowerShell#5880] opened 2018-01-12 15:01 UTC
Steps to reproduce
------------------

```
$ powershell
```

Expected behavior
-----------------

Application does not crash.

Actual behavior
---------------

```
$ powershell
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_f8fJ9u/usr/bin/pwsh.wrapper from within an AppImage.
PowerShell v6.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /tmp> Segmentation fault
```

Backtrace:-

```
[Switching to Thread 0x7fffe9f91700 (LWP 17163)]
0x00007fff562cb99f in __libc_res_nsend () from /lib64/libresolv.so.2
(gdb) bt
#0  0x00007fff562cb99f in __libc_res_nsend () from /lib64/libresolv.so.2
#1  0x00007fff562c8c5e in __libc_res_nquery () from /lib64/libresolv.so.2
#2  0x00007fff562c9840 in __libc_res_nsearch () from /lib64/libresolv.so.2
#3  0x00007fff2f4eac2d in _nss_dns_gethostbyname4_r () from /tmp/.mount_IHLoIp/usr/lib/libnss_dns.so.2
#4  0x00007ffff6eb9ed8 in gaih_inet () from /lib64/libc.so.6
#5  0x00007ffff6ebd5cd in getaddrinfo () from /lib64/libc.so.6
#6  0x00007fffe632feb4 in ?? () from /tmp/.mount_IHLoIp/usr/lib/libcurl.so.4
#7  0x00007fffe633cd64 in ?? () from /tmp/.mount_IHLoIp/usr/lib/libcurl.so.4
#8  0x00007fffe633a60b in ?? () from /tmp/.mount_IHLoIp/usr/lib/libcurl.so.4
#9  0x00007ffff79c2e25 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff6ed434d in clone () from /lib64/libc.so.6
```

Environment data
----------------

```
$ uname -r
3.10.0-693.11.6.el7.x86_64
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
$ rpm -q glibc
glibc-2.17-196.el7_4.2.x86_64
glibc-2.17-196.el7_4.2.i686
```

**Comment by KurtPfeifle** [comment] 2018-01-12 15:11
Ping @probonopd ...

**Comment by markekraus** [comment] 2018-01-12 15:18
I believe this is either a duplicate of or related to #5053

**Comment by iSazonov** [comment] 2018-01-12 16:39
Again libcurl

**Closed** 2023-11-23 13:31 UTC
Labels: Area-Maintainers-Build, Resolution-No Activity
