### ISSUE TITLE
(PSCore, Linux) Split method does not work with multiple delimiters

### ISSUE THREAD

**Issue by gellertb97** [PowerShell/PowerShell#7585] opened 2018-08-21 16:45 UTC
Steps to reproduce
------------------

```powershell
$a = "192.168.2.1/25"
$a.Split("./")
```

Expected behavior
-----------------

```none
192
168
2
1
25
```

Actual behavior
---------------

```none
192.168.2.1/25
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                         
----                           -----                                                                                         
PSVersion                      6.0.4                                                                                         
PSEdition                      Core                                                                                          
GitCommitId                    v6.0.4                                                                                        
OS                             Linux 4.14.65-1-MANJARO #1 SMP PREEMPT Sat Aug 18 13:29:56 UTC 2018                           
Platform                       Unix                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                       
PSRemotingProtocolVersion      2.3                                                                                           
SerializationVersion           1.1.0.1                                                                                       
WSManStackVersion              3.0     
```

Comments
--------------
```
PowerShell Core 6.0.4 installed on Manjaro Linux (Arch) via snapcraft

Performing a split operation with one delimiter, i.e.
> $a.Split('.')
still provides expected output:
> 192
> 168
> 2
> 1/25
```

**Comment by MaximoTrinidad** [comment] 2018-08-21 17:05
Not sure what's the issue here... I'm using WSL Linux Ubuntu, and in PowerShell Core.

Are you trying to use the split method with two characters: "." and "/"? The following line work as expected. 
```
PS /home/maxt> ($a.Split('.')).split('/')
192
168
2
1
25
PS /home/maxt>
```
![wsl_split_01_2018-08-21_12-56-11](https://user-images.githubusercontent.com/19892435/44417195-e00a5c00-a542-11e8-8e61-dce80046939c.jpg)

**Comment by gellertb97** [comment] 2018-08-21 17:19
Hi Max,
I'm trying to use multiple delimiters, as described in online resources. $a.Split('./')

Tested and working in Windows PowerShell 5.1. 
(I'm not in close proximity of a personal windows machine at the moment, will try to get you a screenshot...)

**Comment by MaximoTrinidad** [comment] 2018-08-21 17:28
Good Catch!!  
Ah! You didn't mention it work in Windows PowerShell.  It's a bug!
:)

Either methods works in Windows PowerShell. 
I'm sure it will be fix!

**Comment by RichardSiddaway** [comment] 2018-08-21 17:34
Is this what you want
PS>  $a = "192.168.2.1/25"
PS>  $a.split([char]".",[char]"/")
192
168
2
1
25

Tested and Works with v5.1, v6.0.4 and v6.1.0-preview4

**Comment by gellertb97** [comment] 2018-08-21 18:15
Either works... But yes, using more than one delimirer in a Split command, e.g. Split('/ :;$.,') works for me in Windows PowerShell

**Comment by mklement0** [comment] 2018-08-21 20:11
It is not a bug, but an unfortunate - and unavoidable - consequence of a new method overload that is `[string]`-typed having been introduced in .NET _Core_.

This issue is therefore a duplicate of #3809; specifically:

* https://github.com/PowerShell/PowerShell/issues/3809#issuecomment-302594098 explains the details (note that the `options` argument of  the overload in question, [`public string[] Split (string separator, StringSplitOptions options = System.StringSplitOptions.None);`](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netcore-2.1#System_String_Split_System_String_System_StringSplitOptions_), is optional)

* https://github.com/PowerShell/PowerShell/issues/3809#issuecomment-302804271 explains why PowerShell, a a late-bound language, is _invariably_ susceptible to such changes in behavior.

The simplest solution is to cast to `[char[]]` or use `.ToCharArray()`:

```powershell
 "192.168.2.1/25".Split([char[]] "./")
```

**Comment by MaximoTrinidad** [comment] 2018-08-22 01:59
Thanks @mklement0!

**Comment by iSazonov** [comment] 2018-08-22 06:38
Leave a comment

**Closed by iSazonov** 2018-08-22 06:38 UTC
Labels: Issue-Question, Resolution-Answered, Resolution-Duplicate

**Comment by gellertb97** [comment] 2018-08-22 10:38
Thanks everyone!
