### ISSUE TITLE
Invoke-WebRequest and Invoke-RestMethod: broken tab completion with respect to common parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10846] opened 2019-10-19 20:36 UTC
Note: I haven't looked into what pattern underlies the behavior: the two cmdlets definitely exhibit the broken behavior, while spot-checking others suggests that they're not affected.

# Steps to reproduce

```powershell
Invoke-WebRequest -out<tab>  # press <tab> repeatedly
Invoke-RestMethod -out<tab>  # press <tab> repeatedly
```

# Expected behavior

`-out` should expand to `-OutFile` (cmdlet-specific parameter), then to common parameters `-OutBuffer` and `-OutVariable`

# Actual behavior

`-out` expands to `-OutFile`, but nothing else.

If you type `-outb` or `-outv` before pressing TAB  - i.e. if you type an _unambiguous_ prefix - the common parameters _are_ found.

# Environment data

```none
PowerShell Core 7.0.0-preview.4
```

**Comment by vexx32** [comment] 2019-10-19 22:18
This seems to be broken for any parameter name that could potentially conflict with a common parameter name from a given tab completion.

```powershell
function test {
    [cmdletbinding()]
    param($Pipecleaner)
}

test -pipe<tab>
```

Tab completion is unable to pickup `-PipelineVariable`

**Comment by SteveL-MSFT** [comment] 2019-10-20 01:03
Dupe of https://github.com/PowerShell/PowerShell/issues/1265

**Closed by SteveL-MSFT** 2019-10-20 01:03 UTC
Labels: Area-Intellisense, Issue-Bug
