### ISSUE TITLE
Cannot load Microsoft.PowerShell.Diagnostics when using the SDK on .Net Core on Windows

### ISSUE THREAD

**Issue by svick** [PowerShell/PowerShell#2108] opened 2016-08-28 13:22 UTC
## Steps to reproduce
1. Use Windows 10, `dotnet` CLI preview 2; don't install PowerShell Core.
2. Create a .Net Core project that references `Microsoft.PowerShell.SDK` version 1.0.0-alpha9 from [the powershell-core MyGet feed](https://powershell.myget.org/gallery/powershell-core/).
3. Add the following code to `Program.cs`:
   
   ``` c#
   using System.Management.Automation;
   
   public class Program
   {
       public static void Main()
       {
           var ps = PowerShell.Create();
   
           ps.AddCommand("gci");
   
           ps.Invoke();
       }
   }
   ```
   
   [The complete project is here.](https://gist.github.com/svick/f230af474d9874c9ae7f976d12e4d405)
4. `dotnet restore`, `dotnet run`.
## Expected behavior

`ps.Invoke()` does not throw.
## Actual behavior

`ps.Invoke()` thows:

```
System.Management.Automation.Runspaces.PSSnapInException: Cannot load Windows PowerShell snap-in Microsoft.PowerShell.Diagnostics because of the following error: Could not load file or assembly 'Microsoft.PowerShell.Commands'. The system cannot find the file specified.
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadMshSnapinAssembly(PSSnapInInfo mshsnapinInfo)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIn(PSSnapInInfo mshsnapinInfo)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIns(Collection`1 mshsnapinInfos, PSConsoleLoadException& warning)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadConsole(PSConsoleLoadException& warning)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.CreateDefaultConfiguration()
   at System.Management.Automation.Runspaces.RunspaceConfiguration.Create()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Program.Main()
```

Puzzling things I found when looking into this:
- There is no package for `Microsoft.PowerShell.Commands.Diagnostics`.
- `PSSnapInReader.DefaultMshSnapins` [contains `Microsoft.PowerShell.Diagnostics` only when `UNIX` is not set](https://github.com/PowerShell/PowerShell/blob/d575308/src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs#L1287-L1290). But there is only one `netstandard1.6` version of `System.Management.Automation.dll` in the `System.Management.Automation` 1.0.0-alpha9 package, compiled without the `UNIX` flag set.
- `PSSnapInInfo.AbsoluteModulePath` [treats the `ModuleName` of `Microsoft.PowerShell.Commands.Diagnostics` as file name with extension](https://github.com/PowerShell/PowerShell/blob/d575308/src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs#L254) and returns just `Microsoft.PowerShell.Commands` (as shown in the exception message above).

**Comment by JanivZ** [comment] 2016-08-29 15:42
Can verify this reproduces

**Comment by vors** [comment] 2016-08-31 12:15
Thank you for reporting it @svick !

Indeed, the nuget package provided `Microsoft.PowerShell.SDK` for alpha9 has windows-specific implementation.
The scenario that you are describing (hosting PS in you own program) is not currently supported. There are mulitply issues that we need to address first to enable it. Here are few:
* Remove need in [custom Assembly Load Context](https://github.com/PowerShell/PowerShell/blob/61255447a03730592dd55623e5a559eacdcac7ba/src/powershell/Program.cs#L27) (ALC for short). This is CoreCLR hosting model and we are blocked until CoreCLR will have `AppDomain.GetAssemblies()`.
* Create nuget packages that contains both unix and windows compiled assemblies.
* Publish `Microsoft.PowerShell.Diagnostics` nuget package (the current list is [here](https://github.com/PowerShell/PowerShell/blob/61255447a03730592dd55623e5a559eacdcac7ba/build.psm1#L1164))

The scenario that we are targeting with current `Microsoft.PowerShell.SDK` is the following:
You should be able to author a **binary powershell module** and use it later in the powershell session.

**Comment by enriquelk** [comment] 2016-10-14 00:33
I am doing the following as a workaround, but it is not ideal. Anyone knows of a better way to use powershell from dotnet core linux?

            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = "powershell";
            psi.UseShellExecute = false;
            psi.RedirectStandardOutput = true;

            psi.Arguments = "Get-Host";
            Process p  = Process.Start(psi);
            string strOutput = p.StandardOutput.ReadToEnd();
            p.WaitForExit();
            Console.WriteLine(strOutput);

**Comment by sonphnt** [comment] 2017-06-08 09:03
Hi @svick 

Did you find out the way to execute PS file in .Net core?
I have installed .Net core 2.0 preview but it does not seems to work.

**Comment by WilliamWsyHK** [comment] 2017-08-13 11:24
How's the progress of hosting PS in you own program doing?
I need this feature badly. :sweat_smile:

**Comment by jherby2k** [comment] 2017-08-15 15:42
I'm encounting this issue now, trying to unit test a binary module I am writing for PowerShell core. This is a big issue! Any workaround??

**Comment by michaelherndon** [comment] 2017-09-18 03:25
@sonphnt, @WilliamWsyHK, @jherby2k 

It works, but it's not like the old way where you just reference System.Management.Automation.   I ran into the same issue and found this page.  Then I started to look in the docs in the repo and found:
https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell

There is a sample app here: https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell/sample-dotnet2.0-powershell.beta.3

you need to copy the Nuget.config from the project. If you're using VS, target the powershell feed withing the UI. 

then install the following packages
```xml
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="6.0.0-beta.7" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="6.0.0-beta.7" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Diagnostics" Version="6.0.0-beta.7" />
```

**Comment by iSazonov** [comment] 2017-09-29 09:20
@SteveL-MSFT Can we close the Issue because we update nuget SDK package and docs?

**Closed** 2017-09-29 16:32 UTC
Labels: Area-Engine, Issue-Enhancement, Issue-Meta, Resolution-Answered

**Comment by ahmadalli** [comment] 2018-02-12 12:31
I'm getting the same exception in version 6.0.1

**Comment by SteveL-MSFT** [comment] 2018-02-12 18:19
A new nuget package is being published (6.0.1.1) which will include cross platform runtimes instead of being Windows specific.  Should be this week.

**Comment by Zetanova** [comment] 2018-04-10 20:09
I have this issue with 6.1.0-preview.1

**Comment by cosminstirbu** [comment] 2019-08-16 11:43
This is still reproducing for me with <PackageReference Include="System.Management.Automation" Version="6.2.2" /> on Windows 10 with `dotnet test`

**Comment by iSazonov** [comment] 2019-08-16 13:35
@cosminstirbu Please open new issue with repo steps.

**Comment by steinbachio** [comment] 2019-09-27 05:35
@cosminstirbu for me it was enough to install Microsoft.PowerShell.SDK (6.2.3)

**Comment by cosminstirbu** [comment] 2019-09-27 08:30
Yeap, I confirm that installing Microsoft.PowerShell.SDK (6.2.3) did the trick.

**Comment by lalitzz** [comment] 2021-10-18 07:30
If I use Microsoft.PowerShell.SDK (6.2.3), I am getting the below error.

The term 'Add-MpPreference' is not recognized as the name of a cmdlet, function, script file, or operable program.

Is there any workaround to fix this?

**Comment by iSazonov** [comment] 2021-10-18 07:54
> Add-MpPreference

I guess the module is not compatible with PowerShell Core. You can try to run the cmdlet in interactive session. Also you could try WinCompat feature of Import-Module cmdlet.

**Comment by iSazonov** [comment] 2021-10-18 13:26
> I guess the only fix for the above is to open the powershell session as an admin(Not sure if this is possible with the current library). Would really appreciate if someone can provide pointer to this?

You should run elevated process - parent or child.
