### ISSUE TITLE
"UNIX time stamp" different between windows and linux 

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2195] opened 2016-09-06 13:37 UTC
## Steps to reproduce

[root@cent72 ~]# date
2016年 09月 07日 星期三 14:10:24 CST

PS /root> get-date -UFormat %s ; date +%s  
1473257427.28919
1473228627

PS C:\Windows\system32\WindowsPowerShell\v1.0>get-date
2016年9月7日 14:10:15
## Expected behavior

Today I encountered a script problem: Unix time stamp, I would like to use PowerShell to deal with, but：

get-date -UFormat %s,Seconds elapsed since January 1, 1970 00:00:00 ,
that is 【int format】! i think,but return decimal. and time zones problem.

Now powershell run in linux,return "UNIX time stamp" should be 【CONSISTENT】！
## Actual behavior

return:(i am chinese user,utc +8)
1473257427.28919
1473228627

8 \* 3600 secode different
## Environment data

win:

Name                           Value

---

PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

timezone：utc+8

centos 7.2:

Name                           Value                                                                                                             

---

PSVersion                      6.0.0-alpha  
PSEdition                      Core  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}  
BuildVersion                   3.0.0.0  
GitCommitId                    v6.0.0-alpha.9  
CLRVersion  
WSManStackVersion              3.0  
PSRemotingProtocolVersion      2.3  
SerializationVersion           1.1.0.1 

LANG=zh_CN.UTF-8

timezone：utc+8

**Comment by GeeLaw** [comment] 2016-09-06 17:50
Don't have my Mac at my hand at this time. But could you include more information in your report? The `$PSVersionTable` for both platforms, the timezone for both platforms. You seem to mix the output in two platforms without specifying the order (which is from Windows?) Do you also have `UTC+8 Beijing, Chongqing, Hong Kong, Urumqi` as your timezone on Unix?

As a workaround, you can retrieve the UNIX timestamp by `([System.DateTime]::UtcNow - [DateTime]::new(1970, 1, 1, 0, 0, 0, 0, 'Utc')).TotalSeconds`.

As we can read from [the code](https://github.com/PowerShell/PowerShell/blob/58a2ba730dddbbf015809420aaaaceb87993c72d/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs#L328), the `Get-Date -UFormat %s` runs to:

```CSharp
DateTime epoch = DateTime.Parse("January 1, 1970", System.Globalization.CultureInfo.InvariantCulture);
// ...
case 's': sb.Append(dateTime.Subtract(epoch).TotalSeconds);
// ...
```

And `dateTime` is `DateTime.Now`. There are two problems:

1. `dateTime.Kind` is not `Utc`, but `Local`;
2. `epoch.Kind` is not `Utc`, but `Unspecified`.

You can hardly get good outcomes with such subtraction. I just tested several cases out:

```PowerShell
([System.DateTime]::UtcNow - [DateTime]::new(1970, 1, 1, 0, 0, 0, 0, 'Utc')).TotalSeconds;
([DateTime]::UtcNow - [DateTime]::Parse("January 1, 1970", [System.Globalization.CultureInfo]::InvariantCulture)).TotalSeconds;
([System.DateTime]::Now - [DateTime]::new(1970, 1, 1, 0, 0, 0, 0, 'Utc')).TotalSeconds;
([DateTime]::Now - [DateTime]::Parse("January 1, 1970", [System.Globalization.CultureInfo]::InvariantCulture)).TotalSeconds;
get-date -uformat %s;
```

They give:

```
1473183902.16113
1473183902.16113
1473212702.16113
1473212702.16113
1473212702.16914
```

The first two are good, it's recommended to get UNIX timestamp with the first one.


**It is surely not desirable to have timezone-sensitive UNIX timestamps -- are they UNIX timestamps at all?** It is recommended to change the way `Get-Date` works. The easiest way to do this would be to 

```CSharp
DateTime dateTimeUtc = DateTime.UtcNow;
DateTime dateTime = dateTimeUtc.ToLocalTime();
```

So that any logic that should use `dateTime` can still be happy, and we should change the logic that requires UTC properly, with minimum change to code (though this violates DRY a bit?).

Could some Microsoft staff confirm whether this is a bug or a desired behaviour? If this is a bug, I'd like to file a PR soon ;-)

**Comment by bjtucker** [comment] 2016-09-09 05:49
Unquestionably converting to UNIX time implies and requires conversion to UTC first. The current behavior is just not correct. 

----

To make Get-Date behave without breaking on local timezone or DST, I'm using these:
  
UNIX time (seconds since epoch) 

    PS> Get-Date ((get-date).toUniversalTime()) -UFormat +%s
    1473392778.39634

    PS> [Math]::Floor(Get-Date ((get-date).toUniversalTime()) -UFormat +%s)
    1473392778

Convert UNIX time to PS DateTime:

    function UnixToPsDate([int]$UnixTime){
        [System.DateTimeOffset]::FromUnixTimeSeconds($UnixTime).datetime.tolocaltime()
    }

----

@GeeLaw your conversion breaks for me. [DateTime]::Parse() converts to local time time, even when fed UTC to parse. and you need to coerce it back to UTC before subtracting.
    ([DateTime]::UtcNow - [DateTime]::Parse('1970-01-01T00:00:00Z').touniversaltime()).TotalSeconds

By stealing [DateTime]::UtcNow and dropping it in what I've been using, we get very concise. I believe this should work in all time zones and in any DST situation.

    get-date ([DateTime]::UtcNow) -UFormat +%s

Or strip the non-integer part for the real UNIX timestamp. I was using [int], but [Math]::Floor is more correct (by about half a second) because [Int] rounds instead of truncating in Powrshell.

    [Math]::Floor(get-date ([DateTime]::UtcNow) -UFormat +%s)

----

Fixing the problem may break some things. It will doubtless fix some things too, where the authors didn't know that the conversion to UNIX time was broken.

All of these methods above will not be broken if this bug is fixed by converting to UTC before printing, since DateTime objects internally track if they're in UTC or local time, and a conversion of a UTC DateTime object to UTC is a noop as it should be.

The biggest chance to break things would be with folks who aren't using UTC, but are instead calculating the offset and subtracting the time offset from local time would break. But these people are probably breaking by an hour when DST switches anyway and just don't know it.

**Comment by GeeLaw** [comment] 2016-09-09 06:03
@bjtucker Sorry didn't verify the `Parse` method... It's surely good to have this problem fixed, but it makes confusion when you specify parts of the `DateTime` with `Get-Date` -- that's extremely confusing, and shouldn't be done. See the second section of my last comment.

**Comment by andschwa** [comment] 2016-09-13 17:52
Yeah, this looks to be the case even for the in-box FullCLR PowerShell on Windows.

Windows PowerShell 5.0:

```powershell
> [int][double]::Parse((Get-Date -UFormat %s))
1473761290
```

Linux:

```sh
$ date +%s                                                                                                                                                                                       
1473786490
```

[(1473761290-1473786490)/(60*60) = -7](https://www.google.com/search?q=(1473761290-1473786490)%2F(60*60))

So it's off by the amount of my timezone (PDT, 7 hour offset).

And applying @bjtucker's idea:

```powershell
$ [int][double]::Parse((get-date (get-date).toUniversalTime() -UFormat +%s))
1473786993
```

Which is correct.

Verified and reproduced: it's a bug.

**Comment by bjtucker** [comment] 2016-10-22 02:16
@GeeLaw I didn't like using get-date within get-date either. That's why used that part of your solution. 

Subtracting from the epoch start date doesn't work during Daylight Saving Time though. It's off by 3600 seconds.  Having get-date make the conversion between utc and localtime in way that is aware of DST resolves that. If you want to make that work without relying on get-date, it's necessary to determine and adjust for DST some other way.

It's ugly, but it is concise and works every time. The real solution is to fix the bug.

I hope that this gets fixed even though it may be a breaking change for a few things. Having something that looks like a unix epoch time, but is off is especially bad since most people can't tell at a glance that it's a few hours off, unlike almost every other format.

Also, my final example was wrong, since I need to finish evaluating the expression before passing it to [Math]::Floor

    PS> [Math]::Floor$(get-date ([DateTime]::UtcNow) -UFormat +%s)
    At line:1 char:14
    + [Math]::Floor$(get-date ([DateTime]::UtcNow) -UFormat +%s)
    +              ~~
    Unexpected token '$(' in expression or statement.
        + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : UnexpectedToken

Forcing early evaluation with more parens makes it work. And makes the thing even uglier. 

    [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s))

But it works....

    PS> [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
    1477100336
    1477100336

**Comment by bjtucker** [comment] 2016-10-22 02:46
File this under trivia if you want, but I'll clarify my concern about using [int] here. It's pedantic for most uses, but for me it was important to match exactly, so I did some research.

UNIX time from the date command is expressed in truncated whole seconds since epoch start, adjusted for leap seconds.

[int] in powershell rounds up for values .5 or above, as does [int][double]::parse(). [Math]::floor() truncates the fractional part to zero.

    PS>  [int](5.6)
6

    PS>  [int][double]::parse(5.6)
6

    PS>  [Math]::floor(5.6)
5

[int] is just fine for most uses, but I'll leave this here just in case someone else with a stringent use needs the conversion to be exactly the same as "date +%s"


Here are some examples showing [int] off by one, some of the time.

    PS> [int]((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102554
**1477102553**

    PS> [int]((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102555
**1477102554**

    PS> [int]((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102556
**1477102555**

    PS> [int]((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102556
1477102556

    PS> [int]((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102557
1477102557

Using [Math]::Floor matches "date +%s" every time.

    PS> [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102567
1477102567

    PS> [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102568
1477102568

    PS /Users/ben> [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102569
1477102569

    PS /Users/ben> [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102569
1477102569

    PS /Users/ben> [Math]::Floor((get-date ([DateTime]::UtcNow) -UFormat +%s)) ; date +%s
1477102577
1477102577

**Closed** 2018-03-16 16:44 UTC
Labels: Area-Cmdlets, Issue-Bug, Up-for-Grabs

**Comment by chuanjiao10** [comment] 2018-03-24 15:20
hi all，Seems to have TIME ZONE problems：
```
PS /root> get-date -UFormat %s ; date +%s
1521933328
1521904528
PS /root> get-date

2018年3月24日星期六 下午11:15:31


PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment] 2018-03-26 04:36
@chuanjiao10 Do the time zone problem exist for all UFormat options?  If so please open new issue.

**Comment by chuanjiao10** [comment] 2018-03-26 04:50
PS /root> get-date -uformat %c ;date +%c
周一 26 3月 2018 12:41:12
2018年03月26日 星期一 12时41分12秒
PS /root> get-date -uformat %l ;date +%l
 0
12
PS /root> get-date -uformat %k ;date +%k
12
12
PS /root> get-date -uformat %s ;date +%s
1522068159
1522039358
PS /root> get-date -uformat %j ;date +%j
085
085


in my test,3 same ,2 different.

**Comment by iSazonov** [comment] 2018-03-26 05:17
@chuanjiao10 Thanks! Could you please test all UFormat arguments? I believe we should have new Issue for the timezone problem.

**Comment by chuanjiao10** [comment] 2018-03-26 06:21
As you wish,I tested all date format string in the man date help.


only list difference：
-----------------------------------

full date; same as %Y-%m-%d
PS /root> get-date -uformat %F ; date +%F
F
2018-03-26

====================================
nanoseconds (000000000..999999999)

get-date -uformat %N ; date +%N
N
890019108

====================================
return like p

PS /root> get-date -uformat %P ; date +%P
P
下午


====================================
Other date output string, no time zone difference ！！！

PS /root> get-date -uformat %s ; date +%s
1522073080
1522044280


====================================
get-date -uformat %W ; date +%W
12
13


====================================
get-date -uformat %z ; date +%z
z
+0800

====================================
PS /root> get-date -uformat %Z ; date +%Z
+08
CST

====================================


The output order of the string is incorrect
or
Is not a local date format
-----------------------------------

PS /root> get-date -uformat %r ; date +%r
02:00:04 下午
下午 02时00分04秒

====================================
PS /root> get-date -uformat %c ; date +%c
周一 26 3月 2018 13:48:06
2018年03月26日 星期一 13时48分06秒


====================================
PS /root> get-date -uformat %x ; date +%x
03-26-18
2018年03月26日


====================================
PS /root> get-date -uformat %X ; date +%X
14:10:14
14时10分14秒


====================================
