### ISSUE TITLE
Fix group policy cache

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2877] opened 2016-12-13 16:25 UTC
The internal Group Policy cache does not use a unique key and ends up returning MachinePolicy ExecutionPolicy for a UserPolicy query.  

Update the cache code to use a fully unique key.

Investigate using a Tuple instead of concatenated string for the cache key to improve performance.

Steps to reproduce
------------------
Set Group Policy UserPolicy, ExecutionPolicy to RemoteSigned
Start new PowerShell session
Run 'Get-ExecutionPolicy -List'

Expected behavior
-----------------
ExecutionPolicy UserPolicy set to RemoteSigned

Actual behavior
---------------
ExecutionPolicy UserPolicy set to Undefined

**Comment by daxian-dbw** [comment] 2018-01-22 20:54
I verified the reproduce steps and the issue seems to be fixed:
```
PS:4> Get-Item HKCU:\Software\Policies\Microsoft\PowerShellCore

    Hive: HKEY_CURRENT_USER\Software\Policies\Microsoft

Name                           Property
----                           --------
PowerShellCore                 EnableScripts   : 1
                               ExecutionPolicy : RemoteSigned

PS:5> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy    RemoteSigned
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
```
Given that, I'm closing this issue. @PaulHigin Feel free to re-open this issue if you think it's not fixed.

**Closed by daxian-dbw** 2018-01-22 20:54 UTC
Labels: Area-Engine

**Comment by PaulHigin** [comment] 2018-01-22 21:06
@daxian-dbw   Why do we assume this is fixed?  Please provide a link to the PR that fixed it.

**Comment by daxian-dbw** [comment] 2018-01-22 21:20
Here is the PR: #5791 The group policy cache was redesigned in that PR.

**Comment by PaulHigin** [comment] 2018-01-22 22:20
Thanks.  Agreed that this is no longer an issue.
