### ISSUE TITLE
`Get-Help Clear-Host -Online` gives broken link

### ISSUE THREAD

**Issue by YogurtTheHorse** [PowerShell/PowerShell#7795] opened 2018-09-16 09:45 UTC
Steps to reproduce
------------------

```powershell
get-help clear-host -Online
```

Expected behavior
-----------------

Should give proper links for help 

Actual behavior
---------------
Gives https://go.microsoft.com/fwlink/?LinkID=225747, which produces 404

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Running on Elementary Loki

**Comment by yegorf1** [comment] 2018-09-18 12:29
I just found, that any Get-Help output produces broken links :( 
So `Get-Help Get-Process -Online` opens go.microsoft.com/fwlink/?linkid=821590

**Comment by doctordns** [comment] 2018-09-21 13:40
Both Get-Help Clear-Host and Get-Help Clear-Host -Detailed both work here.

What does NOT work is using -Online.

Using -Online fails with a 404 error. It has been reported. But it's still broken. 

I think the PowerShell team area aware - but I'll tag Joey just in case!

@joeyaiello

**Comment by yegorf1** [comment] 2018-09-21 13:44
Yeah. Problem in `-Online`. Edited, so it will be clear

**Comment by doctordns** [comment] 2018-09-21 13:50
Thanks for the update. 

The -ONLINE issue is known about. It seems to affect ANY call to Get-Help that uses -online.

**Comment by yegorf1** [comment] 2018-09-21 14:01
Yeah. Seems like that. So, is that duplicate?

пт, 21 вер. 2018, 16:51 користувач Thomas Lee <notifications@github.com>
пише:

**Comment by doctordns** [comment] 2018-09-21 15:29
Interestingly - this bug does NOT exist in PowerShell v6.

**Comment by MaximoTrinidad** [comment] 2018-09-21 17:06
This is a known issue and seems it will take some time to fix as they are doing some updates.
Makes Microsoft Online Docs Great Again!!

Patience Is Golden!!

**Comment by doctordns** [comment] 2018-09-21 18:33
I agree, but only up to a point. That it works in 6.1 but fails in 5.1 is curious.

A blog post on the PowerShell blog might help.

**Comment by yegorf1** [comment] 2018-09-21 18:38
But I use 6.1 and bug exists in my configuration

**Comment by MaximoTrinidad** [comment] 2018-09-21 18:39
Hi @doctordns (Thomas)

Yeah! You're right.  But, they are handling it. 
:)

**Comment by KalleOlaviNiemitalo** [comment] 2020-06-07 08:52
`Get-Help Clear-Host -Online` in PowerShell 7.1.0-preview.3 opens <https://go.microsoft.com/fwlink/?LinkID=2096480>, which correctly redirects to <https://docs.microsoft.com/powershell/module/Microsoft.PowerShell.Core/Clear-Host?view=powershell-7>. It was fixed in <https://github.com/PowerShell/PowerShell/pull/11071>.

However, `Get-Help prompt -Online` in PowerShell 7.1.0-preview.3 opens <https://go.microsoft.com/fwlink/?LinkID=225750>, which uselessly redirects to <https://www.microsoft.com?ref=go>. That should redirect to <https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7>, instead.

I don't know whether the online links have been fixed for PowerShell Core 6.2, which is still [supported until September 2020](https://docs.microsoft.com/powershell/scripting/powershell-support-lifecycle?view=powershell-6#powershell-releases-end-of-life).

**Comment by yecril71pl** [comment] 2020-07-15 09:11
Duplicate of https://github.com/MicrosoftDocs/PowerShell-Docs/issues/2939#issuecomment-657233237

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-15 09:21
> Duplicate of [MicrosoftDocs/PowerShell-Docs#2939 (comment)](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/2939#issuecomment-657233237)

No, that comment says "there is no HelpURI for about topics." For `Get-Help prompt -Online`, there actually is a HelpURI, but it redirects to the wrong page:

```
PS Temp:\> (Get-Command prompt).HelpUri
https://go.microsoft.com/fwlink/?LinkID=225750
```

It is defined here: <https://github.com/PowerShell/PowerShell/blob/dd73c303a86ee04afca54a2be949c18299f2d8ed/src/System.Management.Automation/engine/InitialSessionState.cs#L4766-L4771>

**Comment by yecril71pl** [comment] 2020-07-15 09:38
> However, `Get-Help prompt -Online` in PowerShell 7.1.0-preview.3 opens https://go.microsoft.com/fwlink/?LinkID=225750, which uselessly redirects to https://www.microsoft.com?ref=go. That should redirect to https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7, instead.

I do not think it should, as `HELP PROMPT` does not.

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-15 11:35
> I do not think it should, as `HELP PROMPT` does not.

Do you mean that, because `HELP PROMPT` does not show the same offline help as `HELP about_prompts`, they should not have the same online help URI? If that is what you mean, I agree.

**Comment by yecril71pl** [comment] 2020-07-24 21:12
Neither does `HELP CONFIGURATION -O`.  I do not have local help for the module.

**Comment by ThomasNieto** [comment] 2020-10-15 15:34
`Get-Help Clear-Host -Online` works on 7.1 rc1.

**Comment by vexx32** [comment] 2020-10-15 15:39
Marked as fixed for now. If there are other issues around help, please open separate issues for those cases. Thanks!

**Comment by rjmholt** [comment] 2020-11-17 17:52
Reopening, due to the reversion of https://github.com/PowerShell/PowerShell/pull/13176 in https://github.com/PowerShell/PowerShell/pull/14107

**Comment by rjmholt** [comment] 2020-11-19 19:13
Whoops, didn't realise the bot would do that

**Closed** 2023-11-23 12:52 UTC
Labels: Issue-Bug, WG-Interactive-HelpSystem, Resolution-No Activity
