### ISSUE TITLE
Mangled CLIXML printed when running Pester in nested shell

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#7699] opened 2018-09-03 23:02 UTC
I am running Pester in CI in a nested PowerShell. The log output is mangled CLIXML: https://travis-ci.org/felixfbecker/PSKubectl/jobs/424110720#L1227

Here is the script that runs the tests: https://github.com/felixfbecker/PSKubectl/blob/d66a7783d9fc598c87295b281bc86dedac12f487/ci/Invoke-Tests.ps1#L19

But when running that same snippet
```powershell
pwsh-preview -Command {
            # Point all commands to the kubectl proxy
            $PSBoundParameters['*-Kube*:ApiEndPoint'] = 'http://127.0.0.1:8001'
            # Import instrumented assemblies
            Import-Module ../PSKubectl/PSKubectl.psd1
            Invoke-Pester ../Tests
        }
```
locally, the output is correct.

Both locally on macOS and in CI on Linux I'm using latest `pwsh-preview` (6.1.0-rc.1).

Local `PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Any idea what's going on here?

**Comment by MartinSGill** [comment] 2018-09-06 14:45
Possible duplicate of https://github.com/PowerShell/PowerShell/issues/5912

**Comment by iSazonov** [comment] 2021-01-15 06:10
Is the issue present in latest 7.1 build?

**Closed** 2023-11-23 12:53 UTC
Labels: Issue-Question, Resolution-No Activity
