### ISSUE TITLE
Update-Help failing for some modules

### ISSUE THREAD

**Issue by KaeLL** [PowerShell/PowerShell#17577] opened 2022-06-24 18:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Title

### Expected behavior

```console
No error.
```

### Actual behavior

```console
Below
```

### Error details

```console
> Get-Error

Exception             :
    Type    : System.Exception
    Message : Failed to update Help for the module(s) 'ConfigDefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, PSReadline, StartLayout, Whea, WindowsSearch, WindowsUpdate' with UI
culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
              English-US help content is available and can be installed using: Update-Help -UICulture en-US.
    HResult : -2146233088
CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
InvocationInfo        :
    MyCommand        : Update-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Update-Help -UICulture en-US
    PositionMessage  : At line:1 char:1
                       + Update-Help -UICulture en-US
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Update-Help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment] 2022-06-27 17:33
I can verify that I get the same error when updating help with 7.2.5.

**Comment by sdwheeler** [comment] 2022-06-28 18:13
The error is expected for those modules. The modules owners must fix the modules. The only module that there is a workaround for is PSReadline. The workaround is documented:

- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/
- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

This other thing to try for PSReadline is to unload the module, then reload it with the properly-cased name. Then update the help.

```powershell
Remove-Module PSReadline
Import-Module PSReadLine
Update-Help PSReadLine -Force
```

**Comment by rkeithhill** [comment] 2022-07-07 18:30
@sdwheeler Thanks.  The first blog post fixed it for me.  It appears that the one remaining PSRL still named `PSReadline` was in my `Windows PowerShell` Modules folder. 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/5177512/177843955-6e74fba4-4fe3-4f7a-b147-6df850b9a5ba.png">

Once I renamed that folder to `PSReadLine`, `Update-Help PSReadLine -Force` worked just fine from pwsh.

**Comment by kilasuit** [comment] 2022-07-08 22:00
This seems to be a duplicate of #17067

**Closed** 2022-07-09 23:01 UTC
Labels: Resolution-Duplicate, WG-Interactive-HelpSystem

**Comment by sdwheeler** [comment] 2023-12-11 21:11
Adding a summary of answers for this issue is being before closing out comments.

The workaround for the **PSReadline** module is documented in the following blog post:

- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/

This other thing to try is to unload the module, then reload it with the properly-cased name. Then update the help.

```powershell
Remove-Module PSReadline
Import-Module PSReadLine
Update-Help PSReadLine -Force
```

The error is expected for the following Windows modules. 

- ConfigDefenderPerformance
- Dism
- Get-NetView
- Kds
- NetQos
- PcsvDevice
- PKI
- StartLayout
- Whea
- WindowsSearch
- WindowsUpdate

The Windows modules are not maintained by the PowerShell team. To prevent the error, the module owners on the Windows team must fix the modules. For modules that ship in Windows, open a support case with Windows Support or send feedback via the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
