### ISSUE TITLE
Powershell doesn't support F11

### ISSUE THREAD

**Issue by sochka** [PowerShell/PowerShell#4028] opened 2017-06-16 03:53 UTC
Powershell doesn't support F11 for full-screen, supports only Alt+Enter. Cmd.exe supports both F11 and Alt+Enter. 

Steps to reproduce
------------------

```powershell
Press f11
```

Expected behavior
-----------------

```none
Console goes fullscreen
```

Actual behavior
---------------
```none
Nothing happens
```

**Comment by SteveL-MSFT** [comment] 2017-06-16 04:29
It appears that PSReadline is intercepting F11.  If you `rmo psreadline`, F11 will switch between full screen mode.

**Comment by lzybkr** [comment] 2017-06-16 19:58
Duplicate of https://github.com/lzybkr/PSReadLine/issues/280

**Closed by lzybkr** 2017-06-16 19:58 UTC
Labels: Area-PSReadLine

**Comment by mklement0** [comment] 2018-11-24 02:46
For a workaround, see https://github.com/lzybkr/PSReadLine/issues/280#issuecomment-441338880.
