### ISSUE TITLE
System.Net.WebClient.Proxy.GetProxy fails after bad/relative URI

### ISSUE THREAD

**Issue by MysticRyuujin** [PowerShell/PowerShell#3040] opened 2017-01-24 20:32 UTC
Steps to reproduce
------------------
(new-object System.Net.WebClient).Proxy.GetProxy("http://www.msn.com").Host
(new-object System.Net.WebClient).Proxy.GetProxy("www.msn.com").Host
(new-object System.Net.WebClient).Proxy.GetProxy("http://www.msn.com").Host

Expected behavior
-----------------
1. Output of Proxy Server Hostname
2. Error: "This operation is not supported for a relative URI."
3. Output of Proxy Server Hostname

Actual behavior
---------------
1. Output of Proxy Server Hostname
2. Error: "This operation is not supported for a relative URI."
3. "www.msn.com"

This output of the URI continues until I close/reopen PowerShell

Environment data
----------------
$PSVersionTable:
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

$StackTrace:
PS H:\> $StackTrace
   at System.Uri.get_IsLoopback()
   at System.Net.WebProxy.IsBypassedManual(Uri host)
   at System.Net.WebProxy.GetProxy(Uri destination)
   at CallSite.Target(Closure , CallSite , Object , String )

**Comment by MysticRyuujin** [comment] 2017-01-24 20:56
I did a little more digging, this issue only happens when I am using a PAC file from an automatic configuration script. If I manually assign a proxy server, the command behaves as expected, but with an automatic configuration script being used it behaves as posted.

**Comment by SteveL-MSFT** [comment] 2017-01-24 22:15
Isn't this an issue with the WebClient class and not PowerShell?  Do you get expected behavior with just C#?

**Comment by MysticRyuujin** [comment] 2017-01-25 14:39
Here is why I think this is a PowerShell issue:

I'm using New-Object to instance a new System.Net.WebClient each time I run the command, the failure of the second command should have no impact on a New-Object

Second, the following code works:
$Source = @'
using System;
using System.Net;

public class ProxyTest
{
   public static void Main()
   {
      using (WebClient client = new WebClient())
        {
            Uri myUri = new Uri("http://www.google.com");
            var proxy = client.Proxy.GetProxy(myUri);
            Console.WriteLine(proxy.ToString());
            try
            {
                myUri = new Uri("www.google.com");
                proxy = client.Proxy.GetProxy(myUri);
                Console.WriteLine(proxy.ToString());
            }
            catch
            {
                Console.WriteLine("Expected Failure");
            }
            myUri = new Uri("http://www.google.com");
            proxy = client.Proxy.GetProxy(myUri);
            Console.WriteLine(proxy.ToString());
        }
   }
}
'@
Add-Type -TypeDefinition $Source -Language CSharp
[ProxyTest]::Main()
CORRECT PROXY
Expected Failure
CORRECT PROXY

**Comment by iSazonov** [comment] 2017-01-25 16:11
It is seems the key here is `using (WebClient client = new WebClient())`

**Comment by MysticRyuujin** [comment] 2017-01-25 17:28
@iSazonov forgive me if I don't fully understand, I'm certainly not an expert nor a professional programmer...

I don't understand why using what seems to me as a fully disposable command has any impact on additional usage of that command?

(New-Object System.Net.WebClient).Proxy.GetProxy()

I'm not storing it as a variable or making any calls back to it and each time it's run I'm specifically creating a New-Object am I not?

I simply do not know enough to reproduce the issue in C# accurately / exactly the same as the supplied PowerShell would generate.

**Comment by iSazonov** [comment] 2017-01-25 17:51
I am not an expert too. 
I only suggested an experiment with replacing `using (WebClient client = new WebClient())` in `WebClient client = new WebClient()`

**Comment by MysticRyuujin** [comment] 2017-01-25 17:56
Works as expected

```
$Source = @'
using System;
using System.Net;

public class ProxyTest
{
   public static void Main()
   {
        WebClient client = new WebClient();
        Uri myUri = new Uri("http://www.google.com");
        var proxy = client.Proxy.GetProxy(myUri);
        Console.WriteLine(proxy.ToString());
        try
        {
           myUri = new Uri("www.google.com");
           proxy = client.Proxy.GetProxy(myUri);
           Console.WriteLine(proxy.ToString());
        }
        catch
        {
            Console.WriteLine("Expected Failure");
        }
        myUri = new Uri("http://www.google.com");
        proxy = client.Proxy.GetProxy(myUri);
        Console.WriteLine(proxy.ToString());
   }
}
'@
```
Also works as expected:
```
$Source = @'
using System;
using System.Net;

public class ProxyTest
{
   public static void Main()
   {
        WebClient client1 = new WebClient();
        Uri myUri = new Uri("http://www.google.com");
        var proxy = client1.Proxy.GetProxy(myUri);
        Console.WriteLine(proxy.ToString());
        try
        {
           WebClient client2 = new WebClient();
           myUri = new Uri("www.google.com");
           proxy = client2.Proxy.GetProxy(myUri);
           Console.WriteLine(proxy.ToString());
        }
        catch
        {
            Console.WriteLine("Expected Failure");
        }
        WebClient client3 = new WebClient();
        myUri = new Uri("http://www.google.com");
        proxy = client3.Proxy.GetProxy(myUri);
        Console.WriteLine(proxy.ToString());
   }
}
'@
```

I think maybe that last one is a little more "what I think should be happening" based on my understanding of my use of New-Object

**Comment by MysticRyuujin** [comment] 2017-01-25 18:05
Adding a Try {} Catch {} to the second command does not change the PowerShell behavior either, it still just prints "www.msn.com":
Try { (new-object System.Net.WebClient).Proxy.GetProxy("www.msn.com").Host } Catch {}

**Comment by SteveL-MSFT** [comment] 2017-01-27 00:46
I'm not able to repro the original issue making it difficult to investigate further.  I created a simple pac file:

```
function FindProxyForURL(url, host) {

if ( url == "www.google.com" ) {
         return "PROXY 10.10.10.10";
}
else {
        return  "DIRECT";
}

}
```

Chrome, Edge, and IE all observe the Internet Options settings when I set that pac as the auto configure file and behaves as I expect: failing on www.google.com, working for everything else.

When using the WebClient class, it doesn't appear to use my pac at all.

**Comment by MysticRyuujin** [comment] 2017-01-27 23:27
@SteveL-MSFT I recreated your issue, I think...I'm not sure how you configured your stuff but here's what I found:

#1. I altered your "url ==" to "host =="
`if ( host == "www.google.com" ) {`

#2. When I used a local file as in _file://c:\temp\test.pac_ both IE and WebClient ignored it. Apparently that's depreciated but Chrome still accepted it. I had to actually host it on an http:// site. Once I did both of those things the WebClient started using it...not sure how you setup your pac file...

**Comment by MysticRyuujin** [comment] 2017-02-26 15:26
Are there any guides out there for how one might debug an issue like this?

**Comment by iSazonov** [comment] 2017-02-26 17:18
The original test recreate `WebClient` object. Then the problem is not in it. The object has `Proxy` property to be initialized by static method [WebRequest.DefaultWebProxy](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebClient/src/System/Net/WebClient.cs#L202) This may be the place where the problem is. Next hop is [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/WebRequest.cs#L567) Next hop is [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/SystemWebProxy.cs#L32)
Perhaps the exception in the second test, somehow "destroys" this static property or "overlaps" it.

@daxian-dbw Could you comment on this issue and  specify the right direction to fix?

**Comment by daxian-dbw** [comment] 2017-02-28 07:39
This is, in fact, a CoreCLR issue (not sure if it's by design, though).
The key factor in play is how `String` is converted to `Uri` in powershell. powershell uses `Uri(<uri-string>, UriKind.RelativeOrAbsolute)`, which is the same as used in `System.UriTypeConverter.ConvertFromString(String)`.

Therefore, the pure C# equivalent should be like this:
```
void Main()
{
	System.Net.WebClient client = new System.Net.WebClient();
	Uri uri_absolute = new Uri("http://www.msn.com", System.UriKind.RelativeOrAbsolute);
	Uri uri_relative = new Uri("www.msn.com", System.UriKind.RelativeOrAbsolute);
	
	Console.WriteLine(client.Proxy.GetProxy(uri_absolute).Host);
	
	try { client.Proxy.GetProxy(uri_relative); }
	catch { Console.WriteLine("Exception"); }
	
	Console.WriteLine(client.Proxy.GetProxy(uri_absolute).Host);
}
```
And the output is:
```
10.10.10.10
Exception
www.msn.com
```

**Comment by iSazonov** [comment] 2017-02-28 12:48
@daxian-dbw Many thanks for C# reproduction!

@MysticRyuujin  Could you open Issue in CoreCLR?

**Comment by daxian-dbw** [comment] 2017-02-28 17:13
@MysticRyuujin I'm afraid this is not a CoreCLR/.NET Core bug as the type `System.Net.WebClient` is not even available in .NET Core. But please do try them to see if they can redirect you to the right channel to report this issue.

I'm closing this issue as `Resolution-external`.

**Closed by daxian-dbw** 2017-02-28 17:13 UTC
Labels: Issue-Discussion, Resolution-External
