### ISSUE TITLE
Copy-Item does not retain Hidden attribute

### ISSUE THREAD

**Issue by Joe-Zer0** [PowerShell/PowerShell#13552] opened 2020-08-31 19:54 UTC
Copied items do not retain their attributes.

## Steps to reproduce

```powershell
md temp1
md temp2
cd .\temp1\
git init
(Get-Item .\.git\ -Force).Attributes
# Output:  Hidden, Directory
Copy-Item * ..\temp2\ -Recurse -Force
cd ..\temp2\
(Get-Item .\.git\ -Force).Attributes
# Output:  Directory
```

## Expected behavior

```none
The .git folder should still have the Hidden attribute after it is copied.
```

## Actual behavior

```none
The .git folder no longer has the Hidden attribute.
```

## Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2020-09-01 05:25
@Joe-Zer0 Can you reproduce with latest PowerShell 7.1 Preview build?

**Comment by Joe-Zer0** [comment] 2020-09-01 13:05
@iSazonov 
I tested this with docker image mcr.microsoft.com/powershell:7.1.0-preview.6-nanoserver-1903.
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.6
PSEdition                      Core
GitCommitId                    7.1.0-preview.6
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

It didn't have git, so my steps are slightly different.  But you can see that Copy-Item is still not copying the Hidden attribute.
```
PS C:\temp\temp1> md HiddenFolder

    Directory: C:\temp\temp1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            9/1/2020  8:00 AM                HiddenFolder

PS C:\temp\temp1> (Get-Item .\HiddenFolder\).Attributes += 'Hidden'
PS C:\temp\temp1> gci
PS C:\temp\temp1> gci -fo

    Directory: C:\temp\temp1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d--h-            9/1/2020  8:00 AM                HiddenFolder

PS C:\temp\temp1> cp * ..\temp2\ -r -fo
PS C:\temp\temp1> cd ..\temp2\
PS C:\temp\temp2> gci -fo

    Directory: C:\temp\temp2

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            9/1/2020  8:01 AM                HiddenFolder
```

**Comment by iSazonov** [comment] 2020-09-02 04:46
After reviewing FileSystem provider code I see that we do manual enumeration and always care about file metadata/attributes but never about directory metadata/attributes. 

_Also we should fix three code paths - local session, SessionFrom and SessionTo:_
https://github.com/PowerShell/PowerShell/blob/152456d7a0b0185a73731aff92c01f699641a350/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3649-L3669

Compare CopyFileInfoItem() and CopyDirectoryInfoItem() for local session:
    for file we use FIleInfo:
https://github.com/PowerShell/PowerShell/blob/152456d7a0b0185a73731aff92c01f699641a350/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3976-L3982

    for directory we use a path not DirectoryInfo:
https://github.com/PowerShell/PowerShell/blob/152456d7a0b0185a73731aff92c01f699641a350/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3826-L3831
https://github.com/PowerShell/PowerShell/blob/152456d7a0b0185a73731aff92c01f699641a350/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L2810

For the fix we should create tests for local session scenario and manually test for both remote scenarios.

**Comment by Joe-Zer0** [comment] 2020-09-02 06:30
@iSazonov Thank you very much for your help!

**Comment by Joe-Zer0** [comment] 2020-09-11 18:03
I believe I have a fix for this issue.  What branch should I create the pull request on?

**Comment by vexx32** [comment] 2020-09-11 18:21
Target the master branch for pull requests. 🙂

**Comment by PaulHigin** [comment] 2020-09-28 17:40
Actually, I am a bit concerned that this could be a breaking change.  This is new behavior, and if attributes are transferred automatically, are there scenarios where that can fail?  My concern is that existing scripts may break.  Would it be better to make this new behavior opt-in with a parameter switch?

I'll mark this for committee review.

/cc @anmenaga

**Comment by SteveL-MSFT** [comment] 2020-09-30 23:11
@PowerShell/powershell-committee reviewed this.  While exploring behaviors in cmd.exe with xcopy and bash with /bin/cp, we recognize that the default behavior is different between Windows and Linux/macOS.  Also recognize that there is a discrepancy in the current behavior where file attributes are copied, but directory attributes are not on all platforms.  Also, have dynamic parameters `-IncludeAttributes` and `-ExcludeAttributes` in the FileSystemProvider for Copy-Item so that users can get explicit behavior on all platforms.

Because we have some concerns about application compatibility, although likely a bucket 3 breaking change, we request that any change is done as an Experimental Feature.

**Comment by iSazonov** [comment] 2020-10-01 03:48
It is not clear - today we copy only file attributes:
- will preserve current behavior without these new parameters?
- with IncludeAttributes will we copy both file and directory attributes?
- with ExcludeAttributes  will we exclude all file and directory attributes?

_It seems we get a complex behavior and it can confuse users._ I'd prefer more simple UX.

Since file attributes are coped by default should new parameter be -IncludeDirectoryAttributes? And what about with Exclude in the case? Have -ExcludeFileAttributes only or -ExcludeDirectoryAttributes too?

---

I tested with Far Manager - it copies directory attributes by default.
If this feature is present and gone then it will definitely be a bucket 3 breaking change. 
But if this feature is not present, and it will be added, then this is definitely not a breaking change. (Those to whom it is important use a workaround today. Those who don't care ignore it at all.)

My proposal is:
- add the feature (copy directory attributes) by default (as experimental feature)
- add backward compatibility switch ExcludeDirectoryAttributes

We have about 1 year for getting feedbacks and adoption.

**Comment by SteveL-MSFT** [comment] 2020-12-16 23:31
@PowerShell/powershell-committee reviewed this again, we agree on an experimental feature that copies the directory attributes.  In addition, not having any `-ExcludeDirectoryAttributes` switch initially unless customer feedback makes it clear this is needed.  In the case of someone copying a ReadOnly directory and subsequently trying to write to it because it worked previously they would get a clear error message and should update their script to modify the directory attribute explicitly.

**Closed** 2023-11-23 11:26 UTC
Labels: Issue-Enhancement, Up-for-Grabs, Committee-Reviewed, WG-Cmdlets-Management, Area-FileSystem-Provider, Resolution-No Activity
