### ISSUE TITLE
Out-File and carriage returns

### ISSUE THREAD

**Issue by 89z** [PowerShell/PowerShell#15301] opened 2021-04-24 15:40 UTC
If I have a program, for example this Go program:

~~~go
package main
import "fmt"

func main() {
   fmt.Print("North East\n")
   fmt.Print("South West\n")
}
~~~

This program produces no carriage returns at all, only newlines. However if I do this:

~~~
prog.exe > prog.txt
~~~

PowerShell takes it upon itself to add carriage returns to every line. I only want PowerShell to faithfully output what my program created, nothing more. So I tried this instead:

~~~
prog.exe | Out-File -NoNewline prog.txt
~~~

and PowerShell didnt add carriage returns, but it went ahead and removed the newlines too. How do I do what I am trying to do?

**Comment by 89z** [comment] 2021-04-24 19:13
As a workaround, this seems to have correct result:

~~~
start -rso prog.txt prog.exe
~~~

**Comment by 89z** [comment] 2021-04-24 20:10
I just noticed, that the pipe operator `|` also injects carriage returns. So if you do something like this:

~~~
west.exe | east.exe
~~~

If `west.exe` only emits newlines, PowerShell injects carriage returns into the pipe, so `east.exe` might fail if it is not expecting carriage returns, or if it is expecting binary data.

**Comment by daxian-dbw** [comment] 2021-05-03 22:27
Right, the pipeline in PowerShell today doesn't transfer stream between native executables, and neither does the redirection for a native executable.

**Comment by 89z** [comment] 2021-11-03 03:18
I would ask that you please keep this closed, unless someone is interested to fix it

**Comment by daxian-dbw** [comment] 2021-11-03 16:45
Close this one as a duplicate of #1908

**Closed by daxian-dbw** 2021-11-03 16:45 UTC
Labels: Issue-Bug, WG-Engine

**Comment by 89z** [comment] 2022-03-23 00:58
Since Microsoft doesnt seem interested in fixing this, I found another option. NuShell pipes the commands without adding anything:

~~~
D:\Desktop\etc〉.\west.exe | .\east.exe                  
"hello world"
~~~

Compare with PowerShell, which adds carriage return:

~~~
PS D:\Desktop\etc> .\west.exe | .\east.exe
"hello world\r\n"
~~~

So I am uninstalling PowerShell, and use NuShell from now on.
