### ISSUE TITLE
 The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception

### ISSUE THREAD

**Issue by Safirion** [PowerShell/PowerShell#13653] opened 2020-09-18 08:35 UTC
Hi, it's maybe a bug of .Net 5. 

## Steps to reproduce

Open a runspacepool in a .Net5 Web Api published as a single file.

## Expected behavior

The runspace pool is open and works fine like before (before the update of .Net or powershell package)

## Actual behavior

```
System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at System.Management.Automation.PSVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSVersionInfo.get_SerializationVersion()
   at System.Management.Automation.Remoting.RemoteSessionCapability..ctor(RemotingDestination remotingDestination)
   at System.Management.Automation.Remoting.RemoteSessionCapability.CreateClientCapability()
   at System.Management.Automation.Remoting.ClientRemoteSessionImpl..ctor(RemoteRunspacePoolInternal rsPool, URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreateClientRemoteSession(RemoteRunspacePoolInternal rsPoolInternal)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler..ctor(RemoteRunspacePoolInternal clientRunspacePool, TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreateDSHandler(TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspacePool..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable, PSPrimitiveDictionary applicationArguments)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo, PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo)
   at System.Management.Automation.Remoting.RemoteSessionCapability.CreateClientCapability()
   at System.Management.Automation.Remoting.ClientRemoteSessionImpl..ctor(RemoteRunspacePoolInternal rsPool, URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreateClientRemoteSession(RemoteRunspacePoolInternal rsPoolInternal)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler..ctor(RemoteRunspacePoolInternal clientRunspacePool, TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreateDSHandler(TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspacePool..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable, PSPrimitiveDictionary applicationArguments)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspacePool(Int32 minRunspaces, Int32 maxRunspaces, RunspaceConnectionInfo connectionInfo, PSHost host)
   at Perseus.API.Helpers.PowerShell.PowerShellHelper.VerifyRunspacePool(RunspacePool rp, Func`1 creator, Boolean retry)
   at Perseus.API.Helpers.PowerShell.PowerShellHelper.VerifyRunspacePool(RunspacePool rp, Func`1 creator, Boolean retry)
   at Perseus.API.Helpers.PowerShell.PowerShellHelper.VerifyRunspacePool(RunspacePool rp, Func`1 creator, Boolean retry)
   at Perseus.API.Services.RDS.RDSService.GetRunspacePool(RDSPlatformEnum platform)
   at Perseus.API.Services.HostedExchange.HostedExchangeService.GetRunspacePool(ExchangeVersionEnum version)
   at Perseus.API.Services.RDS.RapsManager.UpdateRaps()
   at Perseus.API.Services.HostedExchange.Mailbox.MailboxDatabasesManager.UpdateServersCache()
   at Perseus.API.Services.RDS.RapsManager.GetCache(Boolean forceRefresh)
   at Perseus.API.Services.RDS.RapsManager.RefreshRapsRoles()
   at Perseus.API.Services.HostedExchange.Mailbox.MailboxDatabasesManager.GetCache(Boolean forceRefresh)
   at Perseus.API.Services.HostedExchange.Mailbox.MailboxDatabasesManager.RefreshDatabaseEval()
```

## Environment data

System.Management.Automation Version 7.1.0 Preview 7
.Net 5 RC-1

## Workaround

If I publish the Web API to IIS without single file generation, it's work fine.

**Comment by SeeminglyScience** [comment] 2020-09-18 12:39
Duplicate of #13540

**Closed** 2020-09-18 17:46 UTC
Labels: Issue-Question, Resolution-Duplicate
