### ISSUE TITLE
Get-WinUserLanguageList does not work

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#15898] opened 2021-08-09 22:25 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Get-WinUserLanguageList` does not work

### Expected behavior

```console
output languages
```

### Actual behavior

```console
Get-WinUserLanguageList
Get-WinUserLanguageList: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SeeminglyScience** [comment] 2021-08-09 22:51
Duplicate of #14473.  Currently tracked in issue PowerShell/PowerShellModuleCoverage#18

**Closed** 2021-08-10 03:59 UTC
Labels: Resolution-Duplicate, Resolution-External

**Comment by ajkessel** [comment] 2024-07-25 13:23
Was there any resolution to this? I can't get Get-WinUserLanguageList to work on PS7.4.4. There seem to be a number of issues on this bug that are all closed, and I don't see any place to report/track it. 
```
Get-WinUserLanguageList: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
```
The workaround of importing the international module first allows Get-WinUserLanguageList to work, but then Set-WinUserLanguageList fails with:
```
Set-WinUserLanguageList: Cannot bind parameter 'LanguageList'. Cannot convert the "Microsoft.InternationalSettings.Commands.WinUserLanguage" value of type "Deserialized.Microsoft.InternationalSettings.Commands.WinUserLanguage" to type "Microsoft.InternationalSettings.Commands.WinUserLanguage".
```
