### ISSUE TITLE
Get-Command -Syntax should work with aliases

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#5963] opened 2018-01-19 22:09 UTC
Steps to reproduce
------------------

```powershell
Get-Command -Syntax del
```

Expected behavior
-----------------

```none
del [-Path] <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Recurse] [-Force] [-Crede
ntial <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Stream <string[]>] [<CommonParameters>]                   
                                                                                                                         
del -LiteralPath <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Recurse] [-Force] [-
Credential <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Stream <string[]>] [<CommonParameters>]  
```

Actual behavior
---------------

```none
Remove-Item
```

**Comment by KirkMunro** [comment] 2019-04-10 20:37
I just came here to log this. The existing behavior is most unhelpful.

One thought I have that differs from the above however is in the case of `Get-Command -Syntax $someAliasName`, I was thinking I'd prefer it show the actual alias mapping, followed by the syntax for the alias, especially since aliases shouldn't be used in scripts. The thinking behind this is that 100% of the time when I would use `gcm del -syntax` (or any alias in place of `del`), I'd be using the alias to save typing, as a shorthand to get the actual syntax for the command that will be invoked, and less as a command I actually want to invoke. So my expected behavior would look more like this:

```none
del -> Remove-Item

del [-Path] <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Recurse] [-Force] [-Crede
ntial <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Stream <string[]>] [<CommonParameters>]                   
                                                                                                                         
del -LiteralPath <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Recurse] [-Force] [-
Credential <pscredential>] [-WhatIf] [-Confirm] [-UseTransaction] [-Stream <string[]>] [<CommonParameters>]  
```

Or maybe the output should actually state "NOTE: del is an alias for the Remove-Item command", at the top or bottom of the output.

**Comment by TylerLeonhardt** [comment] 2019-09-17 21:23
@Steve_MSFT potentially a solid hackathon/up-for-grabs issue?

**Comment by KirkMunro** [comment] 2019-09-17 22:40
@TylerLeonhardt A great Hacktoberfest issue.

**Comment by ChrisLGardner** [comment] 2019-10-09 20:45
Sounds like an interesting challenge so I'll give it a shot

**Comment by kvprasoon** [comment] 2020-10-28 19:51
This can be closed @iSazonov / @ChrisLGardner :-)

**Closed** 2020-10-28 22:45 UTC
Labels: Area-Cmdlets-Core, Hacktoberfest, Issue-Enhancement, Resolution-Fixed
