### ISSUE TITLE
New-Module produces verbose output despite -Verbose:$False in caller scope

### ISSUE THREAD

**Issue by EliteLoser** [PowerShell/PowerShell#5325] opened 2017-11-03 07:59 UTC
Steps to reproduce
------------------

It can be reproduced by doing this: https://github.com/pester/Pester/issues/921

Can I get by with that...? You guys probably love Pester and have it or are willing to install it. Motivation is lacking to do it properly at the moment. I'm tired. Sorry.

```powershell
Hi
```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                          
----                           -----                                                                                          
PSVersion                      5.1.15063.674                                                                                  
PSEdition                      Desktop                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                        
BuildVersion                   10.0.15063.674                                                                                 
CLRVersion                     4.0.30319.42000                                                                                
WSManStackVersion              3.0                                                                                            
PSRemotingProtocolVersion      2.3                                                                                            
SerializationVersion           1.1.0.1                                                                                        

```

**Comment by mklement0** [comment] 2017-11-05 02:57
Please see https://github.com/pester/Pester/issues/921#issuecomment-341945409

**Comment by SteveL-MSFT** [comment] 2017-11-06 03:41
@mklement0 isn't this a dupe of https://github.com/PowerShell/PowerShell/issues/4568?

**Comment by mklement0** [comment] 2017-11-06 12:11
@SteveL-MSFT: That's what I initially thought as well, but now I believe this to be a (cosmetic) Pester-internal issue, so I think this issue should be closed.

**Closed** 2017-11-06 17:59 UTC
Labels: Issue-Question, Resolution-External
