### ISSUE TITLE
Never truncate when writing output to file

### ISSUE THREAD

**Issue by pedrogarcia** [PowerShell/PowerShell#4172] opened 2017-07-01 18:41 UTC
When writing console output to file with *>>, lines should not be truncated. Currently, output is truncated to 85 characters. This makes Powershell fundamentally unusable for me.

**Comment by pedrogarcia** [comment] 2017-07-01 18:51
Actually, stuff should never be truncated in general. Pretty much every command I run in powershell has things truncated with ...
THere is plenty of space in my screen and in the window, yet, after 15 characters powershell will truncated some stuff. 
Man, how I really hate microsoft tools.

**Comment by iSazonov** [comment] 2017-07-02 16:31
@pedrogarcia Thanks for your report! The Issue is duplicate #1908. 
Currently PowerShell Core format all output based on console width, we want enhance the behavior for pipes with native commands. 
>Man, how I really hate microsoft tools.

PowerShell Core is an open project - feel free to show how need to build systems correctly. Welcome to make the enhancement and fix the Issue!

**Comment by lzybkr** [comment] 2017-07-03 00:41
@iSazonov - I'm reopening because fixing this issue might require different work than #1908, and this issue can be fixed without fixing #1908.

**Comment by daxian-dbw** [comment] 2017-07-05 16:35
@pedrogarcia could you please add a repro?

**Comment by pedrogarcia** [comment] 2017-07-05 17:29
Sure. 
Run a long copying task for rclone, with verbose output flag, for example:
‘
rclone -vv copy “drive:/folder1” “drive:/folder2” *>> cmd_output_log.log
‘

**Comment by SteveL-MSFT** [comment] 2017-10-14 03:52
I see the code in `Out-File` which computes the console width, but I'm not able to repro this.  In fact, the `-width` parameter doesn't even get honored.

```powershell
$text = "0123456789"
while ($text.Length -lt [console]::WindowWidth) { $text += $text }                
$text | Out-File ./test.txt -Encoding ascii
```

Not even able to repro with Windows PS 5.1

**Comment by iSazonov** [comment] 2017-10-14 15:56
@SteveL-MSFT I believe Out-File don't send simple objects to formatting system before output. If you replace string variable in your test with a hash or array you'll get repo.

**Comment by SteveL-MSFT** [comment] 2017-10-14 16:07
@iSazonov but the original repro was a native command outputting to stdout

**Comment by iSazonov** [comment] 2017-10-14 16:38
I wonder. Maybe Out-File detect a file provider in input strings?

**Comment by SteveL-MSFT** [comment] 2017-10-14 17:51
I tried using the native `echo` on Linux as well as `testexe -echoargs` to get long output, but nothing gets truncated.

Objects being truncated during formatting is currently expected (although I'm open to consider changing it...) and `-width` does work in that case.

**Comment by SteveL-MSFT** [comment] 2017-10-14 17:58
Downloaded rclone and was able to repro it

**Comment by SteveL-MSFT** [comment] 2017-10-14 18:11
The easy fix is to not truncate in all cases.  I'm not convinced that having the text log have the same width as the console used during runtime is useful.  The console I'm using to generate the log is probably not the same console I used to read the log.

**Comment by markekraus** [comment] 2017-10-14 18:24
would that also apply to collections of complex objects with lengthy string members? If so, how would that work or look like? I know I'm in the minority opinion on the usefulness of the console width in `Out-File`, but I think completely removing truncating may have some undesirable side effects too.

**Comment by SteveL-MSFT** [comment] 2017-10-14 18:32
@markekraus I would prefer to add a `-TruncateToConsoleWidth` type switch if needed, but I don't think even that is needed.  For objects with lengthy string members that's only a problem if you view the log in the console, in that case, I'd rather have a switch to `Get-Content` to truncate.

**Comment by markekraus** [comment] 2017-10-14 18:59
@SteveL-MSFT I'm just curious what this would look like?

```powershell
$LoremIpsum = "Lorem ipsum dolor sit amet, bibendum cum ornare, integer ultrices, donec augue, ultricies vitae hendrerit vestibulum et sed iaculis, potenti montes libero. "

1..100 |  %{ 
    [PsCustomObject]@{
         Column1 = $LoremIpsum*(1..100 | Get-Random)
         Column2 = $LoremIpsum*(1..100 | Get-Random)
         Column3 = $LoremIpsum*(1..100 | Get-Random)
    }
} | Out-File -FilePath C:\temp\outfile.txt
```

Currently that is a truncated single column, which i agree isn't great. But, how would not truncating this work? Would it be coerced to a list? What id the user wants to retain columns? if so based on what logic? or would it be in un-truncated columns? and if so, how would column width work? would it really need to calculate the max width of each column  and then build the output file? What kind of performance impact would that have? or would columns just be all different widths with no discernible column alignment?

**Comment by iSazonov** [comment] 2017-10-14 20:01
So it is dup 3813 and 1491.
Please see @lzybkr comments in https://github.com/PowerShell/PowerShell/pull/4006 about a fix direction.

**Comment by SteveL-MSFT** [comment] 2017-10-15 01:03
Resolving as dupe of https://github.com/PowerShell/PowerShell/issues/3813, let's carry on with that one.

**Closed** 2017-10-21 21:17 UTC
Labels: Area-Engine, Issue-Enhancement, Resolution-Duplicate

**Comment by fazee6** [comment] 2019-12-25 19:51
Here is the solution of all the truncation issues https://mcsaguru.com/how-to-fix-truncated-powershell-output/. He explain very well why truncation happens and hwo to fix them.

**Comment by martin12333** [comment] 2024-06-01 00:52
> _Here is the solution of all the truncation issues _[_https://mcsaguru.com/how-to-fix-truncated-powershell-output/_](https://mcsaguru.com/how-to-fix-truncated-powershell-output/)_.  .....  

a broken link
