### ISSUE TITLE
Import-CSV Uses Parent Folder After Error

### ISSUE THREAD

**Issue by rgroefer** [PowerShell/PowerShell#11411] opened 2019-12-20 16:19 UTC
### Import-CSV Looks in Parent Directory
After throwing an error using ConvertFrom-String, Import-Csv no longer uses the current directory, but looks in the parent directory instead.  I'll add my code so you may simulate the same thing.  This code throws an error on ConvertFrom-String, which appears to generate the directory issue on the Import-Csv, but not other cmdlets like Get-Item or Get-Content.

$PSVersionTable:                                                                                                    
PSRemotingProtocolVersion - 2.3                                                                                                        
Platform - Win32NT                                                                                                    
PSVersion - 7.0.0-rc.1                                                                                                 
PSCompatibleVersions - {1.0, 2.0, 3.0, 4.0...}                                                                                    
OS -Microsoft Windows 10.0.18362                                                                               
GitCommitId - 7.0.0-rc.1                                                                                                 
WSManStackVersion - 3.0                                                                                                        
PSEdition - Core                                                                                                       
SerializationVersion - 1.1.0.1                                                                                                    

### Steps to Reproduce
Code:
```
$imp = Import-Csv .\TestColumn.csv
$Template = @'
{Type*:IP4Address},{IP:10.20.30.40}
'@
$imp.col2 | ConvertFrom-String -TemplateContent $Template -PropertyNames Type,IP
Import-Csv `.\TestColumn.csv
```
Content in the IP file (fake IPs... of course)
```
gc .\TestColumn.csv
Col1,Col2
One,@{IP4Address=10.20.30.41}
Two,@{IP4Address=10.20.30.42}
Three,@{IP4Address=10.20.30.43}
Four,@{IP4Address=10.20.30.44}
```

**Comment by iSazonov** [comment] 2019-12-20 19:12
> ConvertFrom-String

WinCompat feature is activated and the issue could come from the fact.

/cc @anmenaga @SteveL-MSFT

**Comment by SteveL-MSFT** [comment] 2019-12-21 00:42
@anmenaga Bruce made this change for the WindowsCompat module to track the current directory, may need something similar: https://github.com/PowerShell/WindowsCompatibility/pull/47

**Comment by anmenaga** [comment] 2020-01-14 03:42
This is a duplicate of #11419 
`ConvertFrom-String` causes WinCompat loading of `Microsoft.PowerShell.Utility` module, which also generates `Import-Csv` proxy function which according to #11419 takes precedence over original `Import-Csv`.
```
PS C:\1> Get-Command Import-Csv -All
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Import-Csv                                         7.0.0.0    Microsoft.PowerShell.Utility
Function        Import-Csv                                         1.0        Microsoft.PowerShell.Utility
```

**Workaround 1** - call local `Import-Csv` cmdlet using call operator
```
&(Get-Command -Name Import-Csv -CommandType Cmdlet) .\TestColumn.csv
```
or
```
$ImportCsv = Get-Command -Name Import-Csv -CommandType Cmdlet
&($ImportCsv) .\TestColumn.csv
```

**Workaround 2** - fix `Import-Csv` proxy function to update current dir in remote session whenever local current dir changes
```
$ExecutionContext.InvokeCommand.LocationChangedAction = {$s = Get-PSSession -Name WinPSCompatSession; if ($s) {$newPath = $_.newPath;Invoke-Command $s {Set-Location $using:newPath}}}
cd . # just once; this will sync remote current dir to the current one; subsequent local dir changes will be sync'ed automatically
Import-Csv .\TestColumn.csv # this will call the proxy function, but it supports serialization, so this works fine
```

**Closed** 2020-01-15 05:00 UTC
Labels: Experimental, Issue-Bug, Resolution-Duplicate
