### ISSUE TITLE
Get-ComputerInfo crashes on Windows 7 x64

### ISSUE THREAD

**Issue by SwarfegaGit** [PowerShell/PowerShell#5036] opened 2017-10-06 14:39 UTC
Steps to reproduce
------------------

```
Get-ComputerInfo
```

Expected behavior
-----------------

To not crash?

Actual behavior
---------------

[Imgur](https://i.imgur.com/dOQPSQa.png)

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment] 2017-10-06 15:47
Dupe of https://github.com/PowerShell/PowerShell/issues/2777

**Closed by SteveL-MSFT** 2017-10-06 15:47 UTC
Labels: Resolution-Duplicate
