### ISSUE TITLE
[6.1.0-rc.1] What does PSEdition in the output of Get-Module actually mean?

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#7643] opened 2018-08-27 23:29 UTC
I'm confused with the `PSEdition` column that we get in the output of the `Get-Module` cmdlet.
This is the output in the Cloud Shell, on a Linux box.
What does it mean that some modules have "Desk" and others "Core"?

```
ModuleType Version    Name                                PSEdition
---------- -------    ----                                --------- 
Script     0.8.6      AzurePSDrive                        Desk
Manifest   1.1.0.0    Microsoft.PowerShell.Archive        Desk 
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core 
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core 
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core 
Script     1.1.7.0    PackageManagement                   Desk 
Script     1.6.0      PowerShellGet                       Desk
Script     0.8.9      PSCloudShellUtility                 Desk 
Script     0.0        PSDesiredStateConfiguration         Desk
Script     2.0.0      PSReadLine                          Desk
Binary     1.1.1      ThreadJob                           Desk   
```

**Comment by rjmholt** [comment] 2018-08-28 03:09
Hi @alexandair, the `PSEdition` field declares what "Editions" of PowerShell a module is compatible with.

Since PowerShell 5.1, a module can declare what PowerShell editions it's compatible with, with those editions currently being "PowerShell Core" and "Windows PowerShell" -- basically this is a CoreCLR vs FullCLR differentiation. You can read more about that here: https://docs.microsoft.com/en-gb/powershell/gallery/concepts/module-psedition-support.

Naturally, it would make no sense to display this normally; if you've got a module loaded in PowerShell Core, then it must be Core-compatible. Moreover, that field has historically been a hint for people using the module to know what it's compatible with -- we never actually processed it in any way, except to check that it's one of the values that's allowed; it doesn't change the way a module behaves.

**But**, we recently did a lot of work to port a number of PowerShell modules shipped with Windows itself (under the `$env:windir\System32\WindowsPowerShell\v1.0\Modules\` path) so that they work with PowerShell Core, a step toward increasing PowerShell Core's value proposition for Windows PowerShell users.

However, because there are thousands of Windows PowerShell modules in Windows, we knew we couldn't port them all at once. So after we added the Windows PowerShell module path into the PowerShell Core module path, we leveraged the `CompatiblePSEditions` field to differentiate between the modules that we have confirmed compatible, with those we have not. Basically we changed all the modules we confirmed as compatible with PowerShell Core to include `Core` in their `CompatiblePSEditions` module manifest field.

So now if you try to import a module from the Windows PowerShell system module path and it's not marked as Core-compatible, it will fail. But note that this **only applies to modules on the Windows PowerShell system module path on Windows**; modules loaded from anywhere else will have their `CompatiblePSEditions` field ignored and will just load as normal.

Anyway, because we simply couldn't check all those modules (some of them are pretty hard to test because they do things like setup data clusters or DNS zones), we also included an override mechanism so that you can still import a module if it not marked as Core-compatible (`Import-Module -SkipEditionCheck Dism` for example). Since you can do this, it's helpful to know in `Get-Module -ListAvailable` which modules have been marked as compatible with what edition. So that's why the field appears there.

The last thing is that not marking the `CompatiblePSEditions` field in a manifest will make it default to `@("Desktop")`, since prior to PowerShell Core you probably wouldn't use that field and we can only assume the module is compatible with Windows PowerShell. This is why we don't check this field for modules that aren't from Windows PowerShell -- normal modules that don't have this field would default to only Desktop-compatible and would fail to load; we'd break everything. Further, versions of PowerShell older than 5.1 would error on the `CompatiblePSEditions` manifest field, so writing a PowerShell module supported by both PowerShell Core 6 and PowerShell 4 would be impossible. So the field is not required for 3rd party modules -- we only check those modules shipped as part of Windows.

So to summarise:
- This is a Windows-only phenomenon to mark module compatibility with Windows PowerShell (marked as `Desk` or `Desktop`) and PowerShell Core (marked as `Core`). It's possible to be compatible with both -- you'd see that in `Get-Module` output as `Core,Desk`.
- We marked some Windows PowerShell modules shipped with Windows as compatible with PowerShell Core after testing them, but not all of them (because there are so many).
- We built in mechanisms to allow users to see the compatibility of modules with PowerShell Core and give them the ability to control their import.
- This compatiblity marking doesn't affect 3rd party modules and adding it in isn't always desirable, so you will see 3rd party modules that work fine in PowerShell Core marked with their compatibility as only `Desktop` (because that is the default).
- On Linux, this whole phenomenon can be ignored -- it doesn't mean anything at all.

You can read more about this whole feature here: https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0025-PSCore6-and-Windows-Modules.md.

I'll close this up now that it's answered. But please comment if you have any other questions or suggestions.

**Closed by rjmholt** 2018-08-28 03:09 UTC
Labels: Area-Cmdlets-Core, Issue-Question

**Comment by alexandair** [comment] 2018-08-28 08:36
@rjmholt
Thank you for your detailed answer.
Here are a couple of things that I think are not right with how PSEdition property is used:

- If PSEdition property is not relevant on Linux, it shouldn't be exposed on Linux
- "Desk" value should be "Desktop"
- If the module is supported in both-Windows PowerShell and PowerShell Core-I would expect value to be "Desk, Core" (for example, AzurePSDrive is compatible with both editions)
- If I run this in PowerShell Core on Windows, I would expect all Core-compatible modules to be marked  as "Core". If they are marked as "Desk", by default, I would think that compatibility is not met, and I could expect certain issues using that module on PowerShell Core

Current behavior doesn't provide a satisfying user experience. Either on Windows or Linux.

**Comment by rjmholt** [comment] 2018-08-28 08:50
On the second point, `Desk` is used rather than `Desktop` because the format column it needs to fit in is 9 characters wide. `Core,Desk` is 9 characters.

**Comment by rjmholt** [comment] 2018-08-28 08:57
On point three, the current decision is to represent what is actually given in the module manifest rather than how PowerShell interprets it. We decided that `Get-Module` should be representing the manifest as faithfully as possible; rather than PowerShell trying to do magic and creating problems, the module owners just need to mark edition compatibility. `AzurePSDrive` [does not have a `CompatiblePSEditions` field](https://github.com/PowerShell/AzurePSDrive/blob/development/AzurePSDrive.psd1) or a `PowerShellVersion` field, so it hasn't been marked as Core-compatible.

**Comment by rjmholt** [comment] 2018-08-28 08:59
Modules are marked as Desktop-compatible-only by default because prior to PowerShell Core there was no marking. So we are forced to interpret no marking as "legacy", i.e. Desktop-compatible-only.

**Comment by rjmholt** [comment] 2018-08-28 09:08
There are two things that you've raised that probably need refining as the edition-compatibility concept matures:
- Should `Get-Module` et al. give an unaltered representation of the module manifest, or show how PowerShell interprets it given the path the module is on and how it was loaded? The problem is that it's possible to force loading an incompatible module as if it's compatible, but then showing the compatibility field as `Core` would be pointless. You know if the module is actually "compatible", since it's loaded. So you probably want to know how the module has been *marked*.
- Should we bother showing the edition compatibility at all in contexts where it doesn't matter (i.e. on non-Windows or when `-ListAvailable` isn't used)? Again the question is one of representing the manifest vs what's relevant to the current session; you might write a Desktop-compatible module on Linux and want to check that it registers as such.
