### ISSUE TITLE
Trash  need more command :)

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12256] opened 2020-04-04 17:33 UTC
sometimes Remove-item is considered a dangerous command. i known it exist -whatif and -confirm switch
but sometimes we need  to restore same files or folder deteled by mistake. it great to add some command   to complete 'Clear-RecycleBin'
```

MoveTo-RecycleBin
  move files to trash instead tto delete them
RestoreTo-RecycleBin
  restore  files
Get-RecycleBinInfo
  show original absolute path and deletion date
```

**Comment by iSazonov** [comment] 2020-04-05 06:48
For Windows we should bring back file system transactions.

**Comment by doctordns** [comment] 2020-04-05 08:32
> For Windows we should bring back file system transactions.

The only transactions I remember were in the registry provider. I don't ever recall transactions within the file system provider. Are you suggesting adding transactions into the file system provider?

**Comment by p0W3RH311** [comment] 2020-04-05 08:48
thanks :) 

transaction in filesystem its maybe impossible.
another suggestion *-RecycleBin command as wrapper to com object Shell.Application

**Comment by iSazonov** [comment] 2020-04-05 09:29
I found that MSFT does not recommend using Transactional NTFS https://docs.microsoft.com/en-us/windows/win32/fileio/about-transactional-ntfs

**Comment by TSlivede** [comment] 2020-08-17 19:05
Is this a duplicate of https://github.com/PowerShell/PowerShell/issues/6801 ?

**Comment by mklement0** [comment] 2020-09-23 21:22
I think so, @TSlivede; @vexx32, can you please mark this as a duplicate?

**Closed** 2020-09-23 21:23 UTC
Labels: Issue-Enhancement, Resolution-Duplicate
