### ISSUE TITLE
Write-Progress incorrectly shows 100% until 1% of the task is completed

### ISSUE THREAD

**Issue by wi-fr** [PowerShell/PowerShell#18850] opened 2022-12-26 15:37 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
for ($i = 0; $i -le 2; $i += 0.1) { 
  Write-Progress -Activity 'DEMO' -Status $i -PercentComplete ([int]$i)
  Start-Sleep 1
}


### Expected behavior

```console
The progress bar shows 0% before 1% of the task is completed.
```

### Actual behavior

```console
The progress bar shows 100% before 1% of the task is completed.

In Windows PowerShell 5.1 the code snippet works as expected.
```

### Error details

```console
No error
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2022-12-26 19:21
Good find, but a duplicate of:

* #18848

**Comment by mklement0** [comment] 2022-12-26 19:40
Good find; let me boil it down to the core problem:

* `-Percent 0` is incorrectly treated like `-Percent 100`, i.e. the whole progress bar is unexpectedly filled in.

```powershell
# !! Shows the whole bar filled in, as if -PercentComplete 100 had been passed.
Write-Progress -Activity Test -Status '0% complete' -PercentComplete 0; Start-Sleep 3

# OK: any value greater than 0 (1 - 100)
Write-Progress -Activity Test -Status '1% complete' -PercentComplete 1; Start-Sleep 3
```

**Comment by SteveL-MSFT** [comment] 2022-12-28 22:59
I found and fixed this as part of this PR: https://github.com/PowerShell/PowerShell/pull/18735/files#diff-cbda13b2a2d772c7dc93249087ce0e6b94bfdc7d022ab9eea9a752610674ab71R427

**Closed** 2023-01-25 11:34 UTC
Labels: In-PR
