### ISSUE TITLE
Need better way to work with native exes that report progress on stderr

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#3132] opened 2017-02-11 21:22 UTC
Steps to reproduce
------------------
Today if you use an executable like git.exe (which uses stderr for progress not just errors), in the PowerShell console stderr appears like stdout (no ErrorRecords). In ISE, stderr is converted to ErrorRecords and displays in red.  RE git.exe using stderr to report progress see http://git.661346.n2.nabble.com/git-push-output-goes-into-stderr-td6758028.html

This leads to less than a desirable user experience in ISE:

![image](https://cloud.githubusercontent.com/assets/5177512/22857505/5cbf68b2-f063-11e6-8f5c-b4f82423e490.png)

The above looks like an error but it is just git reporting progress i.e. that it switched to the branch.

Expected behavior
-----------------

I would like a way to configure an app like git.exe to behave in a host that handles stderr like ISE does, to instead behave like the console. So the same command looks like this:

![image](https://cloud.githubusercontent.com/assets/5177512/22857529/1bd44a74-f064-11e6-8eb2-5fb1bbab071b.png)

Also, it might be useful if a script or module had a way to query the host (or settings for a particular exe) to determine how its stderr is being handled. 

Actual behavior
---------------
The progress output sent to stderr by Git is displayed as an error when it is **NOT** an error. I have a feeling this may be even more common in the Linux world so it would be good to have a more flexible "stderr handling" strategy than the current one.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by joeyaiello** [comment] 2017-02-11 22:41
Oh, interesting. So like a PowerShell variable that lets you either redirect stderr into the PowerShell Error stream or not. 

Something like `$PSRedirectErrors = $True` or the negative `$PSPassthruError = $True`?

**Comment by lzybkr** [comment] 2017-02-11 22:48
Untested and needs verification - but I believe https://github.com/PowerShell/PowerShell/pull/2450 should address hosts like the ISE and remoting that do not handle stderr like the console host. Maybe @vors can chime in to confirm.

Of course, that means these changes need to be pulled back into Windows for the ISE to pick it up.

**Comment by vors** [comment] 2017-02-11 23:07
Jason is correct.

**Comment by vors** [comment] 2017-02-11 23:28
Duplicate of #1599

**Closed by vors** 2017-02-11 23:28 UTC
