### ISSUE TITLE
Add new release steps in release YAML

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#14583] opened 2021-01-08 17:33 UTC
There are some release steps for PowerShell that need to be included in the YAML, first as manual steps and then hopefully as automated ones (ideally turned into GH actions if possible).

- The winget release
- The step to merge the preview branch, if required
- The MSIX store release submission step

Also we should add logic to skip (rather than fail) the global tool step for preview releases.

**Comment by mi-hol** [comment] 2021-07-26 12:19
> Also we should add logic to skip (rather than fail) the global tool step for preview releases.

I've read in other places that winget will provide pre-releases too. Above statements seems to contradict them.
Could availability of preview release via winget be clarified please?

**Comment by rjmholt** [comment] 2021-07-27 18:22
> Could availability of preview release via winget be clarified please?

[We currently release previews to winget](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/PowerShell/Preview) and don't intend to change that

**Comment by mi-hol** [comment] 2021-07-28 07:30
while [this patch](https://github.com/microsoft/winget-pkgs/pull/22466/commits/4521d3138c598760d5e22e482f6e89123437b63f) was merged that should enable powershell-preview 8 around the time you replied.
Trying to install it via winget still fails in Germany.
Is there a delay, after merge completed, that I need to consider?

'''
winget install --name PowerShell-Preview --exact
Es wurde kein Paket gefunden, das den Eingabekriterien entspricht.
'''
No package that meets the input criteria was found.

**Comment by mi-hol** [comment] 2021-07-28 08:27
> Trying to install it via winget still fails in Germany.
> Is there a delay, after merge completed, that I need to consider?

or is it caused by "PackageLocale: en-US" ?

I found it installs on PC in Germany with display language set to English but not when display language is set to German


Example for failed installation:
'''
get-culture

LCID             Name             DisplayName
----             ----             -----------
1031             de-DE            Deutsch (Deutschland)

winget install --name PowerShell-Preview --exact
Es wurde kein Paket gefunden, das den Eingabekriterien entspricht.
'''
Example for working installation:
'''
get-culture

LCID             Name             DisplayName
----             ----             -----------
1031             de-DE            German (Germany)
'''

**Comment by rjmholt** [comment] 2021-07-28 16:22
@mi-hol I've discussed your issue in the linked winget issue and it looks like the issue is one of case-sensitivity. See https://github.com/microsoft/winget-pkgs/issues/22522#issuecomment-888427870.

**Comment by mi-hol** [comment] 2021-07-29 08:42
Thanks for following up, now new topics come to mind.
1. "case-sensitivity" sounds like violating the basic Windows concept of being "case insensitive".
2. From my view there is currently an inconsistent "naming" of pwsh "Preview" release compared to other MSFT products that leads to confusions. In some places the naming uses a dot, in others a dash as name separator and sometime no separator. This is basically asking for human error to happen on both sides (developers and users)
3. changing these name string string in many places manually consumes a lot of effort and introduces a high risk of error. How about using a template pre-processor and a single config file for the string value to auto-generate the correct config files consistently? This would be along the lines of "using automation for building automation tools"



```
winget search preview
Name                                       Id                                              Version         Match
-------------------------------------------------------------------------------------------------------------------------

PowerShell Preview                         Microsoft.PowerShell.Preview                    7.2.0.8         Tag: preview
Windows Terminal Preview                   Microsoft.WindowsTerminalPreview                1.10.1933.0
Visual Studio Professional 2019 Preview    Microsoft.VisualStudio.2019.Professional-Preview 16.11.31320.298
Visual Studio Enterprise 2019 Preview      Microsoft.VisualStudio.2019.Enterprise-Preview  16.11.31320.298
Visual Studio Community 2019 Preview       Microsoft.VisualStudio.2019.Community-Preview   16.11.31320.298
Microsoft Teams Preview                    Microsoft.TeamsPreview                          1.4.00.18264
Microsoft .NET SDK Preview                 Microsoft.dotnetPreview                         6.1.21.30213
AXIS Camera Station Preview                AxisCommunications.AxisCameraStation-Preview    0.2130.058
Visual Studio Enterprise 2022 Preview      Microsoft.VisualStudio.2022.Enterprise-Preview  17.0.31423.177
Visual Studio Community 2022 Preview       Microsoft.VisualStudio.2022.Community-Preview   17.0.31423.177
Visual Studio Professional 2022 Preview    Microsoft.VisualStudio.2022.Professional-Preview 17.0.31423.177
PowerToys (Preview)                        Microsoft.PowerToys                             0.41.4
Azure IoT Explorer (preview)               Microsoft.azure-iot-explorer                    0.14.4.0
AppInstaller File Builder(Preview)         Microsoft.AppInstallerFileBuilder               1.2020.221.0
```

**Comment by rjmholt** [comment] 2021-07-29 19:39
> "case-sensitivity" sounds like violating the basic Windows concept of being "case insensitive".

This is an issue for winget, please open an issue there.

> From my view there is currently an inconsistent "naming" of pwsh "Preview" release compared to other MSFT products that leads to confusions. Only pwsh naming uses a dot as name separator, in other cases a dash or no separator is used. This inconsistency is basically asking for human error to happen on both sides (developers and users)

Yeah, I've opened https://github.com/PowerShell/PowerShell/issues/15836 to track updating our winget automation to standardise the manifests we generate better.

> changing these "name strings" in many places manually for every release, consumes a lot of effort and introduces a high risk of error. How about using a template pre-processor and a single config file for the string value to auto-generate the correct config files consistently? This would be along the lines of "using automation for building automation tools"

We automate the process with [this script](https://github.com/PowerShell/PowerShell/blob/master/tools/releaseToWinget.ps1), which needs updating. However, [the community often gets their winget updates merged first, which is an issue for consistency](https://github.com/microsoft/winget-pkgs/pull/8623#issuecomment-797654830).

@mi-hol at this point I think your discussion should be moved to https://github.com/PowerShell/PowerShell/issues/15836, since it's not on topic for this issue.

**Closed** 2023-11-23 11:21 UTC
Labels: Issue-Enhancement, Area-Maintainers-Build, Resolution-No Activity
