### ISSUE TITLE
Linux: When Prompt include Unicode Char, Cursor Positioned Error

### ISSUE THREAD

**Issue by fcharlie** [PowerShell/PowerShell#5856] opened 2018-01-11 02:16 UTC
Steps to reproduce
------------------

```powershell
cd /tmp
mkdir 测试路径
cd 测试路径
```

Expected behavior
-----------------

Actual behavior
---------------

![2018-01-11 10-10-36](https://user-images.githubusercontent.com/6904176/34805190-b6d7e27e-f6b7-11e7-9e0c-e489cd4c4f2c.png)

![2018-01-11 10-16-56](https://user-images.githubusercontent.com/6904176/34805348-996e3c8c-f6b8-11e7-9986-2c2e7d50f043.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0                                                                                   
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.0                                                                                  
OS                             Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017              
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0                                                                                     

```

This problem is due to the fact that the character length is not calculated correctly. UTF-8 encoding, the length of the character may be 1~4 bytes. So the cursor is not positioned correctly.

**Comment by chuanjiao10** [comment] 2018-01-11 10:05
yes,it is psreadline problem,fixed allready by version 2.
now only manually installed for chinaese users.
I also hope that version 2.0 psreadline will be released as soon as possible. And integrated in ps core 6.

https://github.com/lzybkr/PSReadLine/issues/542

**Comment by lzybkr** [comment] 2018-01-11 19:04
Run `Install-Module PSReadLine -AllowPrerelease -Force -AllowClobber` to get 2.0.0-beta1 with the fix.

PowerShell 6.1 will soon pull this version as well, see https://github.com/PowerShell/PowerShell/pull/5759

If you're running on Linux, you might need to rename the install directory to fix the case, I think it gets installed with `PSReadline` instead of `PSReadLine`. I'm looking in to how that can be fixed.

**Comment by rkeithhill** [comment] 2018-01-11 19:32
Ah, then ignore my comment - https://github.com/lzybkr/PSReadLine/issues/555#issuecomment-357033986, Ah, yup, this `/usr/local/share/powershell/Modules$ sudo mv PSReadline/ PSReadLine/` fixed it for me.

**Comment by lzybkr** [comment] 2018-01-11 23:32
@rkeithhill and anyone else - the PSGallery team have kindly updated the back end, so PSReadLine 2.0 should now install correctly on Linux/Mac w/o needing to rename the directory.

**Comment by fcharlie** [comment] 2018-01-12 00:40
@lzybkr  OK fixed

**Comment by chuanjiao10** [comment] 2018-01-13 03:43
hi @lzybkr : 
I used  PSReadLine 2.0.0-beta1 .
I found backspace  changed,from ctrl+H to ctrl + ?   .
It is by design？

**Closed** 2018-01-13 06:42 UTC
Labels: Issue-Question, Resolution-Answered

**Comment by lzybkr** [comment] 2018-01-13 18:17
@chuanjiao10 - that's definitely a bug, go ahead and open an issue in the PSReadLine repo.
