### ISSUE TITLE
What is the official plans for Tasks/threading?

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShell#10043] opened 2019-07-01 19:51 UTC
The biggest roadblock I see with true dotnet interop is dealing with TPL in PowerShell.  I see opt-in solutions like ThreadJobs resolve the need for creating Tasks, but what about executing Tasks concurrently?  Are there plans for anything like `async`/`await`?

**Comment by Bartolomeus-649** [comment] 2019-07-01 22:16
... and access to extension methods.

**Comment by chriskuech** [comment] 2019-07-01 22:19
@Bartolomeus-649, just curious--is this an issue with TPL interop or interop in general?

Other issues I've had with general interop: 
* Class import/export
* Interfaces

**Comment by Bartolomeus-649** [comment] 2019-07-01 22:31
Yes, TPL (DataFlow) has a lot of extension methods, just look here: [IPropagatorBlock<TInput,TOutput> Interface](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.ipropagatorblock-2?redirectedfrom=MSDN&view=netcore-2.2#extension-methods).

Also easier use of generics would help out a lot.

**Comment by fMichaleczek** [comment] 2019-07-01 22:52
@chriskuech for me, your issue is a duplicate of https://github.com/PowerShell/PowerShell/issues/6716
Maybe better to close this one and continue on #6716.

**Closed** 2019-07-02 00:05 UTC
Labels: Issue-Question
