### ISSUE TITLE
Perf issues in PSCore

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#7897] opened 2018-09-30 08:16 UTC
I know we are fixing performance issues here and there. Below is one observation from @JBorean when using PSCore via ansible.

https://github.com/ansible/ansible/issues/46300#issuecomment-425682646

**Comment by jborean93** [comment] 2018-09-30 08:56
cc me @jborean93

**Comment by jborean93** [comment] 2018-10-01 10:17
No worries, the easiest way for you to test this right now is to install the latest release candidate for [Ansible 2.7](https://pypi.org/project/ansible/2.7.0rc4/). You have to use the release candidate or checkout straight from devel as the `psrp` connection plugin was only recently added.

From there create a file called `inventory.ini` with the following contents;

```
[windows]
windows-server

[windows:vars]
ansible_user=username
ansible_password=password
ansible_connection=psrp
ansible_port=5986
# only needed if using https (port 5986) and self signed certs
ansible_psrp_cert_validation=ignore

# if you want to use basic auth for a more stable timing test add the following
ansible_psrp_auth=basic
```

From there you can test out the timings with the following commands

```
# test out against the Microsoft.PowerShell (PSDesktop) endpoint
time ansible -i inventory.ini windows -m win_ping

# out out against the PowerShell.6 (PSCore) endpoint
time ansible -i inventory.ini windows -m win_ping -e ansible_psrp_configuration_name=PowerShell.6
```

I found that there was roughly a .5 second slowdown when working against the PSCore configuration. I was also able to replicate this when using the basic winrm connection plugin and changing the PS executable called to the PSCore one and it was also slower than PSDesktop.

I'm unsure what the cause is and this was very preliminary tests that I ran but it was consistent.

**Comment by iSazonov** [comment] 2018-10-01 11:07
@jborean93 Thanks for repo with Ansible but it will be more easy for MSFT team and community to investigate the problem with repo steps on pure PowerShell. Do you use New-PSSession cmdlet?

**Comment by jborean93** [comment] 2018-10-01 11:27
I do but I haven't really gone into testing it with the native PS cmdlets, I was merely commenting on the other issue that I came across some performance issues when using PSCore. I was asked to provide some reproducers and that's all I have right now.

**Comment by iSazonov** [comment] 2018-10-01 13:43
> We can see that pwsh is ~.4 seconds slower to startup compared to PowerShell.

@jborean93 The slower startup issue is investigated by @daxian-dbw at the present time. Can you confirm that this is the only problem or do you see another problem in remoting? Also I still don't understand how Ansible use "remoting" - simply start PowerShell on remote host or use PowerShell remoting (PSRP) which you found slower?

**Comment by kvprasoon** [comment] 2018-10-01 19:06
@iSazonov Ansible can use both and the observation is using both the approach.

@jborean93 ?

**Comment by jborean93** [comment] 2018-10-01 19:43
That's correct we use both methods. Traditionally, the `winrm` connection plugin uses WinRS to create a shell and execute modules with `PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command -` and we send the module through the stdin pipe of this process. More recently we've added in the `psrp` connection plugin which uses PSRP (over WinRM) to start a Runspace Pool and execute the module over a PowerShell pipeline. Between the 2, `winrm` is what 99% of Windows users use right now as `psrp` is more experimental and quite new. I found that both `winrm` and `psrp` took longer to execute when using the PSCore equivalents, pwsh.exe for winrm and PowerShell.6 for psrp.

We created the `psrp` connection plugin as we found that creating a new pool and pipeline was slightly faster than the overhead that WinRS has. There are also other issues in the Python WinRM library that `winrm` uses which `psrp` is designed to overcome but that's unrelated to this conversation. We are also looking into persisted connections so we can share the pool between Ansible tasks to speed up execution even more but have hit some roadblocks in Ansible itself that has stopped us so far.

**Comment by iSazonov** [comment] 2018-10-02 04:43
@jborean93 Thanks for clarify!

> I found that both winrm and psrp took longer to execute when using the PSCore equivalents, pwsh.exe for winrm and PowerShell.6 for psrp.

/cc @PaulHigin @SteveL-MSFT  for your information.

**Comment by PaulHigin** [comment] 2018-10-02 22:08
When you use the term "psrp", I assume you mean the OMI/WinRM bridge for Linux platforms?  "PSRP" is for PowerShell Remoting Protocol and is implementation dependent.  It is unfortunate that psrp is also used for the OMI implementation, which causes confusion.

Anyway, OMI/WinRM is not supported on Windows PowerShell, only on PSCore6.  If you are seeing a performance difference using WinRM (Windows platform only) based PowerShell remoting between Windows PowerShell and PSCore6, then that certainly needs investigating.  But I expect OMI/WinRM to be noticeably slower than WinRM since it includes another translation layer.

**Comment by jborean93** [comment] 2018-10-02 22:19
When I say psrp I mean a Python library that uses the PSRP layer over WinRM/WSMan to open a runspace pool. The performance issue seems apparent when running the powershell.exe vs pwsh.exe executables locally so it seems like there is some overhead when starting up the engine.

**Comment by SteveL-MSFT** [comment] 2018-10-02 23:44
The startup perf issue is being tracked in https://github.com/PowerShell/PowerShell/issues/6443

**Comment by jborean93** [comment] 2018-10-02 23:52
Thanks @SteveL-MSFT, feel free to close this issue if it's being tracked elsewhere. We don't have any immediate plans to official support PSCore but can always come back in the future if there's still a performance hit.

**Closed** 2018-10-02 23:59 UTC
Labels: Area-Performance, Area-Remoting, Issue-Discussion, Resolution-Duplicate
