### ISSUE TITLE
SysLogProvider should try/catch and output a warning if psl-native fails to load.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#6858] opened 2018-05-11 18:52 UTC
If libpsl-native, and unhandled exception is thrown within NativeMethods.OpenLog and the process exits.  
Instead, SysLogProvider should catch exceptions from OpenLog, write a detailed warning or error record and disable logging for the session.  While this will not catch other references to this binary, it will provide details at startup to identify the problem.

This is seen with 6.1.0 Preview 2 on private builds for ARM, including 

RMBIAN 5.36 user-built Debian GNU/Linux 8 (jessie) 3.4.113-sun8i
and
Linux rockrobo 3.4.39 #1 SMP PREEMPT Wed Mar 21 16:39:25 CST 2018 armv7l armv7l armv7l GNU/Linux

**Comment by mklement0** [comment] 2018-11-06 22:01
I don't know to what extent the problem is related and where it should be fixed, but I see the same error message even on non-ARM macOS and Linux systems when I try to use the PowerShell SDK from a `*.csx` script  executed by the [`dotnet-script`](https://github.com/filipw/dotnet-script) tool.

To reproduce:

* On macOS or Linux, install the `dotnet-script` with `dotnet tool install -g dotnet-script`

* Run `~/.dotnet/tools/dotnet-script test.csx`, with `test.csx` containing the code below.

```csharp
#r "nuget: Microsoft.PowerShell.SDK, 6.1.0"

using System.Collections.ObjectModel;
using System.Management.Automation;

PowerShell ps = PowerShell.Create();

Collection<PSObject> psObjects = ps.Invoke();

foreach (object pso in psObjects) {
  Console.WriteLine(pso.ToString());
}
```

The result, as of PowerShell Core 6.2.0-preview.1, is:

```
The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw
an exception. ---> System.DllNotFoundException: 
Unable to load shared library 'libpsl-native' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(liblibpsl-native, 1): image not found
```

**Comment by iSazonov** [comment] 2019-03-11 11:49
I see Core team working on implementing of DllMap project (Mono compatible). 
https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/dllmap.md
There is already some merged PRs.
I hope we'll can transform libpsl-native and manage Windows and Unix native dll in universal way.

**Comment by joeyaiello** [comment] 2020-07-30 22:45
Closing because we don't think this is relevant anymore. If someone has a real problem related, please file another issue and link to this one

**Closed by joeyaiello** 2020-07-30 22:45 UTC
Labels: Area-Engine, Issue-Bug, OS-Linux
