### ISSUE TITLE
PowerShell 7.3.4 now shows extra number such as (12345) in window title.

### ISSUE THREAD

**Issue by garretwilson** [PowerShell/PowerShell#19515] opened 2023-04-14 23:05 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I just upgraded from from PowerShell 7.3.3 to 7.4.4 (`PowerShell-7.3.4-win-x64.msi`), and now PowerShell shows extra stuff that is distracting and takes up space in the window title. It's especially distracting in Terminal, because each shell gets its own tab, and this cruft shows up in the tab. e.g.:

`C:\ - PowerShell 7.3. (12345)`

Each PowerShell instance shows a different number

### Expected behavior

I frankly don't remember what the Windows Terminal showed before, but I'm pretty sure it didn't show this extra stuff. Of what use is `(12345)` in the title/tab? (It's not useful to me, because I don't even know what it means!) Why do we need "PowerShell" and the version at all in Windows Terminal? Just show:

`C:\`

I can tell by the icon that it's PowerShell and not e.g. Git for Windows.

### Actual behavior

`C:\ - PowerShell 7.3. (17020)`

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by garretwilson** [comment] 2023-04-14 23:34
Oh, this is weird. Every time I start PowerShell in Windows terminal (and wait the requisite 5–10 seconds as normal), there are _different_ numbers in the tab for each session. i.e. I will see some number in parenthesis `(xxxxx)`, and the number will stay the same until I `exit`. The next time I start PowerShell, the number will be different. And if I open multiple PowerShell tabs in Windows Terminal, they all show different numbers!

(Obviously the usefulness of this for an end-user is doubtful. Maybe it's some debugging information someone forgot to take out.)

I just realized that this happens with the PowerShell window as well, so it has absolutely nothing to do with Windows Terminal. We can take that out of the equation.

**Comment by NoMoreFood** [comment] 2023-04-15 00:24
Can you include a screenshot? Not sure what you're referring to.  Here's what mine looks like.

![image](https://user-images.githubusercontent.com/12881023/232173788-8384b57a-2c82-4d48-bde7-10dda418b8b7.png)

**Comment by garretwilson** [comment] 2023-04-15 00:46
> Can you include a screenshot? Not sure what you're referring to. Here's what mine looks like.

Since yours looks different, I can understand the desire to see it with your own eyes. But you'll see that it's showing exactly what I indicated:

![powershell-issue-19515](https://user-images.githubusercontent.com/627125/232174701-d2bcc233-63ee-4778-b68b-8fc2f1554529.png)

I just noticed that mine shows the `(x64)` when starting up, but then changes to some seemingly arbitrary number. (I don't see why we need the `(x64)` either. Like I need to be reminded that my system isn't 32-bit anymore. 😄)

**Comment by NoMoreFood** [comment] 2023-04-15 01:19
Sanity check... does it change when you do pwsh.exe -NoProfile ?

**Comment by garretwilson** [comment] 2023-04-15 05:05
> Sanity check... does it change when you do pwsh.exe -NoProfile ?

In a PowerShell window, entering `pwshe.exe -NoProfile` results in no change whatsoever to the window title.

**Comment by rhubarb-geek-nz** [comment] 2023-04-15 07:45
> I just noticed that mine shows the `(x64)` when starting up, but then changes to some seemingly arbitrary number. (I don't see why we need the `(x64)` either. Like I need to be reminded that my system isn't 32-bit anymore. 😄)

You might see "ARM64" or "arm64" if you are on a system such as Windows Dev Kit 2023, which can run both AMD64 and ARM64.

**Comment by doctordns** [comment] 2023-04-15 12:03
Note that it is easy to change the text in a tab within Terminal. Just do this:
```powershell
$Host.UI.RawUI.WindowTitle = 'Any Test You Want'
```

**Comment by MartinGC94** [comment] 2023-04-15 12:47
Looks like the PID. It doesn't happen for me: 
![image](https://user-images.githubusercontent.com/42123497/232224347-173ba977-7886-40b3-a1b9-46545e8df3d7.png)
 and I haven't seen any other complaints about this so I guess it's a problem specific to your machine.  
Since the text is dynamic, I'm guessing it's something in your profile. Try launching PowerShell with `-NoProfile`. I know you've already done this, but you did it from inside PowerShell, after the title had already been set so that doesn't really prove anything.

**Comment by jhoneill** [comment] 2023-04-15 13:05
> > Sanity check... does it change when you do pwsh.exe -NoProfile ?
> 
> In a PowerShell window, entering `pwshe.exe -NoProfile` results in no change whatsoever to the window title.

Starting from an existing window will keep the same title 
try `start pwsh -ArgumentList "-noprofile"` 

It's either the setting for Windows terminal (though I don't know _how_ you ask for the PID) or the profile, PowerShell itself doesn't put the minor version in the window title. 

Per @doctordns  above I have this in my profile
```
#Window title (add {3}@{4} for user@machine )
$Host.UI.RawUI.WindowTitle = 'PS {0}.{1} {2}' -f $PSVersionTable.PSVersion.Major,
                                                 $PSVersionTable.PSVersion.Minor,
                                                 $PSVersionTable.PSVersion.PreReleaseLabel,
                                                 [environment]::UserName,
                                                 [environment]::MachineName
if      ([System.Environment]::OSVersion.Platform -notmatch "^Win" ) {
    $Host.UI.RawUI.WindowTitle = $PSVersionTable.Platform + " " + $Host.UI.RawUI.WindowTitle
}
```

**Comment by garretwilson** [comment] 2023-04-15 13:14
I commented out the following in my `$Profile`, and the number disappeared!

```powershell
Import-Module posh-git
```

I would guess that PowerShell 7.3.4 has some API changes that will cause [posh-git](https://github.com/dahlbyk/posh-git) to need updating. Odd for it to happen on a patch version increment, though.

**Comment by iSazonov** [comment] 2023-04-15 13:57
The number is $PID 😄

**Comment by rhubarb-geek-nz** [comment] 2023-04-16 01:36
> I frankly don't remember what the Windows Terminal showed before

Is that actually the "Windows Terminal" in your screenshot? It looks more like the traditional Console window.

**Comment by kilasuit** [comment] 2023-04-16 12:27
> Oh, this is weird. Every time I start PowerShell in Windows terminal (and wait the requisite 5–10 seconds as normal), there are _different_ numbers in the tab for each session. i.e. I will see some number in parenthesis `(xxxxx)`, and the number will stay the same until I `exit`. The next time I start PowerShell, the number will be different. And if I open multiple PowerShell tabs in Windows Terminal, they all show different numbers!

This is most likely the Process ID or $PID - highly unlikely to be anything else



> I commented out the following in my `$Profile`, and the number disappeared!
> 
> ```powershell
> Import-Module posh-git
> ```
> 
> I would guess that PowerShell 7.3.4 has some API changes that will cause [posh-git](https://github.com/dahlbyk/posh-git) to need updating. Odd for it to happen on a patch version increment, though.
> 
> There's also the possibility that this was already there in previous versions and I only now noticed it, but I don't think so.

This to me means that Posh-git added this change not PowerShell, perhaps @rkeithhill can comment on this as he's been involved with the Posh-git module for some time.
@garretwilson what version of Posh-git are you running? We'd need this to be able to properly confirm where the issue is.

> Is that actually the "Windows Terminal" in your screenshot? It looks more like the traditional Console **window.

nope it's the standard console

Marking this for now as resolution answered & resolution external as I believe this is a Posh-git issue for the time being 
I will do some more digging and see if that is the case or not & can change the labels if believed this isn't a Posh-Git issue but it seems very much like it will be.

**Comment by garretwilson** [comment] 2023-04-16 13:09
> Is that actually the "Windows Terminal" in your screenshot? It looks more like the traditional Console window.

No, once I realized that this was simply the window title and nothing to do with Windows Terminal, I sent a screen shot of the PowerShell window to take Window Terminal out of equation. Windows Terminal seems to have been a red herring. I updated the title of this ticket accordingly.

**Comment by garretwilson** [comment] 2023-04-16 13:14
> This to me means that Posh-git added this change not PowerShell …

Except that posh-git has been unchanged for over a year. So I find it odd this would just now show up—or that I would just now notice it.

Maybe somebody could kindly install posh-git and see if you can reproduce the issue?

> Marking this for now as resolution answered & resolution external as I believe this is a Posh-git issue for the time being

I think it's clear that it's _coming_ from posh-git. But I don't think the doubt is fully "answered" yet, as we don't know why it suddenly appeared. It would be more comforting to know what caused posh-git to add this behavior when posh-git hasn't changed. This means something in PowerShell might have changed that would influence the behavior of other applications, and it would be good to know what that was. Once we know that, we'll know better whether the resolution is "external" as you say, or something that PowerShell changed with unintended "external" consequences.

**Comment by kilasuit** [comment] 2023-04-16 14:10
@garretwilson that's why I have not yet closed it but added the labels as I **think** it's an external resolution but it _may_ be a combination of changes in posh-git and PowerShell.

> Maybe somebody could kindly install posh-git and see if you can reproduce the issue?

I did ask what version of posh-git you are using so that it could be reproduced properly

**Comment by doctordns** [comment] 2023-04-16 14:13
My guess, irrespective of the source, the underlying issues that the window title is being changed in a profile. 
The OP could usefully provide the $Profile file to check. 

I think this issue can be closed.

**Comment by garretwilson** [comment] 2023-04-16 14:15
> I did ask what version of posh-git you are using so that it could be reproduced properly

Sorry, didn't see that request.

`Get-Module posh-git` gives me:

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.1.0                 posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranchName, Get-GitBranchStatusColor…}
```

**Comment by garretwilson** [comment] 2023-04-16 14:18
> The OP could usefully provide the $Profile file to check.

I discovered that when I comment out `Import-Module posh-git` the issue goes away. I believe there are no external file references, and the strings `pid` and `title` appear nowhere in the rest of the profile. I thus believe the rest of the profile would be of little value.

**Comment by kilasuit** [comment] 2023-04-16 14:23
@doctordns I'm happy keeping it open for now whilst I try and track down ultimate root cause, no reason to close it too quickly

**Comment by garretwilson** [comment] 2023-04-16 14:26
I note that open opening PowerShell the window title is cut off in Windows Terminal, so I don't see the PID unless I switch to e.g. the root directory to make the window title shorter.

Perhaps I never saw the PID in the window title, and only coincidentally did a `cd \` after upgrading to the latest PowerShell version? I don't think that's what happened, but it's not impossible. I'll be interested in seeing if this was always present in posh-git, but I still think it unlikely.

**Comment by kilasuit** [comment] 2023-04-16 14:32
> If it turns out it was always present in posh-git, then yes the appropriate thing to do would be to close this ticket and I'll open another ticket for posh-git.
 This is where my line of thinking is hence tagging @rkeithhill in this issue due to his closeness with posh-git

**Comment by kilasuit** [comment] 2023-04-16 14:33
I am just about to build using Windows Sandbox a similar environment to replicate this issue

**Comment by garretwilson** [comment] 2023-04-16 14:35
I did a brute force attack and cloned the [posh-git repository](https://github.com/dahlbyk/posh-git.git) and did a text search for `$PID`. This is the only reference, from `PoshGitTypes.ps1`:

```powershell
    [psobject]$WindowTitle = {param($GitStatus, [bool]$IsAdmin) "$(if ($IsAdmin) {'Admin: '})$(if ($GitStatus) {"$($GitStatus.RepoName) [$($GitStatus.Branch)]"} else {Get-PromptPath}) - PowerShell $($PSVersionTable.PSVersion.Major).$($PSVersionTable.PSVersion.Minor) $(if ([IntPtr]::Size -eq 4) {'32-bit '})($PID)"}
```

I'll post it right away before I look into it more closely, but I'll bet one of you will immediately know "ah ha, it was always there" or "ah hah, that's what happened to make it show up".

**Comment by garretwilson** [comment] 2023-04-16 14:38
So from taking that line at face value, it would seem that it was always there and I simply didn't see it because Windows Terminal was cutting truncating a long title? Is that the conclusion you're coming to as well?

**Comment by rkeithhill** [comment] 2023-04-16 16:12
The extra number in parens is the process id of the PowerShell process. Useful if you need to attach a debugger to (or kill) the process.

**Comment by iSazonov** [comment] 2023-04-17 03:03
I'd suggest changing a "mysterious" number into a more comprehensible format - `(pid; 1234)`.

**Comment by rhubarb-geek-nz** [comment] 2023-04-17 03:09
> I'd suggest changing a "mysterious" number into a more comprehensible format - `(pid; 1234)`.

Part of the problem is screen real-estate, hence it not being visible with a long current directory. It's not mysterious if you know that it is a pid, if you don't know what a pid is then saying it's a pid does not stop it being mysterious. Hopefully the formatting is part of posh-git and not powershell itself.

**Comment by garretwilson** [comment] 2023-04-17 23:07
From the line I dug up from the `posh-git` source code, it would appear that posh-git was always adding the PID, and I didn't notice it because the Windows Terminal tab was truncating the long title. That I switched to a root directory and noticed it after upgrading to v7.3.4 seems to have been a coincidence. There's no indication that any change in v7.3.4 made this happen.

If someone has a problem with posh-git adding the PID to the window title, or the way it presents the PID, I agree that the feedback should go in a posh-git ticket, not here.

Thus it would seem appropriate to close this ticket as invalid. Thanks for your quick response and interest. In this case it was a mistake of sorts on my side.

**Comment by jhoneill** [comment] 2023-04-18 10:58
@garretwilson  I'll close it for you 

It would seem like a good idea to raise this with the Posh-git folks. TBH changing someone's window title seems like bad manners to me, especially without providing an easy way to turn it off.

**Closed by jhoneill** 2023-04-18 10:58 UTC
Labels: Resolution-Answered, Resolution-External

**Comment by TheOriginalPiff** [comment] 2023-04-19 04:35
Ya welcome

**Comment by rkeithhill** [comment] 2023-04-19 05:04
FYI you can disable this feature with:
```powershell
Import-Module posh-git
$global:GitPromptSettings.WindowTitle = $null
```
