### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by AlinaPenkina** [PowerShell/PowerShell#6664] opened 2018-04-16 11:58 UTC
```
C:\Users\User>powershell
Starting the CLR failed with HRESULT 80070005.
```

**Comment by MaximoTrinidad** [comment] 2018-04-16 14:52
@AlinaPenkina 

It would be nice if could provide more information as is required every time you create an incident. We can't tell if this is an issue with PowerShell Core, Windows PowerShell, or even DOS command.

We need:

1. OS type and build
2. PowerShell Core Version.

Again, if this is a Windows PowerShell issue then it need to be addressed in the proper UserVoice forum (not Github) or the proper teams won't be able to work on it.

:)

**Comment by rjmholt** [comment] 2018-04-16 16:12
Looks like a permissions problem (HRESULT 80070005 is `E_ACCESSDENIED`). Also, I'm guessing this is Windows PowerShell.

Might be worth getting a crash dump: https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx.

**Comment by mklement0** [comment] 2018-04-17 17:25
Yes, it must be Windows PowerShell, given that the executable name is `powershell`.

@rjmholt: Googling `"Starting the CLR failed" HRESULT 80070005` currently yields this issue as the 2nd hit and switching to the "Images" tab shows your GitHub photo :)

**Comment by rjmholt** [comment] 2018-04-17 20:09
@mklement0 That's a worry. Admittedly when I was googling for the meaning of the error, there were so few good results I was worried I'd arrive back here again.

For reference, [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa378137(v=vs.85).aspx) is an unhelpful page enumerating common `HRESULT` values, and [this](https://fogbugz.bitvise.com/default.asp?WinSSHD.1.19116) page is the only other reference I could find to this bug on the internet.

@AlinaPenkina Without more details about the context or any way to reproduce, I don't think we'll be able to figure out what this is or fix it.

**Comment by SteveL-MSFT** [comment] 2018-04-18 09:26
@AlinaPenkina I'm closing this issue as it's not actionable without more details.  You can still reply to this issue with more details even if the issue is closed and we can reopen.  Thanks.

**Comment by MaximoTrinidad** [comment] 2018-04-26 14:00
OK! Just curious! This was reopened and what's the reason?

If this is a PowerShell Core issue then I would suggest to close this one. And, open new issue with proper information so we can contribute/discuss better.

:)

**Closed** 2018-04-26 16:55 UTC
Labels: Issue-Question, Resolution-Won't Fix
