### ISSUE TITLE
Debian (docker node:strect) using powershell command instead of pwsh

### ISSUE THREAD

**Issue by baio** [PowerShell/PowerShell#5615] opened 2017-12-04 11:26 UTC
Steps to reproduce
------------------
pwsh command is not working on debian (docker container node: stretch)
link to docker file https://gist.github.com/baio/3bb1097dd48510ddb5cf5fc01fe17c73

```powershell
pwsh -v
/bin/sh: 1: pwsh: not found
```

Expected behavior
-----------------

```powershell
pwsh -v
PowerShell v6.0.0-rc
```

Actual behavior
---------------

```powershell
pwsh -v
/bin/sh: 1: pwsh: not found
```

in the same time 

```powershell
powershell -v
PowerShell v6.0.0-rc
```

**Comment by daxian-dbw** [comment] 2017-12-04 19:40
@baio I cannot reproduce the issue using the docker file you pointed to. Here is what I did:
```
bash> curl https://gist.githubusercontent.com/baio/3bb1097dd48510ddb5cf5fc01fe17c73/raw/41e37d0dea01064389e88d5bbc14f2307c58ca81/gistfile1.txt -o Dockerfile
bash> docker build -t test:1 .
bash> docker run -it --rm --entrypoint bash test:1
root@2090288ae9fe:/# 
root@2090288ae9fe:/# pwsh -v
PowerShell v6.0.0-rc
root@2090288ae9fe:/#
```
Is there anything I'm missing?

**Comment by anmenaga** [comment] 2017-12-05 19:32
Also not able to repro; tried with provided dockerfile as well as using [install instructions](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#debian-9) on a clean [Debian 9](https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-9.2.1-amd64-DVD-1.iso) VM.

**Comment by daxian-dbw** [comment] 2017-12-11 16:49
I'm closing this issue as Not Repro.

**Closed by daxian-dbw** 2017-12-11 16:49 UTC
Labels: Issue-Discussion
