### ISSUE TITLE
GetCustomAttributes fails to retrieve CmdletAttribute with ConfirmImpact property

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#1252] opened 2016-06-30 19:10 UTC
Steps to reproduce
------------------
```
[System.Management.Automation.Cmdlet("Get", "Thing", ConfirmImpact = 'High', SupportsPaging = $true)]class C2{}
$t = [C2].GetCustomAttributes($false)
$t
```
From Scripting.Classes.Basic.Parsing.Tests.ps1

Expected behavior
-----------------
```
NounName                : Thing
VerbName                : Get
DefaultParameterSetName :
SupportsShouldProcess   : False
SupportsPaging          : True
SupportsTransactions    : False
ConfirmImpact           : High
HelpUri                 :
RemotingCapability      : PowerShell
TypeId                  : System.Management.Automation.CmdletAttribute
```
Actual behavior
---------------
```
Exception calling "GetCustomAttributes" with "1" argument(s): "'ConfirmImpact' property specified was not found."
At line:1 char:9
+         $t = [C2].GetCustomAttributes($false)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CustomAttributeFormatException
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Linux
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.5.0-217-g9c9161febac5fc433d1987e75d8ba9b18fd286c1
CLRVersion
WSManStackVersion              1.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

**Comment by daxian-dbw** [comment] 2016-10-14 23:41
Fixed via PR #2472

This was caused by a bug in `AssemblyLoadContext` -- dynamic assemblies are not correctly associated with the right load context. This has been fixed in the .NET Core preview packages for Nov. release (1.1.0).

Now it works fine:
```
PS C:\> [System.Management.Automation.Cmdlet("Get", "Thing", ConfirmImpact = 'High', SupportsPaging = $true)]class C2{}
PS C:\> $t = [C2].GetCustomAttributes($false)
PS C:\> $t

NounName                : Thing
VerbName                : Get
DefaultParameterSetName :
SupportsShouldProcess   : False
SupportsPaging          : True
SupportsTransactions    : False
ConfirmImpact           : High
HelpUri                 :
RemotingCapability      : PowerShell
TypeId                  : System.Management.Automation.CmdletAttribute

PS C:\>
PS C:\>
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.10-136-g001f6ecf72481e59e6f81e0f06f59a3e8a6dd587
SerializationVersion           1.1.0.1
PSVersion                      6.0.0-alpha
PSRemotingProtocolVersion      2.3
CLRVersion

PS C:\>
```

**Closed by daxian-dbw** 2016-10-14 23:41 UTC
Labels: Area-Build, Area-Engine, Blocked, Issue-Bug
