### ISSUE TITLE
When using  System.IO.DirectoryInfo with Set-Location subsequent call to Get-Location is not complete

### ISSUE THREAD

**Issue by belotn** [PowerShell/PowerShell#17745] opened 2022-07-22 18:08 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When i use for example 

`get-item c:\windows | set-location`

### Expected behavior

```console
Get-location or pwd should return
```
![image](https://user-images.githubusercontent.com/3379936/180497972-7d11ad9b-e749-4292-899c-c14e86bf0315.png)

### Actual behavior

```console
but instead Drive is not correctly set and Path is not usable outside powershell
```

![image](https://user-images.githubusercontent.com/3379936/180498193-498c0e13-8924-4099-abc9-cd0cae902445.png)

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Problem exist in powershell 5 also
```

**Comment by mklement0** [comment] 2022-07-23 18:48
Probably a duplicate of / related to:
* #9293
* #10522

**Closed** 2022-07-25 17:01 UTC
Labels: Resolution-Duplicate, Needs-Triage
