### ISSUE TITLE
Get-Item and Get-ChildItem formatting broken when remoting into a Windows PowerShell session

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13349] opened 2020-08-04 15:43 UTC
Not sure if other data types are affected as well, but `Get-Item` and `Get-ChildItem` output is.

Remoting into a PS *Core* session works fine.

## Steps to reproduce

Run on Windows, with elevation and remoting set up for Windows PowerShell.

```powershell
icm -cn . { gi c:\ } -ConfigurationName Microsoft.PowerShell | out-string | should -match c:\\
```

## Expected behavior

The test should pass.

## Actual behavior

The test fails, because all output fields are empty.

```none
InvalidResult:
Line |
   1 | icm -cn . { gi c:\ } -ConfigurationName Microsoft.PowerShell | out-string | should -match c:\\
     | Expected regular expression 'c:\\' to match '     Directory:   Mode                 LastWriteTime         Length Name
     | PSComputerName ----                 -------------         ------ ----                                                              --------------
     | localhost  ', but it did not match.
```

## Environment data

```none
PowerShell Core v7.1.0-preview.5 (7.1.0-preview.5) on Microsoft Windows 10 Pro (64-bit; Version 1909, OS Build: 18363.959)
```

Problem also occurs in 7.0.3.

**Comment by iSazonov** [comment] 2020-08-04 17:59
It seems we already have such issue.

**Comment by vexx32** [comment] 2020-09-25 17:16
Marking this as a duplicate of #11400 as that has more complete information and discussion.

**Closed** 2020-09-26 20:00 UTC
Labels: Issue-Question, Resolution-Duplicate
