### ISSUE TITLE
Invoke-RestMethod inconsistent behavior of redirects

### ISSUE THREAD

**Issue by anderssonjohan** [PowerShell/PowerShell#7540] opened 2018-08-16 12:34 UTC
Steps to reproduce
------------------

Test using public service MockBin.

```powershell
function invoke-restmethodtest($url ) {
  Write-Host "Invoke-RestMethod Url: $url"
  try {
    $res = Invoke-RestMethod -Uri $url -MaximumRedirection 0 -Method "GET"
    Write-Host "Request was successful"
    Write-Host $res
  }
  catch {
    Write-Host "Invoke-RestMethod threw exception"
    Write-Host $_
  }
}


invoke-restmethodtest -url "http://mockbin.org/redirect/303?to=http://mockbin.org/status/401/Unauthorized"
```

Expected behavior
-----------------

```none
Invoke-RestMethod Url: http://mockbin.org/redirect/303?to=http://mockbin.org/status/401/Unauthorized
Request was successful
See Other. Redirecting to http://mockbin.org/status/401/Unauthorized
```

Actual behavior
---------------

```none
Invoke-RestMethod Url: http://mockbin.org/redirect/303?to=http://mockbin.org/status/401/Unauthorized
Invoke-RestMethod threw exception
See Other. Redirecting to http://mockbin.org/status/401/Unauthorized
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

This is based on my findings noted here: https://github.com/PowerShell/PowerShell/issues/2896#issuecomment-413299919
However, when I try to get a reproducible error using public HTTP services I can only reproduce some of the inconsistent behaviors. 
In this ticket I only include what I could reproduce using a HTTP GET using MockBin.

The biggest issue for me in pwsh is that it didn't respect `-MaximumRedirection 0` at all when used in my real case (which I could not reproduce using MockBin).

**Comment by markekraus** [comment] 2018-08-16 13:05
@anderssonjohan Can you get a repro for the auth issue you previously discussed?

The change in behavior here between 5.1 and 6+ is intentional. Saying you wish to redirect 0 times and being redirected is an error condition. This issue as stated here is a duplicate of #4534.

**Closed** 2018-10-01 05:37 UTC
Labels: Area-Cmdlets-Utility, Resolution-Duplicate
