### ISSUE TITLE
Type-constrained Boolean variables fail to implicitly convert from most types, such as PSObject / PSCustomObject instances

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10426] opened 2019-08-22 20:23 UTC
# Steps to reproduce

```powershell
# OK: convert via cast (assigns $true)
$b = [bool] [pscustomobject]::new()

# !! BROKEN: convert via type constraint
[bool] $b = [pscustomobject]::new()
```

# Expected behavior

No output. Both assignments should succeed.

# Actual behavior

The 2nd statement causes the following error:

```none
Cannot convert value "System.Management.Automation.PSCustomObject" to type "System.Boolean". 
Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0
```

# Environment data

```none
PowerShell Core 7.0.0-preview.3
```

**Comment by vexx32** [comment] 2020-09-17 23:32
Given that this also doesn't happen with any other type, I think it makes sense to remove this special case. See #13651 for a related issue that arises because of this special casing.

/cc @SteveL-MSFT @rjmholt can we get y'all's thoughts on this one?

**Comment by rjmholt** [comment] 2020-09-28 13:37
I think the big considerations for me are:

- Can we make this change in attributed assignment without making it in parameter binding? (where I think the failure is valid UX, and more importantly is established behaviour)
- If so, does that make PowerShell more complicated by once again introducing a slight variation of concepts or logic?

I suspect that most users don't think of constrained assignment as a form of parameter binding, so muddying the concept might not have dire consequences. But even if so, I suspect decoupling the two pieces of logic while still getting things like validation attributes to work properly will be a large task.

**Comment by vexx32** [comment] 2020-09-28 13:54
Seems to me the logic would be better placed in the binder logic itself, rather than in variable assignment. Might be a bit of work to do, but IMO typical variable assignments should not be half mixed up in what should be binder-specific logic. The binder does a fair bit of extra logic as it is already, it's kind of weird that this (and seemingly this alone) got thrown into the standard variable assignment logic.

**Comment by mklement0** [comment] 2020-09-28 14:04
@rjmholt:

Agreed on point 1.

> muddying the concept might not have dire consequences

In the spirit of @vexx32's comment: It is the _current_ behavior that amounts to muddying: the inappropriate application of argument-mode parsing to expression-mode assignments.

(Most users are probably not even aware that you can use validation attributes in constrained assignments too, and I'm not sure it has any real-world uses. Similarly, that a nonsensical constrained assignment such as
`[alias('hi')] [Parameter(Mandatory)] [string] $there = 'foo'` is quietly accepted is worrisome, though that may be a manifestation of a larger problem of randomly placed attributes getting quietly ignored - see #10614)

**Comment by jantari** [comment] 2023-03-24 20:31
Two and a half years after opening my duplicate of this issue (here: #13651) I was yet again bitten by this surprising behavior: https://github.com/jantari/LSUClient/issues/84

Here's a smaller version of todays repro:

```powershell
$ConditionThatHappensToBeFalse = $false

class Example {
   [string[]]$LogMessage
}

[array]$LogMessage = if ($ConditionThatHappensToBeFalse) { "some value" }
[Example]@{'LogMessage' = $LogMessage}

# Meanwhile this works perfectly:
[Example]@{'LogMessage' = $null}
```

Is this issue going to be addressed at some point? It's not going to stop causing bugs / errors anytime soon ...

**Comment by jantari** [comment] 2023-03-24 21:24
Thank you for clarifying and opening that new issue, since these are all around assigning `AutomationNull` to type constrained values I assumed it to be same same problem.

I guess I'll just have to train myself real hard to stop doing any if-assignments without an explicit else. It _feels_ needlessly verbose, but then again lots of PowerShell conditional logic has to be overcomplicated anyway since 5.1 didn't have the ternary or null-coalescing operators.

The problem is when you see this in the interactive shell:

```powershell
$variable = if ($false) { 1 }
$null -eq $variable
# True
```

it's just so easy to forget that the return value of that if-statement cannot just (always) be treated as if it were the null that it is.

**Comment by mklement0** [comment] 2023-03-25 00:02
> since these are all around assigning `AutomationNull` to type-constrained values 

No, the issue at hand is specifically about `[bool]`-type-constrained variables, not about `AutomationNull`; e.g., the following fails too:

```powershell
[bool] $b = 'foo'
```

However, separately, `AutomationNull` _should_  consistently be treated like `$null` in expression contexts, hence the separate bug report.

**Comment by jantari** [comment] 2023-11-16 19:07
lmao "Resolution-No-Activity" for a relevant bug that's as relevant as ever and has seen _no activity indeed_ from the PowerShell team since 2019 ...

**Closed** 2023-11-24 00:43 UTC
Labels: Issue-Question, WG-Engine, Resolution-No Activity
