### ISSUE TITLE
Pasting a tab character triggers tab-completion

### ISSUE THREAD

**Issue by NotWearingPants** [PowerShell/PowerShell#13275] opened 2020-07-25 14:18 UTC
## Steps to reproduce

Copy the following text and paste it in powershell:
```powershell
echo hello
#	comment
echo world
```

## Expected behavior

Should print `hello` and `world`.

## Actual behavior

Prints `hello`, `hellocomment`, and `world`

## Notes

What happens is that pasting the `#` character followed by a tab character triggers tab-completion and completes to the last command.
So the result is the previous command, `echo hello`, and then the comment text, `comment`, which results in `echo hellocomment`.

This is very unexpected. I had a function with a comment which had an indentation inside it, and the function broke when I pasted its definition in powershell.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment] 2020-07-25 14:21
Duplicate of PowerShell/PSReadLine#579

Workaround is to use <kbd>CTRL</kbd> + <kbd>v</kbd> instead of right click.

**Comment by NotWearingPants** [comment] 2020-07-26 04:08
I tried both, and they both have the same behavior, which has this issue.

**Closed** 2020-07-26 04:14 UTC
Labels: Issue-Question

**Comment by Podbrushkin** [comment] 2023-10-13 16:34
So how do I paste if my clipboard contains tab characters? ctrl+v, mouse, shift+insert, nothing works. It prints hello, hellocomment, and world as issue author mentioned. I have a tsv in here-string:
```
@'
id	name	year
1	The Matrix	1999
2	The Devil's Advocate	1997
'@
```
Is there a way to paste it preserving tab characters without editing actual here-string?

Windows 11 -> wsl -> psreadline
