### ISSUE TITLE
Convert-Json with 1 item array

### ISSUE THREAD

**Issue by AesonDev** [PowerShell/PowerShell#2635] opened 2016-11-05 17:19 UTC
Where is my array of 1 item ?
Steps to reproduce
------------------
$json = @"
{

"contributions": [
        {
            "id": "demo-extension",
            "type": "ms.vss-distributed-task.task",
            "targets": [
                "ms.vss-distributed-task.tasks"
            ],
            "properties": {
                "name": "DemoTask"
            }
        }
    ]

}
"@

$json | ConvertFrom-Json | ConvertTo-Json  |  Write-Output

Expected behavior
-----------------
"targets" is an array and should stay an array

Actual behavior
---------------
The array (of 1 item) becomes an properties
<img width="691" alt="pstojson" src="https://cloud.githubusercontent.com/assets/7828684/20032134/5028f022-a384-11e6-9b50-55362e5a0775.PNG">

Environment data
----------------
Name                           Value                                                                                                                 
----                           -----                                                                                                                 
PSVersion                      5.1.14393.206                                                                                                         
PSEdition                      Desktop                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
BuildVersion                   10.0.14393.206                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                       
WSManStackVersion              3.0                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                   
SerializationVersion           1.1.0.1

**Comment by joeyaiello** [comment] 2016-11-05 17:22
This is a dupe of #2448

**Closed** 2016-12-07 23:19 UTC
Labels: Area-Cmdlets, Resolution-Duplicate
