### ISSUE TITLE
Command-line flags containing dots are not processed correctly

### ISSUE THREAD

**Issue by PStoner3** [PowerShell/PowerShell#19640] opened 2023-05-10 18:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When command line flags contain a dot (e.g. -x=io.quarkiverse.quinoa:quarkus-quinoa) the processor returns an error.

Assumptions:
1. the Quarkus CLI is installed.

Run `quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa`

### Expected behavior

```console
-----------
selected extensions:
- io.quarkiverse.quinoa:quarkus-quinoa


applying codestarts...
>> java
>> maven
>> quarkus
>> config-properties
>> dockerfiles
>> maven-wrapper
>> quinoa-codestart

-----------
[SUCCESS]  quarkus project has been successfully generated in:
--> C:\Users\AA99988\quinoa-app
-----------
Navigate into this directory and get started: quarkus dev
```

### Actual behavior

```console
[ERROR]  Unable to create project: Unmatched argument at index 4: '.quarkiverse.quinoa:quarkus-quinoa'
```

### Environment data

```powershell
 $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment] 2023-05-10 19:02
Tested with simple test harness

```
PS> cat ./echo.sh   
#!/bin/sh -e
echo "$@"
PS> ./echo.sh -x=io.quarkiverse.quinoa:quarkus-quinoa
-x=io .quarkiverse.quinoa:quarkus-quinoa
PS> ./echo.sh -x="io.quarkiverse.quinoa:quarkus-quinoa"
-x=io.quarkiverse.quinoa:quarkus-quinoa
PS> ./echo.sh -x='io.quarkiverse.quinoa:quarkus-quinoa'
-x=io.quarkiverse.quinoa:quarkus-quinoa
```

The unquoted value shows a space between "-x=io" and ".quarkiverse.quinoa:quarkus-quinoa" which means they are being counted as different arguments.

So a solution is to quote the value.

**Comment by mklement0** [comment] 2023-05-10 20:11
Yes, it's an unfortunate bug that's been around for a while ; duplicate of:

* #6291

It is unfortunately not the only parameter-binder bug with respect to `-`-prefixed arguments that _aren't_ PowerShell parameter names:

* https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+parameter+parsing%2Fpassing+in%3Atitle

**Closed** 2023-06-02 15:07 UTC
Labels: Needs-Triage
