### ISSUE TITLE
Invoke-RestMethod and Invoke-WebRequest do not return any HTTP Response content in the Error Object

### ISSUE THREAD

**Issue by jgigler** [PowerShell/PowerShell#3288] opened 2017-03-08 21:29 UTC
Steps to reproduce
------------------

Issue a malformed request to an API. In this case the Pager Duty Create Event API is utilized.

Expected behavior
-----------------

```powershell
PS C:\Users\Administrator> Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-15/create_event.json -met
hod Post -Body $body -ContentType "application/json"
Invoke-RestMethod : {"status":"invalid event","message":"Event object is invalid","errors":["Service key is the wrong
length (should be 32 characters)","Service key cannot contain non-alphanumeric characters."]}
At line:1 char:1
+ Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

Message is successfully captured in $error variable
```powershell
PS C:\Users\Administrator> $error[0].ErrorDetails.Message
{"status":"invalid event","message":"Event object is invalid","errors":["Service key is the wrong length (should be 32 c
haracters)","Service key cannot contain non-alphanumeric characters."]}
```

Actual behavior
---------------
```powershell
Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-15/create_e
vent.json -method Post -Body $body -ContentType "application/json"
Invoke-RestMethod : Response status code does not indicate success: 400 (Bad Request).
At line:1 char:1
+ Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: POST, R...ication/json
}:HttpRequestMessage) [Invoke-RestMethod], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

Details are even missing from the $error variable
```powershell
PS C:\Program Files\PowerShell\6.0.0.16> $error[0].ErrorDetails.Message
PS C:\Program Files\PowerShell\6.0.0.16>
``` 

Environment data
----------------

```powershell
PS C:\Program Files\PowerShell\6.0.0.16> $PSVersionTable

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.16
PSVersion                      6.0.0-alpha
PSEdition                      Core
SerializationVersion           1.1.0.1
CLRVersion
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
```

**Comment by nferrell** [comment] 2017-03-09 06:20
That's normal for Powershell on Windows. Can you try this to see if it catches the actual error? Some of the catch block may need to be reformed (if it even loads the StreamReader object)

```
try
    {
    Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-15/create_event.json -method Post -Body $body -ContentType "application/json"
    }
catch
    {
    $result = $_.Exception.Response.GetResponseStream()
    $reader = New-Object System.IO.StreamReader($result)
    $reader.BaseStream.Position = 0
    $reader.DiscardBufferedData()
    $reader.ReadToEnd()
    }
```

**Comment by jgigler** [comment] 2017-03-09 14:16
Sure thing @nferrell. Results are below

```powershell
PS C:\Program Files\PowerShell\6.0.0.16> try
>>     {
>>     Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-15/create_event.json -method Post -Body $body -ContentType "application/json
"
>>     }
>> catch
>>     {
>>     $result = $_.Exception.Response.GetResponseStream()
>>     $reader = New-Object System.IO.StreamReader($result)
>>     $reader.BaseStream.Position = 0
>>     $reader.DiscardBufferedData()
>>     $reader.ReadToEnd()
>>     }
You cannot call a method on a null-valued expression.
At line:7 char:5
+     $result = $_.Exception.Response.GetResponseStream()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by SteveL-MSFT** [comment] 2017-03-09 19:27
Looks like a dupe of https://github.com/PowerShell/PowerShell/issues/2193 which has already been fixed and should be in alpha.17 coming soon

```
PS /home/steve/repos/PowerShell> Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-15/create_event.json -Method Post -Body $obdy -ContentType "application/json"            
Invoke-RestMethod : {"status":"unrecognized object","message":"Event object format is 
unrecognized","errors":["JSON parse error"]}
At line:1 char:1
+ Invoke-RestMethod -Uri https://events.pagerduty.com/generic/2010-04-1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: POST, R...rShell/6.0.0
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Inv 
   okeRestMethodCommand

PS /home/steve/repos/PowerShell> $error[0].errordetails.message                                
{"status":"unrecognized object","message":"Event object format is unrecognized","errors":["JSON parse error"]}
```

**Closed by SteveL-MSFT** 2017-03-09 19:27 UTC
Labels: Area-Cmdlets-Utility, Issue-Enhancement, Resolution-Duplicate
