### ISSUE TITLE
Start-Process pwsh -UseNewEnvironment crashes the new pwsh process on startup

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#10812] opened 2019-10-16 23:07 UTC
# Steps to reproduce

```powershell
Start-Process pwsh -UseNewEnvironment
```

# Expected behavior

The child `pwsh` starts.

# Actual behavior

![image](https://user-images.githubusercontent.com/127450/66965586-089ac280-f02f-11e9-9872-7f71b1e6bb6f.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2019-10-17 01:00
Seems like a duplicate of #3545? 🙂

**Comment by mklement0** [comment] 2019-10-17 01:52
Please see #4671 and the associated PR in https://github.com/PowerShell/PowerShell/pull/10745

**Closed** 2019-10-18 04:00 UTC
Labels: Issue-Bug, Resolution-Duplicate
