### ISSUE TITLE
Version 7.3 arm32 and arm64 does not work on Linux

### ISSUE THREAD

**Issue by nerdatwork** [PowerShell/PowerShell#18629] opened 2022-11-21 15:32 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install arm32 or arm64 on Linux. 
Run the command `pwsh`

### Expected behavior

```console
Powershell command prompt is shown
```

### Actual behavior

```console
Command not found error message is shown
```

### Error details

```console
Version 7.2.7 works perfectly but 7.3 fails
```

### Environment data

```powershell
Debian Linux on Raspberry Pi 64 bit with 4GB ram
```

**Comment by 237dmitry** [comment] 2022-11-21 17:33
> Command not found error message is shown

Check if pwsh is executable
```
$ stat -c "%a %A" /opt/microsoft/powershell/7/pwsh
755 -rwxr-xr-x
```

**Comment by SteveL-MSFT** [comment] 2022-11-21 20:06
I think this is a dupe of https://github.com/PowerShell/PowerShell/issues/18495?

**Comment by rhubarb-geek-nz** [comment] 2022-11-24 03:51
I have built a tool to create arm32 and arm64 packages from the tar.gz which work on the Raspberry Pi 4.

https://github.com/rhubarb-geek-nz/PowerShell/tree/main/linux

https://github.com/rhubarb-geek-nz/PowerShell/releases/tag/7.3.0

```
$ dpkg-deb -c powershell_7.3.0-1.deb_arm64.deb | grep "/pwsh\$"
-rwxr-xr-x root/root    201272 2022-11-07 22:23 ./opt/microsoft/powershell/7/pwsh
lrwxrwxrwx root/root         0 2022-11-07 22:25 ./usr/bin/pwsh -> /opt/microsoft/powershell/7/pwsh
$ dpkg-deb -c powershell_7.3.0-1.deb_armhf.deb | grep "/pwsh\$"
-rwxr-xr-x root/root     61304 2022-11-07 22:23 ./opt/microsoft/powershell/7/pwsh
lrwxrwxrwx root/root         0 2022-11-07 22:25 ./usr/bin/pwsh -> /opt/microsoft/powershell/7/pwsh
```

**Comment by leoniDEV** [comment] 2023-01-08 22:42
I also have this issue but with PowerShell 7.4.0-preview.1 on a Raspberry Pi 4 with Alpine 3.17.0

**Closed** 2023-11-22 10:57 UTC
Labels: Area-Maintainers-Build, Needs-Triage, Resolution-No Activity
