### ISSUE TITLE
New-PSSession Unhandled Exception Ubuntu 16

### ISSUE THREAD

**Issue by jaredneedell** [PowerShell/PowerShell#1917] opened 2016-08-18 22:45 UTC
Steps to reproduce
------------------
Created PS-Credentials, create new-pssession

Expected behavior
-----------------
Suppose to initiated a new PS Session

Actual behavior
---------------
Program Crashes

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by kilasuit** [comment] 2016-08-18 23:51
I believe that this is currently as expected as detailed in the KNOWNISSUES.md file at https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md (though finding that file could be easier)

**Comment by BrendanThompson** [comment] 2016-08-19 00:58
It seems as though there will be a module released to allow for __PowerShell Remoting__ to work:

> # Remoting Support
>
>Client-side remoting from Linux is not supported with the initial package. This will be enabled shortly after the Alpha release by installing an additional package.

As listed in the [KNOWNISSUES.md](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md) document. Is there any timeframe around when that module will be released?

**Comment by Sum1n** [comment] 2016-08-20 04:13
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by bviktor** [comment] 2016-08-31 17:34
Ouch. ATM PowerShell remoting is also broken on Windows since the last update, so we're dead in the water lol.

**Comment by kilasuit** [comment] 2016-08-31 19:31
@bviktor @jaredneedell - Coming back to this have you run the Install-PowerShellRemoting.ps1 script in the C:\Program Files\PowerShell\6.0.0.9\ (assuming this is on Windows) as I've managed to get PSSessions from 6.0.0.9 to another machine which doesnt have 6.0.0.9 installed

**Comment by bviktor** [comment] 2016-09-02 15:48
@kilasuit dunno, in fact I've migrated my Windows comp to Linux for some testing so can't check it ATM. TIll then, fingers crossed for Linux PS Remoting :)

**Comment by andschwa** [comment] 2016-09-19 22:04
Per the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support), this is **not yet supported**.  Please follow the progress on the [PSRP on Linux repo](https://github.com/PowerShell/psl-omi-provider). Closing as duplicate of #942.

**Closed by andschwa** 2016-09-19 22:04 UTC
Labels: Area-Remoting
