### ISSUE TITLE
Work Around for multiple inheritance

### ISSUE THREAD

**Issue by Xpyder** [PowerShell/PowerShell#14892] opened 2021-02-23 20:50 UTC
## Summary of the new feature/enhancement
Currently powershell is unable to implement [Composition Over Inheritance](https://www.makeuseof.com/tag/basic-programming-principles/#composition-over-inheritance) because of a lack of support for custom "interfaces"

There is a way to get it to work, but it only works when running the code by hand, not in automated scripts

## Proposed technical implementation details (optional)
The issue with the workaround boils down to a problem in the parser error: InterfaceNameExpected
It fails to recognize that using Add-Type will add types, instead it incorrectly assumes the given type will not be available

I think we should either allow a keyword to override this error, or educate the parser on the usage of Add-Type

## Examples
I have included 3 examples:
A single file script that fails when run as a whole, but works if you manually run it line by line
A split that works, but is forced to have an incorrect dependency tree
A split that fails, because it's using a correct dependency tree

Note: The splits use dot sourcing, you'll need to adjust the paths to the appropriate folders on your computer
[Fail - Single File.zip](https://github.com/PowerShell/PowerShell/files/6031780/Fail.-.Single.File.zip)
[Success - Bad Dependancy layout.zip](https://github.com/PowerShell/PowerShell/files/6031781/Success.-.Bad.Dependancy.layout.zip)
[Fail - Good Dependency Layout.zip](https://github.com/PowerShell/PowerShell/files/6031782/Fail.-.Good.Dependency.Layout.zip)

## Related issues
https://github.com/PowerShell/PowerShell-RFC/pull/152
https://github.com/PowerShell/PowerShell/issues/2223

**Comment by Xpyder** [comment] 2021-02-23 20:52
I've included a readme.txt with each set giving a summary of what it's showing and why it's meaningful

**Comment by Xpyder** [comment] 2021-02-23 21:42
A possible work around for this might be to have the parser pause while the dot sources are run

so for example:
Main.ps1 parsing starts
Main.ps1 parsing pauses while dot sources are run
- Tests.ps1 parsing starts
- Tests.ps1 parsing pauses while dot sources are run
  - Classes.ps1 parsing starts
  - Classes.ps1 parsing pauses while dot sources are run
    - Interfaces.ps1 parsing starts
    - Add-Type is run
    - Interfaces.ps1 finishes
  - Classes.ps1 parsing continues
  - Parser correctly recognizes CustomInterface exists

**Comment by daxian-dbw** [comment] 2021-05-06 17:13
Language working group:
This issue is a duplicate of #2223. Allowing to define interface in powershell directly is the right way to go.

**Closed by daxian-dbw** 2021-05-06 17:13 UTC
Labels: Issue-Enhancement, Needs-Triage, WG-Language
