### ISSUE TITLE
Web cmdlets don't use system proxy settings

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#9533] opened 2019-05-04 16:02 UTC
# Steps to reproduce

Web cmdlets ignore system __automatic__ proxy settings (from Internet Explorer) and use explicit system proxy settings or proxy settings from parameter "-Proxy".

For reference https://github.com/PowerShell/PowerShell/issues/9495#issuecomment-489332978.

Perhaps a root of the issue is in CoreFX.

```powershell
Invoke-WebRequest ya.ru
```

# Expected behavior

```none
http response
```

# Actual behavior

```none
Invoke-WebRequest : No such host is known
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-rc.1
PSEdition                      Core
GitCommitId                    6.2.0-rc.1-198-g687697bc90879fe0162d08d409485632d9e79e79
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2019-05-04 20:48
I am not able to reproduce. If I set the proxy in IE, IWR uses the proxy by default. I tested this using manual settings in Internet Explorer, manual settings in the registry, and a proxy connection configuration script. This can all be tested using fiddler and adding a custom rule in the `OnBeforeRequest()` section

```none
if (oSession.clientIP == "::ffff:127.0.0.1") {
    oSession.Ignore();
}
```

When proxy settings are set, IWR/IRM requests will show up in fiddler. When the `-NoProxy` is used while the proxy settings are in place, requests are not show in fiddler. When the proxy is not set, requests are not shown in fiddler. 

The only method I have not tested is DHCP configure proxy (which I do not have the infra to test with).  If there is any issue with proxy detection, it might be there.

**Comment by iSazonov** [comment] 2019-05-06 05:50
Re-checked and the issue persists. With explicit "-Proxy" all works well.
Windows 10 Enterprise, 1809, 17763.437
- System proxy and IE settings is "Automatically detect settings"
- Use automatic configuration script

_If I set explicit proxy ("Use proxy for your LAN") all works well too._

**Comment by iSazonov** [comment] 2019-05-06 05:58
It seems it is only supported in  WinHttpHandler https://source.dot.net/#System.Net.Http/WinHttpHandler.cs,1eccc9f39c1b8d05,references

**Comment by markekraus** [comment] 2019-05-06 14:02
Yea, but we aren't using that one. we are using SocketsHttpHandler and this is where proxy detection occurs
 
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpWindowsProxy.cs 

I still cannot repro this. I have now tried on a second windows 10 system with the same results.

**Comment by iSazonov** [comment] 2019-05-06 16:18
@markekraus Could you share more information where we are using SocketsHttpHandler in the repo?

**Comment by markekraus** [comment] 2019-05-06 16:27
As of .NET Core 2.1 HttpClient uses the SocketsHttpHandler by default unless you change that behavior with configuration options (not present in our repo) or an environment variable:

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-2.2#remarks

**Comment by iSazonov** [comment] 2019-05-06 16:39
@markekraus THanks! I see there is some hops. I'll review config files on my computer (perhaps I disabled SocketsHttpHandler in json config and forgot).

**Comment by joeyaiello** [comment] 2020-07-30 23:09
@iSazonov are you still seeing this? Is there some status you can provide, or is it possibly fixed by .NET now?

**Comment by iSazonov** [comment] 2020-08-01 17:12
@joeyaiello I'd expect that will be resolved after #12675

**Comment by SteveL-MSFT** [comment] 2020-12-07 19:52
@iSazonov can you confirm if the original issue has been resolved by .NET 5?

**Comment by iSazonov** [comment] 2020-12-08 10:25
@SteveL-MSFT As far as I remember, #12675 should fix the situation. If you want a better adaptation in enterprises and plan #12675 then I could continue this work.

**Closed** 2022-10-04 07:03 UTC
Labels: Issue-Discussion, WG-Cmdlets-Utility
