### ISSUE TITLE
DSC tests should be skipped on Ubuntu 20.04, due to libmi incompatibility

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13602] opened 2020-09-08 21:48 UTC
Testing on Ubuntu 20.04 should skip DSC tests, since Ubuntu 20.04's libmi version isn't compatible.

One of the test errors:

```
Expected an exception, with FullyQualifiedErrorId 'Microsoft.PowerShell.Commands.WriteErrorException,CheckResourceFound' to be thrown, but the FullyQualifiedErrorId was 'DllNotFoundException,Get-DscResource'. from /opt/microsoft/powershell/7-preview/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1:4681 char:19
+     $resource = @(Get-DscResource @getArguments -ErrorAction stop)
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Stack trace:

```
at <ScriptBlock>, /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.Tests.ps1: line 527
527:                 Should -Throw -ErrorId 'Microsoft.PowerShell.Commands.WriteErrorException,CheckResourceFound'
```

**Comment by jborean93** [comment] 2020-09-09 20:04
@iSazonov not sure there's much I can add to this, I haven't enabled a Debian 11 target yet because that version isn't out yet. But I would guess that if you tried to include the `libmi` binary that PowerShell distributes it would fail on Debian 11 because it is compiled against OpenSSL 1.0.2 which newer distros won't ship.

**Comment by gaelcolas** [comment] 2021-05-21 20:44
Issue #14421 seems to be a duplicate of this one?

**Closed** 2023-11-23 11:26 UTC
Labels: Issue-Bug, WG-Quality-Test, Resolution-No Activity
