### ISSUE TITLE
sudo command does not work in remote session to Linux machine

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#1527] opened 2016-07-26 22:44 UTC
## Steps to reproduce
1.  Build and setup SSH based remoting (see docs) on a Linux machine
2.  Start an interactive  remote session to the same machine
    Enter-PSSession -HostName <HostName> -UserName <UserName>
    [<HostName>] C:> sudo ls /proc/powershell
## Expected behavior

sudo command to run in remote interactive session.
## Actual behavior

```
sudo : sudo: no tty present and no askpass program specified
    + CategoryInfo          : NotSpecified: (sudo: no tty pr...ogram specified:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
## Environment data

Name                           Value

---

PSVersion                      5.1.10032.0
PSEdition                      PowerShellCore
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-392-ga5b5dc576b8006c0d0a83a5c538f382d9fa65dc6
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by TylerLeonhardt** [comment] 2020-08-07 15:52
Hit this trying to implement a way to run the Azure Arc for Server agent (which requires `sudo`) over a PSRP session... It'd be really great to have this.

**Comment by SteveL-MSFT** [comment] 2020-08-07 15:54
https://www.shell-tips.com/linux/sudo-no-tty-present-and-no-askpass-program-specified/

**Comment by awakecoding** [comment] 2020-10-26 16:09
@SteveL-MSFT @TylerLeonhardt I see this issue has been open for many years now, probably because there is no easy fix. This is pretty much the only major limitation of pwsh on Linux to make it a viable shell alternative. Is this ticket the best place to discuss actively working towards making it happen?

I suppose one approach could be to make a special "pwsh-askpass" that could really just be "pwsh" launched in "--askpass" mode, where it would implement a regular askpass interactive prompt. The twist would be that we'd detect the parent pwsh shell, and use one of the PowerShell mechanisms for IPC, allowing us to somehow prompt interactively in the PowerShell client side.

Bonus points for properly delegating credentials over PSRP such that they never appear in logs anywhere (actually, that should be a requirement, but an intermediate solution would be acceptable). What do you think?

**Comment by TylerLeonhardt** [comment] 2020-10-28 00:44
Conceptually that makes sense to me. Assuming a `pwsh-askpass` can connect to the parent `pwsh` where the actual remote host is, we'd maybe do something similar to what `Get-Credential` or `Read-Host -AsSecureString` does:

![image](https://user-images.githubusercontent.com/2644648/97376932-f0819400-187b-11eb-9b66-d75f0053993f.png)

**Comment by awakecoding** [comment] 2020-10-28 12:58
@TylerLeonhardt do you think this would require an improvement to the PowerShell remoting protocol? I know MS-PSRP treats credentials differently when transferring them to the remote system, maybe all we need is to use a secure string to benefit from that. What you suggested looks perfectly fine in terms of usability at least for a V1 (right now it is just plain unusable).

For a V2, I wonder if we couldn't go one step further and make it possible to override the client-side "askpass" implementation, to allow PowerShell clients to either show a GUI prompt, or even make a special module that would grab the username+password from one of the new secret management modules.

Anyway, back to just getting a V1 done for now. Here is my understanding:
- an 'askpass' program just prompts for the password, and outputs it to stdout, which is captured by the parent process
- "pwsh-askpass" could detect its parent pwsh process id, and then somehow attach to a runspace inside that parent
- once attached to the parent pwsh, find a way to trigger the dynamic password prompt inside the current shell (is it possible?)
- when the password prompt completes, pwsh-askpass outputs the password to stdout, and everybody is happy.

I'm thinking that one could literally try making a PoC using a single PowerShell script called "pwsh-askpass" that you make executable. One quicky and dirty way to get started would be to make it output a hardcoded password just to see if the plumbing is done right at the "askpass" level. Once that is confirmed, we can work towards prompting the password for real.

As for attaching to the parent pwsh runspace, I don't know if it is feasible the way I described, but this presentation on PowerShell Remoting Internals does show a lot of interesting things that could be used as a starting point: https://www.youtube.com/watch?v=MyQGk29w-BM&t=780s

**Comment by TylerLeonhardt** [comment] 2020-10-28 14:16
Yep this all sounds great to me. In PowerShell, you can get the parent process by doing:

```pwsh
(Get-Process $PID).Parent
```

We'd probably continue grabbing `.Parent` until we find another PowerShell... Then use `Enter-PSHostProcess` to enter said parent.

That's when it gets interesting. I don't know how to trigger that secure string prompt but it's possible that all you need to do is the `Read-Host` without having to go into another runspace...



.... This actually could work.

**Comment by PaulHigin** [comment] 2020-10-28 21:49
@awakecoding, @TylerLeonhardt  thanks for reviving this.  What is discussed here sounds possible.  I too was thinking about using askpass to provide the password, but I am not very knowledgeable about it.  I suspect the remoting protocol (PSRP) will have to be updated as mentioned above.

**Comment by TylerLeonhardt** [comment] 2020-10-28 22:34
So I fiddled with this a tad...

```
❯❯❯ Enter-PSSession $windows
[tyleonha-desk1.redmond.corp.microsoft.com]: PS C:\Users\tyleonha\Documents> $rs = [runspacefactory]::CreateRunspace($Host)
[tyleonha-desk1.redmond.corp.microsoft.com]: PS C:\Users\tyleonha\Documents> $rs.Open()
[tyleonha-desk1.redmond.corp.microsoft.com]: PS C:\Users\tyleonha\Documents> $ps = [PowerShell]::Create($rs)
[tyleonha-desk1.redmond.corp.microsoft.com]: PS C:\Users\tyleonha\Documents> $ps.AddCommand("Read-Host").AddParameter("AsSecureString").Invoke()
WARNING: A script or application on the remote computer TYLEONHA-DESK1.REDMOND.CORP.MICROSOFT.COM is asking to read a line securely. Enter sensitive information, such as your credentials, only if you trust the remote computer and the application or script that is requesting it.
****
System.Security.SecureString
[tyleonha-desk1.redmond.corp.microsoft.com]: PS C:\Users\tyleonha\Documents>
```

Looks like as long as the _other_ runspace has the RemoteHost, then it might work...

```
$host.UI.ReadLineAsSecureString()
```

is also an option...

The outstanding questions I have are:

* Can another runspace get a reference to the `PSHost` object we need?
* Is it thread safe?

**Comment by awakecoding** [comment] 2020-10-29 01:36
I did some further experimentation and discussed it with some of the people in #powershell-help. For the first step, which is to get sudo to use our own askpass program, it turns out that you need to do two things:

- Add '-A' or "--askpass" as an argument to sudo, which is often done using an alias in bash.
- Set the SUDO_ASKPASS variable (only works with -A), but this can also be set in sudo.conf

I do not yet know of a way to make it accept our own askpass program without adding the -A argument, but I would consider this a minor issue for now that we can solve later. The end goal is to make it without having to modify scripts calling sudo directly. As a matter of fact, I came up with a quick and dirty solution to work around it for now, using a fake "sudo" program that I added at the beginning of PATH such that it would get picked up instead of the real one.

I created a directory called "/yolo" and placed two simple scripts in there:
- simple 'askpass' script that echoes my password to stdout
- simple 'sudo' script that sets SUDO_ASKPASS and calls the real sudo, adding -A

Here is what it looks like:

```
export PATH=/yolo:$PATH
wayk@pwsh-demo:~$ sudo whoami
root
wayk@pwsh-demo:~$ cat /yolo/sudo
#!/bin/sh
export SUDO_ASKPASS=/yolo/askpass
/usr/bin/sudo -A -n $@
wayk@pwsh-demo:~$ cat /yolo/askpass 
#!/bin/sh
echo "password"
```

I consider the first part of the PoC (finding a way to inject our own askpass program that gets picked up by sudo) completed with the above, moving on to getting the askpass program to prompt inside the parent PowerShell runspace. We can come back to finding better, less hackish ways to achieve the same result afterwards.

**Comment by jborean93** [comment] 2020-10-29 02:50
Just to add some more info to the conversation here is a quick and dirty script that @SeeminglyScience wrote (slightly tweaked)

```powershell
#!/usr/bin/env pwsh

# Parent is sudo, grandparent is the pwsh process
$parentPid = (Get-Process -Id $pid).Parent.Parent.Id

$ci = [Management.Automation.Runspaces.NamedPipeConnectionInfo]::new($parentPid)
$rs = $ps = $null
try {
    $rs = [runspacefactory]::CreateRunspace($ci)
    $rs.Open()
    $ps = [powershell]::Create()
    $ps.Runspace = $rs
    $null = $ps.AddScript{
        $rs = Get-Runspace 1
        $remoteHost = $rs.GetType().GetProperty('Host', 60).GetValue($rs)
        $remoteHost.UI.ReadLine()
    }

    return $ps.Invoke()
} finally {
    if ($null -ne $ps) {
        $ps.Dispose()
    }

    if ($null -ne $rs) {
        $rs.Dispose()
    }
}
```

Making that executable will allow `sudo` to prompt the user for the password and will work over a PSRemoting session. While this "works" it is not a workable solution because:

* `ReadLine()` echos the input characters to the console exposing your password
* Because the user input is read as a string then the data transferred across the wire is the plaintext value
    * The transport may be encrypted but if using a recording device you have now exposed the password
* There's no indication that the user is being prompted, should be solved by just writing a message to the host beforehand, might be something that the askpass interface provides
    * I think the process args may contain the prompt message which would be helpful
* It access' the PSHost through an internal property, would be nice to have a public way of getting this

The last 2 issues aren't the end of the world and should be easily fixed but the first 2 are problematic. I was hoping to utilise secure strings as PSRP has a really nice mechanism to exchange the values themselves. Unfortunately it seems like the secure string session key exchange in PSRP does not work on Linux so I can't call [ReadLineAsSecureString](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.readlineassecurestring?view=powershellsdk-7.0.0).

Using secure strings across PSRemoting should be achievable cross platform as it doesn't rely on DPAPI but rather an ephemeral 16 byte key that's encrypted using an RSA public key. All these things should be achievable in OpenSSL so hopefully it could be implemented one day.

Just for further info on secure strings through PSRemoting this is the error I get when trying to copy one to a remote session

```powershell
$cred = Get-Credential
Invoke-Command hostname -ScriptBlock { $using:cred }

OpenError: 


$Error[0] | Select *

PSMessageDetails      : 
Exception             : System.Management.Automation.Internal.PSCryptoException
                           at System.Management.Automation.Internal.PSCryptoNativeUtils.CryptAcquireContext(PSSafeCryptProvHandle& phProv, 
                        String szContainer, String szProvider, UInt32 dwProvType, UInt32 dwFlags)
                           at System.Management.Automation.Internal.PSRSACryptoServiceProvider.GenerateKeyPair()
                           at System.Management.Automation.Internal.PSRemotingCryptoHelperClient.ExportLocalPublicKey(String& publicKeyAsString)
                           at System.Management.Automation.Remoting.ClientRemoteSessionImpl.StartKeyExchange()
TargetObject          : server2019.domain.test
CategoryInfo          : OpenError: (server2019.domain.test:String) [], PSCryptoException
FullyQualifiedErrorId : PSSessionStateBroken
ErrorDetails          : 
InvocationInfo        : 
ScriptStackTrace      : 
PipelineIterationInfo : {}


$error[0].Exception | Select *

TargetSite     : Boolean CryptAcquireContext(System.Management.Automation.Internal.PSSafeCryptProvHandle ByRef, System.String, System.String, 
                 UInt32, UInt32)
StackTrace     :    at System.Management.Automation.Internal.PSCryptoNativeUtils.CryptAcquireContext(PSSafeCryptProvHandle& phProv, String 
                 szContainer, String szProvider, UInt32 dwProvType, UInt32 dwFlags)
                    at System.Management.Automation.Internal.PSRSACryptoServiceProvider.GenerateKeyPair()
                    at System.Management.Automation.Internal.PSRemotingCryptoHelperClient.ExportLocalPublicKey(String& publicKeyAsString)
                    at System.Management.Automation.Remoting.ClientRemoteSessionImpl.StartKeyExchange()
Message        : 
Data           : {}
InnerException : 
HelpLink       : 
Source         : System.Management.Automation
HResult        : -2146233088
```

**Comment by jborean93** [comment] 2020-10-29 03:09
Looks like https://github.com/PowerShell/PowerShell/pull/11185 has fixed the SecureString issue making it cross platform. I still need to test the latest preview to make sure but it definitely seems to be possible.

**Comment by PaulHigin** [comment] 2020-10-29 16:00
Thanks for looking into this.  Yes, PowerShell remoting does now support passing SecureString objects over all platforms, but unfortunately was only added to 7.1+ versions.

I am not worried about prompting for sudo password over a remote session, that can be handled with remote host calls, and probably an update to the protocol (PSRP).  My main concern was how to interface with sudo, and it looks like @awakecoding 'AskPass' is the mechanism to use.  It would be nice if there was some sort of API hook, but the above PoC may be workable.

**Comment by TylerLeonhardt** [comment] 2020-11-05 21:00
![make it so](https://media.giphy.com/media/bKnEnd65zqxfq/giphy.gif)

Anyone interested in prototyping this?

**Comment by jborean93** [comment] 2020-11-26 01:48
Slight bump, since pwsh 7.1 is out I've tweaked the script for `SUDO_ASKPASS` to use a secure string

```pwsh
#!/usr/bin/env pwsh

# Parent is sudo, grandparent is the pwsh process
$parentPid = (Get-Process -Id $pid).Parent.Parent.Id

# First arg is the prompt from sudo itself
$sudoPrompt = $args[0]

$ci = [Management.Automation.Runspaces.NamedPipeConnectionInfo]::new($parentPid)
$rs = $ps = $null
try {

    $rs = [runspacefactory]::CreateRunspace($ci)
    $rs.Open()
    $ps = [powershell]::Create()
    $ps.Runspace = $rs
    $null = $ps.AddScript({
        $rs = Get-Runspace 1
        $remoteHost = $rs.GetType().GetProperty('Host', 60).GetValue($rs)
        $remoteHost.UI.Write($args[0])
        $remoteHost.UI.ReadLineAsSecureString()
    }).AddArgument($sudoPrompt)

    $ssValue = $ps.Invoke()[0]

    $pass = [PSCredential]::new('noop', $ssValue).GetNetworkCredential().Password
    return $pass
} finally {
    if ($null -ne $ps) {
        $ps.Dispose()
    }

    if ($null -ne $rs) {
        $rs.Dispose()
    }
}
```

Connecting over SSH PSRemoting this is what happens

```
[192.168.0.66]: PS /home/jborean> $env:SUDO_ASKPASS = '/tmp/askpass.ps1'
[192.168.0.66]: PS /home/jborean> sudo -A whoami
[sudo] password for jborean: ********
root
```

We can see that the actual sudo prompt appears and the password that I typed in is hidden behind `*` as the remote Host UI call is `ReadLineAsSecureString`. This solves the more serious problems I had with the implementation but there are a few other things that should be solved

1. The current script logic just get's the pid of the grandparent process.

This is fine if `sudo` was called from `pwsh` directly, but say you are running a script which calls sudo then this won't work. We would need to work up the process tree until it comes to the PSRemoting `pwsh` process. In reality a less brittle way would be to smuggle in that information into the `askpass.ps1` script, maybe through an env var, so we aren't 2nd guessing ourselves

2. You need to call `sudo` with `-A`

Without `-A` then `sudo` won't call the askpass script defined in the env var. Existing scripts would need to be modified We could find a way to make a custom `sudo` script that just recalls `sudo -A` higher in the PATH priority but now `sudo` called with an absolute path won't work.

Maybe someone knows a `sudo` configuration that sets `-A` as the default

3. The Runspace ID is hardcoded to 1

This works fine for a normal `Enter-PSSession` but we probably want to smuggle in the actual Runspace GUID so we use the correct attached PSHost. This would probably involve some more env vars that need to be smuggled in like the pwsh PID.

There are some UX concerns I have as well, namely

1. This script needs to be on the remote host somewhere and set as executable
2. The user needs to set the `SUDO_ASKPASS` env var
3. Probably some more friendly error messages for bad scenarios in the `askpass.ps1`. Luckily exceptions and errors raised in the script appear in the output normally
3. Maybe `sudo -A` configuration needs to tweaking by the user

In my mind this should all be transparent to the end user but even that is fraught with danger.

**Comment by jborean93** [comment] 2020-11-26 02:05
Oh and because feedback on failures is also important, here is what happens when you put in the wrong password

```
[192.168.0.66]: PS /home/jborean> sudo -A whoami
[sudo] password for jborean: ****
Sorry, try again.
[sudo] password for jborean:
```

Also when you press CTRL+C

```
[192.168.0.66]: PS /home/jborean> sudo -A whoami
[sudo] password for jborean: ****
Sorry, try again.
[sudo] password for jborean: no password was provided
sudo: 1 incorrect password attempt
```

**Comment by TylerLeonhardt** [comment] 2020-11-29 08:17
@jborean93 this is awesome. This completely proves that this solution is the right way forward.

My thinking on your UX concerns... Most of the concerns can be solved with a module + overriding `sudo` with a `sudo` function...although it feels weird.

Theoretically a user could install a module (called `pseudo`? 😅). that module has a psm1 that contains a single exported function called `sudo`. 

> This script needs to be on the remote host somewhere and set as executable

Module installation is simple, and in the psm1 the call to chmod to make the file executable could be done (chmod might require sudo in some cases...)

> The user needs to set the SUDO_ASKPASS env var

Again in the psm1 we can set this env var.

> In reality a less brittle way would be to smuggle in that information into the askpass.ps1 script, maybe through an env var, so we aren't 2nd guessing ourselves

We could do this in the `sudo` function. Set a `POWERSHELL_PID_FOR_SUDO` env var before calling the sudo exe.

> In reality a less brittle way would be to smuggle in that information into the askpass.ps1 script, maybe through an env var, so we aren't 2nd guessing ourselves

Same deal. A `POWERSHELL_RUNSPACE_FOR_SUDO` env var. These should get cleaned up after invocation... Though, tbh... This is not a very important work item. Runspace 1 should exist in most of not all scenarios.

> We have to use reflection to get the Host

A PowerShell API feature request. This should be a separate issue... But I totally agree.

@jborean93 interested in throwing a module up on the Gallery for this?

**Comment by jborean93** [comment] 2020-11-29 20:22
> Most of the concerns can be solved with a module + overriding sudo with a sudo function...although it feels weird.

While it does still help in these scenarios I think this request goes beyond just calling `sudo` in PowerShell itself. If you want just a generic function that invokes the command with sudo this will definitely work but there are other ways to pass in a password to `sudo` that doesn't involve creating a file, e.g. `'password' | sudo -S @arguments`.

What I feel like this example solves is a way to automatically get the prompt from `sudo` regardless of how it's called back to the PSHost. That allows me to run a bash script that may contains `sudo my_command` like `./my_script.sh` in PowerShell and it would work like it does through other shells/ssh. For this to occur today you would have to have a user call a script like the below to set up the environment but it would be nice if this wasn't needed (although I don't see how based on how PSRP works today).

```powershell
Function Enable-SudoPrompt {
    [CmdletBinding()]
    param()

    $tempPath = [IO.Path]::GetTempFileName()
    
    # Probably a better way but just for testing
    $cleanupAction = [ScriptBlock]::Create("Remove-Item -Path '$tempPath'")
    $null = Register-EngineEvent -SourceIdentifier PowerShell.Exiting -Action $cleanupAction
    
    $askPassScript = '@
#!/usr/bin/env pwsh

# Parent is sudo, grandparent is the pwsh process
$parentPid = (Get-Process -Id {0}).Parent.Parent.Id

# First arg is the prompt from sudo itself
$sudoPrompt = $args[0]

$ci = [Management.Automation.Runspaces.NamedPipeConnectionInfo]::new($parentPid)
$rs = $ps = $null
try {

    $rs = [runspacefactory]::CreateRunspace($ci)
    $rs.Open()
    $ps = [powershell]::Create()
    $ps.Runspace = $rs
    $null = $ps.AddScript({
        $rs = Get-Runspace -InstanceId '{1}'
        $remoteHost = $rs.GetType().GetProperty('Host', 60).GetValue($rs)
        $remoteHost.UI.Write($args[0])
        $remoteHost.UI.ReadLineAsSecureString()
    }).AddArgument($sudoPrompt)

    $output = $ps.Invoke()

    if ($output) {
        $pass = [PSCredential]::new('noop', $output[0]).GetNetworkCredential().Password
        return $pass
    }
} finally {
    if ($null -ne $ps) {
        $ps.Dispose()
    }

    if ($null -ne $rs) {
        $rs.Dispose()
    }
}
'@ -f ($pid, [Runspace]::DefaultRunspace.InstanceId)

    chmod +x $tempPath
    $env:SUDO_ASKPASS = $tempPath
}
```

It still needs to solve the fact that you need to call `sudo` with `sudo -A` but it at least sets up the environment properly.

**Comment by awakecoding** [comment] 2020-11-29 22:20
@TylerLeonhardt @jborean93 a module could be suitable to get something with older versions of PowerShell, but I think we should consider a built-in solution that comes with PowerShell, and not externally distributed or added on top.

@jborean93 is correct when he says that wrapping the command inside PowerShell would only work when calling "sudo" from PowerShell and wouldn't fix the issue of non-PowerShell scripts or native programs that call sudo directly. Of course, there is the issue of existing scripts that call "sudo" without "sudo -A", but this is still something that can be worked with. For instance, you can call sudo a first time to get prompted and run the unmodified script, the second sudo won't trigger the prompt because of the sudo cache, etc. We can also look into adding the sudo alias in bash, or look into advanced sudo configuration options. In any case, if sudo -A works, it would be a zillion times better than the current state of things.

As for wrapping and cleaning up afterwards, let's just look at the alternative: a guaranteed broken sudo when called from a PowerShell remoting session. I say we should automatically modify the environment to set SUDO_ASKPASS to point to a "pwsh-askpass" program in the PowerShell remoting server. As for the pwsh-askpass program itself, rather than distribute it as an external module, it should probably be part of the distributed PowerShell files.

The first issue we face is that SUDO_ASKPASS works with an executable, and not an executable with a parameter. The ideal solution would be to add an "-AskPass" parameter to the pwsh executable, such that the automatic SUDO_ASKPASS injection would point to the same PowerShell executable as the current PowerShell server. Here's the trick to make it work: just make a "pwsh-askpass" relative symbolic link to make it point to its corresponding "pwsh" executable. In the pwsh executable, all we would need to is inspect argv[0] which contains the executable name. When called through the pwsh-askpass symlink, argv[0] would contain "pwsh-askpass" instead of pwsh, making it easy to run pwsh as if it was called with the -AskPass parameter. I should note that PowerShell $arg[0] is the first parameter is not the executable, but in the pwsh executable I am sure we can extract the same information as it is normally available in C.

SUDO_ASKPASS is not something that is set in most cases, so I suggest we set it automatically unless it is already set, making it possible to override through some global system configuration.

As for helper environment variables to let pwsh-askpass find the parent pwsh to attach to, PowerShell should simply be modified to create and set those environment variables by default. We should take special care of setting the PID for the right process, which I understand should be the one containing the PowerShell remoting server, not some nested pwsh session inside a PowerShell remoting server.

I suggest the following names for the automatic environment variables to set that would be used by pwsh-askpass:
PWSH_ASKPASS_PROCESS_ID
PWSH_ASKPASS_RUNSPACE_ID

Also, even if we can make a working pwsh-askpass script, I suggest we drop the .ps1 extension because we don't necessarily wish it to remain a script. All you need is to make it executable and add the following line at the beginning:

#!/usr/bin/env pwsh

However, I would rather have pwsh-askpass point to pwsh -AskPass, and implement askpass inside pwsh. Maybe we could plan this for PowerShell 7.2, and make a simple pwsh-askpass script that does best effort detection for PWSH_ASKPASS_PROCESS_ID and PWSH_ASKPASS_RUNSPACE_ID.  The script could be installed globally on the system, and modifications to the OpenSSH server configuration could be used to set SUDO_ASKPASS in the PowerShell remoting environment by default. This way we have something that works right now, and it would become a built-in feature in PowerShell 7.2.

**Comment by TylerLeonhardt** [comment] 2020-11-29 23:17
Like a lot of things we consider to be the main package, if we _can_ have it on the Gallery first, that is the first step.

Actually, the perfect model for such a function would be:
https://www.powershellgallery.com/packages/Microsoft.PowerShell.RemotingTools/0.1.0

@SteveL-MSFT @PaulHigin where is that repo?

**Comment by awakecoding** [comment] 2020-11-30 00:23
@TylerLeonhardt totally agree, I think we should make it available as a separate component in a first step, then consider including it in the main package. On the long run, I do think this is something that should be built-in to PowerShell, it looks a bit odd to have to install a separate package to get sudo to work in a PowerShell remoting session, which is something most users would expect to work out of the box.

I suggest we make a first pwsh-askpass executable as a PowerShell script that would do best-effort detection of PWSH_ASKPASS_PROCESS_ID and PWSH_ASKPASS_RUNSPACE_ID when not available. For my own usage I think I would just "install" it manually in /usr/bin/pwsh-askpass and set SUDO_ASKPASS to 'pwsh-askpass' in my OpenSSH server environment. Once this script-based pwsh-askpass solution has had the chance of used by some people, we could plan for possible inclusion in the main pwsh executable.

Do this sound like a good plan?

**Comment by TylerLeonhardt** [comment] 2020-11-30 22:36
@jborean93 do you want to add what you have to this module?

https://github.com/PowerShell/Modules/tree/master/Modules/Microsoft.PowerShell.RemotingTools

Then we can start getting feedback.

**Comment by thukk** [comment] 2020-12-02 03:31
> Thanks for looking into this. Yes, PowerShell remoting does now support passing SecureString objects over all platforms, but unfortunately was only added to 7.1+ versions.
> 
> I am not worried about prompting for sudo password over a remote session, that can be handled with remote host calls, and probably an update to the protocol (PSRP). My main concern was how to interface with sudo, and it looks like @awakecoding 'AskPass' is the mechanism to use. It would be nice if there was some sort of API hook, but the above PoC may be workable.

So, Since PS 7.0.3 is LTS (support lasts longer than 7.1), how can those of us that use/require an LTS version utilize sudo in a PSSession?  Since security is of utmost importance, the script above that utilizes `Readline()` is not preferred.

**Comment by TylerLeonhardt** [comment] 2020-12-02 05:49
> the script above that utilizes Readline() is not preferred.

Why is that not preferred?

**Comment by jborean93** [comment] 2020-12-02 06:13
@TylerLeonhardt 7.1+ can use `ReadLineAsSecureString` which means the inputted characters are not echo'd back in the PSHost. Unfortunately older versions don't support secure strings over PSRemoting on non-Windows hosts so 7.0 is stuck with just `ReadLine`.

**Comment by TylerLeonhardt** [comment] 2020-12-02 06:22
Ahh that's right. I forgot about that fix. Also it's too complex to backport to 7.0 so unfortunately you are out of luck. Maybe we could "fake it" with reading characters one at a time and using some vt100 to clear the character typed... But that sounds so painful.

**Comment by jborean93** [comment] 2020-12-02 06:26
The other issue is that the types of calls you can make over a remote PSHost is limited. You are limited to just the ones listed at https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-psrp/ddd2a4d1-797d-4d73-8372-7a77a62fb204. Any of the methods that return a secure string will be out of luck with 7.0 :( Maybe you could have some sort of complex manual buffer manager at the RawUI layer but honestly I have no desire to investigate this :)

For people on 7.0 they could just do `'my password' | sudo -s something` in PowerShell to cache your sudo credential so subsequent calls don't prompt you for it. Not ideal but it's what we have to work with.

**Comment by thukk** [comment] 2020-12-02 13:08
> For people on 7.0 they could just do `'my password' | sudo -s something` in PowerShell to cache your sudo credential so subsequent calls don't prompt you for it. Not ideal but it's what we have to work with.

Which would honestly be fine, *if* the following worked (which it doesn't).
```
$creds = Get-Credential
$session = New-PSSession -hostname Workstation1 -Username foo -SSHTransport
Invoke-Command -Session $session {param($creds) Invoke-Expression "echo $creds.password | sudo -S whoami"} -Argumentlist $creds
```

In 7.0, I cannot find a single way to pass secure strings to a PSSession, so scripting a `sudo` command is not possible.  That sound about right?

**Comment by jborean93** [comment] 2020-12-02 18:45
> Which would honestly be fine, if the following worked (which it doesn't).

That's because you are trying to send a secure string across which doesn't work on non-Windows hosts until 7.1. If the password was plaintext like so then it would work

```powershell
$creds = Get-Credential
$sudoPass = $creds.GetNetworkCredential().Password
$session = New-PSSession -hostname Workstation1 -Username foo -SSHTransport

Invoke-Command -Session $session {
    param(
        [String]
        $SudoPass
    )

    $null = $SudoPass | sudo -S whoami
    if ($LastExitCode -ne 0) {
        Write-Error -Message "Failed to cache sudo password"
        return
    }
} -Argumentlist $sudoPass
```

Note this is not tested and it may require some better logic to check for failures but it should work. I will agree it's also not good to send passwords as plaintext across the wire but at least SSH encrypts the traffic. There's nothing that can be done about this unless you are on 7.1+ as we've mentioned. Even then on 7.1+ the SecureString will not be encrypted in memory on the remote process due to how SecureStrings work on non-Windows hosts. The 2 benefits 7.1 provides are:

* SecureStrings are encrypted with a unique session key when traversing the wire. If someone was able to decrypt or monitor the plaintext SSH packets then the password will still be encrypted
* You can use the PSHost SecureString prompts as we've mentioned before

It's up to the PowerShell team to backport the changes in https://github.com/PowerShell/PowerShell/pull/11185. I have no idea what the general policy is for this for this project so I can't really comment on it more.

Also your example had `Invoke-Expression`, that is not needed at all. You typically don't need to use iex to call a native binary as all iex does is runs the specified string as a PowerShell command which you already have.

**Comment by TylerLeonhardt** [comment] 2020-12-02 20:18
@jborean93 in your example you do:

```
​# Parent is sudo, grandparent is the pwsh process​
​$parentPid = (Get-Process -Id {0}).Parent.Parent.Id
```
Where that `{0}` will be formatted as `$pid` of the process that called this cmdlet.

Do you still need to do the `.Parent.Parent.Id`?

**Comment by jborean93** [comment] 2020-12-02 20:49
Good catch, that should just be `$parentPid = {0}` or `$parentPid = $env:SOMETHING`. Was a leftover when I was just getting the grandparent PID which wouldn't work in all situations.

**Comment by TylerLeonhardt** [comment] 2020-12-02 21:26
@jborean93 do you have interest in contributing that cmdlet to the [RemotingTools module](https://github.com/PowerShell/Modules/tree/master/Modules/Microsoft.PowerShell.RemotingTools) so we can start getting validation? Your own separate module would also be totally cool.

**Comment by jborean93** [comment] 2020-12-02 21:48
I would be interested but I don't have any spare time in the current week. I would probably only be able to work on it properly in about 2 weeks or so. People are more than welcome to take what I have and work on it if I'm taking too long :).

**Comment by IanEMartin** [comment] 2021-07-09 16:29
Haven't seen any movement on this but see it as still open.  I just started trying to manage *nix systems with remote PS sessions and this is a definite blocker.

**Comment by mcx808** [comment] 2023-11-16 13:42
@PaulHigin despite the lack of updates to this issue, I just tested again on pwsh 7.3.9 running on Debian 11 & 12. Still doesn't work when an interactive password is required but it does work with passwordless sudo, and you can workaround by piping a securestring into the sudo command (I don't remember if this was possible before).

example

```
[admin@test-deb11]: PS /home/admin> $pw = Read-Host -AsSecureString
WARNING: A script or application on the remote computer TEST-DEB11 is asking to read a line securely. Enter sensitive information, such as your credentials, only if you trust the remote computer and the application or script that is requesting it.
*******
[admin@test-deb11]: PS /home/admin> $pw | ConvertFrom-SecureString -AsPlainText | sudo -S cat /proc/cpuinfo
```

**Closed** 2023-11-24 00:44 UTC
Labels: WG-Remoting, Size-MultipleWeeks, Resolution-No Activity

**Comment by soroshsabz** [comment] 2026-06-28 14:15
Why is closed? is it actually done or not?

@SteveL-MSFT @jborean93
