### ISSUE TITLE
SkipCACheck/SkipCNCheck New-PSSession on non-Windows test failing on Debian 10

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#11128] opened 2019-11-19 23:51 UTC
SkipCACheck and SkipCNCheck PSSession options are required for New-PSSession on non-Windows platforms.Verifies expected error when SkipCACheck option is missing

Failed 3h ago on 6dcfecda2e0b
Duration0:00:00.037
Failing buildReleaseAutomationTest-114865
OwnerPaul Higinbotham

Debug
Work items
Attachments
History

Error message
Expected 825, but got 0.

Stack trace
at <ScriptBlock>, /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/engine/Remoting/PSSession.Tests.ps1: line 82
82:         $er.Exception.ErrorCode | Should -Be $expectedErrorCode

https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=117686&view=ms.vss-test-web.build-test-results-tab&runId=1096282&resultId=101189&paneView=debug

# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none

```

**Comment by SteveL-MSFT** [comment] 2019-12-18 01:05
The problem is that it's looking for libpsrpclient.so in $pshome/linux-x64 folder.  Even after copying it there, it has some dependencies and the symlinks are going to the wrong version on the OS.

**Comment by SteveL-MSFT** [comment] 2019-12-18 01:06
Dupe of https://github.com/PowerShell/PowerShell/issues/11128

**Closed by SteveL-MSFT** 2019-12-18 01:06 UTC
Labels: Area-Cmdlets-Core, Issue-Question, Resolution-Duplicate
