### ISSUE TITLE
Copy & paste is not working properly on Windows 10

### ISSUE THREAD

**Issue by loxal** [PowerShell/PowerShell#4294] opened 2017-07-19 08:15 UTC
I need to *right click* to paste which everything but aligned with everything else. On Mac's terminal you can just "Cmd + V" everywhere.

**Comment by mklement0** [comment] 2017-07-19 12:27
Good find.

It looks like a [PSReadLine](https://github.com/lzybkr/PSReadLine) issue.

You can verify this by running `Remove-Module PSReadLine` in your session, at which point the W10 console windows' native selection and copy & paste features start working.

I suggest posting an [issue there](https://github.com/lzybkr/PSReadLine/issues) - correct, @iSazonov?

**Comment by iSazonov** [comment] 2017-07-19 12:42
Could you please test on Linux too?

**Comment by mklement0** [comment] 2017-07-19 13:32
@iSazonov: 

Linux terminals typically use ⌃⇧C and ⌃⇧V rather than ⌃C and ⌃V.

I can confirm that ⌃⇧C and ⌃⇧V work as expected in the default terminal on Ubuntu 16.04.

**Comment by iSazonov** [comment] 2017-07-19 13:45
@mklement0  Thanks for the test!

**Comment by loxal** [comment] 2017-07-19 13:59
After executing `Remove-Module PSReadLine` Ctrl + V works fine again on Windows 10 (Creators Update)/PS6beta4.

**Comment by iSazonov** [comment] 2017-07-19 14:01
@lzybkr Could you please comment the Issue?

**Comment by loxal** [comment] 2017-07-19 14:04
Another, slightly unrelated question:  

When I launch "Ubuntu Bash" in PS and want to use `Ctrl + V` as well, I get `^V` -- only right-click works. With https://conemu.github.io/ it works fine but I do not want to use it because if its preferences bloat.

**Comment by mklement0** [comment] 2017-07-19 17:07
@loxal: I don't think that's a PowerShell problem; `bash.exe` is in control of keyboard handling, and you get the same behavior whether you invoke it from PowerShell or directly, via the official shortcut.

**Comment by lzybkr** [comment] 2017-07-22 03:30
PSReadline depends on winforms for clipboard support, but winforms is not in .Net Core. We likely need to extract the clipboard p/invoke code from winforms to get copy/paste support in PSReadline, but that still won't help on non-Windows platforms that might not support a clipboard at all.

**Comment by iSazonov** [comment] 2017-07-22 19:53
If it work without PSReadline why we need the clipboard p/invoke ?

**Comment by lzybkr** [comment] 2017-07-22 21:33
Cooked mode command line editing (conhost) supports basic selection and clipboard, but isn't extensible, so PSReadline uses raw mode and loses some things like clipboard support.

**Comment by iSazonov** [comment] 2017-07-24 04:54
Is there no way to passthrough for clipboard support?

**Comment by lzybkr** [comment] 2017-07-24 14:13
Not really,  there could be some horrible hack, but no clean way.

**Comment by iSazonov** [comment] 2017-07-24 14:34
@lzybkr Thanks for clarify!

Unix doesn't seem to have a common clipboard 😕. I guess we have to fix at least Windows.

**Comment by iSazonov** [comment] 2017-07-24 14:52
Native API:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms649048%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms649016(v=vs.85).aspx#_win32_Copying_Information_to_the_Clipboard

WinForms uses ComObj  `OleGetClipboard` https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Clipboard.cs,f4f3734655d33a95

**Comment by aarsan** [comment] 2018-01-12 05:09
Any movement on this? Would love to be able to get my ctrl + v back :)

**Comment by MaximoTrinidad** [comment] 2018-01-12 17:27
+1 with @aarsan 

This works in Windows PowerShell without doing "remove-module psreadline", but not in PSCore 6.0.0.
In PSCore 6.0.0, only works if I do the "remove-module psreadline".

:)

**Comment by aarsan** [comment] 2018-01-13 02:48
Awesome. Worked, but I had to add the -SkipPublisherCheck param. Thanks!

**Comment by iSazonov** [comment] 2018-01-13 06:48
I think we can close the Issue - with PSReadline 2.0.0 we got `Ctrl-V` and `Ctrl-C` on Windows back.

**Closed by iSazonov** 2018-01-13 06:48 UTC
Labels: Area-Console, Issue-Question, OS-Windows

**Comment by Hrxn** [comment] 2018-03-24 14:12
In which version of PowerShell Core will PSReadline 2.0.0 land?

**Comment by yves-dolce** [comment] 2018-06-01 22:00
Any progress on this?

**Comment by lzybkr** [comment] 2018-06-01 22:19
You can install [PSReadLine 2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1). Beta2 will hopefully ship with the next preview of 6.1.

**Comment by mklement0** [comment] 2018-06-01 23:26
@lzybkr: 

Thanks for fixing most of the issues in v2, on all platforms.

The one thing that still doesn't seem to work on _Unix_ platforms is copying _keyboard-based_ selections to the clipboard.

What would be required to support that?

**Comment by lzybkr** [comment] 2018-06-01 23:55
@mklement0 - I haven't really looked into clipboard support for non-WIndows - I'd sort of assumed the only viable approach was to use an external utility like `pbcopy` or `xclip` or whatever the tool might be called.

**Comment by mklement0** [comment] 2018-06-02 00:03
@lzybkr:

Indeed: on macOS it is `pbcopy`, on freedesktop.org-compliant Linux distros (X11-based desktops)  it is the `xclip` utility, which, unfortunately, isn't preinstalled.

My [`ClipboardText` module](https://www.powershellgallery.com/packages/ClipboardText) provides a PS wrapper around these (including around `clip.exe` on Windows), if it helps. (It only _warns_ about a missing `xclip` and provides installation _hints_, however).
