### ISSUE TITLE
The PSHostUserInterface constructor throws an exception when published in a "Single File" application

### ISSUE THREAD

**Issue by BobbyCannon** [PowerShell/PowerShell#15382] opened 2021-05-12 01:34 UTC
## Steps to reproduce

I have a custom PowerShell Host using 7.1.3 SDK. The console works great until I "publish" the console as a Single File Executable.

## Example Solution / Project showing issue

I made a very simple project to show the issue.

https://github.com/BobbyCannon/Samples/tree/master/MyPowerShell

Just publish and run the published bits. If you set "PublishSingleFile" to False the publish build will run. If you set "PublishSingleFile" to false it will throw the exception.

## Some Code

I have a few classes that work when **not** running as single file. The constructor for PowerShellHostUserInterface : PSHostUserInterface exceptions when the application is published to single file. If I publish with single file false then everything works fine.

```none
public class PowerShellHost : PSHost, IHostSupportsInteractiveSession
{
	UI = new PowerShellHostUserInterface(console);
}

public class PowerShellHostUserInterface : PSHostUserInterface, IHostUISupportsMultipleChoiceSelection
{
	RawUI = new PowerShellHostRawUserInterface(this);
}

public class PowerShellHostRawUserInterface : PSHostRawUserInterface
{
}
```

I'm wondering if a configuration file that is required is getting removed or is missing from the publish output.

## csproj

```none
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0-windows</TargetFramework>
		<Platforms>x64;x86</Platforms>
		<UseWPF>true</UseWPF>
		<AssemblyVersion>5.0.0.0</AssemblyVersion>
		<FileVersion>5.0.0.0</FileVersion>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.1.3" />
		<PackageReference Include="System.Management.Automation" Version="7.1.3" />
	</ItemGroup>
</Project>
```

## x64.pubxml file

```none
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>x64</Platform>
    <PublishDir>bin\Publish\x64</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>True</SelfContained>
    <PublishSingleFile>False</PublishSingleFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <DeleteExistingFiles>True</DeleteExistingFiles>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>
</Project>
```

## Expected behavior

```none
Should just work as it does without being published as a single file.
```

## Actual behavior

```none
The type initializer for 'System.Management.Automation.Configuration.PowerShellConfig' threw an exception.
   at System.Management.Automation.Utils.GetPolicySettingFromConfigFile[T](ConfigScope[] preferenceOrder)
   at System.Management.Automation.Utils.GetPolicySetting[T](ConfigScope[] preferenceOrder)
   at System.Management.Automation.Host.PSHostUserInterface.<>c.<.cctor>b__54_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at System.Management.Automation.Host.PSHostUserInterface.GetSystemTranscriptOption(TranscriptionOption currentTranscript)
   at System.Management.Automation.Host.PSHostUserInterface.CheckSystemTranscript()
   at System.Management.Automation.Host.PSHostUserInterface..ctor()
   at MyPowerShell.Server.PowerShellHost..ctor(IPowerShellHost console)
   at MyPowerShell.Server.PowerShellConsole..ctor(Int32 port, String options)
   at MyConsole.Program.Main(String[] args)


```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BobbyCannon** [comment] 2021-05-13 00:33
Found this is a duplicate and already known. https://github.com/PowerShell/PowerShell/issues/13540

**Comment by daxian-dbw** [comment] 2021-05-13 04:43
Close as a duplicate of #13540

**Closed by daxian-dbw** 2021-05-13 04:43 UTC
Labels: Needs-Investigation, Needs-Triage, WG-DevEx-SDK
