### ISSUE TITLE
Changing window width disturbs the startup text blurb

### ISSUE THREAD

**Issue by 9Rune5** [PowerShell/PowerShell#11905] opened 2020-02-20 16:29 UTC
# Steps to reproduce
1. Put the following in $profile:
`Invoke-WebRequest https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -OutFile ~\LS_COLORS`
1. Start pwsh.exe
2. Change window width

# Expected behavior
Text shouldn't float around.

# Actual behavior

The version blurb is pulled along.
![image](https://user-images.githubusercontent.com/9988080/74956205-0e9e1700-5406-11ea-8f26-5c6a68d5cb2e.png)

Identical behavior when launched from Windows Terminal.

# Environment data

```Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

(Edited to add missing repro step. Invoking a web-request flashes a blue text dialog on the screen, which seems to screw up the text formatting underneath)

**Comment by mklement0** [comment] 2020-02-20 19:35
Intriguing, I'm not seeing these symptoms, neither in a regular console window nor in Windows Terminal. 

Either way, I think the right place to post this issue is https://github.com/microsoft/terminal, because I don't think PowerShell or PSReadLine modify the existing screen buffer in response to window resizing.

**Comment by 9Rune5** [comment] 2020-02-20 20:20
I'll head over to the terminal guys then.

The oddest thing is that when I booted up my second system, I couldn't reproduce it at first, but when I tried again now it happens there too... Very odd. (and it is just that intro text, everything that comes after looks okay)

**Comment by 9Rune5** [comment] 2020-02-20 21:21
Added a missing step to my reproduce steps.

Is this still a terminal issue?

**Comment by mklement0** [comment] 2020-02-20 21:44
Your repro steps do nothing but perform a _file download_, which shouldn't have any side effects - and doesn't in my tests.
Are there steps missing?

**Comment by 9Rune5** [comment] 2020-02-20 22:34
While downloading, it displays a progress bar. At least I think it is a progress bar, but it flashes by pretty quickly to tell for sure. 

I believe the action of displaying that 'thing' disrupts the console output. After this, modifying the window width behaves abnormally.

**Comment by mklement0** [comment] 2020-02-20 22:49
I see. Yes, it is a progress bar.

Since I assume you don't want that to show anyway, the pragmatic workaround is to do this:

```powershell
& { $ProgressPreference = 'SilentlyContinue';  Invoke-WebRequest https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -OutFile ~\LS_COLORS }
```

Apart from that, for the reasons stated above (I only see it in Windows Terminal, btw), I still suggest you report the issue at https://github.com/microsoft/terminal/issues

**Comment by msftrncs** [comment] 2020-02-21 02:48
This happens for me, and has been for a long time.   Windows 10, PS 7 RC2 currently.

This is after resizing the window immediately after opening.
![image](https://user-images.githubusercontent.com/26179051/74999852-529f1500-5422-11ea-96eb-66dddd4f6c1d.png)

I only have a couple settings and poshgit in my profile for startup.

**Comment by mklement0** [comment] 2020-02-21 03:09
@msftrncs, is it related to the specific content of your `$PROFILE`, such as poshgit?
Does it still occur if you (selectively) comment out statements?

**Comment by msftrncs** [comment] 2020-02-21 04:20
Surprisingly my other machine (I'm at now) does not do it ...  it is nearly the same profile, the biggest difference in machines is that this other machine (that is behaving) is Win 10 insiders build 19564.   I'll have to dig deeper on the profile part tomorrow.

I can mention this, my profile comes from a network redirected resource on the machine I notice this issue on.

**Comment by msftrncs** [comment] 2020-02-21 06:13
I can reproduce this as well in 6.2.4, in the same conditions as originally.

Removing the profile (`pwsh -noprofile`) seems to keep the problem from occurring.

My `profile.ps1` file is pretty simple.

```Powershell
Import-Module posh-git

Set-PSReadLineOption  -Colors  @{
     Command    = [ConsoleColor]::DarkYellow
     Comment    = [ConsoleColor]::DarkGray
     Keyword    = [ConsoleColor]::Magenta
     Member     = [ConsoleColor]::White
     Number     = [ConsoleColor]::Cyan
     Operator   = [ConsoleColor]::Blue
     Parameter  = [ConsoleColor]::Yellow
     String     = [ConsoleColor]::Green
     Type       = [ConsoleColor]::Red
     Variable   = [ConsoleColor]::DarkCyan
 } -PromptText '> '
```
If I comment out the `Import-Module posh-git`, then the issue doesn't occur.

However, simply executing that command after the shell opens without it, and the issue occurs again.   It is something about the process of importing posh-git in my case, and the text on those lines.  Those lines are in the same place as the progress bar would appear.

If I have something else on the screen when the progress bar appears, its those lines that then become corrupted.  Importing posh-git causes a progress bar to very momentarily appear.

![image](https://user-images.githubusercontent.com/26179051/75008861-c51dee00-543e-11ea-9774-152445df7704.png)

The issue is that the progress bar corrupts the display buffer due to it removing and then replacing that text.

**Comment by 9Rune5** [comment] 2020-02-21 08:28
The progress bar also affects the colors on the text it temporarily displaced (see updated screenshot in the winterm issue I opened https://github.com/microsoft/terminal/issues/4677).

Are you still confident it is a conhost/winterm issue @mklement0 ? If so then I'll close this issue here.

**Comment by mklement0** [comment] 2020-02-21 09:03
Nice sleuthing, @msftrncs.

@9Rune5, I'm now unclear on whether this is a PowerShell issue, we'd have to look at the progress-bar code to see if the way it saves and restores the screen buffer is delegated to console API calls that malfunction or if there's something else going on on the PowerShell side (e.g., incorrect use of these calls).

I suggest starting in _this_ repo, which means closing this issue and moving the content of https://github.com/microsoft/terminal/issues/4677 _here_ (closing it there and re-creating it here), with a link to _this_ issue for background info.

https://github.com/microsoft/terminal/issues/4677 can always be reopened if it does turn out to be a console issue after all.

**Closed** 2020-02-21 09:30 UTC
Labels: Issue-Question
