### ISSUE TITLE
PSVersionTable needs an *OS* key

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#1997] opened 2016-08-21 18:31 UTC
We need to be able to *at least* tell whether we're on Windows or Unix _from the PSVersionTable_. 

Ideally, I'd like to be able to differentiate Windows Server, Windows Desktop, Nano Server, OS X, and BSD from Linux.

Since `PSEdition` Core runs on Windows (and even Windows Desktop), and since CLRVersion will presumably be the same across all versions of Core (even if it were populated #1984), and since "BuildVersion" is going _backwards_ ...

I also think that PSVersionTable should expose "Architecture" (ARM, AMD64, x86).

**Comment by kilasuit** [comment] 2016-08-21 18:38
Agreed and suggested this in #1936 as well as a change to the Issue template to make issues easier to track

**Comment by rkeithhill** [comment] 2016-08-21 18:39
It would make for a nice way to gather information for a bug report.  I like.  And on Linux, you probably want the specific version i.e. not just Ubuntu but something to distinguish between 14.04 and 16.04.  Also, `Architecture` needs to disambiguate between OS architecture and current process architecture e.g. PowerShell x86 running on Windows x64.

**Comment by lzybkr** [comment] 2016-08-21 21:33
Dupe of #1635.

**Closed** 2016-08-21 21:50 UTC

**Comment by Jaykul** [comment] 2016-08-21 22:13
Sorry. I couldn't find it (searching for PSVersionTable is pointless in here)

**Comment by MaximoTrinidad** [comment] 2016-08-22 00:41
I agree!
+1 for Jaykul

**Comment by lzybkr** [comment] 2016-08-22 03:19
No problem, I opened it, so I knew it was there.  I did search for `PSVersionTable` first, way too many hits, so added `OS` and many fewer hits.
