### ISSUE TITLE
Do not provide two submenus in file explorer integration

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#6599] opened 2018-04-09 03:00 UTC
there's an opt-in File Explorer context-menu integration in the installer (wizard) GUI.
I have ticked this option.
 
The problem is when I try to pop up the powershell in empty space of a folder, you provide submenus.
![default](https://user-images.githubusercontent.com/3004057/38474725-bbb3fe88-3bd4-11e8-8376-ef266259190a.png)
It's boring for me to choose open here and open as Administrator.
I already set it open as Administrator by default, so I hope you can make it as "git bash here" directly without submenus.

**Comment by bergmeister** [comment] 2018-04-28 16:28
When I did the PR #5774 for this feature, this got already discussed.
The main reason for the submenu is the  limitation of Windows registry options for context menus: they only allow direct elevation of the process using sub menus.
Apart from that the entry name would also become very long since it also needs to include version and bitness due to side-by-side installations to disambiguate.
All this option does is setting some registry keys. If you do not like, you can set your own registry keys for your preferred context menu, there are plenty of blogs on the Internet how to do that.
Therefore I would rather close this issue since there isn't really a viable alternative that a substantial amount of users would find useful. Sure, you could add a checkbox that only gives you one menu entry without a submenu but then the installer UI gets more complex (often leading to most users being overloaded by too much choice). What are your thoughts @SteveL-MSFT

**Comment by chucklu** [comment] 2018-04-28 18:30
@bergmeister  not sure, you can see "git bash here" in my screenshot(it did not contains version number).
The version should not show in context menu, we can check the  version by cmd.

**Comment by SteveL-MSFT** [comment] 2018-04-28 23:35
I agree with @bergmeister that the issue of having a submenu was discussed in the links he provided and we ended up with the current design due to limitations of WIndows registry settings that enable this as well as supporting side-by-side installs of PSCore6

cc @joeyaiello

**Comment by bergmeister** [comment] 2018-05-27 15:35
@iSazonov I think this is an issue that can be closed as 'by design' since we have reasoned the technical design decision behind the need for the submenu.

**Closed** 2018-05-27 15:57 UTC
Labels: Area-Build, Issue-Discussion, Resolution-By Design
