### ISSUE TITLE
Get-ChildItem is super slow when using the combination of `-Recurse` and `-Path` with a collection of files

### ISSUE THREAD

**Issue by amfogor** [PowerShell/PowerShell#15259] opened 2021-04-17 13:53 UTC
### Summary

When using the combination of `-Recurse` and `-Path` with a collection of files, `Get-ChildItem` is way slower than `Get-ChildItem -Path $files` or `Get-ChildItem -Recurse -LiteralPath $files`

See the summary in https://github.com/PowerShell/PowerShell/issues/15259#issuecomment-822043579 and https://github.com/PowerShell/PowerShell/issues/15259#issuecomment-822517175

### Repro steps

```powershell
PS:> cd .\PowerShell\src\System.Management.Automation
PS:> $f = Get-ChildItem -Recurse -File .
PS:> Measure-Command { Get-ChildItem -Path $f } | % TotalMilliseconds
198.2444
# VS
PS:> Measure-Command { Get-ChildItem -Recurse -LiteralPath $f } | % TotalMilliseconds
213.8493
# VS
PS:> Measure-Command { Get-ChildItem -Recurse -Path $f } | % TotalMilliseconds
15967.8931
```

### Environment

```
PS:46> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by zett42** [comment] 2021-04-17 14:13
Why would you use `Get-ChildItem -Recurse` on an array of files to begin with? Seems pointless to me.

**Comment by amfogor** [comment] 2021-04-17 14:24
@zett42  It is used in a utility function. So the input can be anything(same as `gci`).

**Comment by iSazonov** [comment] 2021-04-17 15:08
You measure two commands together. What command is slow? What are you comparing with? Please update repro steps.

**Comment by amfogor** [comment] 2021-04-17 16:19
@iSazonov I'm comparing with the code in "Expected Behavior".

**Comment by mklement0** [comment] 2021-04-17 16:54
While the _extent_ of the slowdown should be investigated, your second command should really be:

```powershell
# -lp == -LiteralPath
gci -R -File -lp $f
```

Only that guarantees the expected results, given that your _verbatim_ file paths would otherwise be interpreted as _wildcard patterns_, due to (positionally) binding to `-Path` rather than `-LiteralPath`.

As a (beneficial) side effect, the command executes much faster.

**Comment by mklement0** [comment] 2021-04-17 16:57
It is the use of `-Recurse` in combination with (implied) `-Path` that causes the excessive slowdown - even though in the case at hand - only _file_ paths as input - there is no recursion to perform.

By contrast, with `-LiteralPath` the presence or absence of `-Recurse` makes virtually no difference.

**Comment by amfogor** [comment] 2021-04-17 18:08
@mklement0 
The code here is only to show the issue. Why is everyone nitpicking the hell out of it...

**Comment by mklement0** [comment] 2021-04-17 18:10
That's not what I was doing. My comments contained:

(a) an acknowledgement of the problem - the excessive slowdown when combining `-Path` with `-Recurse` with an array of _file_ paths.

(b) an explanation of how the problem can be avoided (`-LiteralPath`), which also happens to be _the right thing to do_.

**Comment by amfogor** [comment] 2021-04-17 18:54
@mklement0 

> your second command should really be
> Only that guarantees the expected results,

By looking at the code you figured that `-LiteralPath` should be used. And that would defeat the whole purpose of the code.

**Comment by mklement0** [comment] 2021-04-17 19:14
@amfogor, I'm happy to respond to constructive engagement with the arguments that were made.

**Comment by iSazonov** [comment] 2021-04-18 17:58
Please update the issue with 
`$f = Get-ChildItem -R -File -Path . ; Measure-Command { Get-ChildItem -Recurse -File -Path $f }` vs `$f = Get-ChildItem -Recurse -File -Path . ; Measure-Command { Get-ChildItem -File -Path $f }`

I can even guess why it works so slowly (case normalization). If so, then the PR with the fix has been waiting for a long time.

**Comment by mklement0** [comment] 2021-04-18 19:06
@iSazonov, to demonstrate that not case normalization, but the specific combination of `-Path` and `-Recurse` is the pathological case:

Benchmark code, using only a `10`-element array of file paths:

```powershell
Write-Verbose -vb 'Setting up...'

# Download and define function `Time-Command` on demand (will prompt).
if (-not (Get-Command -ea Ignore Time-Command)) {
  $gistUrl = 'https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27/raw/Time-Command.ps1'
  if ((Read-Host "`n====`n  OK to download and define benchmark function ``Time-Command`` from Gist ${gistUrl}?`n=====`n(y/n)?").Trim() -notin 'y', 'yes') { Write-Warning 'Aborted.'; exit 2 }
  Invoke-RestMethod $gistUrl | Invoke-Expression 3>$null
  if (-not ${function:Time-Command}) { exit 2 }
}

# Create an array with all-lowercase file paths ($PROFILE)
$elementCount = 10
$filePathArray = , $PROFILE.ToLowerInvariant() * $elementCount

# Define the script blocks whose execution to time.
$benchmarks = @(
  {
    Get-ChildItem -Path $filePathArray -File 
  }

  {
    Get-ChildItem -LiteralPath $filePathArray -File 
  } 

  {
    Get-ChildItem -Recurse -Path $filePathArray -File
  }

  {
    Get-ChildItem -Recurse -LiteralPath $filePathArray -File
  } 
)

Write-Verbose -vb "Running benchmarks with $elementCount files..."

# Get the file once, out of competition, to warm up the cache.
$null = Get-ChildItem -File -LiteralPath $filePathArray[0]

# Run the benchmarks 10 times and report the averaged results.
Time-Command -Count 10 $benchmarks
```

Results:


On Windows, I get:

```none
VERBOSE: Setting up...
VERBOSE: Running benchmarks with 10 files...

Factor   Secs (10-run avg.) Command                                                  TimeSpan
------   ------------------ -------                                                  --------
1.00     0.004              Get-ChildItem -LiteralPath $filePathArray -File          00:00:00.0043445
1.02     0.004              Get-ChildItem -Path $filePathArray -File                 00:00:00.0044139
1.03     0.004              Get-ChildItem -Recurse -LiteralPath $filePathArray -File 00:00:00.0044683
1,785.74 7.758              Get-ChildItem -Recurse -Path $filePathArray -File        00:00:07.7581985
```

That is, adding `-Recurse` to `-Path -File` caused a roughly 2000-fold slowdown.

On macOS it isn't quite that bad, but still pathological:

```none
Factor Secs (10-run avg.) Command                                                  TimeSpan
------ ------------------ -------                                                  --------
1.00   0.002              Get-ChildItem -Path $filePathArray -File                 00:00:00.0023656
1.01   0.002              Get-ChildItem -Recurse -LiteralPath $filePathArray -File 00:00:00.0023979
1.02   0.002              Get-ChildItem -LiteralPath $filePathArray -File          00:00:00.0024215
22.71  0.054              Get-ChildItem -Recurse -Path $filePathArray -File        00:00:00.0537165
```

**Comment by iSazonov** [comment] 2021-04-19 04:31
> to demonstrate that not case normalization

You could compare results for very small folder tree (one-file-folder-tree) and for a folder tree with many nested objects.
(Case normalization does one pinvoke per subfolder name in folder path, and globbing multiply this up to 6 times!)

**Comment by mklement0** [comment] 2021-04-19 14:36
The benchmarks above clearly demonstrate a problem that is _unrelated_ to case normalization, and I suggest we stay focused on that specific problem here.

To recap: 

* There is no justification for `-Recurse` to slow things down this dramatically when combined with `-Path` and _file_ paths, given that there is _nothing to recurse on_.

* The problem doesn't occur with `-LiteralPath`.

* Clearly, the specific combination of parameters results in unrelated, unexpected extra activity - and that's what we need to fix.

---

As for case normalization: It is only ever needed for the recursion _entry points_, never _during enumeration_, as previously discussed in https://github.com/PowerShell/PowerShell/issues/13190#issuecomment-663870047. And if there's too much case normalization currently going on, that needs to be addressed separately.

**Comment by iSazonov** [comment] 2021-04-20 11:29
Yes, it is extra globbing.
Proposed fix https://github.com/iSazonov/PowerShell/commit/1c52dc300629e5c79bc18136a2eeeb76b417c329
Feel free If somebody want to pull PR.
(The fix is only cosmetic fix for the specific scenario. To make Globbing fast is very difficult and unobvious work.)

PS; @mklement0 Please look output with Name parameter in second command. Do you see only empty string?

**Comment by mklement0** [comment] 2021-04-20 12:27
Looking at the title, that PR definitely sounds like a worthwhile optimization, but note that it isn't globbing per se that's the problem here, given that `Get-ChildItem -Path $filePathArray -File` in the test above performs virtually the same as the non-globbing `Get-ChildItem -LiteralPath $filePathArray -File` variant (with only a 10 paths).

Again, the addition of `-Recurse` to `-Path` is what triggers the problem, so I suspect that it's some kind of unnecessary traversal that is triggered.

> look output with Name parameter in second command. Do you see only empty strings?

Among the commands in the benchmark code above, the ones with `-Recurse`  - both `-Path` and `-LiteralPath` - indeed produce empty-string output when `-Name` is added.

**Comment by iSazonov** [comment] 2021-04-20 13:03
> but note that it isn't globbing per se that's the problem here

You can look the very weird code here https://github.com/PowerShell/PowerShell/blob/4d702e010d656681e42164ad02344883836668c9/src/System.Management.Automation/engine/SessionStateContainer.cs#L1320-L1371
As you see PowerShell creates new filter with `Include` among other things. So it’s not surprising that it works the slowest way.

(Could you please open new issue for the bug with `-Name` if you have time or such issue already is?)

**Comment by mklement0** [comment] 2021-04-20 17:14
Well, that code does sound like the implementation of the treacherous behavior discussed in #5699. Of course, when given a _full_ path referring to a _file_, no recursion should ever be performed, even with (positionally implied) `-Path`.

> Could you please open new issue for the bug with -Name 

Please see #15283.

**Comment by iSazonov** [comment] 2021-04-20 17:38
> Well, that code does sound like the implementation of the treacherous behavior discussed in #5699. 

It seem the code executed only for Path parameter (SuppressWildcardExpansion is false).

**Comment by mklement0** [comment] 2021-04-20 17:42
I've been saying all along that the problem is the specific combination of `-Recurse` and `-Path`.

**Closed** 2023-11-23 11:18 UTC
Labels: Issue-Bug, WG-Engine-Performance, WG-Engine-Providers, Area-FileSystem-Provider, Resolution-No Activity
