### ISSUE TITLE
Inconvenient behavior of the Switch-operator

### ISSUE THREAD

**Issue by u20221022** [PowerShell/PowerShell#18822] opened 2022-12-19 06:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
($Private:P = 13)
Switch -Exact (13, $P) {
    13            {1}
    "13"          {2}
    $P            {3}
    {$_ -EQ 13}   {4}
    {13 -EQ $_}   {5}
    {$_ -EQ "13"} {6}
    {"13" -EQ $_} {7}
    {$_ -EQ $P}   {8}
    {$P -EQ $_}   {9}
}

($Local:L = 13)
Switch -Exact (13, $L) {
    13            {1}
    "13"          {2}
    $L            {3}
    {$_ -EQ 13}   {4}
    {13 -EQ $_}   {5}
    {$_ -EQ "13"} {6}
    {"13" -EQ $_} {7}
    {$_ -EQ $L}   {8}
    {$L -EQ $_}   {9}
}
```

### Expected behavior

```console
13
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
13
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
```

### Actual behavior

```console
13
1
2
3
4
5
6
7
1
2
3
4
5
6
7
13
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
```

### Environment data

```powershell
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment] 2022-12-19 15:07
This is just a duplicate of  #18816 

```
# parent scope

switch (# parent scope)
{
    { # child scope }  { # parent scope }
}

# parent scope
```

There is certainly an argument that they should be consistent. 

Why have the _action script block_ executed in the parent scope - it's what happens in `if` `for` `foreach` `while` etc. It would be odd to have a statement were it is different, and we often want something to set a variable in the action.  

So if they are consistent the  _value script block_ should run in the parent scope. Normally it won't make any difference EXCEPT in the corner case of variables which are told not to inherit into child scopes and which a script author tries to the use in the value script. Remember, it is a script block, so it can be a big block of code which assigns variables etc, and returns true or false to run the action block. This block should not be leave its working variables behind or change them in the parent scope. Hence it is set to run in a child scope. 

It could be changed, but the present behaviour has existed for a  long time, so there is likely to be code out there which relies on the present design not changing things in the parent scope. Changing the behaviour would introduce quite subtle bugs into that code.  

The inconvenience is small and rare, the effort to "fix" would be better used elsewhere and the "fix" may introduce worse problems than the current one.  So the best you are likely to see is the documentation making the behaviour clear.

**Comment by jhoneill** [comment] 2022-12-19 18:33
> The child scope does not prevent the values in another scopes from changing. Perhaps this is a bug too.

No it is not a bug. Scopes inherit from caller to called, and an assignment in a child scope creates a new variable. Sometimes there is a need to manipulate something in the caller's scope (in the style of errorvariable, or outvariable) so scopes are a _soft_ boundary.)  And you can use `get-variable` to get a "private" variable from the scope above and solve the problem here, though not having to do that would be neater in the tiny, tiny, number of cases where it matters.  

> But I understand that no one wants to work, so they will not fix these bugs.

Well, obviously Microsoft pays the PowerShell to sit around doing nothing all day, don't they? There are more features people want to add, and more issues to fix than there will ever be time for. Any change has to compete with other possible changes to get time. 

This was done intentionally long ago and neither you nor I know why. I came upon the idea of "Chesterton's fence" earlier this year. If someone says "this fence is in the way and should be removed"  we should not remove it before we know if the reason why it was put there still applies.   

> > the present behaviour has existed for a long time
> 
> The current regime in Russia has also existed for a long time, so no one wants to change it, is not it?

(a) Probably best to leave politics out. 
(b) Regime change when it is ill understood can be worse than leaving alone. 

You have also (deliberately I think) edited what I said.  All features/behaviours of a programming language or API eventually become things that some code somewhere depends on.  Lets say I always $i for "Index", and in a switch statement's value block I've done what I always did. The current scope behaviour means that my code doesn't screw up an index outside the switch statement. Now PowerShell changes and the script I wrote 10 years ago, in a place where I haven't worked for 8 years corrupts data. And people say "Oh you can't trust new versions of PowerShell not to screw up your data" 
Or lets say you get your way and PowerShell 7.4 changes the scope so you can write code as you'd expect it to work.. That change isn't backported to Windows PowerShell and client who runs your script on a server with it's pre-installed PowerShell 5 loses their data. 

> > The inconvenience is small and rare
> 
> Therefore, it is better not to annoy him.

In your terms, replacing one tyrant with another tyrant doesn't make things better (unless one is connected to the new tyrant). 
A fix which might break existing code needs demonstrate a huge benefit. This doesn't

**Comment by u20221022** [comment] 2022-12-20 02:18
> Now PowerShell changes and the script I wrote 10 years ago, in a place where I haven't worked for 8 years corrupts data.

Can you give an example when such a change will affect the current code?

> In your terms, replacing one tyrant with another tyrant…

These are not my terms.  You have learned to write long texts, but you cannot read and understand.  It is sad.

**Comment by jhoneill** [comment] 2022-12-20 18:21
@u20221022  

There's not a lot of point in getting drawn into a long discussion. 

Here's an example from neutral territory 
Evaluate   `$true -and $true -or $false -and $false`  
In some languages Boolean AND operations are treated like arithmetic multiplies and a OR operations like arithmetic adds so ANDs are evaluated before ORs `$true -and $true -or $false -and $false` reads as `($true -and $true) -or ($false -and $false)` and is true 
In others, a minority but including PowerShell, the evaluation is simple left to right, `$true -and $true -or $false -and $false` reads as `(($true -and $true) -or $false )-and $false` and is false. 

Those who have grown up with the former, consider the latter to be stupid, and wrong and demand that it is put right. But any code which relies on the present rules - doesn't expressly put ()  into the expression now does something different. 

For switch suppose I want to calculate permutations. 
``` 
$selection = 7,8,9,10,11
$setSize = 10 

 switch ($selection) {
{$_ -gt $Setsize} {"Can't select $_ from $setSize"} 
{$p = 1 ; 
  for ($i = $setSize; $i -ge $_ ; $i --  ) {$p *= $i } 
  $p -ge 1000 } {"$_ gives Greater than 1000"; continue} 
{$p = 1 ; 
 for ($i = $setSize; $i -ge $_ ; $i --  ) {$p *= $i } ; 
 $p -ge 100 } {"$_ gives Greater than 100"} 
default {"$_ gives 100 or Fewer "}
}
   
```

If I use $i or $p outside the switch, they would be untouched currently and corrupted with your proposed change. 

What is unknowable is how many people write code like that in their switches. Maybe lots, maybe none. The fix to your problem is either (a) Don't use Private like that (16 years of PowerShell I have never needed to use it at all) (b) if you absolutely must use private use `get-variable` in the _value Script block_  
The total number of people complaining that neither is good enough for them is a couple in 16 years.
So is the problem big enough allocate resource to fix it and to take the risk with fix. ?  No.

**Comment by u20221022** [comment] 2022-12-21 00:25
False → True
False → False
That is, from the False follows all:
False → Anything
https://en.wikipedia.org/wiki/Material_conditional
RTFM©
```
$selection = 7,8,9,10,11
$setSize = 10 

 switch ($selection) {
# Я презираю тех, кто пишет программы так неряшливо, как будто это какие-то приложения к неизвестно чему.
#     Вы сперва определитесь, как называется переменная – «setSize» или «Setsize», – а потом умничайте.
#     Даже нормальные отступы в тексте сделать не способны, а туда же.  Почему я должен разбирать такие каракули?
#     Посмотрите на мой пример – аккуратные столбцы, всё легко читается.
# Ваш текст я форматировать не намерен, только добавил кое-что.
#     Разбирайтесь сами, раз бардак предпочитаете порядку.
{$_ -gt $Setsize} {"Can't select $_ from $setSize"} 
{$p = 1 ; 
  for ($i = $setSize; $i -ge $_ ; $i --  ) {$p *= $i } 
  $p -ge 1000 } {"$_ gives Greater than 1000"; "Вы нагло врёте: $(($_ -GT 1000) ? ""$_ GT 1000`n"" : ""$_ LE 1000`n"")"; continue} 
{$p = 1 ; 
 for ($i = $setSize; $i -ge $_ ; $i --  ) {$p *= $i } ; 
 $p -ge 100 } {"$_ gives Greater than 100"; "Вы снова нагло врёте: $(($_ -GT 100) ? ""$_ GT 100`n"" : ""$_ LE 100`n"")"} 
default {"$_ gives 100 or Fewer "; "А все нечерномазые становятся расистами и подлежат уничтожению.@BLM`n"}
}
```

**Comment by u20221022** [comment] 2022-12-21 00:30
> 16 years of PowerShell I have never needed to use it at all

Some don't wash for years, so what?

**Closed** 2023-11-22 10:56 UTC
Labels: WG-Engine, Needs-Triage, Resolution-No Activity
