### ISSUE TITLE
OneDrive "files on demand" (sparse files) being downloaded without contents being accessed. 

### ISSUE THREAD

**Issue by b3nt0** [PowerShell/PowerShell#7152] opened 2018-06-23 13:54 UTC
Steps to reproduce
------------------
Change location to a folder synchronized with OneDrive where files or directories have not been accessed. This is represented in the UI by having a "cloud" icon in the "status" column in explorer. Run get-childitem for a listing of the contents. Any items that had a cloud icon in status now have a green check mark indicating that they have been downloaded. This can be verified in the OneDrive UI. 

Expected behavior
-----------------
Files are not downloaded until they are accessed.

Actual behavior
---------------
Files are downloaded without accessing contents. 

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2018-06-23 15:36
Hmm. this ides repro for me.

I created a folder with a a few files in it, set them to be FODed, then `set-location` and `get-childitem`. the items remain FODed.

**Comment by b3nt0** [comment] 2018-06-25 00:16
@markekraus I was able to verify that pwsh.exe would behave this way no matter which host I ran it from. 5.1 didn't behave that way.

**Comment by SteveL-MSFT** [comment] 2018-06-27 00:05
It's possible that corefx is doing something different that accesses the contents.  Needs to be investigated.

**Comment by iSazonov** [comment] 2018-06-27 05:59
There is a special reparse point type for OneDrive on Wondows 10.
https://github.com/dotnet/corefx/issues/26310#issuecomment-358420799

**Comment by craiglandis** [comment] 2018-09-16 21:53
It repros for me with PowerShell 6.1/Win10 RS4/OneDrive Version 2018 (Build 18.172.0826.0010).

I run get-childitem <my onedrive folder> in PS 6.1 and it downloads all files in that folder that haven't been downloaded. PS 5.1 doesn't do that, nor does a "dir" in CMD.exe.

**Comment by sba923** [comment] 2019-05-12 08:10
Did you check what you get with PowerShell 6.2.0?

#8745 might have some effect.

**Comment by iamakulov** [comment] 2019-05-12 09:28
Just checked with 6.2.0; files are still downloaded with `Get-ChildItem`:

![image](https://user-images.githubusercontent.com/2953267/57580357-1745e200-74b1-11e9-893a-1e3ec2ad09d2.png)

**Comment by sba923** [comment] 2019-05-12 10:15
What your screenshot shows is that `pwsh.exe` triggers the download of something called `WinDivert.dll` (part of some module?), not of any of the online-only files in the `Clumsy` folder!

**Comment by iamakulov** [comment] 2019-05-12 10:47
`WinDivert.dll` is there:

![image](https://user-images.githubusercontent.com/2953267/57580904-457af000-74b8-11e9-8d26-4828565124e3.png)

The reason `WinDivert.dll` is not present in the screenshot is that `Get-ChildItem` _waits for the file to get downloaded_ and lists it only after that. Here, I added a few more files and recorded how it looks:

[<img width="480" alt="msedge_2019-05-12_13-45-53" src="https://user-images.githubusercontent.com/2953267/57581151-49a90c80-74bc-11e9-83b1-128145892bff.png">](https://www.youtube.com/watch?v=DJv91aNUINw)

**Comment by sba923** [comment] 2019-05-12 11:23
Weird. After the "download" the files are still marked (as far as the output from `Get-ChildItem` goes) as "online-only."

How did you add the files? Via the website?

I see you're running an Insider build of 19H1 / 1903. Which build exactly?

Have you tried reproducing this on RS5 / 1809?

**Comment by iamakulov** [comment] 2019-05-29 20:33
> Weird. After the "download" the files are still marked (as far as the output from Get-ChildItem goes) as "online-only."

Yup, that’s weird. In the explorer, however, they do get marked as downloaded after the command finishes running. Here’s another recording (26 sec): https://www.youtube.com/watch?v=jxaKL6u1i2k

Probably `Get-ChildItem` reports the status that it read _before_ the file got downloaded?

> I see you're running an Insider build of 19H1 / 1903. Which build exactly?

18362.113.

> Have you tried reproducing this on RS5 / 1809?

Nope.

**Comment by iamakulov** [comment] 2019-05-29 20:35
> Probably `Get-ChildItem` reports the status that it read before the file got downloaded?

Actually, yes. Here’s another `Get-ChildItem` that I ran right after I finished recording the video:

![image](https://user-images.githubusercontent.com/2953267/58589322-435fb200-826a-11e9-8dc3-68659164c648.png)

As you can see from the video, during the first `ls`, online-only files get downloaded, but `ls` still reports them as online-only. By the time the second `ls` runs, files are already downloaded, so it marks them appropriately.

**Comment by sba923** [comment] 2019-05-30 05:43
This really beats me… FWIW, have you checked that `ls` _is_ the standard alias to `Get-ChildItem` / that you get the same behavior when invoking `Get-ChildItem` directly?

Next to that, I would capture Process Monitor traces of `Get-ChildItem` running in Windows PowerShell 5.1 and in PowerShell Core 6.2.0. Maybe they would reveal something.

Have you tried upgrading to PowerShell Core 6.2.1?

Have you tried uninstalling and reinstalling PowerShell Core and (all bits and pieces of) .NET Core everywhere on your system?

Can you repro this on another system?

**Comment by michevnew** [comment] 2019-06-12 06:16
Any reason this is still not fixed in the 7.0 preview? I thought one of the main focuses of 7.0 was better integration/compatibility with Windows...

**Comment by sba923** [comment] 2019-06-12 06:37
@michevnew shall I infer you have a repro on your system? If so, can you please give as much detail as you can about your system and how you're triggering the problem?

**Comment by michevnew** [comment] 2019-06-12 06:45
Yes, the steps to reproduce havent changed from what's described in the original post. I have a W10 machine with files on demand configured, with most of the relevant files set to "Online". I installed the PS7 preview, navigated to the OneDrive directory where all my PS scripts reside, run a simple "dir" and had to wait for OneDrive to fully download the entire content of the directory. The screenshot below illustrates it for another, smaller dir
![PS7-filesondemand](https://user-images.githubusercontent.com/38553333/59329096-b7806800-8cf6-11e9-98d0-98d2598093f2.png)


PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Let me know if you need more info.

**Comment by iSazonov** [comment] 2019-06-13 03:59
@michevnew Can you prepare a repo on C#? I guess it come from .Net Core.

**Comment by SteveL-MSFT** [comment] 2019-06-13 22:56
Took a look at this, I have a fix.

**Comment by sba923** [comment] 2019-06-14 04:46
@SteveL-MSFT just curious: it seems I have never seen this issue. Your explanation in #9895 gives me the feeling everyone should be affected. What am I missing?

**Comment by SteveL-MSFT** [comment] 2019-06-14 05:23
@sba923 I don't know if it depends on a specific version of Win10 or OneDrive client, but it repros easily on my desktop machine.

**Closed** 2019-07-08 06:40 UTC
Labels: Area-Cmdlets-Management, Issue-Discussion
