### ISSUE TITLE
.NET location: Not found after installing .NET

### ISSUE THREAD

**Issue by 4cq2** [PowerShell/PowerShell#19823] opened 2023-06-18 16:30 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

when I start PowerShell, I get this message:

~~~
You must install .NET to run this application.

App: D:\PowerShell\pwsh.exe
Architecture: x64
App host version: 7.0.0
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.0
~~~

so I visit that URL, download and run the installer for ASP.NET Core Runtime. However after that, if I start PowerShell again, the error remains.

### Expected behavior

```console
!
```

### Actual behavior

```console
!
```

### Environment data

```powershell
!
```

**Comment by SteveL-MSFT** [comment] 2023-06-19 21:07
Need more details, what version and package are you using?  Given the location of pwsh.exe, you are using the zip package?

**Comment by 4cq2** [comment] 2023-06-19 21:11
https://github.com/PowerShell/PowerShell/releases/download/v7.3.0/PowerShell-7.3.0-win-fxdependent.zip

**Comment by daxian-dbw** [comment] 2023-06-20 17:11
The fxdependent.zip package depends on the .NET Runtime to be available on your system. The URL shown in the message is from .NET, not PowerShell, do we don't control what that URL leads to.

It seems to be a bug in .NET though, given that it's downloading the ASP.NET Core instead of the .NET Runtime. It does have a note below in the page indicating you still need to download .NET Runtime:

![image](https://github.com/PowerShell/PowerShell/assets/127450/5e27bfb2-d9d7-4d3f-b908-462f4dcc2c9c)

**Comment by daxian-dbw** [comment] 2023-06-20 17:19
Opened https://github.com/dotnet/sdk/issues/33435. Will close this issue as an external.

**Closed** 2023-06-21 19:00 UTC
Labels: Resolution-External

**Comment by 1268** [comment] 2023-07-16 14:55
confirmed fixed, the same Zip from above now links to .NET 7.0 Runtime instead of ASP.NET Core Runtime. thanks
