### ISSUE TITLE
Escape of double quote behaves call context dependent inconsistent, and basically erroneous.

### ISSUE THREAD

**Issue by ArnoCan** [PowerShell/PowerShell#15892] opened 2021-08-09 12:02 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The behaviour of an escaped double quote depends on the call context and is inconsistent. This issue is technically  related to #15888 and #15889. The specifications and definitions are:

* [PowerShell-7.1 - B. Grammar](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-15?view=powershell-7.1) - see *escaped-character*
* [about_Quoting_Rules](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1) - PowerShell-7.1

1. The pure evaluation from the PowerShell prompt behaves as stated in [about_Quoting_Rules](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1):
   ```
   PS C:\PowerShell-7.1.3> "`"a"
   "a
   PS C:\PowerShell-7.1.3>
   ```
2. The call of a PowerShell script
   ```
   write-host -NoNewline "["
   for ( $i = 0; $i -lt $args.count; $i++ ) {
       write-host -NoNewline "'$($args[$i])', "
   }
   write-host "]"
   ```
   behaves the same way:
   ```
   PS C:\PowerShell-7.1.3> X:\print_argv_list.ps1 "`"a"
   ['"a', ]
   PS C:\PowerShell-7.1.3>
   ```
3. The call of an executable such as another PowerShell:
   ```
   PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "`"a"
   ['a', ]
   PS C:\PowerShell-7.1.3>
   ```
   or Python
   ```
   PS C:\PowerShell-7.1.3> C:\Python371\python.exe -c "import sys;print(sys.argv[1:])" "`"a"
   ['a']
   PS C:\PowerShell-7.1.3>
   ```
   drops the escaped double quote.

Some trials for a work-around with a PowerShell script:
```
PS> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "`"a"
['a', ]
PS> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "```"a"
['`a', ]
PS> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  """a"
['a', ]
PS> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "\""a"
['"a', ]
PS>
```

same with Python:
```
PS> C:\Python371\python.exe -c "import sys;print(sys.argv[1:])" """a"
['a']
PS> C:\Python371\python.exe -c "import sys;print(sys.argv[1:])" "```"a"
['`a']
PS> C:\Python371\python.exe -c "import sys;print(sys.argv[1:])" "\""a"
['"a']
PS>
```
Where the final trials produced the originally expected result - even though the backslash is not specified in the grammar [PowerShell-7.1 - B. Grammar](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-15?view=powershell-7.1) by *escaped-character*.

The latter leads me to the assumption, that the execution is actually performed in a DOS/cmd.exe like environment, thus escaped and quoted in accordance to the DOS/cmd.exe command line syntax rules. But I called a PowerShell executable at a PowerShell prompt. So I do not expect an intermediary DOS exec call with it's native command line syntax, which has significant differences.

In my case for example, when writing a scanner/lexer/tokenizer this would resultingly mean that in those cases:

A. The raw command line call string has to be parsed (at least?) twice:

   1. by a PowerShell syntax scanner
   2. the result again by a DOS/cmd.exe syntax scanner
   3. basically once again for the target process which expects to be executed within a PowerShell environment

B. The ARGV has to be expected as pre-parsed result from a pure PowerShell environment.

If this is true, this makes it actually a bit difficult to estimate the required command line for an less experienced user, if not for all. In particular for complex application calls.

The original call should pass the escaped double quote '`"' as a dumb character '"' to the subcall when this is an *escaped-character* as specified in the grammar specification. The command line call syntax should not change during the call process. At least it should be protected and/or transformed appropriately and passed transparently to the target executable. The user should have to apply one command line syntax only - PowerShell.

### Expected behavior

```console
PS> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "`"a"
['"a', ]

PS> C:\Python371\python.exe -c "import sys;print(sys.argv[1:])" "`"a"
['"a']
```

### Actual behavior

```console
PS> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "`"a"
['a', ]

PS> C:\Python371\python.exe -c "import sys;print(sys.argv[1:])" "`"a"
['a']
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rjmholt** [comment] 2021-08-12 15:24
Duplicate of #1995

**Closed** 2021-08-13 17:00 UTC
Labels: Resolution-Duplicate
