### ISSUE TITLE
New in PowerShell 7.3: Expressions are evaluated but aren't substituted with the results

### ISSUE THREAD

**Issue by conioh** [PowerShell/PowerShell#18668] opened 2022-11-28 12:04 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In certain contexts PowerShell 7.3 evaluates expressions (i.e. `$(Do-Something)`) but doesn't replace the expressions with the results of the evaluation.

Accepted behaviors are:
- Evaluate an expression AND replace the expression with the result of the evaluation.
  This is what happens usually and in expandable strings:
  > A string enclosed in double quotation marks is an _expandable_ string. Variable names preceded by a dollar sign (`$`) are replaced with the variable's value before the string is passed to the command for processing.
  > Also, in a double-quoted string, expressions are evaluated, and the result is inserted in the string.

  Source: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3#double-quoted-strings
- Not to evaluate an expression at all (and not to replace the expression because there's nothing to replace it with).
  This is what happens in verbatim strings:
  > A string enclosed in single quotation marks is a _verbatim_ string. The string is passed to the command exactly as you type it. No substitution is performed.

  Source: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3#single-quoted-strings

However evaluating an expressing _and_ not performing substitution is unacceptable.

Evaluating expressions in contexts where they are not replaced makes as much sense - that is, none - as the second line in the following code actually destroying the computer:

```powershell
PS C:\> "$(Get-Location)"
C:\
PS C:\> '$(Destroy-Computer)'
$(Destroy-Computer)
PS C:\>
```

This is wrong, dangerous and unacceptable.

This issue is related to #18502 but distinct from it.
That issue deals with commas preventing substitution.
Regardless of whether not performing substitution is appropriate in contexts other than verbatim strings and whether arguments that contains commas to external commands is one of those context, _in no case whatsoever_ should expressions that are not substituted be evaluated.

Since the verbal explanation in that issue wasn't clear enough to elicit the proper response I have also prepared a visual:

![a](https://user-images.githubusercontent.com/10606081/204272534-1788de8a-1e93-4ec4-8ad5-f909ee0edbca.jpg)

### Expected behavior

```console
PS C:\> #$PSNativeCommandArgumentPassing = "Legacy"
PS C:\> cmd /c echo foo,cd=$(Write-Host "completely insane"; "return")
completely insane
foo,cd=return
```

### Actual behavior

```console
PS C:\> cmd /c echo foo,cd=$(Write-Host "completely insane"; "return")
completely insane
foo,cd=$(Write-Host"completelyinsane";"return")
PS C:\>
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\>
```

**Comment by 237dmitry** [comment] 2022-11-28 13:13
![Screenshot 2022-11-28 160407](https://user-images.githubusercontent.com/78153320/204284787-ac0e1f9c-08d4-4389-93f6-1f77a43e1c3e.png)

**Comment by conioh** [comment] 2022-11-28 14:04
> ![Screenshot 2022-11-28 160407](https://user-images.githubusercontent.com/78153320/204284787-ac0e1f9c-08d4-4389-93f6-1f77a43e1c3e.png)
> 

Did you not see the part titled "environment data"?

**Comment by kilasuit** [comment] 2022-11-28 14:15
@conioh your steps to reproduce could have been a little clearer

however @237dmitry was showing that when you hadn't commented this out `$PSNativeCommandArgumentPassing = "Legacy"` prior to running `cmd /c echo foo,cd=$(Write-Host "completely insane"; "return")` that you do indeed get the desired result as can be shown in this screenshot on my system

![image](https://user-images.githubusercontent.com/6355225/204299356-ec0b64d7-007d-4ba5-b27f-a0d123663fbf.png)

**Comment by 237dmitry** [comment] 2022-11-28 14:18
> Did you not see the part titled "environment data"?

My Environment Data is the same.

**Comment by kilasuit** [comment] 2022-11-28 14:20
@237dmitry - I thought it would be but to many a prompt with `$` in it is often seen to be a unix like system.

**Comment by 237dmitry** [comment] 2022-11-28 14:26
> I thought it would be but to many a prompt with $ in it is often seen to be a unix like system.

What does it matter?

![Screenshot 2022-11-28 172416](https://user-images.githubusercontent.com/78153320/204301962-4d30f43d-ed3e-4400-aac7-1e909b9b40c3.png)

**Comment by conioh** [comment] 2022-11-28 16:54
> @conioh your steps to reproduce could have been a little clearer

@kilasuit, what's unclear? Please explain and I will attempt to improve the report.

> however @237dmitry was showing that when you hadn't commented this out `$PSNativeCommandArgumentPassing = "Legacy"` prior to running `cmd /c echo foo,cd=$(Write-Host "completely insane"; "return")` that you do indeed get the desired result as can be shown in this screenshot on my system

So if you perform different actions than those I have described you get different results?
That's hardly surprising and I don't see even a bit of relevance.

There are lots of other ways to "get the desired result" if you think the result is a string printed to the standard output:

```powershell
PS C:\> Write-Host "foo,cd=return"
foo,cd=return
```

This too "get[s] the desired result", but only with a malicious interpretation of the desired result.

The example is an _example_. The issue is "expressions are evaluated but aren't substituted with the results", not "I am unable to send to the standard output the string `foo,cd=return`".
Finding a different way to print that string is irrelevant. The issue is that PowerShell evaluates an expression where it shouldn't.

**Comment by mklement0** [comment] 2022-11-28 17:04
To provide some context:

* To me, this issue is a duplicate of #18502  (which is also mentioned in the initial post).
  * That the behavior exhibited there (and elaborated on here) should _never_ occur is a given, and doesn't need discussion as a _general hypothetical_.

    * Granted, the only official response to the linked bug report so far was [bewilderingly cavalier](https://github.com/PowerShell/PowerShell/issues/18502#issuecomment-1314583418), but I don't think anyone would actually argue that the behavior is _intentional_.

  *  By contrast, if there are other _actual bugs_ where this behavior manifests, they should be called out _specifically_, in their own bug reports.

* The behavior at hand is clearly a bug, and it was introduced in the context of introducing `$PSNativeCommandArgumentPassing` in 7.3.0
  * Expansion in the given scenario should _always_ occur, irrespective of the effective `$PSNativeCommandArgumentPassing` value.

**Comment by conioh** [comment] 2022-11-28 17:06
> My Environment Data is the same.

@237dmitry, no offence but I don't believe you.

_A few minutes later:_

> ![Screenshot 2022-11-28 172416](https://user-images.githubusercontent.com/78153320/204301962-4d30f43d-ed3e-4400-aac7-1e909b9b40c3.png)

I see that I was right.
On Windows the default value for `$PSNativeCommandArgumentPassing` is `"Windows"`. If you somehow changed it you're not using the same environment and if you did that intentionally that's dishonest.

Obviously I did not specify in the bug report "don't run any other command before the one I provided" and I also did not specify "use and empty PowerShell profile file" because that's implied in any bug report.

Perhaps your `Profile.ps1` file executes `Enter-PSSession` and everything entered after that happens in a remote computer against PowerShell 7.0? There's no way to anticipate all of this and it is generally understood that this is not to be done.

**Comment by mklement0** [comment] 2022-11-28 17:11
> The issue is that PowerShell evaluates an expression where it shouldn't.

In this case it actually _should_ evaluate the expression - as it always has - and therefore, of course, also perform _expansion_ (i.e. replace the subexpression with its (stringified) evaluation result in the argument); the latter part is now broken.

**Comment by jhoneill** [comment] 2022-11-28 17:14
@kilasuit 
> @conioh your steps to reproduce could have been a little clearer

It took me multiple readings are true

> 
> however @237dmitry was showing that when you hadn't commented this out `$PSNativeCommandArgumentPassing = "Legacy"` prior to running `cmd /c echo foo,cd=$(Write-Host "completely insane"; "return")` that you do indeed get the desired result as can be shown in this screenshot on my system

Yes. When legacy is set "return" and not "$(Write-Host "completely insane"; "return")"  is passed to the command all good. 
When it is not set   `$(Write-Host "completely insane"; "return")`  is sent. That is also expected 
What is not expected **is as well as** sending the literal string, to the command, any evaluation still happens. In other words

` cmd /c echo foo,cd=$(Write-Host "completely insane"; "return")  ` 
first does what $() tells it to do and gets the value of what is inside the brackets. @conioh  Write-Host doesn't write to standard output, it bypasses std-out and goes to the console. So we do a write host then send some text back. 
Now:  if the value is set to legacy `return` is sent,   
but   if the value is set to Windows `$(Write-Host "completely insane"; "return") `  is sent, 

Evaluating what's inside $() and sending the result makes sense. 
Not evaluating what's inside and sending $(blah blah) also makes sense
Evaluating what's inside  and the sending $(blah blah) is at best wildly counter intutitve, and as @mklement0  has just said while I've been typing, looks like a bug.

**Comment by mklement0** [comment] 2022-11-28 17:44
@jhoneill 

> When it [`$PSNativeCommandArgumentPassing = 'Legacy'`] is not set, `$(Write-Host "completely insane"; "return")` is sent. That is also expected

No - `$PSNativeCommandArgumentPassing` is unrelated to _expansion_ behavior, so its value shouldn't matter.

> Write-Host doesn't write to standard output

I think @conioh is aware of that and deliberately used `Write-Host` to demonstrate that despite the non-expansion, _evaluation_ still took place - which never makes sense and can be dangerous.

**Comment by conioh** [comment] 2022-11-28 17:47
@mklement0, the actionable thing is to _immediately_ stop evaluating expressions in those comma-containing command-line arguments contexts while we consider whether commas should affect argument parsing at all and try to find out what JamesWTruher meant, what is the mysterious bug he referred to etc.

I agree with you that the answer to this should be "no, commas should not affect this", but while that issue it being investigated this issue should be immediately fixed.

**Comment by kilasuit** [comment] 2022-11-28 17:51
@conioh - the team is predominantly US West coast based so only recently having got up and gotten online - so I hope that @SteveL-MSFT and team will look into this in the coming hours & hope that we will see a PR that can fix this soon enough

But please be realistic on timeframes as immediately just isn't possible here

**Comment by conioh** [comment] 2022-11-28 18:10
@kilasuit, I didn't mean "immediately" to be understood as  "within the hour" but more like "as soon as _reasonably_ possible". PowerShell 7.3.1 is a good place for this fix. PowerShell 7.4 is bad.

**Comment by jhoneill** [comment] 2022-11-28 18:48
> @jhoneill
> 
> > When it [`$PSNativeCommandArgumentPassing = 'Legacy'`] is not set, `$(Write-Host "completely insane"; "return")` is sent. That is also expected
> 
> No - `$PSNativeCommandArgumentPassing` is unrelated to _expansion_ behavior, so its value shouldn't matter.

I think you've quoted the wrong half of what I said.   If it is set to `legacy` the expanded value is sent., if not the expansion _still happens_ (because as you say `PSNativeCommandArgumentPassing` doesn't stop expansion happening) but the expanded result isn't sent. Which is hard to rationalize. 


> > Write-Host doesn't write to standard output
> 

> I think @conioh is aware of that and deliberately used `Write-Host` to demonstrate that despite the non-expansion, _evaluation_ still took place - which never makes sense and can be dangerous.

It was a comment made about std output

**Comment by mklement0** [comment] 2022-11-28 19:59
I'm not sure if there's still a disagreement, and maybe this is just about words, but to be clear: 

>  if not the expansion _still happens_ (because as you say PSNativeCommandArgumentPassing doesn't stop expansion happening)

_Expansion_ - meaning replacing the source code of the subexpression in the original, raw argument with the result of its evaluation - is _not_ happening in the case at hand - only _evaluation_ is (with the (success-stream-output) result getting _discarded_).

And it is the lack of _expansion_ that constitutes the bug.

> It was a comment made about std output

As an aside: I think it's better to use the term _success (output) stream_, so as to distinguish it from _stdout_, which only applies to external programs.

My comment was meant to point out the _intentional bypassing_ of the success-output stream with `Write-Host`, as simple proof that _evaluation_ happened.

**Comment by conioh** [comment] 2022-11-28 20:41
@mklement0, I mentioned "standard output" in passing in another comment, not in the root post and that's what @jhoneill referred to.
I thought it was immaterial to the matter at hand so I didn't reply to @jhoneill's comment about it and just fixed that comment.
But you're both technically right that `Write-Host` writes directly to the console (regardless of  stream redirection) and that PowerShell has multiple output streams (success/error/debug/...) and not just stdout and stderr.
I fixed that so we can move on.

Regarding the substantial issue here I think we're basically in agreement.

**Comment by jhoneill** [comment] 2022-11-29 09:42
@mklement0   yes, reading this last night my brain was swapping "expand" (the string) and "evaluate" (the expression) freely. 

The expression is being evaluated, (it runs)  whether or not the string is expanded  (text of expression replaced by its result as a string).  I think we've all got that.

**Closed** 2023-11-22 10:57 UTC
Labels: Needs-Triage, Resolution-No Activity
