### ISSUE TITLE
Invoke-command on remote PC/Server

### ISSUE THREAD

**Issue by schmidtmic** [PowerShell/PowerShell#2117] opened 2016-08-29 10:36 UTC
Steps to reproduce
------------------
Start Powershell;

`Invoke-Command -ComputerName some_name_for_WINPC -ScriptBlock {Get-WmiObject -Class Win32_ComputerSystem -Property Name } -Credential user_credentia`

Expected behavior
-----------------
Return Object containing the remote PC name

The command worked fine on Windows  but not on linux.

Actual behavior
---------------
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Clear()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.Finalize()
`

Environment data
----------------

PSVersion 6.0.0-alpha
PSEdition Core
PSCompatibleVersions {1.0,2.0,3.0,4.0....}
BuildVersion 3.0.0.0
GitCommitID v6.0.0-alpha.9
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

**Comment by andschwa** [comment] 2016-09-19 22:05
Per the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support), this is **not yet supported**.  Please follow the progress on the [PSRP on Linux repo](https://github.com/PowerShell/psl-omi-provider). Closing as duplicate of #942.

**Closed by andschwa** 2016-09-19 22:05 UTC
Labels: Area-Remoting, Issue-Enhancement, OS-Linux, OS-macOS
