### ISSUE TITLE
Get-ChildItem -Name and Get-ChildItem -Include / -Exclude unexpectedly follow symlinks with -Recurse

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9126] opened 2019-03-12 20:37 UTC
PowerShell Core (unlike Windows PowerShell) by default is supposed to _not_ follow symlinks (symbolic links) to directories during recursive traversal with `Get-ChildItem -Recurse` (you can opt in with `-FollowSymlink`).

While this generally works, using the `-Name` or `-Include` / `-Exclude` switches unexpectedly causes symlinks to be followed even without the `-FollowSymlink` switch.

Note: On _Windows_, the tests currently fail categorically, due to an unrelated bug: #9127

# Steps to reproduce (on Unix)

Run the following Pester tests:

```powershell
Describe "Get-ChildItem: symlink-following tests" {
  BeforeAll {
    Push-Location TestDrive:/
    # Create a directory with 2 files in it. 
    $null = New-Item -Type Directory someDir
    1..2 | % { $_ > "someDir/$_.txt" }
    # Create a symlink to that directory, as a sibling.
    New-Item -Type SymbolicLink someDirLink -Target someDir
  }
  AfterAll {
    Pop-Location
  }
  
  It "Get-ChildItem -Recurse doesn't follow dir. symlinks." {
    (Get-ChildItem -File -Recurse).Count | Should -Be 2
  }

  It "Get-ChildItem -Recurse -Path with a wildcard doesn't follow dir. symlinks." {
    (Get-ChildItem -File -Recurse -Path *).Count | Should -Be 2
  }

  It "Get-ChildItem -Recurse -Name doesn't follow dir. symlinks." {
    (Get-ChildItem -File -Recurse -Name).Count | Should -Be 2
  }

  It "Get-ChildItem -Recurse -Include doesn't follow dir. symlinks." {
    (Get-ChildItem -File -Recurse -Include *).Count | Should -Be 2
  }

  It "Get-ChildItem -Recurse -Exclude doesn't follow dir. symlinks." {
    (Get-ChildItem -File -Recurse -Exclude nosuch).Count | Should -Be 2
  }
  
}
```

# Expected behavior

All tests should pass.

# Actual behavior

The last 3 tests fail.

# Environment data

```none
PowerShell Core 6.2.0-rc.1
```

**Comment by ChrSchultz** [comment] 2019-03-13 17:05
on Windows all tests fails, 
Describing Get-ChildItem: symlink-following tests
    [-] Get-ChildItem -Recurse doesn't follow dir. symlinks. 6ms
      Expected 2, but got 3.
      15:     (Get-ChildItem -File -Recurse).Count | Should -Be 2
      at <ScriptBlock>, C:\Users\ic-sc\test.ps1: line 15
    [-] Get-ChildItem -Recurse -Path with a wildcard doesn't follow dir. symlinks. 5ms
      Expected 2, but got 3.
      19:     (Get-ChildItem -File -Recurse -Path *).Count | Should -Be 2
      at <ScriptBlock>, C:\Users\ic-sc\test.ps1: line 19
    [-] Get-ChildItem -Recurse -Name doesn't follow dir. symlinks. 7ms
      Expected 2, but got 3.
      23:     (Get-ChildItem -File -Recurse -Name).Count | Should -Be 2
      at <ScriptBlock>, C:\Users\ic-sc\test.ps1: line 23
    [-] Get-ChildItem -Recurse -Include doesn't follow dir. symlinks. 7ms
      Expected 2, but got 3.
      27:     (Get-ChildItem -File -Recurse -Include *).Count | Should -Be 2
      at <ScriptBlock>, C:\Users\ic-sc\test.ps1: line 27
    [-] Get-ChildItem -Recurse -Exclude doesn't follow dir. symlinks. 8ms
      Expected 2, but got 3.
      31:     (Get-ChildItem -File -Recurse -Exclude nosuch).Count | Should -Be 2
      at <ScriptBlock>, C:\Users\ic-sc\test.ps1: line 31
Tests completed in 146ms
Tests Passed: 0, Failed: 5, Skipped: 0, Pending: 0, Inconclusive: 0

**Comment by mklement0** [comment] 2019-03-13 17:11
@ChrSchultz: That is due to an _unrelated bug_, reported in #9127.

**Comment by Bertaz** [comment] 2022-10-09 01:41
By changing #L4 `New-Item -Type SymbolicLink someDirLink -Target someDir` into `New-Item -Type SymbolicLink someDirLink -Target .\someDir` the tests can ignore the unrelated bug.
That bug is specifically caused by #15161, which was closed as duplicate of the more comprehensive issue #15235. (#9127 is closed as fixed, but was only partially fixed)

Result:
```
Describing Get-ChildItem: symlink-following tests
  [+] Get-ChildItem -Recurse doesn't follow dir. symlinks. 5ms (4ms|2ms)
  [+] Get-ChildItem -Recurse -Path with a wildcard doesn't follow dir. symlinks. 5ms (4ms|1ms)
  [-] Get-ChildItem -Recurse -Name doesn't follow dir. symlinks. 7ms (7ms|1ms)
   Expected 2, but got 4.
   at (Get-ChildItem -File -Recurse -Name).Count | Should -Be 2, C:\pester\symFollow.Tests.ps1:23
   at <ScriptBlock>, C:\pester\symFollow.Tests.ps1:23
  [-] Get-ChildItem -Recurse -Include doesn't follow dir. symlinks. 8ms (8ms|1ms)
   Expected 2, but got 4.
   at (Get-ChildItem -File -Recurse -Include *).Count | Should -Be 2, C:\pester\symFollow.Tests.ps1:27
   at <ScriptBlock>, C:\pester\symFollow.Tests.ps1:27
  [-] Get-ChildItem -Recurse -Exclude doesn't follow dir. symlinks. 10ms (10ms|1ms)
   Expected 2, but got 4.
   at (Get-ChildItem -File -Recurse -Exclude nosuch).Count | Should -Be 2, C:\pester\symFollow.Tests.ps1:31
   at <ScriptBlock>, C:\pester\symFollow.Tests.ps1:31
Tests completed in 116ms
Tests Passed: 2, Failed: 3, Skipped: 0 NotRun: 0
```

**Closed** 2023-11-23 12:47 UTC
Labels: Issue-Bug, WG-Cmdlets-Management, WG-Engine-Providers, Area-FileSystem-Provider, Resolution-No Activity
