### ISSUE TITLE
Invoke-Webrequest very slow in Powershell 7 compared to 6 and 5.1

### ISSUE THREAD

**Issue by Terr4** [PowerShell/PowerShell#17762] opened 2022-07-24 20:50 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a performance issue with Invoke-Webrequest on PS 7.3.0-preview.6, compared to PS version 5.1 and 6 tested on Windows 10 and OSX.

Can be reproduced with the example URL below.
On PS 5.1 and 6 you get a return value after 1-2 seconds.
With PS 7 it takes around 70-80 seconds.

Reproducible on Windows 10 and OSX.
Please also see comparison videos.

### Expected behavior

```console
Invoke-WebRequest "https://www.libro.at/legor-30464-el-fuegos-stunt-kanone-polybag-30464-5702016668247.html" -Verbose
VERBOSE: GET https://www.libro.at/legor-30464-el-fuegos-stunt-kanone-polybag-30464-5702016668247.html
with 0-byte payload
VERBOSE: received 2586741-byte response of content type text/html

get a return value after 1-2 seconds
```

### Actual behavior

```console
Invoke-WebRequest "https://www.libro.at/legor-30464-el-fuegos-stunt-kanone-polybag-30464-5702016668247.html" -Verbose
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received 2586741-byte response of content type text/html

get a return value after 70-80 seconds
```

### Error details

```console
Performance on PS7 is very slow compared to PS5.1 and PS6
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.6
PSEdition                      Core
GitCommitId                    7.3.0-preview.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://www.youtube.com/watch?v=pNeat9bDuoQ

https://www.youtube.com/watch?v=qW3Bsr8ElsE

**Comment by iSazonov** [comment] 2022-07-25 03:23
The issue appeared after moving to .Net 7.0.

/cc @SteveL-MSFT for information.

**Comment by NoMoreFood** [comment] 2022-07-25 09:27
@Terr4 Is this issue consistent across common MIME types for you? I am able to reproduce this, but not when `-OutFile` is used so I'm guessing it's slowing down in the post-processing of the data.

**Comment by Terr4** [comment] 2022-07-25 14:03
> @Terr4 Is this issue consistent across common MIME types for you? I am able to reproduce this, but not when `-OutFile` is used so I'm guessing it's slowing down in the post-processing of the data.

I am only working with text/html responses, so unfortunately I cannot comment on other filetypes, but I also expected the postprocessing as the culprit so I tried -UseBasicParsing but without success.

I can confirm that it works very fast with -OutFile also on my side!

**Comment by SteveL-MSFT** [comment] 2022-08-01 21:02
This is quite interesting.  Trying it out I see that the progress bar indicates the content is received and then it hangs for a bit before returning the result.  Need to investigate what is happening between that time.

**Comment by SteveL-MSFT** [comment] 2022-08-01 21:16
Looks like the problem is that URL returns a large HTML page and the cmdlet is using a regex to try and find the charset.  This takes a long time.  I'm going to see if I can find an optimization.

**Closed** 2022-08-22 18:19 UTC
Labels: Waiting - DotNetCore, WG-Cmdlets-Utility, Needs-Triage, In-PR
