### ISSUE TITLE
Different behaviour of concatenated command line arguments for single quoted and double quoted strings.

### ISSUE THREAD

**Issue by ArnoCan** [PowerShell/PowerShell#15889] opened 2021-08-08 19:51 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The concatenation of double quoted strings behaves different from the same concatenation of single quoted strings. 

The concatenation of double quoted string arguments is as expected:
-> Call: C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" "a""b""c"
-> Result: ['abc']

While the concatenation of single quoted strings results in the pair-wise escape of the inner single quotes:
-> Call: PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" 'a''b''c'
-> Result: ["a'b'c"] 

I would expect the same consistent behaviour in this case as for double quotes.

### Expected behavior

```console
PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" "a""b""c"
['abc']
PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" 'a''b''c'
["abc"]   # <- EXPECTED
```

### Actual behavior

```console
PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" "a""b""c"
['abc']
PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" 'a''b''c'
["a'b'c"]  # <- ACTUAL
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2021-08-08 20:45
I think this probably has more to do with Python than it does with PS.

The expected behaviour for PS is the second one you illustrate here; doubling up quotes has the effect of inserting a literal quote. This is important especially for single-quoted strings, as there is otherwise no way of adding a literal single quote into a single-quoted string without using a here-string.

If you check these examples in PS itself, you can see PS's behaviour is consistent here:

```
PS> "a""b""c"
a"b"c

PS> 'a''b''c'
a'b'c 
```

**Comment by ArnoCan** [comment] 2021-08-09 02:07
The issue is about calling a command line of any callable and processing the passed ARGV within the called process. This is different from your example. The behaviour of the Python call is here the same as for a PowerShell callable. For example the short script:
```
write-host -NoNewline "["
for ( $i = 0; $i -lt $args.count; $i++ ) {
    write-host -NoNewline "'$($args[$i])', "
}
write-host "]"
```
Has the same behaviour as the Python one-liner:
```
PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "a""b""c"
['abc', ]
PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  'a''b''c'
['a'b'c', ]
PS C:\PowerShell-7.1.3>
```
As my main platform is Posix based - bash/sh/ksh - Linux/Unix/BSD - I would expect a consistent behaviour of concatenated quoted strings and also intermixed with non-quoted. Therefore the following examples are consistent, but in general not as expected:
```
PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  'a'b'c'
['a', 'bc', ]
PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "a"b"c"
['a', 'bc', ]
```
The same concatenation in case of the "bash" on WSL:
```
C:\Users\test>wsl python -c "import sys;print(sys.argv[1:])" "a"b"c"
['abc']

C:\Users\test>wsl python -c "import sys;print(sys.argv[1:])" 'a'b'c'
['abc']

C:\Users\test>
```
and on native Linux:
```
test:~$ python -c "import sys;print(sys.argv[1:])" "a"b"c"
['abc']
test:~$ python -c "import sys;print(sys.argv[1:])" 'a'b'c'
['abc']
test:~$ 
```
Therefore it seems to me that the concatenation of quoted strings at the command line is in general not consistent.

Two remarks:
1. I am currently writing scanner/tokenizer for command line call strings - for raw input as well as the pre-scanned ARGV. 
   For bash(Posix) + DOS/cmd.exe + PowerShell. The first is implemented in Python.
   This is the reason I have to deal in detail with the raw command line call string as well as the ARGV.

2. The pre-scan/parser of the input command line call of a shell is commonly a runtime library - e.g. libc - which 
   passes the ARGV to the main of the process. This is at the end  the same for scripts as well as C/C++, C#, 
   Python, DOS-Batch, PowerShell, Java, etc. 
    The program/script gets(commonly) the ARGV only, thus has no chance/means to split the command line by itself.

**Comment by ArnoCan** [comment] 2021-08-09 02:49
One additional info related to the difference of the call context for a command line and the pure evaluation at the PowerShell prompt.

The following command line calls work:
```PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  'a'b'c'
['a', 'bc', ]
PS C:\PowerShell-7.1.3> powershell.exe -noprofile -executionpolicy bypass -file  X:\print_argv_list.ps1  "a"b"c"
['a', 'bc', ]
```
But the pure evaluation at the PowerShell prompt of those example strings fails:
```
PS C:\Python371> 'a'b'c'
At line:1 char:4
+ 'a'b'c'
+    ~~~~
Unexpected token 'b'c'' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Python371> "a"b"c"
At line:1 char:4
+ "a"b"c"
+    ~~~~
Unexpected token 'b"c"' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\Python371>
```

**Comment by SeeminglyScience** [comment] 2021-08-09 03:13
Note that it's not actually concatenation, doubling up the quotes works as an escape. e.g. `echo 'they''re here'` gives a string object whose value is `they're here`.  This is further confused by the fact that PowerShell strips inner double quotes, but not single quotes, when calling native executables like python.

**Comment by ArnoCan** [comment] 2021-08-09 04:09
@SeeminglyScience
I agree that this is in principle the current implementation, but 
1. it seems not to be really consequent and with some inconsistent behaviour
2. i really tried to find sufficiently detailed documentation - but failed

Therefore see also #15888, with the cases of strings with the concatenation of differently quoted strings:
```
"a"'b'"c"
```
and
```
'a'"b"'c'
```
As I have written in #15888 these are concatenated and therefore basically have no SEPERATOR(as I interpret and same as Posix specification). Therefore these should be tokenized into one string, but actually are treated as 3 separate tokens.

I have the impression, that the tokenization seems not to be consistent. This in particular as I am currently implementing a scanner/lexer/tokenizer for the static tokenization of command lines. This comprises in particular the processing of quotes and escapes(which themself are partially tricky) without dynamic replacement such as variables and subcalls.

**Comment by rjmholt** [comment] 2021-08-12 15:24
Duplicate of #1995

**Closed** 2021-08-13 17:00 UTC
Labels: Resolution-Duplicate, Issue-Question
