### ISSUE TITLE
Defunct ssh processes and CPU load are kept after executing powershell through ssh on linux

### ISSUE THREAD

**Issue by jwboon-t4e** [PowerShell/PowerShell#13356] opened 2020-08-05 10:16 UTC
## Steps to reproduce
Setup powershell ssh on linux system using the following guide: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7

On the host machine (debian 10) execute the following command.

```
Invoke-Command -ScriptBlock {return "kaas";} -SSHTransport -HostName ps@localhost -KeyFilePath /home/ps/.ssh/id_rsa
```

## Expected behavior

No defunct processes from SSH on the machine executing PowerShell.

## Actual behavior

Each execution of the PowerShell script leaves a defunct ssh process. See example of 'ps aux' below. 

On the parent process there remains a CPU load which is unexpected for a server application. This becomes a major issue with a large amount defunct processes which seems to stack the CPU load on the parent process.

```
root@<machine>:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   3880  1504 ?        Ss   09:34   0:00 /bin/bash /entrypoint.sh
root        21  0.1  1.1 3794740 70496 ?       Sl   09:34   0:02 dotnet <dll>
root        81  0.0  0.0   4012  3116 pts/0    Ss   09:35   0:00 bash
root       338  0.0  0.0   4012  3196 pts/1    Ss   09:39   0:00 bash
root      1201  0.0  0.4 2968504 27624 pts/0   Sl+  09:53   0:00 pwsh
root      1209  1.9  2.0 4157756 125756 pts/0  Sl+  09:53   0:04 dotnet /root/.dotnet/tools/.store/powershell/7.0.3/powershe
root      1240  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1247  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1253  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1267  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1274  0.0  0.0      0     0 pts/0    Z+   09:53   0:00 [ssh] <defunct>
root      1373  0.3  0.0      0     0 pts/0    Z+   09:57   0:00 [ssh] <defunct>
root      1377  0.0  0.0   7652  2684 pts/1    R+   09:57   0:00 ps aux 
```

## Environment data

Host machine:

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Target machine:

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The configuration is that this is a Docker container (host) running a sidecar container (target).

The used image for the host is: 'mcr.microsoft.com/dotnet/core/aspnet:3.1'
The used image for the target is 'mcr.microsoft.com/powershell'

**Comment by daxian-dbw** [comment] 2020-08-05 21:21
Quoted from https://askubuntu.com/questions/201303/what-is-a-defunct-process-and-why-doesnt-it-get-killed

> "defunct" means the process has either completed its task or has been corrupted or killed, but its child processes are still running or these parent process is monitoring its child process.

> Processes marked <defunct> are dead processes (so-called "zombies") that remain because their parent has not destroyed them properly.

/cc @PaulHigin for insights.

**Comment by PaulHigin** [comment] 2020-08-06 17:56
I suspect this is due to the way we create the SSH client process to ignore the termination signal (SIG_IGN):

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2220

This was done so that a 'Ctrl+C' keyboard command during a remote session does not terminate the SSH client process (and thus the remote connection), but instead is passed on through the PSRP protocol to stop a running remote command, as expected.

These defunct SSH processes are terminated when the parent pwsh process is terminated.  So that is a (not very satisfactory) workaround.

But I am not enough of a Linux expert to know the right way to have PowerShell ensure the process is terminated, on remote connection close.  Perhaps someone in the community would know?

**Comment by daxian-dbw** [comment] 2020-08-07 23:37
I found the following from the wiki [Zombie process](https://en.wikipedia.org/wiki/Zombie_process)

> defunct process is a process that has completed execution (via the exit system call) but still has an entry in the process table: it is a process in the "Terminated state". This occurs for the child processes, where the entry is still needed to allow the parent process to read its child's exit status: once the exit status is read via the wait system call, the zombie's entry is removed from the process table and it is said to be "reaped".

I think we probably just need to call [waitpid](https://man7.org/linux/man-pages/man2/wait.2.html) after the ssh process is terminated. An example from the wiki:

```c
int main(void)

{
  pid_t pids[10];
  int i;

for (i = 9; i >= 0; --i) {
    pids[i] = fork();
    if (pids[i] == 0) {
        printf("Child%d\n",i);
        sleep(i+1);
        _exit(0);
    }
}

for (i = 9; i >= 0; --i){
    printf("parent%d\n",i);
    waitpid(pids[i], NULL, 0);
    }
return 0;
}
```

**Comment by PaulHigin** [comment] 2020-08-10 16:25
We can experiment with this.  I am concerned about calling a blocking function.  Since the child process is created without SIG_IGN, I don't know if it will respond to the call, and I hope we don't end up with a hang.  I just don't know enough about Linux processes, but we can see what works.

**Comment by jwboon-t4e** [comment] 2020-10-08 09:50
Hi guys, any update on this ticket?

**Comment by ncvanleeuwen** [comment] 2020-11-19 11:07
I'm experiencing the same issue, any update?

**Comment by awakecoding** [comment] 2020-11-19 13:58
We are facing the same issue, PowerShell leaves defunct ssh processes after the connection is closed. We are working on implementing PowerShell remoting over SSH, without SSH (https://blog.devolutions.net/2020/07/powershell-remoting-over-ssh-without-ssh) with a drop-in replacement for the 'ssh' executable. We originally thought this was limited to our custom way of doing it, until we figured out that the real PowerShell remoting over SSH with the OpenSSH client exhibited the same symptoms.

**Comment by awakecoding** [comment] 2020-11-19 15:13
I found more information about the Ctrl+C / SIGINT behaviour in a regular SSH session here: https://goteleport.com/blog/ssh-client-signal-handling/

It appears to me that in a regular OpenSSH session, the client does not ignore but forwards the signals to the remote host. This effectively means the OpenSSH client does not process the signal for itself, I tried doing Ctrl+C multiple times locally and it wouldn't kill the OpenSSH client. This appears to be close to the approach taken by PowerShell: it spawns the OpenSSH client process but makes it ignore the signals so the PowerShell client can forward them over PSRP to the remote host.

The main issue I see with the current code is that the defunct ssh processes remain until the parent process (pwsh) is killed. This can be very problematic when spawning multiple PowerShell sessions within the same pwsh process, because you would get a defunct ssh process for each.

Other people have suggested calling waitpid, which is normally a blocking call. [There is a WNOHANG flag that can be passed to waitpid](https://www.gnu.org/software/libc/manual/html_node/Process-Completion.html), but we'd have to look into how portable this flag is (is it only with a Linux glibc?).

In all cases, I think attempts to fix this would need to be added in the part of code called when the PowerShell remoting session is freed. Can anybody point to where that would be? The code creating the ssh process is easy to find, but it is not so clear to me where the code freeing the PowerShell remoting session for SSH is being called. The goal would be to call some cleanup code at that point in time where we are sure that the ssh process should either be cleaned up if defunct, or force killed if still there.

This procedure would attempt the following, in order:
- waitpid + WNOHANG for a defunct process
- force kill process (SIGKILL) if process is "alive"

Force killing the process is obvious the last resort, but it shouldn't happen under normal circumstances, it's just there to ensure we clean up the process in all possible cases. Most of the time, we would just find the defunct process and clean it up by calling waitpid.

**Comment by PaulHigin** [comment] 2020-11-19 17:10
The code already tries to terminate the SSH client process on remote session termination (and other error conditions).  We need to investigate why that isn't happening, but I know that .NET 'System.Diagnostics.Process' does not always work the same over different platforms.
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs#L1654

The fact that terminating the parent pwsh process terminates the SSH client process mitigates this somewhat.

**Comment by PaulHigin** [comment] 2020-11-19 23:14
I verified that the clean up code does run.  However, the issue is not terminating the SSH process, it is terminated, but the fact that it still exists as a 'zombie' process to the parent process as @daxian-dbw  describes above.  We can try using `waitpid` during clean up as Dongbo suggests above, but again my concern with that is hanging PowerShell during the wait.

**Comment by awakecoding** [comment] 2020-11-20 02:26
@PaulHigin waitpid + the WNOHANG flag should make the call non-blocking. I think this flag may be Linux-specific, but it can't hurt to try it out. Here is an example: https://stackoverflow.com/a/7255053

**Comment by dinhngtu** [comment] 2021-01-19 19:10
After looking a bit into this, it seems like OutOfProcTransportManager (and therefore RunspaceConnectionInfo) uses its own implementation of fork/exec in libpsl for spawning SSH instead of using System.Diagnostics.Process. I'm not sure why it's done this way so could someone chime in?

Regardless, the easiest fix for this would be to fix System.Diagnostics.Process.WaitForExit() to call waitpid() for unmanaged processes, and then calling WaitForExit() after killing SSH.

**Comment by PaulHigin** [comment] 2021-01-19 19:41
The custom fork/exec was added to modify the 'Ctrl+C' sigint, which interferes with PowerShell remoting.  .NET team declined to support it so it had to be added as custom.

I am not optimistic that .NET will accept a change like this for WaitForExit(), but it may be worth a try.  Otherwise more custom code will have to be added.

**Comment by dinhngtu** [comment] 2021-01-19 19:51
waitpid() is safe for nonchild processes, and it's arguable that WaitForExit() reaping unmanaged children is actually what we want. Another solution is to add waitpid() to libpsl and call it ourselves.

In any case, this is a behavior I need to fix so I can help with making a patch.

**Closed** 2021-06-03 20:19 UTC
Labels: Issue-Question, WG-Remoting

**Comment by et1975** [comment] 2021-11-26 17:04
@adityamandaleeka  This is still an issue with 7.2:
>    41 root      0:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
  124 scriptin  0:17 [pwsh]
  326 scriptin  0:15 [pwsh]
  531 scriptin  0:17 [pwsh]
  743 scriptin  0:16 [pwsh]
  946 scriptin  0:16 [pwsh]
 1154 scriptin  0:16 [pwsh]
 1361 scriptin  0:17 [pwsh]
 1571 scriptin  0:16 [pwsh]
 1775 scriptin  0:17 [pwsh]
 1983 scriptin  0:16 [pwsh]

The use case is creating a Runspace via SSH. I'm available on Teams for details if needed.

**Comment by iSazonov** [comment] 2021-11-26 17:12
@et1975 Can you share `ps aux` output?

**Comment by dinhngtu** [comment] 2021-11-26 17:26
I can't reproduce the issue with manual runspace creation.

I used the following script:

```
PS > $ssh=[System.Management.Automation.Runspaces.SSHConnectionInfo]::new($null, "*****", $null)
PS > $rs=[runspacefactory]::CreateRunspace($ssh)
PS > $rs.Open()
PS > $ps=[powershell]::Create($rs)
PS > $ps.Commands.AddCommand("uname").AddArgument("-a")

Commands
--------
{uname}

PS > $ps.Invoke()
Linux *****
PS > $ps.Dispose()
PS > $rs.Close()
```

After the runspace is closed I couldn't see any zombie processes on either side of the connection.

**Comment by et1975** [comment] 2021-11-26 17:46
Intersting, this is more or less what I'm doing as well, but I'm using this workaround: https://github.com/PowerShell/PowerShell/issues/15641
I'm also calling `Dispose()` instead of `Close()` on the Runspace.

> PID   USER     TIME  COMMAND
    1 root      1:09 /opt/agent/Agent
   41 root      0:00 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups
  124 scriptin  0:17 [pwsh]
  326 scriptin  0:15 [pwsh]
  531 scriptin  0:17 [pwsh]
  743 scriptin  0:16 [pwsh]
  946 scriptin  0:16 [pwsh]
 1154 scriptin  0:16 [pwsh]
 1361 scriptin  0:17 [pwsh]
 1571 scriptin  0:16 [pwsh]
 1775 scriptin  0:17 [pwsh]
 1983 scriptin  0:16 [pwsh]
 
 This is on Alpine after 10 runs, the Agent is the one opening the runspaces.

**Comment by iSazonov** [comment] 2021-11-27 17:53
> This is on Alpine after 10 runs, the Agent is the one opening the runspaces.

If the process is still live this could be the reason. Do you see zombie processes after Agent termination?
