### ISSUE TITLE
Linux pwsh enables DECCKM, but Windows pwsh cannot handle it; arrow keys stop working after exiting linux powershell

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/PowerShell#12268] opened 2020-04-06 20:53 UTC
# Steps to reproduce

1. Use Windows PowerShell 7 and PowerShell 7 in WSL.
2. Launch Windows Powershell in Windows Terminal
3. Launch wsl, `pwsh`
4. Exit Linux powershell
5. Observe the arrow keys

Linux powershell emits the escape sequence `DECSET` `DECCKM`[1] on startup before it emits the first prompt.

This reconfigures the cursor keys, which usually emit `CSI A...D`, to emit `SS3 A...D` instead.

Linux powershell can handle `SS3` arrow key sequences. This is fine.

When Linux powershell exits, it _does not restore `DECCKM` to its original state_. All applications that manipulate global terminal state are expected to return the terminal to "normal" once they are done.

Because the state is not restored when you exit Linux powershell, Windows powershell (which doesn't know that the terminal state has been changed) will start to receive `SS3` arrow key sequences.

Windows powershell _cannot_ handle `SS3` arrow key sequences, and it ignores them, so the arrow keys do not work.

This also reproduces when you SSH to a linux machine, but WSL is easier for a self-contained repro.

# Expected behavior

`DECCKM` is disabled on exit.

# Actual behavior

`DECCKM` remains enabled on exit, downstream applications get confused.

# Environment data

```none
(dhowett-sl) ~ % $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

(dhowett-sl) ~ % wsl pwsh -c '\$PSVersionTable'

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

[1] Notes about DECCKM

```
CSI ? Pm h
          DEC Private Mode Set (DECSET).
            Ps = 1  ⇒  Application Cursor Keys (DECCKM), VT100.
```

DECCKM reconfigures the arrow keys as follows

```
Key            Normal     Application
-------------+----------+-------------
Cursor Up    | CSI A    | SS3 A
Cursor Down  | CSI B    | SS3 B
Cursor Right | CSI C    | SS3 C
Cursor Left  | CSI D    | SS3 D
-------------+----------+-------------
```

[2] I've investigated PowerShell, PSReadline and dotnet/runtime, and I cannot determine where DECCKM is being enabled.

**Comment by DHowett-MSFT** [comment] 2020-04-06 20:56
Originally filed: https://github.com/microsoft/terminal/issues/5257

**Comment by LookoutHill** [comment] 2020-04-06 21:04
@DHowett-MSFT As a workaround it seems like one could create a script that would emit the appropriate reset sequence. Would you post this sequence in PowerShell string format?

**Comment by DHowett-MSFT** [comment] 2020-04-06 21:05
```
"`e[?1l"
```

**Comment by LookoutHill** [comment] 2020-04-06 21:26
Thanks for that. It gave me enough info to interpret this arcane knowledge. That sequence doesn't restore functionality, but the "Reset to Initial State" sequence ("`ec") does.

**Comment by DHowett-MSFT** [comment] 2020-04-06 21:35
It legitimately looks like it's being stripped out of the output.

When I type this:

```
(dhowett-sl) ~ % "a`e[?1lb"
```

I get this out of the pty:

```
ab
```

but when I run this:

```
(dhowett-sl) ~ % wsl printf 'a\\e[?1lb'
```

I get

```
a␛[?1lb
```

I wonder why it's being filtered from powershell's output stream. Similar sequences, like "`e[?2004l", are not.

**Comment by DHowett-MSFT** [comment] 2020-04-06 21:37
As a workaround, you can do this:

```
"`e[?;1l"
```

Masking that you're requesting DECRST 1 by placing a `;` before it confuses powershell, but Terminal can understand it.

**Comment by iSazonov** [comment] 2020-04-07 05:10
>  I've investigated PowerShell, PSReadline and dotnet/runtime, and I cannot determine where DECCKM is being enabled.

Wow! 
/cc @daxian-dbw who have huge experience in the area.

**Comment by DHowett-MSFT** [comment] 2020-04-08 01:16
Of note, this reproduces without PSReadline available :smile:

(I tracked down why I can't forcibly print "`e[?1l" -- PowerShell isn't using VT input on _Windows_, so that value is technically meaningless to it. Conhost is ignoring it.)

**Comment by lukaszroz** [comment] 2020-09-01 22:13
I have come across this bug when I SSH from Ubuntu to Windows machine. It works when I SSH from Bash without starting PowerShell. To reproduce in PowerShell on Ubuntu in Gnome Terminal:

```
$ cat #try up/down/right/left arrow, Enter, Ctrl-D
^[[A^[[B^[[C^[[D

$ pwsh
PowerShell 7.0.3
> ssh user@host
PowerShell 7.0.3
> exit #arrow keys don't work
Connection to host  closed.
> exit
$ cat #try up/down/right/left arrow, Enter, Ctrl-D
^[OA^[OB^[OC^[OD
ABCD
```

After some digging I have found dotnet/corefx#6488. The Pull Request fixed a number of bugs related to terminal escape codes handling. It seems to me the DECCKM might be set in System.Console, see [lines 937 - 947](https://github.com/dotnet/runtime/blob/2f1ece19ff8e4a4fe903a8df6ac66f76d2d1dec3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L937)

**Comment by lukaszroz** [comment] 2020-09-01 22:17
Found the issue: https://github.com/dotnet/runtime/issues/27626

**Comment by DHowett** [comment] 2020-09-01 23:25
Excellent investigation. Thanks!

**Comment by tig** [comment] 2020-10-21 16:26
Tagging @TylerLeonhardt so he's aware of this relative to https://github.com/PowerShell/GraphicalTools

Specifically, this is why `out-consolegridview` has issues on Linux where the cursor keys don't work after using it.  Related to https://github.com/PowerShell/GraphicalTools/issues/99.

**Comment by mklement0** [comment] 2020-10-22 21:53
> This also reproduces when you SSH to a linux machine

There is another case, namely an "intra-Unix" one:

The cursor keys in `ksh` only work if application-cursor mode  is _off_ (`keypad_local` / `rmkx`)

Since PowerShell unconditionally turns that mode _on_  (`keypad_transmit` / `smkx`), even a simple call to the PowerShell CLI such as 
 `pwsh -noprofile -c 'get-date'` 
breaks cursor-key handling in `ksh`.

(`bash` and `zsh` are _not_ affected, because they work in _either_ mode.)

**Comment by iSazonov** [comment] 2021-01-16 10:22
How can we detect whether SS3 mode is on?

**Comment by DHowett** [comment] 2021-01-16 19:44
You don’t need to detect it. An application should set the states it needs on startup and _set them back to reasonable defaults for a terminal_ on exit. Nothing to remember, nothing to restore.

**Comment by mklement0** [comment] 2021-01-17 02:06
@DHowett, this isn't so much about _terminals_, but about the _shells_ that run in them, and as my previous comment implies, different shells:

* require different settings

* seem to rely on commands they invoke _not_ to change these settings.

For instance:

* `ksh` malfunctions if a command turns application-cursor mode _on_ and _leaves it on_.

* `pwsh` malfunctions if a command turns application-cursor mode _off_ and _leaves it off_.

Therefore, while it may be a challenge to implement, _restoring_ the previous state seems like the right thing to do.

**Comment by DHowett** [comment] 2021-01-17 02:12
@mklement0 I'm _also_ not talking about terminals. As the reporter of the issue and engineering owner for a terminal, I'm supposed to be aware of how applications expect to work... so here goes:

A shell that cannot go from a terminal left in its default state **is broken**.
A shell that requires a state that is different from the default *must* restore the default when it exits naturally or launches an application that will bootstrap from the default state¹. If it does not do so, **it is broken.**

Introducing another back-and-forth call/response to determine the application keypad mode state -- ESPECIALLY if you're going to do it every time input returns to the user -- is madness. It limits the ability of users to pre-fill the keyboard input queue and the ability for terminals and applications across high-latency links to properly coordinate. There's a default assumption here: applications are started with the terminal in its default state, and applications that start other applications return the terminal to its default state.

¹ Per the above axiom, this is all applications.

**Comment by DHowett** [comment] 2021-01-17 02:14
Your example above indicates that ksh is operating as expected (terminal not in default state => it isn't expected to get to the state it needs when that state is the default state) and that pwsh is broken (it expects a non-default state, but does not request it.)

**Comment by mklement0** [comment] 2021-01-17 02:52
@DHowett:

Given your premise, PowerShell is broken in _two_ respects:

* (a) Intra-session, it doesn't actively restore application keypad mode after running a command, even though it should expect the mode to _potentially_ have been reset to the default state, i.e., off.

* (b) On exiting a session, it doesn't reset the terminal to the default state (it doesn't turn application keypad mode off again).

Fixing (a) would require the very back-and-forth you think should be avoided - even though probably only a minority of commands (other shells, CUIs) change the terminal state.

So I gather that:

* the conclusion is that PowerShell shouldn't require application keypad mode to be ON for its own sake, correct?

* if you have any insight on what such a change would entail technically / if it is feasible at all, please share.

**Comment by DHowett** [comment] 2021-01-17 03:20
So, I do think powershell (or according to an earlier comment, the .NET runtime 😦) is broken here.

Before reading user input where it cares about the format of the arrow/line editing keys, it should set the mode it wants. After it's done, it should reset that mode. That's _very cheap_, and it doesn't require any back-and-forth.

I've observed zsh doing this:

1. Emit `\e[?1h` (enable DECCKM)
2. Emit my prompt
3. Accept input
4. On CR/LF, emit `\e[?1l` (disable DECCKM)
5. Spawn an application
6. Application exits.
7. GOTO 1.

There's no querying, just assertion. "DECCKM should be on now." "DECCKM should be off now." It never needs to know the state, because of two things:

1. If DECCKM is off, `\e[?1h` turns it on.
2. If DECCKM is on, `\e[?1h` does nothing.

**Comment by iSazonov** [comment] 2021-01-19 12:36
@DHowett Many thanks! I think we should ask @SteveL-MSFT to add this in next milestone plan.

**Comment by tig** [comment] 2021-01-22 17:55
@SteveL-MSFT & @TylerLeonhardt - is there a PowerShell issue tracking this?

This impacts `Out-ConsoleGridView` pretty significantly: https://github.com/PowerShell/GraphicalTools/issues/134

**Comment by DHowett** [comment] 2021-01-22 19:09
![image](https://user-images.githubusercontent.com/189190/105534355-38109400-5ca2-11eb-853c-cce21fb49501.png)

This appears to _be_ the PowerShell issue tracking this. o_O

**Comment by wez** [comment] 2021-03-03 16:28
FWIW, this issue also applies to users of powershell on macos, running in any terminal emulator--it's not linux-specific.

**Comment by SteveL-MSFT** [comment] 2021-03-04 14:15
The problem is https://github.com/dotnet/runtime/issues/27626

**Comment by wez** [comment] 2021-03-04 15:11
Please also disable that mode when running child processes!

**Comment by iSazonov** [comment] 2021-03-04 15:24
@wez Welcome to review #14943. You can download artifacts there and check its locally.

**Comment by iSazonov** [comment] 2021-03-04 16:28
@wez You can just download the compiled artifacts, tests them in your environment and give a feedback before the PR will be merged.

**Comment by mklement0** [comment] 2021-03-04 17:02
@wez, you can _emulate_ what the PR will implement as follows:

```powershell
$Host.UI.Write("`e[?1l"); gh auth login; $Host.UI.Write("`e[?1h")
```

For entire-session support - as a stopgap that should also work for older PS versions - you can place the following at the end of your `$PROFILE` file:

```powershell
# Turns application key mode ON before displaying the PS prompt and back OFF right after.
$function:PSConsoleHostReadLine = " `$Host.UI.Write(`"``e[?1h`"); $function:PSConsoleHostReadLine; `$Host.UI.Write(`"``e[?1l`") "
# For non-interactive invocations of the PowerShell CLI: turn application-key mode off too, 
# So that it is left OFF on exiting (obviously won't work for -NoProfile invocations).
$Host.UI.Write("`e[?1l")
```

**Comment by wez** [comment] 2021-03-04 17:05
Thanks, but I don't use powershell; as I mentioned above, I'm just here because this issue was raised by one of the users of my terminal.  @gaborbernat: perhaps you could try those suggestions?

**Comment by gaborbernat** [comment] 2021-03-04 18:21
I can confirm that @mklement0 solution works on:

```
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Closed** 2021-04-01 20:01 UTC
Labels: Issue-Bug, OS-Linux, WG-Interactive-Console, Waiting - DotNetCore
