### ISSUE TITLE
Can't execute powershell commands from the code in the docker container or azure webjob

### ISSUE THREAD

**Issue by antondats** [PowerShell/PowerShell#9467] opened 2019-04-25 14:45 UTC
Hello,

I have a question about powershell core in the docker container or in the azure webapp.
I develop some webjob(.net core app) that tries to execute powershell commands using the Microsoft.PowerShell.Commands.Diagnostics, Microsoft.PowerShell.SDK, Microsoft.WSMan.Management packages(version 6.2.0).
In my local environment(I've installed powershell 6 and I have powershell 5 as default) the webjob works correct without any issues. Then I try to deploy the webjob in the linux docker container. The dockerfile has some instruction for installing powershell core 6.2.0 in the container. So, docker container(OS Debian 9) with my webjob runs with installed powershell core. Then my code tries to execute the following command:
```
using (PowerShell ps = PowerShell.Create())
{
   ps.AddScript("Get-PackageProvider -ListAvailable");
   var results = ps.Invoke();
}
```
and after that I get the following error:

> Unhandled Exception: System.AggregateException: One or more errors occurred. (The term 'Get-PackageProvider' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.) ---> System.Management.Automation.CommandNotFoundException: The term 'Get-PackageProvider' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
> at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin, ExecutionContext context)
> at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
> at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
> at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
> at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
> at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
> at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> --- End of inner exception stack trace ---

The same issue I have in azure. When I run webjob I get that error.
I've already googled a lot of sources and tried a lot of different solutions but any of them didn't help me.
Could you help me, please?
Why this issue isn't reproduce in my local environment but only in azure and container?

Thanks!

**Comment by fmichaleczek** [comment] 2019-04-25 17:52
@antondats The informations you need to understand the whole chain :

The error said "Get-PackageProvider" not found.

Get-PackageProvider is a command from module packagemanagement [get-packageprovider](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-packageprovider?view=powershell-6)

The environment variable that declare module path : [Modifying the PSModulePath Installation Path](https://docs.microsoft.com/en-us/powershell/developer/module/modifying-the-psmodulepath-installation-path)

There is preference variable that configure PSModule Autoloading [PSModuleAutoloadingPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-6#psmoduleautoloadingpreference)

This is the command for import module [Import-Module](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-6)

I advice you to verify where is packagemanagement module,if it's in the env:PSModulePath, verify PSModuleAutoloadingPreference, and use Import-Module.

PS : it's a community response to help you quickly but it's not a problem in this repository

**Comment by antondats** [comment] 2019-04-26 11:16
@fmichaleczek Thanks for the answer) 
But in docker container there is PSModulePath with valid data about path to the packagemanagement module. And when I connect to container I can execute "Get-PackageProvider" command without any errors but when command is executed from the code in my webjob, I get an error. 
So, I thing problem is with powerhell packages. It seems that these packages can't run powershell core in the docker container. (the same issue there is azure webjob)

**Comment by TravisEz13** [comment] 2019-04-26 23:12
What container are you talking about?  Can we see the Dockerfile for this container?

**Comment by antondats** [comment] 2019-04-29 09:38
@TravisEz13 Yes, of course) 
This is my docker file for windows container: 
```
FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY [<All my files and projects>]
RUN dotnet restore "WebJob.csproj"
COPY . .
WORKDIR "/src/WebJob"
RUN dotnet build "WebJob.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebJob.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
COPY ["pathtopowershell/PowerShell/", "PowerShell/"]
ENTRYPOINT ["dotnet", "WebJob.dll"]
```
Container starts without any errors and PSModulePath is set correct.

I've also tried with linux containers but I get the same error:
```
FROM microsoft/dotnet:2.1-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY [<all my files and projects>]
RUN dotnet restore "WebJob.csproj"
COPY . .
WORKDIR "/src/WebJob"
RUN dotnet build "WebJob.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebJob.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

RUN apt-get update
RUN yes | apt-get install curl gnupg apt-transport-https 
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list' 
RUN apt-get update 
RUN apt-get install -y powershell --allow-unauthenticated

ENTRYPOINT ["dotnet", "WebJob.dll"]
```

I think it is not a problem because the same issue I have when I deploy webjob in azure webjob.

**Comment by TravisEz13** [comment] 2019-04-29 17:47
@PoshChan Please remind me in 7 days

**Comment by TravisEz13** [comment] 2019-04-29 17:47
@antondats I'm at dockercon.  I'll try to look at this, but I cannot guarantee.

**Comment by TravisEz13** [comment] 2019-04-29 17:51
@PoshChan Please remind me in 7 days

**Comment by TravisEz13** [comment] 2019-04-29 17:55
FYI, this issue might have been better if filed in https://github.com/powershell/powershell-docker , but either way it goes to me for now.

**Comment by fMichaleczek** [comment] 2019-05-01 03:09
@antondats @TravisEz13 in my opinion, it's a dupe of [#8625](https://github.com/PowerShell/PowerShell/issues/8625)

**Comment by TravisEz13** [comment] 2019-05-01 19:06
@fMichaleczek Agreed.

**Closed by TravisEz13** 2019-05-01 19:06 UTC
Labels: Issue-Question, Resolution-Duplicate
