### ISSUE TITLE
PowerShell cannot have a pipeline with more then 2 native processes with redirected stdin

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3321] opened 2017-03-13 20:23 UTC
Steps to reproduce
------------------

```
ps aux | grep powershell | grep -v grep
```

Expected behavior
-----------------

Return filtered results. I.e. same as

```
PS > $a = ps aux | grep powershell; $a | grep -v grep
vors          2995   7.4  0.3  4813880  44460 s000  S+   11:07AM   0:10.07 -powershell
vors          6628   0.0  0.1  4810520  19192 s001  S+   11:35AM   0:02.51 -powershell
```

Actual behavior
---------------

Pipeline hanging (first grep never receives "output closed" event, besides the fact that corresponding stream is disposed)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                                                       
----                           -----                                                                                                                                                       
PSVersion                      6.0.0-alpha                                                                                                                                                 
PSEdition                      Core                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                     
BuildVersion                   3.0.0.0                                                                                                                                                     
GitCommitId                    v6.0.0-alpha.17                                                                                                                                             
CLRVersion                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                         
SerializationVersion           1.1.0.1    
```

**Comment by vors** [comment] 2017-03-22 19:35
I'd treat is a high priority, because it makes impossible to have any pipeline with 2 or more native commands (when both have stdin redirected).

The simpler repro is `1 | grep 1 | grep 1`

**Comment by SteveL-MSFT** [comment] 2017-03-22 19:41
CC @joeyaiello

**Comment by daxian-dbw** [comment] 2017-05-19 06:45
I submitted a PR to fix dotnet/corefx#13447. The PR is at https://github.com/dotnet/corefx/pull/19988

**Comment by daxian-dbw** [comment] 2017-05-20 00:07
The PR has been merged to dotnet/master and ported to release/2.0 branch.: https://github.com/dotnet/corefx/pull/20001

I also verified that this issue doesn't repro with the fix in .NET Core 2.0:
```
PS /home> ps aux | grep powershell | grep -v grep                                            
dongbo   22410  4.0  0.8 3697196 104800 pts/2  SLl+ 17:02   0:04 powershell
```
Hence, I'm closing this issue.

**Comment by vors** [comment] 2017-05-26 20:05
@daxian-dbw that's awesome, thank you so much!!

**Comment by vors** [comment] 2017-06-03 03:03
I get the old behavior on beta-2

![image](https://cloud.githubusercontent.com/assets/816680/26750068/80fbfc50-47ce-11e7-9ff7-d0d60205d2e2.png)

**Comment by SteveL-MSFT** [comment] 2017-06-03 22:15
Did we not have a test for this?

**Comment by vors** [comment] 2017-06-04 00:01
@daxian-dbw is it just not yet included in the dotnet packages we consume?

**Comment by daxian-dbw** [comment] 2017-06-05 16:39
We haven't moved to the lastest dotnet preview2 packages yet because preview2 packages will break VSCode. preview2 packages are not supported by VSCode C# extension at this moment, see https://github.com/OmniSharp/omnisharp-vscode/issues/1495

**Comment by daxian-dbw** [comment] 2017-06-14 23:51
PowerShell has moved to the latest 2.0.0-preview2 packages via #3887.
A test is also added with #4012 to cover this scenario.

**Comment by daxian-dbw** [comment] 2017-06-15 21:02
We are moving back to .NET Core 2.0.0-preview1 via PR #4026 due to regressions in the latest .NET Core 2.0.0-preview2 (https://github.com/dotnet/corefx/issues/21095). So re-open this bug.

**Comment by daxian-dbw** [comment] 2017-06-30 20:33
We finally moved to .NET Core 2.0.0-preview3 via PR #4144.
I have verified this issue has been fixed.

**Closed by daxian-dbw** 2017-06-30 20:33 UTC
Labels: Area-Engine, Issue-Bug, OS-Linux, OS-macOS, Resolution-External, Resolution-Fixed
