### ISSUE TITLE
Unable to use runspaces for ContainerConnectionInfo - The Containers feature may not be enabled on this machine

### ISSUE THREAD

**Issue by pagariyaalok** [PowerShell/PowerShell#12905] opened 2020-06-05 10:18 UTC
#1513  Steps to reproduce
I'm trying implement the below sample for container -
https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/creating-remote-runspaces?view=powershell-7#using-a-wsmanconnection-to-create-a-remote-runspace

I created ContainerConnectionInfo  object using below code.

ContainerConnectionInfo connectionInfo = null;
            connectionInfo = ContainerConnectionInfo.CreateContainerConnectionInfo(containerId, true, "");
            connectionInfo.CreateContainerProcess();

## Expected behavior
I was hoping to see successful connection to container and output of get-process from within container

## Actual behavior
when I use https://github.com/PowerShell/PowerShell/tree/master/src/System.Management.Automation I get below error
                
  ErrorRecord = {The Containers feature may not be enabled on this machine.}
Which seems to be throwing at https://github.com/PowerShell/PowerShell/blob/e93381e73e16a0d55ceab879ccaa58456800371d/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs

 result = HcsCreateProcess(ComputeSystem, cmd, ref ProcessInformation, ref Process, ref resultString);
//
	                    // The ComputeSystemExists call depends on the existence of microsoft.hostcompute.interop.dll,
	                    // which requires Containers feature to be enabled. In case Containers feature is
	                    // not enabled, we need to output a corresponding error message to inform user.
	                    //
	                    ProcessId = 0;
	                    ErrorCode = ContainersFeatureNotEnabled;
	                    return;

I do have container feature enabled on the environment and able to run Enter-PSSession from powershell console.

## Environment data

PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3-73-gc22ccbebd2955ff67c03574ec26d252955e8ea6d
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SeeminglyScience** [comment] 2020-06-05 12:28
Duplicate of #12570.  From that issue:

> This is correct. PowerShellDirect connections work only from host to container, not container to container. As mentioned above, you need to use WinRM or SSH remoting.

**Comment by pagariyaalok** [comment] 2020-06-05 19:20
I was trying from container host and not container.

**Comment by ShadowXVII** [comment] 2023-08-01 05:36
Same issue. `Enter-PSSession` works fine.

However, I've noticed that it seems to only work from Windows PowerShell 5.1 while `Enter-PSSession` on PowerShell 7.3.6 returns the same issue as in my .NET 6 application.

**Closed** 2024-02-05 10:41 UTC
Labels: Issue-Question, WG-Remoting, Resolution-No Activity

**Comment by XVII** [comment] 2024-02-06 03:55
@pagariyaalok , are you able to re-open this please? Or did you find a solution?
