### ISSUE TITLE
Computer field in InformationRecord is incorrect on Ubuntu 18.04 container

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#9526] opened 2019-05-02 23:43 UTC
This repros only on container for ubuntu. It works as expected on VMs and containers of other Linux distros

# Steps to reproduce

```powershell
PS /> docker run -it --rm mcr.microsoft.com/powershell:latest
PowerShell 6.2.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /> $result = Write-Information "Test Message" *>&1
PS /> $result.Computer

PS /> [Environment]::MachineName
35dc3ee9a157
PS /> cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
PS />
```

# Expected behavior

```none
PS /> $result.Computer
35dc3ee9a157
```

# Actual behavior

```none
$result.Computer is an empty string
```

# Environment data

```none
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment] 2019-05-03 18:19
We call `NonWindowsGetHostName()` from `libpsl-native` to get computer name. So the root of the issue is there.

https://github.com/PowerShell/PowerShell/blob/3bfca6d0fa9c935d78e9f7e9640b3994e5ca5c65/src/System.Management.Automation/engine/cmdlet.cs#L690

https://github.com/PowerShell/PowerShell/blob/3bfca6d0fa9c935d78e9f7e9640b3994e5ca5c65/src/System.Management.Automation/engine/InformationRecord.cs#L124

https://github.com/PowerShell/PowerShell/blob/3bfca6d0fa9c935d78e9f7e9640b3994e5ca5c65/src/System.Management.Automation/utils/PsUtils.cs#L216

https://github.com/PowerShell/PowerShell/blob/3bfca6d0fa9c935d78e9f7e9640b3994e5ca5c65/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L528

https://github.com/PowerShell/PowerShell/blob/3bfca6d0fa9c935d78e9f7e9640b3994e5ca5c65/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L693-L695

**Comment by SteveL-MSFT** [comment] 2019-05-03 19:09
Perhaps if GetFullyQualifiedName() is empty or null, we can fallback to [Environment]::MachineName?

**Comment by iSazonov** [comment] 2019-05-03 19:18
Or use ` [Environment]::MachineName` derectly and remove pinvoke?

**Comment by iSazonov** [comment] 2019-05-03 19:26
I see on Windows we use `System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties` - the API is ported and we could test it and use for all platforms.

**Comment by SteveL-MSFT** [comment] 2019-05-03 19:37
We should probably see if we can get rid of libpsl-native altogether as .NET Core keeps adding more APIs

**Comment by iSazonov** [comment] 2019-05-04 04:00
I'd expect the issue on container for ubuntu is not PowerShell issue and should be fixed on container for ubuntu.

I reviewed API  that we use on Unix-es - we use the same [GetHostName()](https://github.com/PowerShell/PowerShell-Native/blob/5e914ec784b3c7e4b1b6f176e4543aec5d1cd6dd/src/libpsl-native/src/getcomputername.cpp#L23) ([and CoreFX](https://github.com/dotnet/corefx/blob/09e2417cd0505df4558535651efb1bbcffdf0c59/src/Common/src/CoreLib/Interop/Unix/System.Native/Interop.GetHostName.cs#L15)) to get host name but [getaddrinfo()](https://github.com/PowerShell/PowerShell-Native/blob/5e914ec784b3c7e4b1b6f176e4543aec5d1cd6dd/src/libpsl-native/src/getfullyqualifiedname.cpp#L41) to get domain name - CoreFX uses [GetDomainName()](https://github.com/dotnet/corefx/blob/a6f76f4f620cbe74821c6445af3f13e048361658/src/Common/src/Interop/Unix/System.Native/Interop.GetDomainName.cs#L15)

I think we should follow CoreFX and remove P/Invokes in our code.

**Comment by iSazonov** [comment] 2019-05-09 18:55
@adityapatwardhan Can we close the issue?

**Closed** 2019-05-10 04:26 UTC
Labels: Area-Engine, Issue-Bug, Resolution-Fixed
