### ISSUE TITLE
Scripts with hexadecimal names not executing without prefixing them with a path

### ISSUE THREAD

**Issue by 1F916** [PowerShell/PowerShell#15543] opened 2021-06-08 13:46 UTC
## Steps to reproduce

Put a script file name 0x.ps1 in your $env:path directory, like `C:\scripts\`.
Try to call the script:
```powershell
PS C:\> 0x.ps1
```

## Expected behavior

```none
The script should execute
```

## Actual behavior

```none
The script is not executed. No output is produced and I'm back at the command prompt.

If I prefix the script name with its path or rename it to something that does not look like a hex digit (i.e. "0xqqq.ps1" but not "0xffff1337.ps1"), it works as expected.
This also does not appear to happen with script files that only contain decimal numbers like "1234.ps1"

This works in Windows Powershell (PSVersion 5.1.21390.1) just fine.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.21390
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2021-06-08 14:08
`0x.ps1` will parse as the numeral literal `0x`, then the property accessor `.` and property name `ps1`. All hexadecimal literals would work similarly; it gets parsed as a number, then a property is queried. The property doesn't exist, so the only result is `$null`.

This is by design, I think. A workaround is to use `&` and quote the command name:

```ps1
& "0x.ps1"
```

**Comment by doctordns** [comment] 2021-06-08 14:12
I would never expect the script to be run if you just specify it as `0x.ps1'. PowerShell does not run scripts in the current working directory, no matter what the name. If you had typed `0x.ps1>tab>`, Powershell helpfully prepends a path and runs `.\0x.ps1`. 

I think this is by design.

**Comment by vexx32** [comment] 2021-06-08 14:13
@doctordns it will work if the script is in a directory specified in `$env:PATH` as @1F916 mentions it is.

**Comment by 237dmitry** [comment] 2021-06-08 14:39
The same with `0b1.ps1` like names.

**Comment by 1F916** [comment] 2021-06-08 14:48
> `0x.ps1` will parse as the numeral literal `0x`, then the property accessor `.` and property name `ps1`. All hexadecimal literals would work similarly; it gets parsed as a number, then a property is queried. The property doesn't exist, so the only result is `$null`.

The strange thing though is that it does work just fine with strictly decimal names like `1234.ps1`. Also it worked fine in previous versions of PowerShell, so I would consider it a regression. I have a couple of scripts with similar naming that call each other like that and this new behavior breaks them in a - what I would consider - surprising way.

**Comment by 1F916** [comment] 2021-06-08 14:54
This (imo) inconsistent behavior between the handing of decimal numbers and hex/binary/exponential numbers also leads to other surprising behavior:

```powershell
PS C:\> 0xb.equals(11)
True
PS C:\> 11.equals(0xb)
11.equals: The term '11.equals' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by 1F916** [comment] 2021-06-08 15:09
Also the behavior between the `0x` and `0b` prefixes is inconsistent when they are not followed by a number:

```powershell
PS C:\> 0x.equals(0)
True
PS C:\> 0b.equals(0)
0b.equals: The term '0b.equals' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\> 0.equals(0)
0.equals: The term '0.equals' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Consequently, if the script in my initial example was named `0b.ps1` (or `0.ps1`), it would work as expected, i.e. as it worked before.

**Comment by 1F916** [comment] 2021-06-08 15:27
Sorry if i'm spamming here while I'm digging deeper, but another thing I discovered is that calling a script that is called `0GB.ps1` (or `10.GB` etc) doesn't work either, similar as I lined out in my initial post. Interestingly this one doesn't work in Windows PowerShell 5.1 either.

Windows PowerShell 5.1 did have support for hex literals as well as KB/MB/GB/... suffixes, but not binary literals. So it doesn't really make sense to me why "0GB.ps1" works in neither Windows PS 5.1 and PS7, but "0x.ps1" works in Windows PS 5.1 but not PS7. `0.ps1` on the other hand works on both versions. `0b1.ps1` works in Windows PowerShell 5.1 but not PS7.

I think it would be nice if there was some consistency in the handling of number literals so as to minimize surprise, particularly in light of the other examples I posted above.
For a command line interpreter, I would generally expect (existing) file names to have precedence over accessing properties of some - but not all - number literals.

**Comment by vexx32** [comment] 2021-06-08 16:57
Thanks for digging a bit deeper here! Yeah, I agree, the fact that certain literals, especially binary (which has a similar prefix) seems to suggest that the hex tokenization is subtly broken.

Hard to say exactly how without a deep dive though, but I do agree this could and should be fixed.

**Comment by rkeithhill** [comment] 2021-06-08 17:14
Some time ago there used to be a problem invoking `7z.exe` in PowerShell. You could not just type `7z a ....`.  You had to invoke it using `&` e.g. `& 7z a ...`.  The team fixed that issue but as with most "fixes" there are unintended consequences.

**Comment by vexx32** [comment] 2021-09-30 20:42
The error occurs here:

https://github.com/PowerShell/PowerShell/blob/7cf1ef8c8599a90cd9579c7bb7b7676e097c4938/src/System.Management.Automation/engine/parser/tokenizer.cs#L3985-L3990

We append a `0` character to the hex string initially due to a complication in the way that it's parsed. I believe we rely on BigInteger's hexadecimal parsing, which parses as signed hexadecimal by default. Prefixing the `0` forces it to parse as effectively unsigned, or something like that.

As a result, the following `if (sb.Length == 0)` check will never be hit, it will always have at least length 1. This issue should be resolved if we update that check on line 3987 to `if (sb.Length == 1)`. Probably worth adding a comment explaining why the check must differ from the binary one not far below.

**Comment by JamesWTruher** [comment] 2021-09-30 23:26
WG: definitely something that could be addressed - marked up for grabs

**Closed** 2023-11-23 11:17 UTC
Labels: Issue-Bug, WG-Engine, Up-for-Grabs, Resolution-No Activity
