### ISSUE TITLE
PowerShell on Windows 10 mobile

### ISSUE THREAD

**Issue by hey-red** [PowerShell/PowerShell#2152] opened 2016-09-01 08:54 UTC
Is there any plans for this?

**Comment by KexyBiscuit** [comment] 2016-09-01 15:12
As far as I know, there's no plan to port dev tools onto Windows 10 Mobile, including PowerShell. It's a phone, not a general purpose OS.
However, if Microsoft want to turn Windows 10 Mobile in to a productivity tool, I'll be glad to use it.

**Comment by grahamehorner** [comment] 2016-09-01 15:33
I think that it would be a good user story for Windows 10 Mobile to support PowerShell; these devices are used in businesses and having the device support PowerShell would align the remote management/deployment story with other types of devices.

@KexyBiscuit Windows Mobile 10 is build on top of WindowsOne core and is becoming a more powerful general purpose platform with support for things like Continuum etc. plus PowerShell is much more than a dev tool.

**Comment by oising** [comment] 2016-09-01 17:42
@KexyBiscuit  -- as @grahamehorner says, Continuum is a game changer here. If I can run office on a full keyboard and screen off of my w10 device, why not manage servers?

**Comment by kilasuit** [comment] 2016-09-02 15:45
I asked this question to @BrucePay in November last year as I was curious of this being a possibility although there would still be the question of the editor experience which I suppose @daviwil would be better placed to comment on.

The following is the content of the email I sent 

> Hi Bruce,
> 
>As we discussed on Twitter here are just a few of the possible scenarios that I can envision being possible use cases of PowerShell if it were to be made available on the Mobile platform.
> 
>Scenario 1 - MS Partner 
>As an MS partner you may be an organisation of 1/2-50+ people supporting a number of organisations with migrating to Office 365 and although you perhaps will be already using PowerShell on your Laptop/Desktop to help you with managing these organisations.
The scenario is that you are currently travelling  between organisations to perhaps provide an in person training session when you get an email detailing that there's been an issue with another organisations Tenant. In this case it is an issue with a user being unable to access one of their shared mailboxes - this can be quickly checked and resolved with an imported Pssession to Exchange for that organisation to see if the user has been removed from the mailbox and if they have you can then resolve it within the same Pssession and within minutes whilst running between having to catch a number of trains.
> 
>Scenario 2 - Single person LTD company (something that I would actually be looking to do in future ) 
>This organisation who is proficient with PowerShell on their desktop or laptop has a requirement to keep receipts for any purchases they make for tax purposes and has decided that they would like to do this via a customised SharePoint List in which to upload the item they will create a Universal Windows App to provide a UI however would prefer to use PowerShell as the background engine to submit the item to the SharePoint list on hitting the submit button with the functionality working across devices.
> 
>Scenario 3 - Enterprise sized customer
>In a cost cutting initiative the organisation have decided to recall all staff laptops and replace the whole estate with Virtual Desktops that can be accessed via a secured remote login portal.
However they also have a VPN set up that staff can log into via their own laptops or desktops or mobile devices for browsing internal sites.
There becomes a major incident which requires the on-call engineer to diagnose the issue on the companies recently deployed Nano Server Farm hosting a mission critical application. The engineer via his mobile whilst out shopping at the supermarket learns of this via standard reporting that they have set up and can then quickly connect his phone to the VPN and using PowerShell Remoting can directly access the members of the Nano Server Farm to find out what the issue is - in this case the issue happens to be that a service account's password had changed and this needed to be reset but as a temporary measure the engineer changed the service account to another one of the less used service accounts for the application & restarted the service. Upon restart across the whole Nano Farm the service was brought back online and the issue resolved. If it had not been for the ability to connect via VPN and run PowerShell directly from his phone the engineer would have likely had an escalation call regarding this issue along with a Major Incident Bridge which equates to higher expenditure for the organisation due to the resource cost. However even if the engineer had not got the notification and have been called he could still have whilst out on the go been able to resolve this issue within a manner of minutes due to having the ability in their hand to do so.
> 
>Scenario 4 - The for "fun"  scripter (very much me again)
>This person most likely deals with lots of different sites / technologies and would likely have a need to query various API's for their workloads which could be a variety of different sources however he already has some manipulation skills with PowerShell so in use with the scheduling engine built into Windows he already has some things running on a Desktop at home - however for redundancy if he could also run a subset of these on his mobile as he could then find more interesting ways to push his phone to its limit. However he would likely replace running things on his desktop and run stuff on his mobile instead.
Also with it being a different device completely he would have more items that he could possibly interact with including GPS location, temperature and so on and so forth.
>
>
>
> I know that these are "hypothetical" however if able to run on the Windows Mobile version of Windows 10 I would definitely spend time investigating the ability of scenarios 2 & 4 in great detail as this is something that would very much interest me and would be willing to spend time working with you to test these out if this was to become a reality.

I believe though some of the sticking points will be around the API's that are available on the Windows 10 Mobile platform however there is *a slight* chance that creating a Universal Windows app and making use of Xamarin forms that PowerShell *could* get a xplat mobile editing/running experience however there may be some .Net Core dependency on whether it will run on arm powered devices in future https://github.com/dotnet/core/issues/243 

I hope that this could become a possibility as I would love to see PowerShell running natively on devices like Lumia 950/950xl/iPhones/iPads and Android powered devices too.

**Comment by daviwil** [comment] 2016-09-02 17:27
Editor experience is pretty possible via remote PS Editor Services instance.  All of the raw material is there, just a matter of someone being motivated enough to wire it up :)

**Comment by MathiasMagnus** [comment] 2016-10-24 20:34
Being a Linux sysadmin but using a Windows box for development purposes, if Windows Mobile were to pick up desktop capabilities, it would be an actual reason to buy an expensive Continuum capable phone and go to work with that.

Visual Studio (Code) & PowerShell on Win10 Mobile and I'm in for a +1000$ mobile phone. If it can get ***t done, I'd buy it. I know a phone is not a general purpose OS, but MS is pretty much losing the mobile war, and innovating would be the way to go. Continuum is the first step, now make it actually useful for others than Office users.

**Comment by dragonwolf83** [comment] 2016-10-26 05:44
Well the idea of Continuum is to purpose it as a general OS and Windows Mobile is supposed to be focused on Enterprise which means this fits right into those user stories.

To be able to PowerShell and SSH into a Linux or Windows server for those 4am calls.... Killer! Makes it easier to not get out of bed to do some quick easy things or project onto a TV without getting out of bed to get the bigger screen.

As a Windows Phone, SysAdmin, and PowerShell scripter, this fits right into my needs.

**Comment by TheNocturnalEvil** [comment] 2018-03-07 16:07
Well if you want something similar to powershell on Windows 10 Mobile you can try Token2Shell, of course it costs $10.4.

**Comment by MathiasMagnus** [comment] 2018-03-07 17:36
Token2Shell works like a charm, I have it setup for our cluster and it did come in handy multiple times to install requested packages on the subway or the bus. It is kinda' cheating though, because it's not local. Since [command-line apps are a thing](https://channel9.msdn.com/Events/Ch9Live/Windows-Community-Standup/Kevin-Gallo-February-2018) now, it would've been not too distant to achieve something like this, if the platform wouldn't have been left behind. Shame, really.

**Comment by fMichaleczek** [comment] 2019-07-02 01:43
@iSazonov Could you close this one as Windows Mobile is now dead ?

**Closed** 2019-07-02 03:19 UTC
Labels: Area-Portability, Issue-Discussion, Resolution-Answered, Up-for-Grabs
