### ISSUE TITLE
FileSystem provider doesn't support NTFS long path syntax

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4439] opened 2017-07-31 23:43 UTC
Not sure how much we care.  Works with cmd.exe

Steps to reproduce
------------------

```powershell
dir \\?\c:\users
```

Expected behavior
-----------------

```none
directory of c:\users
```

Actual behavior
---------------

```none
nothing, no error or output
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.16253
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment] 2017-08-02 05:28
Related PR #3960 
@jeffbi Could you please comment the Issue?

**Comment by jeffbi** [comment] 2017-08-02 06:16
I did a little poking around and it looks to me like this is more in the globbing code than in the provider itself.

**Comment by daxian-dbw** [comment] 2020-07-14 18:00
Close as a duplicate of #10805
> Note: This is a generalization of #4439. @SteveL-MSFT, if you agree, please close the latter.

**Closed by daxian-dbw** 2020-07-14 18:00 UTC
Labels: Area-Providers, Issue-Enhancement
