### ISSUE TITLE
Start-process pwsh -credential $cred <- strange input issue

### ISSUE THREAD

**Issue by a-dimas** [PowerShell/PowerShell#13743] opened 2020-10-05 13:17 UTC
## Steps to reproduce
in the console:
```powershell
$cred = get-credential
start-process pwsh -credential $cred
```

## Expected behavior
the same as `start-process pwsh` but within the context of $cred
```none
```

## Actual behavior
I cannot type in the new console running as `$cred`... unless I type in the original console running as my user.

If I go to the new console and type, nothing shows nor is executed. However if I switch to the original console and start typing, the characters start to appear in the new console, one by one.
Then, the issue reverts, and I stop being able to write in the original console until I type in the new console.
It looks as though there's only one buffer.
```none

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2020-10-05 14:30
Can you confirm whether this is still happening in the most recent preview/RC releases?

**Comment by jborean93** [comment] 2020-10-05 19:07
I believe this is a duplicate of https://github.com/PowerShell/PowerShell/issues/12129.

**Comment by a-dimas** [comment] 2020-10-06 04:16
Confirmed duplicate, you can close this.
Thank you, I hadn't found it.

**Closed** 2020-10-06 12:06 UTC
Labels: Issue-Question, Resolution-Duplicate

**Comment by jamie-sandbox** [comment] 2023-12-03 21:39
## Workaround

https://github.com/PowerShell/PSReadLine/issues/288#issuecomment-1837606501
