### ISSUE TITLE
Attribute may silently crash

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3769] opened 2017-05-12 05:22 UTC
Steps to reproduce
------------------

```powershell
function Test-BadAttribute
{
    [CmdletBinding()]
    Param
    (
        # Param1 help description
        [Parameter]
        [ValidateSet("a","b")]
        $Param1,

        [Parameter]
        [ValidateSet()] # Bad attribute - the constructor is failed
        $Param2
    )

    Begin
    {
    }
    Process
    {
    }
    End
    {
    }
}

1. Test-BadAttribute -Param1 <Press Tab>
2. Test-BadAttribute -Param1 <Press Enter>
3. Test-BadAttribute -Param1 "a" <Press Enter>
```

Expected behavior
-----------------

1. IntelliSenese work for Param1 and don't  work for Param2 with error message
or IntelliSenese don't work for both parameters with appropriate error message.
2. Show appropriate error message.
3. Cmdlet work well or don't work with showing appropriate error message.

Actual behavior
---------------
1. No exception. No error message. IntelliSense don't work.
2. Murky error message: it is impossible to understand that there is a problem with _any_ attribute, which is the attribute and which is the parameter.
3. The same as 2. and the cmdlet don't work.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1-7-g7fa53aedb3c7514cf1c2a19af6c26566661596d9-dirty
OS                             Microsoft Windows 10.0.10240
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by alx9r** [comment] 2017-09-10 14:01
Silent failure for the entire `param()` block also occurs when there is a typo in the attribute.  For example, the following outputs nothing:

```PowerShell
function f { param([NonExistentAttribute()]$x,$y) }
(Get-Command f).Parameters
```

**Comment by iSazonov** [comment] 2020-07-16 12:35
Possible place for the fix https://github.com/PowerShell/PowerShell/blob/e8bf6ca18a04ee04b290d2f01f5ef01750280d36/src/System.Management.Automation/engine/parser/Compiler.cs#L1702-L1705

**Comment by vexx32** [comment] 2020-07-16 13:46
I think this will be tricky to fix in a meaningful way. The function code isn't executed until it's actually invoked; the missing attribute type could well be added as a powershell class (for example) before the function is actually run.

Running the function yields the expected error, so I'm not sure there's anything we can really fix here?

**Comment by iSazonov** [comment] 2020-07-16 14:52
@vexx32 Please look repro steps in the OP.

**Comment by vexx32** [comment] 2020-07-16 14:57
@iSazonov gotcha, that's not clear at all and can be improved. Not sure about tab completion though 🤔

**Comment by davidBar-On** [comment] 2021-04-06 14:58
I have a proposed solution to the issue which will function as follows:
1. `Test-BadAttribute -Param1 <Press Tab>`: the "a b" valid values are displayed.
2. `Test-BadAttribute -Param1 <Press Enter>`: error message "Missing an argument for parameter 'Param1' ...",
3. `Test-BadAttribute -Param1 "a" <Press Enter>`: works properly.
4. `Test-BadAttribute -Param1 "a" -Param2<Press Tab>`: nothing happens.
5. `Test-BadAttribute -Param1 "a" -Param2<Press Enter>`: error message "Missing an argument for parameter 'Param2'. Specify a parameter of type 'System.Object' and try again.".

In addition, on the first time `Test-BadAttribute` is activated, after the first Enter or Tab (which comes first), error message is displayed "WARNING: Parameter $Param2 cannot be used since its ValidateSet is empty".

The main issue I see with this approach is that the error message in step 5 suggests that `Param2` may have valid values, but I didn't find a better functioning approach.

**Is this approach acceptable?**

If it is, then I need help with:
1. **How should the above ""WARNING" message be displayed?**  Currently I am using `Console.WriteLine` but I assume this is not the right way to do this.
2. **Were should the test cases be added?**

**Comment by iSazonov** [comment] 2021-04-06 16:08
> 4\. `Test-BadAttribute -Param1 "a" -Param2<Press Tab>`: nothing happens.

Why nothing?
What if there is a typo in the attribute name?

**Comment by davidBar-On** [comment] 2021-04-06 17:51
>>    4. Test-BadAttribute -Param1 "a" -Param2<Press Tab>: nothing happens.

>Why nothing?

Nothing, because in the suggested solution `GetRuntimeDefinedParameter()` adds `Param2` as legal `ValidateSetAttribute` parameter with empty list of valid values.

>What if there is a typo in the attribute name?

In this case Tab shows the list of current directory files as the valid values.

**Comment by iSazonov** [comment] 2021-04-07 07:54
> as legal `ValidateSetAttribute` parameter with empty list of valid values.

Do you change the attribute? I think it is nit right direction to address the issue. 
The issue asks to add more information to script developer if there are errors/typos in using attributes.

**Comment by davidBar-On** [comment] 2021-04-07 11:01
The approach I took is:
- In `validateValidateSetAttribute()` change the exception thrown in the following code to a new exception `ArgumentEmptyValidateSetException`, to make sure it is unique exception for this case: https://github.com/PowerShell/PowerShell/blob/3d49de134ea9b98ad5991bc7974575a7b242181d/src/System.Management.Automation/engine/Attributes.cs#L1702-L1704
- In `GetRuntimeDefinedParameter()`, **catch** the `PSArgumentEmptyValidateSetException` exception in the following call to `GetAttribute()`: https://github.com/PowerShell/PowerShell/blob/3d49de134ea9b98ad5991bc7974575a7b242181d/src/System.Management.Automation/engine/parser/Compiler.cs#L1800
In the `catch` body a new `ValidateSetAttribute` attribute is created with an empty list of valid values.

Initially, I planned that the `catch` body will just through the same exeception, but now with the real parameter name.  However, in this case Tab for `Param1` does not do anything, and even if `Param1` is set with a legal value, after the Enter the `Param2` exception is shown.  With the above approach the function can be used as long as `Param2` is not included in the command line.

The `catch` body also issues the "WARNING" message, and this is why I asked how to properly display this warning message.  As I wrote, I am also not sure were to add test cases (and examples of test cases for functions parameters will also help).

**Comment by iSazonov** [comment] 2021-04-07 11:45
The issue is not exclusively about ValidateSetAttribute. Any wrong attribute should raise an user friendly message.

**Comment by davidBar-On** [comment] 2021-04-07 13:11
> The issue is not exclusively about ValidateSetAttribute.

The specific error message in the issue is about ValidateSetAttribute - the `ArgumentOutOfRangeException` message thrown by `ValidateSetAttribute()`.  I am not sure it is related top other attribute types.

This is a "Murky error message" because `ValidateSetAttribute()` does not know the parameter name (and I didn't find a relatively easy way to pass it the parameter name).  As far as I understand, in all other cases it is called the list is from internal list, so the '"_argument "validValues_"' in the message is o.k.

**Comment by iSazonov** [comment] 2021-04-07 16:30
You can replace `ValidateSetAttribute` with `ValidateRange` for investigating.
Again, with `Test-BadAttribute -p<tab>` user should get an useful error message why IntelliSense does not work. Really there is an exception (we can see it if press <Enter> instead of <Tab>) but IntelliSense code hides it.

**Comment by davidBar-On** [comment] 2021-04-08 07:45
> with `Test-BadAttribute -p<tab>` user should get an useful error message why IntelliSense does not work. Really there is an exception (we can see it if press instead of ) but IntelliSense code hides it.

Seems I misunderstood the main issue.  I thought it is that _"validValues"_ should be _"Param2"_ in the error message '_InvalidArgument: Cannot process argument because the value of argument "validValues" is out of range._'.

From the `ValidateRange` example and and using `bool` parameter I see that there are some issues with the auto complete:
1. The above \<tab\> issue that "should get an useful error message why IntelliSense does not work".  I assume that the required fix is showing the exception error message that IntelliSense currently hides.

2. When specifying empty `ValidateRange` parameter, after \<enter\> the following `MethodException` error is shown, but there is no such error message for empty `ValidateSet`.  I assume a fix is to show such `MethodException` error for empty `ValidateSet` (and maybe other attribute types).
```
MethodException:
Line |
  10 |          [ValidateRange()] # Bad attribute - the constructor is failed
     |          ~~~~~~~~~~~~~~~~~
     | MethodArgumentCountException Cannot find an overload for ".ctor" and the argument count: "0".
```

3. When a parameter is defined as `bool`, `int`, etc., \<tab\> shows the current folder files as valid values, instead of something like "_$True, $False, 1 or 0_"  for `bool` and probably showing nothing for `int`.  I assume that this should be fixed for all parameter types, except for `switch`.

**Should all these issues be fixed**?  If not, which of them (or other related issues that I didn't see) should be fixed?

**Comment by iSazonov** [comment] 2021-04-08 09:14
> When a parameter is defined as bool, int, etc., <tab> shows the current folder files as valid values, instead of something like "$True, $False, 1 or 0" for bool and probably showing nothing for int. I assume that this should be fixed for all parameter types, except for switch.

This is a separate issue(s). We can find many such ones. Most from them could be fixed by improving a type inference.

In the issue we say only about improving the user experience with broken attributes:
- typo in name
- wrong attribute arguments
- an exception in attribute implementation and so on.

**Comment by davidBar-On** [comment] 2021-04-13 07:04
> In the issue we say only about improving the user experience with broken attributes:

To allow letting the use know about errors during tab-complete, an error message should be displayed to the user.  However, I did not find any `PSReadLine` method that allows to do that before <enter>.

Did I miss something, or such method should be added to allow to show tab-completion errors?  I assume that just using `Console.WriteLine()` is not good enough, since the completion options may be shown in a GUI menu (unless such  menu is never used by PowerShell).

**Comment by iSazonov** [comment] 2021-04-13 08:31
There are a lot of WriteError() methods. We should find an appropriated one from current (execution) context.

**Comment by davidBar-On** [comment] 2021-04-20 06:01
After further evaluation I now believe that a proper solution to this issue requires **changes to `PSReadLine`**.  This is assuming that after showing the tab-completion error message, the **PS prompt should be displayed again**.  E.g., case "1." from the original issue description should look something like:
```pwsh
PS> Test-BadAttribute -Param1 <Tab>
Error: No completion options found since parameter "$Param2" ValidateSet is empty

PS> Test-BadAttribute -Param1 
```
However, displaying the prompt after the error message should be done by `PSReadLine`, similar to the way the prompt is displayed after the completion options are displayed by [PSReadLine/Completion.cs PossibleCompletionsImpl()](https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/Completion.cs#L800-L801):
```cs
    menu.DrawMenu(null, menuSelect:false);
    InvokePrompt(key: null, arg: _console.CursorTop);
```
For this, `PSReadLine` should be able to receive the error message, display it and then re-display the prompt.  This is similar to the way it handles the received the completion options list (and maybe the error message can be implemented by returning the message as a special case of the completion options).

**Does this approach seem reasonable?**  If it is, is it worth trying to implement it? (I am far from understanding the full process done for tab-completion between `PSRealLine` and `PowerShell`, but it seems that the required changes for this approach are relatively local, so I am willing to try.)

**Comment by iSazonov** [comment] 2021-04-20 11:49
@davidBar-On Thanks for your research! I thought it was easier to fix than it turned out. 

I'd expect this works without PSReadline too in a way.
Perhaps @daxian-dbw could comment how better the fix could be implemented.

**Closed** 2021-08-25 04:05 UTC
Labels: Issue-Enhancement, WG-Engine, WG-Interactive-IntelliSense, Up-for-Grabs, First-Time-Issue
