### ISSUE TITLE
How do we stop the bot from going berserk and closing of real/genuine issues?

### ISSUE THREAD

**Issue by mjr4077au** [PowerShell/PowerShell#21406] opened 2024-04-02 07:27 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

There are so many significant issues that all got closed off around November 2023 by the `microsoft-github-policy-service` bot; not because they were fixed or erroneously open, but simply because they were open for so long.

![image](https://github.com/PowerShell/PowerShell/assets/48643140/019571d0-4efa-4811-9d96-0a2509712468)

Issues like https://github.com/PowerShell/PowerShell/issues/6615 are 100% genuine and have been in existence as far back as Windows PowerShell 5.1, and still exist in 7.4.1 today.

Issues like https://github.com/PowerShell/PowerShell/issues/20771 have been re-created out of the goodness of the author's heart, but even they expressed their dismay in https://github.com/PowerShell/PowerShell/issues/9206, the original issue that got closed off.

Please consider an internal audit to review the issues the bot closed for validity and re-open genuinely ongoing issues that still exist to this day. It's regrettable that many of the issues have sat there as long as they have, but they should sit there for as long as they need.

### Expected behavior

The expected behaviour in my mind is that an issue/ticket should sit there for as long as it needs until it's resolved. Issues shouldn't be auto-closed due to aged, they should be closed because a human says "won't fix" or because it actually has been fixed and inadvertently not closed.

### Actual behavior

The actual behaviour is that with the bot closing off genuine, legitimate issues, that they'll never get the chance to be re-visited. The issue https://github.com/PowerShell/PowerShell/issues/6615 that I highlighted earlier is an example of an ongoing issue for nearly a decade and personally cost me many hours of time as I wondered what my issue was.

**Comment by jborean93** [comment] 2024-04-02 09:30
Playing the devils advocate here, if an issue stayed open for so long without any action, the chances of anything happening is very slim. I don’t agree with the decision here but I can under the driver behind it.

**Comment by jhoneill** [comment] 2024-04-02 18:19
> ...  issues just closed off because it's old and doesn't look good on my list.

I did get the feeling that was what drove this exercise. 

At the same time, when there are a vast number of open issues, and the huge majority are not  going be addressed, spiking them once any discussion has died down seems a pragmatic thing to do. Trying to pick items to work on from a smaller number is easier

**Comment by SeeminglyScience** [comment] 2024-04-03 17:25
> > ...  issues just closed off because it's old and doesn't look good on my list.
> 
> I did get the feeling that was what drove this exercise.

Just to clear this up, no - this was definitely not the driver. Nor is it even a side benefit, I don't think anyone looks at open issues as a metric full stop. If anything, one could argue more open issues look *good* because it would mean we have more to do - but it's not really tracked like that.

> At the same time, when there are a vast number of open issues, and the huge majority are not going be addressed, spiking them once any discussion has died down seems a pragmatic thing to do. Trying to pick items to work on from a smaller number is easier

Yeah, this was the driver.

---

Also worth noting that an issue being closed is not a statement that it isn't a problem (unless it's closed with `Resolution - By Design`). Most issues, valid or not, we can't prioritize. If anything, the issue remaining open implies someone is working on it and for most of these that just wasn't ever going to be the case.

**Comment by mjr4077au** [comment] 2024-04-03 18:35
To me, it's only implied that an issue is being worked on once it's assigned to a resource or milestone, otherwise it should sit there as long as it needs. I completely get a high issue count can be daunting when it comes to prioritisation, but it's still in the 800s and that's daunting enough as it is.

Having genuine issues closed off as "Resolution - No Activity" doesn't state anything to indicate its validity, moreover it could indicate that the issue was closed because the author didn't respond in time to reaffirm its validity or provide a demonstrable example.

All I can see happening from this is that these issues will now never get addressed because they're off the radar, and that people are just going to necro post on their issues they've raised out of fear the bot will simply close it off.

**Comment by mklement0** [comment] 2024-04-03 18:50
Other undesirable effects of the auto-closures:

* A marked increase in duplicates, because users don't expect to have to look among _closed_ issues for an existing one.

* There are plenty of up-for-grabs issues among the closed ones, which again users won't think to look for among closed issues.

* Auto-closed feature requests that were never adjudicated but are _candidates_ for up-for-grabs will fall through the cracks.

**Comment by MartinGC94** [comment] 2024-04-03 20:35
> Yeah, this was the driver.

It doesn't seem like it achieved the desired effect. There's 800+ issues now VS the 3k there were before the bot was activated, that number still seems too large for anyone to be able to manually sort through.

If it's hard for the team to decide which issues to prioritize, why not use some of the available metrics? This one: https://github.com/PowerShell/PowerShell/issues/7654 has 56 👍 and it's a decently complex issue that is unlikely to simply be picked up by a random community member. It seems like the perfect candidate to assign to someone on the team.  
If highly upvoted issues are consistently getting fixed then you will be incentivizing good behavior by the community (finding existing issues to upvote rather than creating duplicates. And actually voting for issues that they feel are important) and this will ultimately make your jobs easier because you will have a good idea of what the community wants.

**Comment by SeeminglyScience** [comment] 2024-04-04 15:32
So I do agree that the team should utilize reactions more than it does currently, but sometimes they don't necessarily reflect demand relative to other issues. That one for instance is linked externally, in this case it's to SO so it's at least representative.

Not applicable to that issue, but often an issue has a high reaction count because a tool maker asks their users to upvote an issue. The users then understandably want to support the person who makes the tool they like, even if they don't really want to use the feature that's being asked for. I'm not saying that feedback is useless, but it doesn't hold the same amount of weight as if they all independently wanted the feature.

Back to that issue in particular, it's a primarily dev time problem with a pretty easy workaround. Those can certainly still be very annoying no doubt, but that change is a lot harder than it first appears. Mainly because `using module` is parse time, so we'd have to shift a lot of the work to be conditionally done at runtime. That means a good chuck of compiler work which tends to be much more time consuming. We would also need to find all of the places where types are cached and then clear those caches or update them, and reset all the call site binders so method invocations don't use the old type. I know you called out that it was more complicated than most, but even for a PS team member that could easily be a few months of dev time.

Adding onto that, I wouldn't really consider `using module` to be in a particularly good state anyway. Of course that doesn't mean we shouldn't fix it, but if we were deciding to put more effort into that space then I'm not sure that particular bug would be in the top 5 most worth fixing.

**Comment by SteveL-MSFT** [comment] 2024-04-04 17:07
As a reminder, we do have ways to keep open issues that are impactful but don't warrant additional discussion.  Maintainers and Working Group members can add the `Keep Open` label so the bot doesn't auto-close due to lack of activity.  However, as Jordan noted, it also doesn't help anyone to have lots of issues open that no action is being taken to address and the larger the set of issues (and I agree 800 is still too many), the harder it is to find broadly impactful issues that are worth community and team time to address.

**Closed** 2024-04-09 19:34 UTC
Labels: Issue-Question, Resolution-Answered

**Comment by mjr4077au** [comment] 2024-04-09 19:44
@SeeminglyScience I don't really think this has been answered at all. Michael made some excellent suggestions that haven't been responded to at all. Can you please reopen this?

**Comment by mjr4077au** [comment] 2024-04-10 04:46
There needs to be some significant improvement in how issues are handled here. The ticket auto-closed because a day prior, it was marked as answered. If you look at the email chain below, I get _zero_ notification that the labels against the ticket have been changed.

![image](https://github.com/PowerShell/PowerShell/assets/48643140/76e90bef-ddd3-4a78-b47a-5e4eafa83997)

Is one meant to have a dedicated monitor with the page refreshing every 5 minutes just to ensure a label change isn't missed? I'm sorry but this is sub-standard...

**Comment by SeeminglyScience** [comment] 2024-04-10 15:00
> @SeeminglyScience I don't really think this has been answered at all.

That's fair, `Resolution - By Design` probably would have been more accurate.

> Michael made some excellent suggestions that haven't been responded to at all.

We can't always write out a point by point rebuttal of every suggestion unfortunately. The feedback has been passed on though (that's why Steve is in the thread, I brought it up to him in our 1 on 1).

> Can you please reopen this?

Right now there aren't any plans to change the bot whether the issue is open or closed. I will for sure continue to pass on the feedback, but leaving the issue open would be disingenuous.

> There needs to be some significant improvement in how issues are handled here. The ticket auto-closed because a day prior, it was marked as answered. If you look at the email chain below, I get _zero_ notification that the labels against the ticket have been changed.
> Is one meant to have a dedicated monitor with the page refreshing every 5 minutes just to ensure a label change isn't missed? I'm sorry but this is sub-standard...

To be clear the alternative to the label would be just clicking the close button. The whole "one day with no activity" thing isn't a call to stop it from being closed, it's just to delay the close until discussion isn't as active.

**Comment by mjr4077au** [comment] 2024-04-10 19:52
If the bot can announce the closure of a ticket, surely it can announce the ticket will close in one day unless there's further activity on it? The points being made here are that it seems that, rightly or wrongly, the focus is to close issues as fast as possible, by any means necessary.

Please forgive me as I don't mean to be confrontational, I've just never seen anything this aggressive before.

**Comment by SeeminglyScience** [comment] 2024-04-10 20:52
> If the bot can announce the closure of a ticket, surely it can announce the ticket will close in one day unless there's further activity on it?

The idea behind the `Resolution - *` labels is that the issue *will* be closed unless the label is removed, if you had made another comment before it closed that would have just delayed the close one more day.

But the issue isn't being deleted or locked, it's just not tracking active work.

> The points being made here are that it seems that, rightly or wrongly, the focus is to close issues as fast as possible, by any means necessary.

The `Resolution - *` labels have been in place for a long time, it's different from the no activity closures that's being talked about in this issue. In this case if the intent was to close it as quickly as possible then I'd just click the close button. Which tbh, I don't 100% know the reasoning of why we don't just click the close button, but that's a different topic.

But to be clear, I personally closed the issue by adding the label, even if the bot ultimately did the closing.

> Please forgive me as I don't mean to be confrontational,

Nah you're good.

> I've just never seen anything this aggressive before.

I don't frequent a ton of repos but the vscode repo is an example. That one is a bit more aggressive than ours, but also does a few things better. Even so, it can confirm it still sucks to have your issue closed there same as it does here. Having an issue left open for years also sucks though.

**Comment by mjr4077au** [comment] 2024-04-10 22:25
Everything you've said is reasonable enough, I'll probably just leave this as a stalemate of sorts. I'll be mindful of tickets I open in the future and to be vigilant with checking in on them etc.

I'm not sure what to do with issues that have been closed but are ongoing, should I open new issues and reference the original? To be clear, these would be issues that I encounter to this day that I've had to work around and are causing legitimate issues.

**Comment by SeeminglyScience** [comment] 2024-04-10 22:58
> Everything you've said is reasonable enough, I'll probably just leave this as a stalemate of sorts. I'll be mindful of tickets I open in the future and to be vigilant with checking in on them etc.
> 
> I'm not sure what to do with issues that have been closed but are ongoing, should I open new issues and reference the original? To be clear, these would be issues that I encounter to this day that I've had to work around and are causing legitimate issues.

Yeah if you come across an issue that is still impactful and hasn't had a WG ruling against it, it's very helpful for us if the issue could be recreated. Ideally with a summary of the points on both sides so that it can be re-evaluated (or evaluated for the first time if it's an older issue, going forward nothing with needs triage should be closed) by the WG involved.
