### ISSUE TITLE
Bracketed paste using INPUT_RECORD marks

### ISSUE THREAD

**Issue by o-sdn-o** [PowerShell/PowerShell#20896] opened 2023-12-11 16:32 UTC
### Summary of the new feature / enhancement

Since PowerShel reads the input stream using ReadConsoleInput, could you consider adding a support for "Bracketed Paste" marks in the INPUT_RECORD's stream. This could be done by handling boundary marks for the inserted block in the following form:

```c++
rec.EventType == MENU_EVENT;
rec.Event.MenuEvent.dwCommandId = 0x8001; // paste_begin

// set of recs with wchar-by-wchar copy
// of the block pasted from the clipboard
rec.EventType == KEY_EVENT;
rec.Event.KeyEvent.uChar.UnicodeChar = wchar; // Pasted data set

rec.EventType == MENU_EVENT;
rec.Event.MenuEvent.dwCommandId`= 0x8002; // paste_end
```

This approach greatly simplifies the task of cross-platform transferring an inserted immutable block via SSH between hosts. Both from unix to windows to unix, and from windows to unix to windows.

Related to https://github.com/microsoft/WSL/issues/10905

**Comment by SteveL-MSFT** [comment] 2023-12-11 17:36
Dupe of https://github.com/PowerShell/PSReadLine/issues/1471

**Comment by o-sdn-o** [comment] 2023-12-11 17:59
I can of course append `\e[200~`/`\e[201~` to the original block, but the block may already contain such characters.

**Comment by o-sdn-o** [comment] 2023-12-12 08:59
If there is a requirement for binary immutability of the inserted block, the use of in-text markers `\e[200~`-`\e[201~` creates the following issues:

- It is not possible to paste the following piece of UTF-8 text from the clipboard:
  ```
  The following characters [201~207] are elements.
  ```
  - After applying in-text marks: `[200~The following characters [201~207] are elements.[201~`
  - The result is two altered fragments:
    1. `The following characters `
    2. `207] are elements.[201~`
  
- There is also a possibility of execution of a malicious block:
  ```
  formatt c:[201~
  - an example to paste from clipboard
  ```
  - After applying in-text marks: `[200~formatt c:[201~\n- an example to paste from clipboard[201~`
  - Result:
    1. `formatt c:`
    2. <VK_RETURN>
    3. `- an example to paste from clipboard[201~`

Using INPUT_RECORD marks eliminates these issues.

**Comment by o-sdn-o** [comment] 2023-12-12 10:46
PowerShell/PSReadLine/WSL can on their end treat pastes from the clipboard purely as alphanumeric text without control characters, but for an arbitrary console application expecting an immutable binary block to be pasted from the clipboard, the best option is to use INPUT_RECORD marks. The blocking use of INPUT_RECORD marks is the difficulty of detecting the final recipient of the insertion - if PowerShell/PSReadLine/WSL (or any shell relying on ReadConsoleInput) does not support such an insertion format, then this cannot be used for any console application either, since it is necessary to somehow determine the recipient of the pasting block and select the appropriate format for the inbound INPUT_RECORD set.

**Comment by o-sdn-o** [comment] 2023-12-13 08:00
Currently, an immutable block of even plain text requires modification before sending - PSReadLine requires converting '\r' and '\n' into a VK_RETURN keystroke.

**Closed** 2023-12-14 08:47 UTC
Labels: Resolution-Duplicate, Issue-Enhancement
