### ISSUE TITLE
Select-Object -Unique is unnecessary slow and exhaustive

### ISSUE THREAD

**Issue by heaths** [PowerShell/PowerShell#11221] opened 2019-11-30 17:15 UTC
# Steps to reproduce

```powershell
# Contrived example; imagine a pipelined collection of a lot of large objects.
get-childitem c:\ -recurse -ea silentlycontinue | select-object Name -unique
```

# Expected behavior
Items with a unique name are output immediately to the host.

# Actual behavior
Items are buffered and require a large amount of memory and a ridiculous amount of time.

# Reason
Passing `-Unique` creates a `List<T>` to store all items, and performance is O(n^2) based on [this source](https://github.com/PowerShell/PowerShell/blob/d67ee7aee3cf4e25fcd750e5f576054b0361a031/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs#L617). Instead, you could instead create a key based on properties selected or some other heuristic. In fact, using that same `ObjectCommandComparer`, you could probably even use its `GetHashCode` (if implemented properly). I have been using [my own Select-Unique](https://gist.github.com/heaths/3358559) for years quite successfully. It has O(n) performance and uses very little memory. Its key algorithm is roughly copied from what `Group-Object` does.

I had to write this when I was trying to filter unique items in a huge graph of objects. In that particular case, `Select-Object -Unique` ended up throwing an `OutOfMemoryException`. My version didn't and was much faster to use even on smaller data sets.

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2019-12-01 17:07
@heaths Thanks for raising the issue! Have you plans to contribute?

**Comment by heaths** [comment] 2019-12-01 19:28
I was thinking about it. I need to see what the test suite is like. This is an oft-used cmdlet so the bar is extremely high.

**Comment by iSazonov** [comment] 2019-12-02 04:47
Yes, the cmdlet is complex and sensitive. If you see any gaps in tests we could discuss and add new ones. 
My concern is about switching from generated comparer to string keys. Perhaps @lzybkr and @KirkMunro could add more info.

**Comment by heaths** [comment] 2019-12-03 01:23
A generated comparer could still work if it implements or works like `IEqualityComparer<T>`, which can still be used for maps. A string key in my implementation was a quick and simple little hack that has so far worked, but it doesn't get nearly the use `select-object` does.

**Comment by iRon7** [comment] 2020-04-21 18:27
I just noticed the same behavior: **`Select-Object -Unique`** stalls the pipeline:

```PowerShell
1,2,3,1,4 | ForEach-Object {Write-Host 'In:' $_; $_} |
Select-Object -Unique | ForEach-Object {Write-Host 'Out:' $_}
In: 1
In: 2
In: 3
In: 1
In: 4
Out: 1
Out: 2
Out: 3
Out: 4
```

Where I would expect it to return in this order:
```
In: 1
Out: 1
In: 2
Out: 2
In: 3
Out: 3
In: 1
In: 4
Out: 4
```

Related to StackOverflow question: [Which way is better in PowerShell and why](https://stackoverflow.com/q/61322502/1701026)

**Comment by iSazonov** [comment] 2020-04-22 05:57
@iRon7 It is easy to implement. Do you want pull PR?

Also we could cache a comparer in the code - while we get objects with the same type from pipeline we will get a perf win.

**Comment by iRon7** [comment] 2020-04-22 10:10
@iSazonov, I think I might say that I some knowledge of PowerShell itself and programming in general, but I am still learning C# and haven't pulled any PR so far. I am afraid this is above my head.
Anyways, I am happy to investigate this a little deeper presuming that the first step for me is to get familiar with the processes behind this: see e.g. if I can compile a new `Select-Object` and run the related tests.
Can you point me to a general instruction of what processes I should follow?

**Comment by iSazonov** [comment] 2020-04-22 13:24
@iRon7 
>  I am still learning C#

I started from level zero. I liked C # and I was looking for a project where I could benefit. I chose this project because it is a high-quality code and the best experts. In these conditions, training is happening rapidly. I started by monitoring PRs. This provided an understanding of the process, style and key points. When you try to understand changes in a PR, it educates great. After that, you begin code review and commenting. You can spend it 5 minutes or an hour a day for your pleasure. Then you can try to prepare the environment and compile the project. But first you have to read documents in the repo. They can be outdated and you can update them in your first PRs to get experience with contributing process and git. This is my experience.

**Comment by vexx32** [comment] 2020-04-22 13:54
@iRon7 I'd start from here: https://github.com/PowerShell/PowerShell/blob/master/README.md#building-the-repository

Once you can get it built, you can find most common commands in the `src` folder, sorted into subfolders based on which module they're part of. I believe `Select-Object` is in `Microsoft.PowerShell.Utility` so you should be able to find it in that folder. _Most_ commands are named `VerbNounCommand` so I'd start looking for `SelectObjectCommand`, but there are some exceptions, so you might just want to search for `SelectObject` and see where that gets you. 

You can sometimes find things searching the PS cmdlet name in full `Select-Object`, but that will typically only appear in documentation comments more than anything, so you might have trouble finding things using that.

If you're not used to C#, @iSazonov's suggestions will help a lot when it comes to getting familiar with it, but equally I'd say tinkering around with a cmdlet or two would also be a great way to get a feel for things.

---

On the most recent aspect of this issue specifically, where Select-Object seems to be waiting until the end of the pipeline to send off output when using `-Unique`, I'd think you can remedy that by simply outputting each object in `ProcessRecord`. It'll most likely be adding each unique object to some cached collection that it uses to ensure each object is unique, so you can build off of that by just outputting objects as they're added to the collection. Once that's working, just remember to remove the output in `EndProcessing` that most likely occurs when using `-Unique`.

**Comment by iRon7** [comment] 2020-04-25 10:41
@iSazonov, @vexx32, thanks for sharing your experience (I have hidden my previous comment).
Indeed, the [Contributing to PowerShell](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md) document was right in front of me but I simply looked over it. It cascades to several other documents, some of them I am already familiar with, others not. As stated, I need to do some investigation before I can grab this PR and need to start with some easier ones, like [Rule for the use of the command: [ScriptBlock]::Create `#1454`](https://github.com/PowerShell/PSScriptAnalyzer/issues/1454.).
My goal is to eventually pick this one up, but it might take quiet a while, therefore I do not want prevent anybody else to do so if it get any urgency.

**Comment by GraphiteWingedBird** [comment] 2021-10-15 12:39
This is the closest issue I could find instead of opening a new one. Not only is `Select-Object` slower than it should be, but there is no documentation regarding the fact that the `Unique` switch is applied to output *AFTER* other parameters have been applied. Therefore if the input collection has more items than you're asking to be returned as output, the final number isn't guaranteed. To me this feels backward and the workaround of using two instances of `Select-Object` as shown below is inherently slow due to how it is implemented. See [PowerShell Select-Object: Using -Unique with First/Last/Skip/Index](https://stackoverflow.com/a/69577421/15243610) for additional details.

**Recommendation:** Update documentation for how `Unique` interacts with `-First` / `-Last` / `-Skip` / `-Index` / `-SkipIndex` / `-SkipLast` parameters

**If possible:** Change how `Select-Object` is implemented. I don't know exactly what this would look like, but using the pipeline is an advantage in my mind, yet whenever I'm working with large data sets I find myself avoiding the pipeline syntax in scripts. This is another example that I'll be using a workaround in a script instead of the pipeline

As an example of where documentation would be helpful, consider the following which I expected to return 3 unique items:

```powershell
PS > 1, 1, 2, 2, 3, 3, 4, 4, 5, 5 | Select-Object -Unique -First 3
1
2
```
A quick workaround is to use a second call to `Select-Object` to first get the `Unique` items and then select the `First` number. This approach is 1) Slow due to how `Select-Object` is implemented, and 2) undocumented as far as I can tell

```powershell
PS > 1, 1, 2, 2, 3, 3, 4, 4, 5, 5 | Select-Object -Unique | Select-Object -First 3
1
2
3
```

**Comment by iRon7** [comment] 2021-12-02 13:49
Just a quick (PowerShell) alternative for selecting objects with a specific unique property that respects the pipeline (meaning faster and less exhaustive):

```PowerShell
$HashSet = [System.Collections.Generic.HashSet[String]]::new()
get-childitem . -recurse |Where-Object { $HashSet.Add($_.Name) }
```

**Comment by GraphiteWingedBird** [comment] 2021-12-02 16:37
Solid example @iRon7 - there are a few other examples including a LINQ solution on [Stackoverflow here](https://stackoverflow.com/a/69577421/15243610).

If anyone happens here and wants to use a `HashSet` or some alternative thereof, here are a few other examples or variations depending on your mood.

It should also be noted that for string comparisons, `Select-Object` is unexpectedly case-sensitive: [Select-Object -unique is inconsistently case sensitive](https://github.com/PowerShell/PowerShell/issues/12059)

Onto an example or two - consider the fact that `Where-Object` is just a special implementation of `ForEach-Object` that returns the pipeline object if it is true, especially if you're using a script block instead of a comparison statement. With this in mind - it is somewhat clunky to explicitly return `$_`, but you can use `ForEach-Object` and create your `HashSet` in the `-Begin` block. _However_, due to [issue #7930](https://github.com/PowerShell/PowerShell/issues/7930), you cannot free-up memory by removing the `HashSet` in an `-End` block.
```pwsh
#iRon7's example using case insensitive string comparisons
$HashSet = [System.Collections.Generic.HashSet[String]]::New([StringComparer]::InvariantCultureIgnoreCase)
Get-ChildItem . -Recurse | Where-Object { $HashSet.Add($_.Name) }

#Swapping Where-Object to ForEach-Object
Get-ChildItem . -Recurse | ForEach-Object -Begin { $HashSet = [System.Collections.Generic.HashSet[String]]::New([StringComparer]::InvariantCultureIgnoreCase) } -Process { If ($HashSet.Add($_.Name)) { $_ } }

#Getting wild with a direct invocation to script blocks instead of ForEach-Object
Get-ChildItem . -Recurse | . { begin { $HashSet = [System.Collections.Generic.HashSet[String]]::New([StringComparer]::InvariantCultureIgnoreCase) } process { If ($HashSet.Add($_.Name)) { $_ } } }
```

Definitely worth checking out [this blog](https://powershell.one/tricks/performance/pipeline) and [Issue #10982](https://github.com/PowerShell/PowerShell/issues/10982) on why the last example might be speedy.

Overall, the contrived example using `Get-ChildItem` probably isn't the most realistic scenario - but `Select-Object` definitely has a few problems that have been noted:

- `-Unique` is applied after other switches which means you might not get the total number of results you're expecting
- `Select-Object`'s case sensitivity isn't consistent and the opposite of what you would expect (and get with `Sort-Object`)

**Comment by ImportTaste** [comment] 2022-01-01 19:03
> ```powershell
> #Getting wild with a direct invocation to script blocks instead of ForEach-Object
> Get-ChildItem . -Recurse | . { begin { $HashSet = [System.Collections.Generic.HashSet[String]]::New([StringComparer]::InvariantCultureIgnoreCase) } process { If ($HashSet.Add($_.Name)) { $_ } } }
> ```
> 
> Definitely worth checking out [this blog](https://powershell.one/tricks/performance/pipeline) and [Issue #10982](https://github.com/PowerShell/PowerShell/issues/10982) on why the last example might be speedy.

The blog suggests that the `&` call operator is faster than using dot sourcing, is there a reason you went with that instead? Or was it just an oversight?

**Comment by GraphiteWingedBird** [comment] 2022-01-02 13:19
In this weird example, using `&` might have been better, but in general dot-sourcing would be more akin to a translation of what `ForEach-Object` is doing. Since we don't care about the value of `$HashSet` and would eventually want to free up the memory there, the call operator would have made sense.

I'm not sure I recall the blog comparing dot-sourcing to the call operator, as they're different operations; but should be comparable in performance. The simple difference is easy to see with something like:

```
1..5 | . { begin { $FirstVal = $_ ; "First Value was $($FirstVal)" } process { "Current number is: $($_)" } } | Select-Object -First 2

1..5 | & { begin { $FirstVal = $_ ; "First Value was $($FirstVal)" } process { "Current number is: $($_)" } } | Select-Object -First 2
```

Give each of those a whirl and check $FirstVal when you're done. For me, I'm often updating a variable (hashtable, custom object, anything really) within the `ForEach` loop structure and I need that variable beyond a pipeline one-liner, so dot-sourcing works well a lot of the time and is a more direct translation of what `ForEach-Object` is doing

**Comment by dkaszews** [comment] 2022-08-23 19:08
Duplicate of https://github.com/PowerShell/PowerShell/issues/7707

**Closed** 2022-08-25 05:01 UTC
Labels: Resolution-Duplicate, Issue-Enhancement, WG-Engine-Performance, Up-for-Grabs, WG-Cmdlets-Utility
