### ISSUE TITLE
Import-LocalizedData should have a parameter to force only using the neutral strings

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4337] opened 2017-07-24 23:54 UTC
Steps to reproduce
------------------

```powershell
Import-LocalizedData -BaseDirectory $PSScriptRoot -FileName 'mystring.psd' -UICulture 'neutral'
```

**`-UICulture 'neutral'` is only an example.**

Expected behavior
-----------------

load the neutral resources in $PSScriptRoot

Actual behavior
---------------

```none
Import-LocalizedData : Cannot find the Windows PowerShell data file 'mystring.psd1' in directory 
'/Users/travisplunk/git/powershell/neutral', or in any parent culture directories.
At line:1 char:1
+ Import-LocalizedData -BaseDirectory $PSScriptRoot -FileName 'mystring ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/Users/travispl...l/mystring.psd1:String) [Import-LocalizedData], PSInvalidOper 
   ationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                       
----                           -----                                                                                                       
PSVersion                      6.0.0-beta                                                                                                  
PSEdition                      Core                                                                                                        
GitCommitId                    v6.0.0-beta.4                                                                                               
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X...
Platform                       Unix                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                         
SerializationVersion           1.1.0.1                                                                                                     
WSManStackVersion              3.0          
```

**Comment by mklement0** [comment] 2017-07-26 03:35
I'm curious what you mean by _neutral strings_.

Wouldn't placing a  `mystring.psd1` file _directly_ in `$PSScriptRoot` do the trick, given that it  will act as the fallback file in case no `'neutral'` (or whatever argument was passed to `-UICulture`) subfolder is found?

You then wouldn't have to bother with the `-UICulture` parameter at all: If a subfolder name for the current culture exists and contains a ` 'mystring.psd1` file, it will get picked up automatically; otherwise, the `$PSScriptRoot` version will be picked up.

**Comment by daxian-dbw** [comment] 2017-07-26 15:55
As @lzybkr pointed out in https://github.com/PowerShell/PowerShell/pull/4333#discussion_r129203128, `Import-PowerShellDataFile` should be used in the case that you want to evaluate/import a specific .psd1 file. So I will close this issue as `Resolution-By Design`.
@TravisEz13 please re-open it if you have other concerns.

**Closed by daxian-dbw** 2017-07-26 15:55 UTC
Labels: Area-Cmdlets-Utility, Issue-Enhancement

**Comment by TravisEz13** [comment] 2017-07-27 19:58
Agreed, filed https://github.com/PowerShell/PowerShell-Docs/pull/1478 to update the docs to say the two CmdLets are related.
