### ISSUE TITLE
Invoking commands via CommandInfo objects fails in pwsh 7

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#12888] opened 2020-06-03 20:58 UTC
## Steps to reproduce

```powershell
pwsh -noprofile
& (Get-Command Write-Host) "text"
```

## Expected behavior

The text is written to host by calling the Write-Host cmdlet via the CommandInfo object (as it is working in Windows PowerShell, and I'm pretty sure older versions of pwsh as well).

```none
text
```

## Actual behavior

```none
ArgumentNullException: Value cannot be null. (Parameter 'key')
```

Error details from `Get-Error -Last 1`:

```none
Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'key')
    ParamName  : key
    TargetSite :
        Name          : ThrowKeyNullException
        DeclaringType : System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue]
        MemberType    : Method
        Module        : System.Collections.Concurrent.dll
    StackTrace :
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Management.Automation.CommandProcessor.ConstructInstance(Type type)
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
    Source     : System.Collections.Concurrent
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : & (gcm w*st) a
    PositionMessage  : At line:1 char:1
                       + & (gcm w*st) a
                       + ~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

## Environment data

Reproduces both in a clean `7.0.1` install as well as the most recent preview release (7.1-preview3). Also reproduces under 7.3.0-preview4 and 7.2.4.

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by rjmholt** [comment] 2020-06-03 21:55
~~Code golf~~ script works in my PS 7.1-preview.3 instance

```powershell
 &(gcm w*st)'hi'
```

**Comment by vexx32** [comment] 2020-06-03 23:03
Very strange. I'm seeing this in:

- macOS Catalina
- Windows 10 VM on said macOS machine
- A completely separate laptop.

**Comment by lukeb1961** [comment] 2020-06-04 06:42
PS C:\Users\LukeB> $PSversiontable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\LukeB> &(gcm w*st)'hi'
ArgumentNullException: Value cannot be null. (Parameter 'key')
PS C:\Users\LukeB>

PowerShell 7.1.0-preview.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\LukeB> $PSversiontable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Microsoft Windows 10.0.19635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\LukeB> &(gcm w*st)'hi'
ArgumentNullException: Value cannot be null. (Parameter 'key')
PS C:\Users\LukeB>

**Comment by vexx32** [comment] 2020-06-04 17:03
Gotcha. So it's related to loading the assembly. 

If you load pwsh (ideally with -noprofile to preclude write-host etc use on load) and then try the repro you'll get an error.

Until you actually call Write-Host directly (or I assume any other cmdlet defined in that same assembly) it will fail. As soon as one of the cmdlets in that module is called directly, it starts working again.

So it seems like there needs to be a check for if the module is loaded & to load it if need be.

**Comment by rjmholt** [comment] 2020-06-04 17:04
> Gotcha. So it's related to loading the assembly.

Ah!

> So it seems like there needs to be a check for if the module is loaded & to load it if need be.

Agreed

**Comment by vexx32** [comment] 2020-06-04 17:08
I suspect this may have regressed when #10784 was added, since I seem to recall there having to be some workarounds made in that for similar things (retrieving proper commandinfo objects when the module has yet to be loaded).

I suspect this code path simply isn't accounting for the possibility that a more complete CommandInfo object could be returned before the module is loaded.

**Comment by StevenBucher98** [comment] 2022-06-06 21:42
Is this still an issue @vexx32 ? I cannot seem to reproduce it on PS 7.2.4

**Comment by lukeb1961** [comment] 2022-06-07 08:30
PowerShell 7.3.0-preview.4
PS C:\Users\LukeB>  &(gcm w*st)'hi'
ArgumentNullException: Value cannot be null. (Parameter 'key')
PS C:\Users\LukeB>

**Comment by vexx32** [comment] 2022-06-07 12:21
@StevenBucher98  I just checked 7.2.4 as well, still happening. I will note that if you're not running it in a fresh session with no profile loaded, there's a good chance you'll miss it, because profiles _tend_ to trigger autoloading of commands, and there's a good chance you've already loaded the assembly containing the Write-Host command.

I'm pretty sure this is going to be the case for _any_ command that is provided by an assembly and not a PowerShell script that you try to invoke this way without triggering the module loading beforehand in some fashion. I think tab completion is even enough to trigger the module loading on its own, too?

That said, this is definitely still a bug and we should absolutely still fix it.

**Comment by StevenBucher98** [comment] 2023-11-21 17:41
I cannot reproduce this in 7.4, marking as resolved fixed unless anyone else reports differently.

**Closed** 2023-11-23 04:24 UTC
Labels: Issue-Bug, Resolution-Fixed
