### ISSUE TITLE
Powershell 7.2.2 crashes on startup

### ISSUE THREAD

**Issue by anders43** [PowerShell/PowerShell#17114] opened 2022-04-06 03:40 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Every time I try to start I get an exception and a stack dump. Mind you this is a company PC, on my home PC it works fine.
I am administrator on my PC. cylance antivirus program is running in background.
Older version works 7.1.x

### Expected behavior

```console
That it starts
```

### Actual behavior

```console
PowerShell 7.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

C:\Program Files\PowerShell\7>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.2
OS: Microsoft Windows 10.0.19043
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Error details

```console
PowerShell 7.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

C:\Program Files\PowerShell\7>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.2
OS: Microsoft Windows 10.0.19043
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Environment data

```powershell
see above
```

**Comment by jborean93** [comment] 2022-04-06 07:02
I believe this is due to an old PSReadLine module installed, update that and try again. It should solve that problem

**Comment by anders43** [comment] 2022-04-06 12:11
Ok and how do update PSReadLine  ?


<https://twitter.com/JABKarlsson>

<https://twitter.com/JABKarlsson>---
αη∂єяѕ кαяℓѕѕση<https://twitter.com/JABKarlsson> ***@***.***<https://twitter.com/JABKarlsson>)


________________________________

**Comment by 237dmitry** [comment] 2022-04-06 13:53
> Ok and how do update PSReadLine  ?

I use PSReadline 2.1.0 and no problem. You can install PSReadline in CurrentUser's scope:
```
Install-Module PSReadline -Scope CurrentUser -Force     # 2.2.2 latest at the moment
```
This version will be loaded the next pwsh start automatically.

**Comment by jborean93** [comment] 2022-04-06 19:08
> Ok and how do update PSReadLine  ?

That was part of my edit sorry, I would rename the existing `PSReadLine` module folder and then install a new version manually.

**Comment by daxian-dbw** [comment] 2022-04-18 17:00
Duplicate of https://github.com/PowerShell/PSReadLine/issues/3254. Upgrade to 2.2.2 version of PSReadLine will resolve the issue.

**Closed by daxian-dbw** 2022-04-18 17:00 UTC
Labels: Needs-Triage

**Comment by anders43** [comment] 2022-10-11 07:51
considering it crashes at start?


<https://twitter.com/JABKarlsson>

<https://twitter.com/JABKarlsson>---
αη∂єяѕ кαяℓѕѕση<https://twitter.com/JABKarlsson> ***@***.***<https://twitter.com/JABKarlsson>)


________________________________

**Comment by anders43** [comment] 2022-10-11 08:16
Thank you you were right, seems there was a beta version installed.

Install-Module -Name PSReadLine -Force

fixed it


<https://twitter.com/JABKarlsson>

<https://twitter.com/JABKarlsson>---
αη∂єяѕ кαяℓѕѕση<https://twitter.com/JABKarlsson> ***@***.***<https://twitter.com/JABKarlsson>)


________________________________
