### ISSUE TITLE
pwsh segmentation fault when running -Command or -File

### ISSUE THREAD

**Issue by bobrozelle** [PowerShell/PowerShell#18958] opened 2023-01-17 15:03 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We have installed Powershell 7.3.1 using Yum on a Redhat 7.9 OS.  We are getting an intermittent Segmentation Fault when attempting to run either a -File or a -Command using pwsh.  It does not happen when we just run pwsh.  The behavior is very strange.  For example, if I run "pwsh -Command {Write-Host 'hello'}" I will get Segmentation Fault, then after a few tries, it may (or may not) start working as expected.  this will continue to work until after the weekend, then it stops working.  I am trying to find out what the client sysadmins are doing on the weekend (probably running a Yum update, maybe a system reboot?)  So yea, not a lot to go on.

### Expected behavior

```console
'hello'
```

### Actual behavior

```console
Segmentation Fault
```

### Error details

```console
Can't provide since Segmentation Fault occurs immediately.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Linux 3.10.0-1160.81.1.el7.x86_64 #1 SMP Thu Nov 24 12:21:22 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment] 2023-01-30 19:06
@bobrozelle can you please take a look at https://github.com/PowerShell/PowerShell/issues/18998#issuecomment-1409173263 and also verify if that's that case for you?

**Comment by bobrozelle** [comment] 2023-01-31 12:49
Not able to duplicate the error, Linux environment has been configured to use 7.3.0 by default and I think that is keeping everything running, so that even when I attempt testing using 7.3.1, the problem does not occur.

**Comment by bobrozelle** [comment] 2023-02-03 20:27
The problem showed up again using 7.3.0.  We removed the StartupProfileData-NonInteractive file under /home/<user-name>/.cache/powershell as recommended by Issue 18998 and pwsh with a -file argument began to work again!

**Comment by daxian-dbw** [comment] 2023-02-06 22:44
@bobrozelle Thanks for the updates! Then the theory should be correct, and I will open an issue to the dotnet/runtime repo.

**Comment by daxian-dbw** [comment] 2023-02-07 23:59
.NET issue opened: https://github.com/dotnet/runtime/issues/81799

**Comment by BlacksWise** [comment] 2023-02-21 19:04
I also ran into this issue on Ubuntu 22. The error occurs once a day only on a specific machine user, who executes a lot of pwsh scripts. After a reboot powershell is working fine for approx. 24 hours. Then the issue occus again. While the issue is appearing on the users account, another user can execute the same script flawlessly.

**Comment by daxian-dbw** [comment] 2023-02-21 19:49
@BlacksWise Please try the workaround specified in https://github.com/PowerShell/PowerShell/issues/18998#issuecomment-1409173263, and help verify if that works for you.

**Comment by BlacksWise** [comment] 2023-02-22 14:58
@daxian-dbw After deleting the file the execution of several scripts runs without any problems. Are there any expected downsides if I delete the file via crontab every hour?

Just a side note an Ubuntu 20 LTS with powershell 7.3.1 runs just fine without any problems.

**Comment by daxian-dbw** [comment] 2023-02-22 17:11
For automation runs, there is no downside. That file is for faster startup, which is less interesting for automation jobs.

**Comment by daxian-dbw** [comment] 2023-03-06 18:35
I don't think we will add a switch flag just for a workaround. It would be better for you to comment in the .NET issue, so that we can get more attention from the .NET team for fixing the root problem.

**Comment by daxian-dbw** [comment] 2023-03-07 19:36
From https://github.com/dotnet/runtime/issues/81799#issuecomment-1458494879:

> We wrote an entire file processing framework using PowerShell, now the business team is thinking of rejecting the roll-out of this because of this problem and asking us to use Bash instead. Need this addressed. It is a regression and should receive attention.

@bobrozelle I'm sorry that it turns out to be such an annoying blocking issue for you. I just posted the issue to the internal channel for the .NET team and hope we can get some traction by doing that.

At the meantime, can you please consider using v7.2.x of PowerShell instead? It's a LTS version, the latest version is v7.2.10. We have NOT heard any reports about this "seg fault" issue with the v7.2.x versions, so you can avoid this issue by moving to v7.2 for now.

**Closed** 2023-11-22 10:56 UTC
Labels: Area-Maintainers-Build, Waiting - DotNetCore, 7.3-Triage, Resolution-No Activity
