### ISSUE TITLE
Default case in Switch not called when variable is in an undefined state

### ISSUE THREAD

**Issue by TheToor** [PowerShell/PowerShell#21558] opened 2024-04-30 19:05 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following code gives no output:
```
$Test = $Null | Out-Null
switch($Test) {
  $null { Write-Host "It's null" }
  Default { Write-Host "It's Default" }
}
```

The following codes gives an output on the $null case:
```
$Test = $Null
switch($Test) {
  $null { Write-Host "It's null" }
  Default { Write-Host "It's Default" }
}
```

### Expected behavior

```console
Either the $null or Default case should be called
```

### Actual behavior

```console
Neither of the cases is called when the output of the pipeline is empty.
This is also reproducable with a custom function returning nothing:
`Function Out-CustomNull { return }`

Emits the same behaviour in the switch case above
```

### Error details

```console
No error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2024-04-30 19:31
`$Null | Out-Null` doesn't return `$null`; any cmdlet - such as `Out-Null` - that produces no output technically returns the `[System.Management.Automation.Internal.AutomationNull]::Value` singleton, the "enumerable null", if you will.

In an _enumeration_ context - including input provided to a `switch` statement  -  `[System.Management.Automation.Internal.AutomationNull]::Value` behaves _like an empty enumerable_; that is, _no_ iterations take place; the `switch` statement is effectively _skipped_.

That is, it behaves like the following statement: `switch (@()) { Default { 'never get here' } }`: enumerating the empty array results in no elements, so the statement body is never entered.

What is tricky is that it isn't easy to discover whether a given variable value is a bona fide `$null` or `[System.Management.Automation.Internal.AutomationNull]::Value`, especially given that in _expression_ contexts as well as in parameter-binding, the latter is effectively the same as `$null`.

#13465 is a green-lit proposal to make discovery of `[System.Management.Automation.Internal.AutomationNull]::Value` easier, via `$Test -is [System.Management.Automation.AutomationNull]`, but it hasn't been implemented yet; also, it was inappropriately closed by the bot.

**Comment by 237dmitry** [comment] 2024-04-30 19:33
`default` is executed when no switches are found that match the condition.

```
$null -eq $null     # True
```

**Comment by TheToor** [comment] 2024-04-30 20:07
Default is not executed in that case. That is the problem.
```
$Test = $Null | Out-Null
switch($Test) {
  $null { Write-Host "It's null" }
  Default { Write-Host "It's Default" }
}
```
Produces no output when the default case should have been run.

**Comment by TheToor** [comment] 2024-04-30 20:20
Thanks @mklement0 for the detailed explaination.
Digging through the other proposal and issues this is probably a case not often encountered but still results in confusing behaviour when it happens.

Any plans to reopen the conversation of your proposed implementation?

**Comment by 237dmitry** [comment] 2024-04-30 20:36
> Default is not executed in that case. That is the problem.

This is because there is a $null switch, which is equivalent to $Test and returns $true. If you have a match, then `default` will not be executed.

**Comment by mklement0** [comment] 2024-04-30 20:42
Glad to hear it helped, @TheToor; I have no say in what gets reopened, but I generally think that _all_ auto-closed issues that have the `Up-for-grabs` label should be reopened, as previously suggested in https://github.com/PowerShell/PowerShell/issues/21406#issuecomment-2039752097.

**Comment by daxian-dbw** [comment] 2024-06-10 21:28
@mklement0 has explained it very well (thank you!) that it's because `AutomationNull` exposes difference behavior comparing to `$null` in the enumeration context. The Engine WG reviewed this issue in the meeting of 5/13 and agreed that this is by design.

The `AutomationNull` is documented at https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null?view=powershell-7.4#empty-null. I also reopened the issue https://github.com/PowerShell/PowerShell/issues/13465.

**Comment by mklement0** [comment] 2024-06-10 22:17
Thank you, @daxian-dbw; "empty null", as in the docs you link to, is actually not a good name for `[System.Management.Automation.Internal.AutomationNull]::Value`, so I've created:

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11175

**Comment by mklement0** [comment] 2024-06-10 22:25
@daxian-dbw, I also suggest adding the `Keep-Open` label to #13465

**Closed** 2024-06-12 07:38 UTC
Labels: WG-Engine, Resolution-By Design, WG-Reviewed
