### ISSUE TITLE
Background color leaking to next scrolled line

### ISSUE THREAD

**Issue by yves-dolce** [PowerShell/PowerShell#15130] opened 2021-03-31 17:16 UTC
## Steps to reproduce
Issue this command on the last line of your window so that scrolling is taking place:
```powershell
Write-Host "Bebop" -BackgroundColor Green -ForegroundColor Black
```

## Expected behavior
The line below the "Bebop" line is clean (i.e. what was done with `Write-Host` doesn't leak into the following line)

## Actual behavior

The line is painted green
![image](https://user-images.githubusercontent.com/1760825/113184538-23a0c880-920a-11eb-9b86-a2fd6108fe93.png)

## Environment data

```none
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2021-04-02 06:49
Please make the title of the issue more descriptive.

Please check with latest PowerShell 7.2 Preview.

**Comment by yves-dolce** [comment] 2021-04-06 19:11
Still there in Preview 4:
![image](https://user-images.githubusercontent.com/1760825/113765484-2f403380-96d1-11eb-93cc-f8d867bfe937.png)

**Comment by iSazonov** [comment] 2021-04-07 04:50
@yves-dolce Please remove PSReadline (Remove-Module PSReadline) and check again. If you can not repro without PSReadline please install and check with latest PSReadline prerelease version.

**Comment by yves-dolce** [comment] 2021-04-16 06:18
I can repro without it.

**Comment by freMea** [comment] 2021-06-06 18:17
# Similar issues or duplicates

#14686
#11267

# Setup

I can reproduce. Same without PSReadline.

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Tested with cleaned session from user installed modules.
```
PS>gmo | select name, version

Name                            Version
----                            -------
Microsoft.PowerShell.Management 7.0.0.0
Microsoft.PowerShell.Utility    7.0.0.0
```

# Step to reproduce

I you run this below code directly or via a file.ps1, the result is the same.

 ```powershell
[Enum]::GetValues([ConsoleColor]) |
ForEach-Object {
	$color = $_.ToString().Trim()
	if (($color -like 'dark*') -or ($color -like 'black')) {
		Write-Host 'test' -BackgroundColor Black
		Write-Host "$color" -ForegroundColor $color
		Write-Host "$color" -ForegroundColor White -BackgroundColor $color
	} else {
		Write-Host 'test' -BackgroundColor Black
		Write-Host "$color" -ForegroundColor $color
		Write-Host "$color" -ForegroundColor Black -BackgroundColor $color
	}
}
```
# Results
Rendering in console or in WT.
![test](https://user-images.githubusercontent.com/22337329/120934212-b1fb6400-c6fd-11eb-8915-e232e0f6e5f7.gif)

As we can see, `write-host` with `-BackgroundColor` option fills the entire line with the color. For some reason, the line length seems to be longer than the console width and leak to the the next scroll line. This is solved when resizing console width.

# Expectation

First, documentation doesn’t mention `write-host` with `-BackgroundColor`  is supposed to fill the entire line instead of the object alone. This needs to be clarified.

Secondly, it seems that line length seen by `write-host`  is longer than the console width. In any case, background color should not line break.

# Workaround (almost)

Use `-NoNewline` if using `-BackgroundColor`.

```powershell
[Enum]::GetValues([ConsoleColor]) |
ForEach-Object {
	$color = $_.ToString().Trim()
	if (($color -like 'dark*') -or ($color -like 'black')) {
		Write-Host "`n$color" -ForegroundColor $color
		Write-Host "$color" -ForegroundColor White -BackgroundColor $color -NoNewline
	} else {
		Write-Host "`n$color" -ForegroundColor $color
		Write-Host "$color" -ForegroundColor Black -BackgroundColor $color -NoNewline
	}
}
```

This will produce non apparent bug. Only the object is filled with background color. But when resizing window, the all line is filled.
![test](https://user-images.githubusercontent.com/22337329/120935224-01439380-c702-11eb-98ac-1c60623725ac.gif)

 # Note

This problem does not occur in the integrated terminal for VSCode

**Comment by yves-dolce** [comment] 2021-06-11 07:08
It doesn't look like anybody cares... Thanks for the workaround and pointing to those duplicates.

**Comment by nmbell** [comment] 2021-11-16 06:06
As a workaround, you can try adding a call to ScrollDisplayDownLine before the call to Write-Host, .e.g.:
```
[Enum]::GetValues([ConsoleColor]) | ForEach-Object {
	[Microsoft.PowerShell.PSConsoleReadLine]::ScrollDisplayDownLine()
	Write-Host 'some text' -BackgroundColor $_.ToString()
	# [Microsoft.PowerShell.PSConsoleReadLine]::ScrollDisplayUpLine()
	Write-Host 'some more text'
}
```

It does create some upward scrolling until you hit the bottom of the console, though. You can call ScrollDisplayUpLine afterwards if this is an issue, but then that can cause some jerkiness in the display. Six of one... :man_shrugging:.

**Comment by SteveL-MSFT** [comment] 2023-03-28 00:34
The scrolling problem is a dupe of https://github.com/PowerShell/PowerShell/issues/18984
The resizing issue is a problem with the terminal and needs to be opened in their repo.

**Closed** 2023-03-29 02:00 UTC
Labels: Resolution-Duplicate, WG-Interactive-Console, Needs-Triage

**Comment by zhusulai** [comment] 2023-04-20 17:29
Just to share that the workaround posted by @Fred-Vatin solved the problem for me. The only thing I did differently is to call `Write-Host` again to make sure a newline is added. Something like this:
```
Write-Host $Object -ForegroundColor $ForeGroundColor -BackgroundColor $BackGroundColor -NoNewline
Write-Host
```
