### ISSUE TITLE
xml better with select-xml (1)

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15032] opened 2021-03-15 20:08 UTC
Hi guys!!

add new parameters to select-xml fort better output

`1) select-xml -AsString`
to return xml string output instead of xml object

`2) select-xml -Node `
the switch -Node is here to simplify this code `select-xml -path $xmlfile -xpath $xpath | select -expand node` it return the same output but without another select-object -expand node

**Comment by mklement0** [comment] 2021-03-15 23:09
👍 for `-AsString`.

As for `-Node`: I like the idea in principle, but, following the guidance suggested in #7855, a `-Raw` switch seems more appropriate (consistent with `Select-String -Raw`, for instance), which has been suggested before: see #13669

**Comment by joeyaiello** [comment] 2021-03-16 17:30
Closing as a dupe of the two issues that @mklement0 raised

**Closed by joeyaiello** 2021-03-16 17:30 UTC
Labels: Area-Cmdlets-Utility, Issue-Enhancement, Resolution-Duplicate

**Comment by mklement0** [comment] 2021-03-16 17:36
Thanks, @joeyaiello, but the linked issues only cover the `-Node` -> `-Raw` proposal, so perhaps we should reopen this for the `-AsString` proposal, or, @p0W3RH311, perhaps you're willing to create new proposal that focuses just on `-AsString` (and links to #13669).
