### ISSUE TITLE
Send-MailMessage $Subject Mandatory=$true

### ISSUE THREAD

**Issue by BitteringAgent** [PowerShell/PowerShell#4043] opened 2017-06-18 01:00 UTC
Not a bug, but a request for "Send-MailMessage" cmdlet

```powershell
 $From = $email
    $To = $Number
    $Body = "Something"
    $Subject = $null
    $SMTPServer = "smtp.gmail.com"
    $SMTPPort = "587"
    Send-MailMessage -From $From -to $To -Subject $Subject `
        -Body $Body -SmtpServer $SMTPServer -port $SMTPPort -UseSsl `
    -Credential $Cred
```

RESULT:
```
Send-MailMessage : Cannot validate argument on parameter 'Subject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:8 char:52
+       -Body $Body -SmtpServer $SMTPServer -Subject $Subject -port $SM ...
+                                                    ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-MailMessage], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.SendMailMessage
```

CAUSE:
```
[Parameter(Mandatory=$true, Position=1)]
        [Alias('sub')]
        [ValidateNotNullOrEmpty()]
        [string]
        ${Subject},
```

--------
Emails do not require subjects to be present.  However, in the Send-MailMessage cmdlet, the $subject parameter is set to "Mandatory=$true".  Since an email does not require a subject, this should really be set to "$false". 

I've created my own workaround this, but I feel that this should be changed since a subject is not imperative for an email to be sent.

**Comment by SteveL-MSFT** [comment] 2017-06-18 03:34
Seems reasonable.  Cc @joeyaiello

**Comment by iSazonov** [comment] 2017-06-18 18:35
Missing Subject is a bad practice. By default, we must ask for it to exist. Maybe add `-IgnoreSubject`?

**Comment by ThreeFive-O** [comment] 2018-08-20 18:57
I would like to try this one. 

Most information is gathered from PR #4044, which was closed due to non-addressed comments.

The easiest way to implement the option to make `-Subject` always mandatory, unless the user explicitly states to send the mail without a subject is to use `ParameterSetName` as stated by @dantraMSFT.

Though I would like to go with the `-Force` switch, due to consistency with other cmdlets as suggested by @SteveL-MSFT.

ParameterSetName "Default": This would prompt for missing parameter `-Subject` due to being a mandatory parameter
```powershell
Send-Mail -From xyz@from.com -To xyz@to.com -Body 'Test Mail Body' ...
```

ParameterSetName "Force": This would not prompt for missing parameter `-Subject`
```powershell
Send-Mail -From xyz@from.com -To xyz@to.com -Body 'Test Mail Body' -Force ...
```

One problem is, that `Send-Mail` uses positional parameters, where `-Subject` is at position 1. Two options would be available:

1. ParameterSetName "Force": Don't use positional parameters at all.
2. ParameterSetName "Force": Make `-Body` positional parameter at 1 instead of 2 and `-SmtpServer` 2 instead of 3. 
Example for solution 2:
```powershell
Send-Mail xyz@to.com 'Test Mail Body' smtp.server.com -Force ...
```

TODOs

- [ ] Submit PR to Powershell repository with suggested modifications.
  - [ ] Implement `-Force` switch.
  - [ ] Include test case which uses `-Force` switch.
- [ ] Submit PR to Powershell-Docs repository to reflect alternative parameter set.

Any feedback is highly appreciated. Thx.

**Comment by joeyaiello** [comment] 2018-08-20 19:12
Sounds good to me. I like solution 2 👍

**Comment by SteveL-MSFT** [comment] 2018-08-20 20:23
@ThreeFive-O thanks for taking this up!  The one concern I have is that the proposal forces `-Force` to always apply to no-subject.  Perhaps it would be better to have a `-NoSubject` switch thereby having a specific parameter set for that scenario.

**Comment by dantraMSFT** [comment] 2018-08-20 20:23
Personally, I think we're overloading -Force here.  Consider potential help text 

'-Force: sends the mail message without a subject'.  

I personally favor your other suggestion, -NoSubject. 

'-NoSubject: sends the mail message without a subject.'

I favor -NoSubject and an associated parameter set.

Changing the parameter order for the new parameter set should be fine since it requires an opt-in and won't break existing scripts.

**Comment by ThreeFive-O** [comment] 2018-08-21 16:33
Two more questions:

1. Strange case: Using the switch `-NoSubject` would exclude `-Subject` from this parameter set. What if someone uses a pipeline or splatting where both parameters `-NoSubject` and `-Subject` are passed through? This would result in an error, since `-Subject` is not available. My other suggestion with the `-Force` parameter would have allowed still to include `-Subject`, but to ignore the mandatory prompt.

2. `Send-MailMessage` is not available in the version 6 Powershell-Docs repository. Am I missing something?

**Comment by iSazonov** [comment] 2018-08-22 04:05
@ThreeFive-O Please open new issue in PowerShell-Docs repo https://github.com/PowerShell/PowerShell-Docs

**Comment by SteveL-MSFT** [comment] 2018-09-05 22:33
@PowerShell/powershell-committee reviewed this, making a parameter that was mandatory no longer mandatory is not a breaking change.  Recommendation is to make `mandatory=false`, remove validation for `nullorempty` and set default to empty string.

**Comment by ece-jacob-scott** [comment] 2019-02-23 20:08
Hack Illinois Competition participant. 
Working with Dan and Tyler

I can take this one on.

**Comment by ece-jacob-scott** [comment] 2019-02-23 23:06
Tested with Tyler's own smtp server.
The test when run in CI just don't run.

We used this code to test on my local environment and confirmed that it works.
`PS /home/jacob/Documents/Powershell> $a = @{
>> From = "me@tylerleonhardt.com"
>> To = "tylerl0706@gmail.com"
>> Body = "adsfsdafsfda"
>> SMTPServer = "smtp.mailgun.org"
>> Port = "587"
>> Credential = (Get-Credential)
>> }

PowerShell credential request
Enter your credentials.
User: postmaster@tylerleonhardt.com
Password for user postmaster@tylerleonhardt.com: **************************************************

PS /home/jacob/Documents/Powershell> Send-MailMessage @a -UseSsl
PS /home/jacob/Documents/Powershell> 
`

**Comment by ThreeFive-O** [comment] 2019-02-24 06:16
@ece-jacob-scott Tests for Send-MailMessage cmdlet don't run on CI, since there is no SMTP server installed on the CI agents.
See PR #8859 which would allow testing the cmdlet on the CI agents. PR is ready but yet to be merged.

**Closed** 2019-03-18 03:24 UTC
Labels: Area-Cmdlets-Utility, Committee-Reviewed, First-Time-Issue, Hackathon, Issue-Discussion, Up-for-Grabs
