### ISSUE TITLE
Helper method converting PSObject to string may fail

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#11797] opened 2020-02-07 01:18 UTC
This was encountered by a MS Partner team.  When calling a cmdlet that outputs lots of objects, the [SmartToString()](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs#L205) helper throws the exception "InvalidOperationException: Collection was modified after the enumerator was instantiated" as the PSObject is modified before the conversion completes.  There is already code to catch an ExtendedTypeSystemException and we could extend that for any exception and just return string.empty.  Or alternatively, we could make a copy of the object but that would impact perf.

In the repro, it was explicitly going through the `Format-List` code, although `Format-Table` may also use this helper.

**Comment by mklement0** [comment] 2020-02-07 03:58
This may not be _technically_ related, but it reminded me of #6163

**Comment by iSazonov** [comment] 2020-02-07 07:49
If the PSObject is changed while it is enumerated it looks like a race condition in user code - why should we hide the exception?

**Comment by SteveL-MSFT** [comment] 2020-02-19 22:37
@iSazonov in this specific repro, they were enumerating a large collection of AD objects and it only repro'd for them when transcription was enabled although I'm not sure that is directly related.  Transcription may have just slowed it down to make the race condition happen more easily.

**Comment by iSazonov** [comment] 2020-02-20 03:53
It looks as fundamental problem. I caught the same with AccountManagement API. It depends on a `context` and every call to the object causes a "remote" call to ensure that the object is live. So if such check presents in enumerator we can not resolve this exception naturally.

**Comment by HerbertMauerer** [comment] 2020-07-14 14:28
Hello,
I'm the Windows code Escalation Engineer working on this problem, I'm partnering with Krishna Yalavarthi <Krishna.Yalavarthi@microsoft.com> from the Windows hotfix/CSD team.

The problem happens in the Active Directory Admin Center (ADAC) when there are many objects in a container. I have a customer waiting for a resolution on this. And I have the worry that additional customers run into this as they switch from the older toolset to ADAC. 

I'm aware you have other deliverables. I would appreciate if you could share an ETA when you think you can start working on this  problem.

Thanks

Herbert Mauerer

**Comment by vexx32** [comment] 2020-07-14 15:03
If what @iSazonov is saying is correct, I suspect the issue can only really be resolved in the ActiveDirectory module itself.

PowerShell can attempt to _mitigate_ the eventual effect of it, but it can't change the way the ActiveDirectory module is choosing to operate. The best we could hope for from the PowerShell end would probably be that some objects would end up quietly skipped and maybe a less intrusive error would be recorded after enumeration completes.

But even then, I'm not sure it's something PowerShell will be able to account for.

**Comment by iSazonov** [comment] 2020-07-14 19:43
@HerbertMauerer Because ADAC is not OSS we need a simple repro like a script or GitHub shared C# project. We need to understand what API to investigate.
Perhaps you could share more information about the broken scenario. As I know ADAC limits to 20000 objects by default and max limit is 100000. Perhaps it is not right things to build so large PSObject and convert it to string.

**Comment by iSazonov** [comment] 2020-07-20 17:32
I guess ADAC implements custom transcription and you could look the code - I wonder if it changes an object in the enumerator.

**Comment by HerbertMauerer** [comment] 2020-07-27 08:05
Hello,

do you have Windows source access?
I could also hook you up with the DEV Owner of ADAC.

Herbert

**Comment by iSazonov** [comment] 2020-07-27 11:58
No, I haven't the access.

**Comment by HerbertMauerer** [comment] 2020-07-28 05:12
Hello,

In windows this is area path:
OS\Core\Base\DevPartners\AD-Active Directory\ADDS - Active Directory (DS and LDS)\Manageability\UI - AD Admin Center

Responsible folks:
Developer: ramanch@ntdev.microsoft.com
PM: ccrane@microsoft.com

You can refer to the windows hotfix request fot this investigation, it's https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/25542034.

**Comment by SteveL-MSFT** [comment] 2020-07-29 20:59
@HerbertMauerer that information won't help anyone here in the community.

**Comment by SteveL-MSFT** [comment] 2020-08-05 19:48
For @PowerShell/powershell-committee, a couple of options:

- do nothing
- add warning/non-terminating error and return empty string allowing pipeline to continue
- copy collection before enumerating

**Comment by SteveL-MSFT** [comment] 2020-08-05 22:13
@PowerShell/powershell-committee reviewed this, we agreed for 7.1 we should have a warning message saying "Object skipped: <exception message>" returning an empty string.

**Comment by rjmholt** [comment] 2020-08-06 00:57
> If the PSObject is changed while it is enumerated it looks like a race condition in user code (how do they change it? from another runspace?) - why should we hide the exception?

This happens in some contexts with PowerShell APIs when they are called off the pipeline thread. If your module does something like get a value from PowerShell, store it, allow the pipeline to continue and later tries to use or manipulate the variable, issues like this may occur. As someone who's hit issues like this in many places, it's painful, but it represents a race condition in library code.

It's also worth noting that formatters contain script, so they need a runspace/thread to work on.

So to resolve this properly in your code you must:

- Ensure you do not yield the pipeline before you have finished processing PowerShell objects. If you are obtaining PowerShell objects without a pipeline (e.g. by API traversal or reflection) you should be very careful about how and when you do so.
- Fall back to `Out-String` if needed. `Out-String` is the best mechanism for rendering PowerShell formatting to a string object. Similarly, `Out-File` is best for printing to a file. These can be run like this:

```csharp
string strRepr;
using (var pwsh = PowerShell.Create(RunspaceMode.CurrentRunspace))
{
    strRepr = pwsh.AddCommand("Out-String").Invoke(inputObjectCollection);
}
```

**Comment by iSazonov** [comment] 2020-08-06 03:45
> we should have a warning message saying "Object skipped: " returning an empty string.

It looks like hiding a race condition in customer code. :-( It can be dangerous.

**Comment by rjmholt** [comment] 2020-08-06 16:12
From the original description, it sounds like the issue was occurring in the actual call of `Format-List`. If it's being called as we expect, it just sounds like there's some kind of race condition or over-aggressive optimisation in our code.

**Comment by iSazonov** [comment] 2020-08-06 16:33
@rjmholt From the comment https://github.com/PowerShell/PowerShell/issues/11797#issuecomment-661056380 the issue is with transcripting or in transcripting.

**Comment by HerbertMauerer** [comment] 2020-08-10 07:25
Hello,

Adding Krishna and Raman who own the bug and area, this is bug https://dev.azure.com/microsoft/OS/_workitems/edit/25542034.
Summary:
AD Admin Center (DSAC.EXE) is switching to a container with 20000 or more objects.
This works fine without powershell transscripting. When it is enabled, you get an error dialog saying:
"Collection was modified after the enumerator was instantiated"

And you don’t get the list of objects in the container. The customer encounters this for the “Deleted Objects” container when he wants to restore AD objects, but I can also reproduce it with a OU with 20000 objects.
When you run the Get-ADObject query DSAC uses under the hood in Powershell, the query is successful. So you can’t really rebuild what DSAC is doing in plain PS.

We have a TTD of the error attached to related RFC: https://dev.azure.com/microsoft/OS/_workitems/edit/24080919
I worked it to the point where we see an invalid result set size variable within .Net runtime.

We need some collaboration between ADAC and Powershell teams to get to the bottom of this problem. Can you please assist?

Herbert Mauerer
Senior Escalation Engineer
Customer Services and Support EMEA
WW Communities Debugging<http://aka.ms/wwcomdebug>, SME
Which WW Community should you join? Click here<https://microsoft.sharepoint.com/teams/campusWWCs/Pages/Landing.aspx>
[cid:image001.jpg@01D66EF7.6EB32520]
Do you have feedback for me? Please ask me for a connect survey.

**Comment by HerbertMauerer** [comment] 2020-08-10 07:25
Email to OS bug and area owners:
Adding Krishna and Raman who own the bug and area, this is bug https://dev.azure.com/microsoft/OS/_workitems/edit/25542034.
Summary:
AD Admin Center (DSAC.EXE) is switching to a container with 20000 or more objects.
This works fine without powershell transscripting. When it is enabled, you get an error dialog saying:
"Collection was modified after the enumerator was instantiated" 

And you don’t get the list of objects in the container. The customer encounters this for the “Deleted Objects” container when he wants to restore AD objects, but I can also reproduce it with a OU with 20000 objects.
When you run the Get-ADObject query DSAC uses under the hood in Powershell, the query is successful. So you can’t really rebuild what DSAC is doing in plain PS.

We have a TTD of the error attached to related RFC: https://dev.azure.com/microsoft/OS/_workitems/edit/24080919
I worked it to the point where we see an invalid result set size variable within .Net runtime.

We need some collaboration between ADAC and Powershell teams to get to the bottom of this problem. Can you please assist?

**Comment by rjmholt** [comment] 2020-08-10 16:21
Original public info from @HerbertMauerer:

AD Admin Center (DSAC.EXE) is switching to a container with 20000 or more objects.
This works fine without powershell transscripting. When it is enabled, you get an error dialog saying:
"Collection was modified after the enumerator was instantiated"

And you don’t get the list of objects in the container. The customer encounters this for the “Deleted Objects” container when he wants to restore AD objects, but I can also reproduce it with a OU with 20000 objects.
When you run the Get-ADObject query DSAC uses under the hood in Powershell, the query is successful. So you can’t really rebuild what DSAC is doing in plain PS.

I worked it to the point where we see an invalid result set size variable within .Net runtime.

**Comment by SteveL-MSFT** [comment] 2020-12-16 05:57
@iSazonov I've looked through the transcription code and don't see anything that would modify the object.  I think transcription is misleading and likely just making the race condition more apparent as it changes the timing.

**Comment by iSazonov** [comment] 2020-12-16 06:13
Perhaps transcription slows down the code and increases the likelihood the race condition.

I think ADAC should be re-implemented with best practice as ADUC module does - map native objects to custom ones and don't use wrapping in PSObject. This approach helps to resolve the race condition issue and to get great perf win.

**Closed** 2021-01-28 00:37 UTC
Labels: Committee-Reviewed, Issue-Bug
