### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#16617] opened 2021-12-14 22:17 UTC
### Name of the Distribution

Debian

### Version of the Distribution

bullseye

### Package Types

- [X] Deb
- [ ] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

arm32

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by rhubarb-geek-nz** [comment] 2021-12-15 05:57
Goal is to target the Raspberry Pi's raspbian, but debian/11/armhf should be sufficient and generic

**Comment by daxian-dbw** [comment] 2022-01-18 22:18
Duplicate of https://github.com/PowerShell/PowerShell/issues/10923

**Closed by daxian-dbw** 2022-01-18 22:18 UTC
Labels: Distribution-Request, Review - Maintainer, Needs-Triage

**Comment by rhubarb-geek-nz** [comment] 2022-01-18 22:23
Hi, it is not a duplicate of 10923, that was for AMD64, this is for ARM32.
The requests explicitly say one architecture per request.
