### ISSUE TITLE
Expand-Archive does not preserve filenames with accents

### ISSUE THREAD

**Issue by mcx808** [PowerShell/PowerShell#14687] opened 2021-02-01 15:41 UTC
## Steps to reproduce

[test Alex é è ç à_.zip](https://github.com/PowerShell/PowerShell/files/5904878/test.Alex.e.e.c.a_.zip)

```powershell
#After downloading the attached example:
Expand-Archive '.\test Alex é è ç à_.zip' -DestinationPath outfolder
Get-ChildItem outfolder
```

## Expected behavior

```none
#File should be:
test Alex é è ç à .txt
```

## Actual behavior

```none
#Filename is
test Alex � � � � .txt

```

## Environment data

Originally noticed this behaviour in Powershell 5.1 on Windows Server 2016.
Confirmed the same behaviour on Powershell 7.1.1 on Windows 10 and macOS 11.1
This doesn't happen when extracting a zip with the windows explorer, or other tools such as 7zip.

```none

Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.21286
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by mcx808** [comment] 2021-02-01 16:18
After I posted this I found a related enhancement request that largely deals with this issue: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/88

**Comment by mklement0** [comment] 2021-02-01 18:51
Thanks, @mcx808 - the comment I posted there may be of interest to you as well.

**Comment by jborean93** [comment] 2021-02-01 22:38
I believe this should be closed in favour of the issue in Microsoft.PowerShell.Archive. That is where the code is located and should be fixed.

**Comment by daxian-dbw** [comment] 2021-02-02 17:19
Close as a duplicate of PowerShell/Microsoft.PowerShell.Archive#88

**Closed by daxian-dbw** 2021-02-02 17:19 UTC
Labels: Needs-Triage
