### ISSUE TITLE
List format on FileInfo and DirectoryInfo on Unix-like systems shows Mode property instead of UnixMode, unlike table format

### ISSUE THREAD

**Issue by schuelermine** [PowerShell/PowerShell#16850] opened 2022-02-05 10:52 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On Unix-like systems, if a `FileInfo` or `DirectoryInfo` object is formatted as a list by `Format-List`, it displays the `Mode` property, but if it is formatted as a table, e.g. by `Format-Table`, it displays the `UnixMode` property.

### Expected behavior

```console
PS /> gi . | ft

    Directory: 

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxr-xr-x root             root               11/10/2021 00:23           4096 /

PS /> gi . | fl

    Directory: 

Name           : /
CreationTime   : 11/10/2021 00:23:56
LastWriteTime  : 11/10/2021 00:23:56
LastAccessTime : 05/02/2022 10:56:57
UnixMode       : drwxr-xr-x
LinkType       : 
Target         :
```

### Actual behavior

```console
PS /> gi . | ft

    Directory: 

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxr-xr-x root             root               11/10/2021 00:23           4096 /

PS /> gi . | fl

    Directory: 

Name           : /
CreationTime   : 11/10/2021 00:23:56
LastWriteTime  : 11/10/2021 00:23:56
LastAccessTime : 05/02/2022 10:56:57
Mode           : d-r--
LinkType       : 
Target         :
```

### Environment data

```powershell
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.16.2 #1-NixOS SMP PREEMPT Thu Jan 20 08:12:22 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment] 2022-02-05 14:10
You can edit output format and  update default with custom one. `Update-FormatData`
![fd](https://user-images.githubusercontent.com/78153320/152644779-6b9a6492-5db6-4619-b6af-35bb6d0d56b6.png)

**Comment by schuelermine** [comment] 2022-02-05 14:52
Yes, but I think that should be the default wherever UnixMode is already the default.

**Comment by jhoneill** [comment] 2022-02-05 18:52
You can customize it, but really the properties for list and table should be in sync - there is no reason for them to be different. 

It looks to me like the table was changed for Unix and the list was overlooked.

**Comment by rkeithhill** [comment] 2022-02-05 19:02
As an example of the customization, I use `Update-TypeData` to get the table output to remove the `@AD.COMPANYNAME.COM` from both `User` and `Group` PSScriptProperties since it was causing gci ouput to wrap.

**Comment by jhoneill** [comment] 2022-02-06 11:49
@iSazonov   Do we know a reason why the list _should_ show a different mode from the table ?

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs  has an `#if unix` block _for tables_ at line 44,  but there isn't one _for lists_.  

If I'm right and this was by omission not by design , then should be marked as a bug not an enhancement.  It's one of those mods where adding a test is much more work than making the change :-)

**Comment by iSazonov** [comment] 2022-02-06 17:51
> @iSazonov Do we know a reason why the list _should_ show a different mode from the table ?

It was an enhancement from @JamesWTruher for table format. Anybody could pull a PR to enhance list format too.

**Closed** 2023-11-22 11:03 UTC
Labels: Issue-Enhancement, Needs-Triage, WG-Engine-Format, Resolution-No Activity
