### ISSUE TITLE
asterisk in path name affects `ls` differently according to that `ls` is with `-Recurse` or not. 

### ISSUE THREAD

**Issue by LqkUWp** [PowerShell/PowerShell#17991] opened 2022-08-30 14:55 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a file `.\o\abc [defg].pdf`, then I try all commands below to `ls` it. The first char y/x represents that the corresponding command works or not, i.e. prints the file or nothing without any error. 

1. with recurse
   + without asterisk
      ```
      y ls -Path 'abc [[]defg[]].pdf' -Recurse
      y ls -Path 'abc `[defg`].pdf' -Recurse
      x ls -Path 'abc ``[defg``].pdf' -Recurse
      ```
   + with asterisk
      ```
      y ls -Path '*\abc [[]defg[]].pdf' -Recurse
      y ls -Path '*\abc `[defg`].pdf' -Recurse
      x ls -Path '*\abc ``[defg``].pdf' -Recurse
      ```
2. without recurse
   + without asterisk
      ```
      x ls -Path 'o\abc [[]defg[]].pdf'
      y ls -Path 'o\abc `[defg`].pdf'
      y ls -Path 'o\abc ``[defg``].pdf'
      ```
   + with asterisk
      ```
      x ls -Path '*\abc [[]defg[]].pdf'
      x ls -Path '*\abc `[defg`].pdf'
      y ls -Path '*\abc ``[defg``].pdf'
      ```

### Expected behavior

```console
The impact of asterisk on `ls` should be exactly the same whether `ls` is with `-Recurse` or not. 

I understand these two things: 

1. In each minor command group above, all three commands works differently according to [[], `[, or ``[. 
2. whether `ls` is with `-Recurse` or not, asterisk affects the behavior of `ls`, i.e. in each major group composed of two minor groups above, any possible difference between the two minor groups results from asterisk. 

But it looks like a bug that asterisk affects differently on bare `ls` and `ls` with `-Recurse`. In the 1st major group with recurse above, you can see that asterisk does not affect on `ls`. But in the 2nd major group without recurse, asterisk does affect on `ls`. That difference is a little annoying.
```

### Actual behavior

```console
Just as the first char y/x in each command line shows.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by jhoneill** [comment] 2022-09-07 14:16
There are some oddities about how parts of Get-ChildItem (alias ls) work, most of which are in the filesystem provider rather than the cmdlet. These are compounded when using wildcard characters in file names. 

There is no obvious reason why ```ls -Path '*\abc `[defg`].pdf' ``` should not work.  `ls -Path '*\foo.pdf' ` is fine. 

The path in  `ls -Path 'abc [[]defg[]].pdf'  seems to read as abc , then one from the set  {"[" } , defg , one from the set {"]" } , and finally .pdf   which matches.  
 `"abc [defg].txt" -like 'abc [x[]defg[]x].txt'  `  makes the two sets two-character ones and returns true. So the recursive behaviour is right and it's unclear why the not recursive one does something different 

The examples where you have ```  ``  ```  are escaping the ```   `  ``` itself, so those are saying a ``` ` ``, then` one from the set {"d","e","f","g"} and another ```  `  ```

**Comment by mklement0** [comment] 2022-09-07 15:53
With respect to backtick-escaping (`` ` ``):

 * Only ever _one_ `` ` `` should be required to escape `[` and `]` - irrespective of whether `-Recurse` is present or not.
   * As an aside: even in cases where the single `` ` ``-escaping works, the fact that `]` _also_ needs escaping could be considered a bug in its own right, because that is _not_ a requirement of wildcard matching itself; e.g., `'[ab]' -like '`[ab]'` works fine without also escaping the `]` (though you may do so).

 * Such oddities are collected in the following catch-all issue:
    * https://github.com/PowerShell/PowerShell/issues/7999

With respect to escaping `[` and `]` as `[[]` and `[]]`:

* This _should_ work and does with pure wildcard matching: `'[ab]' -like '[[]ab[]]'`
* Similar to #17992, the problem seems to come down to still treating what is between `[` and `]` as a _character set_, even though that is clearly inappropriate if the `[` and `]` are _escaped_.
* While the problem is not covered by #7999 as such, I wonder if resolving the latter would also resolve this.

**Closed** 2023-11-22 10:59 UTC
Labels: WG-Engine-Providers, Needs-Triage, Area-FileSystem-Provider, Resolution-No Activity
