### ISSUE TITLE
PSNativePSPathResolution breaks passing strings starting with ":" to native tools

### ISSUE THREAD

**Issue by DHowett** [PowerShell/PowerShell#13638] opened 2020-09-15 21:56 UTC
## Steps to reproduce

```powershell
PS> cmd /c echo ":(top,exclude).*"
```

## Expected behavior

```none
:(top,exclude).*
```

## Actual behavior

```none
C:\Users\duhowett\src\openconsole-inbox\:(top,exclude).*
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.7
PSEdition                      Core
GitCommitId                    7.1.0-preview.7
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

It appears as though the check here

https://github.com/PowerShell/PowerShell/blob/3effa204103460c996a8612aa70718fdf924047d/src/System.Management.Automation/engine/NativeCommandParameterBinder.cs#L388-L406

is not strict enough.

I encountered this by trying to use a `git` globbing expression, which can begin with `:` to introduce a set of flags.

```powershell
PS> & git log ":(top,exclude).git/" ":(top,exclude)**/*.rec"
fatal: invalid object name 'C'.
```

**Comment by DHowett** [comment] 2020-09-15 21:57
(This broke an existing script that we were using to generate git logs.)

**Comment by DHowett** [comment] 2020-09-15 21:57
(We cannot figure out how to get `:x` to behave normally.)

**Comment by mklement0** [comment] 2020-09-15 23:06
As for a _workaround_, on _Windows_ - assuming you don't need _PowerShell_ to perform the globbing - the stop-parsing symbol will (`--%`) will do (adding the `"..."` around the arguments would yield the same):

```powershell
PS> git log --% :(top,exclude).git/ :(top,exclude)**/*.rec
```

**Comment by mklement0** [comment] 2020-09-15 23:29
As for the root cause: please see #13640 - I suggest you close this issue in favor of the latter.

Another workaround _on Windows_ is to use `'...'` rather than `"..."` quoting, though the fact that this works is arguably a separate bug:

```
PS> git log ':(top,exclude).git/' ':(top,exclude)**/*.rec'
```

**Closed** 2020-09-16 02:07 UTC
Labels: Issue-Question
