### ISSUE TITLE
Wrong file permissions of release binary tarballs

### ISSUE THREAD

**Issue by Suyun114** [PowerShell/PowerShell#24050] opened 2024-07-14 07:58 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I downloaded 7.4.3 binary [tarball](https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/powershell-7.4.3-linux-x64.tar.gz) of Linux x64. I found the executable file `pwsh` and DLLs is not executable in file permissions. But the permissions of 7.4.2's [tarball](https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell-7.4.2-linux-x64.tar.gz) is correct.

### Expected behavior

```console
$ ls -l pwsh
-rwxr-xr-x 1 user users 72520 Apr 10 06:45 pwsh
```

### Actual behavior

```console
$ ls -l pwsh
-rwx---r-- 1 user users 72520 Apr 10 06:45 pwsh
```

### Environment data

```powershell
It is a problem of release tarballs.
```

**Comment by 237dmitry** [comment] 2024-07-14 08:25
This is not an new issue. I am always do this after unpacking:

```
chmod -x *.dll
chmod +x pwsh
setcap cap_net_raw=eip pwsh
```

**Comment by mklement0** [comment] 2024-07-16 00:53
Duplicate of:

* #23968

**Closed** 2024-07-16 03:03 UTC
Labels: Needs-Triage
