### ISSUE TITLE
Add-Type replaces init accessor with set accessor

### ISSUE THREAD

**Issue by pgarm** [PowerShell/PowerShell#20684] opened 2023-11-14 16:43 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using Add-Type to add custom class to session seems to ignore the accessors defined for properties, e.g.
``` powershell
Add-Type @'
public class timestamp {
    public System.DateTime time_generated { get; init;}

    public timestamp()
    {
        time_generated = System.DateTime.Now;
    }
}
'@
```
doesn't properly restrict setting property value after object instantiation - replacing the init; accessor with set;

### Expected behavior

```console
❯  $t = [timestamp]::new()
❯  $t | Get-Member
   TypeName: timestamp

Name           MemberType Definition
----           ---------- ----------
Equals         Method     bool Equals(System.Object obj)
GetHashCode    Method     int GetHashCode()
GetType        Method     type GetType()
ToString       Method     string ToString()
time_generated Property   datetime time_generated {get;init;}

❯  $t.time_generated
Tuesday, November 14, 2023 4:31:50 PM

❯  $t.time_generated = Get-Date
InvalidOperation: 'time_generated' is a ReadOnly property.
```

### Actual behavior

```console
❯  $t = [timestamp]::new()
❯  $t | Get-Member
   TypeName: timestamp

Name           MemberType Definition
----           ---------- ----------
Equals         Method     bool Equals(System.Object obj)
GetHashCode    Method     int GetHashCode()
GetType        Method     type GetType()
ToString       Method     string ToString()
time_generated Property   datetime time_generated {get;set;}

❯  $t.time_generated
Tuesday, November 14, 2023 4:31:50 PM

❯  $t.time_generated = Get-Date
❯  $t.time_generated
Tuesday, November 14, 2023 4:38:24 PM
```

### Environment data

```powershell
❯  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment] 2023-11-14 17:21
Duplicate of #13819

**Comment by SeeminglyScience** [comment] 2023-11-14 17:21
Thanks for the report! We're tracking this in the issue above.

**Comment by pgarm** [comment] 2023-11-15 10:25
Thanks @SeeminglyScience - looks like that one was closed and dropped without resolution (as it needs consensus on what way to fix it).

**Comment by SeeminglyScience** [comment] 2023-11-15 19:31
> Thanks @SeeminglyScience - looks like that one was closed and dropped without resolution (as it needs consensus on what way to fix it).

The related PR was yeah, the issue is still open though

**Closed** 2023-11-16 21:50 UTC
Labels: Issue-Bug, Resolution-Duplicate
