### ISSUE TITLE
Get-ChildItem -Depth ignores -Include and -Exclude parameters

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#5616] opened 2017-12-04 18:03 UTC
See June's comment in https://github.com/PowerShell/PowerShell-Docs/issues/889

Steps to reproduce
------------------
This example uses PowerShell v5.1
```powershell
(dir C:\Git\PowerShell\PowerShell-Docs\reference -Recurse -Depth 2).count
1930

(dir C:\Git\PowerShell\PowerShell-Docs\reference -Recurse -Include *.md -Depth 2).count
2626
```

This example uses PowerShell v6.0.0-rc
```powershell
(dir C:\Git\PowerShell\PowerShell-Docs\reference -Recurse -Depth 2).count
1930

(dir C:\Git\PowerShell\PowerShell-Docs\reference -Recurse -Include *.md -Depth 2).count
1793
```

Expected behavior
-----------------
The results should be the same for both examples in both versions.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.64
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.64
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chuanjiao10** [comment] 2017-12-08 07:19
#3762

**Comment by SteveL-MSFT** [comment] 2017-12-12 00:58
@sdwheeler the problem is that Windows 5.1 ignores the `-Depth` parameter when `-Include` or `-Exclude` is used.  This was fixed in PSCore6 via https://github.com/PowerShell/PowerShell/issues/3726 hence the different results.  The results from PSCore6 are correct and 5.1 is wrong.

**Closed by SteveL-MSFT** 2017-12-12 00:58 UTC
Labels: Area-Providers, Resolution-Answered
