### ISSUE TITLE
Release process for 6.1.0-preview.2

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#6730] opened 2018-04-25 17:15 UTC
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a private branch named `6.1.0-preview.2` in private repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [ ]  ~Verify the release Dockerfiles.~
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the `release` branch to `master` and delete the `release` branch.
- [ ]  ~Trigger the release docker builds for Linux and Windows container images.~
   - [ ]  ~Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).~
     ~Delete the `docker` branch once the builds succeed.~
   - [ ]  ~Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.~
- [ ]  ~Verify the generated docker container images.~

**Comment by daxian-dbw** [comment] 2018-04-27 00:44
Test results for Linux runs:
```
OS                          Total Pass Fail Skipped Pending
--                          ----- ---- ---- ------- -------
CentOS Linux 7 (Core)        7987 6383   22    1249     333
Debian GNU/Linux buster/sid  7987 6400    6    1249     332
openSUSE Leap 42.3           7987 6402    3    1251     331
Red Hat Enterprise Linux     7987 6383   23    1249     332
Ubuntu 14.04.5 LTS           7987 6402    4    1249     332
Ubuntu 16.04.3 LTS           7987 6402    4    1249     332
Ubuntu 17.10                 7987 6402    4    1249     332
```
The test failures are similar to previous results, except that we had one failure that I couldn't reproduce when run in isolation (set-date tests). I'm still working on the PR to update the tests to be more platform aware (centos/rhat) Someday I hope to actually submit it.
 
There is a new actual test failure in tabcompletion2 - where 2 results are returned when only 1 was expected. This is not a blocker.

**Comment by daxian-dbw** [comment] 2018-04-30 17:34
The 6.1.0-preview.2 release is done. Closing this issue.

**Closed by daxian-dbw** 2018-04-30 17:34 UTC
