### ISSUE TITLE
Prompt Function in $PROFILE works incorrectly

### ISSUE THREAD

**Issue by chenyj796** [PowerShell/PowerShell#7056] opened 2018-06-13 07:54 UTC
Steps to reproduce
------------------
cat $PROFILE
```powershell
Function Prompt
{
	Write-Host	
	Write-Host "$($executionContext.SessionState.Path.CurrentLocation)" -ForegroundColor Green	
	"PS> "
}
```

Expected behavior
-----------------
In WindowsPowerShell, it works fine as below:
```powershell
C:\Users\chenyj
PS>
```

Actual behavior
---------------
But in pwsh, it shows the prompt twice as below:
```powershell
/root
PS> 
/root
PS>   
```

---------------
cat /etc/redhat-release
```powershell
CentOS Linux release 7.4.1708 (Core) 
```

$PSVersionTable  
```powershell
Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      6.0.2                                                                                                                         
PSEdition                      Core                                                                                                                          
GitCommitId                    v6.0.2                                                                                                                        
OS                             Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017                                                               
Platform                       Unix                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                       
WSManStackVersion              3.0       
```

**Comment by BrucePay** [comment] 2018-06-13 14:00
@chenyj796 Please include the output of `$PSVersionTable` in the issue as per the template so we know what version/platform you are running on. I tried your example - it doesn't repro with 6.1.0-preview.2 on Windows but it does repro on (Ubuntu) Linux.

**Comment by BrucePay** [comment] 2018-06-13 23:51
@MaximoTrinidad I do get a repro on Ubuntu 16.04 with preview.2.  @chenyj796 can you please provide the platform/version info where you are seeing this problem? Thanks.

**Comment by chenyj796** [comment] 2018-06-14 01:04
My platform is:
 CentOS Linux release 7.4.1708 (Core) 
 PSVersion  6.0.2

**Comment by MaximoTrinidad** [comment] 2018-06-14 14:31
BTW! In Prompt function, in Windows is behaving the same way as in Linux. 

**Windows PowerShell**
```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17686.1003
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17686.1003
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**CenOS 7**
```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

![promptissue_2018-06-14_10-13-58](https://user-images.githubusercontent.com/19892435/41417579-c63ec0f2-6fbb-11e8-8648-3b8af5a6831e.jpg)

![promptissue2_2018-06-14_10-13-58](https://user-images.githubusercontent.com/19892435/41418391-96f51cc2-6fbd-11e8-924e-6455541d3402.jpg)

**Comment by lzybkr** [comment] 2018-06-14 17:44
Dupe of https://github.com/lzybkr/PSReadLine/issues/468, the fix is available from the PSGallery and is installed in the latest preview of 6.1.

**Comment by daxian-dbw** [comment] 2018-06-14 18:56
@chenyj796 The preview.3 release was out, and I have verified that the prompt works as expected on Linux (Ubuntu 16.04). Please install the preview.3 powershell core (`apt-get update`, then `apt-get install -y powershell-preview`), and then start it with `pwsh-preview` (yes, we renamed the symlink for preview powershell starting from this release to enable stable/preview side-by-side).

**Closed by daxian-dbw** 2018-06-14 18:56 UTC
Labels: Area-Console, Issue-Bug

**Comment by MaximoTrinidad** [comment] 2018-06-14 21:03
Ubuntu 18.04
![ubuntu1804_2018-06-14_17-01-55](https://user-images.githubusercontent.com/19892435/41438322-e6693018-6ff4-11e8-91ff-b653cf10c6f8.jpg)

**Comment by MaximoTrinidad** [comment] 2018-06-14 21:53
And WSL Ubuntu 16.04 - getting the same results.

![wsl1604_2018-06-14_17-01-55](https://user-images.githubusercontent.com/19892435/41440192-a9213352-6ffb-11e8-970e-4ca98b0f307e.jpg)

By the way!  

Adding the string "PS>" in the Prompt script. is not necessary. It will work the same.
:)
