### ISSUE TITLE
Invoke-Item 'foo bar' doesn't work

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2977] opened 2017-01-08 19:09 UTC
Steps to reproduce
------------------

```
PS /Users/vors/Downloads> mkdir foo
PS /Users/vors/Downloads> ii './foo/' # works fine: open the folder in Finder                                                                                   
PS /Users/vors/Downloads> mkdir 'foo bar'                                                                             
PS /Users/vors/Downloads> ii './foo bar/' # doesn't work, writes to stderr                                                                             
PS /Users/vors/Downloads> The file /Users/vors/bar does not exist. # this text comes from stderr and even not wrapped in the PS error
```

Expected behavior
-----------------

Folder `foo bar` is open in Finder (macOS). I didn't test in on Unix.

Actual behavior
---------------

Error `The file /Users/vors/bar does not exist.` is printed to the terminal

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                 
----                           -----                                                                                 
PSVersion                      6.0.0-alpha                                                                           
PSEdition                      Core                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                               
BuildVersion                   3.0.0.0                                                                               
GitCommitId                    v6.0.0-alpha.14                                                                       
CLRVersion                                                                                                           
WSManStackVersion              3.0                                                                                   
PSRemotingProtocolVersion      2.3                                                                                   
SerializationVersion           1.1.0.1  
```

**Comment by MaximoTrinidad** [comment] 2017-01-08 22:34
Definitely, something to look into. I Linux I found that has to be related to escape code.  As I can do a "CD 'foo bar'" and it will process the command but it breaks when doing Invoke-Item.  When you do the bash command "dir", it will show the escape code as the space "\ "  as "foo\ bar".
(See Attached image)
![invoke-item_folderissue](https://cloud.githubusercontent.com/assets/19892435/21754171/b4ccc2ee-d5c8-11e6-856b-67c66737c9bd.png)

**Comment by MaximoTrinidad** [comment] 2017-01-08 22:38
By the way, when using Get-ChildItem "foo bar" works fine.

![invoke-item_folderissue2](https://cloud.githubusercontent.com/assets/19892435/21754195/3f2c1142-d5c9-11e6-9b0a-86b9903a88d0.png)

**Comment by vors** [comment] 2017-01-09 22:24
For the `Invoke-Item` we are calling some platform specific hacks, I believe for OSX it's something like AppleScript `open` equivalent. That would explain why the problem happens: we are calling a command line that performs it's own parameter parsing.

**Comment by vors** [comment] 2017-03-10 20:55
Just hit this problem again. Very annoying.

**Comment by SteveL-MSFT** [comment] 2017-05-16 21:31
Dupe of https://github.com/PowerShell/PowerShell/issues/2900

**Closed by SteveL-MSFT** 2017-05-16 21:31 UTC
Labels: Area-Cmdlets, OS-macOS, Resolution-Duplicate
