### ISSUE TITLE
Cannot install powershell 7.2  preview 4 on Big Sur via github releases

### ISSUE THREAD

**Issue by AraHaan** [PowerShell/PowerShell#15111] opened 2021-03-28 02:23 UTC
## Steps to reproduce
- Download the mac x64 pkg installer from the github releases tab to powershell 7.2 preview 4 on a mac with Big Sur.
- go to the downloads and double click to try to install it.

## Expected behavior

To be able to install the latest preview version of powershell core.

## Actual behavior

This gets displayed instead of being able to install:
<img width="135" alt="image" src="https://user-images.githubusercontent.com/15173749/112740393-9a0fa300-8f4a-11eb-9b73-bba9df887a1b.png">

## Environment data

Unable to provide powershell environment data without being able to install powershell.

**Comment by AraHaan** [comment] 2021-03-28 05:39
The issue seems to be that the tag releases do not get signed like the .NET Core installers do.

**Comment by vexx32** [comment] 2021-03-28 13:22
Unless it changed significantly for Big Sur, on Mac you should be able to open it from the right-click context menu instead, which forces MacOS to actually let you pick whether you want to install it or not, instead of just refusing to let you do anything.

But yeah, GH pkg releases should probably be signed if there's any way to make that happen.

**Comment by sdwheeler** [comment] 2021-11-18 18:31
This is a duplicate of https://github.com/PowerShell/PowerShell/issues/10874

**Closed** 2021-11-19 05:40 UTC
Labels: Resolution-Duplicate, Area-Maintainers-Build
