### ISSUE TITLE
Using custom attributes in PowerShell Class results in parsing error.

### ISSUE THREAD

**Issue by LiamFisher92** [PowerShell/PowerShell#2642] opened 2016-11-08 09:41 UTC
Using a custom attribute in a PowerShell class causes PowerShell to error with message "An error occurred while creating the pipeline"

Steps to reproduce
------------------

> class CustomAttribute1 : System.Attribute
> {
> }
> 
> class CustomObject1
> {
>     [CustomAttribute1()]
>     $Var1
> }
> 

Expected behavior
-----------------
Creates class with attributed member

Actual behavior
---------------
PowerShell throws "An error occurred while creating the pipeline"

Environment data
----------------
PSVersion                      5.0.10240.16384                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                                       
BuildVersion                   10.0.10240.16384                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                               
PSRemotingProtocolVersion      2.3

**Comment by TheFish92** [comment] 2016-11-09 12:55
This appears to go deeper than custom Attributes. Custom classes defined in in dll files also do not work! Trying my best to come up with a solution.

**Comment by iSazonov** [comment] 2017-02-18 18:29
I tested the sample in Powershell Core (alpha 15) - it work without a parser error.

**Comment by lzybkr** [comment] 2017-02-18 18:43
It's a runtime error because we can't resolve the type and don't yet support defining an attribute in PowerShell.

There is no reason this couldn't work though - and that is the basic syntax you'd use (though we'd require an `AttributeUsage` attribute on the attribute class definition.

**Comment by iSazonov** [comment] 2017-02-18 18:56
@lzybkr Please clarify what `DefineCustomAttributes` do in [PSTypes.cs](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/System.Management.Automation/engine/parser/PSType.cs#L170)?

**Comment by lzybkr** [comment] 2017-02-18 20:59
It constructs the metadata when an attribute is applied to something.

A blob of metadata has a reference to the constructor (and implicitly the attribute type) and the positional and named arguments for the specific application of the attribute.

**Comment by iSazonov** [comment] 2017-02-19 11:22
@lzybkr Thanks! 
I don't see the parser error in PS 5.1 and PS Core alfa.15
I didn't realize that we need to fix 😕 
```powershell
class TestAttribute : System.Attribute {
    [string]$var1 = "q1"
    TestAttribute ([string] $t) {
        write-host "qwerty"
        $this.var1 = $t
}
 }

[TestAttribute("q2")]
   class TestClass {
   [int] [TestAttribute("q3")] $i = 5
}


$a = New-Object TestClass

PS C:\Program Files\PowerShell\6.0.0.15> $a.Gettype().GetCustomAttributes($false)
qwerty

var1 TypeId
---- ------
q2   TestAttribute


PS C:\Program Files\PowerShell\6.0.0.15> $a.gettype().Getproperties()


MemberType       : Property
PropertyType     : System.Int32
Attributes       : None
CanRead          : True
CanWrite         : True
GetMethod        : Int32 get_i()
SetMethod        : Void set_i(Int32)
IsSpecialName    : False
Name             : i
DeclaringType    : TestClass
ReflectedType    : TestClass
CustomAttributes : {[TestAttribute("q3")]}
MetadataToken    : 385875969
Module           : RefEmit_InMemoryManifestModule


PS C:\Program Files\PowerShell\6.0.0.15> $a.gettype().Getproperty("i").GetCustomAttributes($true)
qwerty

var1 TypeId
---- ------
q3   TestAttribute
``

**Comment by lzybkr** [comment] 2017-02-19 16:46
@iSazonov - I think you're getting lucky - maybe tried this in the ISE, and the attribute was defined before you ran the full script using the attribute.

I get an error with your example when run in fresh console.

**Comment by iSazonov** [comment] 2017-02-19 17:34
Reboot my notebook. (Win 10 build 14936)
Run C:\Program Files\PowerShell\6.0.0.15\powershell.exe
Run the test (copy by right click).
No errors 😕 

I don't install any development tools, SDK... on my notebook.
Powershell is installed from package downloaded from the repo.

**Comment by lzybkr** [comment] 2017-02-19 23:19
Ah - right click - that's your problem.  Put the repro in a file and run that.

With right click - the attribution definition was seen as one complete statement and run before parsing the next class.

If you pasted (Ctrl+v in Windows PowerShell), then the entire buffer would have been parsed like a single file and I think you'd have seen the problem.

**Comment by iSazonov** [comment] 2017-02-20 03:38
@lzybkr I thought that it is discovered something new.
But this is not a new problem, the direct duplication old #1762 by @SteveL-MSFT .

I see Issues with the loading of modules. Maybe they have the same root and we should gather all of them under one Issue:
New-Object doesn't work with classes in nested modules  #2963 
Using module behavior on nested modules is inconsistent  #2964
???

**Comment by lzybkr** [comment] 2017-02-20 19:39
Agreed - this is a dupe of #1762.

The other issues you referenced may feel similar, but I don't believe they have the same root cause.

**Closed by lzybkr** 2017-02-20 19:39 UTC
Labels: Area-Language, Issue-Bug, Up-for-Grabs

**Comment by iSazonov** [comment] 2017-02-21 03:28
@lzybkr Thanks! Clear.
