### ISSUE TITLE
Windows MSI installer does not remember the previous installation settings

### ISSUE THREAD

**Issue by reduckted** [PowerShell/PowerShell#17222] opened 2022-04-28 23:53 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Download the MSI for v7.2.2 and run it.
   a. Use a custom directory (in my case I choose `D:\PowerShell`)
   b. Untick the options to update automatically through Windows Update or WSUS.
2. Now download the MSI for v7.2.3 and run it.
3. When you reach the page for the installation directory, it shows the default directory in `C:\Program Files`.
4. When you reach the page for automatic updates, both options are ticked.

### Expected behavior

The installer for a new version should respect the options that were selected for the previous verison.

### Actual behavior

The installer for a new version uses the default options.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Related Issues

This could be related to #17211, which is about the original installation directory not being respected when PowerShell is automatically updated through Windows Update.

**Comment by Hrxn** [comment] 2022-05-01 16:28
Can confirm..

I'd also like to add that this is not some kind of regression, I've observed this behaviour in the MSI installer packages at least since PowerShell Core version 6.something

But the thing is, remembering the previously used installer settings would mandate to store that information somewhere in the local system, like the registry or something else..

The upside is that the installer can be considered clean in the way it behaves right now.. 😄 

Also, just out of curiosity, what is the convention or the consensus on installing PowerShell in a custom location like that?
I mean, I'm doing it as well, and I've never encountered any issue related to filesystem locations, but is there some kind of "official" guideline that would serve as a recommendation?

**Comment by adityapatwardhan** [comment] 2022-06-07 20:13
We understand that is a bug in the Wix manifest and need to be looked at. It is not high priority for us right now and hence added the Up-for-Grabs label.

**Comment by adityapatwardhan** [comment] 2022-06-07 20:25
Marking this as a duplicate of https://github.com/PowerShell/PowerShell/issues/17222

**Closed** 2022-06-08 23:00 UTC
Labels: Resolution-Duplicate, Up-for-Grabs
