### ISSUE TITLE
Add ConvertTo/From Base64

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#11414] opened 2019-12-20 21:25 UTC
# Summary of the new feature/enhancement

I think powershell needs some analogy of base64 utility 

# Proposed technical implementation details (optional)
"YmxhaGJsYWgNCg==" | ConvertFrom-Base64  | ConvertTo-Base64

**Comment by alexandair** [comment] 2019-12-20 21:33
@SteveL-MSFT is already working on it.

**Comment by SteveL-MSFT** [comment] 2019-12-20 22:27
Dupe of https://github.com/PowerShell/PowerShell/issues/8620

**Closed by SteveL-MSFT** 2019-12-20 22:27 UTC
Labels: Issue-Enhancement
