### ISSUE TITLE
dotnet fires a resolve event for "System.Core.dll", when it should not

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#751] opened 2016-03-29 22:33 UTC
The "deprecated" PsSnapIn system believes that `System.Management.Automation.dll` depends on `System.Core.dll`, which is false when building for .NET Core. Unfortunately, PowerShell (through the `InitialSessionState` constructor `CreateDefault2()`) still uses the PsSnapIn system to load the SMA assembly, and so throws an internal exception when it can't find `System.Core.dll`.

The PsSnapIn system really needs to be fully removed.

**Comment by andschwa** [comment] 2016-09-16 19:29
Confirmed, this still repros with v6.0.0-alpha.10-8-gdd2394b1e608.

**Comment by iSazonov** [comment] 2018-01-18 12:52
I can not repo - I think after we migrated to .Net Core 2.0 it's gone and we can close the Issue.

/cc @SteveL-MSFT @daxian-dbw

**Comment by daxian-dbw** [comment] 2018-01-18 23:31
I cannot reproduce the issue either. We have stopped using a custom implementation of `AssemblyLoadContext` in powershell. Instead, we solely depend on the default loader (`AssemblyLoadContext.Default`) for loading assemblies. I think we can close this issue now.

**Closed by daxian-dbw** 2018-01-18 23:31 UTC
Labels: Area-Build, Area-Engine, Issue-Bug, Up-for-Grabs
