### ISSUE TITLE
Add-Member affects constants

### ISSUE THREAD

**Issue by renatfx** [PowerShell/PowerShell#11167] opened 2019-11-22 21:15 UTC
# Steps to reproduce

```powershell
PS > $true | Add-Member -MemberType ScriptMethod -Name ToString -Value {'False'} -Force
PS > $true
False
PS > 1 | Add-Member -MemberType ScriptMethod -Name ToString -Value {'0'} -Force
PS > 1
0
PS >  New-Variable -Name test -Value (1MB) -Option Constant
PS > $test | Add-Member -MemberType ScriptMethod -Name ToString -Value {$true} -Force
PS > $test
False
```

# Expected behavior

```none
Any constant modifications must be forbidden for all cmdlets, functions, .NET types
and operators. The Add-Member cmdlet should not be an exception of this rule.
```

# Actual behavior

```none
It is possible to extend/modify ETS of constants, including standard constants like 0, 1,
$true, $false. Probably this won't lead to any serious consequences (while experimenting
I was only able to overwrite constant's formatting methods), but the behavior is not obvious
(especially knowing that *-*Item cmdlets are disallowed to modify constants in any way).
```

# Environment data

```none
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2020-01-31 11:39
In a PR we discussed this and agreed that we don't want block ETS for value types.
@JamesWTruher @daxian-dbw @SteveL-MSFT  I think we can close this as "by design".

**Comment by daxian-dbw** [comment] 2020-01-31 17:32
I think this is by design.
Here, `constant` means the variable is constant, so the variable cannot be re-assigned or removed.
But the value pointed by the variable is not constant and you can do anything you want to the object/value pointed by the variable.

**Comment by renatfx** [comment] 2020-01-31 17:50
But strings behave differently!

If you need to add a member to a `[string]` you should specify the `-PassThru` switch in a call  to the `Add-Member` cmdlet and it will produce another object, looking similar to the original `string`, but different. Due to nature of strings, being immutable by design, for consumers they are also constants. 

I could understand the design, if _any constant_ could be extended with extra members only by producing another object, meaning `-PassThru` switch is required. But with what we have today, the _design_ istelf is unobvious (non-intuitive).

**Comment by iSazonov** [comment] 2020-01-31 18:08
@renatfx PowerShell caches boxed values like $true, $false, 0 .. 100 to reduce allocations. This can cause a side effects.

**Comment by renatfx** [comment] 2020-01-31 18:15
@iSazonov I know this, but I'm just dreaming about strict design - if you are using numbers or other primitive types specifying value directly (e.g. literal in cmdlet args), then its vaue is read from cache (or even probably as real type bypassing `[psobject]`). But if you extend the type, another object is created (with `-PassThru` = value is copied from the cache and then extened) and you can use it as you wish w/o affecting "global constants" - it would correspond to how strings are working today (as far as I understand that).

**Comment by vexx32** [comment] 2020-01-31 18:29
I don't see why we _couldn't_ handle primitives the same way we handle string values purely for Add-Member purposes -- I'm pretty sure we could.

I think the question is just... should we? I'm in favor of it personally, if only for consistency's sake... but I'm not sure how others feel on the issue.

**Comment by iSazonov** [comment] 2020-01-31 18:30
>  I'm just dreaming about strict design

Currently there is a trend towards C# and make PowerShell more strict but PowerShell has very long history, many things was designed for better UX in specific scenarios that can be changed with time. Perhaps we will see business scenarios where we have to address this inconsistency.

**Comment by daxian-dbw** [comment] 2020-01-31 18:53
@renatfx You question is more about "_should `Add-Member` update the passed-in objects for immutable values_", not about the const variables.
I recommend you to open an new issue for that topic and close this one, as it's confusing for people who are new to this issue to find out what is actually being discussed.
BTW, the behavior of `Add-Member` on string is indeed inconsistent, though I'm not sure whether it's worth to change it.

**Comment by renatfx** [comment] 2020-01-31 19:49
@daxian-dbw agree, behavior is inconsistent (in general, IMHO).

I actualy filed 2 more related issues: #11171 (answered) & #11169 

If the PS team thinks these are not bugs, then all 3 could be closed.

**Closed** 2020-01-31 19:50 UTC
Labels: Resolution-By Design
