### ISSUE TITLE
Output format misalignment

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#6766] opened 2018-04-28 01:13 UTC
There is  misalignment in pwsh-bash cloudshell. The version used is v6.1.0-preview.2.

![image](https://user-images.githubusercontent.com/10171679/39390019-8ed108ac-4a43-11e8-84fa-2ab891aa0f76.png)

I did initial investigation, it 's likely the issue got introduced by the PR:
https://github.com/PowerShell/PowerShell/pull/6504 

From my vscode, you can see col =0, and lastColWithContent[row]) = 0, so Line 357 gets executed. As a result, "+    " gets TrimEnd().

![image](https://user-images.githubusercontent.com/10171679/39390124-253893c2-4a45-11e8-9520-cc8d830bf969.png)

Line 303 did not get called.

![image](https://user-images.githubusercontent.com/10171679/39390163-b0ef474e-4a45-11e8-9e2b-d165a43ee3c4.png)

Steps to reproduce
------------------
So far I only see the issue on cloudshell. I am not sure other simple way to repro it. 

0. pwsh  preview-2
1. Install-module azurerm.netcore
1. install-module ships
2. install-module Azurepsdrive
3. ipmo ships
4. AzureRM.Profile.NetCore\Login-AzureRMAccount
5. ipmo AzurePSDrive
6. New-psdrive -name Azure -psprovider SHiPS -root 'Azurepsdrive#Azure'

cd to Azure: and dir
PS Azure:\AutomationTeam> dir

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable
v6.1.0-preview.2

```

**Comment by SteveL-MSFT** [comment] 2018-04-29 01:05
Dupe of https://github.com/PowerShell/PowerShell/issues/6767

**Closed** 2018-04-30 17:51 UTC
Labels: Area-Engine, Issue-Bug, Resolution-Duplicate
