### ISSUE TITLE
Get-Content adds several NoteProperties, including PSDrive and PSProvider or extra metadata by default.  Get-Content should not add the several NoteProperties or extra metadata.

### ISSUE THREAD

**Issue by ikanni** [PowerShell/PowerShell#6458] opened 2018-03-21 23:28 UTC
Steps to reproduce
------------------

```
echo "testline1" > test.txt
echo "testline2" >> test.txt

$textContent = Get-Content .\test.txt
$json=ConvertTo-Json -InputObject $textContent -Depth 10 

```

Expected behavior
-----------------

```
Get-Content should not add the several NoteProperties or extra metadata.

```

Actual behavior
---------------

```
Review the $json  and you will notice Get-Content adds several NoteProperties, including PSDrive and PSProvider or extra metadata.

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.0.10586.117                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.10586.117                                                                               
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1    
```

**Comment by mklement0** [comment] 2018-03-22 01:24
@SteveL-MSFT: This is in essence a duplicate of the more general #5797.

@ikanni: As an aside: please note that the ``  ```...``` `` blocks are for _source code_ only; please do not place regular text in them.

**Comment by SteveL-MSFT** [comment] 2018-03-22 05:19
@mklement0 agree, dupe of https://github.com/PowerShell/PowerShell/issues/5797

**Closed by SteveL-MSFT** 2018-03-22 05:19 UTC
Labels: Area-Cmdlets-Utility, Breaking-Change, Review - Committee
