### ISSUE TITLE
Install Fails on Ubuntu 16.10

### ISSUE THREAD

**Issue by dougransom** [PowerShell/PowerShell#2933] opened 2016-12-27 17:55 UTC
I do realize the .deb is for 16.04.1 but I thought someone might want to know.

Steps to reproduce
------------------
ransom@claw:~/Downloads$ sudo dpkg -i powershell_6.0.0-alpha.14-1ubuntu1.16.04.1_amd64.deb 
Selecting previously unselected package powershell.
(Reading database ... 221717 files and directories currently installed.)
Preparing to unpack powershell_6.0.0-alpha.14-1ubuntu1.16.04.1_amd64.deb ...
Unpacking powershell (6.0.0-alpha.14-1ubuntu1.16.04.1) ...
dpkg: dependency problems prevent configuration of powershell:
 powershell depends on libicu55; however:
  Package libicu55 is not installed.

dpkg: error processing package powershell (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 powershell
ransom@claw:~/Downloads$ sudo apt-get  install -fReading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  powershell
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 130 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
ransom@claw:~/Downloads$ powershell
Failed to initialize CoreCLR, HRESULT: 0x80131500
ransom@claw:~/Downloads$ 

Expected behavior
-----------------

Install success

Actual behavior
---------------

Install failed to work

Environment data
----------------
ransom@claw:~/Downloads$ cat /proc/version
Linux version 4.8.0-32-generic (buildd@lcy01-34) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016

ransom@claw:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

```powershell
> $PSVersionTable

```

**Comment by vors** [comment] 2016-12-27 18:54
Duplicate of #2735

**Closed by vors** 2016-12-27 18:54 UTC
