### ISSUE TITLE
Update notification for PowerShell

### ISSUE THREAD

**Issue by Karl-WE** [PowerShell/PowerShell#13534] opened 2020-08-27 22:43 UTC
## Summary of the new feature/enhancement

Currently PowerShell does already show update notifications. Seen this on Windows Terminal, might also apply in classic Windows console (not tested)

## Proposed technical implementation details (optional)

**Option 1 (as-is)**

![image](https://user-images.githubusercontent.com/45657752/91501820-c08f3200-e8c6-11ea-95e8-ba489fffc1c4.png)

**Option 2 (might feel intrusive)**
Toast notification for updates
https://gist.github.com/dend/5ae8a70678e3a35d02ecd39c12f99110

**Option 3 (might feel most intrusive, easy UX for non devs)**
Updater 
- refer implementation of PowerToys, I find theirs pretty good. 
- Checking for updates
- update notifcation, uninstall, install and progress notification
- improvements over PowerToys: uninstall / install could be silent as it is MSI, but they do not use silent switch for MSI atm

things that should be adjustable
 - update settings (automatic, manual, defer)
 -  target version
 - minimum version
 - channel (release, preview)

switches via registry (better ADMX and Intune Policies) similar to Windows / Office implementation.

**Option 4**
when conditions are met (Windows, appropriate version), offer winget to install / upgrade
https://github.com/microsoft/winget-cli/issues/120

**Comment by chenxizhang** [comment] 2021-01-16 00:16
echo this, do we provide a simple way to upgrade powershell in powershell itself? like just run a cmdlet as "Upgrade-this" or anything

**Comment by Karl-WE** [comment] 2021-01-16 00:18
I would rely on winget to be honest. But it is sad to see that Server vNext has still no Winget support.

**Comment by MarioLiebisch** [comment] 2021-12-15 14:12
Picking this up again, rather than creating a separate suggestion/issue:

I think installations from the Microsoft Store should simply include a clickable link to directly open the store page (maybe make the "Upgrade now" clicky?).

This would already provide a more casual friendly upgrade process without introducing any additional user interface elements or maintainable components.

**Comment by kilasuit** [comment] 2023-07-17 19:04
I think this is a duplicate of other very similar issues & comments made on this & these ideally need linking together. Though this is a hard thing to get right because there is on one way that you can install/maintain that install.

Comments around how to improve the User/Dev/Admin experiences across Windows versions help but we also need bigger picture conversations even if many might have previously been covered.

Think this can be "resolution-duplicate" but feel that we should get this linked to similar discussions/issues that have been raised for this for tracking purposes.

**Closed** 2024-01-21 18:45 UTC
Labels: Issue-Enhancement, Area-Maintainers-Build, Resolution-No Activity
