### ISSUE TITLE
The new `-ProgressAction` common parameter breaks calls to advanced scripts and functions.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20657] opened 2023-11-08 15:52 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`-ProgressAction Ignore` should translate into a target scope-local `$ProgressPreference = 'Ignore'` variable, analogously to how it works with other common parameter, such as `-ErrorAction`.

```powershell
& { [CmdletBinding()]param() $ProgressPreference } -ProgressAction Ignore
```

### Expected behavior

```console
Ignore
```

### Actual behavior

The following error occurs:

```none
: Specified argument was out of the range of valid values. (Parameter 'index')
```

### Environment data

```powershell
PowerShell 7.4.1
```

**Comment by jborean93** [comment] 2024-11-12 21:08
See https://github.com/PowerShell/PowerShell/issues/21074#issuecomment-2471578887 for the reasoning behind this

**Comment by SeeminglyScience** [comment] 2024-12-20 20:54
Duplicate of #21074

**Comment by SeeminglyScience** [comment] 2024-12-20 20:54
@mklement0 FYI I know yours was first, just keeping the other since it has the additional research from Jordan.

**Closed** 2024-12-22 00:49 UTC
Labels: Issue-Bug, Resolution-Duplicate, In-PR
