### ISSUE TITLE
Unable to create New-PSSession from Mac

### ISSUE THREAD

**Issue by shubhamrajvanshi** [PowerShell/PowerShell#2163] opened 2016-09-01 23:30 UTC
Steps to reproduce
------------------
1. Install latest release from github release page for mac
2. Try to run New-PSSeesion command after entering in Powershell mode.

Expected behavior
-----------------
New session to remote machine should be created.

Actual behavior
---------------
```
New-PSSession -ComputerName 52.160.111.46                                                                                                 
New-PSSession : Unable to load DLL 'libpsrpclient': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
At line:1 char:1
+ New-PSSession -ComputerName 52.160.111.46
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PSSession], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.NewPSSessionCommand
```
Environment data
----------------
```
$PSVersionTable                                                                                                                           

Name                           Value                                                                                                                                           
----                           -----                                                                                                                                           
PSVersion                      6.0.0-alpha                                                                                                                                     
PSEdition                      Core                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                         
BuildVersion                   3.0.0.0                                                                                                                                         
GitCommitId                    v6.0.0-alpha.9                                                                                                                                  
CLRVersion                                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                             
SerializationVersion           1.1.0.1
```

**Comment by nduijvelshoff** [comment] 2016-09-06 18:31
+1

**Comment by andschwa** [comment] 2016-09-06 18:42
This is unsupported, but there is work-in-progress to support it. Please see the [PSRP provider](https://github.com/PowerShell/psl-omi-provider).

**Comment by nduijvelshoff** [comment] 2016-09-06 21:56
@andschwa any idea about an Mac solution?

**Comment by andschwa** [comment] 2016-09-06 22:45
There is no solution. It is not yet supported. Our developers are working to implement it.

**Comment by vinodc** [comment] 2016-09-11 21:15
I tried from Linux instead after installing OMI and PSRP, and ran into #942 unfortunately. Is there no solution on Linux at the current time as well?

**Comment by andschwa** [comment] 2016-09-12 18:19
@vinodc Per the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#command-availability) this is **not yet supported**.

**Comment by andschwa** [comment] 2016-09-19 22:04
Please follow the progress on the [PSRP on Linux repo](https://github.com/PowerShell/psl-omi-provider).

Closing as duplicate of #942.

**Closed by andschwa** 2016-09-19 22:04 UTC
Labels: Area-Remoting, Issue-Enhancement, OS-Linux, OS-macOS

**Comment by ElFerminador** [comment] 2016-12-08 23:50
+1. Very interested in this, since I'm switching to Mac and would need something like this for remoting into Office 365.

**Comment by edgarsj** [comment] 2016-12-12 14:16
+1

**Comment by wolske** [comment] 2016-12-16 16:30
Maybe a brief explanation of what PSRP is, for those who don't follow why "there is no solution" and "this is not supported" yet...

PowerShell for OSX/Linux needs a communication mechanism to reach remote nodes. PowerShell for Windows uses WinRM, and this is what will be listening on your servers. PowerShell for OSX/Linux only ships with support for SSH at this time, but the PSRP implementation @andschwa referred to will provide the WinRM layer for OSX/Linux. That will be a glorious day indeed.

The current workaround appears to be installing OpenSSH (very alpha, v0.0.4.0) on your Windows server, so it's able to connect to your PowerShell client over ssh -- see here: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

(Full disclosure, I have not tried this yet.)

**Comment by aghassemlouei** [comment] 2017-07-04 21:01
While the issue has been closed, there is no mention of this being addressed in the latest release notes, and there aren't any other open pull requests on the topic.. are there any updates or progress that has been made over the past few months?
