### ISSUE TITLE
ForEach-Object -Parallel | Execution hangs when method in class calls other method in class

### ISSUE THREAD

**Issue by dr-dolittle** [PowerShell/PowerShell#17806] opened 2022-07-31 15:09 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

**The following works:**

main.ps1
```
Write-Host "Script started."

[string[]]$objects = @("one", "two")

$job = $objects | ForEach-Object -Parallel {
    Write-Host "Executing [$_]."
    .\job.ps1 -SomeInput $_
} -ThrottleLimit 5 -AsJob

$job | Receive-Job -Wait

Write-Host "Script finished."
```

job.ps1
```
using module .\modules\testmodule.psm1

param (
    [string]$SomeInput
)

Write-Host "Executing job script [$SomeInput]."

[TestClass]$test = [TestClass]::new("test")
$test.TestMethod1($SomeInput)
```

testmodule.psm1
```
class TestClass {
    [string]$Test

    TestClass(
        [string]$_test
    ) {

        $this.Test = $_test
    }

    [void] TestMethod1([string]$someInput) {
        Write-Host "Method 1: [$someInput]."

        $this.TestMethod2()
    }

    [void] TestMethod2() {
        Write-Host "Method 2."
    }
}
```

Output
```
Script started.
Executing [one].
Executing [two].
Executing job script [two].
Executing job script [one].
Method 1: [one].
Method 1: [two].
Method 2.
Method 2.
Script finished.
```

-------------------------------------

**The following does not work:**
main.ps1
```
using module .\modules\testmodule.psm1

Write-Host "Script started."

[TestClass]$test = [TestClass]::new("test")
[string[]]$objects = @("one", "two")

$job = $objects | ForEach-Object -Parallel {
    Write-Host "Executing [$_]."
    .\job.ps1 -TestClass $using:test -SomeInput $_
} -ThrottleLimit 5 -AsJob

$job | Receive-Job -Wait

Write-Host "Script finished."
```

job.ps1
```
using module .\modules\testmodule.psm1

param (
    [TestClass]$TestClass,
    [string]$SomeInput
)

Write-Host "Executing job script [$SomeInput]."

$TestClass.TestMethod1($SomeInput)
```

testmodule.psm1
```
class TestClass {
    [string]$Test

    TestClass(
        [string]$_test
    ) {

        $this.Test = $_test
    }

    [void] TestMethod1([string]$someInput) {
        Write-Host "Method 1: [$someInput]."

        $this.TestMethod2()
    }

    [void] TestMethod2() {
        Write-Host "Method 2."
    }
}
```

Output
```
Script started.
Executing [one].
Executing [two].
Executing job script [one].
Executing job script [two].
Method 1: [one].
```

There is no error, the script does not terminate, it just hangs.

### Expected behavior

```console
Both approaches should work.
```

### Actual behavior

```console
When using the instance from outside `ForEach-Object -Parallel` the script does not complete and just hangs.
```

### Environment data

```powershell
Windows 11
PowerShell 7.2.5
```

**Comment by SeeminglyScience** [comment] 2022-08-01 14:58
Duplicate of #12801

**Comment by SeeminglyScience** [comment] 2022-08-01 14:59
Thanks for the report! PowerShell classes are not thread safe, this is tracked in the linked issue above.

**Closed** 2022-08-02 17:01 UTC
Labels: Issue-Bug, Resolution-Duplicate
