### ISSUE TITLE
Make default gci/gi output more like "gci | ft -autosize"

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16712] opened 2022-01-07 04:07 UTC
### Summary of the new feature / enhancement

The default format for `gci` looks terrible, it looks much better as `gci | ft -autosize`, I will post a few screenshots here.

This is `gci` on my Windows system:

![gci on Windows](https://i.imgur.com/3WgxsoE.png)

This is `gci | ft -autosize` on my Windows system:

![gci with ft -autosize on Windows](https://i.imgur.com/jsu97gM.png)

This is `gci` on my Linux system, this is especially horrible, I can't even see the file names!

![gci on Linux](https://i.imgur.com/M30Xy4X.png)

This is `gci | ft -autosize` on my Linux system, it looks pretty good, not quite as good as `ls --color=auto -lh`, but close, your color selections are also less than ideal (especially for directories.)

![gci | ft -autosize on Linux](https://i.imgur.com/ussV2Su.png)

this is the top part with directories, to show you what I mean about the colors:

![gci | ft -autosize on Linux (directories)](https://i.imgur.com/K8rIw2A.jpg)

this `ls --color=auto -lh` output on my Linux system for comparison (GNU coreutils ls of course):

![ls -lh output on Linux](https://i.imgur.com/dqnXXjf.jpg)

and here is `ls --color=auto` output:

![ls output on Linux](https://i.imgur.com/yARZqtD.png)

for a couple more comparisons, here is `lsd -lh`:

![lsd -lh on Linux](https://i.imgur.com/Lj8BsZr.png)

and here is `lsd`:

![lsd on Linux](https://i.imgur.com/cp0ZBse.png)

and here is `exa -lh`:

![exa -lh on Linux](https://i.imgur.com/07TO9Fg.png)

and here is `exa`:

![exa on Linux](https://i.imgur.com/ohKZOcq.png)

### Proposed technical implementation details (optional)

If using an autosize format for File/Dir info has negative implications like performance, it should still be possible to make a compact format with fixed widths for just about all the fields except name. Name would be the last field and can wrap. In case e.g. a username or length is too long, it could be truncated.

A lot can be said about file listing presentation, and this is not a strong point for this project.

The default format on Windows is OK. I like the autosize format better, but the default works more or less.

On Linux the default format is unusable at smaller widths because there are two extra columns for user and group with an unnecessarily huge amount of spacing. I suppose you did this to make listing closer to things like `ls -l` on Linux, but on Windows you do not show ACL/owner information in file listings, and for most of the work users do on Linux, they do not need this information either. Which is why they generally just use `ls` and not `ls -l`.

`gci -n` is closer to how `ls` works, actually closer to how `ls -1` works, but then you don't get the colors.

The permission bits are also generally not very interesting. On Windows the attributes column shows useful information like whether the filesystem object is a directory or readonly etc.. So why not have an attributes column on Linux with actually useful indicators of some sort? And hide the user/group columns?

But this is a digression.

This issue is specifically about the column spacing.

You will probably say "override the format", and I will definitely do that, even though that's not particularly pleasant to do and involves XML files etc.. But I am opening this issue about the default experience for users.

You might say "make your own function", this is also extremely unpleasant, because I cannot make a function that has all of the completion magic of `gci` without doing a lot of really horrible things. Also if I make a function that just pipes to `ft -autosize` it will destroy the objects and I would not be able to use it in pipelines.

**Comment by rkitover** [comment] 2022-01-07 06:41
Not related to this issue, but I enabled:

```powershell
enable-experimentalfeature PSAnsiRenderingFileInfo
```

in my pwsh on Windows which is version 7.2.1, and the directory color bleed is also present:

![gci directory color bleed](https://i.imgur.com/4In65fB.png)

**Comment by jhoneill** [comment] 2022-01-07 19:57
The bleed problem is something I mentioned here https://github.com/PowerShell/PowerShell/issues/16700#issuecomment-1005932973   the because the text just doesn't wrap onto a new line, - the table formatter tries to keep it in its column - the  format opens before "windows-dev-guide" and remains is in effect all the way to the end of "x11-packages"  


The rest is solved with a custom format xml file  : default listings don't need to be listings don't need to be re-arranged for all users because one person has a 40 column screen :-) 

If you're creating your own format file there are multiple things which you can do which out of the box PowerShell does not. 
Changing the format of the length and last-write columns depending on the value would be an obvious one.

**Comment by daxian-dbw** [comment] 2022-01-07 22:31
So, the default table format will remove columns from right when the terminal size is not big enough on Linux. This is pretty bad for cmdlets like `Get-ChildItem`, because the last column in the table view is the file/directory names, and cutting that column will make the formatting meaningless.

**Comment by jhoneill** [comment] 2022-01-08 11:04
I posted  a gist https://gist.github.com/jhoneill/4b74aa82cb5b4608687b24dddef293f8   With the XML  to create your own format.  

I've forced 24 hour clock to save 3 spaces for " AM" / " PM" in cultures where the default clock is 12 hours , and convert length to TB / GB / MB  / KB. (Lines 43 to 48) 

On  Windows I might dump the `mode` column and put <DIR> instead of a blank space at line 43 
On Linux the` mode` column wants to be the property `UnixMode` and you can add `User` and `Group` 

If you're using ANSI formatting you might want to replace `name`  at line 50 with `NameString`

**Comment by rkitover** [comment] 2022-01-08 15:27
@jhoneill Thank you very much for the XML file, I will definitely use this with some changes and in my guide as well.

But my point was exactly about the fact that the default format sucks and could be improved.

I have 68 columns btw not 40, which is a bit small but generally adequate.

**Comment by rkitover** [comment] 2022-01-08 15:39
On the subject of terminal widths, the standard width for a terminal is `80` columns. The Linux format does not work with this either. Here is a screenshot of `gci` on Linux at 80 columns:

![gci on Linux at 80 columns](https://i.imgur.com/bIRS0ZH.jpg)

**Comment by iSazonov** [comment] 2022-01-08 17:04
Interesting, can you try more old pwsh versions (starting with 6) and share results? I want to know if we have a regression.

**Comment by jhoneill** [comment] 2022-01-08 17:10
> @jhoneill Thank you very much for the XML file, I will definitely use this with some changes and in my guide as well.
> 
> But my point was exactly about the fact that the default format sucks and could be improved.
> 
> I have 68 columns btw not 40, which is a bit small but generally adequate.


You're welcome. The very first VDU I used was 40 columns wide so "40 + smiley" is my shorthand for unusually narrow. 

The original design of PowerShell set some formats which we're still using 15 years later.  I said in another thread that just because it's been in places for years doesn't mean it can't be improved. **I** think it's fine as it is, but I _would think that_ because I've grown used to it :-)     
What the default templates should optimize for is a valid question, but I think a typical screen is at least 120 characters wide and many are heading up towards 200 using only half or 1/3 of the screen is tough to sell.

**Comment by iSazonov** [comment] 2022-01-08 17:15
> What the default templates should optimize for is a valid question, but I think a typical screen is at least 120 characters wide and many are heading up towards 200 using only half or 1/3 of the screen is tough to sell.

Modern Microsoft design direction is that the same application should work on any device from smartphone to mainframe.

**Comment by jhoneill** [comment] 2022-01-08 17:19
> Interesting, can you try more old pwsh versions (starting with 6) and share results? I want to know if we have a regression.

Just a quick thing for linux I've still got 7.1 in wsl 
```
Label         Alignment Width
-----         --------- -----
UnixMode           Left    10
User               Left    16
Group              Left    16
LastWriteTime     Right    18
Size              Right    14
Name               Left     0
```
You need to add 1 to each of those widths, because there is a space between each column - so the 5 columns before name take 79 chars of space. 

7.2.1 on windows is 
```
 (Get-FormatData System.IO.FileInfo).FormatViewDefinition[0].control.headers

Label         Alignment Width
-----         --------- -----
Mode               Left     7
LastWriteTime     Right    26
Length            Right    14
Name               Left     0
```
So that's only 50.

**Comment by jhoneill** [comment] 2022-01-08 17:52
> > What the default templates should optimize for is a valid question, but I think a typical screen is at least 120 characters wide and many are heading up towards 200 using only half or 1/3 of the screen is tough to sell.
> 
> Modern Microsoft design direction is that the same application should work on any device from smartphone to mainframe.

And PowerShell's "Only convert objects to print-out at the last possible moment" design helps that, the application doesn't change, only the formatting instructions do :-)   
But I've built quite a lot of formatting files in my time and for some I've assumed the user has a terminal window as wide as the one I'm using - bad choice! - when you use PowerShell in a Jupyter notebook, width assumptions break.    I think assuming a width of 80 chars (or fewer) may also be a bad choice. 

I ran this to find out how wide the built in formats are 
```powerShell
Get-FormatData | % FormatViewDefinition  | where {$_.control -is [System.Management.Automation.TableControl] } | % {$n = $_.name;  $_.control.headers | measure -sum width | select @{n='name';e={$n}}, Count, sum} | sort sum 
```
There are quite a few more than 80.   Usually with a format we want to keep adding information, and make columns wider so text doesn't need to wrap (which causes problems with coloration ), while cutting off the smallest number of people  with demands for excessively wide screens. It's often a compromise.

**Comment by rkitover** [comment] 2022-01-08 20:25
Just wanted to mention that the default format on Windows is not too terrible, it also works fine at 68 columns for me.

The issue is on linux is the two extra columns.

**Comment by jhoneill** [comment] 2022-01-11 12:59
> How to replace `NameString` with `Name` but save the colorization?
> 


```
    <TableColumnItem><PropertyName>Name</PropertyName></TableColumnItem>
```
should just become 
```
    <TableColumnItem><PropertyName>NameString</PropertyName></TableColumnItem>
```

In those Table Column _Item_  blocks you  have  either  `<propertyName>   </propertyName> `   or `<scriptblock>   </scriptblock> `   and  the label, width, and alignment go in Table Column _Header_
  
There must be as many headers as items, but a header can just be "all defaults" and I didn't notice when I posted the gist that the last header - line 33 is doing that so it picks up the property name.

```
    <TableColumnHeader><Label>Length</Label><Width>7</Width><Alignment>right</Alignment></TableColumnHeader>
    <TableColumnHeader/>
```

So if you _only_ change the property name you will get "NameString" as a label at the top of the column. Changing line 33 to
```    
<TableColumnHeader><Label>Name</Label></TableColumnHeader>
```
should fix that.

**Comment by 237dmitry** [comment] 2022-01-11 13:31
> should fix that.

Thank you very much!

**Comment by dkaszews** [comment] 2022-10-17 20:51
How can I make `-AutoSize` the default? `$PSDefaultParameterValues['Format-Table:Autosize']` only works if I explicitly pipe `Get-ChildItem | Format-Table`, while I want it to work for simple `Get-ChildItem`.

**Comment by rkitover** [comment] 2022-10-17 21:21
@dkaszews I believe this is not possible without defining an XML format.

**Comment by jhoneill** [comment] 2022-10-18 08:58
@dkaszews  It's XML file only.  The first time you do a big dir -recurse you'll be glad you don't have autosize as the default. 

Autosize is masking a problem here. 
1. File name varies in length, and it appears on the right so that all the columns always start in the same place, some space is pre-allocated and filename has the rest - on windows it starts at column 50  and we assume screen width is at least 51+ (longest file name.).  In other words that anyone who selects 80 columns as a width for their terminal doesn't use 30+ characters for their file names. 
Length can cope with files heading towards exabytes in size (but the eye finds it hard to tell if a string of numbers is 8 , 9 or 10 digits so we can't gauge file size at a glance)  Last write date will handle even the longest local date formats, both are usally wasteful of space and auto size claims back 15 or 16 characters.  

For the case where narrow terminal meets wide file name we can make fields narrower or drop them altogether, or we can use autosize to get the best compromise for the each output. But that's always going to be matter of personal choices, sending people back to the XML file. (See my Gist above for a starter file).

**Comment by dkaszews** [comment] 2022-10-18 10:18
Agreed, I think a lot of complains could be resolved by providing a better API for modification. There is `Update-TypeData -DefaultDisplayPropertySet` but I could never get it to work, always errored out with `member already present` or was ignored.

We are currently moving a lot of stuff related to colors under `$PSStyle.Formatting`, I think it would be a good place to allow user to configure stuff like: default columns, format, width, extra calculated properties, etc. Surely PowerShell already has an in-memory object storing parsed format XML, so it's just a matter of making it public and cleaning it up.

**Comment by jhoneill** [comment] 2022-10-18 15:35
> > @jhoneill The first time you do a big dir -recurse you'll be glad you don't have autosize as the default.
> 
> That's what I keep hearing, but I just run it and can't see why. 


Try `dir C:\ -recurse <filename in your profile dir> | ft -auto`
and then `dir C:\ -recurse <filename in your profile dir> | ft `

Notice when the output appears.

**Comment by dkaszews** [comment] 2022-10-18 15:50
@jhoneill If this experiment was supposed to show that `-Autosize` has to wait for all data before it starts displaying any (like e.g sorting), then it completely failed. Data appears one by one without any noticeable delay, because autosize is on per-directory basis, that's why they may be misaligned which I said I'm completely fine. If you have any points, please spell them out and try them yourself to see if they are actually valid instead of telling people to "see yourself" when there is nothing to see. It may have been the case in older PS, but is definitely not now.

**Comment by jhoneill** [comment] 2022-10-19 09:56
@dkaszews  

I have just tested it to make sure I wasn't going made just demoed it with two windows in on my system 
`dir -Recurse -Force -ErrorAction 0 Photoshop.exe | ft   `

Output  the file on finding it. and is still working through the rest of my disk. 
` dir -Recurse -Force -ErrorAction 0 Photoshop.exe | ft -AutoSize `

hadn't  produced any output  when I stopped it (big disk / stupid number of files so dir -r takes forever) 


`dir -Recurse -Force -ErrorAction 0 pwsh.exe | ft -a`  

Outputs the files in one directory when it finds a file in another.  
So It output  `C:\Program Files\PowerShell\6` when it found a file in  `C:\Program Files\PowerShell\7`   ;  but doesn't  output  `C:\Program Files\PowerShell\7` until it finds one in ` C:\Users\me\AppData\Local\Microsoft\powershell`  etc. 

if I run it without the -a in a neighbouring pane that version is always one directory ahead of the one with -a until they finish. 

(BTW I don't mind your tone - I  sound like that myself sometimes - but others think we should all be super polite on these threads, so go carefully )

**Comment by dkaszews** [comment] 2022-10-19 10:12
@jhoneill I rested it on my Windows machine and it looks like you're right - output from one folder does not appear until another one is printed, so the very last result does not appear until the command is done. Easiest to see when looking for file which appears multiple times close to each other, e.g. some built artifact in Debug/Release. Which does make sense from how the command is implemented, as it needs to be sure that the table is finished. Weird I could not see it on Ubuntu, maybe some filesystem oddity, or just other latencies influencing observation.

I apologise for my tone, I am easily annoyed when people respond with "see for yourself" instead of providing explanation of the issue, especially stuff that may be harder to reproduce or observe. Mostly caused by people shutting down my ideas to remove sharp edges and/or improve diagnostics with "RTFM", or providing ugly workarounds that don't really work. I think we all sometimes lack empathy and ability to see somebody else's viewpoint, especially when vast differences in experience come to mind, and I will try to be more mindful of that myself.

**Comment by rkitover** [comment] 2022-10-19 10:29
@jhoneill @dkaszews 

Let's make a gallery module that will manage this XML file automatically on import from `$profile` and set a nice default format for filesystem ops, on both Windows and Linux/Mac.

We can also provide an API for modifying these formats in code, backed by the XML file.

I could throw a prototype together fairly quickly using @jhoneill's XML example and link it here, I recently pushed my first module so I'm familiar with the process.

We could use this to prototype eventual core functionality, and if not it would still be a useful module to have.

**Comment by jhoneill** [comment] 2022-10-19 10:54
@dkaszews  no apology needed from my side, I talk the same way to people :-) But the powers-that-be like to keep the atmosphere welcoming.   

I hadn't even allowed for ubuntu looking different, and it depends on the example used. (And how much more there is to process after the last item). 

@rkitover  I'm a bit conditioned to what Update-FormatData and XML files do so I'd be interested to see the prototype of what some extra functionality might look like.

**Comment by dkaszews** [comment] 2022-10-19 11:33
@rkitover I think something like `ConvertFrom/To-StyleXml` could work, good idea! My primary annoyance is that you need to create a copy of the default style just to modify a single thing. For example, I want to remove user and group on Unix (don't need it as a single user) and change the size to be human readable. With object notation, I can just do:

```pwsh
# Find loaded  ps1xml with `<TypeName>System.Io.FileInfo`, convert to object
$style = Get-FormatData 'FileInfo'
$style.Table.Remove('User')
$style.Table.Remove('Group')
$style.Table['Length'].ScriptBlock = Get-HumanReadableSize
# Convert back to XML and apply
Set-FormatData $object
```

**Closed** 2023-11-22 11:04 UTC
Labels: Issue-Bug, Issue-Enhancement, WG-Engine-Format, Resolution-No Activity
