### ISSUE TITLE
Unix: A script without .ps1 extension passed to the powershell binary lacks invocation information ($PSCommandPath, $MyInvocation), such as when invoked via a shebang line.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4217] opened 2017-07-11 02:18 UTC
Steps to reproduce
------------------

Create file `./t` - note the absence of extension `.ps1` - with the content below and make it executable (`chmod +x ./t`).

```powershell
#!/usr/bin/env powershell

'$PSCommandPath: ' + $PSCommandPath
'$MyInvocation.MyCommand.Path: ' + $MyInvocation.MyCommand.Path
'$MyInvocation: ' + ($MyInvocation | Out-String)
```

Both the following invocation methods, from `bash`, yield the behavior described below:

```sh
./t  # invocation via shebang line
powershell ./t   # implied -File
```

Expected behavior
-----------------

`$PSCommandPath` and `$MyInvocation.MyCommand.Path` should reflect the script's file path, and `$MyInvocation` should be populated appropriately.

Actual behavior
---------------

```none
$PSCommandPath:
$MyInvocation.MyCommand.Path:
$MyInvocation:

MyCommand             : #!/usr/bin/env powershell

                        '$PSCommandPath: ' + $PSCommandPath
                        '$MyInvocation.MyCommand.Path: ' + $MyInvocation.MyCommand.Path
                        '$MyInvocation: ' + ($MyInvocation | Out-String)

BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 0
OffsetInLine          : 0
HistoryId             : 1
ScriptName            :
Line                  :
PositionMessage       :
PSScriptRoot          :
PSCommandPath         :
InvocationName        :
PipelineLength        : 2
PipelinePosition      : 1
ExpectingInput        : False
CommandOrigin         : Runspace
DisplayScriptPosition :
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.3 on macOS 10.12.5
PowerShell Core v6.0.0-beta.3 on Ubuntu 16.04.1 LTS
```

**Comment by iSazonov** [comment] 2017-07-11 15:05
Is it work well without "env"? ( `#!/usr/bin/powershell`)

**Comment by mklement0** [comment] 2017-07-11 15:11
No, that doesn't make a difference.

Also keep in mind that using `env`  (`#!/usr/bin/env powershell`) is the only way to _portably_ (across Unix platforms) specify the shebang line.
(On macOS, the location is `/usr/local/bin/powershell`, not `/usr/bin/powershell`).

**Comment by iSazonov** [comment] 2017-07-11 15:20
What parameter do the shebang use to run powershell?  `powershell -f filename` ?

**Comment by mklement0** [comment] 2017-07-11 15:41
`#!/usr/bin/env powershell` is the full shebang line, to which the system on invocation passes the absolute script file path as an argument.

In other words: the system calls `env` with `powershell` and the script file path, effectively resulting in invocation `/path/to/powershell <script-file-path>`.

Given that we've switched to defaulting to `-File`, that is all that is needed (except that to suppress the profile loading you'd also need `-NoProfile` - see below).

Note that _portably_ (across Unix platforms) only _one_ argument is supported in the shebang line, which do to using indirect invocation via `env` is already "used up" by the `powershell` argument.

macOS supports multiple arguments, but Linux does not, so if you wanted a shebang line that is both portable _and_ uses `-NoProfile`, you're out of luck.

Of course, the larger issue is that `-NoProfile` should be the _default_ - see #3743

**Comment by iSazonov** [comment] 2017-07-11 15:57
Thanks for clarify! Have we the Issue if run  /path/to/powershell <script-file-path> from bash?

**Comment by mklement0** [comment] 2017-07-11 15:59
Yes, same issue, because these two invocation methods are effectively the same.

**Comment by iSazonov** [comment] 2017-07-11 16:04
Please add this to first post and maybe change the Issue subject. Thanks!

**Comment by mklement0** [comment] 2017-07-11 16:21
@iSazonov: Done.

**Comment by eedwards-sk** [comment] 2019-08-14 19:46
This is still affecting PowerShell 7.0.0-preview.2

**Comment by PeterHodges15** [comment] 2020-02-25 12:58
This is still affecting PowerShell 7.0.0-RC3 and applies to the Windows environment - in Visual Studio Code. 
If you have a library that uses $PSScriptRoot, and you open a ps1 and selected and run (F8) "Import-Module Library.psm1"  The $PSScriptRoot is not evaluated (in the library load).

**Comment by m5x** [comment] 2020-04-13 00:30
I can confirm this issue still exists on PowerShell 7.0.0 final (OS Linux). Is there by any chance any workaround?

**Comment by m5x** [comment] 2020-04-25 01:19
Looking at the code it seems that a simple removal of [this block of code](https://github.com/PowerShell/PowerShell/blob/16ec1cc32f9e60c9d76b074c865c32a5d2acf5a2/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1840-L1846) fixes this issue. However I haven't been able to assess so far if there would be any adverse side-effects nor why is this code block there in the first place.

From the comment it looks like the special treatment for files without .ps1 extension provided by this code block is because of the shebang line. But shebang line starts with # character which makes it a comment in PowerShell so there seems to be no need for any special treatment at all.

@SteveL-MSFT seems to be the author of that code block. Maybe he could tell the best for what scenario it is still needed?

**Comment by fekfoq259** [comment] 2020-06-23 16:49
Same issue.

`
PSVersion 7.0.2
PSEdition Core
OS Microsoft Windows 10.0.19041

MyCommand             : test.ps1
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 0
OffsetInLine          : 0
HistoryId             : 1
ScriptName            :
Line                  :
PositionMessage       :
PSScriptRoot          :
PSCommandPath         :
InvocationName        : C:\Users\uongo\Dropbox\powershell\test.ps1
PipelineLength        : 2
PipelinePosition      : 1
ExpectingInput        : False
CommandOrigin         : Runspace
DisplayScriptPosition :
`

**Comment by SteveL-MSFT** [comment] 2020-07-21 22:14
Took a look at this.  This is currently "by-design".  This [line](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1840) explicitly handles the case of a shebang script that doesn't have .ps1 extension by running the contents of the script so the file path is not preserved.  Workaround is to have .ps1 extension even if using shebang to have invocation info.

**Comment by vexx32** [comment] 2020-07-21 23:06
Is there any reason this design should be kept?

**Comment by iSazonov** [comment] 2020-07-22 06:22
Is there any reason this design should be changed? :-)

**Comment by mklement0** [comment] 2020-07-22 12:17
@iSazonov, of course there is:

A script should provide invocation information _irrespective of the specific invocation method_.

The proposed workaround is only a workaround _from within PowerShell_ and would also switch from running in a child process to running in-process; when called from outside PowerShell, you'd have to call the script _with_ the `.ps1` extension, whereas the primary advantage of a shebang-line-based script is _to _not_ require a filename extension.

@SteveL-MSFT's statement is open to interpretation, but I read it to mean: "While the current behavior is somewhat intentional, it should be changed - here's the relevant source-code location for someone who wants to work on this."
@SteveL-MSFT, can you confirm?

Either way, the current behavior is clearly a bug that should be fixed, so please reopen this issue.

**Comment by m5x** [comment] 2020-07-22 21:11
> A script should provide invocation information _irrespective of the specific invocation method_.

Exactly. To me it also seems logical to expect external scripts to have the invocation info available no matter what the file name is. And PowerShell knows from the shebang line that the file is an external script so why not treat is as such?

I have proposed such a solution in #12494 but it does not have necessary reviews to be merged nor explanations why.

**Comment by iSazonov** [comment] 2020-07-23 08:00
Will #12494  fix the issue too?

**Comment by mklement0** [comment] 2020-07-28 17:45
The stated intent of #12494 is to fix this issue.

Unfortunately, activity there has stalled after an initial flurry, as @m5x states.

Therefore:

* Please reopen this issue.

* Please finish reviewing #12494, so that it can be merged.

That is, unless there truly are objections to fixing this, which I find hard to imagine.
If so, we need an unambiguous statement to that effect.

**Comment by daxian-dbw** [comment] 2020-08-03 17:05
Reopen the issue as there is an open PR for this.

**Comment by hongwen000** [comment] 2023-01-12 05:43
Any progress?

**Comment by edwin-jones** [comment] 2023-04-27 09:38
Hi - I found this issue when I encountered this bug trying to treat some pwsh scripts like normal scripts on linux. I was very surprised core functionality is broken entirely when you remove the file extension. I think it would be a good thing to change this so you can run scripts the same way with or without the extension.

**Closed** 2023-11-23 13:37 UTC
Labels: Issue-Bug, OS-macOS, OS-Linux, WG-Engine, Up-for-Grabs, Resolution-No Activity

**Comment by juvtib** [comment] 2024-09-15 04:25
2024 here. I don't have this issue. But Steve used a relative link to the code. Here is a permanent link to the v.7.0.3 code:

https://github.com/PowerShell/PowerShell/blob/380e7db910c749c22acb890d3b0d25ec15d3098f/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1840
