### ISSUE TITLE
ConvertFrom-JSON incorrectly deserializes dates to DateTime

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#13592] opened 2020-09-07 11:12 UTC
When `ConvertFrom-JSON` guesses something in the input data can be converted to a `DateTime`, it (silently) does so.

But the conversion doesn't correctly interprets some strings.

## Steps to reproduce

I'm running this on a system that's on UTC+2 (CEST).

```
Write-Host("PowerShell version: " + $PSVersionTable.PSVersion.ToString())
$date = "2020-09-07T09:44:13.769Z"
Write-Host ("Original string: " + $date)
Write-Host("Cast to Datetime: " + [datetime] $date)
$json = ('[{"start":"' + $date + '"}]') 
Write-Host("JSON data: " + $json)
$data = $json |  ConvertFrom-Json
Write-Host($data[0].start.GetType().Name + " resulting from ConvertFrom-JSON: " + $data[0].start)
```

## Expected behavior

```
PowerShell version: 7.0.3
Original string: 2020-09-07T09:44:13.769Z
Cast to Datetime: 09/07/2020 11:44:13
JSON data: [{"start":"2020-09-07T09:44:13.769Z"}]
DateTime resulting from ConvertFrom-JSON: 09/07/2020 11:44:13
```

## Actual behavior

```
PowerShell version: 7.0.3
Original string: 2020-09-07T09:44:13.769Z
Cast to Datetime: 09/07/2020 11:44:13
JSON data: [{"start":"2020-09-07T09:44:13.769Z"}]
DateTime resulting from ConvertFrom-JSON: 09/07/2020 09:44:13
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The same issue is still present in 7.1.0-preview.6.

**Comment by sba923** [comment] 2020-09-07 14:03
FWIW, here's my current workaround:

````
$JSONdata = (Invoke-WebRequest $url).Content
# workaround for https://github.com/PowerShell/PowerShell/issues/13592
$marker = '#@#@#'
$JSONdata2 = $JSONdata -replace '("timestamp":")([^"]+)(")', ('$1' + $marker + '$2' + $marker + '$3')
$objects = ($JSONdata2 | ConvertFrom-Json).items | Foreach-Object { $_.timeEntry = [datetime] ($_.timeEntry -replace $marker, ''); $_ }
````

HTH

**Comment by kvprasoon** [comment] 2020-09-07 15:30
Confused. Are you sure on the expected behavior ? Isn't the original date string and the json converted string same ? Isn't that the expected behavior ?

**Comment by sba923** [comment] 2020-09-07 15:34
Nope, the expected behavior is that the JSON deserializer converts any string representing a date **the exact same way** `[datetime]$string` does it.

@SteveL-MSFT 

BTW, I wonder how that deserializer guesses that a certain field in the JSON is a date and has to be converted to a DateTime... (I know, I could look at the code...)

**Comment by mklement0** [comment] 2020-09-07 22:24
@sba923, `ConvertTo-Json` in v6+ creates a `[datetime]` instance with a `.Kind` value as follows:

* `Unspecified`, if there is no time-zone information in the input string.
* `Utc`, if the time-zone information is a trailing `Z`
* `Local`, if the time-zone information is given as a trailing UTC _offset_ (e.g., `+02:00`), in which the offset is properly converted to the caller-local equivalent.

Therefore, in your example a `Utc` `[datetime]` instance is constructed.

The default output formatting / `.ToString()` output for such an instance does _not_ indicate the fact that it represents a UTC point in time, which is the source of the confusion.

To express such an instance as a _local_ (`.Kind` == `Local`) `[datetime]` instance, call its `.ToLocalTime()` method:

```powershell
('"2020-09-07T09:44:13.769Z"' | ConvertFrom-Json).ToLocalTime()
```

As for what causes `ConvertFrom-JSON` in v6+ (via Json.NET) to interpret a _string_ value as a `[datetime]` instance: it is the _specific format_, that is an `"o"`-formatted (roundtrip format) string or a _prefix_ of it that at least includes everything up to the _seconds_ part (e.g., `2020-09-07T09:44:13`).

**Comment by sba923** [comment] 2020-09-08 06:59
Thanks for the clarifications.

Two comments:

1. this cannot be guessed, and definitely not from the [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-6&WT.mc_id=ps-gethelp)
2. the `.ToLocalTime()` trick doesn't work for the _typical_ use case where `ConvertFrom-JSON` is used to convert something that represents an array of objects:

````
PS❯ ('[{"start":"2020-09-07T09:44:13.769Z"}]' | ConvertFrom-Json).ToLocalTime()

InvalidOperation: Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'ToLocalTime'.
````

**Comment by mklement0** [comment] 2020-09-08 18:49
@sba923, thanks for opening the docs issue.

Note that the new `System.Text.Json` API that is being considered as the future underpinning of the `*-Json` cmdlets - see #11198 - exhibits the same behavior.

Yes, it is nontrivial to convert all deserialized-as-`[datetime]` properties to local dates, especially _in place_ - see the code in the bottom section.

It would be nice if `ConvertFrom-Json` had a parameter that requests that `[datetime]` instances of a given type should be returned.

---

```powershell
# Parse sample JSON that by default is parsed with [datetime] instances with 
# .Kind values 'Utc', 'Local', and 'Unspecified', in order.
$fromJson = @'
[
  {"start":"2020-09-07T09:44:13.769Z"}, 
  {"start":"2020-09-07T09:44:13.769+02:00"},
  {"start":"2020-09-07T09:44:13.769"}
]
'@ | ConvertFrom-Json

# Convert any [datetime] instances in the object graph that aren't already 
# local dates (whose .Kind value isn't already 'Local') to local ones.
ForEach-Object -InputObject $fromJson {
  # Helper script block that walks the object graph.
  $sb = {
    foreach ($el in $args[0]) {
      # iterate over elements (if an array)
      foreach ($prop in $el.psobject.Properties) {
        # iterate over properties
        if ($dt = $prop.Value -as [datetime]) {
          switch ($dt.Kind) {
            'Utc' { $prop.Value = $dt.ToLocalTime() }
            # Note: calling .ToLocalTime() is not an option, because it interprets
            #       an 'Unspecified' [datetime] as UTC.
            'Unspecified' { $prop.Value = [datetime]::new($dt.Ticks, 'Local') }
          }
        }
      }
    }
  }
  # Call the script block with the input object.
  & $sb $_
}

# Output the array with the transformed [datetime] instances.
$fromJson
```

**Comment by mklement0** [comment] 2020-09-08 20:35
@sba923, I've created a feature request for a `-DateKind` parameter for `ConvertFrom-Json` that would solve your problem: #13598

I think you can therefore close this issue now.

**Comment by iSazonov** [comment] 2020-09-09 05:29
> Nope, the expected behavior is that the JSON deserializer converts any string representing a date the exact same way [datetime]$string does it.

I am very amazed that you think so. NewtonSoft implementation is de-facto modern standard. New .Net implementation follow this. I believe users and developers expect that PowerShell follows the standard too and don't change the default behavior. As @mklement0 noted we could add new optional parameter to change the conversion but I'd prefer to see more feedback because I am sure it is again Formatting System task to show a data in a format user wants.

**Comment by sba923** [comment] 2020-09-09 06:27
I know there are two sides to this coin:
- what data is returned by the conversion
- how that data is formatted when displayed or otherwise converted to string

PowerShell always has had a certain way to convert strings representing date and time to DateTime.

That's why with my PowerShell user hat on, I would expect that a string representing a date/time inside a JSON would be converted to DateTime the same way that same string would be converted outside a JSON container.

Even if I'm not too familiar with the .Kind property of DateTime objects.

Now there is another way of looking at things: apparently JSON users expect date/time conversions to behave a certain way that might not be the PowerShell way.

Which way should `ConvertFrom-JSON` be attracted?

@Steve_MSFT, do you have 'a policy' on this?

**Comment by sba923** [comment] 2020-09-09 10:35
Indeed, once you know that there _is_ a `.Kind` property, you can convert to the appropriate flavor:

````
Write-Host("PowerShell version: " + $PSVersionTable.PSVersion.ToString())
$date = "2020-09-07T09:44:13.769Z"
Write-Host ("Original string: " + $date)
Write-Host("Cast to Datetime: " + [datetime] $date)
$json = ('[{"start":"' + $date + '"}]') 
Write-Host("JSON data: " + $json)
$data = ($json |  ConvertFrom-Json)
Write-Host($data[0].start.GetType().Name + " resulting from ConvertFrom-JSON: " + $data[0].start)
Write-Host($data[0].start.GetType().Name + " resulting from ConvertFrom-JSON -- '.Kind' property: " + $data[0].start.Kind)
Write-Host($data[0].start.GetType().Name + " resulting from ConvertFrom-JSON, with .ToLocalTime() applied: " + $data[0].start.ToLocalTime())

PowerShell version: 7.0.3
Original string: 2020-09-07T09:44:13.769Z
Cast to Datetime: 09/07/2020 11:44:13
JSON data: [{"start":"2020-09-07T09:44:13.769Z"}]
DateTime resulting from ConvertFrom-JSON: 09/07/2020 09:44:13
DateTime resulting from ConvertFrom-JSON -- '.Kind' property: Utc
DateTime resulting from ConvertFrom-JSON, with .ToLocalTime() applied: 09/07/2020 11:44:13
````

but if that's array data you get e.g. from some REST API, you'd have to iterate over _each and every_ `DateTime` object produced by `ConvertFrom-JSON` to apply `.ToLocalTime` to them.

Rather inconvenient if you ask me.

**Comment by mklement0** [comment] 2020-09-09 19:54
Let's take a step back:

**Use of `[datetime]`:**

* `[datetime]` has several inherent limitations:
  * It only specifies an _absolute_ point in time if its `.Kind` is `Utc`.
  * With `Local`, it isn't self-contained: that is, only in relationship to the local time zone does it imply an absolute point in time.
  * With `Unspecified`, it is an _abstract_ point in time that is interpreted _differently_ when you call `.ToLocalTime()` (assumed to be UTC) vs `.ToUniversalTime()` (assumed to be local).
  * In terms of default formatting, an `Utc` instance _lacks any indication that the timestamp is indeed expressed in UTC_.

* `[datetimeoffset]` overcomes these limitations, but for the sake of backward compatibility we're stuck with `[datetime]` in many cases.
  * `[datetimeoffset]`  doesn't even have a proper PowerShell display format at the moment (just does `Format-List`) and also lacks proper integration with respect to serialization - see #3172

In short: If backward compatibility weren't in the picture, `[datetime]` should be considered obsolete and replaced with `[datetimeoffset]`.

---

**`[datetime] <string>` vs. `ConvertFrom-Json` behavior**

* I agree that these two behaviors differ is surprising, and that implementing something PowerShell-idiomatic justifies deviation from underlying API behavior.

* However, I find the behavior of `[datetime] <string>` (`[datetime]::Parse(<string>, $null)`) in itself counterintuitive behavior in that `[datetime]::Parse('2020-01-01')`, for instance, results in a instance with `.Kind` `Unspecified` rather than `Local`.
   * More sensibly, `[datetimeoffset]::Parse('2020-01-01')` assumes that the date is in the _local_ time zone.

---

Given the need for backward compatibility, I don't think we can change the current behavior, but what #13598 proposes should give you the desired functionality (asking that timestamps be normalized to UTC, local, or unspecified `[datetime]` or to `[datetimeoffset]` instances).

**Comment by sba923** [comment] 2020-09-23 08:34
> > do you have 'a policy' on this?
> 
> The cmdlet correctly converts a datetime string to Datetime type value. If you want to get a local value you can use Datetime.ToLocalTime() method, if you want to get UTC - ToUniversalTime() method.

What's your definition of "correctly"?

The whole point seems to be that some people want the conversion to be "the same as PowerShell's `[datetime] $string`", some other people want the conversion to be "the usual way JSON is interpreted." 

And those two methods are different.

Next to that, as I mentioned earlier, the behavior of `ConvertFrom-JSON` is very _inconvenient_ in the **typical** case where the JSON contains an **array of objects**. Hence the need for the workaround I shared above.

**Comment by Szeraax** [comment] 2020-12-22 17:38
@iSazonov asked for more feedback, so I'm back to share my issue. In my experience, a datetimeOffset with offset gets its offset totally blown away. The Ticks matches up to the correct instant, but I lose all power that comes from being able to see what timezone was previously there. Makes for a sad day.  When outputting back to JSON, it uses my local offset.  Perhaps I should be opening a new issue since this isn't the same as the original that is generally solved with `.Kind`. 

    '{"date":"2020-12-19T15:34:49+01:00"}' | ConvertFrom-Json | ConvertTo-Json

**Comment by mklement0** [comment] 2020-12-22 17:45
@Szeraax, note that there's already another issue with a specific proposal:  #13598; if implemented as proposed, you'd use `ConvertFrom-Json -DateKind Offset`, which would create `[datetimeoffset]` instances that preserve the original offset information.

**Comment by Szeraax** [comment] 2020-12-22 17:46
Agreed, this would completely solve my issue.

**Comment by mklement0** [comment] 2020-12-22 20:10
Glad to hear it, @Szeraax; since thumbs-ups matter as a gauge of interest the community has in seeing a proposal implemented, I invite you to up-vote  #13598

**Comment by wilsoncg** [comment] 2021-07-21 14:43
> @sba923, `ConvertTo-Json` in v6+ creates a `[datetime]` instance with a `.Kind` value as follows:
> 
> * `Unspecified`, if there is no time-zone information in the input string.
> * `Utc`, if the time-zone information is a trailing `Z`
> * `Local`, if the time-zone information is given as a trailing UTC _offset_ (e.g., `+02:00`), in which case the offset is properly converted to the caller-local equivalent.
> 

There is a bug in this logic, for example when running in British summer time (UTC + 1), the behaviour differs from dotnet. An offset of +00:00 should be treated the same as Z, for example some WebApi's return UTC as +00:00, but now `ConvertFrom-json` incorrectly returns as local time +0.

```Powershell
PS> "{ date: '2021-06-30T00:00:00.0000000Z' }" | ConvertFrom-json
date
----
30/06/2021 00:00:00

PS> "{ date: '2021-06-30T00:00:00.0000000+00:00' }" | ConvertFrom-json
date
----
30/06/2021 01:00:00
```

Compare with dotnet/C# (which is correct)
```csharp
public class Program
{
  public static void Main()
  {
    Console.WriteLine(System.DateTime.Parse("2021-06-30T00:00:00.0000000Z"));
    Console.WriteLine(System.DateTime.Parse("2021-06-30T00:00:00.0000000+00:00"));
  }  
}

06/30/2021 00:00:00
06/30/2021 00:00:00
```

**Comment by mklement0** [comment] 2021-07-21 14:56
@wilsoncg, there's no bug, just a _display_ problem, which is what prompted creation of this issue to begin with.

The first command's output is a `[datetime]` instance with a `Utc` `.Kind` value, whereas it is `Local` for the second one.

The only problem is that the _string representation_ of the UTC date _doesn't indicate that it is UTC_ and is therefore indistinguishable from a local date.

By contrast, `System.DateTime.Parse()` returns a `Local` instance in _both_ cases.

**Comment by sba923** [comment] 2022-10-10 15:21
I've been bitten once again by this issue, albeit a slightly different way.

Consider this JSON file:

```json
{"Count":1,"Items":[{"score":"2","comment":"2","adjectives":"slow","timestamp":"2022-10-06T15:47:15.886Z"}]}
```

If I convert it using `ConvertFrom-JSON` with localtime == UTC+2 (in PowerShell 7.2.6 FWIW) I get:

```powershell
PS> (gc c:/tmp/items.json | convertfrom-json).items.timestamp

Thursday, 6 October, 2022 15:47:15
```

The output is "incorrect" if you interpret it as localtime.

Same if you're using `Out-GridView`:

![image](https://user-images.githubusercontent.com/12860484/194899812-321be905-3015-48c1-bbfe-43fbd32811d8.png)


The `.Kind` property _is_ correct:

```powershell
PS>  (gc c:/tmp/items.json | convertfrom-json).items.timestamp.Kind
Utc
```

but this doesn't affect the _displayed_ output.

Windows PowerShell 5.1 doesn't convert to `DateTime` so interpreting the displayed output is correct / unambiguous:

```powershell
PS>  (gc c:/tmp/items.json | convertfrom-json).items.timestamp
2022-10-06T15:47:15.886Z
```

@SteveL-MSFT, any idea on how this could get improved?

**Comment by SteveL-MSFT** [comment] 2022-10-11 00:01
@sba923 I think the solution to this is via https://github.com/PowerShell/PowerShell/issues/13598.  As noted, the actual object has correct content, but it's a matter of display and this is something that not everyone will agree upon.  I would suggest further discussion in the proposed new parameter.

**Comment by mklement0** [comment] 2022-10-11 04:29
@sba923, I agree with @SteveL-MSFT  that #13598 is the only non-breaking way forward.

To recap: 

 * The _display_ problem you mention - the same as [previously reported by @wilsoncg ](https://github.com/PowerShell/PowerShell/issues/13592#issuecomment-884246533) - is unfortunate, but it is built into the `[datetime]` (`System.DateTime`) type - PowerShell is only the messenger here. That is, the  _string representation_ of a UTC date (a `[datetime]` instance with `.Kind` value `Utc`) _doesn't indicate that it is UTC_ and is therefore indistinguishable from a local date.

 * That `ConvertFrom-Json` parses `"2022-10-06T15:47:15.886Z"` as a `[datetime]` instance with `.Kind` value `Utc` is justifiable and arguably better than the behavior of `[datetime]::Parse("2022-10-06T15:47:15.886Z")` (ditto with a PowerShell cast), which returns a  (properly adjusted) `Local` instance - even though that amounts to a perhaps surprising difference in behavior.

* Using `[datetimeoffset]` instead of `[datetime]` would avoid these problems, which #13598, if/when implemented, would allow you to request, via `-DateKind Offset`.
  * `-DateKind None` would give you compatibility with _Windows PowerShell_, i.e., timestamp strings would be passed through as _strings_.

* One problem with `[datetimeoffset]` use is its current, needlessly verbose multi-line display representation, which should be  replaced with a single-line representation similar to that of `[datetime]`, albeit _with UTC offset_.
  * See #18255

As for the status quo:

You can _mitigate_ the problem with how `[datetime]` instances with `.Kind` value `Utc` stringify by default, although this requires a modification you must make in every session (such as via `$PROFILE`):

```powershell
# In effect override the default formatting, via the .DateTime ETS property
Update-TypeData -Force -TypeName System.DateTime -MemberType ScriptProperty -MemberName DateTime -Value {
  if ((& { Set-StrictMode -Version 1; $this.DisplayHint }) -ieq "Date") {
    "{0}" -f $this.ToLongDateString()
  }
  elseif ((& { Set-StrictMode -Version 1; $this.DisplayHint }) -ieq "Time") {
    "{0}" -f $this.ToLongTimeString()
  }
  else {
    # Date + time representation requested; if the instance at hand is a UTC timestamp, append " (UTC)"
    # to distinguish it from a local timestamp.
    ("{0} {1}" -f $this.ToLongDateString(), $this.ToLongTimeString()) + 
      $(if ($this.Kind -eq 'Utc') { ' (UTC)' })
  }  
}

# Override the parameter-less .ToString() method.
Update-TypeData -Force -TypeName System.DateTime -MemberType ScriptMethod -MemberName ToString -Value {
  $this.psbase.ToString() + $(if ($this.Kind -eq 'Utc') { ' (UTC)' })
}
```

Example stringifications with this modification in place - note the ` (UTC)` suffix:

```powershell
PS> Get-Date -AsUtc; '---'; (Get-Date -AsUtc).ToString()

Tuesday, October 11, 2022 4:26:54 AM (UTC)
---
10/11/2022 4:26:54 AM (UTC)
```

**Comment by sba923** [comment] 2022-10-11 18:14
> @sba923 I think the solution to this is via #13598. As noted, the actual object has correct content, but it's a matter of display and this is something that not everyone will agree upon. I would suggest further discussion in the proposed new parameter.

This will affect the conversion, but not the display problem.

@mklement0's mitigation tackles the latter.

**Comment by sba923** [comment] 2022-10-11 18:17
> You can _mitigate_ the problem with how `[datetime]` instances with `.Kind` value `Utc` stringify by default, although this requires a modification you must make in every session (such as via `$PROFILE`):

Thanks for sharing this, it works like a charm and does address my latest issue:

```powershell
PS> (gc c:/tmp/items.json | convertfrom-json).items

score comment adjectives timestamp
----- ------- ---------- ---------
2     2       slow       2022-10-06 15:47:15 (UTC)
```

but (of course) not when using `Out-GridView` 😭

**Comment by sba923** [comment] 2022-10-12 12:24
> but not when using `Out-GridView` 😭

@mklement0 is there a way to have this work?

**Comment by mklement0** [comment] 2022-10-12 16:26
@sba923, there is a workaround, but it is cumbersome:

If you wrap all `[datetime]` instances inside the object graph returned from `ConvertFrom-Json` in `[psobject]`, `Out-GridView` will honor the ETS `.ToString()` override (as a curious aside: _string interpolation_ (`"..."`) _never_ honors such an override).

E.g.:

```powershell
# Honors the .ToString() override, but only due to the extra [psobject] case.
[pscustomobject] @{ foo = [psobject] [datetime]::UtcNow } | Out-GridView
```

Conceivably, you could write a wrapper (proxy) function for `Out-GridView` that recursively walks the properties of `[pscustomobject]` instances among its input and wraps those property values that are of type `[datetime]` in `[psobject]`.
Needless to say, you'll pay a performance penalty.

**Comment by sba923** [comment] 2022-11-07 09:35
Please note that whatever improvements are made to `ConvertFrom-Json` must ripple over to other cmdlets that perform the same conversions, such as `Invoke-RestMethod`.

**Comment by sba923** [comment] 2022-12-07 18:42
> The @PowerShell/wg-powershell-cmdlets discussed this and agree this is by-design and suggestions for allowing the user to change behavior should be in #13598

I'm not sure how to interpret the "by-design" part. Only that the current behavior, although unexpected (at least by some users, in some circumstances) is the result of a design choice, period... but that via that other issue we are open to suggest changes?

**Closed** 2022-12-09 09:01 UTC
Labels: Issue-Question, Resolution-By Design, WG-Cmdlets-Utility
