### ISSUE TITLE
7.2.0 breaks New-PSSession on Centos 7.9 - Unable to load shared library 'libpsrpclient'

### ISSUE THREAD

**Issue by jessecarbon** [PowerShell/PowerShell#16382] opened 2021-11-05 20:23 UTC
### Steps to reproduce

Install/upgrade Powershell on CentOS 7.9 (ours was handled by Puppet) to `7.2.0`, which was released today to the `https://packages.microsoft.com/rhel/7/prod/` yum repo:
```
Nov  5 13:55:37 Docker-1 yum[23463]: Updated: powershell-7.2.0-1.rh.x86_64
Nov  5 13:55:37 Docker-1 puppet-agent[23019]: (/Stage[main]/Profile::Base::Linux::jenkins_node/Exec[install pwsh]/returns) executed successfully (corrective)
```

Invoke `New-PSSession` to Windows DC:
```
PS> New-PSSession -ComputerName dc-01.mydomain.com -Credential $cred -Authentication Negotiate
```

### Expected behavior

Successful connection, as with `7.1.5`:
```console
PS> New-PSSession -ComputerName dc-01.mydomain.com -Credential $cred -Authentication Negotiate

 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
  1 Runspace1       WSMan     englab-dc-01.c… RemoteMachine   Opened        Microsoft.PowerShell     Available
```

### Actual behavior

Failed connection:
```console
PS> New-PSSession -ComputerName dc-01.mydomain.com -Credential $cred -Authentication Negotiate
New-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```

### Error details

Additional error from `/var/log/messages`:
```console
Nov  5 13:59:02 Docker-1 powershell[24057]: (7.2.0:D:80) [TransportError:None.Open.Error] Runspace Id: WSManAPIDataCommon.ctor Pipeline Id: WSManInitialize. WSMan reported an error with error code: -2146233052.#012 Error message: Unable to load shared library 'libpsrpclient' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibpsrpclient: cannot open shared object file: No such file or directory#012 StackTrace:    at System.Management.Automation.Remoting.Client.WSManNativeApi.WSManInitialize(Int32 flags, IntPtr& wsManAPIHandle)#012   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.WSManAPIDataCommon..ctor()
```

If I downgrade Powershell back to `7.1.5` with `yum downgrade`, it works again. Upgrade to `7.2.0`, it breaks.

### Environment data

```powershell
PS /home/jjarzynka_a> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment] 2021-11-08 22:13
The WSMan operation rely on PowerShell being able to load `libpsrpclient` and then subsequently `libmi` in the `pwsh` directory. This has gotten harder over time as `libmi.so` is reliant on OpenSSL 1.0.2 and and failures loading a dependency will cause a failure trying to load the parent library itself. On a brand new Docker image of CentOS 7 here are some of the details I can find

```
[root@7dc31d837336 /]# ldd /opt/microsoft/powershell/7/libpsrpclient.so
ldd: warning: you do not have execution permission for `/opt/microsoft/powershell/7/libpsrpclient.so'
        linux-vdso.so.1 =>  (0x00007ffc279de000)
        libmi.so => /opt/microsoft/powershell/7/libmi.so (0x00007f0cc6092000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0cc5bd9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0cc580b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0cc5607000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f0cc53f8000)
        libssl.so.1.0.0 => /opt/microsoft/powershell/7/libssl.so.1.0.0 (0x00007f0cc5186000)
        libcrypto.so.1.0.0 => /opt/microsoft/powershell/7/libcrypto.so.1.0.0 (0x00007f0cc4d23000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0cc6045000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f0cc4afa000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f0cc48ad000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f0cc45c4000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f0cc43c0000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f0cc418d000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f0cc3f77000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f0cc3d71000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f0cc3b61000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f0cc395d000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f0cc3743000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f0cc351c000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0cc32ba000)

[root@7dc31d837336 /]# ldd /opt/microsoft/powershell/7/libmi.so
ldd: warning: you do not have execution permission for `/opt/microsoft/powershell/7/libmi.so'
        linux-vdso.so.1 =>  (0x00007fff8bbdd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3ec871f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f3ec851b000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f3ec830c000)
        libssl.so.1.0.0 => /opt/microsoft/powershell/7/libssl.so.1.0.0 (0x00007f3ec809a000)
        libcrypto.so.1.0.0 => /opt/microsoft/powershell/7/libcrypto.so.1.0.0 (0x00007f3ec7c37000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3ec7869000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3ec893b000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f3ec7640000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f3ec73f3000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f3ec710a000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f3ec6f06000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f3ec6cd3000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f3ec6abd000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f3ec68b7000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f3ec66a7000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f3ec64a3000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f3ec6289000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f3ec6062000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f3ec5e00000)

[root@7dc31d837336 /]# ls -al /opt/microsoft/powershell/7/libssl.so.1.0.0
lrwxrwxrwx. 1 root root 19 Nov  8 22:07 /opt/microsoft/powershell/7/libssl.so.1.0.0 -> /lib64/libssl.so.10

[root@7dc31d837336 /]# ls -al /opt/microsoft/powershell/7/libcrypto.so.1.0.0
lrwxrwxrwx. 1 root root 22 Nov  8 22:07 /opt/microsoft/powershell/7/libcrypto.so.1.0.0 -> /lib64/libcrypto.so.10
```

In particular I can see that `libcrypto` and `libssl` are pointed to the OpenSSL 1.0.2 install of OpenSSL on the system. This is usually the cause of a failure when trying to load `libmi` but your `ldd` outputs might show another problem.

You might be interested in my [PSWSMan](https://www.powershellgallery.com/packages/PSWSMan/2.2.1) module which ships with a patched copy of `libpsrpclient` and `libmi` that fixes a few problems and also adds support for OpenSSL 1.1.x and 3.x removing the need for the older OpenSSL version altogether. This is not supported by Microsoft or the PowerShell team but in the current state of OMI I would argue neither is the one shipped by PowerShell. Ultimately it's up to you to decide what you are happy to use. You can find more details of my fork at https://github.com/jborean93/omi.

**Comment by PaulHigin** [comment] 2022-04-07 18:01
@WG-Remoting
Remoting working group confirms that WinRM/OMI remoting on non-Windows platforms is no longer supported since OMI is no longer supported (#15310).  Our hope is that support will be picked up by community members using the new custom remoting connections (#16923).

**Comment by PaulHigin** [comment] 2022-04-07 18:01
Closing and resolving as answered.

**Closed by PaulHigin** 2022-04-07 18:01 UTC
Labels: Resolution-Answered, WG-Remoting
