### ISSUE TITLE
macOS Packaging and libcurl+openssl+gssapi

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5635] opened 2017-12-06 01:36 UTC
@daxian-dbw :
> We need to figure out what to do with the powershell package about this limitation on macOS.
CoreCLR has explicitly moved away from OpenSSL on mac, see this PR: dotnet/corefx#17011.
Please open an issue to track the macOS packaging about this.

re #5629 #5590

**Comment by daxian-dbw** [comment] 2017-12-12 23:14
Duplicate of #5638

**Closed by daxian-dbw** 2017-12-12 23:14 UTC
Labels: Area-Build, Resolution-Duplicate

**Comment by markekraus** [comment] 2017-12-12 23:58
one of these was supposed to be about addressing the packaging related issues, and the other was supposed to be for the fact that this is needed at all.
