### ISSUE TITLE
Unable to install v7.0.0-preview.4 Release of PowerShell Core via msix

### ISSUE THREAD

**Issue by cq01** [PowerShell/PowerShell#10783] opened 2019-10-13 15:07 UTC
# Steps to reproduce

```none
Click PowerShell-7.0.0-preview.4-win-x64.msix.
Then click "install"
```

# Expected behavior

```none
powershell should be installed.
```

# Actual behavior

![image](https://user-images.githubusercontent.com/17787354/66717663-0c033380-ee0e-11e9-9146-92f28b4a6c0f.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by cq01** [comment] 2019-10-13 15:10
Developer mode in Settings has been opened。

**Comment by kilasuit** [comment] 2019-10-13 15:41
This feels like it's a duplicate of  #10469

**Closed** 2019-10-14 17:00 UTC
Labels: Issue-Question, Resolution-Duplicate
