### ISSUE TITLE
Get-Help does not return help about the 'PowerShell Help System' when being called parameterless in PS6-Beta1 on Windows

### ISSUE THREAD

**Issue by ChristophB125** [PowerShell/PowerShell#3781] opened 2017-05-13 22:20 UTC
In PowerShell 5.1 one can get help about the 'PowerShell Help System' in general with ``Get-Help``. However, in PowerShell 6.0Beta1 this is broken (on Windows)

Steps to reproduce
------------------
``Get-Help``

Expected behavior
-----------------
TOPIC
    Windows PowerShell Help System

SHORT DESCRIPTION
    Displays help about Windows PowerShell cmdlets and concepts.

LONG DESCRIPTION
    Windows PowerShell Help describes Windows PowerShell cmdlets,
    functions, scripts, and modules, and explains concepts, including
    the elements of the Windows PowerShell language.

    Windows PowerShell does not include help files, but you can read the
    help topics online, or use the Update-Help cmdlet to download help files
    to your computer and then use the Get-Help cmdlet to display the help
    topics at the command line.

    You can also use the Update-Help cmdlet to download updated help files
    as they are released so that your local help content is never obsolete.

    Without help files, Get-Help displays auto-generated help for cmdlets,
    functions, and scripts.

  ONLINE HELP
    You can find help for Windows PowerShell online in the TechNet Library
    beginning at http://go.microsoft.com/fwlink/?LinkID=108518.

    To open online help for any cmdlet or function, type:

        Get-Help <cmdlet-name> -Online

  UPDATE-HELP
    To download and install help files on your computer:

       1. Start Windows PowerShell with the "Run as administrator" option.
       2. Type:

          Update-Help

    After the help files are installed, you can use the Get-Help cmdlet to
    display the help topics. You can also use the Update-Help cmdlet to
    download updated help files so that your local help files are always
    up-to-date.

    For more information about the Update-Help cmdlet, type:

       Get-Help Update-Help -Online

    or go to: http://go.microsoft.com/fwlink/?LinkID=210614

  GET-HELP
    The Get-Help cmdlet displays help at the command line from content in
    help files on your computer. Without help files, Get-Help displays basic
    help about cmdlets and functions. You can also use Get-Help to display
    online help for cmdlets and functions.

    To get help for a cmdlet, type:

        Get-Help <cmdlet-name>

    To get online help, type:

        Get-Help <cmdlet-name> -Online

    The titles of conceptual topics begin with "About_".
    To get help for a concept or language element, type:

        Get-Help About_<topic-name>

    To search for a word or phrase in all help files, type:

        Get-Help <search-term>

    For more information about the Get-Help cmdlet, type:

        Get-Help Get-Help -Online

    or go to: http://go.microsoft.com/fwlink/?LinkID=113316

  EXAMPLES:
      Save-Help              : Download help files from the Internet and saves
                               them on a file share.
      Update-Help            : Downloads and installs help files from the
                               Internet or a file share.
      Get-Help Get-Process   : Displays help about the Get-Process cmdlet.
      Get-Help Get-Process -Online
                             : Opens online help for the Get-Process cmdlet.
      Help Get-Process       : Displays help about Get-Process one page at a time.
      Get-Process -?         : Displays help about the Get-Process cmdlet.
      Get-Help About_Modules : Displays help about Windows PowerShell modules.
      Get-Help remoting      : Searches the help topics for the word "remoting."

  SEE ALSO:
      about_Updatable_Help
      Get-Help
      Save-Help
      Update-Help

Actual behavior
---------------
The command ``Get-Help`` does not return help but an array with 2 objects that are not of any use/help:

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
default                           HelpFile                            SHORT DESCRIPTION
default                           HelpFile                            SHORT DESCRIPTION

``(Get-Help) | select -Property *``  returns:

Name          : default
Category      : HelpFile
Synopsis      : SHORT DESCRIPTION
Component     :
Role          :
Functionality :
Length        : 3565

Name          : default
Category      : HelpFile
Synopsis      : SHORT DESCRIPTION
Component     :
Role          :
Functionality :
Length        : 3565

Environment data
----------------
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by mklement0** [comment] 2017-05-14 15:04
There are several related problems, and I've just tried to consolidate them in #3782.

**Comment by joeyaiello** [comment] 2017-05-22 18:23
This is a duplicate of #3503. When it's fixed, this will also be fixed.

**Closed by joeyaiello** 2017-05-22 18:23 UTC
Labels: Area-HelpSystem, Issue-Enhancement, Resolution-Duplicate
