### ISSUE TITLE
New-Item -Force fails with existing folders

### ISSUE THREAD

**Issue by 89z** [PowerShell/PowerShell#14730] opened 2021-02-08 15:38 UTC
If I do this:

~~~
New-Item -Type Directory dest
New-Item -Force dest
~~~

I get this result:

~~~
New-Item: Access to the path 'C:\PowerShell-7.0.4-win-x64\dest' is denied.
~~~

I think if the user provides `-Force`, then the destination should implicitly be removed if it is a file **or empty folder**. However if people disagree, I would at least say that the error message could be better.

**Comment by jborean93** [comment] 2021-02-08 19:24
The issue here is you haven't supplied `-ItemType Directory` in your second call so PowerShell goes to create a new handle (to create the file) at that location and Windows is giving the generic access denied error for this scenario.

**Comment by 89z** [comment] 2021-02-08 19:35
@jborean93 the code was carefullly chosen, it wasnt a mistake.

In the situation above, where a user tries to create a file, where a folder already exists at the same path. The situation may be unlikely, but in that case, I think either the path should be killed (as happens with existing files), or a better error message should be given (output path is a an existing directory).

To further elaborate, I would especially expect the given example to work, as the conflicting directory is empty. If the conflict directory was non-empty, then maybe the same action could happen (recursively kill) or different action (stop with error).

**Comment by jborean93** [comment] 2021-02-08 19:43
That's perfectly fine, it would be up to the maintainers to decide the next course, just trying to indicate why the error is what it is.

**Comment by mklement0** [comment] 2021-02-08 22:05
> I would at least say that the error message could be better.

Fully agreed. 
(The underlying system message, which is passed through as is, as @jborean93 notes, is itself quite unhelpful; something like "Cannot open a directory as a file." would have provided a much better clue; a custom error message is called for either way, in this case.)

> should implicitly be removed with `Remove-Item -Recurse`

I'd say that's too risky. 

Restricting the scope of `-Force` to file-system items _of the same type_ makes sense to me, especially given that you could end up wiping out an entire directory tree by accident, because you thought you were replacing a _file_.

(As an aside: We already have item-type-specific behavior, albeit in the form of an unfortunate discrepancy: `-Force` with a _directory_ simply _returns_ a preexisting item as-is, whereas with a _file_ the existing file is _truncated_ first.)

Incidentally, the inverse - trying to create a _directory_ with `-Force` when an _file_ by that name already exists -  is currently a _quiet no-op_, which is undoubtedly a _bug_ - see #5290.

If there's consensus that reporting an _error_ rather than quietly wiping out an entire directory in the case at hand is the right thing to do, we can close this in favor of #5290, which covers both this and the inverse scenario and also asks for better error messages.

**Comment by 89z** [comment] 2021-02-08 22:19
@mklement0 thanks for the detailed response.

I posed this issue because I am designing some similar functions in Go, and I ran
up against some simlar issues. However in my case, the decision was on me how to
handle all these questions. In the end I decided on something like this
(pseudocode):

~~~
New-Item [-Ignore | -Force]
~~~

Where you have essentially three code paths:

~~~
New-Item
New-Item -Ignore
New-Item -Force
~~~

and the behavior as such:

1. `New-Item`: if destination exist, regardless of type, print error and stop.
2. `New-Item -Ignore`: if destination exist, regardless of type, continue with
   no error.
3. `New-Item -Force`: if destination exist as file or empty folder, remove and
   continue with no error. If destination exist as non-empty folder, print error
   and stop.

I found this to be a good compromise between handling different use cases,
without the code getting too complicated.

**Comment by 237dmitry** [comment] 2021-02-09 10:08
> New-Item -Ignore

To do this, there is `-ErrorAction` parameter and `$ErrorActionPreference` variable.

**Comment by 89z** [comment] 2021-02-09 13:45
@237dmitry yeah, I know. Everything matches pretty much except number 3.

**Comment by mklement0** [comment] 2021-02-09 20:02
Interesting, @89z; I have a few thoughts (see below), but I suggest closing this issue (which doesn't preclude further discussion that may lead to new issues ), given that the only non-breaking (and, to me, sensible) fix to the original issue is to amend the error message, as already requested in #5290.

---

I agree that more switches may be called for, but there is an additional behavior in the mix, which further complicates things:

* `-Force` currently also creates not-yet-extant _intermediate directories_ on demand, both when creating a file and a directory.

To summarize, `New-Item` currently offers the following behaviors:

* create the item only if it doesn't exist (default behavior)

  * create the parent directory (path) for the new item on demand (with `-Force`, with both files and directories)

* keep an existing item, with `-Force`:
   * keep as-is (applies only to _directories_ - all content is preserved)
   * keep, but _truncate_  (applies only to _files_) - note that the file is _not_ recreated: the creation timestamp stays the same.

This means that `New-Item` currently offers NO way to:
* keep a _file_ as-is
* truly _recreate_ a file in the face of an existing one (as opposed to _truncating_ the existing one)
* _recreate_ a _directory_ (which may be too risky with a non-empty existing one, as your proposal suggests)

So, _if_ we had the chance to start with a blank slate in PowerShell, I'd go for something like this, avoiding the ambiguous `-Force` altogether:

```
New-Item [-CreateParentOnDemand]
New-Item -KeepExisting [-CreateParentOnDemand]
New-Item -Recreate [-CreateParentOnDemand] # with -ItemType Directory only if empty
````

**Comment by 89z** [comment] 2021-02-09 20:12
@mklement0 Im not closing the issue.

I would ask that you cease commenting in this thread, and you have continued with
your long tradition of derailing threads with long winded off topic essays.

Please stop.

**Comment by mklement0** [comment] 2021-02-09 20:21
* You've reported an issue that is a duplicate of an existing issue.

* The alternative resolution you've pondered (deleting a preexisting directory tree) is not only ill-advised in principle (as your own later musings seem to concur with), but, more importantly, would constitute an unacceptable breaking change.

That is why this issue should be closed.

---

Given that there is therefore nothing (immediately) actionable in this issue, I personally didn't mind your "long-winded off-topic" essay on implementing a similar command _in another language_.

And continuing such tangents is benign in a closed issue; as I said, new issues may later emerge as the result of the discussion.

What I _do_ mind is your abrasive comments:

Stop.

**Comment by 89z** [comment] 2021-02-09 20:33
@mklement0 you dont have the power to close this issue. If you did, you would have done it already.

I dont care about your opinions on if this should be closed or not. My opinion is that its a unique issue, or different enough to deserve its own page.

So in short, go away, I dont care what you have to say about this (or frankly any) issue.

**Comment by mklement0** [comment] 2021-02-09 20:40
If the lesson you took from this exchange is that this is about _power_ and about _forcing someone to do something_, my _recommendation_ is that you not engage with _anyone_ here - it'll only make you and, perhaps more importantly, others unhappy.

**Comment by 89z** [comment] 2021-02-09 20:48
@mklement0 what I took from this engagement, is that you are **a troll**, who happens to subscribe to the PowerShell repo, so you get notified of all new issues.

You then take it upon yourself to go into each issue and give your two cents, even if you comments might not be welcome or even valid.

Perhaps you should rethink this strategy in the future. Microsoft doesnt employ you to police their threads, maybe you should stop acting like it.

**Comment by mklement0** [comment] 2021-02-10 02:32
On a one-time meta note, @89z  (and I'm happy to _hide_ - rather than _delete_ - this comment, once it has served its purpose):

First, let's focus on the positive, which you've edited out [of your previous comment](https://github.com/PowerShell/PowerShell/issues/14730#issuecomment-775501732):

> 
![image](https://user-images.githubusercontent.com/588825/107455550-09594100-6b1d-11eb-97cb-81fa99da821f.png)

You're most welcome.

---

Your subsequent comments were _deleted_, however, which is generally unfortunate (I don't know whether you've deleted them yourself).

Rather than trying to _rewrite history_, it's better to _hide_ comments that are no longer relevant, as I have done with my comments that responded to the since-deleted comment of yours.

Just so that the history isn't lost, here's a screenshot showing the since-_deleted_ comments of yours, as well as my since-_hidden_ responses to them:

![image](https://user-images.githubusercontent.com/588825/107456107-9dc3a380-6b1d-11eb-9fc4-9fdce1e2c895.png)

---

On re-reading the since-deleted comments of yours, however, let me make the following recommendation:

Instead of posting abrasive, ad-hominem comments that later warrant deletion, I suggest not posting them in the first place.

**Comment by 89z** [comment] 2021-02-10 02:48
FFS dude, **drop it**.

What is wrong with you? Do you have a complex or something. Just be quiet and get out.

**Comment by mklement0** [comment] 2021-02-10 02:51
Regrettably, the previous meta comment has not served its purpose yet, so just to keep history from getting rewritten again:

![image](https://user-images.githubusercontent.com/588825/107457882-e597fa00-6b20-11eb-9bbc-66240ff856d2.png)

**Comment by 89z** [comment] 2021-02-10 02:54
I dont know if he can see this, but I have now blocked @mklement0, so hopefully that will shut him up:

> Comment on or edit issues or pull requests that you've created

https://docs.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-personal-account

**Comment by Jaykul** [comment] 2021-02-10 03:22
Ignoring off-topic rants.

The error message is confusing, but ... the behavior is consistent.

Currently, `New-Item` does not overwrite existing items unless they are of the _same type_ that you're trying to create. That's the error you're getting: `-Force` doesn't work to overwrite a file with a folder, and vice-versa. 

However, I believe that  is _implementation specific_ (i.e. the behavior is defined by the _Provider_)...

As a side-note, don't forget that `New-Item` has a `-Value` parameter, and works on all sorts of things that are _neither directories nor files_.  I think that makes replacing `-Force` with multiple other switches a huge breaking change...

**Comment by 89z** [comment] 2021-02-10 03:27
@Jaykul thanks for comment. In my vision, the only change would be with `-Force`, being able to implicitly remove an existing file *or empty folder*. I updated the original post. Thanks again!

**Closed** 2021-11-03 02:58 UTC
Labels: WG-Cmdlets-Management, Needs-Triage
