### ISSUE TITLE
StdErr is wrapped as ErrorRecord producing undesired effects

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3813] opened 2017-05-18 19:02 UTC
Steps to reproduce
------------------

Run some executable that outputs a long line to stderr and redirect it.
For example

```
python -c "from __future__ import print_function`nimport sys`nprint(range(100), file=sys.stderr)" *> 1
```

Real-life scenario that's highly impacted by that problem is searching in the logs.
When log file can be arbitrary split on the search tokens, you cannot reliable find anything in the logs.

Expected behavior
-----------------

One line in the file `1`

Actual behavior
---------------

Several lines in the output file.
Compare it with the redirection of `stdout` which works as expected.

```
PS /Users/svorobev/junk> python -c "from __future__ import print_function`nimport sys`nprint(range(100), file=sys.stdout)" *> 1                           
PS /Users/svorobev/junk> cat 1 | measure                                                                                                                  


Count    : 1
Average  : 
Sum      : 
Maximum  : 
Minimum  : 
Property : 



PS /Users/svorobev/junk> python -c "from __future__ import print_function`nimport sys`nprint(range(100), file=sys.stderr)" *> 1                           
PS /Users/svorobev/junk> cat 1 | measure                                                                                                                  


Count    : 3
Average  : 
Sum      : 
Maximum  : 
Minimum  : 
Property : 
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                     
----                           -----                                                                                                                     
PSVersion                      6.0.0-beta                                                                                                                
PSEdition                      Core                                                                                                                      
BuildVersion                   3.0.0.0                                                                                                                   
CLRVersion                                                                                                                                               
GitCommitId                    v6.0.0-beta.1                                                                                                             
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64            
Platform                       Unix                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                   
WSManStackVersion              3.0 
```

**Comment by vors** [comment] 2017-06-03 20:16
I looked into that, the gist of the problem is the following

In [GenerateOutOfBandData](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/FormatViewManager.cs#L521) we are receiving [View](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/FormatViewManager.cs#L527) for error record, which is registered [here](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L156).
If we receive a View, it's automatically will be passed thru out format system, either as a complex object or as a list. That would force the screen width formatting on it.

There are few ways we can go about it that come to my mind:
- Put a special case hack 👎  - easy, but ugly
- Consider to take away the formatting break logic from ComplexViewEntry maybe?
- Subclass the NativeErrorRecord from ErrorRecord so we can have more granular control and put less ugly special case hack.

Looking for opinions

**Comment by SteveL-MSFT** [comment] 2017-06-03 22:11
Seems like option 3 is best.  Whenever PowerShell works with native cmds we should keep the data raw for perf and compat reasons.

**Comment by iSazonov** [comment] 2017-06-04 07:44
Can the problem be in other streams?
Can the problem will be resolved by native pipes #1908?

**Comment by iSazonov** [comment] 2017-06-05 06:01
I can't reproduce the bug with cmd.exe 😕

**Comment by vors** [comment] 2017-06-05 06:23
@iSazonov you may need to make your window smaller or output larger to observe it (essentially larger then 1 width of your window)

Here is another repro with just powershell

```
PS C:\dev\platyPS> powershell -Command '1..1000 | % { [System.Console]::Error.Write("1") }' *> 1
PS C:\dev\platyPS> cat 1 | measure


Count    : 12
Average  :
Sum      :
Maximum  :
Minimum  :
Property :


```

**Comment by iSazonov** [comment] 2017-06-05 07:55
Thanks for the repo! 

I see that the formatting work well - we hit that [line](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L771).
If we remove the view the problem persists.

**Comment by iSazonov** [comment] 2017-06-05 08:03
Bay be the same problem #1491

**Comment by vors** [comment] 2017-06-05 16:43
> I see that the formatting work well 

Let me elaborate the problem.

If `view != null` [here](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/FormatViewManager.cs#L530)

We are using ViewGenerator and it will apply logic for the window width.

What we want is something like [GenerateOutOfBandObjectAsToString(so)](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/FormatViewManager.cs#L549)

**Comment by iSazonov** [comment] 2017-06-06 15:31
Thanks for clarify!

Can we add new parameter in [the view](https://github.com/PowerShell/PowerShell/blob/ef33c30219770986cbb365e7f7ca7a082fe7f7ca/src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L720)?
```powershell
CustomControl.Create(outOfBand: true, MaxWidth: Int.MaxValue)
```

**Comment by daxian-dbw** [comment] 2017-11-28 23:34
@SteveL-MSFT Is this issue already fixed? The PR #5190 hasn't been merged, but I cannot repro with @vors's [windows repro step](https://github.com/PowerShell/PowerShell/issues/3813#issuecomment-306112883) on RC build:
```powershell
PS:1> pwsh -Command '1..1000 | % { [System.Console]::Error.Write("1") }' *> 1
PS:2> cat 1 | measure


Count    : 1
Average  :
Sum      :
Maximum  :
Minimum  :
Property :
```

**Comment by SteveL-MSFT** [comment] 2017-11-29 00:10
@daxian-dbw the original issue where line breaks were added at window width has been fixed.  stderr is still being wrapped as error record, but it gets unwrapped I believe so it's just an optimization.  I think we can close this since the original user facing issue is resolved.

**Closed by SteveL-MSFT** 2017-11-29 00:10 UTC
Labels: Area-Console, Issue-Bug

**Comment by vors** [comment] 2017-11-30 03:16
Oh nice, didn't see that being fixed 💃
