### ISSUE TITLE
Regression from 7.3.3: Verbose Invoke-WebRequest / Invoke-WebRequest output is missing the byte count

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19230] opened 2023-02-26 21:40 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
Invoke-RestMethod -Method HEAD http://example.org -Verbose
```

### Expected behavior

```console
VERBOSE: HTTP/1.1 HEAD with 0-byte payload
VERBOSE: received 648-byte response of content type text/html
```

### Actual behavior

```console
VERBOSE: HTTP/1.1 HEAD with 0-byte payload
VERBOSE: received -byte response of content type text/html
```

Note the missing number before "-byte".

### Environment data

```powershell
PowerShell Core 7.4.0-preview.1
```

**Comment by 237dmitry** [comment] 2023-02-26 22:39
It works but not every time.

![ArcoLinux_2023-02-27_01-38-55](https://user-images.githubusercontent.com/78153320/221441748-94e42440-8ae3-4271-a3c0-3a5f31deee0d.png)

**Comment by mklement0** [comment] 2023-02-26 22:49
Interesting. I can never get it to succeed in v7.4.0-preview.1. 
Either way, it's clear that there's a problem that needs to be fixed.

**Comment by CarloToso** [comment] 2023-02-27 14:23
I guess the error must originate from here, but it doesn't make any sense
WebRequestPSCmdlet.Common.cs
```cs
                            using HttpResponseMessage response = GetResponse(client, request, keepAuthorization);

                            string contentType = ContentHelper.GetContentType(response);
                            string respVerboseMsg = string.Format(
                                CultureInfo.CurrentCulture,
                                WebCmdletStrings.WebResponseVerboseMsg,
                                ***response.Content.Headers.ContentLength***,
                                contentType);

                            WriteVerbose(respVerboseMsg);
```

**Comment by iSazonov** [comment] 2023-02-27 18:37
If it is .Net API please open new issue in .Net Runtime repository.
But before I'd look in Fiddler all packets in the session.

**Comment by CarloToso** [comment] 2023-02-27 20:01
I found the origin of the problem, it's a .NET bug
Test:
```ps1
$handler = [System.Net.Http.HttpClientHandler]::New()
$handler.AutomaticDecompression = "All" #<--- BUG ORIGIN
$client = [System.Net.Http.HttpClient]::new($handler)
$message = [System.Net.Http.HttpRequestMessage]::New('HEAD', "http://example.com/")
$client.sendAsync($message).Result.Content.Headers.ContentLength #--> $null

$handler = [System.Net.Http.HttpClientHandler]::New()
$client = [System.Net.Http.HttpClient]::new($handler)
$message = [System.Net.Http.HttpRequestMessage]::New('HEAD', "http://example.com/")
$client.sendAsync($message).Result.Content.Headers.ContentLength #--> 648 or 1258
```
http://example.com/ always responds with the same Content-Length (checked with MITM-Proxy), but it's not reported with `$handler.AutomaticDecompression = "All"`

Tested in PS 5 - 7.3.3 - 7.4preview1 - latest, the bug is always there

**Comment by iSazonov** [comment] 2023-02-28 06:14
From comments in .Net, we need a workaround to write better message.

**Comment by CarloToso** [comment] 2023-02-28 12:22
Tested in PS 7.3.3, not a regression, just a bad implementation:
```ps1
iwr http://www.google.com -Verbose
#VERBOSE: HTTP/1.1 GET with 0-byte payload
#VERBOSE: received -byte response of content type text/html
```

**Comment by jborean93** [comment] 2023-02-28 19:51
> Write-Output "first: $($client.sendAsync($message).Result.Content.Headers.ContentLength)"

When calling an async call you should be doing `AsyncMethod().GetAwaiter().GetResult()`. Doing just `.Result` is problematic because

1. PowerShell won't automatically wait for it to finish
2. A property getter in PowerShell ignores an exceptions and instead returns null

**Comment by CarloToso** [comment] 2023-03-01 11:09
@mklement0 I think we should close this issue and open another one to discuss a new implemantation or workaround

**Comment by iSazonov** [comment] 2023-03-01 12:03
We have no need new issue.

Since it is .Net behaviour by-design as solution I suggest to make the message conditional.

**Comment by CarloToso** [comment] 2023-03-01 12:27
Now that we introduced handler.AutomaticDecompression = "All", we will probably never recieve a content-length header. We should just remove it and change the message to something like `#VERBOSE: received response of content type text/html`

**Comment by iSazonov** [comment] 2023-03-01 12:34
But reports above say that sometimes we get the length.

**Comment by mklement0** [comment] 2023-03-01 15:08
So it sounds like we should report it _when available_, right?

N/A (as @CarloToso  suggested):
> received response of content type text/html

Available (as before):
> received $num-byte response of content type text/html

For the N/A case, I wonder if it's worth being explicit about _not knowing_ the size; pro: people will know that the information is unavailable; con: they might be wondering why - but that could explained in the docs.

> received response of content type text/html of unknown size

**Comment by jborean93** [comment] 2023-03-01 18:39
I forgot to mention when using `GetAwaiter().GetResult()` in @CarloToso example I cannot replicate the problem. It always returns the content length so I don’t think the problem exists in dotnet.

**Comment by CarloToso** [comment] 2023-03-01 18:53
@jborean93 It was confirmed it's a dotnet dy design problem (https://github.com/dotnet/runtime/issues/82737). I replicated the problem when using `GetAwaiter().GetResult()` instead of `Result`.

**Closed** 2023-03-02 02:21 UTC
Labels: In-PR
