### ISSUE TITLE
JEA doesn't work with PowerShell from the App Store

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#14865] opened 2021-02-20 19:39 UTC
If you install PowerShell from the App Store, you can't use JEA because it can't write to the installation directory.

Here's a repro:

````
New-PSSessionConfigurationFile -Path c:\temp\restricted.pssc -VisibleCmdlets Get-Random -SessionType RestrictedRemoteServer 
Register-PSSessionConfiguration -Name Random -Path c:\temp\restricted.pssc -Force
Register-PSSessionConfiguration: Access to the path 'C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.0.0_x64__8wekyb3d8bbwe\SessionConfig' is denied
````

**Comment by SteveL-MSFT** [comment] 2021-03-03 22:20
Dupe of https://github.com/PowerShell/PowerShell/issues/9278

**Closed by SteveL-MSFT** 2021-03-03 22:20 UTC
Labels: Needs-Triage, Resolution-Duplicate, WG-Remoting
