### ISSUE TITLE
Invoke-Webrequest errors do not contain the original response

### ISSUE THREAD

**Issue by thomasbruggink** [PowerShell/PowerShell#9030] opened 2019-03-02 17:11 UTC
Currently the exception of Invoke-WebRequest does not contain the original response. A regex is used to remove the HTML tags to make it easier to read https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1525.
The only way to get the response is by using `$_.ErrorDetails.Message` which is not the original message. Using `$_.Exception.Response.Content.ReadAsStringAsync().GetAwaiter().GetResult()` returns `"The stream was already consumed. It cannot be read again."` because the stream is disposed on line 1535.

# Steps to reproduce

```powershell
try {
 # Endpoint that returns an html error
 Invoke-WebRequest "http://localhost"
}
catch {
 # Does not contain the HTML tags
 Write-Verbose $_.ErrorDetails.Message -Verbose
}
```

# Expected behavior

```none
A property or method that returns the original response
For example: $_.ErrorDetails.OriginalMessage
```

# Actual behavior

```none
The parsed and HTML tag stripped response
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.3
PSEdition                      Core
GitCommitId                    6.2.0-preview.3
OS                             Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2019-03-03 04:13
duplicate of #5555

**Closed by markekraus** 2019-03-03 04:13 UTC
Labels: Issue-Question
