### ISSUE TITLE
Unable to set custom type on system.string objects

### ISSUE THREAD

**Issue by MSAdministrator** [PowerShell/PowerShell#7459] opened 2018-08-06 14:49 UTC
Steps to reproduce
------------------
It seems that you cannot set a TypeName on `Strings` in PowerShell Core 5.1 or 6+.

```powershell
$a = 'a'
$a.PSObject.TypeNames.Insert(0,'Example.Custom.Type')
$a.PSOBject.TypeNames

System.String
System.Object
```

Expected behavior
-----------------
A `System.String` TypeName can be set.
```powershell
$a = 'a'
$a.PSObject.TypeNames.Insert(0,'Example.Custom.Type')
$a.PSOBject.TypeNames

Example.Custom.Type
System.String
System.Object
```

Actual behavior
---------------
A `System.String` TypeName cannot be set.
```powershell
$a = 'a'
$a.PSObject.TypeNames.Insert(0,'Example.Custom.Type')
$a.PSOBject.TypeNames

System.String
System.Object
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2018-08-07 00:12
ref: #7450

**Comment by BrucePay** [comment] 2018-08-07 14:12
This appears to be a duplicate of the bug @markekraus  mentioned.

**Comment by DHowett** [comment] 2018-08-08 06:56
At the bottom of that bug is a comment from @MSAdministrator wherein they say they’ll file a separate bug for strings not being able to hold custom type names. _This_ appears to be that issue.

**Comment by markekraus** [comment] 2018-08-08 12:46
@BrucePay This is the bug report. I was only referencing another issue where this was discussed for context. @MSAdministrator had originally filed an issue on something else for which this issued ended up being the root cause.

Would you be so kind as to answer if String PSObjects should allow for custom type names?

**Closed** 2023-11-23 13:24 UTC
Labels: WG-Engine, Resolution-No Activity
