### ISSUE TITLE
[Error] Invoke-RestMethod : Document Has Moved

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#4801] opened 2017-09-10 17:49 UTC
This works in PS v5.1

```
Name                           Value                                                                                                                       
----                           -----                                                                                                                       
PSVersion                      6.0.0-beta                                                                                                                  
PSEdition                      Core                                                                                                                        
GitCommitId                    v6.0.0-beta.6                                                                                                               
OS                             Microsoft Windows 10.0.15063                                                                                                
Platform                       Win32NT                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                         
SerializationVersion           1.1.0.1                        01                                                                                            
WSManStackVersion              3.0                                                                                                                         
```

```
PS C:\> Invoke-RestMethod "http://finance.yahoo.com/d/quotes.csv?s=msft&f=snd1l1yr"
Invoke-RestMethod :
Document Has Moved
Document Has Moved
Description: The document you requested has moved to a new location.  The new location is
"http://download.finance.yahoo.com/d/quotes.csv?s=msft&f=snd1l1yr".
At line:1 char:1
+ Invoke-RestMethod "http://finance.yahoo.com/d/quotes.csv?s=msft&f=snd ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by SteveL-MSFT** [comment] 2017-09-10 21:48
This seems to only repro on Windows.  Doesn't repro on Mac which uses the libcurl library.  Might be an issue with corefx if it's giving different behavior on different OS's.

**Comment by markekraus** [comment] 2017-09-10 21:57
It looks like it is because the the Redirect is from HTTPS to HTTP and that is disabled `by design` dotnet/corefx#12171

```
http://finance.yahoo.com/d/quotes.csv?s=msft&f=snd1l1yr redirects to https://finance.yahoo.com/d/quotes.csv?s=msft&f=snd1l1yr
https://finance.yahoo.com/d/quotes.csv?s=msft&f=snd1l1yr redirects to http://download.finance.yahoo.com/d/quotes.csv?s=msft&f=snd1l1yr
```

**Comment by SteveL-MSFT** [comment] 2017-09-11 00:14
Dupe of https://github.com/PowerShell/PowerShell/issues/2896

**Closed by SteveL-MSFT** 2017-09-11 00:14 UTC
Labels: Area-Cmdlets-Utility, Issue-Bug, OS-Windows, Resolution-Duplicate

**Comment by WilliamBelini** [comment] 2024-12-03 01:46
the problem persist
