### ISSUE TITLE
python function error 

### ISSUE THREAD

**Issue by yuyixuantai** [PowerShell/PowerShell#5082] opened 2017-10-11 07:07 UTC
Steps to reproduce
------------------

```powershell

```
1. cd dir:
PS C:\Program Files\PowerShell\6.0.0-beta.8> cd D:\code\py\google-python-exercises\john
2. start python in powershell
PS D:\code\py\google-python-exercises\john> python
3. use help function:
 help(dict)

Expected behavior
-----------------

```none

```
display next text:
Help on class dict in module __builtin__:
class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
In python 2.7.13, is ok:
![20171011150552](https://user-images.githubusercontent.com/13009510/31426385-b6cbcc4c-ae95-11e7-9cc0-05b702f1ffea.png)
![20171011150154](https://user-images.githubusercontent.com/13009510/31426266-2cdd5190-ae95-11e7-9a4d-b9ba0f6137c8.png)
Actual behavior
---------------

```none

```
1. if there is a file <string.pyc>, display:
hello
HELLO
Hello
1
e
o
H
o
l
el
Hello
I want code string I have 100 time

2. if there has no file named <string.pyc>:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site.py", line 445, in __call__
    import pydoc
  File "C:\Python27\lib\pydoc.py", line 58, in <module>
    from string import expandtabs, find, join, lower, split, strip, rfind, rstrip
ImportError: cannot import name expandtabs

![20171011150204](https://user-images.githubusercontent.com/13009510/31426267-2d139142-ae95-11e7-97bf-e2301ba64167.png)
Environment data
----------------
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```powershell
> $PSVersionTable

```

**Comment by markekraus** [comment] 2017-10-11 08:43
I can't reproduce this with Python 2.7.14 ( I don't have 2.7.13 handy to test with). But that output seems ti indicate to me you are not working with a clean python environment.  Also, you are running the alias `python` which could be resolving to something else.

Can you try running the python.exe from its full path name frm the ptython install folder?

```powershell
set-location c:\Python27\
C:\Python27\python.exe
```

and then run 

```python
help(dict)
```

And see if you get the same results?

![2017101101](https://user-images.githubusercontent.com/6509955/31430383-4cc4803c-ae36-11e7-85d8-94bfa051dbb8.PNG)

**Comment by MaximoTrinidad** [comment] 2017-10-11 13:53
Although, I got Windows 10 Build 15063, I just installed Python 2.7.12 selecting to install all features. 
And, was able to execute the "help(dict)" command without any issues in both DOS and PowerShell Core Beta.8 shells.

My suggestion would be to reinstall Python 2.7.12 with all features, then try again.  Remember to "unblock" the MSI file before installing.

![poshpython2 7 12_2017-10-11_9-46-15](https://user-images.githubusercontent.com/19892435/31444278-c0928936-ae69-11e7-93be-12fbaec9f046.png)

**Closed** 2017-10-11 17:34 UTC
Labels: Issue-Question, Resolution-Answered

**Comment by yuyixuantai** [comment] 2017-10-12 01:25
@markekraus @MaximoTrinidad  @SteveL-MSFT I installed Python 2.7.14 and I can reproduce it every time. and now I kown the reason and avoid it.
Steps to reproduce:
1. cd a new path:
    cd D:\code\pytest
    in "D:\code\pytest", there is only one file **string.py  (this is bug source)**
2. start python in current path:
    path
3. help(dict)
![bugwithstring](https://user-images.githubusercontent.com/13009510/31474567-3855b24e-af2e-11e7-9cc3-0b1decc81cbc.png)

4. **del string.py**, exit python then restart python, help(dict) run ok: 
![helpfuncwithnostring](https://user-images.githubusercontent.com/13009510/31474668-c0746b8e-af2e-11e7-9882-f57072682af5.png)


python import string.py in current path 1st，and import orther module in lib path next。the string.py dirty python environment.

**Comment by MaximoTrinidad** [comment] 2017-10-12 14:12
@yuyixuantai, Thanks for the update!
:)
