### ISSUE TITLE
PackageManager.FindPackages Method doesn't work

### ISSUE THREAD

**Issue by farag2** [PowerShell/PowerShell#14712] opened 2021-02-05 07:13 UTC
## Steps to reproduce

Open PowerShell 7.1.1 with admin privileges and type

```powershell
[Windows.Management.Deployment.PackageManager,Windows.Web,ContentType=WindowsRuntime]::new().FindPackages() | Select-Object -ExpandProperty Id -Property DisplayName | Format-Table -Property Name, DisplayName
```

## Expected behavior

```none
List of installed UWP apps with thier localized names
```

## Actual behavior

```none
InvalidOperation: Unable to find type [Windows.Management.Deployment.PackageManager,Windows.Web, ContentType=WindowsRuntime].
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The command above works on PowerShell 5.1 but not with 7.1.1. 
[PackageManager.FindPackages](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackages) Method

**Comment by SeeminglyScience** [comment] 2021-02-05 16:21
Duplicate of #13042

**Closed** 2021-02-05 19:02 UTC
Labels: Needs-Triage
