### ISSUE TITLE
Enter-PSSession fails from Docker image

### ISSUE THREAD

**Issue by Stlouistechy** [PowerShell/PowerShell#7342] opened 2018-07-23 20:31 UTC
Steps to reproduce
------------------
From a RHEL server running docker, pull down latest release by running:
docker run -it microsoft/powershell
From PS command prompt, connect to a Windows 2012 R2 server by running:
PS /> $creds = Get-Credential
PS /> Enter-PSSession -ComputerName {Win2012-R2 Hostname} -Authentication Basic -Credential $creds

Expected behavior
-----------------

PS connects to server

Actual behavior
---------------

Enter-PSSession : Connecting to remote server {Win2012-R2 Hostname} failed with the following error message : MI_RESULT_ACCESS_DENIED For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName {Win2012-R2 Hostname} -Authentica ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: ({Win2012-R2 Hostname}:String) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : CreateRemoteRunspaceFailed

Environment data
----------------

PS /> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.0.3
PSEdition                      Core
GitCommitId                    v6.0.3
OS                             Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by MaximoTrinidad** [comment] 2018-07-23 20:50
@Stlouistechy 

Question: Did you setup Winrm linux on RHEL Docker?

I know it's kind-of hard to setup but it's possible.  The best and fast route it to setup ssh on the Windows Server.  Docker IT/PowerShell image will not have the Winrm configured.

:)

**Comment by Stlouistechy** [comment] 2018-07-23 21:18
@MaximoTrinidad 

Thanks Maximo. I just tested this on my Container by installing pywinrm (pip install pywinrm) and running the steps again. Unfortunately no luck, I receive the same error.

**Comment by MaximoTrinidad** [comment] 2018-07-24 20:46
@Stlouistechy 

OpenSSH can be install in Windows so you can use SSH protocol for remoting.  

By the way, the AD Module will be available (if is not already) for PSCore. Then again, all components to support AD Authentication need to be in place on the Linux system. I know the way to install these components does varies on different Linux distributions. 

:)

**Comment by chuanjiao10** [comment] 2018-07-25 01:58
hi Stlouistechy:
 docker run -it microsoft / powershell ,then you get a **linux powershell**.
the only way is **OVER SSHD** from a **docker linux powershell** to windows,This is the by design.
so this issue is a  question

**Comment by Stlouistechy** [comment] 2018-07-26 17:26
@chuanjiao10 Thanks. Is there a timeline when PSSession and ActiveDirectory modules may be available to PSCore on Linux?

**Comment by chuanjiao10** [comment] 2018-07-27 04:21
Now you can.

the only way is OVER SSHD from a docker linux powershell to windows.

**Comment by danports** [comment] 2019-03-28 18:09
@Stlouistechy The `microsoft/powershell` image is based on Ubuntu, which does not bundle `/etc/services`, so you are likely being bit by this issue: https://github.com/Microsoft/omi/issues/623. The workaround for now is to build your own Docker image based on the PowerShell image that includes a command like:
`RUN echo 'http            80/tcp          www www-http' > /etc/services`

**Comment by jimdigriz** [comment] 2020-02-13 15:15
> @Stlouistechy The `microsoft/powershell` image is based on Ubuntu, which does not bundle `/etc/services`, so you are likely being bit by this issue: [microsoft/omi#623](https://github.com/microsoft/omi/issues/623). The workaround for now is to build your own Docker image based on the PowerShell image that includes a command like:
> `RUN echo 'http 80/tcp www www-http' > /etc/services`

...or `apt-get install netbase`

I just lost two hours of my life because of this.

**Comment by apiening** [comment] 2020-06-12 21:22
Thanks @jimdigriz an `apt update && apt install netbase` did the trick for me as well.

However I can't get around saying how poor this looks to me that Microsoft is unable / unwilling to fix errors like this in their official images that are around for two years.
I only stumbled upon this issue because it seems not to be possible to do PowerShell remoting from Mac OS X (even though it is an officially supported platform) due to an incorrect hard linked dependency to an outdated OpenSSL library.
Searching the web tells that even after 3 years still a lot of users (like me) are wasting their time with no workaround or even a solution provided by Microsoft.

So I thought with their docker image at least it should work right out of the box. Double fail! What a shame!
Sorry but I'm just frustrated after wasting nearly three hours.

**Comment by danports** [comment] 2020-06-13 03:10
@apiening Agreed. I think it took me 1-2 days of work last year digging into the OMI library internals to identify the issue - and then when I did, the fix I proposed was promptly [rejected](https://github.com/microsoft/omi/issues/623#issuecomment-488154661). 🤷‍♂️ 😖

**Comment by VGerris** [comment] 2021-04-16 13:15
It also fails for a non-docker image for me with netbase installed on Ubuntu 20.04. Don't kid yourself, the total lack of support of Microsoft for this and similar issues just shows clearly how committed they are to providing true cross platform solutions.
Kerberos support should work out of the box, it's trivial to make that work if it works on Windows. I would expect more from a so called commitment to open source and other platforms.

**Comment by dvnaveenkashyap** [comment] 2021-04-28 02:45
> apt-get install netbase

Life savior!!

**Comment by VOVELEE** [comment] 2021-06-09 05:08
Please take a look into this threat - https://github.com/jborean93/omi/issues/29
Looks like the limitation comes from the libraries which ship with different version of Windows. The workaround is to set the CbtHardeningLevel to None so Windows doesn't try to validate the value at all.

**Comment by Veverke** [comment] 2021-06-29 20:09
> > apt-get install netbase
> 
> Life savior!!

I had a working image in .net core 3.1 where I could establish remote connections via powershell from linux containers to windows machines, but the same code did not succeed when upgrading to .net 5.
Simply adding netbase package installation to my container dockerfile did the job, I am able to connect from linux containers to windows machines via powershell in .net 5 using sdk 5.0 docker hub image.

**Closed** 2023-11-23 13:25 UTC
Labels: Issue-Discussion, WG-Remoting, Resolution-No Activity
