### ISSUE TITLE
Get-ChildItem -Exclude excludes the base directory

### ISSUE THREAD

**Issue by zzJinux** [PowerShell/PowerShell#9903] opened 2019-06-14 22:24 UTC
As far as I know, `Get-ChildItem` does only care about children of specified path.
But it seems `-Exclude` parameter breaks the rule.

# Steps to reproduce
Assume the working directory is `<some_path>\foo`.
There are some files at  `<some_path>\foo\`.
Let them `file1.txt`, `file2.txt`, and so on
```powershell
gci '.' -File -Exclude 'foo'
# or
gci '.' -Exclude 'foo'
```

# Expected behavior

```none
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2019-06-15  오전 7:17              0 file1.txt
-a----        2019-06-15  오전 7:17              0 file2.txt
```

# Actual behavior
Nothing is printed
```none
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kvprasoon** [comment] 2019-06-16 07:48
Yes, and it does the exclusion in the parent directory. It lists other files in the parent directory.

**Comment by kvprasoon** [comment] 2019-06-16 07:52
Yes, and it does the job only for files. If there is file with name `foo.txt` in the same directory.
This works: `Get-ChildItem -Path '.' -Exclude foo.*`
This doesn't: Get-ChildItem -Path '.' -Exclude foo*``

**Comment by mklement0** [comment] 2019-06-16 19:45
Certainly surprising; ultimately a duplicate of #3304

In short: the exclusion is applied to the leaf component of the targeted dir. _itself_, not to the children.

@kvprasoon: Interesting that `-Name` behaves differently; needless to say, it shouldn't (even though it exhibits the more sensible behavior here) - there are a number of problems relating to `-Name`.

**Closed** 2020-05-08 17:00 UTC
Labels: Area-Cmdlets-Core, Issue-Question, Resolution-Duplicate
