### ISSUE TITLE
Fix path normalization

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1115] opened 2016-06-15 20:03 UTC
Per #1081, we have the known issue of not supporting a path with a literal backward slash for PowerShell cmdlets. This [branch](https://github.com/PowerShell/PowerShell/tree/andschwa/path-normalization) is work-in-progress that investigated PowerShell's path normalization.

The summary is that it's a mess. PowerShell has half a dozen different path normalization functions (all essentially just blindly replacing `/` with `\`, or the reverse on Linux), another dozen locations where these are ignored and a `path.Replace()` is done, and completely separate code to handle escape character parsing (which is tied into the globbing system); and all of this is spread across several systems.

My WIP branch removes all the normalization functions and adds some (dumb, so far) logic to handle a path with a backtick escaped backward slash (but it needs to be improved to handle backtick escaped backticks). Normalization of all backticks can only happen once, and we need to figure out how to make this happen, because parsing globs must be handled around the same time (since glob characters may be escaped). As of now, the WIP does allow escaping a backward slash with a backtick.

This issue is an extension of #570 and #954.

**Comment by andschwa** [comment] 2016-10-04 20:17
Removing assignment as this is future work that will require going through RFC.

**Comment by joeyaiello** [comment] 2017-05-22 23:12
@BrucePay: I think we're "good enough" in this regard already. Since you've been in the globbing code lately, do you know of any shortcoming we still have from a functional perspective? I'd like to close this in lieu of more specific issues.

**Comment by jeffbi** [comment] 2017-05-22 23:31
FWIW, In issue #3414 I [mentioned](https://github.com/PowerShell/PowerShell/issues/3414#issuecomment-298255415) that part of the issue is "premature normalization".

Also, paths ending up fully-qualified (I believe by the globbing mechanism) makes it difficult to provide relative paths to cmdlets like `New-Item -ItemType SymbolicLink` (#3500).

**Comment by joeyaiello** [comment] 2017-05-22 23:55
@jeffbi: thanks for the context. I'm adding this to our Usability project. At some point, I need to look at all these and figure out holistically what we're okay with.

**Comment by joeyaiello** [comment] 2017-08-07 21:32
@anmenaga do you have enough context from @jeffbi for this to be actionable?

**Comment by anmenaga** [comment] 2017-09-18 19:42
This is very high-level and broad kind of issue, which is too risky at this point.
Closing this as duplicate of more specific and narrow #3666 and #3500.

**Closed by anmenaga** 2017-09-18 19:42 UTC
Labels: Issue-Enhancement, OS-Linux, Porting, Resolution-Duplicate
