### ISSUE TITLE
Passing a ScriptBlock (in syntax only) to native commands produces surprising results

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#5187] opened 2017-10-21 00:42 UTC
Steps to reproduce
------------------
Run a command like

```powershell
echoargs {1}
bcdedit /set {cbd971bf-b7b8-4885-951a-fa03044f5d71} device partition=C:
```

PowerShell has long assumed that an argument that looks like a `ScriptBlock` is always a script block - regardless of what command is being called. If the command is native, a very different command line is passed.

This doesn't make sense for most native commands. Long ago there was a vision that there might be many native commands that supported PowerShell and maybe this made sense then, but that hasn't happened.

The workaround is to use quotes - not a bad workaround but still shouldn't be necessary.

If we changed the behavior, we would still pass these special parameters to `powershell.exe` and `pwsh.exe`.

Expected behavior
-----------------

```none
PS> echoargs {1}
arg 0: <{1}>

CommandLine:
EchoArgs.exe {1}
```

Actual behavior
---------------

```none
PS> echoargs {1}
arg 0: <-encodedCommand>
arg 1: <MQA=>
arg 2: <-inputFormat>
arg 3: <xml>
arg 4: <-outputFormat>
arg 5: <text>

CommandLine:
EchoArgs.exe -encodedCommand MQA= -inputFormat xml -outputFormat text
```

**Comment by SteveL-MSFT** [comment] 2017-10-21 00:47
So the expected behavior is that if the command is native, braces are literal always?  What about parenthesis?

**Comment by lzybkr** [comment] 2017-10-21 01:28
I'm suggesting syntax doesn't matter - if the **value** is a `ScriptBlock`, pass the literal text unless calling `powershell.exe` or `pwsh.exe`, then use `-encodedCommand`.

We could attempt to be smart too - only pass the literal if the `ScriptBlock` has no whitespace, or I suppose escaped whitespace

**Comment by SteveL-MSFT** [comment] 2017-10-25 01:02
Isn't this a dupe of https://github.com/PowerShell/PowerShell/issues/1761?

**Comment by lzybkr** [comment] 2017-10-26 02:24
Not really a dupe.

**Comment by BrucePay** [comment] 2018-03-09 21:03
@lzybkr Historical context: this feature was introduced when we were still having to consider mini-shells. In that scenario, we were expecting many, many shells - essentially one mini-shell executable per module - all with unknown names. And so we autoconverted scriptblocks for all executables. Obviously that is no longer the case however people may have aliases/symlinks for our binaries (similar to python & python3). So there is still a chance that there will be unknown binaries. As an alternative to hard coding the list of executables, we could tweak the converter to special-case GUIDs. Are there other common cases where we'd want scriptblocks passed to executable verbatim?

**Comment by lzybkr** [comment] 2018-03-09 21:21
@BrucePay - `bcdedit` accepts names in place of a GUID, e.g.: ` bcdedit /default {ntldr}`.

I suppose a heuristic is possible though - if there are no spaces, it's unlikely to be a script block. Furthermore, if the text specifies calling a single command with no arguments and that command doesn't exist, that is very strong evidence that it's not really a script block - that would cover most use cases.

That said, I've never seen another executable that relies on this behavior. Introducing quirky behavior on the off chance that a non-PowerShell binary expects the current behavior is maybe being a little too paranoid w.r.t. compatibility.

**Comment by mklement0** [comment] 2018-10-09 15:34
As for the symlink issue (the PowerShell executable in disguise): resolving symlinks to their ultimate target to check the latter's name sounds like a simple solution.

I agree that _not_ employing heuristics is best - both in this case and #1761 - because in the long run users are better served by simply having to remember - and being able to rely on - _one_ simple rule:

_PowerShell's own syntax requirements must be satisfied first_, which means that any metacharacters recognized by PowerShell must be quoted for literal use in an argument.

Yes, for users unfamiliar with PowerShell's syntax that involves growing pains - given that more characters are metacharacters than in other shells, especially compared to `cmd.exe`, but the _principle_ is the same: Just like you must double-quote a literal `&` in `cmd.exe`, for instance, you must quote a `{...}` token meant to be a literal.

In the long run, and across different scenarios, not having to remember heuristics and exceptions is a blessing.

> The workaround is to use quotes - not a bad workaround but still shouldn't be necessary.

Therefore, I wouldn't frame the need to use quoting as a _workaround_ - it's simply a syntactic necessity in PowerShell.

As PowerShell sees wider adoption - and perhaps even becomes the single, _cross-platform_ choice for users - these issues will lessen: 

 * users will know the syntax requirements
 * more command lines that use PowerShell syntax to begin with will appear online

That said (a separate issue), the [broken treatment of double quotes](https://github.com/PowerShell/PowerShell-Docs/issues/2361) will continue to be a pain point.

---

As for helping users understand:

In the case at hand, applying the usual rules - stringification of a script block to its literal content - will at least tell users that the `{` and `}` were "eaten" during invocation, which is a starting point for investigation.

In #1761 the symptom is more obscure.

Providing a way to inspect the actual arguments passed would definitely be helpful, as originally discussed in https://github.com/PowerShell/PowerShell/issues/1761#issuecomment-283857859.

**Closed** 2023-11-23 13:34 UTC
Labels: Issue-Discussion, Breaking-Change, Resolution-No Activity
