### ISSUE TITLE
``new-item`` cannot create hardlinks with ``[]`` in the name on win10

### ISSUE THREAD

**Issue by LDSpits** [PowerShell/PowerShell#14960] opened 2021-03-07 20:55 UTC
When attempting to create a hardlink with special characters in powershell 7.1, the command fails with the message 
```New-Item: Cannot find path 'D:\debugging\[name] with special chars.txt' because it does not exist.```
for items with the special characters ``[]``

I have attempted to create a hardlink with the ``mklink /H`` command on the commandpromt, Which is able to accept targets with special characters.

Since the commandprompt is able to do this, I would expect to be able to do the same with powershell

## Steps to reproduce

```powershell
# Validating being able to create normal hardlinks
New-Item -ItemType HardLink -Target (Resolve-Path .\test.txt) -Path "./test-hard.txt"
New-Item -ItemType HardLink -Target (Resolve-Path '.\test name.txt') -Path "./test-hard spaced.txt"

# attempting to create a hardlink with `[]` in the name
New-Item -ItemType HardLink -Target (Resolve-Path '.\`[name`] with special chars.txt') -Path "./test-hard spaced 2.txt"
```

## Expected behavior
Powershell creates a hardlink named `test-hard spaced 2.txt` in the current directory.
```none
    Directory: D:\debugging

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            7-3-2021    15:21              0 test-hard spaced 2.txt
```

## Actual behavior
The Cmdlet fails with the following message
```none
New-Item: Cannot find path 'D:\debugging\[name] with special chars.txt' because it does not exist.
```
I have validated that the target file actually exists in the file explorer, and the command prompt is able to handle this case just fine with the ``mklink`` tool. Provided you escape the name correctly.

```none
D:\debugging>mklink /H "test-hard spaced 2.txt" "[name] with special chars.txt"
Hardlink created for test-hard spaced 2.txt <<===>> [name] with special chars.txt
```

## Environment data
```none
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by p0W3RH311** [comment] 2021-03-07 21:12
try to execute Resolve-Path with -LiteralPath

**Comment by LDSpits** [comment] 2021-03-07 21:14
> 
> 
> try to execute Resolve-Path with -LiteralPath

This still gives me a failure 
```powershell
New-Item -ItemType HardLink -Target (Resolve-Path -LiteralPath '.\[name] with special chars.txt') -Path "./test-hard spaced 2.txt"
New-Item: Cannot find path 'D:\debugging\[name] with special chars.txt' because it does not exist.
```

**Comment by mklement0** [comment] 2021-03-07 21:39
Please see #14534

**Comment by 237dmitry** [comment] 2021-03-07 22:18
It works for me:
![hl](https://user-images.githubusercontent.com/78153320/110256805-fb77ce00-7fab-11eb-8de9-c2805faa2857.png)

**Comment by mklement0** [comment] 2021-03-07 22:21
@237dmitry, this is about the `-Target` parameter, not the `-Name` parameter.

**Comment by 237dmitry** [comment] 2021-03-08 00:02
> this is about the -Target parameter, not the -Name parameter.

I'm sorry, I'm always inattentive. mklink is of course easier.
```
$item = Get-Item '.\`[test`] test `[1`].txt'
New-Item -ItemType HardLink -Name file.txt -Target $($item -replace '(?=[\[\]])','``')
```

**Comment by mklement0** [comment] 2021-03-08 01:51
@237dmitry, while it's good to know about _workarounds_, this is ultimately about _fixing PowerShell's behavior_, as discussed in #14534.

Specifically:

* `mklink` is not only Windows-specific, it is an _internal to `cmd.exe`.

* While _doubly_ escaping the `[` and `]` characters with _two_ `` ` `` characters _happens to work_, that in itself is a bug - see #7999

**Comment by mklement0** [comment] 2021-03-08 02:09
Another way of putting it:

* If we accepted the - questionable - premise that the `-Value` / `-Target` argument should be interpreted as a _wildcard pattern_:
  * Then `[WildcardPattern]::Escape('C:\Path\To\file [123].txt')` - i.e. ``'C:\Path\To\file `[123`].txt'`` -  should work: _one_ `` ` `` to escape each metacharacter.

* We _shouldn't_ accept this premise, however, because that argument should be interpreted as a _literal_ (verbatim) path.

**Comment by abaumgaertner** [comment] 2021-04-05 18:29
similar issue #6232

**Comment by CCRcmcpe** [comment] 2022-11-15 12:32
How this is still an open issue in 2022? `New-Item -ItemType SymbolicLink` with `-Target` contains `[]` still does not work.

**Comment by daxian-dbw** [comment] 2023-06-12 21:22
**The Engine WG reviewed this issue** and believe this is a duplicate of #14534. Will close this issue as a duplicate.

**Closed** 2023-06-13 23:00 UTC
Labels: Resolution-Duplicate, WG-Engine-Providers
