### ISSUE TITLE
Date and time related functions returning error

### ISSUE THREAD

**Issue by sachidananda04** [PowerShell/PowerShell#4874] opened 2017-09-20 12:44 UTC
Steps to reproduce
------------------
I am using "powershell-6.0.0_beta.7-1.el7.x86_64.rpm" running inside my docker container

$cstZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
Write-Host $cstZone
$cstTime = [System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), $cstZone)
$date = Get-Date $cstTime -f "yyyy-MM-dd"
Write-Host $date

Expected behavior
-----------------

Should get the datetime of timezone specified and convert it to UTC.

Actual behavior
---------------
Exception calling "FindSystemTimeZoneById" with "1" argument(s): "The time zone
 ID 'Eastern Standard Time' was not found on the local computer."
$cstZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Sta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TimeZoneNotFoundException

Exception calling "ConvertTimeFromUtc" with "2" argument(s): "Value cannot be n
ull.
Parameter name: destinationTimeZone"
 $cstTime = [System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUni ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
 
Get-Date : Cannot bind parameter 'Date' to the target. Exception setting "Date"
: "Cannot convert null to type "System.DateTime"."
+ $date = Get-Date $cstTime -f "yyyy-MM-dd"
+                  ~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-Date], ParameterBindingExce 
   ption
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Comm 
   ands.GetDateCommand

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by markekraus** [comment] 2017-09-20 13:40
Dupe of dotnet/corefx#11897

This is a CoreFX issue where time zones are inconsistent between Linux and Windows. This will be fixed in PowerShell when it is fixed upstream.

**Closed** 2017-09-20 14:00 UTC
Labels: Resolution-External
