### ISSUE TITLE
String with parenthesis in subexpression in expandable string parsed incorrectly

### ISSUE THREAD

**Issue by TimCurwick** [PowerShell/PowerShell#13729] opened 2020-10-01 16:23 UTC
A parenthesis within a string in a subexpression within an expandable string is incorrectly treated by the parser as an operator rather than as part of a string.

## Steps to reproduce

```powershell
"$('(')"
```

```powershell
"$(')')"
```

## Expected behavior

```none
(
```

```none
)
```

## Actual behavior

```none
$(subexpression) is missing the closing ')'.
```

```none
The string is missing the terminator: '.
```

## Environment data

```none
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2020-10-01 18:56
Good find, but it looks like a duplicate of #4543.

**Closed** 2020-10-02 23:00 UTC
Labels: Issue-Question, Resolution-Duplicate
