### ISSUE TITLE
Proxy not being used on Linux/Mac under 6.1.0

### ISSUE THREAD

**Issue by ciranor** [PowerShell/PowerShell#7945] opened 2018-10-04 17:44 UTC
With the release of 6.1.0, it appears to not always use a proxy on Linux or OSX, specifically when trying to run "Connect-AzureRmAccount". If I downgrade to 6.0.4 on Linux or OSX, it works. On Windows, the Connect-AzureRmAccount correctly uses the system defined proxy.

I'm assuming it's a PowerShell 6.1.0 issue and not a AzureRM.Netcore issue.

The version of AzureRM.Netcore is current (0.13.1)

Running tcpdump in the background, I can see that under powershell 6.1.0 it only tries to open direct sockets to port 443 out on the internet; under powershell 6.0.4 it instead correctly talks to my corporate proxy. The proxy is defined via the environment variables HTTP_PROXY and HTTPS_PROXY. 

If I run "Invoke-WebRequest" instead, under 6.0.4, it picks up the HTTPS_PROXY env var and uses it without needing a -Proxy argument. Under 6.1.0 it doesn't use the env vars, and requires the -Proxy argument.

I've tested and reproduced this on both Linux (CentOS 7.5) and OSX (10.13.6).

Steps to reproduce
------------------

```powershell
[simon@simon-base7-01 (devkvm) ~]$ export HTTP_PROXY=http://webproxy:3128/
[simon@simon-base7-01 (devkvm) ~]$ export HTTPS_PROXY=http://webproxy:3128/
[simon@simon-base7-01 (devkvm) ~]$ pwsh
PowerShell v6.0.4
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /home/simon> Connect-AzureRmAccount
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXX to authenticate.
^C[simon@simon-base7-01 (devkvm) ~]$ sudo rpm -U /home/simon/powershell-6.1.0-1.rhel.7.x86_64.rpm
[simon@simon-base7-01 (devkvm) ~]$ pwsh
PowerShell 6.1.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /home/simon> Connect-AzureRmAccount
Connect-AzureRmAccount : Connection refused: Connection refused
At line:1 char:1
+ Connect-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], AadAuthenticationFailedException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

PS /home/simon>

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
PS /home/simon> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/simon> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2018-10-05 03:39
@markekraus Could you please comment the Issue?

**Comment by markekraus** [comment] 2018-10-05 11:02
I'm not entirely sure, but this looks like a regression in corefx. dotnet/corefx#28088 changes the way the environment variables are handled. if I'm understanding this correctly, it looks like they will get incorrect URIs for HTTPS_PROXY. `GetUriFromString()` is striping the string of `http://` but not `https://` and then later they depend on `:` being at the end of the host.

**Comment by markekraus** [comment] 2018-10-05 11:55
ok.. looks like it is a regression but not the one I thought.

```powershell
$assembly = [System.Net.Http.HttpClientHandler].Assembly
$class = $assembly.GetType('System.Net.Http.HttpEnvironmentProxy')
$method = $class.GetMethod('TryCreate')
$proxy = [System.Net.WebProxy]::new()
$env:HTTPS_PROXY = 'http://webproxy:3128/'
$method.Invoke($null, @($proxy))
```

Should be `True` but is `False`.

but, if you remove the trailing `/` from the proxy it works:

```powershell
$assembly = [System.Net.Http.HttpClientHandler].Assembly
$class = $assembly.GetType('System.Net.Http.HttpEnvironmentProxy')
$method = $class.GetMethod('TryCreate')
$proxy = [System.Net.WebProxy]::new()
# No trailing slash
$env:HTTPS_PROXY = 'http://webproxy:3128'
$method.Invoke($null, @($proxy))
```

@ciranor as a work around, set your env vars without the trailing slash.

We will need to open an issue with corefx.

**Comment by markekraus** [comment] 2018-10-05 12:08
Created dotnet/corefx#32635

**Comment by ciranor** [comment] 2018-10-05 12:42
Yes, I can confirm that by removing the trailing slash, Invoke-WebRequest and Connect-AzureRMAccount both work under 6.1.0.

Cheers.

**Comment by iSazonov** [comment] 2018-10-05 15:13
@markekraus Could you test with latest build? Currently we moved to .Net Core 2.1.5 and seems CoreFX fix should be there. 
I can not run your repo script - `$class = $assembly.GetType('System.Net.Http.HttpEnvironmentProxy')` is empty.

**Comment by markekraus** [comment] 2018-10-06 00:37
@iSazonov `System.Net.Http.HttpEnvironmentProxy` is only available on Linux and macOS. 

I was able to build the latest on ubuntu and confirmed it is fixed with the move to .NET Core 2.1.5

**Closed by markekraus** 2018-10-06 00:37 UTC
Labels: Area-Cmdlets-Utility, Issue-Discussion, Waiting - DotNetCore
