### ISSUE TITLE
Unsupported Ubuntu Version 20.04 when building repository on Ubuntu 20.04

### ISSUE THREAD

**Issue by ashmoreinc** [PowerShell/PowerShell#14554] opened 2021-01-07 01:05 UTC
## Steps to reproduce

```powershell
using Ubuntu 20.04
clone repo
cd into repo
run ./tools/install-powershell.psh
```

## Expected behavior

```none
Installation
```

## Actual behavior

```none
Output: ERROR: unsupported Ubuntu Version 20.04
![Output](https://user-images.githubusercontent.com/12419736/103912508-4cc82600-50ff-11eb-8b58-07c284d3dbd9.png)
```

## Environment data

```none
Fresh install of Ubuntu version 20.04 LTS. 
Using Gauke Terminal

```

**Comment by iSazonov** [comment] 2021-01-07 12:18
> Using Guake Terminal Emulator

Could you please add more info about your scenario? Also please use more informative Title.

/cc @DHowett for information.

**Comment by JustinGrote** [comment] 2021-03-23 20:54
@iSazonov I think I had a dupe of this. 20.04 is now supported by 7.1:
https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7.1

But the install-powershell.sh script does not have 20.04 listed so it fails with unsupported version.
https://github.com/PowerShell/PowerShell/blob/7acf70e0234cd57e0bb20e77a4681e924a92b13e/tools/installpsh-debian.sh#L157-L173

**Closed** 2021-04-05 20:21 UTC
Labels: Area-Maintainers-Build, Needs-Triage
