### ISSUE TITLE
exit fails after pipeline chain operator (&&)

### ISSUE THREAD

**Issue by UziTech** [PowerShell/PowerShell#13253] opened 2020-07-23 17:50 UTC
## Steps to reproduce

```powershell
echo 1 && exit
```

## Expected behavior

```none
1
```

then terminates the process

## Actual behavior

```none
1
exit: The term 'exit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2020-07-23 17:59
@rjmholt this is by design, right?

**Comment by rjmholt** [comment] 2020-07-23 18:03
Duplicate of https://github.com/PowerShell/PowerShell/issues/10967

**Closed** 2020-07-23 19:19 UTC
Labels: Issue-Question, Resolution-Duplicate
