### ISSUE TITLE
Get-Alias Name parameter allows Null value

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2544] opened 2016-10-27 10:51 UTC
Reported via [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13741089-get-service-name-parameter-allows-null-value) (in comments)

(Related #2540 )
## Steps to reproduce
1. Get-Alias -Name $null
2. Get-Alias -Name ""
## Expected behavior

ParameterBinding exception saying the value is null or empty
## Actual behavior
1. Returns all aliases
2. Return `Get-Alias -Name ""
   Get-Alias : This command cannot find a matching alias because an alias with the name '' does not exist.`
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10240.17113
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by SteveL-MSFT** [comment] 2016-10-27 16:13
This is not a regression and I can repro with PS2.0.  If we change this, it would be a breaking change.  There's probably a number of cmdlets that assume that $null means that parameter wasn't passed and acts accordingly which I agree is wrong.

**Comment by HemantMahawar** [comment] 2016-10-27 20:40
@SteveL-MSFT Are you proposing that we don't fix this issue (as well as #2540) or fix it as "potential breaking change" or something else?

**Comment by SteveL-MSFT** [comment] 2016-10-27 20:52
@HemantMahawar before I can make proposal, I would like to know what other cmdlets have this behavior to understand the extent of the breaking change if we decide to change the behavior.  seems like this should be easy to script

**Comment by HemantMahawar** [comment] 2016-10-27 23:45
@SteveL-MSFT 
I wrote a [quick script](https://gist.github.com/HemantMahawar/c21b628a85ccc58e2c3c78e89db3207a) to find this data on PS 5.1 machine for Get-* cmdlets.

# Cmdlets that do the right thing
## Get-Acl
Path                           True  

## Get-Command
Name                           True  

## Get-ControlPanelItem
Name                           True  

## Get-HotFix
Id                             True  

## Get-FormatData
TypeName                       True  

## Get-ItemPropertyValue
Path                           True  

## Get-Member
Name                           True  

## Get-Module
Name                           True  

## Get-Process
Name                           True  

## Get-PSDrive
Name                           True  

## Get-PSHostProcessInfo
Name                           True  

## Get-TypeData
TypeName                       True  

## Provider cmdlets that should not be changed
## Get-ChildItem 
Path                          False 
Filter                         False 

## Get-ItemProperty
Name                           False 

# Cmdlets that I am not sure about
## Get-Credential 
UserName                       False 

## Get-Help (fixing this would be a breaking change for interactive scenario only)
Name                           False 

# Cmdlets that have room for improvement
## Get-Alias
Name                           False 

## Get-ComputerInfo
Property                       False 

## Get-Event
SourceIdentifier               False 

## Get-EventSubscriber
SourceIdentifier               False 

## Get-PSBreakpoint
Script                         False 

## Get-PSProvider
PSProvider                     False 

## Get-PSSessionConfiguration
Name                           False 

## Get-PSSnapin
Name                           False 

## Get-Runspace
Name                           False 

## Get-RunspaceDebug
RunspaceName                 False 
ProcessName                    True
AppDomainName             True  

## Get-Service
Name                           False 

## Get-TimeZone
Name                           False 

## Get-TraceSource
Name                           False 

## Get-Variable (Does only ValidateNotNull)
Name                           False 

## Get-WmiObject
Class                          False 
Property                       False

**Comment by SteveL-MSFT** [comment] 2016-10-28 00:37
@HemantMahawar thanks for taking the time to script this.  Are you saying we shouldn't change the provider cmdlets because passing $null explicitly is a valid case (maybe registry provider?)?  As for the other ones, doing a quick look over them, I don't see a real scenario where you would pass in $null as the parameter value and expect it to return all results rather than it being a mistake on my part to not have defined the value being passed in.  Seems like we either fix all of them or none.  I don't think I would be selective here unless $null is a legitimate value.

**Comment by iSazonov** [comment] 2016-10-28 13:21
My _subjective_ assessment:
- Low - the likelihood of a deliberate transfer of _empty_ values directly or from a pipeline is very small and/or cmdlet is used relatively rarely.
- Middle -  cmdlet is used relatively often and submisson of empty values possible.
- High - breaking - cmdlet should not be fixed.

My greatest concerns relate to `Get-ChildItem` and `Get-ItemProperty`.  We could use the script template from @daxian-dbw [AnalyzeSelectObject.ps1  ](https://gist.github.com/daxian-dbw/07847ff5ef6da2c100e8b22bd94f0feb) to assess their.

(I attached the file with the table source so you can edit it [cmdlet_table.txt](https://github.com/PowerShell/PowerShell/files/558428/cmdlet_table.txt) )

Cmdlet|Param|Need Fix|Break Level
----|------|------|---------
Get-Alias|Name|Yes|Low
Get-ChildItem|Path|Yes| Middle
Get-ChildItem|Filter|Yes| Middle
Get-Credential|UserName|Yes| Low
Get-Event|SourceIdentifier|Yes| Low
Get-EventSubscriber|SourceIdentifier|Yes| Low
Get-Help|Name|Yes| Low
Get-ItemProperty|Name|Yes| Middle
Get-PSBreakpoint|Script|Yes| Low
Get-PSProvider|PSProvider|Yes| Low
Get-PSSessionConfiguration|Name|Yes| Low
Get-PSSnapin|Name|Yes| Low
Get-Runspace|Name|?| ?
Get-RunspaceDebug|RunspaceName|?| ?
Get-Service|Name|Yes| Low
Get-TraceSource|Name|?| ?
Get-Variable|Name|Yes| Low
Get-WmiObject|Class|Yes| Low
Get-WmiObject|Property|Yes| Low

**Comment by SteveL-MSFT** [comment] 2016-11-01 00:21
#2545 is one specific case, this one covers the broader discussion, keeping it open for committee to review

**Comment by HemantMahawar** [comment] 2016-11-11 23:46
@PowerShell/powershell-committee agreed that we should leave the provider cmdlets as is, due to high chance of breaking changes and fix the other cmdlets.
@SteveL-MSFT  to open a meta-issue for all the remaining cmdlets (subjected to above statement) and then close this issue.

**Closed** 2016-11-12 00:59 UTC
Labels: Area-Cmdlets, Issue-Discussion, PS 5.0 BreakingChange
