### ISSUE TITLE
use MSMQ PS7 ? (under Windows 11 22H2)

### ISSUE THREAD

**Issue by togarashi7** [PowerShell/PowerShell#18824] opened 2022-12-19 11:08 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using PowerShell on Windows 11 22H2, can I use MSMQ ?
Both PS5.1 and PS7.3.1.
I was able to use it on Windows 11 21H2.

### Expected behavior

```console
PS C:\> Get-Command "*MSMQ*"

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Clear-MsmqOutgoingQueue                            1.0        MSMQ
Function        Clear-MsmqQueue                                    1.0        MSMQ
Function        Enable-MsmqCertificate                             1.0        MSMQ
Function        Get-MsmqCertificate                                1.0        MSMQ
Function        Get-MsmqOutgoingQueue                              1.0        MSMQ
Function        Get-MsmqQueue                                      1.0        MSMQ
Function        Get-MsmqQueueACL                                   1.0        MSMQ
Function        Get-MsmqQueueManager                               1.0        MSMQ
Function        Get-MsmqQueueManagerACL                            1.0        MSMQ
Function        Move-MsmqMessage                                   1.0        MSMQ
Function        New-MsmqMessage                                    1.0        MSMQ
Function        New-MsmqQueue                                      1.0        MSMQ
Function        Receive-MsmqQueue                                  1.0        MSMQ
Function        Remove-MsmqCertificate                             1.0        MSMQ
Function        Remove-MsmqQueue                                   1.0        MSMQ
Function        Resume-MsmqOutgoingQueue                           1.0        MSMQ
Function        Send-MsmqQueue                                     1.0        MSMQ
Function        Set-MsmqQueue                                      1.0        MSMQ
Function        Set-MsmqQueueACL                                   1.0        MSMQ
Function        Set-MsmqQueueManager                               1.0        MSMQ
Function        Set-MsmqQueueManagerACL                            1.0        MSMQ
Function        Suspend-MsmqOutgoingQueue                          1.0        MSMQ
```

### Actual behavior

```console
I can't use MSMQ PowerShell.

PS C:\> Get-Command "*MSMQ*"
PS C:\>
```

### Error details

```console
PS C:\Users> Get-MsmqQueue
Get-MsmqQueue: The term 'Get-MsmqQueue' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS C:\Users> Get-Command "*MSMQ*"
PS C:\Users>
```

### Environment data

```powershell
PS C:\Users> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users>  Get-WindowsOptionalFeature -Online  | ? FeatureName -match "msmq"

FeatureName : WCF-MSMQ-Activation45
State       : Disabled

FeatureName : MSMQ-Container
State       : Enabled

FeatureName : MSMQ-DCOMProxy
State       : Enabled

FeatureName : MSMQ-Server
State       : Enabled

FeatureName : MSMQ-ADIntegration
State       : Disabled

FeatureName : MSMQ-HTTP
State       : Disabled

FeatureName : MSMQ-Multicast
State       : Disabled

FeatureName : MSMQ-Triggers
State       : Enabled
```

**Comment by jborean93** [comment] 2022-12-20 02:45
Somewhat of a duplicate of https://github.com/PowerShell/PowerShell/issues/18783. The MSMQ module is a Windows component that has not been updated to support the newer dotnet versions that PowerShell 7 runs with. This is not part of PowerShell itself and there's not much that can be done to fix that here.

A workaround is to run all the MSMQ code in a WinPS remoting session like

```powershell
$s = New-PSSession -UseWindowsPowerShell
Invoke-Command -Session $s -ScriptBlock {
    Get-MsmQueue -Name foo
}
$s | Remove-PSSession
```

Everything inside the ScriptBlock is run in a Windows PowerShell process and is completely backwards compatible. If even this doesn't work then the module just isn't installed and is maybe under a different feature name.

**Closed** 2022-12-21 05:00 UTC
Labels: Resolution-Duplicate, Needs-Triage
