### ISSUE TITLE
"$a = 1.2.3" gives no error message but doesn't do anything

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#15909] opened 2021-08-12 01:24 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I would expect some kind of exception but there isn't any.

### Expected behavior

```console
$a = 1.2.3
1.2.3: The term '1.2.3' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Actual behavior

```console
$a = 1.2.3

# no error but $a is null
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2021-08-12 01:28
When accessing nonexistent properties, PS silently returns `$null` unless strict mode is enabled. The way PS reads this is `$a = (1.2).3` -- in other words, it parses `1.2` as a number and then looks for a property named `3`. Finding none, it returns null and stores that value into `$a`

**Comment by vexx32** [comment] 2021-08-12 01:35
Duplicate of https://github.com/PowerShell/PowerShell/issues/15756

**Comment by jszabo98** [comment] 2021-08-12 01:54
I guess you can sort of add a member to a number.

```powershell
$a = 1.2
$a | Add-Member -NotePropertyName 3 -NotePropertyValue Done
$a.3
Done
```

**Closed** 2021-08-13 02:00 UTC
Labels: Resolution-Duplicate, Issue-Question
