### ISSUE TITLE
Test failures on Linux under Admin account

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#3659] opened 2017-04-27 20:46 UTC
A couple of tests fail during a test run under 'sudo'ed PowerShell or 'su'.

Steps to reproduce
------------------
1)
```
sudo /home/andrew/PowerShell/src/powershell-unix/bin/Linux/netcoreapp2.0/debian.8-x64/publish/powershell
Invoke-Pester /home/andrew/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Utility/Export-Alias.Tests.ps1
```

2)
```
sudo /home/andrew/PowerShell/src/powershell-unix/bin/Linux/netcoreapp2.0/debian.8-x64/publish/powershell
Invoke-Pester /home/andrew/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
```

Expected behavior
-----------------
100% test pass

Actual behavior
---------------
1)
```
 [-] Export-Alias for Force ReadOnly Test 587ms
   Expected string length 64 but was 13. Strings differ at index 0.
   Expected: {FileOpenFailure,Microsoft.PowerShell.Commands.ExportAliasCommand}
   But was:  {No Exception!}
   -----------^
   at line: 124 in /home/andrew/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Utility/Export-Alias.Tests.ps1
   124: 			$_.FullyQualifiedErrorId | Should be "FileOpenFailure,Microsoft.PowerShell.Commands.ExportAliasCommand"
```

2)
```
 [-] Should error correctly when failing to create a symbolic link 385ms
   Expected string length 81 but was 59. Strings differ at index 7.
   Expected: {NewItemSymbolicLinkElevationRequired,Microsoft.PowerShell.Commands.NewItemCommand}
   But was:  {NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand}
   ------------------^
   at line: 186 in /home/andrew/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
   186:             $_.FullyQualifiedErrorId | Should Be "NewItemSymbolicLinkElevationRequired,Microsoft.PowerShell.Commands.NewItemCommand"
```

Environment data
----------------
```
$psversiontable

Name                           Value
----                           -----
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-alpha.18-36-ga2268ab3ecb6c1addffbedba0606aa6c95809dd4-dirty
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
Get-Content /etc/os-release -Raw
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by JamesWTruher** [comment] 2017-04-27 23:04
it's probable that #1 above should be skipped in this context. When running in an elevated `sudo` context you pretty much have permissions to override anything, including creating files. It should be possible to run these tests correctly in a _lowered_ context. (`sudo -u underpowereduser` ...)

**Comment by TravisEz13** [comment] 2018-02-13 20:18
This is basically a duplicate of https://github.com/PowerShell/PowerShell/issues/5645 which says we should tag the tests that are supposed to run as sudo

**Closed by TravisEz13** 2018-02-13 20:18 UTC
Labels: Area-Test
