### ISSUE TITLE
On Linux, tab completion doesn't show files whose names differ from others by case only

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14365] opened 2020-12-09 21:14 UTC
Note: The problem seems to be in the match-_cycling_ logic, because `TabExpansion2` is working properly.

## Steps to reproduce

On Linux:

```powershell
# Switch to a temp dir.
Push-Location (New-Item -Type Directory -Force "temp:/$PID")

# Create two files whose names differ only in case.
$null = New-Item foo.txt, FOO.txt

# Note that the following test SUCCEEDS.
# That is, the TabExpansion2 function correctly finds both names.
(TabExpansion2 './').CompletionMatches.CompletionText | Should -Be './foo.txt', './FOO.txt'

# However,  INTERACTIVE CYCLING is broken.
# Type "./" and press TAB to cycle through the matches.
# Currently only *1* name is found.
```

Code for later cleanup:

```powershell
Pop-Location;  Remove-Item -Recurse "temp:/$PID"
```

## Expected behavior

Tab-completion should cycle through `./foo.txt` and `/FOO.txt`.

## Actual behavior

Only _one_ name is found, `./foo.txt`

## Environment data

```none
PowerShell Core 7.2.0-preview.1
```

**Comment by MartinGC94** [comment] 2022-09-24 22:27
This is a PSReadline issue, see: https://github.com/PowerShell/PSReadLine/issues/722 relevant code is here: https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/Completion.cs#L305 where it's using a case insensitive hashset to filter out apparent duplicates.

**Comment by dkaszews** [comment] 2022-09-28 21:52
Will see if changing the line found by @MartinGC94 to check if system is case insensitive (Windows) or case sensitive (mostly everything else) resolves the issue without breaking any tests.

**Comment by dkaszews** [comment] 2022-10-01 19:02
Interesting, Windows can also be case sensitive on per-folder basis https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

So should we query each path to check it (may be prohibitively expensive), or just make the comparison always case sensitive? Or assume nobody uses this feature and just fix it for non-Windows systems?

**Comment by MartinGC94** [comment] 2022-10-01 21:45
@dkaszews Neat. I just tested it on my Windows 11 PC and it works without issues if you unload the PSReadline module so if there was any doubt before that the issue was caused by PSReadline then that doubt should be cleared now.

**Comment by dkaszews** [comment] 2022-10-22 12:17
Confirmed that this is a `PSReadLine` issue resolved by removing `StringComparer.OrdinalIgnoreCase` in line pointed by @MartinGC94 .

Issue promoted https://github.com/PowerShell/PSReadLine/issues/3455 , this one can be closed as `Resolution-External`

**Closed** 2022-10-24 16:48 UTC
Labels: Resolution-External
