### ISSUE TITLE
ScriptProperty extensions on String via Update-TypeData break ConvertTo-Json

### ISSUE THREAD

**Issue by rmbolger** [PowerShell/PowerShell#7091] opened 2018-06-17 06:26 UTC
Steps to reproduce
------------------

```powershell
# add a ScriptProperty to System.String
Update-TypeData -TypeName System.String -MemberType ScriptProperty -MemberName Foo -Value { $this.ToUpper() }

# call ConvertTo-Json with an object that contains at least one string
'asdf' | ConvertTo-Json
```

Expected behavior
-----------------

```none
"asdf"
```

Actual behavior
---------------

```none
Process is terminating due to StackOverflowException.
Aborted (core dumped)
```

In this simple example where the script value is `$this.ToUpper()`, crashing with a StackOverflowException happens reliably and relatively quickly. If the script value is changed to something more complex, the PowerShell process tends to hang and consume massive amounts of memory until it crashes or is terminated.

Environment data
----------------

This seems to affect both Windows PowerShell and PowerShell Core 6.0.2 regardless of OS platform. The tests I did were from Windows 10 1803 running Windows PowerShell 5.1 and PowerShell Core 6.0.2 both on Windows and Ubuntu 16.04 via WSL. I've included the `$PSVersionTable` output for all below.

```powershell
# Win PowerShell 5.1
Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

# PowerShell Core 6.0.2 (Windows)
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# PowerShell Core 6.0.2 (Ubuntu 16.04)
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2018-06-17 12:07
Good find.

#5797 is essentially the same issue with respect to `NoteProperty` members (and without a crash) in that it also asks that such ETS properties be _ignored_ during to-JSON serialization.

**Comment by msftrncs** [comment] 2019-03-17 06:52
Still happening in 6.2 RC 1, and per #6847, the object might be converted to a hash first, something must be going wrong during that pre-conversion before being sent to NewtonSoft?

**Comment by kganjam** [comment] 2020-10-28 04:22
Still happening in 7.0.3. This bug caused me to lose more than a week dealing with an internal support team as I thought the issue was due to something wrong in their code. In fact, their code was simple calling ConvertTo-Json and I happened to have had some extension methods for System.String.

**Comment by SteveL-MSFT** [comment] 2020-11-04 22:46
Closing as dupe of https://github.com/PowerShell/PowerShell/issues/5797, carry on discussion in that one

**Closed by SteveL-MSFT** 2020-11-04 22:46 UTC
Labels: Area-Cmdlets-Utility, Issue-Discussion, Resolution-Duplicate
