### ISSUE TITLE
Out-File exports Powershells colors 

### ISSUE THREAD

**Issue by YourturnGaming** [PowerShell/PowerShell#17206] opened 2022-04-27 22:19 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When running a command then piping out-file, if that command has color formatting in powershell 7 it seems to export the color formatting as well. 

In following examples, I'm just censoring my user profile name.

Following command I'm using is  `ls | out-file test.txt`

### Expected behavior

```console
Directory: C:\Users\(user)


Mode                 LastWriteTime         Length Name                            
----                 -------------         ------ ----                            
d-----        2022-04-18   9:32 AM                .openshot_qt                    
d-r---        2021-08-09   3:06 PM                3D Objects                      
d-----        2021-12-17  12:42 PM                ansel                           
d-r---        2021-08-09   3:06 PM                Contacts                        
d-r---        2022-04-26   9:41 AM                Desktop                         
d-r---        2022-04-22  12:41 PM                Documents                       
d-r---        2022-04-27  12:23 PM                Downloads                       
d-r---        2021-08-09   3:06 PM                Favorites                       
d-r---        2021-08-09   3:06 PM                Links                           
d-r---        2021-08-09   3:06 PM                Music                           
d-r---        2021-08-09   3:24 PM                OneDrive                        
d-r---        2022-04-19   3:46 PM                Pictures                        
d-r---        2021-08-09   3:06 PM                Saved Games                     
d-r---        2021-08-09   3:08 PM                Searches                        
d-r---        2022-04-18  12:02 PM                Videos                          
d-----        2022-03-07  10:10 AM                Web                             
-a----        2022-03-02  11:44 AM              0 Sti_Trace.log                   
-a----        2022-04-27   4:00 PM           1251 test.txt                        
-a----        2022-04-27   4:05 PM              0 test2.txt
```

### Actual behavior

```console
Directory: C:\Users\(user)

[32;1mMode                 LastWriteTime         Length Name[0m
[32;1m----                 -------------         ------ ----[0m
d----          2022-04-18  9:32 AM                .openshot_qt
d-r--          2021-08-09  3:06 PM                3D Objects
d----          2021-12-17 12:42 PM                ansel
d-r--          2021-08-09  3:06 PM                Contacts
d-r--          2022-04-26  9:41 AM                Desktop
d-r--          2022-04-22 12:41 PM                Documents
d-r--          2022-04-27 12:23 PM                Downloads
d-r--          2021-08-09  3:06 PM                Favorites
d-r--          2021-08-09  3:06 PM                Links
d-r--          2021-08-09  3:06 PM                Music
d-r--          2021-08-09  3:24 PM                OneDrive
d-r--          2022-04-19  3:46 PM                Pictures
d-r--          2021-08-09  3:06 PM                Saved Games
d-r--          2021-08-09  3:08 PM                Searches
d-r--          2022-04-18 12:02 PM                Videos
d----          2022-03-07 10:10 AM                Web
-a---          2022-03-02 11:44 AM              0 Sti_Trace.log
-a---          2022-04-27  4:00 PM              0 test.txt
```

### Environment data

```powershell
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Screenshot 2022-04-27 161622](https://user-images.githubusercontent.com/14059332/165640601-f86fbbca-5d55-4ce3-9340-40b06c6cb2e2.png)

**Comment by SeeminglyScience** [comment] 2022-04-28 14:10
Duplicate of #16618

As a work around you can use

```powershell
$oldRendering = $PSStyle.OutputRendering 
try {
	$PSStyle.OutputRendering = 'PlainText'
    ls | Out-File test.txt
} finally {
    $PSStyle.OutputRendering = $oldRendering
}
```

**Closed** 2022-04-29 17:00 UTC
Labels: Resolution-Duplicate

**Comment by AspenForester** [comment] 2023-01-24 20:58
Just as a note, this same thing happens to the output capture when you have an Azure Automation Hybrid Worker running a 7.1 runspace runbook.  @SeeminglyScience's solution applies nicely.
