### ISSUE TITLE
removing a file with wildcards in the name fails on MacOS

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#1473] opened 2016-07-21 23:41 UTC
## Steps to reproduce

on MacOS

```
new-item -type file file[]file.txt
remove-item -literal file[]file.txt
```
## Expected behavior

file is removed
## Actual behavior

```
PS /tmp/jimtru> remove-item -literalpath file[]file.txt
remove-item : An object at the specified path /tmp/jimtru/file[]file.txt does not exist.
At line:1 char:1
+ remove-item -literalpath file[]file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.RemoveItemCommand
```
## Environment data

```
PS /tmp/jimtru> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Linux
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0
CLRVersion
WSManStackVersion              1.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS /tmp/jimtru> uname -a
Darwin osdev-mac1011-01 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

```

**Comment by SteveL-MSFT** [comment] 2017-03-15 18:42
Dupe of #2799

**Closed by SteveL-MSFT** 2017-03-15 18:42 UTC
Labels: Area-Cmdlets, Resolution-Duplicate
