### ISSUE TITLE
Invoke-RestMethod: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by HppZ** [PowerShell/PowerShell#15322] opened 2021-04-29 11:41 UTC
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.1
`Invoke-RestMethod -Uri https://blogs.msdn.microsoft.com/powershell/feed/`
`Invoke-RestMethod: No connection could be made because the target machine actively refused it.`

pwsh.exe Invoke-RestMethod always fails. but powershell.exe works.

**Comment by 237dmitry** [comment] 2021-04-29 13:29
It works in my environment.
```
 $ (Invoke-RestMethod -Uri https://blogs.msdn.microsoft.com/powershell/feed/).Title
Optimizing your $Profile
Announcing the preview of PSArm
SecretManagement and SecretStore are Generally Available
SecretStore Release Candidate 3
Updating help for the PSReadLine module in Windows PowerShell 5.1
Announcing PSReadLine 2.2-beta.2 with Dynamic help
SecretManagement and SecretStore Release Candidate 2
PowerShell Team 2021 Investments
PowerShell for Visual Studio Code Updates – February 2021
Announcing PowerShell Community Blog

$  $Host.Version.ToString(); $IsLinux  
7.1.3
True
```

**Comment by daxian-dbw** [comment] 2021-05-03 21:42
It works for me too, and I'm running on Windows
```
PS:91> Invoke-RestMethod -Uri https://blogs.msdn.microsoft.com/powershell/feed/

title       : Optimizing your $Profile
link        : https://devblogs.microsoft.com/powershell/optimizing-your-profile/
comments    : {https://devblogs.microsoft.com/powershell/optimizing-your-profile/#comments, 6}
creator     : creator
pubDate     : Tue, 06 Apr 2021 18:55:09 +0000
category    : category
guid        : guid
description : description
encoded     : encoded
commentRss  : https://devblogs.microsoft.com/powershell/optimizing-your-profile/feed/
...
```

@HppZ Since we cannot reproduce the issue, I will close the issue for now.

**Closed by daxian-dbw** 2021-05-03 21:42 UTC
Labels: Needs-Triage

**Comment by helviojunior** [comment] 2024-07-06 05:54
I faced the same issue, in my case was environmet variable called 'HTTP_PROXY'. You can solve that removing this key or passing a -NoProxy parameter.
