### ISSUE TITLE
The concatenation of differently quoted command line arguments splits into multiple argv.

### ISSUE THREAD

**Issue by ArnoCan** [PowerShell/PowerShell#15888] opened 2021-08-08 19:35 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The concatenation of differently quoted string arguments for a command line call is resolved into separate argv entries. 

For example a python one-liner, same for PowerShell scripts etc.
-> Call: C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys;print(sys.argv[1:])" "a"'b'"c"
-> Result: ['a', 'b', 'c']

I would expect these strings to be actually concatenated into one string:
-> Result: ['abc']

As this is the case e.g. for:
-> Call: C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys;print(sys.argv[1:])" "a""b""c"
-> Result: ['abc']

### Expected behavior

```console
PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" "a"'b'"c"
['abc']
```

### Actual behavior

```console
PS C:\temp\PowerShell-7.1.3-win-x64> c:/Python371/python.exe  -c "import sys; print(sys.argv[1:])" "a"'b'"c"
['a', 'b', 'c']
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2021-08-08 20:49
PS supports both single and double quoted string, so I'm not sure this is really unexpected.

Your example has three separate string tokens in it, so they get passed as three separate arguments.

PS's parsing treats " and ' as enclosing characters for strings, and it doesn't support concatenation like this. Three separate strings, three separate arguments.

**Comment by ArnoCan** [comment] 2021-08-09 02:29
See also #15889.
The reason I have to deal with this is that I am currently writing scanner/lexer/tokenizer for command line call strings - for raw input as well as the pre-scanned ARGV. This requires to process the strings exactly - for bash/sh/ksh + PowerShell + DOS/cmd.exe - each with it's own domain of course.

The differently quoted strings are scanned on the first view as three separate string tokens, but they miss a SEPARATOR. The "outer" quotes of a string are commonly dropped from a parsed command line string as these are temporary markers grouping the characters into a string. This would result in three concatenated strings with dropped temporary markers - the quotes. Thus as expected a single concatenated string argument - ARGV entry.

The same example for Posix based shells - bash/sh/ksh. for WSL/Linux:
```
C:\Users\test>wsl python -c "import sys;print(sys.argv[1:])" "a"'b'"c"
['abc']

C:\Users\test>
```
and for native Linux:
```
test:~$ python -c "import sys;print(sys.argv[1:])" "a"'b'"c"
['abc']
test:~$ 
```

**Comment by rjmholt** [comment] 2021-08-12 15:25
Duplicate of #1995

**Closed** 2021-08-13 17:00 UTC
Labels: Resolution-Duplicate, Issue-Question

**Comment by mklement0** [comment] 2021-08-13 19:03
The problem is unrelated to #1995 - it equally affects PowerShell commands.

Instead, it is a specific instance of  #6467 and - on Unix with potentially destructive consequences - #12647

The short of it is that composing a single string argument from a mix of quoting styles - the way you can do in POSIX-like shells such as `bash` - only works in PowerShell _if the first string (or simple variable reference) is UNQUOTED_:

```powershell
# OK - single argument, because the first token is *unquoted*.
PS> Write-Output foo'bar'
foobar

# !! TWO arguments
PS> Write-Output 'bar'foo
bar
foo
```

More info in [this SO answer](https://stackoverflow.com/a/65380907/45375).
