### ISSUE TITLE
Memory leak in Import-PSSession and Remove-Module

### ISSUE THREAD

**Issue by hihayak** [PowerShell/PowerShell#5244] opened 2017-10-26 14:11 UTC
Steps to reproduce
------------------
1. Copy the following PowerShell and edit "My Password" and "My O365 Account" to your own ones.

```powershell
param(
[Parameter(Mandatory=$True)]
[int]$nLoopCount
)

$secPass = ConvertTo-SecureString -AsPlainText "My Password" -Force
$credential = New-Object System.Management.Automation.PSCredential "My O365 Account",$secPass

for ( $i = 0; $i -lt $nLoopCount; $i++ )
{
    "# --------------------"
    "# $i"
    "# --------------------"
    "(1) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $credential -Authentication Basic -AllowRedirection
    "(2) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    $modInfo = Import-PSSession $Session -AllowClobber
    "(3) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    
    Remove-Module -Name $modInfo.Name
    "(4) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    
    Remove-PSSession -Session $Session
    "(5) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64

    $modInfo = $null
    $Session = $null

    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
    [System.GC]::Collect()
} 
```

Expected behavior
-----------------
Memory usage doesn't increase up to infinity.

Actual behavior
---------------
Memory usage keeps increasing.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.674
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.674
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment] 2017-10-27 02:55
@PaulHigin has confirmed there's a memory leak

**Comment by MaximoTrinidad** [comment] 2017-10-31 23:46
This is Windows PowerShell issue and not PowerShell Core. 

This need to be addressed in UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell 

:)

**Comment by PaulHigin** [comment] 2017-11-01 17:35
Actually PowerShell Core does support implicit remoting for both WinRM and SSH transports.  And I am able to repro the memory leak.  It appears that the temporary module created by implicit remoting is not getting fully cleaned up with Remove-Module.

Here is my simpler repro:
```powershell
param (
    [int] $loopCount = 30
)

$cred = Get-Credential -UserName redmond\paulhi -Message "Type Password"

for ($i=0; $i -lt $loopCount; $i++)
{
    "# --------------------"
    "# $i"
    "# --------------------"
    "(1) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    $Session = New-PSSession -Cn localhost -Credential $cred
    "(2) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    $modInfo = Import-PSSession $Session -CommandType Cmdlet -AllowClobber 
    "(3) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64

    Microsoft.PowerShell.Core\Remove-Module $modInfo.Name -Force
    "(4) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
    
    Microsoft.PowerShell.Core\Remove-PSSession -Session $Session
    "(5) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64

    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
    [System.GC]::Collect()

    "(6) {0:N0} Byte" -f [System.Diagnostics.Process]::GetCurrentProcess().PrivateMemorySize64
}
```

**Comment by lzybkr** [comment] 2017-11-01 17:45
30 iterations is insufficient to detect a real leak. There is a cache of script blocks, so in your example, I would expect to see the heap grow. The cache is bounded though, and when the cache is full, we clear it.

I think the cache has 1024 entries - so you'd see growth until at least that many iterations.

**Comment by PaulHigin** [comment] 2017-11-01 18:01
But I am importing almost 300 cmdlets, all of which are wrapped in proxy scripts.  Wouldn't that cause the cache to clear?  Or at least flatten the memory use?  I see continuous growth in heap.

**Comment by lzybkr** [comment] 2017-11-01 18:05
If you're not running each of those proxies, then you're just seeing the ScriptBlock for the module.

**Comment by PaulHigin** [comment] 2017-11-02 16:54
Ok, I do see a leveling off of memory use when I run 2000 iterations and a smaller module scriptblock (only importing 5 cmdlets). So this does look like the scriptblock cache causing the high memory usage.  The high memory is due to importing a huge amount of cmdlets, making the module script very large.  Maybe the scriptblock cache clear heuristic should include memory size as well as count.

**Comment by lzybkr** [comment] 2017-11-02 17:28
If the import generates the same filename and contents, the cache will do it's job - so it's worth investigating why either the filename or contents change on each iteration.

**Comment by PaulHigin** [comment] 2017-11-02 19:45
Import-PSSession creates temporary modules with random filenames.  So each time an import is done of the same endpoint, new scriptblocks are created and cached (keyed by filename).

I suppose we could:
 a. Use a hash to key scriptblocks (possibility of collisions)
 b. Be smarter about clearing the cache and remoting temporary module files that are no longer imported into the session.

**Comment by lzybkr** [comment] 2017-11-02 19:57
I would use an algorithm that generates reproducible filenames based on the string content or something else.

The filename is an important part of the key to the cache - e.g. error messages use position information encoded in the script block which in turn refer to the file.

**Comment by caoko** [comment] 2022-05-03 03:41
try this...

```powershell
[System.Management.Automation.ScriptBlock].GetMethod('ClearScriptBlockCache', [System.Reflection.BindingFlags]'Static,NonPublic').Invoke($null, $null)
```

**Closed** 2023-11-23 13:34 UTC
Labels: Issue-Bug, Resolution-No Activity
