### ISSUE TITLE
PSRP over WSMan/WinRM from Linux/OSX to Windows

### ISSUE THREAD

**Issue by mklemm2** [PowerShell/PowerShell#1883] opened 2016-08-18 17:04 UTC
I looked around for about an hour but did not find a clear statement on this. So I thought I just ask: Does Powershell for Linux and OSX have the ability to execute a command on a remote Windows machine without installing Microsoft's SSH server on that machine? Or is it PSRP-over-SSH only?

Thanks, Marcus

**Comment by dombarnes** [comment] 2016-08-18 19:06
I just attempted  
````  
Invoke-Command -ComputerName IP.ADD.RE.SS -ScriptBlock { $env:computername } -credential administrator
````
 and it prompted for password and then it crashed   
````  
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Clear()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.Finalize()
Abort trap: 6
````

So..in theory yes?

**Comment by m-hodgkins** [comment] 2016-08-18 19:07
Same issue from MacOS

<img width="884" alt="screen shot 2016-08-18 at 8 57 05 pm" src="https://cloud.githubusercontent.com/assets/19345722/17787034/c6d65ad8-6587-11e6-8de1-4ec73eae768d.png">

**Comment by andschwa** [comment] 2016-08-18 19:48
Server side (Windows to Linux) is supported! See the OMI provider https://github.com/PowerShell/psl-omi-provider.

/cc @paulcallen

**Comment by mklemm2** [comment] 2016-08-19 02:51
On OSX, I get:

`PS /> Invoke-command -cn winhop1.test.dev -authentication negotiate -credential (Get-Credential) -command {hostname}

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
User: vagrant
Password for user vagrant: *******

Invoke-command : Unable to load DLL 'libpsrpclient': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
At line:1 char:1
+ Invoke-command -cn winhop1.test.dev -authentication negotiate -c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Command], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.InvokeCommandCommand`

**Comment by andschwa** [comment] 2016-08-19 03:04
Thanks for trying! Client side remoting (*nix to Windows) is in progress :smile:

**Comment by andschwa** [comment] 2016-09-19 22:07
Just echoing because I'm closing a bunch of these issues:

Per the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support), this is **not yet supported**.  Please follow the progress on the [PSRP on Linux repo](https://github.com/PowerShell/psl-omi-provider). Closing as duplicate of #942.

**Closed by andschwa** 2016-09-19 22:07 UTC
Labels: Area-Remoting, Issue-Question

**Comment by jkonstas** [comment] 2017-10-09 02:04
My command still fails is there a fix Mac->Windows ?
PS /Users/ikonstas> New-PSSession -ComputerName 10.178.228.100 -Credential administrator                       

PowerShell credential request
Enter your credentials.
Password for user administrator: ****************

New-PSSession : MI_RESULT_ACCESS_DENIED
At line:1 char:1
+ New-PSSession -ComputerName 10.178.228.100 -Credential administrator
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-PSSession], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.NewPSSessionCommand

**Comment by SteveL-MSFT** [comment] 2017-10-09 16:04
@jkonstas I believe Mac->Windows currently only supports using Basic auth.
