### ISSUE TITLE
Issue processing thoughts

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#9563] opened 2019-05-08 16:17 UTC
As a PowerShell contributor, I have a thought about bug/enhancement processing.

Today the process seems to be:
1. Identify a bug or an enhancement for PowerShell.
1. Have optional discussion about that bug or enhancement in the related Issue page.
1. Submit a PR that addresses the issue. In submitting the PR, you can write tests first or write code first, but if it can be automatically tested, tests must be included in the PR.

One part of this process that seems to be lacking is visibility into the relationships that your issue/PR may have with other open issues. There are ~1900 open issues at the time of this writing. We have maintainers who will add comments to an issue, referencing other related issues, but that's manual and some relationships may be missed. Also, when we add Pester tests, there are no references for those tests back to the issues they were designed to identify and confirm fixed, so if they then break in the future, intentionally or otherwise, and you want visibility into the discussion around the related issues, that information isn't readily available to you.

After having gone through this process a decent number of times, I find myself wondering if it would be better if:

1. The form for submitting new bugs recommends that the reproduction code be written as a one or more Pester tests if users know Pester already (not requiring it though, to keep the barrier to posting an issue as low as possible).
1. Once bugs are confirmed, if the Issue does not have an associated Pester test already, add a label indicating Pester tests are needed.
1. Once bugs are confirmed and Pester tests are ready, add them to the repo via a PR, with the Issue numbers used as tags for the tests.

    > **Aside**: Today in Pester you can tag on Describe, but not on It -- it may be beneficial to be able to do more granular tagging on It so that Describe can be used to group a set of related tests while still allowing individual tests to be associated with GitHub issues, and if that is desirable we may need to request a fix or submit a PR for Pester.

1. When the CI/CD pipeline runs Pester tests, tests associated with open issues are ignored unless they are specifically related (tagged) to that PR.
1. As an additional background build step (not required for success), tests associated with open issues that are not also associated to the PR are run so that PR authors can identify other related tests (and therefore issues) that are impacted by their changes, and tag them so that they are associated with the PR as well.

The end goals behind these ideas are:

1. To increase visibility between related issues without having to scour through the issue discussion and/or manually add a reference between issues as part of that discussion.
1. To identify all issues that are either partially or fully addressed when a PR is merged, ensuring that all open issues are actually still open issues.
1. To accurately report all issues that are fixed in product releases.
1. To encourage TDD, ensuring that issues are reproducible on a machine before they are fixed and facilitating the verification of those issues once they are fixed.

Thoughts?

**Comment by SteveL-MSFT** [comment] 2019-05-10 05:33
I like the idea and intent, but not sure how well this will work in practice.  Part of the problem is for CI/CD to be aware of GitHub issues, we'd have to have a wrapper to skip the tests by querying GitHub at runtime.  Although doable, this will hit GitHub API throttling issues unless we use someone's personal access token.

I do like the idea of submitting bug reports as Pester tests and a few people actually do this, but I suspect the number of people able to author Pester tests (let along good Pester tests) is extremely small compared to the total number of folks reporting issues.  I think if regular contributors start doing this leading by example, we may see more of it happening.

**Comment by KirkMunro** [comment] 2019-05-10 15:57
Good point. Maybe a better way to separate tests expected to be working from tests for open issues is to physically separate them then, in separate paths. Then CI/CD wouldn't have to query GitHub at all. It would only care if the tests in the "expected working path" passed, and the result of other tests would be purely informational.

**Comment by adityapatwardhan** [comment] 2019-05-10 16:43
Another way this can be achieved is by using `Set-ItResult` - [docs](https://github.com/pester/Pester/wiki/Set%E2%80%90ItResult)

```PowerShell

Describe "Help system tests" {
  It 'Valid test' {
    Get-Help | Should -Not -BeNullOrEmpty
  }
  
  It 'New-Cmdlet test' {
    Set-ItResult -Inconclusive -Because 'New-Cmdlet is not implemented yet' 
    Get-Help New-Cmdlet | Should -Not -BeNullOrEmpty
  }
}
```
The output will be like: 

```
Describing Help system tests
  [+] Valid test 72ms
  [?] New-Cmdlet test, is inconclusive, because New-Cmdlet is not implemented yet 15ms
```

**Comment by iSazonov** [comment] 2019-05-12 16:38
Currently such tests is marked as "pending" in our code base.

**Closed** 2023-11-23 12:45 UTC
Labels: Issue-Enhancement, Resolution-No Activity
