### ISSUE TITLE
Start-Process test for stdin redirection fails only on AppVeyor daily builds

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#2396] opened 2016-09-30 21:25 UTC
## Steps to reproduce

Execute tests in AppVeyor daily builds. The test https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1#L66 fails. 
## Expected behavior

Test should pass.
## Actual behavior

The test fails as the output file is not generated.
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSEdition                      Core
CLRVersion
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.10-98-g877c193af0ea79f8b3e15528aeb144fef9305305-dirty
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
```

**Comment by vors** [comment] 2016-09-30 23:26
This is duplicate of #2394

**Comment by joeyaiello** [comment] 2017-05-25 18:41
Closing as a dupe

**Closed by joeyaiello** 2017-05-25 18:41 UTC
Labels: Area-Test, Resolution-Duplicate
