### ISSUE TITLE
Add support for OS check to the #requires statement

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3751] opened 2017-05-10 08:46 UTC
PowerShell Core is a cross-platform, so it makes sense to add support for operating system check to the #requires statement in case you want to write an OS-specific script.

**Comment by MaximoTrinidad** [comment] 2017-05-10 22:34
Hum!! I'm using the isXXXX variables to identify which OS I want the code to execute.  It won't hurt to implement another #REQUIRES -OS option. 

:)

**Comment by SteveL-MSFT** [comment] 2017-05-11 18:54
Benefit of `#requires` is that it's a parse time check and not runtime if the entire script is not compatible vs using $isWindows, etc...

**Comment by joeyaiello** [comment] 2017-05-17 23:23
I'm writing an RFC right to discuss platform differences. For the time being, I think it's a perfectly usable workaround to throw at the beginning of a psm1 if !isLinux.

**Comment by joeyaiello** [comment] 2017-08-22 21:43
Reminder here to discuss with @PowerShell/powershell-committee the possibility of pushing this out. No immediate need (certainly not moreso than the "interop" variables), and this should be done with intent.

**Comment by SteveL-MSFT** [comment] 2017-09-06 23:33
@PowerShell/powershell-committee reviewed this and agree that this isn't needed for 6.0.0, we'll revisit the necessity at all post 6.0.0

**Comment by rjmholt** [comment] 2018-03-23 18:34
I've opened [an RFC](https://github.com/PowerShell/PowerShell-RFC/pull/122) on updating the behaviour of `#requires`. Please feel free to comment in the PR.

**Comment by tnieto88** [comment] 2019-05-31 18:43
@joeyaiello Can this enhancement be included with PS 7?

**Comment by rjmholt** [comment] 2019-05-31 19:10
This has been accepted in https://github.com/PowerShell/PowerShell-RFC/pull/122

Now it just needs to be implemented

**Comment by iSazonov** [comment] 2019-06-03 06:48
I think we would be great to have a meta issue with not implemented RFCs.

**Comment by rjmholt** [comment] 2019-06-03 15:48
> I think we would be great to have a meta issue with not implemented RFCs.

We should discuss with @SteveL-MSFT and @joeyaiello, but I do keep feeling that RFCs don't integrate well with issue tracking for us.

I think meta issues tend to get neglected and aren't very helpful compared to a 1-issue-per-workitem approach and tagging. So my suggestion would be:

- When RFCs are accepted, they are linked to the appropriate issue in the relevant repository and the issue is tagged as implementing an RFC
- Then, when the issue is closed as implemented, the RFC is moved to implemented

**Comment by iSazonov** [comment] 2019-06-03 17:42
In the case we need one issue in RFC repo to track implementing and there can be some related issues and PRs in the repo.

**Comment by SteveL-MSFT** [comment] 2019-06-05 11:04
Perhaps instead of a meta issue that itself is additional work to maintain, we should have a `RFC Approved, Waiting on Implementation` type label (but shorter) in this repo and have the ability to render a view of RFCs based on filtering criteria (we already need it for other purposes).

**Comment by iSazonov** [comment] 2019-06-05 11:42
In the case we need to create an issue to apply the label.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-06-30 10:40
As @SteveL-MSFT [states](https://github.com/PowerShell/PowerShell/issues/3751#issuecomment-300883997), why is this necessary? An initial `If` condition is perfect.

**Closed** 2023-11-24 00:44 UTC
Labels: Issue-Enhancement, WG-Language, Up-for-Grabs, Committee-Reviewed, Resolution-No Activity
