### ISSUE TITLE
Cannot Connect to Office 365 Exchange 2016 via terminal in 10.15.1 (Catalina)

### ISSUE THREAD

**Issue by Zebzx** [PowerShell/PowerShell#11188] opened 2019-11-25 11:35 UTC
Hello,

I am experiencing the below error.

New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system

This is not representative of the issue resolved and closed in issue #5561 

I have the below version of Powershell installed currently

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.4                                           
PSEdition                      Core                                            
GitCommitId                    v6.0.4                                          
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: T...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0              

Thanks in advance.

**Comment by vexx32** [comment] 2019-11-25 11:59
The most current stable version of PowerShell is 6.2.3. I'd recommend updating at least to that version, and if this issue isn't fixed there, do please try the latest v7-preview, as this issue may have already been resolved. 🙂

**Comment by Zebzx** [comment] 2019-11-25 12:00
Sadly, I anticipated this and updated in advance but sadly have the same result.

Name                           Value     
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by xaoseric** [comment] 2019-11-26 19:44
can also confirm I am receiving this error on macOS High Sierra and Catalina as well.

**Comment by Zebzx** [comment] 2019-11-26 20:02
Just to continue on the thread for this issue. I have since reinstalled my OS to a fresh Catalina build with the same issue present.

I am only able to SSH to a server in order to have it running and stable.

I’d really appreciate a fix on this as soon as.

**Comment by xaoseric** [comment] 2019-11-26 20:03
I saw that it was working on 6.0.2 of powershell, perhaps something changed that caused it to break on macOS?

**Comment by renatocalderani** [comment] 2019-11-28 09:13
Same issue here, 

macOS Catalina v10.15.1
PSVersion 6.2.3

I just thought, I would contact Microsoft support (who knows maybe they could help?) and this was their reply hahahaha
"Unfortunately, there is no such option where we can make the PowerShell work on MacOS terminal, that I am aware of."

**Comment by hampsink** [comment] 2019-12-05 14:28
> Sadly, I anticipated this and updated in advance but sadly have the same result.
> 
> Name Value
> 
> PSVersion 6.2.3
> PSEdition Core
> GitCommitId 6.2.3
> OS Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu…
> Platform Unix
> PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion 2.3
> SerializationVersion 1.1.0.1
> WSManStackVersion 3.0

I have the same error, same version of powershell on Mac 10.15.1 when trying to connect to Office 365

**Comment by THEWaltmanno** [comment] 2019-12-05 22:57
Also having this issue with the following installed:

Mac OS  10.15.1

PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

error:

New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

**Comment by joshnck** [comment] 2019-12-09 18:47
```
 $session=New-PSSession -Configuration Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $cred -Authentication Basic -AllowRedirection
New-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```

```
$psversiontable 

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by scottnursten** [comment] 2019-12-10 18:08
Same here: 

New-PSSession
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
At line:1 char:1

**Comment by overflower83** [comment] 2019-12-21 19:09
I can confirm that I have the same issue. Tried pwsh and pwsh-preview
```
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0```

**Comment by tthoma24** [comment] 2019-12-23 20:02
I believe this is a dupe of #10600

**Comment by tthoma24** [comment] 2019-12-23 20:29
I was able to get the CLI working on macOS 10.15 by symlinking to system provided libssl and libcrypto in /usr/lib/libssl.dylib and /usr/lib/libcrypto.dylib.

I suspect there are really two issues here:

1. pwsh (specifically libmi.dylib) expects OpenSSL to be provided by Homebrew in the Homebrew location /usr/local/opt/openssl/lib/
2. pwsh is expecting an older version of OpenSSL that has the " _SSL_library_init" symbol in it, so linking to a newer version from Homebrew, MacPorts, or hand-compiled doesn't work as it should, yielding the following error:

dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /usr/local/microsoft/powershell/6/libmi.dylib
  Expected in: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib


Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Sun Dec  8 22:27:29 PST 2019; root:xnu-6153.80.8.0.1~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by JigSawFr** [comment] 2019-12-24 09:08
Same problem too... unable to use PWSH for Office 365.
```
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by klamberth27** [comment] 2019-12-24 19:45
Same here.  Tried every combo.  
New-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

**Comment by slabber** [comment] 2020-01-06 08:57
The issue here is that Homebrew has removed openssl 1.0 here https://github.com/Homebrew/homebrew-core/pull/46876/commits/5c3de7dd7c1eec7ed10b6456510163895c397201

With powershell looking explicitly for the 1.0 version here
```
otool -L /usr/local/microsoft/powershell/6/libmi.dylib
/usr/local/microsoft/powershell/6/libmi.dylib:
	@rpath/libmi.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/lib/libpam.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
```

The workaround for me at the moment is to revert homebrew to 1.0
```brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/64555220bfbf4a25598523c2e4d3a232560eaad7/Formula/openssl.rb```

and copy the dylib files from /usr/local/opt/openssl/lib to a temporary location before re-installing homebrew openssl and moving the files back to /usr/local/opt/openssl/lib

**Comment by richbarfoot** [comment] 2020-01-06 14:46
@slabber Thank you for posting this work-around. It worked great for me and got me back up and running.

**Comment by hampsink** [comment] 2020-01-06 15:42
How can I revert to homebrew openssl 1.0 ?
I have installed openssl 1.1 and it is refusing to uninstall openssl

**Comment by slabber** [comment] 2020-01-08 13:58
@hampsink See the comment above.

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/64555220bfbf4a25598523c2e4d3a232560eaad7/Formula/openssl.rb`

should replace OpenSSL 1.1 with 1.0 on homebrew

**Comment by Jeralckx** [comment] 2020-01-08 14:25
Hey @slabber , thanks for the suggested workaround. 

What do you mean by "re-installing homebrew openssl"? Is that the newest 1.1 version? Is it really necessary to copy the 1.0 dylib files and copy them back, instead of just trying with the reverted openssl version?

**Comment by slabber** [comment] 2020-01-08 14:32
@Jeralckx I've not investigated this but my concern is that the workaround could break any other packages that have openssl 1.1 as a dependency.  That's why I suggest re-installing it back again once you have the necessary files you need to satisfy the powershell dependency on 1.0

Just FYI, I'm connecting using an application credential created here:
[https://account.activedirectory.windowsazure.com/AppPasswords.aspx](https://account.activedirectory.windowsazure.com/AppPasswords.aspx)

And then with the following commands
```
$secpasswd = ConvertTo-SecureString "<pass from above>" -AsPlainText -Force
$UserCredential = New-Object System.Management.Automation.PSCredential ("user@example.com", $secpasswd)
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session
```

**Comment by Jeralckx** [comment] 2020-01-08 14:56
Too bad, it's still throwing the same error notice regarding WSMan, even after having a go with your workaround @slabber ... 

```
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerShell.Commands.NewPSSessionCommand
```
@richbarfoot Seems like you got it working? Any ideas?
Thanks!

**Comment by hampsink** [comment] 2020-01-09 11:54
> @hampsink See the comment above.
> 
> `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/64555220bfbf4a25598523c2e4d3a232560eaad7/Formula/openssl.rb`
> 
> should replace OpenSSL 1.1 with 1.0 on homebrew

@slabber 
When I run the command, it stops with :

Error: openssl 1.1.1d is already installed
To upgrade to 1.0.2t, run `brew upgrade openssl`

And when I do that it still says 'Warning: openssl 1.1.1d already installed'

**Comment by hampsink** [comment] 2020-01-09 12:17
@slabber 
It worked for me with **brew upgrade https://raw.githubusercontent.com/Homebrew/homebrew-core/64555220bfbf4a25598523c2e4d3a232560eaad7/Formula/openssl.rb**

But then I get the same kind of error like @Jeralckx 
And maybe that is because I forgot to backup and copy back the dylib files.... ?

Is there another way to get the dylib files ?

**Comment by hampsink** [comment] 2020-01-09 12:41
Now I am also back at the WSMan error again...

**Comment by maeck** [comment] 2020-02-24 12:00
Is there a solution yet? 
I run into the same error on MacOS 10.15.3

**Comment by slabber** [comment] 2020-02-24 12:18
@maeck Did you try the workaround above of reverting openssl homebrew to 1.0, saving the dylib files somewhere, reinstalling openssl 1.1 and copying the dylib files back again?  The following files MUST exist.  It's best to follow the working whilst not being in the /usr/local/opt/openssl folder as I think homebrew completely removes the folder during upgrade/install/reinstall.

```
/usr/local/opt/openssl/lib/libssl.1.0.0.dylib
/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
```

**Comment by slabber** [comment] 2020-03-05 08:26
Still broken in powershell 7.0

**Comment by maeck** [comment] 2020-03-05 10:29
@slabber Yes, it works. Also with Pwsh v7. Thank you very much.
Now I need only to wait for the cmdlets for O365 to create users, mailboxes, etc.

**Comment by luckman212** [comment] 2020-04-07 22:31
Here's a hack that's working for me for now, until pwsh is updated to be compatible with openssl1.1+ or removes the dependency on WSMan:
```
brew install https://github.com/luckman212/openssl10/releases/download/1.0.2u/openssl@1.0.rb
rm /usr/local/opt/openssl
ln -s /usr/local/Cellar/openssl@1.0/1.0.2u /usr/local/opt/openssl
```

**Comment by iSazonov** [comment] 2020-05-08 12:10
@PaulHigin What is right resolution here? WinRM deprecated?

**Comment by Jeralckx** [comment] 2020-07-24 10:27
Guys, any news yet? Still no working solution for me... 

@slabber I get the error notice saying I can't sign in to office365. Even after correctly reinstalling openssl and copying the dylib files.

Then I tried @luckman212 's workaround, but still no luck... Same error. 

Any suggestions on how to proceed? 

Thanks again!

**Comment by iSazonov** [comment] 2020-07-24 18:12
@Jeralckx It seems there is a beta module for Cloud Exchange which should be compatible with PowerShell Core.

**Comment by luckman212** [comment] 2020-07-24 19:38
@iSazonov Do you have any links for that module?

**Comment by iSazonov** [comment] 2020-07-25 18:16
@luckman212 No. It seems it was a tweet a week ago. And it is seem not open beta. You could ask Exchange team.

**Closed** 2020-07-27 00:00 UTC
Labels: Issue-Question, Resolution-Answered

**Comment by luckman212** [comment] 2020-07-28 00:32
Why did this issue get closed? Is there a way to connect to Exchange Online now on pwsh core on macOS?

**Comment by iSazonov** [comment] 2020-07-28 04:33
It is an external issue - now Enchange team works on beta Exchange Online module compatible with PowerShell Core.

**Comment by GCHPX** [comment] 2020-11-25 10:01
This issue still exists with MacOS BigSur.  Is there a workaround or even a solution ?

**Comment by viniciusferrao** [comment] 2020-12-17 04:13
> It is an external issue - now Enchange team works on beta Exchange Online module compatible with PowerShell Core.

There's a preview release for this? Any information?

**Comment by iSazonov** [comment] 2020-12-17 04:50
@viniciusferrao See docs https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#powershell-core-support-in-the-exo-v2-module

**Comment by viniciusferrao** [comment] 2020-12-17 04:53
> @viniciusferrao See docs https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#powershell-core-support-in-the-exo-v2-module
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0f67595c301739c467733e670e036897181dae5cea0e9d7f7fa2f3f4a79a5fba/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f656e2d75732f6d656469612f6c6f676f732f6c6f676f2d6d732d736f6369616c2e706e67">**[About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2)**Admins can learn about the installation, maintenance, and design of the Exchange Online PowerShell V2 module that they use to connect to all Exchange-related PowerShell environments in Microsoft 365.

This seems to be Windows only...

```
New-ExoPSSession: /Users/ferrao/.local/share/powershell/Modules/ExchangeOnlineManagement/2.0.3/ExchangeOnlineManagement.psm1:426
Line |
 426 |  … PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral,
     | PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified. .
```

**Comment by luckman212** [comment] 2020-12-17 04:59
@iSazonov From the docs page you linked:

> Notes: PowerShell 7 in MacOS is not supported.

**Comment by iSazonov** [comment] 2020-12-17 16:08
You need to communicate with Exchange Server team to request the support.

**Comment by viniciusferrao** [comment] 2020-12-17 16:16
> You need to communicate with Exchange Server team to request the support.

Sazonov, are you working with Microsoft? If yes can you provide the proper location to open the RFE (Request for Enhancement)? Because it's really confusion for us where we should report/open issues for defects or features.

This one for me is a bug/defect/deprecated without notice feature.

Thanks.

**Comment by iSazonov** [comment] 2020-12-17 16:31
> Sazonov, are you working with Microsoft?

No, I am a community member like you.

> If yes can you provide the proper location to open the RFE (Request for Enhancement)?

You can use MSFT forums, UserVoice site, MSFT support from your enterprise contract.
You can find men with MVP status (Office 365 MVP) who could communicate with the team directly.
I know the team is very conservative so you need to have very important business scenario for them to do it.

**Comment by JeremyHargis** [comment] 2021-02-11 18:32
According to [this link](https://techcommunity.microsoft.com/t5/exchange-team-blog/exo-v2-powershell-module-is-now-generally-available-on-linux-amp/ba-p/2121811#.YCVSRagQ7RU.twitter), this is supposed to work on MacOS as of today. I installed the module fresh and I'm getting the "no supported WSMan client library was found." Seems like this shouldn't require a workaround anymore since it's an officially supported scenario.

**Comment by kyanar** [comment] 2021-02-21 00:19
This issue shouldn't be closed. The cause of the issue is nothing to do with Exchange Online, and everything to do with the fact PowerShell WSMan demands an out of date version of OpenSSL. Simply using New-PSSession with a remote target at all fails with the exact same error, despite using only PowerShell Core modules.

**Comment by slabber** [comment] 2021-02-21 07:19
I really wish someone at Microsoft would sit up and pay attention to this.  Bugs have been reported in Powershell Core, EXO and OMI if I'm not mistaken.

And then we see new versions being reported as MacOS compatible.  It's as if they are not testing their software on fresh installs of MacOS and have an old version of OpenSSL on their system.

I've tested the latest versions and still the EXO module relies on WSMan and WSMan in powershell core is still broken because libmi.dylib references openssl 1.0 that was removed by homebrew.

Anyway, some bright spark has resolved this with a much better workaround than using openssl 1.0 libraries:
https://github.com/jborean93/omi

Install his replacement

```
Install-Module -Name PSWSMan

# Requires root access to install, Install-WSMan can be run directly if already running as root
sudo pwsh -Command 'Install-WSMan'
```

Restart powershell and for me it works just fine.  Now if only MS would fix it upstream :-(
