### ISSUE TITLE
Powershell Core deserializes numbers in JSON as Int64 vs Windows Powershell which does it as Int32

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#14264] opened 2020-11-25 14:39 UTC
This is actually a copy of the StackOverflow issue with the same name from [@Mark](https://stackoverflow.com/users/80002/mark):
[Powershell Core deserializes numbers in JSON as Int64 vs Windows Powershell which does it as Int32](https://stackoverflow.com/q/64930079/1701026)

## Steps to reproduce

```PowerShell
$a = "1" | ConvertFrom-Json
(@{ $a = 2 }).1
```

## Expected behavior

Return `2` (just like Windows PowerShell 5)

## Actual behavior

Returns nothing (because the actual key is of type `[Int64]` and the key ".`1`" of type `[Int32]`)

I am not sure whether this can be called a bug or  is "by design" but my expectation (from a dynamically typed language as  PowerShell Core) is that a Json number (less then `[int]::MaxValue`) should default to an `[Int32]` type, just like:

```PowerShell
$a = 1
$a.GetType().Name
Int32
```

## Workarround

Recast the number:

```PowerShell
$a = "1" | ConvertFrom-Json
$a = 0 + "$a"
(@{ $a = 2 }).1
2
```

**related:** 

- [#9207 convertto-json bigint is not properly serialized](https://github.com/PowerShell/PowerShell/issues/9207)
- [Make Newtonsoft JsonConvert Default to Int32 Rather Than Int64](https://stackoverflow.com/a/44010307/1701026)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2020-11-26 16:14
Certainly a pitfall; perhaps to be revisited in the context of moving to the new `System.Text.JSON` APIs - see #11198.

Simpler workarounds: `@{ $a = 2 }.1l` or `@{ $a = 2 }[1l]` or `@{ $a = 2 }[[long] 1]`

**Comment by iRon7** [comment] 2020-11-26 17:53
@mklement0 , using those suggested simpler *static* type workarounds will cause another pitfall as that will mean that the same script (that works in PowerShell 7) will break in the older PowerShell versions.
In other words:
```PowerShell
$a = "1" | ConvertFrom-Json
(@{ $a = 2 }).1l
```
Works in PowerShell Core but not in Windows PowerShell

**Comment by mklement0** [comment] 2020-11-26 18:18
@iRon7, yes, though at least in your example `$a = [long] 1; @{ [int] $a = 2 }.1` should do as a workaround.

**Comment by jhoneill** [comment] 2020-11-27 08:58
> Certainly a pitfall; perhaps to be revisited in the context of moving to the new `System.Text.JSON` APIs - see #11198.
> 
> Simpler workarounds: `@{ $a = 2 }.1l` or `@{ $a = 2 }[1l]` or `@{ $a = 2 }[[long] 1]`



I think a lot of people have been caught by the issue of "This key in the hash table is a value type, but not the same value type as ...".  So 2 might be a floating point number, or a variety of integer and IIRC  even a char "a" and a string "a" 

```
$x = [char]65
$hash = @{$x = "aaa"}
>$x -eq "A 
true 

> $hash["A"]

>
```
That's because of the way a hash table is **not** doing `for each k in Keys` and it would be useless if it did.  


> @iRon7, yes, though at least in your example `$a = [long] 1; @{ [int] $a = 2 }.1` should do as a _cross-edition_ workaround.

I have had to use this in a couple of places both putting the key/value in and getting things back. And it was painful to learn. 

That's subtly different from   
 "This conversion from to / from  text serialization format changes type X to type Y". I think if you had an int64 or int32 in PS5 and sent them to json and got them back they became int32 and a  `1` is an int32 by default and "a" is a string by default. 

Now they come back as int64 - I suspect to avoid a test to say "Does this need to be an int64 ?"   This may be something inherited from .net but _anything_ which assumes `1` read from a json file being the same kind of `1` as the `1` in `$x = 1`  - which tbh is a pretty easy assumption to make - is going to hit trouble. 
By the same logic we don't want a json converter seeing "y" and converting it to a char instead of a string,.

**Comment by mklement0** [comment] 2020-11-27 16:10
> "This conversion from to / from text serialization format changes type X to type Y"

The problem is that JSON is an invariably "lossy" serialization format with .NET types as the input.
You lose the specific number types, as any number in JSON becomes that abstraction: a JSON primitive of kind `Number`.
Similarly, JSON has no `[char]` type, only `String`.

Therefore, no one should expect a round trip to work.

However, it _is_ reasonable to expect from-JSON conversion to expect _PowerShell-typical_ behavior, which to me means performing the automatic type-widening _as needed_, the same way that (non-type-letter-suffixed) _number literals_ in PowerShell source code employ, which means: `[int]` as the smallest type -> `[long]` -> `[decimal]` -> `[double]`.

(On a related note: going from `[decimal]` to  `[bigint]`  before going to `[double]` in number-literal parsing would make sense, to avoid quiet loss of accuracy - see #13212; by contrast, `ConvertFrom-Json` in PS Core currently skips the `[decimal]` step and goes straight from `[long]` to `[bigint]` - see https://github.com/PowerShell/PowerShell/issues/9207#issuecomment-573992565).

>  I suspect to avoid a test to say "Does this need to be an int64 ?

Yes, as implied by a quote of the author of the Json.NET library underlying the current `ConvertFrom-Json` from the [SO answer that @iRon7 links to in the OP](https://stackoverflow.com/a/44010307/45375):

> Json.NET by default reads integer values as Int64 because there is no way to know whether the value should be Int32 or Int64, and Int64 is less likely to overflow. For a typed property the deserializer knows to convert the Int64 to a Int32 but because your property is untyped you are getting an Int64.

**Comment by LaurentDardenne** [comment] 2022-08-15 10:39
The use of
```powershell
   ...|Convert-From | Group-Object -Property XYZ -AsHashTable
```
may in some cases require an adaptation of the code depending on the version of powershell.

Example :
```powershell
$Runs=( gh api -H "Accept: application/vnd.github+json" /repos/OWNER/REPO/actions/runs|ConvertFrom-Json).workflow_runs|
     Group-Object workflow_id -AsHashTable

$List=$runs.GetEnumerator()|% {$_}
$List[0].Key.GetType()
```
If I have to search for a key, from a cast of a string, the code differs.
```powershell
$id='1234'

#v5.1
$runs.ContainsKey($id -as [int32])

#Core
$runs.ContainsKey($id -as [int64])
```
Shouldn't this post be marked as 'Breaking change' ?

**Comment by iRon7** [comment] 2023-11-16 14:25
The still exists:

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Please either mark this issue with something like <kbd>Resolution-Declined</kbd> or put it on a kind of <kbd>wishlist</kbd> "[*Issue we would like to prioritize, but we can't commit we will get to it yet*](https://github.com/dotnet/runtime/labels?q=wishlist)

**Comment by rifuller** [comment] 2024-01-03 01:37
This is still a problem.

Repro

```ps1
[bigint]"93839802329326" | ConvertTo-Json
```

Expected:
```ps1
93839802329326
```

Actual
```ps1
{
    "IsPowerOfTwo":  false,
    "IsZero":  false,
    "IsOne":  false,
    "IsEven":  true,
    "Sign":  1
}
```

**Closed** 2024-07-08 19:54 UTC
Labels: Issue-Question, WG-Cmdlets-Utility, Resolution-No Activity

**Comment by LaurentDardenne** [comment] 2024-07-08 20:53
Completed ? How ?

**Comment by JimbobSquelchy** [comment] 2024-07-08 20:58
> Completed ? How ?

I was thinking exactly the same thing...!!!

**Comment by LaurentDardenne** [comment] 2024-07-08 21:30
The bot says 'Resolution-No Activity' but it is the inactivity of the team that is concerned here, not that of the users.

Our activity is to confirm a correction, unless we need to correct the bugs we find.

At worst indicate 'Up-for-Grabs'...

That said without animosity :-)

**Comment by argium** [comment] 2024-07-08 23:25
> Completed ? How ?

Automatically, I think? 😂
