### ISSUE TITLE
Output cutoff at 74 chars per line

### ISSUE THREAD

**Issue by phrohdoh** [PowerShell/PowerShell#1912] opened 2016-08-18 21:32 UTC
OS X
## Steps to reproduce

```
PS /Users/thill/projects/work> Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 5
```
## Expected behavior

No maximum line length.
## Actual behavior

Evidence of lines being cutoff:

```
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                                      
-------  ------    -----      -----     ------     --  -- -----------                                                                                                                                      
      0       0        0     756156 ...127.183  12881   1 plugin-containe                                                                                                                                  
      0       0        0     738004 ...219.210  12879   1 firefox                                                                                                                                          
      0       0        0     160060 37,618.788  38707   1 Microsoft Remot                                                                                                                                  
      0       0        0      77596  6,914.063  12899   1 iTerm                                                                                                                                            
      0       0        0      19852  2,687.954    313   1 Flux                                                                                                                                             
```
## Environment data

``` powershell
> $PSVersionTable

Name                           Value                                                                                                                                                                       
----                           -----                                                                                                                                                                       
PSVersion                      6.0.0-alpha                                                                                                                                                                 
PSEdition                      Core                                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                     
BuildVersion                   3.0.0.0                                                                                                                                                                     
GitCommitId                    v6.0.0-alpha.9                                                                                                                                                              
CLRVersion                                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                         
SerializationVersion           1.1.0.1
```

**Comment by lzybkr** [comment] 2016-08-18 23:00
PowerShell asks the host how wide the display is and does formatting to fit that width.

This is normally what people want when the output is sent to the screen, otherwise tables might look bad.

If your issue is that the truncation happens when writing to a file - then I agree this is something we should fix.

**Comment by crypticgeek** [comment] 2016-08-18 23:32
I don't think this is a bug. This is just how Powershell tables work. Similar fields will be truncated on Windows, regardless of the window width. Try Format-Table.

```
PS> Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 5 | Format-Table                    

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                   
-------  ------    -----      -----     ------     --  -- -----------                                                                   
      0       0        0    3853192 ...104.693  16063   1 prl_vm_app                                                                    
      0       0        0     438936 ...179.407    670   1 Google Chrome                                                                 
      0       0        0      70932 ...150.444    676 676 VTDecoderXPCSer                                                               
      0       0        0      92120 ...417.235    675   1 Google Chrome H                                                               
      0       0        0      64508 ...452.274   1150   1 Dropbox                                                                       


PS> Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 5 | Format-Table -AutoSize          

Handles NPM(K) PM(K)   WS(K)        CPU(s)    Id  SI ProcessName    
------- ------ -----   -----        ------    --  -- -----------    
      0      0     0 3853192 2,445,139.277 16063   1 prl_vm_app     
      0      0     0  438936 2,408,189.629   670   1 Google Chrome  
      0      0     0   70752 2,233,173.934   676 676 VTDecoderXPCSer
      0      0     0   92120 1,863,433.605   675   1 Google Chrome H
      0      0     0   64508   490,453.083  1150   1 Dropbox     

```

**Comment by lzybkr** [comment] 2016-08-18 23:57
Good point - I didn't look closely at the output.

We've been tweaking the fixed column widths for the Get-Process output.  It might make sense to adjust those some more so there is no truncation in the CPU column.

**Comment by doctordns** [comment] 2022-04-03 11:59
This is by design. PowerShell like Windows PowerShell uses display XML to guide the formatting ((although the XML is 'inside' the cmdlets rather than a separate XML file as with Windows PowerShell. You can see what PowerShell 7 thinkls:

```powershell
PSH [C:\Foo]: $f = Get-FormatData -TypeName System.Diagnostics.Process | Select -Expand FormatViewDefinition | Where name -eq 'process' | Select -first 1 | Select -Expand control

PSH [C:\Foo]: $f.headers

Label  Alignment Width
-----  --------- -----
NPM(K)     Right     7
PM(M)      Right     8
WS(M)      Right    10
CPU(s)     Right    10
           Right     7
           Right     3
       Undefined     0
```
As you can see, the width of the CPU column is 10 characters. And that is what you are seeing - PowerShell attempt to format a BIG number into those 10 characters and fails gracefully. Not what you ideally wanted but it is by design. 

The solution would be to update the XML. You can do that in your PowerShell profile (create XML that overrides the system formatting defaults).  

I am not sure it's worth changing the default but that is an option worth discussing. The question then is how wide to make it, given that most CPU values are adequately covered by the current implementation.

**Comment by SeeminglyScience** [comment] 2022-04-04 15:09
> The question then is how wide to make it, given that most CPU values are adequately covered by the current implementation.

I wonder if that's only the case for Windows though. If large numbers are the norm on Mac (as the OP is running) it's probably worth increasing the size of that column a few.

**Comment by vexx32** [comment] 2022-04-05 14:35
> Changing this default would only help a fairly small number of users. Given that -Autosize works, not sure we'd want to change this default for edge cases.

I don't think we can make this assertion without data to back it up.

**Comment by iSazonov** [comment] 2023-06-09 03:01
Since `Format-Table -AutoSize` works well I think we can close the issue as `Won't fix`.
(If even the default format(s) covers 80% of the cases it is a very good result, but I think there is even more positive percentage.)

**Closed** 2023-12-14 01:01 UTC
Labels: Issue-Enhancement, WG-Cmdlets, Up-for-Grabs, Resolution-No Activity
