### ISSUE TITLE
System.Net.Http.HttpClient always fails on first attempted connection

### ISSUE THREAD

**Issue by mkellen1** [PowerShell/PowerShell#20813] opened 2023-11-29 19:18 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a re-report of Issue #19486, which was resolved for inactivity but still persists in 7.4.0.  I have golfed the problem down to the following minimum code example.

```
> PS> $client = New-Object -TypeName System.Net.Http.HttpClient
> PS> $r1=$client.GetStringAsync('http://www.google.com')
> PS> $r1.Status
> Faulted
> PS> $r1.Exception.InnerException.InnerException.Message
> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
> PS> $r1.Exception.InnerException.InnerException.InnerException | Select SocketErrorCode,ErrorCode
> SocketErrorCode ErrorCode
> ConnectionReset     10054
> PS> $r2=$client.GetStringAsync('http://www.google.com')
> PS> $r2.Status
> RanToCompletion
```

### Expected behavior

```console
Should connect the first time.
```

### Actual behavior

```console
Always fails on the first attempt to connect to a site.
```

### Error details

```console
No output.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment] 2023-11-29 21:21
So this looks like an issue with .NET, not PowerShell ( more on that in a minute )

You are calling an xxxxAsync method, [GetStringAsync](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstringasync?view=net-8.0#system-net-http-httpclient-getstringasync(system-string)) which returns an ITask<string>. You need to await ( or equivalent ) for the result.

The Async methods 'run in background' ( actually they don't, it is a form of cooperative multitasking), you are asking for the result before it has completed.

So the good news is that nothing is broken if you abide by the asynchronous programming techniques and use await.

The bad news is that PowerShell is fundamentally not designed for asynchronous programming.

The other good news is that given you are doing PowerShell programming then use the Web cmdlets such as Invoke-WebRequest  for invoking web requests

**Comment by mkellen1** [comment] 2023-11-29 22:05
I'm sorry if I tried to drill too far down the object stack.  It doesn't matter about the Async in this case. I get the same result with any HTTP or HTTPS connection method:

PS> Invoke-WebRequest http://www.google.com
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

**Comment by rhubarb-geek-nz** [comment] 2023-11-29 22:11
```
PowerShell 7.4.0
PS> Invoke-WebRequest -Uri "http://www.google.com"

StatusCode        : 200
StatusDescription : OK
Content           : <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-GB"><head><meta
                    content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta
                    content="/images/branding/googleg/1x/…
RawContent        : HTTP/1.1 200 OK
                    Date: Wed, 29 Nov 2023 22:08:43 GMT
                    Cache-Control: max-age=0, private
                    Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src
                    'nonce-2WayZcovNOBhWeuRFFIqjg…
Headers           : {[Date, System.String[]], [Cache-Control, System.String[]], [Content-Security-Policy-Report-Only,
                    System.String[]], [Server, System.String[]]…}
Images            : {@{outerHTML=<img alt="Google" height="92"
                    src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png"
                    style="padding:28px 0 14px" width="272" id="hplogo">; tagName=IMG; alt=Google; height=92;
                    src=/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png;
                    style=padding:28px 0 14px; width=272; id=hplogo}}
InputFields       : {@{outerHTML=<input value="en-GB" name="hl" type="hidden">; tagName=INPUT; value=en-GB; name=hl;
                    type=hidden}, @{outerHTML=<input name="source" type="hidden" value="hp">; tagName=INPUT;
                    name=source; type=hidden; value=hp}, @{outerHTML=<input name="biw" type="hidden">; tagName=INPUT;
                    name=biw; type=hidden}, @{outerHTML=<input name="bih" type="hidden">; tagName=INPUT; name=bih;
                    type=hidden}…}
Links             : {@{outerHTML=<a class="gbzt gbz0l gbp1" id=gb_1 href="https://www.google.co.uk/webhp?tab=ww"><span
                    class=gbtb2></span><span class=gbts>Search</span></a>; tagName=A; class=gbzt gbz0l gbp1; id=gb_1;
                    href=https://www.google.co.uk/webhp?tab=ww}, @{outerHTML=<a class=gbzt id=gb_2
                    href="https://www.google.com/imghp?hl=en&tab=wi"><span class=gbtb2></span><span
                    class=gbts>Images</span></a>; tagName=A; class=gbzt; id=gb_2;
                    href=https://www.google.com/imghp?hl=en&tab=wi}, @{outerHTML=<a class=gbzt id=gb_8
                    href="http://maps.google.co.uk/maps?hl=en&tab=wl"><span class=gbtb2></span><span
                    class=gbts>Maps</span></a>; tagName=A; class=gbzt; id=gb_8;
                    href=http://maps.google.co.uk/maps?hl=en&tab=wl}, @{outerHTML=<a class=gbzt id=gb_78
                    href="https://play.google.com/?hl=en&tab=w8"><span class=gbtb2></span><span
                    class=gbts>Play</span></a>; tagName=A; class=gbzt; id=gb_78;
                    href=https://play.google.com/?hl=en&tab=w8}…}
RawContentLength  : 51173
RelationLink      : {}
```

I tried

- Invoke-WebRequest http://www.google.com
- Invoke-WebRequest "http://www.google.com"
- Invoke-WebRequest -Uri "http://www.google.com"

and they all worked

**Comment by mkellen1** [comment] 2023-11-29 22:18
It works just fine for me in PowerShell 5 on the same machine and it used to work in PowerShell 7 up until about somewhere in 7.2.x

**Comment by rhubarb-geek-nz** [comment] 2023-11-29 22:21
I would validate your installation of PowerShell 7, completely remove it and confirm you don't have multiple copies. Then install a self-contained version of PowerShell ( eg the MSI ) which contains the dotnet runtime. Make sure you don't have unexpected modules folders on the PSModulePath

**Comment by mklement0** [comment] 2023-11-30 19:42
@mkellen1, I suggest first narrowing down whether this is indeed a _PowerShell_ problem or a _.NET_ problem:

The fact that the problem also happens with direct use  `[System.Net.Http.HttpClient]` points to the latter.

If you still suspect that PowerShell is somehow to blame or at least part of the problem, I suggest doing the following:

* Create a .NET 8 console application in C# with the translation of the code that produces the problem in PowerShell.

* Run this application from _outside_ PowerShell, and see if there's any difference in behavior.

If not, you should report the issue in the [.NET repo](https://github.com/dotnet/runtime/issues).

**Comment by mkellen1** [comment] 2023-11-30 19:43
I get the same behavior with "-DisableKeepAlive." I get the same behavior working remotely or in the office. I can even replicate it completely off network using a localhost web server. I can also reproduce it in Windows Subsystem for Linux (kali) on the same box.

**Comment by rhubarb-geek-nz** [comment] 2023-11-30 22:16
> actually under mono in the kali WSL2

Alas that doesn't really help PowerShell based on .NET Core and just adds 3 additional layers of confusion.

I suggest download the .NET SDK 8.0 on Windows and demonstrate the problem on Windows side by side with it working in PowerShell 5.1.

You say it stopped working on PowerShell 7.2, that used .NET SDK 6.0

**Comment by rhubarb-geek-nz** [comment] 2023-12-01 00:11
Now it may be that some server component is actually resetting the connection, or closing it early. Unfortunately it does not mean that `Invoke-WebRequest` may be able to automate any retry.

The existing` -MaximumRetryCount` parameter allows retries for specific status code ranges. However if the connection was terminated before the status code was received you can't make any claim as to what the status value actually was. 

Perhaps the lower level code can retry if the connection failed, but if the connection succeeded and the body was sent, then if the connection was terminated before the response was received you do not know if the request was successful or not.

So this may require application level retry of an operation. Just because you are writing PowerShell code does not mean that all partial failure scenarios disappear.

**Comment by mklement0** [comment] 2023-12-01 00:26
@rhubarb-geek-nz, your recommendation to use a _.NET 8 SDK application_ to reproduce the issue was sound ([Mono](https://en.wikipedia.org/wiki/Mono_(software)) is an entirely separate issue):

* Once we know whether it occurs _only there_, we'll know what the appropriate repo is  in which to pursue this further.

* The [lower-level angle](https://github.com/PowerShell/PowerShell/issues/19486#issuecomment-1503989238) was covered by @jborean93  in the original issue, but the fact that _a change in PowerShell and/or .NET version made a difference_ warrants narrowing it down to which  of the two environments - PowerShell or .NET, if any - accounts for the change.

**Comment by CarnaViire** [comment] 2023-12-01 01:00
I'm a bit confused which PowerShell used which version of .NET. Is PowerShell 5 on .NET 6 or .NET 5?

**Comment by rhubarb-geek-nz** [comment] 2023-12-01 01:04
```
PowerShell 5.1 .NET Framework 4.8
```

```
PowerShell 7.0 netcoreapp3.1
PowerShell 7.1 net5.0
PowerShell 7.2 net6.0
PowerShell 7.3 net7.0
PowerShell 7.4 net8.0
```

**Comment by CarnaViire** [comment] 2023-12-01 01:12
Aah thanks. The internal retry policy of HttpClient was changed in .NET 6 -- see full discussion in https://github.com/dotnet/runtime/issues/60644. The recommendation is do the application-level retries (I believe, it was mentioned above as well).

It aligns with the problem becoming visible in PowerShell 7.2.

**Comment by mklement0** [comment] 2023-12-01 16:28
@mkellen1, you should post this at https://github.com/dotnet/runtime/issues/95487.

Now that we know that the problem is at (at least) the .NET level, the discussion should continue there, and the maintainers here should tag this as "Resolution-External".

**Closed** 2023-12-07 20:30 UTC
Labels: Resolution-External
