### ISSUE TITLE
Move-Item, Remove-Item don't work with paths containing \, [, ] on unix

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3414] opened 2017-03-24 19:08 UTC
Steps to reproduce
------------------

On macOS or Linux `touch '1\2'`
Try `mv 1\2 2`, try `rm 1\2`

The real-world example of when you are getting `\` without knowing it is https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/11

The problem happens not only with `Compress-Archive`, but with other archive programs too. So macOS users need a way to bulk-rename files with `\` in the name and PS doesn't provide a way to do it at the moment.

UPD: same problem for paths like `[foo]`.

Expected behavior
-----------------

PowerShell should be able to perform the operations

Actual behavior
---------------

Paths are getting normalized to `1/2`

```
rm : Cannot find path '/Users/vors/dev/PowerShell/1/2' because it does not exist.
```

Environment data
----------------

```powershell

> $PSVersionTable

Name                           Value                                                                                
----                           -----                                                                                
PSVersion                      6.0.0-alpha                                                                          
PSEdition                      Core                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                              
BuildVersion                   3.0.0.0                                                                              
GitCommitId                    v6.0.0-alpha.17                                                                      
CLRVersion                                                                                                          
WSManStackVersion              3.0                                                                                  
PSRemotingProtocolVersion      2.3                                                                                  
SerializationVersion           1.1.0.1                                                                              
```

**Comment by lzybkr** [comment] 2017-03-24 21:06
Aren't `mv` and `rm` the Unix utilities? Assuming so, we shouldn't assume an argument that looks like a path is actually a Unix path.

**Comment by daxian-dbw** [comment] 2017-03-24 21:15
Weird, I cannot reproduce this:
```
PS /home/dongbo/temp> touch '1\2'                                                                   
PS /home/dongbo/temp> dir                                                                           

    Directory: /home/dongbo/temp/1

Mode                LastWriteTime         Length Name                                              
----                -------------         ------ ----                                              
------          3/24/17   2:11 PM              0 1\2                                               

PS /home/dongbo/temp> mv 1\2 2
PS /home/dongbo/temp> dir

    Directory: /home/dongbo/temp

Mode                LastWriteTime         Length Name                                              
----                -------------         ------ ----                                              
------          3/24/17   2:11 PM              0 2      
```
```
PS /home/dongbo/temp> touch '1\2'                                                                   
PS /home/dongbo/temp> dir                                                                           

    Directory: /home/dongbo/temp/1

Mode                LastWriteTime         Length Name                                              
----                -------------         ------ ----                                              
------          3/24/17   2:13 PM              0 1\2                                               

PS /home/dongbo/temp> 
PS /home/dongbo/temp> rm 1\2                                                                        
PS /home/dongbo/temp> dir                                                                           
PS /home/dongbo/temp>
```
**Environment**
```
Name                           Value                                                               
----                           -----                                                               
PSVersion                      6.0.0-alpha                                                         
PSEdition                      Core                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                             
BuildVersion                   3.0.0.0                                                             
GitCommitId                    v6.0.0-alpha.16                                                     
CLRVersion                                                                                         
WSManStackVersion              3.0                                                                 
PSRemotingProtocolVersion      2.3                                                                 
SerializationVersion           1.1.0.1

RID:         ubuntu.16.04-x64
```

**Comment by vors** [comment] 2017-03-24 21:28
Oh yeah, I mean our versions of rm and mv (aliases)

**Comment by joeyaiello** [comment] 2017-03-24 23:29
Update the title to reflect the issue more accurately.

**Comment by vors** [comment] 2017-04-26 18:18
The other thing with path like `[foo]` is that you cannot use `remove-item -recurse -force .` to get rid of them.
I.e.

```
PS /Users/svorobev/dev/PowerShell> mkdir junk                                                                                                                                  
PS /Users/svorobev/dev/PowerShell> cd junk                                                                                                                                     
PS /Users/svorobev/dev/PowerShell/junk> touch '[foo]'                                                                                                                          
PS /Users/svorobev/dev/PowerShell/junk> ls                                                                                                                                     
[foo]
PS /Users/svorobev/dev/PowerShell/junk> rm -Recurse -Force *                                                                                                                   rm : An object at the specified path /Users/svorobev/dev/PowerShell/junk/[foo] does not exist.                                                                                 
At line:1 char:1
+ rm -Recurse -Force *
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.RemoveItemCommand
 
PS /Users/svorobev/dev/PowerShell/junk> 
```

**Comment by jeffbi** [comment] 2017-04-26 21:47
Regarding the operations on `[foo]`: `[foo]` is shell globbing pattern, so you should probably use `-LiteralPath` when trying to give that filename to `Remove-Item`.

It probably still won't work right now, but I have a fix for #2799 coming that seems to also fix that, as well as the `Remove-Item -Recurse -Force *` issue. I haven't looked at this for the `\` character, so I can't yet say whether my changes will fix that part.

**Comment by vors** [comment] 2017-04-26 22:51
@jeffbi oh, awesome to see that you working on it!
```
rm -LiteralPath '[foo]'
```
give the same result. I tried few things like explicit escaping with backticks and nothing seems to work.

**Comment by SteveL-MSFT** [comment] 2017-04-26 23:57
@jeffbi I'm assigning this to you to make sure you capture all the test cases with your current PR

**Comment by jeffbi** [comment] 2017-04-27 00:01
@SteveL-MSFT Of course I'm happy to take this, but I want it to be clear that at this point I'm not claiming that my current PR will fix this issue in its entirety, just the `[foo]` part.

I will be sure to add tests involving Unix globbing characters in my PR's tests.

**Comment by jeffbi** [comment] 2017-04-29 04:36
This appears to be fixed by .NET Core 2.0. The current set of permission bits seems to be 666 (checked with umask set to 000).

**Comment by jeffbi** [comment] 2017-04-30 20:36
The issue of a backslash character in the filename is a completely different problem than the wildcard characters part of this, one that PR #3661 does not address.

The basis of the problem is premature normalization of paths. Path normalization happens quite early (and *very* frequently and in a great number of places in the PowerShell code) while processing a command. Usually this happens before the path reaches its provider, and often that normalization is a brute-force change one slash to another mechanism. Thus a path such as `1\2` on Unix is "normalized" to `1/2`, ensuring that the path will never be found.

Using `-LiteralPath` does not prevent the path normalization, so that is not a workaround.

**Comment by SteveL-MSFT** [comment] 2017-04-30 20:56
@jeffbi perhaps it makes sense to have the backslash as a separate issue then

**Comment by jeffbi** [comment] 2017-04-30 23:44
@SteveL-MSFT It probably does. The only reason I didn't was that this issue was originally about the backslash---the globbing part was added later. I'll go ahead and open a new issue for this.

**Comment by anmenaga** [comment] 2017-08-28 20:56
Verified on latest release (v6.0.0-beta.6) on Ubuntu14 that `Move-Item`, `Remove-Item` work as expected with `[`, `]`, `*` when `-LiteralPath` parameter is used.

**Comment by anmenaga** [comment] 2017-08-28 21:12
The remaining thing for this issue are backslashes (`\`) that are covered in greater detail in a linked issue #3666 (On Unix, PowerShell will not find files with backslashes in their names), so closing this one.

**Closed by anmenaga** 2017-08-28 21:12 UTC
Labels: Area-Cmdlets-Management, OS-Linux, OS-macOS
