### ISSUE TITLE
new-pssession fails to connect to second linux box

### ISSUE THREAD

**Issue by kort3x** [PowerShell/PowerShell#1978] opened 2016-08-20 11:56 UTC
Steps to reproduce
------------------
trying to create session to second linux box (both Ubuntu 14.04):
$session = New-PSSession -HostName manubuntu -UserName admerlin

Expected behavior
-----------------
+PS /home/admerlin> $session = New-PSSession -HostName manubuntu -UserName admerlin
 +The authenticity of host 'manubuntu (192.168.114.249)' cannot be established.
 +ECDSA key fingerprint is SHA256:2kCbnhT2dUE6WCGgVJ8Hyfu1z2wE4lifaJXLO7QJy0Y.
 +Are you sure you want to continue connecting (yes/no)?
 +admerlin@manubuntu password:

Actual behavior
---------------
PS /home/admerlin> $session  = New-PSSession -HostName manubuntu -UserName admerlin
New-PSSession : [manubuntu] The background process reported an error with the following
message: "The named pipe target process has ended.".
At line:1 char:6
+ $s = New-PSSession -HostName manubuntu -UserName admerlin
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace)
    [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : 2100,PSSessionOpenFailed

Environment data
----------------

PS /home/admerlin> $PSVersionTable

Name                                       Value
PSVersion                                   6.0.0-alpha
PSEdition                                   Core
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0...}
BuildVersion                              3.0.0.0
GitCommitId                             v6.0.0-alpha.9
CLRVersion
WSManStackVersion                3.0
PSRemotingProtocolVersion    2.3
SerializationVersion                  1.1.0.1

```

**Comment by DexterPOSH** [comment] 2016-08-22 05:05
Able to repro the error when connecting from Ubuntu 14.04 (machine 1) to a CentOS (machine 2), using the New-PSSession -HostName <> -UserName <>
 
Machine 1
```
PS /vagrant_data> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

```

Machine 2
```Shell
[vagrant@dev ~]$ rpm --query centos-release
centos-release-6-6.el6.centos.12.2.x86_64
```

**Comment by kirby14** [comment] 2016-08-23 15:14
I get teh same exact error trying to connect from OS X to Windows.

`Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.9                                  
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1 `

**Comment by andschwa** [comment] 2016-09-19 22:03
Per the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support), this is **not yet supported**.  Please follow the progress on the [PSRP on Linux repo](https://github.com/PowerShell/psl-omi-provider). Closing as duplicate of #942.

**Closed by andschwa** 2016-09-19 22:03 UTC
Labels: Area-Remoting
