### ISSUE TITLE
Share FunctionInfo and execute it with $using when using `ForEach-Object -Parallel` causes session state corruption

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#16461] opened 2021-11-13 01:44 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is reported by internal MSFT folks. Quote the emails content below:

**`Write-Host` sometimes undefined with `ForEach-Object -Parallel`.**

Due to networking issues, I can’t grab my actual code, but I wrote code along the lines of:
```powershell
function f1
{
    param([string]$i)
    if (Test-Path $i) { return $i }
    # do something
    if ($i-eq "bad")
    {
        Write-Host "something is wrong!"
        return $null
    }

    return $i
}

function get-inputs
{
    return @("foo", "bar", "bad", "good")
}

function invoke-processInputs
{
    $inputs = get-inputs
    $f1Func = Get-Command -Name "f1"
    $job = $inputs | ForEach-Object -AsJob -ThrottleLimit 2 -Parallel {
        $output = & $using:f1Func $_
        if ($output -eq $null)
        {
            # do something
        }
    }

    #do some status reporting on the job...
    while ($job.State -eq "Running") { write-host "running..." ; start-sleep 1 }
    Wait-Job -Id $job.Id
    Remove-Job -Id $job.Id
}
```

My actual input set has 100+ entries and some of them essentially trigger the bad case (through a bunch of network stuff). What’s super confusing is that I both see the actual output (the “something is wrong” in this example) as well as “The term ‘Write-Host’ is not recognized as the name of a cmdlet…” error too. I’ve also seen the Test-Path give the same error. Those both seem… wrong

I expect there’s something about the parallel foreach that I’m messing up, but I’m not sure what here.

### Expected behavior

```console
Write-Host should work fine
```

### Actual behavior

```console
Run into error:
The term 'Write-Host' is not recognized as the name of a cmdlet…
```

### Error details

```console
Not available
```

### Environment data

```powershell
This is all on pwsh 7.2 (GA, nothing internal)

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

N/A

**Comment by daxian-dbw** [comment] 2021-11-13 01:50
>   $output = & $using:f1Func $_

The `FunctionInfo` object is passed to different Runspace’s for execution, so it’s highly likely that you were experiencing state corruption because of that.

There is a concept of “Runspace affinity” – a script block is associated with the Runspace where it was created, so when it’s running in a different Runspace, the script block will be marshalled back to the Runspace where it was created to execute. This design is built on the assumption that a script block created in a Runspace is likely to depend on resources only available in that Runsapce at the run time. However, in practice, this causes a lot problems when you share a script block among multiple Runsapces. Here are some issues tracking this on GitHub: #4003, #7626.

Simply put, this may cause the session state of the original Runspace, where the script block was created, to be corrupted, and thus you will see errors like “Write-Host is not recognized as the name of a cmdlet” because the command lookup through scopes failed (the script block could be running with a dangling scope that was remove from the chain prematurely).

So, the solution is to not share script block among Runspace’s. Instead, share the AST among those Runsapce’s. In your case, it would be something like this:

```
$f1Func = Get-Command -Name "f1"
$f1BodyAst = $f1Func.ScriptBlock.Ast.Body

$job = $inputs | ForEach-Object -AsJob -ThrottleLimit 2 -Parallel {
    if (-not $global:f1Func)
{
    # this creates a new script block in the Runspace where it’s supposed to be running.
        $global:f1Func = $using:f1BodyAst.GetScriptBlock()
    }

    $output = & $global:f1Func $_
    if ($output -eq $null)
    {
        # do something
    }
}
```

@PaulHigin did some work to disallow passing script block with `$using` when using `ForEach-Object -Parallel`, but I guess it should **disallow FunctionInfo, FilterInfo, and ExternalScriptBlockInfo** too.

![image](https://user-images.githubusercontent.com/127450/141601255-cf08257b-8d00-4579-8d50-7b22aaeb2be7.png)

Also, it would be nice to document the workaround using AST for scenarios like this one, and make the error message thrown from PowerShell points to the that doc, so the user can learn about this workaround.

**Comment by iSazonov** [comment] 2021-11-13 06:05
> Instead, share the AST among those Runsapce’s. In your case, it would be something like this:

If it is an unambiguous match we could do it automatically. Simply banning these constructs is bad UX. It would be much easier for users to use intuitive explicit constructs and the Engine would convert this into the correct implementation.

**Comment by SeeminglyScience** [comment] 2021-11-13 14:40
> If it is an unambiguous match we could do it automatically. Simply banning these constructs is bad UX. It would be much easier for users to use intuitive explicit constructs and the Engine would convert this into the correct implementation.

I fear that if that's done automatically it will lead to a lot of confusion about why the function can't access the state it previously could. While the error isn't great UX, it happens at design time and is instantly clear what is wrong. Plus the work around makes it a lot easier to understand that it won't work exactly the same.

**Comment by iSazonov** [comment] 2021-11-13 17:30
> I fear that if that's done automatically it will lead to a lot of confusion about why the function can't access the state it previously could.

Why? `$Using` assumes coping an entity to _another_ context. 
One more option we discussed already is to clone whole context. It is slow to start but this could be useful in some scenarios.

I don't like workarounds in languages. Languages are designed _to make things easier_. If a consumer has to make workarounds, it means the language creator did not think the language or its implementation through.

**Comment by daxian-dbw** [comment] 2021-11-13 17:50
This is a workaround of a bug, and that bug will be fixed at some point, even though it's low priority today.

**Comment by SeeminglyScience** [comment] 2021-11-13 18:15
> Why? `$Using` assumes coping an entity to _another_ context. 

It did with serialization, with thread jobs it doesn't imply a copy/clone.

> I don't like workarounds in languages. Languages are designed _to make things easier_. If a consumer has to make workarounds, it means the language creator did not think the language or its implementation through.

I don't disagree, but they're still preferred until the right solution is determined.

**Comment by PaulHigin** [comment] 2021-11-15 18:19
This has nothing to do with the remoting system, so changing working group to core cmdlets.

It looks like there are two issues here with the `$using:` keyword.

One is using unsafe objects (objects with runspace affinity and/or with thread safety issues).  This can be mitigated by detecting the use of these new objects and providing a useful error message.

The other is the (reasonable) expectation that parallel running runspaces share the same state as the runspace hosting the `foreach-object -parallel` call, and is captured in this issue (#12240).  Unfortunately, this has been considered lower priority and I have not been able to work on it yet.

It should be noted that these issues are not unique to `foreach-object -parallel`, and are simply inherent weaknesses of PowerShell threading and script execution model.

**Comment by snydergd** [comment] 2023-01-09 15:15
Disclaimer: I'm a casual PowerShell user and don't understand internals (don't even know what `FunctionInfo` is).  I got here because I was using an approach similar to https://github.com/PowerShell/PowerShell/issues/7626, and actually had what I think is meant by "state corruption" issues.

Is there a good workaround to the issue or preferred way to avoid the issue?  Maybe there is some way to create a fresh/empty "state" for the script block or create a new clone with fresh/empty state?

The best workaround I've found that still seems really wrong is to convert the `ScriptBlock` to a String using `toString()`, pass it in, and then convert it back to a `ScriptBlock` using `[scriptblock]::Create($using:scriptBlockString)`.  I could also just define the logic from the script block directly in the job's script block, but the problem is I want to use this for multiple `ForEach-Object` calls as well as outside of any `ForEach-Object` call.  I also considered putting it into a separate file and including it where I needed it, but it seems like I should not have to do that.

```
Function Get-Something($arg) {
  # do stuff in here (don't use anything not passed in, though)
}

$getSomethingString = ${function:Get-Something}.toString()
@(1, 2, 3) | ForEach-Object -ThrottleLimit 5 -Parallel {
  invoke-command -scriptBlock ([scriptblock]::Create($using:getSomethingString)) -ArgumentList $_
}
```

**Comment by PaulHigin** [comment] 2023-01-09 17:04
When PowerShell creates a script block, it is associated with the session in which it is created.  `ForEach-Object -Parallel` runs script in different sessions (runspaces) on separate threads.  So passing in a script block object is disallowed because it would run a script block created for one session on a different session.

But your solution above works around this limitation by creating a new script block in each `ForEach-Object -Parallel` session.  Another similar solution is to pass in script file path, instead of a script string, or use PowerShell modules.

Note that `ForEach-Object -Parallel` now supports a `-UseNewRunspace` switch that creates a new session for each foreach loop element.  This is less efficient but guarantees a clean/fresh session for each loop iteration.

Also, the #12240 work item above, has been pretty much abandoned.  @daxian-dbw looked into transferring state between sessions (runspaces) and found it is impossible to do it perfectly.

**Closed** 2023-11-22 11:04 UTC
Labels: WG-Cmdlets-Core, Needs-Investigation, Resolution-No Activity
