### ISSUE TITLE
`Import-Module -UseWindowsPowerShell:$false` does non-op on a non-existing module

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20723] opened 2023-11-18 18:41 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:

```powershell
Import-Module NoSuchModule -UseWindowsPowerShell:$false
```

### Expected behavior

```console
Import-Module: The specified module 'NoSuchModule' was not loaded because no valid module file was found in any module directory.
```

### Actual behavior

The call is a quiet no-op, and `$?` is `$true`

### Environment data

```powershell
PowerShell 7.4.0
```

**Comment by daxian-dbw** [comment] 2024-01-08 20:07
The Engine WG reviewed this today. It seems the issue is not rooted in `$PSDefaultParameterValues`, but in `Import-Module -UseWindowsPowerShell:$false`. When running `Import-Module NoSuchModule -UseWindowsPowerShell:$false`, it doesn't really do anything, but `$?` is `true` afterward. So, we believe it's an issue with `Import-Module -UseWindowsPowerShell`.

Marked it as a bug and changed the issue title.

**Closed** 2024-07-15 03:12 UTC
Labels: Issue-Bug, WG-Engine-Module, Resolution-No Activity, WG-Triaged

**Comment by mklement0** [comment] 2024-07-15 18:00
@daxian-dbw: This is probably an easy fix, so I suggest adding the `Up-for-grabs` and `Keep-Open` labels.
