### ISSUE TITLE
Bug with bigint multiplication

### ISSUE THREAD

**Issue by Tragen** [PowerShell/PowerShell#21341] opened 2024-03-13 20:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Write-Host "int: $([int]5 * [double]1.5)"
Write-Host "bigint: $([bigint]5 * [double]1.5)"
```
prints
```
int: 7.5
bigint: 5
```

using c# directly in PS prints the correct result
```
Add-Type -TypeDefinition @"
using System;
namespace DemoCode
{
    public class DemoClass
    {
        public static void Test()
        {
            int i = 5;
            System.Numerics.BigInteger bi = 5;
            double d = 1.5;

            double r = i * d;
            Console.WriteLine("bigint c#: " + r.ToString());
        }
    }
}
"@
[DemoCode.DemoClass]::Test()
```
prints
```
bigint c#: 7.5
```

Why is the multiplication directly in PS truncating the double?
It doesn't matter if I use 1.1, 1.5 or 1.9, the double gets truncated and then multiplied.

This bug happens in PowerShell 74.1 and 5

### Expected behavior

```console
PS> [bigint]5 * [double]1.5
7.5
```

### Actual behavior

```console
PS> [bigint]5 * [double]1.5
5
```

### Error details

```console
There was no error
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2024-03-13 21:49
The bug boils down to this:

* While performing arithmetic operations with _other_ integer types in combination with a `[double]` (or the rarely used `[float]`) yield a `[double]`-typed result, with `[bigint]`, specifically, the respective other operand is forced to `[bigint]` too.

In other words:

```powershell
[bigint] 5 * [double] 1.5
```

is currently - unexpectedly - the same as:

```powershell
[bigint] 5 * [bigint] [double] 1.5
```
Since `[bigint] 1.5` (same as: `[bigint] [double] 1.5`, given that a number literal with a decimal point is _implicitly_ a `[double]`)  is `1`, the result is `5n` (aka `[bigint] 5`)

**Comment by rhubarb-geek-nz** [comment] 2024-03-14 00:57
The C# is not equivalent code because you are not multiplying an integer

You get a compiler error trying to multiply an integer with a double, eg

```
int i=5;
i+=1.5;
```

won't compile because the 1.5 can't be implicitly casted to an int in this case.

Because you have

```
double r=
```

it promotes everything on the right side to doubles to make the calculation, hence the expected result

**Comment by mklement0** [comment] 2024-03-14 01:11
@rhubarb-geek-nz:

* Fundamentally, C# plays by different rules than PowerShell, so differing behavior isn't in and of itself relevant.

* For that reason, my comment focused on how the observed behavior is _inconsistent in the  realm of PowerShell_ - and that's what the conversation should focus on.

* As an - inconsequential - aside: C# _prevents_ mixing `System.Numerics.BigInteger` and `System.Double` in arithmetic expressions, so that, for instance, `double r = (System.Numerics.BigInteger) 1 * 1.2;` _fails_.

**Comment by Tragen** [comment] 2024-03-14 01:14
You are right with C#, I made a mistake there.
But in PS, there should be an error also and not a wrong result.

**Comment by rhubarb-geek-nz** [comment] 2024-03-14 01:14
This then counts as the PowerShell inconsistency

```
PS> [int]5*1.5
7.5
PS> [bigint]5*1.5
5
```

**Comment by mklement0** [comment] 2024-03-14 01:36
> there should be an error

I haven't looked at any _technical_ challenges, but _ideally_ the - PowerShell-idiomatic - behavior would be:

Automatically convert to `[double]`, because that's what happens with all other integer types (`[sbyte]`, `[byte]`, `[int16]`, `[uint16]`, `[int]`, `[uint]`, `[long]`, `[uint64]`).

Thus:

```powershell
# 5n == [bigint] 5; 1.5 == [double] 1.5
5n * 1.5 | % {  [pscustomobject] @{ Result = $_; ResultType = $_.GetType() } } 
```

SHOULD be:

```
Result ResultType
------ ----------
 7.500 System.Double
```

But currently is:

```none
Result ResultType
------ ----------
     5 System.Numerics.BigInteger
```

However, the open-ended nature of `[bigint]` theoretically makes it possibly for the result _not_ to fit into a `[double]` - something that cannot happen with the other integer types.

In that case, it would make sense to exhibit the same behavior as when trying too cast a too-large / too-small  `[bigint]` to a `[double]`, which means: `[double]::PositiveInfinity` / `[double]::NegativeInfinity`

```powershell
# Try to cast a [bigint] that is too large to fit into [double] to a [double]
[double] (Invoke-Expression ('9' * 1e3 + 'n'))
# Ditto for a negative number
[double] (iex ('-' + ('9' * 1e3 + 'n')))
```

**Comment by SeeminglyScience** [comment] 2024-04-01 18:55
The Engine WG reviewed this and we've decided this is by design. If `bigint` is specified, it's expected that very large numbers will be involved. If you need decimal places, we'd recommend converting the `bigint` to `double` before the operation.

**Comment by Tragen** [comment] 2024-04-02 08:50
How about a warning when using `Set-StrictMode -Version Latest`
At least you would know about this. I can accept that it's not working.
But failing without error or warning is not good.

**Comment by mklement0** [comment] 2024-04-03 05:58
@Tragen, speaking in no official capacity whatsoever:

* I disagree with the WG decision: coercion to `[double]` - even if it situationally results in `[double]::PositiveInfinity` / `[double]::NegativeInfinity` -  amounts to behavior that is consistent with arithmetic with other types; receiving either of the two results allows you to _infer_ what happened. Carving out an exception for `[bigint]` is a confusing exception that is likely to trip up users.

* `Set-StrictMode` is problematic in general, given PowerShell's _dynamic scoping_: it affects not just the current scope, but also all _descendent_ scopes, and therefore requires careful managing; note that `Set-StrictMode` hasn't seen updates since `-Version 3`.

Given the WG decision:

* The behavior should be _documented_: however, going by past behavior, this likely won't happen until  a (non-team) user akes the initiative to ask that the [Type conversion to accommodate result](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.4#type-conversion-to-accommodate-result) part of the docs be amended.

*  The best you can hope for is implementation of a [PSSA](https://github.com/PowerShell/PSScriptAnalyzer) rule, so that, for instance you'd get a design-time warning in Visual Studio Code - again, this will likely require user initiative.

**Comment by Tragen** [comment] 2024-04-03 14:36
I think also the decision is wrong.
You force all users to start searching why it isn't working until you find the documentation or the this bug.
It's unnecessary at makes more work.

**Comment by SeeminglyScience** [comment] 2024-04-03 17:42
> * I disagree with the WG decision: coercion to `[double]` - even if it situationally results in `[double]::PositiveInfinity` / `[double]::NegativeInfinity` -  amounts to behavior that is consistent with arithmetic with other types; receiving either of the two results allows you to _infer_ what happened. Carving out an exception for `[bigint]` is a confusing exception that is likely to trip up users.

I would be more worried about loss of precision than hitting an actual limit. Neither choice is wrong here, we just think it's more likely to need precision if you've already specified a bigint. Also helps that it's the existing behavior at least as far back as 5.1 so no breaks.

> I think also the decision is wrong. You force all users to start searching why it isn't working until you find the documentation or the this bug. It's unnecessary at makes more work.

Keep in mind that this would also apply if we changed it and someone was instead expecting precision. Short of becoming a strict language like C# where it would instead simply fail to compile, that isn't really avoidable.

**Comment by SeeminglyScience** [comment] 2024-04-03 19:34
> And this is clearly wrong and it's also wrong because it works differently in C#. I would think that PowerShell is .Net and behaves the same way like C# so different behavior is just wrong for me imho.

In C# it just fails to compile, the example you had was `double * int`. See this [SharpLab.io example](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgDkBXMAUwCcoBjAZwG5MEBmfJXAYVwG9Ncg/OwAmAe1LAANhVwBZABQAhKAHMAkjAAuFVdVwyAZloA0ucZJm4aqgBZaAlHwFDXCAOwGKx3ACpravbMGK4AvpihQA===).

**Comment by Tragen** [comment] 2024-04-03 19:35
I know. And I expect that to happen in PowerShell as well.
I would know much faster to use long or int or double or cast it if necessary.

**Comment by mklement0** [comment] 2024-04-04 02:38
@Tragen, it was never PowerShell's goal to be C#-compatible, and it intentionally deviates from C# in several ways, notably with respect to PowerShell's very flexible _implicit type conversions_:

_Typically_, these conversions are helpful and work as one would intuitively expect - pitfalls notwithstanding - and are a better fit for a "looser" shell scripting language vs. a compiled language such as C#.

In the context of PowerShell's existing behavior with integer type operands - coercion to `[double]` when an operand of that type is involved - I would have expected `[bigint]` to be treated the same way: it would make for consistent behavior _in a PowerShell context_.

As @SeeminglyScience points out, the behavior of unexpectedly forcing `[double]` operands to `[bigint]` - an inconsistency in the realm of PowerShell - goes back to _Windows PowerShell_, which would make changing the behavior a more serious breaking change than I originally thought.

Yet, breaking changes are still acceptable if they fall into [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area): a breaking change considered to be beneficial while deemed to be _unlikely_ to impact existing code.
However, determining whether something falls into bucket 3 would require extensive analysis of real-world scripts.

----

@SeeminglyScience 

> more worried about loss of precision than hitting an actual limit. 

While I can appreciate that perspective, note that loss of precision has always been and continues to be an ever-present danger in PowerShell, due to the implicit widening to `[double]` that occurs whenever an integer operand exceeds the range of `[int]` (`System.Int32`):

```powershell
([int]::MaxValue + 1).GetType().Name # !! 'Double'
```

To give a concrete example of how loss of precision can occur in practice:

```powershell
# !! -> $false, because [long]::MaxValue + 2 is coerced to [double], resulting in loss of precision
# !! The equivalent operation is the following - note the difference in the last digit.
# !!  9223372036854775809ul -eq 9223372036854775808ul
9223372036854775807ul + 2 -eq [ulong] ([long]::MaxValue + 2)
```


By contrast, number _literals_  more helpfully widen their types from `[int]` -> `[long]` -> `[decimal]` -> `[double]`.
Suggesting that `[decimal]` transition to `[bigint]` instead is the subject of:
 *  #13212.

**Comment by mklement0** [comment] 2024-04-04 14:17
@Tragen, let me attempt a pragmatic summary (speaking in no official capacity whatsoever):

* It isn't PowerShell's goal to be consistent with C# - that won't change.

* The WG decision is justifiable, especially from a backward-compatibility perspective.

* The documentation should be amended to describe the existing `[bigint]` behavior; I've created an issue to bring that about:
  * https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11004

* I don't think that a strict-mode warning will be implemented; the next best thing (though not equivalent) is to get a _design-time_ warning, via implementation of a [PSSA](https://github.com/PowerShell/PSScriptAnalyzer) rule, which notably would be surfaced via the PowerShell extension in Visual Studio Code.
   * If you feel strongly enough about this, I encourage you to open a new-rule feature request at https://github.com/PowerShell/PSScriptAnalyzer/issues/new/choose

**Closed** 2024-04-05 21:40 UTC
Labels: WG-Engine, Resolution-By Design, WG-Reviewed
