### ISSUE TITLE
Export-CliXml fails when exporting credential objects

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/PowerShell#2059] opened 2016-08-25 17:27 UTC
**EDIT**: Apologies, this appears to be a duplicate of #1654; presumably Export-CLIXml uses the same .NET classes (or the Cmdlet itself) as ConvertFrom-SecureString.  This is definitely a critical component in a number of community modules and tools.

Steps to reproduce
------------------

```powershell
# Create a credential object
$c = Get-Credential 

# Serialize credential to disk
$c | Export-Clixml ./pw.xml
```

Expected behavior
-----------------

Command should succeed, and encrypt credential on the disk.  Presumably, you'll use something other than DPAPI : )

Actual behavior
---------------

```
Export-Clixml : Unable to load DLL 'CRYPT32.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
At line:1 char:6
+ $c | Export-Clixml ./pw.xml
+      ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-Clixml], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.ExportClixmlComma
   nd
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> gci variable:Is*

Name                           Value
----                           -----
IsLinux                        False
IsOSX                          True
IsWindows                      False
IsCoreCLR                      True
```

Cheers!

**Comment by SteveL-MSFT** [comment] 2016-10-28 18:52
Agree this is dupe of #1654

**Closed by SteveL-MSFT** 2016-10-28 18:52 UTC
Labels: Area-Cmdlets, Issue-Bug, Resolution - Duplicate
