### ISSUE TITLE
Microsoft.Management.Infrastructure can't be loaded in latest .NET 8 Preview 5 build

### ISSUE THREAD

**Issue by mthalman** [PowerShell/PowerShell#19679] opened 2023-05-19 14:14 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a regression between build 8.0.100-preview.5.23267.7 and 8.0.100-preview.5.23269.4. It was discovered when attempting to update the .NET Docker images to the latest build of Preview 5. You can see the CI results with this error here: https://github.com/dotnet/dotnet-docker/pull/4628

This affects Windows only.

Build this Dockerfile:

```Dockerfile
# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS installer

RUN powershell -Command " `
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        `
        # Retrieve .NET SDK
        $sdk_version = '8.0.100-preview.5.23269.4'; `
        Invoke-WebRequest -OutFile dotnet.zip https://dotnetbuilds.azureedge.net/public/Sdk/$sdk_version/dotnet-sdk-$sdk_version-win-x64.zip; `
        mkdir $Env:ProgramFiles\dotnet; `
        tar -oxzf dotnet.zip -C $Env:ProgramFiles\dotnet; `
        Remove-Item -Force dotnet.zip;"

RUN powershell -Command " `
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        `
        # Install PowerShell global tool
        $powershell_version = '7.4.0-preview.3'; `
        Invoke-WebRequest -OutFile PowerShell.Windows.x64.$powershell_version.nupkg https://pwshtool.blob.core.windows.net/tool/$powershell_version/PowerShell.Windows.x64.$powershell_version.nupkg; `
        & $Env:ProgramFiles\dotnet\dotnet tool install --add-source . --tool-path $Env:ProgramFiles\powershell --version $powershell_version PowerShell.Windows.x64; `
        & $Env:ProgramFiles\dotnet\dotnet nuget locals all --clear; `
        Remove-Item -Force PowerShell.Windows.x64.$powershell_version.nupkg; `
        Remove-Item -Path $Env:ProgramFiles\powershell\.store\powershell.windows.x64\$powershell_version\powershell.windows.x64\$powershell_version\powershell.windows.x64.$powershell_version.nupkg -Force;"

RUN setx /M PATH "%PATH%;C:\Program Files\powershell;C:\Program Files\dotnet"

RUN pwsh --version
```

### Expected behavior

```console
It should be able to run `pwsh` without failure.
```

### Actual behavior

```console
Process terminated. The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSObject' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Management.Automation.PSObject..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.get_Properties()
   at System.Management.Automation.SemanticVersion.op_Implicit(SemanticVersion semver)
   at System.Management.Automation.PSVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSVersionInfo.get_PSVersion()
   at System.Management.Automation.PSSnapInReader.ReadRegistryInfo(Version& assemblyVersion, String& publicKeyToken, String& culture, String& applicationBase, Version& psVersion)
   at System.Management.Automation.PSSnapInReader.ReadCoreEngineSnapIn()
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCorePSSnapIn()
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)The command 'cmd /S /C pwsh --version' returned a non-zero code: 2148734499
```
```


### Error details

_No response_

### Environment data

```powershell
Can't run it because pwsh fails to run.
```

**Comment by lbussell** [comment] 2023-05-23 00:03
@mthalman it looks like you had a similar issue in the past - do you recall the solution there? https://github.com/PowerShell/PowerShell/issues/15710

**Comment by mthalman** [comment] 2023-05-23 13:31
> @mthalman it looks like you had a similar issue in the past - do you recall what the solution was there? #15710

I don't know what the solution was. My guess is that the new RID made its way in. I eventually removed the disabling of PowerShell tests because they started working at some point: https://github.com/dotnet/dotnet-docker/pull/3269. If I had to guess, that issue is RID-dependent but this one is likely unrelated to that.

**Comment by daxian-dbw** [comment] 2023-05-24 17:04
My investigation shows it’s a regression in .NET 8-preview.5.

The `Microsoft.Management.Infrastructure.dll` (MMI.dll) can be loaded in preview.5 without a problem by `Assembly.LoadFrom`. However, when running a fxdependent build of pwsh with the preview.5 SDK (through `....\dotnet.exe  ....\pwsh.dll`), the MMI.dll doesn’t get included in the `Trusted_Platform_Assemblies` (TPA) list, and thus it cannot be found when the loading is requested. As a comparison, when running the same fxdependent build of pwsh with the .NET 8-preview.4 SDK, the MMI.dll is included in the TPA list and hence the loading works as expected at pwsh startup.

I want to call out that the `Microsoft.Management.Infrastructure` NuGet package ships `netstandard1.6` managed assemblies (MMI.dll). Maybe the regression in .NET 8 preview.5 is related to the `netstandard1.6` TFM? Just a guess.

**Comment by daxian-dbw** [comment] 2023-05-24 17:21
Issue opened in dotnet/runtime: https://github.com/dotnet/runtime/issues/86713

**Comment by Francisco-Gamino** [comment] 2023-07-11 17:00
Hello @daxian-dbw and @adityapatwardhan -- We need this fix for Azure Functions. Please keep us in the loop.

/cc @anatolib @paulyuk @shreyabatra4

**Comment by AnatoliB** [comment] 2023-07-12 20:49
@daxian-dbw @adityapatwardhan I realize this is not a trivial issue to fix, and thank you for prioritizing it. I just want to explicitly add that delaying this fix may delay PowerShell 7.4 support in Azure Functions. Our intention is to declare GA on the Functions end as soon as possible after the official PowerShell 7.4 GA. But, in order to make this happen, we have to complete some preparation work on the Functions infrastructure ahead of time, and this work is blocked today.

**Comment by daxian-dbw** [comment] 2023-07-17 18:01
@AnatoliB Just FYI, it's also blocking our adoption of the .NET 8 preivew.5.

**Comment by Francisco-Gamino** [comment] 2023-07-19 20:15
Adding @SteveL-MSFT for FYI

**Comment by mthalman** [comment] 2023-08-09 18:38
@daxian-dbw - Can you provide an update on this? Is there a fix planned any time soon?

**Comment by daxian-dbw** [comment] 2023-08-18 16:43
Resolved by https://github.com/PowerShell/PowerShell/pull/20081

**Closed by daxian-dbw** 2023-08-18 16:43 UTC
Labels: Needs-Triage
