### ISSUE TITLE
Powershell not found

### ISSUE THREAD

**Issue by dustinmoris** [PowerShell/PowerShell#5225] opened 2017-10-25 07:07 UTC
The latest Powershell build doesn't seem to be able to execute a Powershell script any longer.

I have two identical builds where one has successfully finished with an older version of Powershell (`6.0.0-beta.8-1.ubuntu.14.04`) and the other fails with the latest version (`6.0.0-beta.9-1.ubuntu.14.04`):

[Successful build](https://travis-ci.org/dustinmoris/Giraffe/jobs/292284619)
[Failed build](https://travis-ci.org/dustinmoris/Giraffe/jobs/292464078)

Please find all relevant details from the full build logs above.

Do I need to change anything? It seems like basic functionality is broken now.

**Comment by SteveL-MSFT** [comment] 2017-10-25 08:20
I believe the problem is that we're in the middle of the beta.9 release with some packages published (which renamed the exe to pwsh), but the full release isn't done yet.  This should be resolved by tomorrow once the beta.9 release is complete.

**Comment by mmattes** [comment] 2017-10-25 20:03
[See for a temporary fix by creating a link](https://github.com/PowerShell/PowerShell/issues/5211#issuecomment-339453008)

**Comment by daxian-dbw** [comment] 2017-10-26 05:18
@dustinmoris The PowerShell Core executable was renamed to be `pwsh` starting from beta.9 release, and that's why the Travis CI failed with the new package. Please see the issue #4214 for the discussion details.

**Comment by SteveL-MSFT** [comment] 2017-10-26 05:47
This should be working now since we've completed the beta.9 release

**Closed by SteveL-MSFT** 2017-10-26 05:47 UTC
Labels: Area-Build, Resolution-Answered

**Comment by sandersaares** [comment] 2017-10-27 08:26
I confirm that I can reproduce the issue - using the "powershell" command does not work, which broke quite a lot of our automation.

**Comment by SteveL-MSFT** [comment] 2017-10-27 08:29
@sandersaares just to be clear, this issue is specifically about a race condition with our Travis-CI script and publishing of beta.9.  Dependency on `powershell` exe name should be discussed under https://github.com/PowerShell/PowerShell/issues/4214 although I would suggest creating a symlink to `pwsh` if you have tooling that expects `powershell`

**Comment by jgreat** [comment] 2017-10-27 19:23
Please update the .deb package to include a link from /opt/microsoft/powershell/6.0.0-beta.9/pwsh to /usr/bin/powershell.   This is breaking VS Code and compatibility between Linux and Windows scripting.
