### ISSUE TITLE
Read-Host cannot provide default input text

### ISSUE THREAD

**Issue by Andrew74L** [PowerShell/PowerShell#19037] opened 2023-01-26 23:26 UTC
### Summary of the new feature / enhancement

Read-Host should accept default input text.
Ex1:
```
$name = Read-Host -Prompt 'Enter user name'
Enter user name: Sydney
$fullname = Read-Host -Prompt 'Enter full name' -Default $name
Enter full name: Sydney|  # pipe represents cursor
```
Ex2:
```
$copyright = Read-Host -Prompt 'Enter copyright text' -Default "(c) $Author. All rights reserved."
Enter copyright text: (c) ContosoAdmin. All rights reserved|
```

**Comment by mklement0** [comment] 2023-01-27 02:25
Good, idea, but it's a duplicate of:

* #14013

**Comment by Andrew74L** [comment] 2023-01-27 02:34
Oh, sorry about that! I entered 'read-host' in the search field and didn't see anything relevant. In case I can't work it out myself, how best to find duplicates before posting a new issue?

**Comment by mklement0** [comment] 2023-01-27 02:45
No worries - it's not always easy to find duplicates.

`read-host` seemingly searches by both `read` and `host` (I'm unclear on the exact rules), use`"read-host"` to search for the whole term, but by itself that searches not just titles but the bodies of and comments on posts, which can yield an overwhelming number of results.

The best way to narrow things down, at least initially, is to start with a _title-only_ search: `in:title "read-host"`

See https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

**Comment by Andrew74L** [comment] 2023-01-27 04:24
Thankyou.

I'll wait ~24hrs, and if there are no further comments, will close this issue.

**Comment by 237dmitry** [comment] 2023-01-27 18:11
You can specify default value in the prompt. Something like this:

```powershell
$prompt = "Enter username (`e[2;3m$env:USER`e[0m)"

$result = Read-Host $prompt
if ($result -eq '') { $result = $env:USER }
$result
```

**Closed** 2023-01-28 20:00 UTC
Labels: Resolution-Duplicate, Issue-Enhancement, Needs-Triage
