### ISSUE TITLE
Invoke-WebRequest is ignoring -MaximumRedirection 0

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#6157] opened 2018-02-14 19:22 UTC
Sometimes when you have a link that is a bit.ly/t.co, you just want to see the actual URL it refers to.  With IWR in Windows PowerShell 5.1, I can do this and it works as I expect (sort of):

```
2:9ms> $res = iwr https://t.co/4OAcNMg9kv -MaximumRedirection 0
iwr : The maximum redirection count has been exceeded. To increase the number of redirections allowed, supply a higher
value to the -MaximumRedirection parameter.
At line:1 char:8
+ $res = iwr https://t.co/4OAcNMg9kv -MaximumRedirection 0
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], Invali
   dOperationException
    + FullyQualifiedErrorId : MaximumRedirectExceeded,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

3:5ms> $res

StatusCode        : 301
StatusDescription : Moved Permanently
Content           : {}
RawContent        : HTTP/1.1 301 Moved Permanently
                    strict-transport-security: max-age=0
                    vary: Origin
                    x-connection-hash: 94474df9124c65999989ad64a0f38026
                    x-response-time: 17
                    Content-Length: 0
                    Cache-Control: private,...
Headers           : {[strict-transport-security, max-age=0], [vary, Origin], [x-connection-hash,
                    94474df9124c65999989ad64a0f38026], [x-response-time, 17]...}
RawContentLength  : 0

5:9ms> $res.Headers

Key                       Value
---                       -----
strict-transport-security max-age=0
vary                      Origin
x-connection-hash         94474df9124c65999989ad64a0f38026
x-response-time           17
Content-Length            0
Cache-Control             private,max-age=300
Date                      Wed, 14 Feb 2018 19:13:29 GMT
Expires                   Wed, 14 Feb 2018 19:18:29 GMT
Location                  https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell-6.0.1-linux-a...
Set-Cookie                muc=d3b55e8c-d0af-472a-8000-bc59b67e290f; Expires=Fri, 14 Feb 2020 19:13:29 UTC; Domain=t.co
Server                    tsa_a
```
And the Location header gives me the final destination.  The only thing I don't like about this experience is the error I get for the 301.  I'm not sure I buy that redirection status codes represent errors.

Anyway, this same scenario does not work on PS Core 6.0.0:

```
74:114ms> $res = iwr https://t.co/4OAcNMg9kv -MaximumRedirection 0
iwr : Response status code does not indicate success: 301 (Moved Permanently).
At line:1 char:8
+ $res = iwr https://t.co/4OAcNMg9kv -MaximumRedirection 0
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

[user/hillr/borrow-update-to-new-api] C:\Git\BitBucket\FLO
75:119ms> $res


StatusCode        : 200
StatusDescription : OK
Content           : {31, 139, 8, 0...}
RawContent        : HTTP/1.1 200 OK
                    Date: Wed, 14 Feb 2018 19:04:42 GMT
                    Accept-Ranges: bytes
                    ETag: "62af342f4264243bca3173c241d19f21"
                    Server: AmazonS3
                    x-amz-id-2: PjFeSMrUze+kswdPjRLgY22ISsjZl88k1HKFvKGRQ16UuI0JMG2T...
Headers           : {[Date, System.String[]], [Accept-Ranges, System.String[]], [ETag, System.String[]], [Server,
                    System.String[]]...}
RawContentLength  : 25675274
RelationLink      : {}



[user/hillr/borrow-update-to-new-api] C:\Git\BitBucket\FLO
76:113ms> $res.Headers

Key                 Value
---                 -----
Date                {Wed, 14 Feb 2018 19:04:42 GMT}
Accept-Ranges       {bytes}
ETag                {"62af342f4264243bca3173c241d19f21"}
Server              {AmazonS3}
x-amz-id-2          {PjFeSMrUze+kswdPjRLgY22ISsjZl88k1HKFvKGRQ16UuI0JMG2TlvEeS2rjpoH96CDukGNZgRc=}
x-amz-request-id    {06FB9DA9874CEF99}
Content-Length      {25675274}
Content-Type        {application/octet-stream}
Last-Modified       {Thu, 25 Jan 2018 19:21:10 GMT}
Content-Disposition {attachment; filename=powershell-6.0.1-linux-arm32.tar.gz}
74:114ms> $res = iwr https://t.co/4OAcNMg9kv -MaximumRedirection 0
iwr : Response status code does not indicate success: 301 (Moved Permanently).
At line:1 char:8
+ $res = iwr https://t.co/4OAcNMg9kv -MaximumRedirection 0
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

[user/hillr/borrow-update-to-new-api] C:\Git\BitBucket\FLO
75:119ms> $res


StatusCode        : 200
StatusDescription : OK
Content           : {31, 139, 8, 0...}
RawContent        : HTTP/1.1 200 OK
                    Date: Wed, 14 Feb 2018 19:04:42 GMT
                    Accept-Ranges: bytes
                    ETag: "62af342f4264243bca3173c241d19f21"
                    Server: AmazonS3
                    x-amz-id-2: PjFeSMrUze+kswdPjRLgY22ISsjZl88k1HKFvKGRQ16UuI0JMG2T...
Headers           : {[Date, System.String[]], [Accept-Ranges, System.String[]], [ETag, System.String[]], [Server,
                    System.String[]]...}
RawContentLength  : 25675274
RelationLink      : {}



[user/hillr/borrow-update-to-new-api] C:\Git\BitBucket\FLO
76:113ms> $res.Headers

Key                 Value
---                 -----
Date                {Wed, 14 Feb 2018 19:04:42 GMT}
Accept-Ranges       {bytes}
ETag                {"62af342f4264243bca3173c241d19f21"}
Server              {AmazonS3}
x-amz-id-2          {PjFeSMrUze+kswdPjRLgY22ISsjZl88k1HKFvKGRQ16UuI0JMG2TlvEeS2rjpoH96CDukGNZgRc=}
x-amz-request-id    {06FB9DA9874CEF99}
Content-Length      {25675274}
Content-Type        {application/octet-stream}
Last-Modified       {Thu, 25 Jan 2018 19:21:10 GMT}
Content-Disposition {attachment; filename=powershell-6.0.1-linux-arm32.tar.gz}
```
Note that even though I specified max redirect of 0 - it still redirected so I don't get the location info I wanted and I have to wait while it downloads the file in order to find this out.

BTW curl has a pretty elegant way of handling this scenario:
```
$ curl -v https://t.co/4OAcNMg9kv
*   Trying 199.59.150.44...
* Connected to t.co (199.59.150.44) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: t.co (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject:
*        start date: Thu, 15 Dec 2016 00:00:00 GMT
*        expire date: Thu, 20 Dec 2018 12:00:00 GMT
*        issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 Extended Validation Server CA
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET /4OAcNMg9kv HTTP/1.1
> Host: t.co
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< cache-control: private,max-age=300
< content-length: 0
< date: Wed, 14 Feb 2018 19:21:18 GMT
< expires: Wed, 14 Feb 2018 19:26:18 GMT
< location: https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell-6.0.1-linux-arm32.tar.gz
< server: tsa_a
< set-cookie: muc=cc75759f-1809-439f-9055-708995ce87a7; Expires=Fri, 14 Feb 2020 19:21:18 UTC; Domain=t.co
< strict-transport-security: max-age=0
< vary: Origin
< x-connection-hash: f78970e680cc89a5598d292530b213cf
< x-response-time: 6
<
* Connection #0 to host t.co left intact
```

**Comment by markekraus** [comment] 2018-02-14 22:06
This has come up a few times. `HttpClient` treats 300 level responses as an unsuccessful response. The web cmdlets interpret that as a failure and produces a terminating error. It's not that `MaximumRedirection 0` is ignored, it's that it is producing an error and your `$res` is stale with the previous succesful `$res = irw ...` call. Toe verify, please run `$res = $null` before your `$res = irw ...` call

```powershell
$res = $null
$res = Invoke-WebRequest -uri 'https://t.co/4OAcNMg9kv' -MaximumRedirection 0
$null -eq $res
```

Should be `True`.


You can get the location like this:

```powershell
Invoke-WebRequest -uri 'https://t.co/4OAcNMg9kv' -MaximumRedirection 0 -ErrorVariable Err
$err[0].InnerException.Response.Headers.Location
```

or

```powershell
Try {
    Invoke-WebRequest -uri 'https://t.co/4OAcNMg9kv' -MaximumRedirection 0
} catch {
    $_.Exception.Response.Headers.Location
}
```

In previous discussions, I leaned on this actually being a correction of bad behavior, If I tell the command I want it to not redirect by supplying `-MaximumRedirection 0`, then I expect it to error if it tries to redirect, The behavior in 5.1 is odd to me...  it displays an error but still populates the variable with a result. To me, this is a terminating error and the behavior in 6.0.0 is correct.

**Comment by rkeithhill** [comment] 2018-02-14 23:03
It's nice to have a workaround but really, this is a bit of spew don't you think?
```posh
Invoke-WebRequest -uri 'https://t.co/4OAcNMg9kv' -MaximumRedirection 0 -ErrorVariable Err
$err[0].InnerException.Response.Headers.Location
```
By specifying `-MaximumRedirection 0` in this scenario, I'm indicating that I **want** the 301 redirect response (headers and content).  That's not that uncommon of a thing to do especially when you're trying to resolve the target of bit.ly style URL.  FWIW I much prefer the PowerShell 5.1 behavior in this case.  At the very least, there should be a way to accomplish this in PS Core without having to root around in exception info.  That just not intuitive at all.  Could we special case the `-MaximumRedirection 0` scenario - catch the HttpClient exception and if a 3xx status, not report as an error?  Or maybe we should have another parameter??  What I'm after is something like `curl -v <url>` provides.  Our verbose output is, well, lacking.  Maybe we should have a `-Trace` switch that writes out at least request/response header info?

**Comment by markekraus** [comment] 2018-02-15 01:04
Yea, This is a difference of opinion. I have times where I don't want to redirect.. and in those times I'm specifying `-MaximumRedirection 0`. In 5.1 this behavior was bad...

```powershell
Try { 
    Invoke-WebRequest -uri 'https://t.co/4OAcNMg9kv' -MaximumRedirection 0
} catch {
    'Caught'
}
```

doesn't catch, spits out both the response and an error.

```powershell
Try { 
    Invoke-WebRequest -uri 'https://t.co/4OAcNMg9kv' -MaximumRedirection 0 -ErrorAction Stop
} catch {
    'Caught'
}
```

Just spits out the response... what?

In 6.0.0 it at least makes sense now. it's a terminating error so it catches. 

> At the very least, there should be a way to accomplish this in PS Core without having to root around in exception info.

I'd have to dig around for the other issue on this, but on option would be to add an option to treat all responses as successful. There are times when you want to test a 404 page, for example, and doing that currently is a serious pain. Especially when that 404 is a JSON object. That, or allow specifying a collection of response codes to be considered successful... something like `-SuccessStatusCodes 200, 301` that way a 404 would still be a terminating error, but 200 and 301 would be successful and return the response object.

I don't think removing the terminating error nature as it exists in core is the right direction. `-MaximumRedirection 0` and a single redirect should be an error and nothing more by default, IMO.

>  What I'm after is something like curl -v <url>

It's been suggested. Some of that output is possible, some if it is not (for example, we cannot get the SSL information). The general consensus is that the verbose output needs work. Implementing some of that is trivial.. and some of it is not. There are several ways in which we make the HTTP calls and in some of those scenarios, we don't even have access to the intermediary headers (for example, hop 2 of 3). To implement it we would have to step back from the default behavior of HttpClient and not allow it to redirect at all and handle all the redirects manually ourselves (which introduces some overhead). This all also gets complicated by some of the other features. Automatic retries, for example. 

I don't have a good solution to all of this. I agree the verbosity needs work, but improving it will likely introduce bugs as we will need to reinvent the wheel and mimic much of the default behavior if HttpClient. This is already causes issues when we introduced the removal of authorization headers on redirect.

**Comment by rkeithhill** [comment] 2018-02-15 01:13
`-SuccessStatusCodes 200, 301` or something to that effect sounds reasonable to me.  RE improved verbose output - I'll try to be patient.  :-)

**Comment by markekraus** [comment] 2018-04-17 14:03
Closing as is duplicate of #4534

**Closed by markekraus** 2018-04-17 14:03 UTC
Labels: Area-Cmdlets-Utility, Issue-Discussion
