### ISSUE TITLE
Wrong module is auto-loaded when using unqualified cmdlet and multiple modules contain a cmdlet by that name

### ISSUE THREAD

**Issue by conioh** [PowerShell/PowerShell#19657] opened 2023-05-15 14:53 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install the [VMWare PowerCLI](https://developer.vmware.com/web/tool/vmware-powercli) module. Available in the PowerShell gallery at: https://www.powershellgallery.com/packages/VMware.PowerCLI
2. Open a new PowerShell instance with standard settings (including, but not limited to, `PSModuleAutoloadingPreference` being undefined). [ Tip: Use `-NoProfile` if your profile load any module or modifies any settings. ]
3. Run `Get-VM`.

### Expected behavior

```console
> Get-VM

Name                             State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
----                             ----- ----------- ----------------- ------   ------             -------
Ubuntu                           Off   0           0                 00:00:00 Operating normally 11.0
Ubuntu 22.04 LTS                 Off   0           0                 00:00:00 Operating normally 11.0
Windows 10 Enterprise 21H1       Off   0           0                 00:00:00 Operating normally 10.0
.......
```

### Actual behavior

```console
> Get-VM
WARNING: Please consider joining the VMware Customer Experience Improvement Program, so you can help us make PowerCLI a better product. You can join using the following command:

Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $true

VMware's Customer Experience Improvement Program ("CEIP") provides VMware with information that enables VMware to improve its products and services, to fix problems, and to advise you on how best to deploy and use our products.  As part of the CEIP, VMware collects technical information about your organization’s use of VMware products and services on a regular basis in association with your organization’s VMware license key(s).  This information does not personally identify any individual.

For more details: type "help about_ceip" to see the related help article.

To disable this warning and set your preference use the following command and restart PowerShell:
Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $true or $false.
Get-VM: 15/05/2023 17:49:56     Get-VM          You are not currently connected to any servers. Please connect first using a Connect cmdlet.
```

### Error details

```console
> Get-Error

Exception             :
    Type              : VMware.VimAutomation.Sdk.Types.V1.ErrorHandling.VimException.ViServerConnectionException
    ErrorId           : Core_BaseCmdlet_NotConnectedError
    ErrorCategory     : ResourceUnavailable
    RecommendedAction : Connect to server.
    Severity          : Error
    TargetSite        :
        Name          : ThrowNotConnectedError
        DeclaringType : VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.MessageHelper
        MemberType    : Method
        Module        : VMware.VimAutomation.Sdk.Util10Ps.dll
    Message           : 15/05/2023 17:49:56     Get-VM          You are not currently connected to any servers. Please connect
first using a Connect cmdlet.
    Data              : System.Collections.ListDictionaryInternal
    Source            : VMware.VimAutomation.Sdk.Util10Ps
    HResult           : -2146232832
    StackTrace        :
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.MessageHelper.ThrowNotConnectedError()
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ConnectionDispatchHelper.DispatchObjectsHelper(IList`1
connectionList, IList`1 moListFromCmdletParameter, Dictionary`2 runlist, Dictionary`2 connectionIdToUidBourneIdList,
Boolean isConnectionListExplicit)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ConnectionDispatchHelper.DispatchObjects(ParallelConnectionExecutor
executor, UidDispatchHelper uidDispatchHelper, IList`1 connectionList, Boolean isConnectionListExplicit, IList`1
moListFromCmdletParameter, String moListFromCmdletParameterName, Boolean isServerParameterObnOnly)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.BaseCmdlet.ProcessRecordErrorHandled()
   at VMware.VimAutomation.ViCore.Util10Ps.BaseCmdlet.BaseCmdlet.ProcessRecordErrorHandled()
CategoryInfo          : ResourceUnavailable: (:) [Get-VM], ViServerConnectionException
FullyQualifiedErrorId : Core_BaseCmdlet_NotConnectedError,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetVM
InvocationInfo        :
    MyCommand        : Get-VM
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Get-VM
    PositionMessage  : At line:1 char:1
                       + Get-VM
                       + ~~~~~~
    InvocationName   : Get-VM
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional information

This is not the same issue as a function taking precedence over a cmdlet [as documented](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.3). In this case both names refer to a cmdlet:

```powershell
> Get-Command -Name "Get-VM" -All | ft -AutoSize

CommandType Name   Version         Source
----------- ----   -------         ------
Cmdlet      Get-VM 2.0.0.0         Hyper-V
Cmdlet      Get-VM 13.0.0.20797821 VMware.VimAutomation.Core
```

PowerShell decided to use `VMware.VimAutomation.Core\Get-VM` over `Hyper-V\Get-VM` contrary to reasonable exepctations. Perhaps because `[Version]"13.0.0.20797821" -gt [Version]"2.0.0.0"` or maybe because `"VMware.VimAutomation.Core" -gt "Hyper-V"`. 

I couldn't find any documentation saying how the [module auto-load feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-7.3#module-auto-loading) assigns priorities in such a case so I don't know if there even is a rule and it's not arbitrary. Either way - assigning arbitrary priorities is unexpected and assigning the observed priorities is unexpected.

Perhaps it's difficult to set a rule that would do the expected thing in all use cases. Allowing the user to set precedence of module load is probably the best approach.

**Comment by MartinGC94** [comment] 2023-05-15 15:26
You say "Contrary to reasonable expectations" but why would the expectation be that it chooses Hyper-V over VMware in this instance? I don't know how it chooses the right module but the version difference you mention seems like a pretty good reason for it to go with VMware. Another reason could be that VMware is a user installed module VS a system bundled module but you could argue both ways here.

Personally I would just treat it as random/undefined behavior and force myself to use the module qualified name, or in a script, make sure to add a `#requires -Modules` statement to ensure the right module is loaded beforehand.

**Comment by conioh** [comment] 2023-05-15 15:48
> You say "Contrary to reasonable expectations" but why would the expectation be that it chooses Hyper-V over VMware in this instance?

What my reasons are is irrelevant. That's why I said:

> Either way - assigning arbitrary priorities is unexpected and assigning the observed priorities is unexpected.

Even if you don't agree with the order I think is correct, doing stuff randomly is unexpected and wrong.

Consider what would happen if someone made a module with cmdlets such as `Write-Warning` and `Select-Object`. It is idiomatic _not_ to specify their full names, so using them in every module can do anything under the approach you suggest.

> I don't know how it chooses the right module but the version difference you mention seems like a pretty good reason for it to go with VMware.

Obviously not. Between different version of the same module the newer versions should win. Comparing version numbers of different modules is senseless. Ubuntu 16.04 isn't newer (or "higher") than Debian 11.7.

> Another reason could be that VMware is a user installed module VS a system bundled module but you could argue both ways here.

That's an interesting option I hadn't considered, and indeed I have PowerCLI installed in user scope. At the very least this should be documented, but as you said yourself, you could argue both ways, and there's the issue I mentioned above.

> Personally I would just treat it as random/undefined behavior and force myself to use the module qualified name, or in a script, make sure to add a `#requires -Modules` statement to ensure the right module is loaded beforehand.

Great. So all the modules that use `Write-Warning`, `Select-Object` and `Select-String` without qualifying them should do random/undefined behavior? I certainly think _that's_ unexpected and maintain that this is self-evident.

https://github.com/search?q=repo%3AAzure%2Fazure-powershell+%22Select-Object%22&type=code

**Comment by jhoneill** [comment] 2023-05-15 16:10
> What my reasons are is irrelevant. That's why I said:
> 
> > Either way - assigning arbitrary priorities is unexpected and assigning the observed priorities is unexpected.

$Env:PSModulePath says where to search for commands.  By default the order is

1. Modules installed for the current user  
2. Modules installed for all users of the current system
3. Modules provided with PowerShell (for PowerShell 7)
4. Models provided with the OS (and also with Windows PowerShell) 

> Even if you don't agree with the order I think is correct, doing stuff randomly is unexpected and wrong.

Someone I worked with used to say "What the software does is not random, you just can't see the pattern" . It is working from most specific definition of the command (user only) to most general (installed with the OS).  

> Consider what would happen if someone made a module with cmdlets such as `Write-Warning` and `Select-Object`. It is idiomatic _not_ to specify their full names, so using them in every module can do anything under the approach you suggest.

Yes, and that is by design - although because they are in the _utility_ module, that will often be loaded by something else. But if you take something like `start-transcript` you can replace it with your own `start transcript` command if you so choose.  There have been comments in the past that if users can be tricked into installing a malicious module, then it can replace common commands with harmful ones (true) but the ability to replace a command is a key one.

**Comment by conioh** [comment] 2023-05-15 17:41
> $Env:PSModulePath says where to search for commands. By default the order is
> 
> 1. Modules installed for the current user
> 2. Modules installed for all users of the current system
> 3. Modules provided with PowerShell (for PowerShell 7)
> 4. Models provided with the OS (and also with Windows PowerShell)

And what happens if two modules that provide a cmdlet with the same name are in the same level?

> Someone I worked with used to say "What the software does is not random, you just can't see the pattern" . It is working from most specific definition of the command (user only) to most general (installed with the OS).

Someone I never worked with but kind of knows what he's doing used to say (paraphrasing): "Well, sure, there's an underlying technical explanation for any behavior, but if it's not _contractual_ you should count on it." You can look for the exact quote in his blog: https://devblogs.microsoft.com/oldnewthing/

Is there a contract that says what will happen? Are modules in each of the folder in `$Env:PSModulePath` tried in alphabetical order? Some other order? Where is it documented? Where is the contract?

> Yes, and that is by design - although because they are in the _utility_ module, that will often be loaded by something else. But if you take something like `start-transcript` you can replace it with your own `start transcript` command if you so choose. There have been comments in the past that if users can be tricked into installing a malicious module, then it can replace common commands with harmful ones (true) but the ability to replace a command is a key one.

Citation needed. Your `Start-Transcript` is a great example of cherry picking, but I have a hard time believing anyone (up to a single digit number of people in the world) who wrote `Select-Object` rather than `Microsoft.PowerShell.Utility\Select-Object` did that because he expected that the user or third parties could override this cmdlet with _useful_ implementations.

**Comment by ThomasNieto** [comment] 2023-05-15 17:53
> And what happens if two modules that provide a cmdlet with the same name are in the same level?

It would return the command from the module when sorted alphabetically first. I actually do this in my own module to replace a built-in one. I have my module name starting with "A" so discovery finds it first before "P".

**Comment by conioh** [comment] 2023-05-15 19:40
> While I would expect that workaround to work, is there any reason you cannot just run `Import-Module` or in the script put a `#requires -modules X` so that command discovery isn't needed?

Because that won't solve the problem:
![image](https://github.com/PowerShell/PowerShell/assets/10606081/227eeb6c-ece5-4a66-8cdf-9f07fe75d7c7)

Perhaps you what you really wanted to suggest is to qualify the cmdlet names.
That might work, sometimes, but depends on the details of what I write, what I only use and how much control I have over the environment.

If I'm writing a script/module I can qualify all cmdlets names. That would make the code look pretty awful but at least it's possible.
But what happens when I use a third module (let's call it X), one that calls `Get-VM` expecting it to be `Hyper-VM\Get-VM` because they didn't know about the VMware module?

Or even worse, perhaps they knew about it, but mistakenly thought that adding `#Requires` like you suggested fixes the issue, but I've intentionally imported the VMware module _after_ the Hyper-V module to make its cmdlets shadow over the Hyper-V cmdlets. I didn't know and didn't expect module X to break because of that.

What should I do in that case? "Only run module X in a specially designated PowerShell session in which you didn't import other modules". That's not a solution and it doesn't scale. That's not a solution because what makes PowerShell useful is the synergy between modules, even if those modules weren't explicitly designed to work together. It doesn't scale because there's no limit to how many surprises of this sort can happen and when.

If we're saying "run command A in session 1 and put its output in `i.txt`, then run command B in a distinct session, 2, as input for B use the file `i.txt` and put its output in `ii.txt`, then run command C in yet another session, 3, and as input for it use `ii.txt` and so on, because you can never safely run more than one command in a given session" not only is it not PowerShell, it's even worse than using Unix-like shells.

**Comment by ThomasNieto** [comment] 2023-05-15 20:00
You can add the [-NoClobber](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.3#-noclobber) parameter to `Import-Module` to prevent the new module from overwriting your existing commands.

I'm not sure why you imported the VMWare module as well. Do you need both modules imported? If you need both modules loaded in the same session you can fully-qualify your commands as you mention or load one/both of the modules with a [prefix](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.3#-prefix) `Import-Module Hyper-v -Prefix X` and use prefixed commands in your script.

**Comment by conioh** [comment] 2023-05-15 20:30
> You can add the [-NoClobber](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.3#-noclobber) parameter to `Import-Module` to prevent the new module from overwriting your existing commands.

But...

>>Or even worse, perhaps they knew about it, but mistakenly thought that adding `#Requires` like you suggested fixes the issue, but I've **_intentionally_** imported the VMware module after the Hyper-V module to make its cmdlets **_shadow_** over the Hyper-V cmdlets. I didn't know and didn't expect module X to break because of that.

Emphasis added.

> I'm not sure why you imported the VMWare module as well. Do you need both modules imported?

Perhaps I'm managing both VMware and Hyper-V virtual machines and at that moment I was doing more operations against VMware server so I've decided to let it take over. Or perhaps I've decided that if I have to use a qualified name for one of the `Get-VM` cmdlets I prefer it to be the shorter `Hyper-V\Get-VM` rather than the long `VMware.VimAutomation.Core\Get-VM`. Or perhaps some other reason.

Can we focus on the general issue instead of the example and why I shouldn't be importing these two specific modules simultaneously?

> If you need both modules loaded in the same session you can fully-qualify your commands as you mention or load one/both of the modules with a [prefix](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.3#-prefix) `Import-Module Hyper-v -Prefix X` and use prefixed commands in your script.

But ...

>>It doesn't scale because there's no limit to how many surprises of this sort can happen and when.
>> 
>> If we're saying "run command A in session 1 and put its output in `i.txt`, then run command B in a distinct session, 2, as input for B use the file `i.txt` and put its output in `ii.txt`, then run command C in yet another session, 3, and as input for it use `ii.txt` and so on, because you can never safely run more than one command in a given session" not only is it not PowerShell, it's even worse than using Unix-like shells.

Sure. If I know in advance that module X depends on `Get-VM` being `Hyper-V\Get-VM` I can import the VMware module with a prefix. But that requires me knowing that in advance. And what if some other clever module, Y, depends on `Get-VMHost` being PowerCLI's `VMware.VimAutomation.Core\Get-VMHost` and won't work if I import it with a prefix?

The more I think about it, it almost sounds like the kind of problem C++ namespace were intended to solve.

**Comment by jhoneill** [comment] 2023-05-16 12:44
> > > Or even worse, perhaps they knew about it, but mistakenly thought that adding `#Requires` like you suggested fixes the issue, but I've **_intentionally_** imported the VMware module after the Hyper-V module to make its cmdlets **_shadow_** over the Hyper-V cmdlets. I didn't know and didn't expect module X to break because of that.
> 
> Emphasis added.

`#requires` says the module must be loaded. It is, so that is fine. However the script didn't qualify 'load the cmdlet from this module'  - because the author didn't think it would ever _not_ be the first or only name found. Your loading a competing `get-vm` over the top of the one they wanted was never considered.  
If things were done differently it wouldn't be any better. Your complaint is "I overwrote my Hyper-V command with a VMWare one and my Hyper-V script doesn't work" Well no, but changing things to "I overwrote my Hyper-V command with a VMWare one and my VMWare script doesn't work" is just inverting the badness. PowerShell allows you to overwrite commands and one will work and one won't. Never mind the complications of alias/function/cmdlet precedence.  


> 
> > I'm not sure why you imported the VMWare module as well. Do you need both modules imported?
> 
> Perhaps I'm managing both VMware and Hyper-V virtual machines and at that moment I was doing more operations against VMware server so I've decided to let it take over. Or perhaps I've decided that if I have to use a qualified name for one of the `Get-VM` cmdlets I prefer it to be the shorter `Hyper-V\Get-VM` rather than the long `VMware.VimAutomation.Core\Get-VM`. Or perhaps some other reason.
> 
> Can we focus on the general issue instead of the example and why I shouldn't be importing these two specific modules simultaneously?

The general issue is (a) The first match on ps module path is loaded (b) when names are duplicated and not qualified, alias beats function, function beats cmdlet, and cmdlet beats external program. The last alias / function loaded over writes an earlier one. Two loaded DLLs can contain compiled cmdlets with the same name, if not qualified to a module the most recently loaded module is selected first when names of compiled cmdlets are duplicated. 

Authors are told to take steps to avoid name clashes. I was responsible for the first Hyper-V commands in PowerShell - the product team wrote their own later but kept my naming - so you can blame me for the use of Get-VM and not Get-HyperVVM. I was on good terms with the people writing for VMWare, and they didn't see any reason to use Get-VMwareVM  and we both regard the chances of both modules being loaded in the same session as too tiny to make it worth changing our names. 
But Other things do deliberately replace - or at least wrap - the built in functions. It was always part of PowerShell's design to allow this . But if authors don't take and users don't understand the risk of a clash problems can result.  

Possibly too many people have been too-used to how it works for too long and regard it as not needing explanation when really the docs fall a little short.

**Comment by jhoneill** [comment] 2023-05-18 12:09
@kilasuit  In this case the user has a script which might need the command as implemented by module X or as implemented by module Y.  His complaint is he wanted X but got Y.  How is PowerShell meant to know. ? If it selected X people who wanted Y (possibly the same user on another occasion) would complain.
The process is deterministic, even if not always understood. But I'd be amazed if there is a way which can please more of the people more of the time.   Different people at different times, sure.  It's for the Engine WG to say for definite of course.

**Comment by kilasuit** [comment] 2023-05-18 12:53
@jhoneill from the repro steps provided this reads to me that it's an interactive experience & not a non-interactive experience which would have differing steps

My reasoning for not assigning this to WG-Interactive-Console (at least not yet) was that I personally feel that this is something we've already got processes in place to manage & work around this user expectation. Personally if I needed both VM Ware and Hyper-VM cmdlets I'd as mentioned use a prefix to differentiate between them in a manner that **ensures** the correct module is always loaded by auto-module loading even if that means creating a wrapper module that does this for me, due to being both lazy and defensive in my ways of working. Then `Get-HVM` or `Get-VVM` would align with `Get-AzVM` for Azure or `Get-EC2Instance` for AWS (I think that's the right command)

If this however is due to a non-interactive scenario then my above solution would also work to, however the repo steps did not mention this was non-interactive and if so that should be in another issue that is linked to this one for tracking purposes or the repro steps updated so that instead of scrolling thru loads of comments this is all captured in the first comment in the issue, which I cannot do but members of the PowerShell team may be able to.

 @conioh if you want to ensure which module is loaded in your scripts in this case
1. Don't rely on #Requires as it doesn't (as far as I know) stop other modules being autoloaded in any way at all
2. It doesn't allow for loading with prefixes - which Import-Module does
3. It's actually slower on execution that using Import-Module & defensively coding for it being on a machine or needing to be installed on a machine in your scripts in my experiences as this is because Requires doesn't at present allow to specify to install if unavailable whilst an Import then install if not present loop does allow for this.

**Comment by kilasuit** [comment] 2023-05-18 13:07
One other minor point from @ThomasNieto comment 
> #requires -modules X so that command discovery isn't needed?

This in my experience doesn't stop the issue of commands from other modules being named the same being run instead of the one that you actually want and the only ways I know around this is by Module Qualified calls or by using Prefixes on module import & has been this way since v3 - unless this has changed in more recent v6/v7 times but I don't think it has - happy though to be proven wrong

**Comment by ThomasNieto** [comment] 2023-05-18 13:23
@kilasuit No, it does not but usually is good enough most of the time. As you mention and has been stated by others the only way is to use module qualified or by using prefixes.

There is one enhancement that could be implemented as brought up by the OP in this issue. The use of module qualified command names is tedious and not very pretty in scripts. What could be done is having a way in scripts to define that I'm using commands from this module as if they were module qualified.

How I see this working is as follows:

1. Lets say a `using -commands Hyper-V` is defined (note I don't like naming things or don't think `using` or `commands` is the best option just an example)
2. Then at runtime, the engine lookups all the commands shipped by `Hyper-V` and then any commands in the script from that module would be treated as module qualified.
3. Any commands in the script that aren't in the module are discovered as normal.

**Comment by SeeminglyScience** [comment] 2023-05-18 16:32
> 1. Lets say a `using -commands Hyper-V` is defined (note I don't like naming things or don't think `using` or `commands` is the best option just an example)

Wouldn't `Import-Module Hyper-V` solve this? I guess if they're both imported it can be problematic for specific commands but you can always do `${alias:Get-VM} = 'Hyper-V/Get-VM'`

**Comment by ThomasNieto** [comment] 2023-05-18 16:45
> Wouldn't `Import-Module Hyper-V` solve this? I guess if they're both imported it can be problematic for specific commands but you can always do `${alias:Get-VM} = 'Hyper-V/Get-VM'`

That wouldn't work, look at the examples earlier in the thread about the user importing `Hyper-V` first and than `VMWare` afterwards clobbers the command, I guess you could use `-Force` command to reclobber the command to get `Hyper-V` back.

As for your alias suggestion I tried that as a workaround when this was brought up, that would work if your script requires `Hyper-V` but if you call a script that requires `VMWare` it would impact that script since aliases aren't script scoped. I'm not aware of a way to scope the alias.

**Comment by SeeminglyScience** [comment] 2023-05-18 16:52
> As for your alias suggestion I tried that as a workaround when this was brought up, that would work if your script requires `Hyper-V` but if you call a script that requires `VMWare` it would impact that script since aliases aren't script scoped. I'm not aware of a way to scope the alias.

They're scoped the same as any other session state item. So as long as the second script is not dot sourced, it can follow the same pattern of setting an alias at the top.

```powershell
& {
    ${alias:Get-VM} = 'Hyper-V\Get-VM'
    (Get-Alias Get-VM).Definition
    & {
        ${alias:Get-VM} = 'VMware.VimAutomation.Core\Get-VM'
        (Get-Alias Get-VM).Definition
    }

    (Get-Alias Get-VM).Definition
}
```

`Set-Alias` also has a `-Scope` parameter you can specify `script` to if desired.

**Closed** 2023-11-22 10:54 UTC
Labels: WG-Engine, Needs-Triage, Resolution-No Activity
