### ISSUE TITLE
Powershell version 7.4 does not support script block logging and no logs seen in eventviewer

### ISSUE THREAD

**Issue by defaultshr** [PowerShell/PowerShell#21339] opened 2024-03-13 12:22 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Configure group policy for script block logging for powershell.

### Expected behavior

```console
logs in eventviewer under "Application and Services logs" -> "Microsoft" -> "Windows" -> "PowerShell" -> Operational
```

### Actual behavior

```console
No logs seen in the eventviewer for 7.4 powershell. However, we can see for older 5.x powershell.
```

### Environment data

```powershell
PS C:\Program Files\PowerShell\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment] 2024-03-13 13:37
PowerShell does support script block logging, it just logs them in a different location: `PowerShellCore/Operational`. IIRC one of the MSI install options asks if you want logging enabled, maybe you disabled that?

**Comment by gwsales** [comment] 2024-03-13 14:35
The docs aren't updated to reflect the needed steps to enable logging.
 
Check out issue #20769 I created. 

The install settings to enable logging doesn't actually enable logging, you have to set some registry keys in order to turn it on, the GPO settings aren't currently working.

**Comment by daxian-dbw** [comment] 2024-03-18 23:07
If you are using group policy, be noted that PowerShell 7+ are using different registry keys from Windows PowerShell.
 https://github.com/PowerShell/PowerShell/blob/4faf52726dd16ea97aaafa8faa5fff4c5c824f93/src/System.Management.Automation/engine/Utils.cs#L783-L792

However, PowerShell 7+ allows falling back to the Windows PowerShell group policy for each of them, by setting a registry key named `UseWindowsPowerShellPolicySetting` to `1` for that particular logging policy:

https://github.com/PowerShell/PowerShell/blob/4faf52726dd16ea97aaafa8faa5fff4c5c824f93/src/System.Management.Automation/engine/Utils.cs#L932-L940

Please give it a try and see if it enables the module logging for you.

**Comment by daxian-dbw** [comment] 2024-03-19 21:30
Duplicate of #20769

**Closed** 2024-03-20 22:18 UTC
Labels: Resolution-Duplicate, Needs-Triage
