### ISSUE TITLE
Command line parsing bug: spaces and trailing backslash

### ISSUE THREAD

**Issue by akervinen** [PowerShell/PowerShell#4358] opened 2017-07-27 11:43 UTC
This has already been posted on UserVoice ([here](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/20102977-command-line-parsing-bug-spaces-and-trailing-slas)), but appears to still happen in 6.0.

Steps to reproduce
------------------

Using any .exe capable of outputting its command line arguments:
```powershell
PS X:\scratch> .\ps-args-test.exe .\test1\ '.\test 2\' .\test1\
```
Auto-completion uses this format with a trailing backslash, so it's expected to work correctly.

Expected behavior
-----------------

```none
.\test1\
.\test 2\
.\test1\
```

Actual behavior
---------------

```none
.\test1\
.\test 2" .\test1\
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2017-07-28 01:09
@iSazonov: 

This is only indirectly related to IntelliSense (which _suggests_ passing the arguments like that).

The real issue is how the command line is rebuilt _behind the scenes_ by PowerShell:

Argument list `.\test1\ '.\test 2\' .\test1\` is translated to `.\test1\ ".\test 2\" .\test1\` behind the scenes, which any external utility that uses `\` as the escape character (most of them) parses as reflected in the initial post, causing the initial argument partitioning to be misinterpreted:

* The 2nd `"` in `".\test 2\"`, due to being preceded by `\` is interpreted as an _escaped_ `"`, causing the remainder of the string - despite a then-missing closing `"` to be interpreted as part of the same argument.

---

The - cumbersome - **workaround** on **Windows** is to add an extra `\`, though, given that PowerShell does re-quoting behind the scenes, the **fix** is to let _PowerShell_  do  that _automatically_:

    > .\ps-args-test.exe .\test1\ '.\test 2\\' .\test1\  # Note the '\\'

The - proper, unfortunately-hypothetical-as-of-now - **fix** on **Unix** platforms is to pass the arguments as an _array of literals_ to the target utility, as is the norm on Unix platforms, bypassing such issues altogether.

cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment] 2017-07-28 22:21
Unless I hear otherwise, this doesn't seem to be a common use case.  I think we can fix in 6.1.0 unless someone from the community submits a PR.

**Comment by akervinen** [comment] 2017-07-30 21:29
I'd argue it's common since it happens every time I auto-complete a directory name with a space unless I remove the trailing slash manually. My example was a bit incomplete I think, since the extra quote is also inserted with just one argument.

```powershell
PS X:\scratch> .\ps-args-test.exe '.\test 2\'
```
```
.\test 2"
```

A shell that has a broken auto-complete for directories is... inconvenient.

**Comment by SteveL-MSFT** [comment] 2017-07-30 23:46
@akervinen I see, every time with a space is definitely a concern

**Comment by daxian-dbw** [comment] 2017-08-04 22:00
The trailing slash is added by PSReadline, but by powershell tab completion:
```
PS> $s = TabExpansion2 -inputScript 'git t' -cursorColumn 'git t'.Length
PS> $s.CompletionMatches[0].CompletionText
'.\test 2'
```
So this is more of a PSReadline issue, maybe PSReadline should have an option to no adding trailing slash for directories?

**Comment by mklement0** [comment] 2017-08-04 22:39
@daxian-dbw: 

Not appending a `\` would be band-aid, especially given that nothing stops a user from _typing_ a path that ends in `\`.

There is no good reason not to properly support passing of arguments with whitespace that end in `\`.

At the risk of repeating myself: The problem is a fundamental problem with how PS rebuilds the command line behind the scenes on Windows and that it even _does so at all_ on Unix platforms, and it should be fixed at that level.

**Comment by daxian-dbw** [comment] 2017-08-04 22:50
@mklement0 I see your point now.
The problem is in `NativeCommandParameterBinder.cs`, which cause the argument passed in native commands like this:
```
PS> testexe.exe -echoargs '.\test 2\'
Arg 0 is <.\test 2">
```

**Comment by JVimes** [comment] 2017-09-12 15:48
Just lost an hour wondering why git status wouldn't work with -C. And a number of RoboCopy folks [lost time](https://github.com/RamblingCookieMonster/PSDeploy/issues/42) to it.

This use case gets hit!

**Comment by daxian-dbw** [comment] 2017-09-19 00:09
> The - cumbersome - workaround on Windows is to add an extra \, though, given that PowerShell does re-quoting behind the scenes (as is necessary on Windows), the fix is to let PowerShell do that automatically:
>      .\ps-args-test.exe .\test1\ '.\test 2\\' .\test1\  # Note the '\\'

@mklement0 Do you think we should do this fix for now or shall we wait until #23592 is addressed?

I'm trying to do this fix now but having some trouble figuring out the reasonable behavior handling the trailing backslashes of an arg string. When the arg string needs to be quoted, the trailing backslashes will escape each other and if there are odd number of backslashes, then the closing quote will be misinterpreted, for example:
```powershell
PS> testexe.exe -echoargs 'test \'
Arg 0 is <test ">
PS> testexe.exe -echoargs 'test \\'
Arg 0 is <test \>
PS> testexe.exe -echoargs 'test \\\'
Arg 0 is <test \">
PS> testexe.exe -echoargs 'test \\\\'
Arg 0 is <test \\>
```
Now, we think the resulting `"` is confusing, and the ending `\` should be preserved when passing to the native command. As a result, we will see behaviors like this:
```powershell
PS> testexe.exe -echoargs 'test \'
Arg 0 is <test \>
PS> testexe.exe -echoargs 'test \\'
Arg 0 is <test \>
PS> testexe.exe -echoargs 'test \\\'
Arg 0 is <test \\>
PS> testexe.exe -echoargs 'test \\\\'
Arg 0 is <test \\>
```
You can see that when there is an odd number of backslashes, the ending backslash will be preserved, which makes the odd number of trailing backslashes always behave as _(odd number + 1)_ trailing backslashes. Does this look like a reasonable behavior?

**Comment by mklement0** [comment] 2017-09-19 00:50
@daxian-dbw:

My sense is that once [this RFC proposal](https://github.com/PowerShell/PowerShell-RFC/pull/90) by @TSlivede is implemented, it will cover this scenario too, so we probably don't need a separate fix for this specific issue.

For background, see https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-325231274

**Comment by TSlivede** [comment] 2017-09-19 08:56
Yes, that's true. My RFC-Proposal (or any other fix for https://github.com/PowerShell/PowerShell/issues/1995) should also fix this. Basically we could rename https://github.com/PowerShell/PowerShell/issues/1995 to something like "Arguments for external executables aren't correctly escaped". In that case this issue could be closed as duplicate.

**Comment by SteveL-MSFT** [comment] 2017-09-19 16:16
@TSlivede makes sense.  Dupe of https://github.com/PowerShell/PowerShell/issues/1995

**Comment by SteveL-MSFT** [comment] 2017-10-01 03:02
I'm separating this out from the uber issue of args to native commands which might be resolved by a future corefx api.  I'll see if there is something we can do to solve this one sooner.

**Closed** 2017-10-11 14:01 UTC
Labels: Area-Engine, Issue-Bug

**Comment by triynko** [comment] 2021-09-21 17:27
This bug causes all kinds of problem in Jenkins builds.  Trying to set any ENV variable to a path then ends in a backslash causes this.

For example, if you try to call   setx 'MY_PATH' 'C:\folder1\folders\' /M;
It ends up setting MYPATH to "C:\folder1\folder2" /M"
So instead of the value ending in a backslash, it ends with a double quote a space a forward slash and a capital M.

It doesn't get more wrong that that.  And Jenkins is just tied to this powershell version () so there's no fixing it. Just literally cannot pass any powershell arguments using single quotes when the string ends in a backslash.
