### ISSUE TITLE
Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by yao00jun** [PowerShell/PowerShell#9795] opened 2019-06-01 09:42 UTC
# Steps to reproduce

```powershell
open powershell
```

# Expected behavior

```none

```

# Actual behavior

Internal CLR error. (0x80131506)
   at Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)
   at Microsoft.PowerShell.ConsoleHost+<>c.<Start>b__4_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

# Environment data

```none
Windows 10 20H1 18908
```

**Comment by iSazonov** [comment] 2019-06-03 10:03
@yao00jun Please add PSVertionTable

**Comment by jared-is-ray** [comment] 2019-06-05 15:12
I can reproduce this same exact error and stack trace intermittently by right-clicking `pwsh.exe` (7.0.0-preview.1) and running it as an Administrator.

I'm using the zip distribution: PowerShell-7.0.0-preview.1-win-x64.zip
My version table when I AM able to open powershell is:

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.18908
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment] 2019-06-06 03:46
@bergmeister Perhaps we should skip this step if PowerShell is installed side-by-side. Thoughts?

**Comment by bergmeister** [comment] 2019-06-06 06:49
When you pin the task bar item to the taskbar, then that 'run as admin' context menu is specific to the location of the binary (after it is run once, it will even persist), therefore the feature still makes sense for side-by-side. I have always had the daily build and the RTM installation side by side on my machine without any problem. By looking at the OS version, the user is running a Windows Insider build of ` 20H1`, therefore I imagine this to be an issue of this preview version of Windows that should be reported to the Windows Insider team.

**Comment by iSazonov** [comment] 2019-06-06 07:52
@SteveL-MSFT Can you assign next milestone?

**Comment by SteveL-MSFT** [comment] 2019-06-14 17:23
Dupe of https://github.com/PowerShell/PowerShell/issues/9295

**Closed by SteveL-MSFT** 2019-06-14 17:23 UTC
Labels: Area-Engine, Issue-Bug, Resolution-Duplicate

**Comment by bergmeister** [comment] 2019-07-16 18:49
The fix for this issue has been back-ported to the recent release of `6.2.2`, please update and provide feedback if it fixed it. Users of the preview will have to wait for `7.0.0-preview.2`
https://github.com/PowerShell/PowerShell/releases/tag/v6.2.2
cc @yao00jun @jared-is-ray
