### ISSUE TITLE
[Ubuntu 20.04] PowerShell v7.1.0 is not available in the packages.microsoft.com repository

### ISSUE THREAD

**Issue by al-cheb** [PowerShell/PowerShell#14056] opened 2020-11-12 12:57 UTC
What is the status of updating powershell packages in the https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/p/ repository for Ubuntu 20.04?

**Comment by kilasuit** [comment] 2020-11-12 16:11
Likely as it was with the Microsoft store it is going through an additional cycle of internal review testing first but perhaps @SteveL-MSFT or @TravisEz13 can comment further

**Comment by TravisEz13** [comment] 2020-11-12 18:21
Duplicate of #12626

**Closed by TravisEz13** 2020-11-12 18:21 UTC
Labels: Distribution-Request, Resolution-Duplicate

**Comment by kilasuit** [comment] 2020-11-13 01:07
FYI @al-cheb  it is now available to install via that method as shown in the docs https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#installation-via-direct-download---ubuntu-2004
