### ISSUE TITLE
Feature Request: Allow class properties to define behavior and scope for their getters and setters

### ISSUE THREAD

**Issue by bender-the-greatest** [PowerShell/PowerShell#13662] opened 2020-09-20 04:19 UTC
## Summary of the new feature/enhancement
Similar to how it works in C#, or even using PowerShell's existing `Add-Member` cmdlet, under this feature request class properties would be able to define a `ScriptBlock` or use an `Attribute` to change how a class property's getter or setter works. If possible, being able to specify a private setter would also be beneficial to expose properties that can only be changed by class members.
  
Some cases where this would be useful:

- Sort collection values before returning
- Escape a string before it's set or gotten
- Data validation before the property is set
- Return localized values, especially useful if the class instance is expected to work with external data stored in a culture invariant format. Examples:
  - Return a localized date
  - Store a localized date in UTC or another timezone
  - Return culture-specific data for the invoker
  - Store culture-specific data in a culture-invariant way
- Fire an event or update the value in a remote API when a property value is set 
- Store information about class access metadata, such as the last time the class was read or written to, and which Property was accessed 

## Proposed technical implementation details (optional)

Take the following class definition representing an `InventoryItem` from the database of an in-house asset management system:

```powershell
using namespace System.Data.SqlClient

class InventoryItem {
  static [string] $InventoryItemsUrl
  [int] $Id
  [string] $FQDN
  [string[]] $ItemNotes
  [string[]] $IpAddresses
  [DateTime] $ActiveSince

  InventoryItem( [string]$connectionString, [string]$id ) {
    # Query database and assign member properties the correct values based on the returned results
  }
}
```

As is, this works fine for storing and retrieving information about the `InventoryItem`, but we have to code around not having access to getter and setter instructions. If we want to change how the getter or setter behaves (including treating the setter as "private"), we have to resort to hacky workarounds [like this](https://stackoverflow.com/q/63973656/584676).

Getters and setters on some of these properties _could_ look something like this syntactically using `Attributes` without having to change the parser:

```powershell
class InventoryItem {
  [ClassPropertySetter(Scope="private")]
  static [string] $InventoryItemsUrl = 'https://assetmanager.company.tld/InventoryItems/'
  [ClassPropertySetter(Scope="private")]
  [int] $Id
  [ClassPropertySetter(Definition="set_ValidateFQDN")]
  [string] $FQDN
  [string[]] $ItemNotes
  [ClassPropertySetter(Definition="set_ValidateIPs")]
  [string[]] $IpAddresses
  [ClassPropertyGetter(Definition="get_ActiveSinceLocalTime")]
  [ClassPropertySetter(Definition="set_ActiveSinceUTC")]
  [DateTime] $ActiveSince

  InventoryItem( [string]$connectionString, [string]$id ) {
    # Query database and assign member properties the correct values based on the returned results
  }

  hidden [void] set_ValidateFQDN( [string]$value ) {
    # Validate that $value looks like an FQDN before setting
  }

  hidden [void] set_ValidateIPs( [string[]]$values ) {
    # Validate that each element of $values looks like an IP address before setting
  }

  hidden [void] set_ActiveSinceUTC( [DateTime]$value ) {
    # Convert $value to UTC time before setting
  }

  hidden [DateTime] get_ActiveSinceLocalTime() {
    # Return $ActiveSince in the local time zone
  }
}
```

In this case, `ClassPropertySetter` and `ClassPropertyGetter` both would take the same arguments - `Definition` is the member function name in the class to use for its get or set function, which said function must take exactly one parameter for a setter and zero for a getter. `Scope` would be one of "public" (default), "private", and possibly "internal" (where internal may only be invoked from the module which declared the class). Omitting either attribute would simply create the default getter or setter which defining the class already does today.

**Comment by SeeminglyScience** [comment] 2020-09-20 11:48
Duplicate of #2219

**Closed** 2020-09-21 17:00 UTC
Labels: Area-Language, Issue-Enhancement, Resolution-Duplicate
