### ISSUE TITLE
Prompt runs twice on linux

### ISSUE THREAD

**Issue by kellypleahy** [PowerShell/PowerShell#3561] opened 2017-04-14 08:40 UTC
Steps to reproduce
------------------
1. create a custom prompt function in your profile.  A good choice is the one at the end of here:
https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Prompts
2. run powershell
3. you should see the prompt get written twice on the command line.  This is problematic for prompts that do "interesting" things like those on poshgit, etc.  (my real function is given below at the end of this issue).

Expected behavior
-----------------
Prompt function should only run once, otherwise functions that do "Write-Host" will do bad things.

Actual behavior
---------------
Prompt function appears to run twice.  Once it seems the output is kept, the other time it seems to be ignored.

By the way... the reason I say this is "on linux" is that running the same version of PS on my desktop machine in windows gave different (expected) results.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      6.0.0-alpha                                                                                                                                                    
PSEdition                      Core                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   3.0.0.0                                                                                                                                                        
GitCommitId                    v6.0.0-alpha.18                                                                                                                                                
CLRVersion                                                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        
```

My Custom Prompt
-----------------------
```powershell
function prompt
{
  $realLASTEXITCODE = $LASTEXITCODE
  $Host.UI.RawUI.ForegroundColor = "White"

  Write-Host ""
  $status_string = ""
  $branch_distance = ""
  # check to see if this is a directory containing a symbolic reference,
  # fails (gracefully) on non-git repos.
  $git_folder = _find_folder_above (get-item -force .) ".git"
  $git_color = "yellow"
  if($git_folder -ne $null)
  {
    $g = $git_folder.fullname
    $symbolicref = git symbolic-ref HEAD
    $current_hash = git log HEAD -n 1 --format='%h'
    $branch_name = "no branch"
    if($current_hash -ne $null)
    {
        $current_hash = "[" + $current_hash.substring(0, 7) + "]"
    }
    if($symbolicref -ne $null)
    {
      $branch_name = $symbolicref.substring($symbolicref.LastIndexOf("heads/") + 6)
      $branch_distance = _git_branch_vs_remote $branch_name
      if($branch_distance.length -gt 0) {
        $branch_distance = " (" + $branch_distance + ")"
      } else {
        $branch_distance = " (up to date)"
      }
    }
    elseif(test-path "$g\rebase-merge\interactive")
    {
      $branch_name = split-path -leaf (get-content "$g\rebase-merge\head-name")
      $branch_name += "|REBASE-i"
      $git_color = "red"
    }
    elseif(test-path "$g\rebase-merge")
    {
      $branch_name = split-path -leaf (get-content "$g\rebase-merge\head-name")
      $branch_name += "|REBASE-m"
      $git_color = "red"
    }
    
    # if a symbolic reference exists, snag the last bit as our
    # branch name. eg "[master]"
    $status_string += "GIT $current_hash for [$(git config user.name)] on [$branch_name]"
    
    if($env:SHOW_GIT_DIFFERENCES -ne "0")
    {
      # grab the differences in this branch   
      $differences = (git status --porcelain) 
      
      $git_update_count = _count_lines_with_matches "M" $differences
      $git_create_count = _count_lines_with_matches "A" $differences
      $git_create_count += _count_lines_with_matches "C" $differences # treat copy as create (never seen this from git, but git-status(1) indicates it's possible)
      $git_delete_count = _count_lines_with_matches "D" $differences
      $git_rename_count = _count_lines_with_matches "R" $differences
      $git_unknown_count = _count_lines_with_matches "?" $differences
      $git_unknown_count += _count_lines_with_matches "U" $differences
      $git_change_count = $git_update_count + $git_create_count + $git_delete_count + $git_unknown_count + $git_rename_count
      
      # place those variables into our string.
      if($git_change_count -eq 0)
      { 
        $status_string += " (clean)" 
      }
      else 
      { 
        $status_string += " r:$git_rename_count a:$git_create_count u:$git_update_count d:$git_delete_count ?:$git_unknown_count" 
      }
    }
  }
  else
  {
    # Not in a Git environment, must be PowerShell!
    $status_string = 'PS '
  }
  # write out the status_string with the approprate color.
  # prompt is done!
  if ($status_string.StartsWith('GIT'))
  {
    Write-Host $status_string -foreground $git_color -nonewline
    Write-Host $branch_distance -foreground white -nonewline
    Write-Host ' | '  -foreground $git_color -nonewline
  }
  else
  {
    Write-Host $status_string -foreground Cyan -nonewline
  }
  Write-Host $pwd.ProviderPath -NoNewLine -ForegroundColor Green
  Write-Host "`nλ " -NoNewLine -ForegroundColor Green

  reset-color
  $global:LASTEXITCODE = $realLASTEXITCODE
  return ' '
}
```

**Comment by kellypleahy** [comment] 2017-04-14 09:01
This seems like it could be the problem ;)

https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.PSReadLine/ReadLine.cs#L562

**Comment by lzybkr** [comment] 2017-04-14 22:15
Duplicate of https://github.com/lzybkr/PSReadLine/issues/468

**Closed by lzybkr** 2017-04-14 22:15 UTC
Labels: Area-PSReadLine
