### ISSUE TITLE
Publish PowerShell Core Assemblies to NuGet

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#2597] opened 2016-11-03 20:20 UTC
The packages should contain Windows, Linux, and macOS binaries.

We need to use the PowerShellTeam profile to publish them and develop a process for regular updates.

**Comment by atanasa** [comment] 2016-11-08 14:27
Can you also publish a package that could act as a "platform" dependency, that is, when publishing an app that consumes that package, dotnet cli should not output any dependencies that are already preinstalled by PowerShell (the platform). Essentially a package that defines the PowerShell platform similar to the Microsoft.NETCore.App that defines the .Net Core platform for Console Apps.

**Reasons**: 
Is there a way to build a module with dotnet cli that produce all the required module output? Currently a portable library project does not output any packaged dependencies. What I've done is to use a repurposed console app project because dotnet cli would then collect all the required dependencies on publish. The issue there is that even if I use the platform dependency for the .Net Core it would output the PowerShell reference assemblies (e.g. System.Management.Automation). We've worked around this by manually creating a PowerShell "platform" package, but there is the inconvenience of updating this with every release of PowerShell.

If there is a better approach than to use a platform package, let me know.

Here is a sample fragment from the project.json for the module project.

```json
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "PowerShell.Platform": {
          "version": "1.0.0-alpha9",
          "type": "platform"
        }
      }
    }
  },
```

**Comment by vors** [comment] 2016-11-16 22:47
@atanasa sounds like you are describing https://github.com/PowerShell/PowerShell/tree/master/src/Microsoft.PowerShell.SDK

We already publish this package to MyGet feed.

**Comment by SteveL-MSFT** [comment] 2017-03-20 17:36
Dupe of https://github.com/PowerShell/PowerShell/issues/1152

**Closed by SteveL-MSFT** 2017-03-20 17:36 UTC
Labels: Area-Build, Resolution-Duplicate
