### ISSUE TITLE
Update-Help

### ISSUE THREAD

**Issue by prepstarr** [PowerShell/PowerShell#17533] opened 2022-06-17 01:38 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

it might be because the computer language is French looking at Get-Error... 

**PS C:\Users\steve> man java**
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Get-Help could not find java in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.PS

**C:\Users\steve> Update-Help**
Update-Help: Failed to update Help for the module(s) '7zip-Archive' with UI culture(s) {fr-FR} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 'https://github.com/stadub/PowershellScripts/blob/master/7Zip/README.md' does not resolve to a container..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {fr-FR} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

### Expected behavior

```console
Example 1: Update help files for all modules
The Update-Help cmdlet updates help files for installed modules that support Updatable Help. The user-interface (UI) culture language is set in the operating system.

PowerShell

Copy
Update-Help

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/update-help?view=powershell-7.2
```

### Actual behavior

```console
**C:\Users\steve> Update-Help**

Update-Help: Failed to update Help for the module(s) '7zip-Archive' with UI culture(s) {fr-FR} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. The HelpInfoUri 'https://github.com/stadub/PowershellScripts/blob/master/7Zip/README.md' does not resolve to a container..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {fr-FR} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

### Error details

```console
Get-Error

Exception             :
    Type    : System.Exception
    Message : Failed to update Help for the module(s) 'WindowsUpdateProvider'
with UI culture(s) {fr-FR} : One or more errors occurred. (Response status code
does not indicate success: 404 (Not Found).).
              English-US help content is available and can be installed using:
Update-Help -UICulture en-US.
    HResult : -2146233088
CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
FullyQualifiedErrorId :
UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
InvocationInfo        :
    MyCommand        : Update-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Update-Help
    PositionMessage  : At line:1 char:1
                       + Update-Help
                       + ~~~~~~~~~~~
    InvocationName   : Update-Help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/65930206/174204990-12e226c8-4cec-4438-8634-ef2196166e68.png)

**Comment by prepstarr** [comment] 2022-06-17 01:56
also note : after running the usa update-help and this one the command man java yielded the following response:

man java

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
ConvertFrom-Json                  Cmdlet    Microsoft.PowerShell.Uti… Converts a JSON-formatted string to a custom object or a hash table.
ConvertTo-Json                    Cmdlet    Microsoft.PowerShell.Uti… Converts an object to a JSON-formatted string.
Invoke-RestMethod                 Cmdlet    Microsoft.PowerShell.Uti… Sends an HTTP or HTTPS request to a RESTful web service.
Test-Json                         Cmdlet    Microsoft.PowerShell.Uti… Tests whether a string is a valid JSON document
about_Object_Creation             HelpFile
about_Trap                        HelpFile

**Comment by jhoneill** [comment] 2022-06-17 10:15
One of these is a problem with the `7zip-Archive` module
```
The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored. 
The HelpInfoUri 'https://github.com/stadub/PowershellScripts/blob/master/7Zip/README.md' does not resolve to a container..
```
Someone needs to tell the module authors. 


One is a problem with a module which is bundled with windows and not PowerShell 7

```
Update-Help: Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {fr-FR} : 
One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).).
```
There are some known windows modules which have a problem  (see https://github.com/PowerShell/PowerShell/issues/17067#issuecomment-1079663584 ) but this one is new


And `man java` fails because man is aliased to get-help and java is an external help topic not a PowerShell one. The choice is either delete the alias or use man.exe for man pages.  When Java isn't a topic name PowerShell help searches through all the help for the word "java" - which gives *something* but probably not what you want.

**Comment by StevenBucher98** [comment] 2022-07-25 16:41
I messaged the module owner on the gallery for the `7zip-Archive` module. Marking as "as designed".

**Closed** 2022-07-26 21:01 UTC
Labels: Resolution-By Design
