### ISSUE TITLE
Windows Previous Versions 'Open' of previous version of folder causes open of PowerShell at that location and point in time.

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#8007] opened 2018-10-12 04:09 UTC
Steps to reproduce
------------------
On a Windows machine, in a location which utilizes Previous Versions, request the previous versions, specifically of a folder.  Select a previous version of the selected folder, and then press the 'Open' button.

(In my case I was on a mapped network drive, of a Windows 2012 R2 file server)

Expected behavior
-----------------
Windows Explorer opens a view of the folder in its previous state.

Actual behavior
---------------
PowerShell 6 opens at the selected location and point in time instead.

Environment data
----------------
Windows 10 1803
PowerShell 6.1.0

I believe this is happening as I chose the option during installation of PowerShell 6.1 to enable the PowerShell context menu on folders.

When PowerShell opened, I simply commanded `START .` and Explorer opened up the view of the folder instead.  I actually opened the folder multiple times to insure the same result, I was so caught by surprise.

**Comment by bergmeister** [comment] 2018-10-12 10:01
This is a duplicate of issue #6799 and has already been fixed by PR #7932
If this is a problem for you then either apply the registry changes in the PR by renaming the registry key `Directory\ContextMenus\PowerShell6x64\shell\open` to `Directory\ContextMenus\PowerShell6x64\shell\openpwsh` or reinstall PowerShell and not tick the 'context menu option'.

**Closed** 2018-10-12 11:13 UTC
Labels: Issue-Question, Resolution-Answered, Resolution-Duplicate
