### ISSUE TITLE
The context menu item "Open PowerShell window here" to remove the set-executionpolicy

### ISSUE THREAD

**Issue by krishnayalavarthi** [PowerShell/PowerShell#15577] opened 2021-06-14 18:53 UTC
## Steps to reproduce

```powershell

## Steps to Reproduce: (Add details for how we can reproduce the issue)

"if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }” to be removed when invoking a script as runas.
```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by rkeithhill** [comment] 2021-06-15 04:52
Which version of PowerShell are you using? I can't reproduce this on `v7.1.3`.  What is the output of `$PSVersionTable`?

**Comment by krishnayalavarthi** [comment] 2021-06-15 18:57
@rkeithhill Applies to all open versions.

**Comment by daxian-dbw** [comment] 2021-06-17 20:41
@krishnayalavarthi The issue doesn't describe the problem, and it doesn't have repro steps and environment data. Hence, I will close this issue. Please following the issue template to provide all needed information when you open a new issue, thanks!

**Closed by daxian-dbw** 2021-06-17 20:41 UTC
Labels: Needs-Triage
