### ISSUE TITLE
Get-ChildItem wrongly handling NBSP

### ISSUE THREAD

**Issue by iricigor** [PowerShell/PowerShell#4017] opened 2017-06-15 13:29 UTC
Steps to reproduce
------------------
 In C:\temp folder create new folder whose name consists only of [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space). You can type NBSP with holding alt and pressing 0160 on numerical keyboard. After creating it, run

```powershell
Get-ChildItem C:\Temp\ -Recurse
```

Expected behavior
-----------------
It should list folder only once.
```none
d-----        6/15/2017   2:20 PM
```

Actual behavior
---------------
you will get endless list of folders without name, although there exists only one such folder.

```none
d-----        6/15/2017   2:20 PM
d-----        6/15/2017   2:20 PM
d-----        6/15/2017   2:20 PM
d-----        6/15/2017   2:20 PM
d-----        6/15/2017   2:20 PM
. . . 
```

I have tried this on Desktop and Server environments, and with PowerShell 4 and 5. Command Get-Item is having also issue with this name, and both switches -Path and -LiteralPath are behaving in the same way. It was confirmed by multiple [persons](https://stackoverflow.com/questions/44567844/get-childitem-and-non-breaking-space). Running DIR /S in CMD works as expected.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iricigor** [comment] 2017-06-15 17:05
I was further tracking down this behavior.  Get-ChildItem is just calling provider, so that's not where the problem is, but in PSProvider FileSystem. Checking the code there, I saw that problem seems to originate from Get-Item. And even further, it comes from **[IO.DirectoryInfo]** constructor. This one is trimming trailing spaces (including NBSP), which in this case is wrong.

In the above listed example (NBSP folder inside of c:\temp), run these three commands:
```PowerShell
$nbsp = (gci c:\temp).Fullname 
# gets the full name of problem folder

$nbsp.ToCharArray() | % {write-host $_ [byte]($_)} 
# lists all chars from name and their ascii values
# we can see trailing NBSP

[IO.DirectoryInfo]::new($nbsp)  
# this returns wrong folder 'temp' and not the one with NBSP name
```

Can someone with more experience recheck this?

**Comment by jeffbi** [comment] 2017-06-15 19:30
What I'm seeing is that the problem is with the DirectoryInfo.EnumerateDirectories() method. That method is returning the NBSP-named directory as part of the enumeration of child directories.

This is not limited to CORE; a small test on the full CLR shows the same behavior.

**Comment by SteveL-MSFT** [comment] 2017-06-15 19:52
It sounds like this should be an issue opened in https://github.com/dotnet/corefx repo and not an issue in PowerShell?

**Comment by jeffbi** [comment] 2017-06-16 00:04
I've opened issue dotnet/corefx#21111 for this.

**Comment by iSazonov** [comment] 2017-06-17 12:19
The Issue was marked as bug in CoreFX so I close the Issue as external.

**Closed by iSazonov** 2017-06-17 12:19 UTC
