### ISSUE TITLE
Add PowerShell to Homebrew

### ISSUE THREAD

**Issue by alastairs** [PowerShell/PowerShell#1906] opened 2016-08-18 20:07 UTC
[Homebrew](https://brew.sh) is the standard community-developed and -supported package manager for OS X. It would be awesome to be able to `brew install powershell`.

**Comment by titussanchez** [comment] 2016-08-18 21:12
It's available if you install [Homebrew Cask] (https://caskroom.github.io/).

```
# brew tap caskroom/cask
# brew cask install powershell
```

**Comment by Phrohdoh** [comment] 2016-08-18 21:28
Duplicate of #1779.

**Comment by patrickobrien** [comment] 2016-08-19 03:28
brew told me to use:
`brew install Caskroom/cask/powershell`

**Comment by amuessig** [comment] 2016-08-19 10:01
Not working for me :/ 
 # 'brew install Caskroom/cask/powershell' 
==> brew cask install Caskroom/cask/powershell
Error: No available Cask for Caskroom/cask/powershell
Error: nothing to install

**Comment by childnode** [comment] 2016-08-23 06:09
same problem here for me @amuessig but : seems to be a brew problem at all
* https://github.com/caskroom/homebrew-cask/blob/master/Casks/powershell.rb ✅ 
* `brew update` and `brew cask update` ✅ 
* `brew doctor` was ok ✅ 
* `/usr/local/Library/Taps/caskroom/homebrew-cask/Casks` is outdated 🔴 <br>
^ so for me, it was hung up on master@[e283474 where no powershell.rb is in](https://github.com/caskroom/homebrew-cask/blob/e283474/Casks/powershell.rb) <br>
^ so: go into this dir, then `$ git fetch --all && git reset --hard origin/master`

btw. to all that "use brew cask" callers: cask is not a solution to some of us but simple and helpful for others. It (cask brew formular) more or less just takes down the huddle for you to download, verify the signature, run the installer, cleanup after uninstall. It doesn't do any recompile. It needs to re-download the complete package anytime.

**Closed** 2016-09-29 21:17 UTC
Labels: Resolution - External
