### ISSUE TITLE
Commands made CMD (and Windows Terminal) window flash

### ISSUE THREAD

**Issue by jasl** [PowerShell/PowerShell#10035] opened 2019-07-01 05:36 UTC
See attached GIF

![cmd](https://user-images.githubusercontent.com/1024162/60412807-30435780-9c05-11e9-97f5-3b5db86d9f2d.gif)

Actually including `$PSVersionTable.PSVersion` all commands will trigger this issue, but didn't capture it.

# Environment data

```none
Windows 10 1903 18362.207 Chinese language
PowerShell 6.2.1 x64 installed from its Github releases page
```

**Comment by DHowett** [comment] 2019-07-02 05:03
This is probably related to PSReadline saving and restoring the codepage before and after every command. If you use `Remove-Module PSReadline`, does it still happen?

**Comment by jasl** [comment] 2019-07-02 05:13
@DHowett 

You're right, it works. Thank you!

One more question, I'm not familiar with PowerShell, is there any side effect by removing `PSReadline` ? is this a `PSReadline`'s bug?

**Comment by iSazonov** [comment] 2019-10-02 11:11
@daxian-dbw @SteveL-MSFT Coul you move the issue to PSReadline repo?

**Comment by SteveL-MSFT** [comment] 2019-10-03 20:44
This is dupe of https://github.com/PowerShell/PSReadLine/issues/964 so no need to transfer

**Closed by SteveL-MSFT** 2019-10-03 20:44 UTC
Labels: Area-PSReadLine, Issue-Question
