### ISSUE TITLE
Test-Json doesnt parse json array

### ISSUE THREAD

**Issue by deepend-dev** [PowerShell/PowerShell#13561] opened 2020-09-01 14:57 UTC
# Test-Json doesn't parse json array at root level.

## Steps to reproduce

```powershell

PS /home/vsonline/workspace> $arrayobject = @( @{
>> name = "person1"; job = "it" } , @{ name = "persone2"; job = "it"} )


PS /home/vsonline/workspace> $arrayobject | ConvertTo-Json


[
  {
    "name": "person1",
    "job": "it"
  },
  {
    "name": "persone2",
    "job": "it"
  }
]
PS /home/vsonline/workspace> $arrayobject | ConvertTo-Json | test-json


Test-Json: Cannot parse the JSON.
False

```

## Expected behavior

```none
$arrayobject | ConvertTo-Json | test-json
True
```

## Actual behavior

```none

Test-Json: Cannot parse the JSON.
False

```

## Environment data

```none
PS /home/vsonline/workspace> $PSVersionTable 


Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 5.3.0-1035-azure #36-Ubuntu SMP Thu Aug 6 09:21:33 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by deepend-dev** [comment] 2020-09-01 14:59
cc @iSazonov any thoughts on this one?

**Comment by vexx32** [comment] 2020-09-01 15:15
Duplicate of #11384 🙂

**Comment by iSazonov** [comment] 2020-09-02 05:14
Yes, it is duplicate. I rebased my PR to .Net 5.0 Preview8 so you can download the artifact, test and report your results there.

**Closed by iSazonov** 2020-09-02 05:14 UTC
Labels: Issue-Question, Resolution-Duplicate
