### ISSUE TITLE
add grep call in powershell

### ISSUE THREAD

**Issue by volviq** [PowerShell/PowerShell#3280] opened 2017-03-08 10:55 UTC
It would be great if I could use a primitive grep call to pipe text data into it.
Currently there is the possibility to run:
$(command) |  where {$_ -match 'pattern'}
which is basically doing what I am searching for from the functional point of view.
As I - and many other developers have memorized Unix commands, a support of:
$(command) |  grep 'pattern'
would reduce the amount of time to get into Powershell usage.

Many commands already provide a similar syntax to the unix shell like ls and rm by wrapping native Powershell commands. It would be very much appreciated if you could extend the list.

In Linux environments it may be still useful to be able to use a native grep somehow, as it may still be more flexible or not all flags may be supported in the Powershell equivalent.

**Comment by iSazonov** [comment] 2017-03-08 12:50
@volviq Thanks for your contribution!

You can use:
```powershell
$(command) | Select-String 'pattern'
or with alias
$(command) | sls 'pattern'
```

**Comment by nferrell** [comment] 2017-03-09 06:29
I don't think Powershell is ever going to have grep, even as an alias. Select-String has been the Powershell version of grep for years and works great

**Comment by lzybkr** [comment] 2017-03-09 18:51
We are well aware of the consequences of adding aliases to well known commands and have no plans to add `grep`.

Closing as a duplicate of https://github.com/PowerShell/PowerShell/issues/929.

**Closed by lzybkr** 2017-03-09 18:51 UTC
Labels: Area-Cmdlets, Issue-Enhancement

**Comment by greddyatpt** [comment] 2021-08-16 15:07
The PowerShell commands always require you to RTFM.  Too verbose.

**Comment by doctordns** [comment] 2021-09-04 10:01
> The PowerShell commands always require you to RTFM. Too verbose.

Get-Help is built in so no need to read a fine manual...
