### ISSUE TITLE
Powershell translates all output bytes that equal '\n' to '\r\n'

### ISSUE THREAD

**Issue by tannergooding** [PowerShell/PowerShell#4961] opened 2017-09-30 05:27 UTC
### Repro
Take the following simple C# program:
```C#
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.Write('\n');
        Console.Out.Write('\n');
        Console.OpenStandardOutput().WriteByte((byte)('\n'));
    }
}
```

Compile it and execute the program under Powershell, redirecting the output to a file:

### Expected Behavior
One would expect that if you redirected this to a file, it would contain:
```
\n
\n
\n
```

I expect, that if I tell my program to output '\n' and then redirect that to a file, it is written exactly as '\n'.

I expect, that if I tell my program to write raw bytes to the console, and then redirect that to a file, it is written exactly as given.

I expect in both of these cases, if I do not redirect, that the output is written to the console exactly as given.

### Actual Behavior
However, Powershell force converts all bytes equaling '\n' to '\r\n', so instead you get:
```
\r\n
\r\n
\r\n
```

Additionally, it will further translate other bytes written to it into the encoding it "assumes" (Unicode by default for `> Out.txt` and the specific encoding for `| Out-File Out.txt -encoding`). This can cause egregious errors for output that **should** be written to the file exactly as given, unless otherwise specified.

**Comment by markekraus** [comment] 2017-09-30 10:28
This behavior is highly depending on the method which which you are creating the file. Can you provide both the `$PSVersionTable` output and some PowerShell code to reproduce the issue? In some cases, this behavior is "by design"  in others there are known issues (or ongoing debates), or this could be completely new. One cannot tell which is the case without relevant PowerShell code.

**Comment by tannergooding** [comment] 2017-09-30 15:46
Open `cmd.exe` and do the following:
```
D:\>mkdir repro

D:\>cd repro

D:\repro>dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on D:\repro\repro.csproj...
  Restoring packages for D:\repro\repro.csproj...
  Generating MSBuild file D:\repro\obj\repro.csproj.nuget.g.props.
  Generating MSBuild file D:\repro\obj\repro.csproj.nuget.g.targets.
  Restore completed in 219.23 ms for D:\repro\repro.csproj.


Restore succeeded.


D:\repro>notepad Program.cs

D:\repro>
```

Set the contents of Program.cs to:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.Write('P');
        Console.Write('4');
        Console.Write('\n');
        Console.Write('2');
        Console.Write('0');
        Console.Write('0');
        Console.Write(' ');
        Console.Write('2');
        Console.Write('0');
        Console.Write('0');
        Console.Write('\n');

        Console.Out.Write('P');
        Console.Out.Write('4');
        Console.Out.Write('\n');
        Console.Out.Write('2');
        Console.Out.Write('0');
        Console.Out.Write('0');
        Console.Out.Write(' ');
        Console.Out.Write('2');
        Console.Out.Write('0');
        Console.Out.Write('0');
        Console.Out.Write('\n');

        Console.OpenStandardOutput().WriteByte((byte)('P'));
        Console.OpenStandardOutput().WriteByte((byte)('4'));
        Console.OpenStandardOutput().WriteByte((byte)('\n'));
        Console.OpenStandardOutput().WriteByte((byte)('2'));
        Console.OpenStandardOutput().WriteByte((byte)('0'));
        Console.OpenStandardOutput().WriteByte((byte)('0'));
        Console.OpenStandardOutput().WriteByte((byte)(' '));
        Console.OpenStandardOutput().WriteByte((byte)('2'));
        Console.OpenStandardOutput().WriteByte((byte)('0'));
        Console.OpenStandardOutput().WriteByte((byte)('0'));
        Console.OpenStandardOutput().WriteByte((byte)('\n'));
    }
}
```

Next, continue on the command line with:
```
D:\repro
D:\repro>dotnet run > CMD.txt

D:\repro>D:\PowerShell-6.0.0-beta.7-win-x64\powershell.exe
PowerShell v6.0.0-beta.7
Copyright (C) Microsoft Corporation. All rights reserved.

PS D:\repro> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS D:\repro> dotnet run > PS-1.txt
PS D:\repro> C:\Windows\System32\fc.exe /B .\CMD.txt .\PS-1.txt
Comparing files .\CMD.txt and .\PS-1.TXT
00000000: 50 FF
00000001: 34 FE
00000002: 0A 50
00000003: 32 00
00000004: 30 34
00000005: 30 00
00000006: 20 0D
00000007: 32 00
00000008: 30 0A
00000009: 30 00
0000000A: 0A 32
0000000B: 50 00
0000000C: 34 30
0000000D: 0A 00
0000000E: 32 30
0000000F: 30 00
00000010: 30 20
00000011: 20 00
00000013: 30 00
00000015: 0A 00
00000016: 50 30
00000017: 34 00
00000018: 0A 0D
00000019: 32 00
0000001A: 30 0A
0000001B: 30 00
0000001C: 20 50
0000001D: 32 00
0000001E: 30 34
0000001F: 30 00
00000020: 0A 0D
FC: .\PS-1.TXT longer than .\CMD.txt


PS D:\repro> dotnet run | Out-File -filePath PS-2.txt
PS D:\repro> C:\Windows\System32\fc.exe /B .\CMD.txt .\PS-2.txt
Comparing files .\CMD.txt and .\PS-2.TXT
00000000: 50 FF
00000001: 34 FE
00000002: 0A 50
00000003: 32 00
00000004: 30 34
00000005: 30 00
00000006: 20 0D
00000007: 32 00
00000008: 30 0A
00000009: 30 00
0000000A: 0A 32
0000000B: 50 00
0000000C: 34 30
0000000D: 0A 00
0000000E: 32 30
0000000F: 30 00
00000010: 30 20
00000011: 20 00
00000013: 30 00
00000015: 0A 00
00000016: 50 30
00000017: 34 00
00000018: 0A 0D
00000019: 32 00
0000001A: 30 0A
0000001B: 30 00
0000001C: 20 50
0000001D: 32 00
0000001E: 30 34
0000001F: 30 00
00000020: 0A 0D
FC: .\PS-2.TXT longer than .\CMD.txt

PS D:\repro>
```

You can repeat for `dotnet run | Out-File -filePath <fileName> -encoding {encoding}` and see similar results. Below is the hex dump for each:
```
CMD.txt
    50 34 0A
    32 30 30 20 32 30 30 0A
    50 34 0A
    32 30 30 20 32 30 30 0A
    50 34 0A
    32 30 30 20 32 30 30 0A
PS-1.txt, PS-2.txt, PS-Unknown.txt, PS-String.txt, PS-Unicode.txt
    FF FE
    50 00 34 00 0D 00 0A 00
    32 00 30 00 30 00 20 00 32 00 30 00 30 00 0D 00 0A 00
    50 00 34 00 0D 00 0A 00
    32 00 30 00 30 00 20 00 32 00 30 00 30 00 0D 00 0A 00
    50 00 34 00 0D 00 0A 00
    32 00 30 00 30 00 20 00 32 00 30 00 30 00 0D 00 0A 00
PS-BigEndianUnicode.txt
    FE FF
    00 50 00 34 00 0D 00 0A
    00 32 00 30 00 30 00 20 00 32 00 30 00 30 00 0D 00 0A
    00 50 00 34 00 0D 00 0A
    00 32 00 30 00 30 00 20 00 32 00 30 00 30 00 0D 00 0A
    00 50 00 34 00 0D 00 0A
    00 32 00 30 00 30 00 20 00 32 00 30 00 30 00 0D 00 0A
PS-UTF8.txt
    EF BB BF
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
    50 34 0D 0A 32 30 30 20 32 30 30 0D 0A
PS-UTF7.txt
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
PS-UTF32.txt (UTF32)
    FF FE 00 00
    50 00 00 00 34 00 00 00 0D 00 00 00 0A 00 00 00
    32 00 00 00 30 00 00 00 30 00 00 00 20 00 00 00 32 00 00 00 30 00 00 00 30 00 00 00 0D 00 00 00 0A 00 00 00
    50 00 00 00 34 00 00 00 0D 00 00 00 0A 00 00 00
    32 00 00 00 30 00 00 00 30 00 00 00 20 00 00 00 32 00 00 00 30 00 00 00 30 00 00 00 0D 00 00 00 0A 00 00 00
    50 00 00 00 34 00 00 00 0D 00 00 00 0A 00 00 00
    32 00 00 00 30 00 00 00 30 00 00 00 20 00 00 00 32 00 00 00 30 00 00 00 30 00 00 00 0D 00 00 00 0A 00 00 00
PS-ASCII.txt, PS-Default.txt, PS-OEM.txt
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
    50 34 0D 0A
    32 30 30 20 32 30 30 0D 0A
```

From this, I can see the following problems:
* None of the encodings give the exact output desired (due to forced translation of '\n' to '\r\n')
  * This means there is no "workaround" (I would expect, at the very least, there to be a `-encoding Byte` option, as some other commands have)
* UTF-8 enforces addition of the BOM (may be undesirable in some scenarios)
* When no encoding is specified, it transforms the bytes to be Unicode
  * This means my output is "broken" and "twice as big", by default
* The default is not `-encoding Default`, it is `-encoding Unicode`

**Comment by SteveL-MSFT** [comment] 2017-09-30 16:05
@tannergooding thanks for the thorough investigation.  The encoding issue should be addressed by https://github.com/PowerShell/PowerShell/issues/4878, the EOL issue is probably https://github.com/PowerShell/PowerShell/issues/2145

**Comment by iSazonov** [comment] 2017-09-30 19:19
I believe it is dup with great repo.

**Comment by SteveL-MSFT** [comment] 2017-09-30 19:56
Agree that the other two issues have this covered, @tannergooding let me know if you don't agree.

**Closed by SteveL-MSFT** 2017-09-30 19:56 UTC
Labels: Area-Engine, Resolution-Duplicate
