### ISSUE TITLE
7.0rc.1 Update-Help for Microsoft.PowerShell.Utility pull content for PS 6 help

### ISSUE THREAD

**Issue by KevinMarquette** [PowerShell/PowerShell#11462] opened 2019-12-31 20:04 UTC
I noticed that I am getting PS 6 help for commands on PS7
# Steps to reproduce

```powershell
Update-Help -Module Microsoft.PowerShell.Utility -Force 
Get-Help Invoke-RestMethod
Get-Help Invoke-RestMethod -Online
```

# Expected behavior
Related links of help should point to the PS 7.0 uri of  `https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7&WT.mc_id=ps-gethelp`
The browser should open to the PowerShell 7 version of the help documentation

# Actual behavior

Related links of help point to the PS 6.0 uri of  `https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6&WT.mc_id=ps-gethelp`
The browser opens to the PowerShell 6 version of the help documentation

# Additional Info
Calling Update-Help -Verbose shows it pulling PS 6 details.

```
PS> Update-Help -Module Microsoft.PowerShell.Utility -Force -Verbose
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855960"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/Microsoft.PowerShell.Utility/"
VERBOSE: Performing the operation "Update-Help" on target "Microsoft.PowerShell.Utility, Current Version: 6.1.0.1, Available Version: 6.1.0.1, UICulture: en-US".
VERBOSE: Microsoft.PowerShell.Utility: Updated C:\Users\kemarqu\Documents\PowerShell\Help\en-US\Microsoft.PowerShell.Commands.Utility.dll-Help.xml. Culture en-US Version 6.1.0.1
VERBOSE: Microsoft.PowerShell.Utility: Updated C:\Users\kemarqu\Documents\PowerShell\Help\en-US\Microsoft.PowerShell.Utility-help.xml. Culture en-US Version 6.1.0.1

PS> get-module Microsoft.PowerShell.Utility -ListAvailable

    Directory: C:\program files\powershell\7-preview\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I found this merged PR for RC1 that I think should have addressed this.
https://github.com/PowerShell/PowerShell/pull/11071

But I cannot identify why I am not getting the PS 7.0 help.

Possibly related historical issues:
https://github.com/PowerShell/PowerShell/pull/5820
https://github.com/PowerShell/PowerShell/issues/6187
https://github.com/PowerShell/PowerShell/issues/2616
https://github.com/PowerShell/PowerShell/issues/10705

**Comment by iSazonov** [comment] 2020-01-01 12:47
I think 7.0 help content is still not published.
/cc @sdwheeler

**Comment by sdwheeler** [comment] 2020-01-01 18:42
@iSazonov The content is published. This was verified by @adityapatwardhan. The issue is that the HelpInfoUri in the v7-preview modules points to v6 downloads. This will be fixed for release.

**Closed** 2020-01-03 12:00 UTC
Labels: Area-HelpSystem, Issue-Question, Resolution-Answered
