### ISSUE TITLE
Misbehaving Executables and Console Mode

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2873] opened 2016-12-12 15:52 UTC
On newer versions of Windows with support for ANSI colors in the console, some badly behaving executables changes the Console mode. An example is ```$env:USERPROFILE\AppData\Local\GitHub\PortableGit_d7eff...\usr\bin\perl.exe``` that is installed by GitHub Desktop.

Before executing the command (perl.exe), ConsoleMode is 7 (```ENABLE_PROCESSED_OUTPUT|ENABLE_WRAP_AT_EOL_OUTPUT|ENABLE_VIRTUAL_TERMINAL_PROCESSING```) and after execution it is 3 (```ENABLE_PROCESSED_OUTPUT|ENABLE_WRAP_AT_EOL_OUTPUT```)

The result is that my colored prompt output is looking like 
```[1;31mdev-walrus-online[0m - [D:\ws\walon\TnT]```

Is this something PowerShell should handle (restoring ConsoleMode) or is this by design?

**Comment by iSazonov** [comment] 2016-12-12 17:54
I vote to fix this (after native command execution).

**Comment by lzybkr** [comment] 2016-12-12 18:42
Dupe of #1177.

**Closed by lzybkr** 2016-12-12 18:42 UTC
