### ISSUE TITLE
[BUG] Invoke-WebRequest does not return the server response on 500 error

### ISSUE THREAD

**Issue by corbob** [PowerShell/PowerShell#8799] opened 2019-01-31 06:51 UTC
If you issue an invalid request to the Cisco Unified Call Manager Administrative XML SOAP API (AXL), it returns a 500 error response that includes XML. Under Windows PowerShell 5.1, this XML is available in the `ErrorDetails.Message` property. Under PowerShell 6.1.2 and 6.2.0-Preview.4 you do not get the XML tags

# Steps to reproduce

```powershell
$IWRParams = @{
                 Headers    = @{ 'Content-Type' = 'text/xml; charset=utf-8' }
                 Body       = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/11.5"><soapenv:Header/><soapenv:Body><ns:doLdapSync><name>ldapsyn</name><sync>true</sync></ns:doLdapSync></soapenv:Body></soapenv:Envelope>'
                 Uri        = "https://10.10.20.1/axl/"
                 Method     = 'Post'
                 Credential = (Get-Credential)
 SkipCertificateCheck = $true
             }
 Invoke-WebRequest @IWRParams
```

# Expected behavior

When catching the exception, the `ErrorDetails.Message` should contain the entire results returned from the server.

```none
#When run from Windows PowerShell 5.1:
PS C:\Users\corbob> $error[0].errordetails.message
<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><soapenv:Fault><faultcode>soapenv:Server</faultcode><faultstring>Item not valid: The specified ldapsyn was not found</faultstring><detail><axlError><axlcode>5007</axlcode><axlmessage>Item not valid: The specified ldapsyn was not found</axlmessage><request>doLdapSync</request></axlError></detail></soapenv:Fault></soapenv:Body></soapenv:Envelope>
```

# Actual behavior

XML tags are being stripped out

```none
C:\Users\corbob> $error[0].errordetails.message
soapenv:ServerItem not valid: The specified ldapsyn was not found5007Item not valid: The specified ldapsyn was not founddoLdapSync
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.4
PSEdition                      Core
GitCommitId                    6.2.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2019-01-31 13:05
Duplicate of #5555

**Closed by markekraus** 2019-01-31 13:05 UTC
Labels: Issue-Bug, Resolution-Duplicate
