### ISSUE TITLE
Autocomplete is not cleared if it's more than  line

### ISSUE THREAD

**Issue by abdellatifLabr** [PowerShell/PowerShell#13001] opened 2020-06-20 11:45 UTC
commands autocomplete is not cleared well after executing the command. if the autocomplete length is more than one line, it's not fully cleared.
here is the autocomplete line appears and abviously it's more than 1 line
![image](https://user-images.githubusercontent.com/17796722/85200939-528d2400-b2f3-11ea-81fe-3662ee732169.png)

and when i execute the ls command, the rest of the autocomplete is not cleared.
![image](https://user-images.githubusercontent.com/17796722/85200975-9a13b000-b2f3-11ea-8bb1-869faf11762d.png)

I'm using Windows Terminal 1.0 & Powershell 7.0.2 on Windows 10 version 1909

it happend also on the normal powershell windows, so it's not a Windows Terminal issue
![image](https://user-images.githubusercontent.com/17796722/85201026-fa0a5680-b2f3-11ea-8c6e-386440cb7df0.png)

**Comment by iSazonov** [comment] 2020-06-23 02:54
Can you check without PSReadline? (Remove-Module PSReadline)

/cc @daxian-dbw

**Comment by abdellatifLabr** [comment] 2020-06-23 11:18
@iSazonov 
Yes, the error doesn't happen when i remove PSReadline, but there's no autocomplete at all.

**Comment by daxian-dbw** [comment] 2020-07-10 17:48
This is a duplicate of https://github.com/PowerShell/PSReadLine/issues/1591.

**Closed** 2020-07-10 22:11 UTC
Labels: Area-PSReadLine, Issue-Question, Resolution-Duplicate
