### ISSUE TITLE
When starting PowerShell via its exe the new black icon is not applied in the Window (but in the taskbar)

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5013] opened 2017-10-04 22:10 UTC
If you launch PowerShell Core via its exe Windows PowerShell then the window icon is still the old blue one in the window (but the taskbar icon is the new black one of PR #4848). This also affect the proposed context menu in issue #5012.
EDIT: I believe this is an issue with the exe itself because when double clicking on the exe `C:\Program Files\PowerShell\6.0.0-beta.7\powershell.exe` itself the new icon does not get applied either.

Steps to reproduce
------------------
Either double click on `C:\Program Files\PowerShell\6.0.0-beta.7\powershell.exe` or execute in Windows PowerShell:
`Start-Process "C:\Program Files\PowerShell\6.0.0-beta.7\powershell.exe"`

Expected behavior
-----------------

The icon in the window and taskbar should both be the new black ones.

Actual behavior
---------------

The icon in the window is the old blue icon but the taskbar icon is the new black one.

Environment data
----------------

```
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.7
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7-84-gee902a649e0b803b3db4619f7eeeadea5e60d0e6
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by SteveL-MSFT** [comment] 2017-10-04 22:36
The icon is really only applying to the shortcut as the .exe itself doesn't have the icon embedded in its resources.  Proper fix is to add the icon the the resources of the exe, but that's not currently a priority.

**Comment by iSazonov** [comment] 2017-10-05 04:53
It seems dotnet/cli don't still support embedding custom icon in exe. 😕 https://github.com/dotnet/cli/issues/3267

**Comment by SteveL-MSFT** [comment] 2017-10-05 15:13
@iSazonov we can use something like this: https://github.com/electron/rcedit

**Comment by bergmeister** [comment] 2017-10-05 17:38
@iSazonov I don't understand how this can be an issue with the dotnet cli because my thinking is that the old blue PowerShell icon must come from somewhere. Or is this a red herring because PowerShell Core is somehow linked to Windows PowerShell?

**Comment by SteveL-MSFT** [comment] 2017-10-05 17:48
@bergmeister I think the OS is doing something there to show the blue icon from Windows powershell.exe

**Comment by bergmeister** [comment] 2017-10-05 19:47
Hmm, yes probably. I just found that this issue seems to be a duplicate of #2883

**Comment by bergmeister** [comment] 2017-10-05 20:12
I manually tried `rcedit "path-to-powershell.exe" --set-icon "path-to-black-icon"` and although it changes the icon that is displayed in explorer.exe, it did not change the icon of the window

**Comment by SteveL-MSFT** [comment] 2017-10-05 20:54
Yes, think is a dupe of #2883

Agree that it's quite possible that the icon is associated to the powershell.exe process.

**Closed by SteveL-MSFT** 2017-10-05 20:54 UTC
Labels: Area-Build, Resolution-Duplicate
