### ISSUE TITLE
'utf8' is not a supported encoding name. 

### ISSUE THREAD

**Issue by Santhoshsekar89** [PowerShell/PowerShell#7836] opened 2018-09-21 18:42 UTC
Getting the below error, when I run the Tableau API in powershell. It works in other environments and all of sudden its not working in the new environment which we created recently.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version
 for the right syntax to use near 'utf8' is not a supported encoding name. For information on defining a custom enc' at line 1" 'utf8' is not a supported enco
ding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

Please help to fix.

**Comment by SteveL-MSFT** [comment] 2018-09-21 23:58
@Santhoshsekar89 you'll need to provide more details of your environment and steps to repro to figure out what's going on.  Thanks.

**Comment by Santhoshsekar89** [comment] 2018-10-09 14:19
Hi Steve,

Im using the function invoke-restmethod API  like below,

$TabResponse = Invoke-RestMethod -Uri $TabUri/sites/$global:TabSiteID/groups -Headers $global:TabHeaders -Method POST -Body $TabGroupXML

**Comment by Santhoshsekar89** [comment] 2018-10-09 14:58
Please find the details requested,

Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      4.0                                                                                                                           
WSManStackVersion              3.0                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                               
BuildVersion                   6.3.9600.18968                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                          
PSRemotingProtocolVersion      2.2  


Variable Info:
$TabUri = https://ause1tabap02.ds.mot.com/api/3.1
$global:TabSiteID = 3552ed41-8bd3-4155-bf07-9c9071a45e64
$global:TabHeaders = Key                                                                            Value                                                                         
---                                                                            -----                                                                         
X-Tableau-Auth                                                                 -s6x3oEpRq-jhytHnRyR-Q|wQfW3ArXGRNsA6WPLZrgBOkpz4QV2fOP  
$TabGroupXML = <tsRequest><group name="TestingProject - Publisher" /></tsRequest>


Note: 1. Copy and paste the above values in notepad to have better formatting.
2. Im facing the problem only with response when I hit the above invoke restmethod but the request is getting completed.

**Comment by SteveL-MSFT** [comment] 2018-10-09 18:00
@Santhoshsekar89 can you try with PowerShell Core 6.1?  We don't provide support for Windows PowerShell here let alone v4.

**Comment by markekraus** [comment] 2019-01-24 00:48
Closing issue due to lack of follow up. If @Santhoshsekar89  can reproduce this in 6.1.2 and provide results we can always re-open.

**Closed by markekraus** 2019-01-24 00:48 UTC
Labels: Issue-Discussion
