### ISSUE TITLE
Broken hotkeys

### ISSUE THREAD

**Issue by ruffe972** [PowerShell/PowerShell#13792] opened 2020-10-16 10:27 UTC
## Steps to reproduce

Hotkeys don't work if Powershell is started while Russian keyboard layout is active. Even switching back to English after launching Powershell doesn't fix the problem.

![bug](https://user-images.githubusercontent.com/11010943/96247573-f9888080-0fb2-11eb-9a2b-26a3a11e528e.gif)

## Expected behavior

Ctrl+C and other hotkeys should work at all times.

## Actual behavior

Ctrl+C and other hotkeys don't work.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Problem persists in conhost.exe too. Problem doesn't occur in old powershell 5.

**Comment by ruffe972** [comment] 2020-10-16 10:29
Problem persists in conhost.exe too. Problem doesn't occur in old powershell 5.

**Comment by iSazonov** [comment] 2020-10-16 17:25
Please check with latest PowerSHell 7.1 RC and PSReadline 2.1 RC builds and confirm the issue.

**Comment by ruffe972** [comment] 2020-10-23 09:33
I've checked PowerShell-7.1.0-rc.2, this version has the bug too.

**Comment by ForNeVeR** [comment] 2021-11-20 14:51
This is a duplicate of https://github.com/PowerShell/PSReadLine/issues/1393.

**Closed** 2023-11-23 11:25 UTC
Labels: Issue-Question, WG-Interactive-PSReadLine, Resolution-No Activity
