### ISSUE TITLE
The tab complete returned command is repeated

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#4865] opened 2017-09-19 18:40 UTC
Steps to reproduce
------------------
get-psr```<press tab>```

Actual behavior
------------------
return:
Get-PSReadlineKeyHandler  Get-PSReadlineOption      Get-PSRepository          Get-PSReadlineKeyHandler  Get-PSReadlineOption

Environment data
----------------
centos 7.4 + powershell 6.0 beta7

**Comment by lzybkr** [comment] 2017-09-19 19:11
Duplicate of https://github.com/lzybkr/PSReadLine/issues/430

**Closed by lzybkr** 2017-09-19 19:11 UTC
