### ISSUE TITLE
[Windows] Pinned PowerShell shortcuts are lost after upgrade.

### ISSUE THREAD

**Issue by SwarfegaGit** [PowerShell/PowerShell#6088] opened 2018-02-01 22:05 UTC
New issue at the request of @SteveL-MSFT in issue #6080 

When upgrading between new versions of PowerShell any pinned Start Menu or Taskbar Icons are lost.
If you copy the shortcut from the Start Menu to anywhere else, such as the desktop, that icon also stops functioning following an upgrade.

I believe the reason for this is because the path changes to the pwsh.exe changes after the upgrade due to the version being part of the file path for the pwsh.exe file.  E.G.

* C:\Program Files\PowerShell\6.0.0-beta.9\pwsh.exe
* C:\Program Files\PowerShell\6.0.0-rc.2\pwsh.exe
* C:\Program Files\PowerShell\6.0.0\pwsh.exe
* C:\Program Files\PowerShell\6.0.1\pwsh.exe

Ideally the version number folder should be removed or at least the pwsh.exe is moved into the PowerShell folder and the rest of the files remain in the version folder.  Also, is there a real need to keep the version number found on the shortcut that's placed into the Start Menu?

Steps to reproduce
------------------

1. Uninstall PowerShell.
2. Install [PowerShell 6.0.0](https://github.com/PowerShell/PowerShell/releases/download/v6.0.0/PowerShell-6.0.0-win-x64.msi).  
3. Right click the 'PowerShell-6.0.0' shortcut and select 'Pin to Start' or/and 'Pin to taskbar'. 
4. Run the [PowerShell 6.0.1](https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/PowerShell-6.0.1-win-x64.msi) installer to perform an upgrade.

Expected behavior
-----------------

For the PowerShell icon to remain pinned and working after the upgrade.  

Actual behavior
---------------

The one in the Start Menu disappears.  The one on the taskbar turns to a white default file icon which when clicked (Windows 10)...

````none
[Window Title]
Windows

[Main Instruction]
Can't open this item

[Content]
It might have been moved, renamed, or deleted. Do you want to remove this item?

[Yes] [No]
````

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17083
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2018-02-02 00:19
I think this is a dupe of  #5226

**Comment by SteveL-MSFT** [comment] 2018-02-02 00:41
@markekraus is right, this is a dupe.

@SwarfegaGit appreciate you opening this.  Comment/follow the other one which I promoted to 6.1.0-Consider.

**Closed by SteveL-MSFT** 2018-02-02 00:41 UTC
Labels: Resolution-Duplicate
