### ISSUE TITLE
Publish Microsoft.Management.Infrastructure.CimCmdlets as NuGet package

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShell#10012] opened 2019-06-26 16:38 UTC
# Current Behavior
I am not productive as possible as a C# developer writing PowerShell DevOps infrastructure, because:

1. `Microsoft.Management.Infrastructure` exists on nuget.org
2. `Microsoft.Management.Infrastructure.CimCmdlets` does not exist on nuget.org
3. `Microsoft.Management.Infrastructure.CimCmdlets.dll` must be manually copied from the local modules path into a C# .csproj directory and explicitly refererenced.  Not desirable as it binds my C# Cmdlets to a specific version of `Microsoft.Management.Infrastructure.CimCmdlets.dll`

# Desired Behavior
Either:
1. Adopt "SDK metapackage" for PowerShell similar to .NET Standard / .NET Core metapackages
2. Publish a NuGet package for CimCmdlets so we can be productive writing DevOps infrastructure in C#.

Duplicate of #8119

**Comment by jzabroski** [comment] 2019-06-26 19:32
I'm debating closing this - I see now that my request is probably misguided:

1. I was trying to invoke GetCimInstanceCommand directly from `Microsoft.Management.Infrastructure.Cmdlets`
2. The "easier" approach is to use the more fundamental `Microsoft.Management.Infrastructure` package/dll OR use the PowerShell SDK via `PowerShell.Create`.

The fundamental problem is to get the goodness of PowerShell's ability to handle partial failures as non-terminating, but get the goodness of C# + Visual Studio + ReSharper to debug and write code quickly.

There is a library on CodePlex called MissingLinq which tries to expose a lot of CIM functionality via LINQ, and I think that is a powerful concept that would help unify PowerShell and C# interfaces to CIM.  However, MissingLinq is over 2 years old and does not seem to be actively maintained.

**Comment by SteveL-MSFT** [comment] 2019-07-05 21:36
cc @adityapatwardhan

**Comment by jzabroski** [comment] 2019-07-05 21:45
Just to be clear, I think we may want to retitle this thread as "Allow composable Cim calls from C#".  This would retain the current package set-up, while allowing infrastructure engineers to write infrastructure mostly in C#.

Let me know if you understand why this is painful for me.  It's probably not obvious to someone who only does PowerShell and never uses C#.

For what it's worth, we're slowly making progress moving our PowerShell interfaces to C# and then exposing them as PowerShell Commands via thin wrappers around the C# logic we write.  We have found it significantly easier to benchmark and optimize the hell out of things like pinging giant networks of machines, doing scheduled reboots in ways that don't suck (_Hello, Microsoft Operations Manager_), etc.

**Comment by adityapatwardhan** [comment] 2020-01-13 16:28
This is a duplicate of #8119

**Closed by adityapatwardhan** 2020-01-13 16:28 UTC
Labels: Issue-Enhancement
