### ISSUE TITLE
prebuilt binary downloads should be available in flatpak format 

### ISSUE THREAD

**Issue by zaxebo1** [PowerShell/PowerShell#1924] opened 2016-08-19 01:07 UTC
on the releases page , please provide pre-built binary in two more formats 
1) flatpak format = (See flatpak.org) = In this way we can install it on multiple linux distributions, **and without requiring root password** . note that, flatpak format is accepted in many distributions by default ,like debian testing,fedora. In other distributions it can be installed as http://flatpak.org/getting.html    . This flatpak format is the most promising and buzzword of the packaging formats)

2) the debian stable .deb = currently debian linux stable is 8.5 ( see https://en.wikipedia.org/wiki/Debian )
# 

note: you may automate creation of the pre-built binaries formats using travis CI + github
( see https://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/  )

if you can support **only one** additional format, then support flatpak and drop debian stable .deb

**Comment by tidux** [comment] 2016-08-19 01:29
If it's just bootstrapping a build system there is no need for OS packages at all.  Build against Debian 8 for an old glibc and static-link the binary and you just have a single binary per system architecture to download.  Targeting Debian Stable is also optimal for cross platform usage, since creating a binary for Debian armel (ARMv5te soft float) would allow bootstrapping on Raspbian (ARMv6 hard float), and Debian already has ports to armhf (ARMv7 hard float) and arm64 (ARMv8).  Microsoft is typically big on home-lab usage, and using PowerShell to orchestrate a fleet of tiny Raspberry Pis or other cheap single board computers would be good practice for using it to orchestrate a fleet of VMs in AWS, Azure, locally-hosted Hyper-V, or (maybe some day) KVM+Libvirt.

**Comment by zaxebo1** [comment] 2016-08-19 19:04
additionally I will even propose that **LATER in future** the debian package be submitted to debian standard repository later. So that there is no need to get separate binary of powershell and using "dpkg" to install it.   The deb of powershell will become part of "debian package standard repository", which can be easily installed through "apt-get"

refer to:
http://askubuntu.com/questions/13255/how-do-i-propose-my-project-to-be-part-of-debian-too
http://askubuntu.com/questions/16446/how-to-get-my-software-into-ubuntu

**Comment by Sum1n** [comment] 2016-08-20 04:19
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by voltagex** [comment] 2016-08-21 05:45
@zaxebo1 already underway https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834756

@tidux it's always better to use the distro package manager.

This is pretty much a duplicate of #1903

**Comment by Carringguns** [comment] 2016-08-22 05:30
-------- Original message --------From: Adam Baxter <notifications@github.com> Date: 8/21/16  1:45 AM  (GMT-05:00) To: PowerShell/PowerShell <PowerShell@noreply.github.com> Subject: Re: [PowerShell/PowerShell] prebuilt binary downloads should be
  available in flatpak format and debian stable .deb format too (#1924) 
@zaxebo1 already underway https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834756

@tidux it's always better to use the distro package manager.

This is pretty much a duplicate of #1903

**Comment by SteveL-MSFT** [comment] 2016-09-29 21:31
This seems like a dupe of #1903 , reactivate if you don't agree

**Comment by zaxebo1** [comment] 2016-09-30 00:47
@SteveL-MSFT 
i do not agree, both are different issues

**Comment by zaxebo1** [comment] 2016-10-01 05:43
just a clarification: flatpak is a linux "distribution independent" format. It can install on any distribution, with minimal dependencies requirement.
 My request emphasis was more on flatpak format. So I have modified the title just to reflect my original indent of request more appropriately.

advantage of delivering in flatpak format will be: that I can install it without admin(root) permissions. I can install it on Redhat,Fedora, Debian,Arch etc - all of them now **officially** support flatpak. So with single release format one can easily target all the distributions.

**Comment by TravisEz13** [comment] 2020-03-02 18:35
@zaxebo1  What would be the purpose of a flatpak for PowerShell?  Since flatpaks always run in a sandbox, what use case did you have in mind?

**Comment by Gigadoc2** [comment] 2020-03-02 18:54
Well, most of the sandboxing can be turned off, but the filesystem will always not be that of the host, due to how the packaging works. So having powershell in flatpak would indeed not make much sense when using it as a shell for the local host.

But I wonder, isn't powershell also used for remoting? Having it in a flatpak might still be useful if you only want to use it for remote sessions.

**Comment by TravisEz13** [comment] 2020-03-02 21:37
@Gigadoc2 A flatpak would probably work for SSH remoting (also another sandbox that has to be turned off), but WSMan remoting is unlikely to work based on my experience with Snap (unless someone rewrites the MI implementation for Linux)

**Comment by TravisEz13** [comment] 2020-03-02 21:38
I already have a PR, that in theory, that should allow the flatpak to work for SSH remoting (I've done NO testing).
https://github.com/TravisEz13/PowerShell-flatpak/pull/3

**Comment by zaxebo1** [comment] 2020-03-02 21:41
i only want it be used for SSH remoting (say,for servers) only, not for local scripting.

**Comment by Gigadoc2** [comment] 2020-03-02 22:56
@TravisEz13 I am afraid I don't know much about WSMan, but isn't it running over HTTP? Apart from needing network access, how would the sandbox impede WSMan?

**Comment by TravisEz13** [comment] 2020-03-02 23:05
> how would the sandbox impede WSMan?

In theory, it shouldn't, but the library that implements WSMan is not maintained and critical bugs are not fixed.  It's not compatible with a modern runtime and takes hacks to make it run on most.  I'm not going to use an old runtime and hack it to make WSMan work.

**Comment by TravisEz13** [comment] 2020-03-02 23:10
One anyone ever try to use the PowerShell flatpak for device automation?    
If so, I don't know what device you want.  I'll have to say that the flatpak should have access to all devices.

**Comment by TravisEz13** [comment] 2020-03-02 23:51
I opened the sandbox for the filesystem and network. 
I published a release so you can test it.

https://github.com/TravisEz13/PowerShell-flatpak/releases/tag/v0.0.1

Install instructions are here:

https://github.com/TravisEz13/PowerShell-flatpak#installation

Verified client SSH remoting is working.

**Comment by TravisEz13** [comment] 2020-03-03 00:43
@zaxebo1 @Gigadoc2 How would you feel if flathub was the one building the flatpak?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-12 19:57
> http://github.com/PowerShell/PowerShell/issues/1924#issuecomment-593707024

Would that allow for automated building of the package? If any repository's build process should be used, currently [Flathub's](http://github.com/flathub) shall be the most useful.

**Comment by RokeJulianLockhart** [comment] 2023-11-16 22:09
https://discourse.flathub.org/search?q=powershell%20%23requests doesn't return anyone, so perhaps someone could make a post requesting that a repository be created.

**Closed** 2023-11-24 00:44 UTC
Labels: Area-Maintainers-Build, Resolution-No Activity

**Comment by RokeJulianLockhart** [comment] 2024-07-01 19:16
> https://github.com/PowerShell/PowerShell/issues/1924#issuecomment-1815392914

I've filed https://discourse.flathub.org/t/powershell-preview-flatpak-request/7213.
