### ISSUE TITLE
Rewrite FileSystemProvider as v2

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5785] opened 2018-01-04 06:33 UTC
The current FileSystemProvider is complex to maintain (small changes introduce regressions), expects NTFS, and not optimized.  We should consider writing a new v2 version that works side-by-side with the current implementation kept for backwards compatibility.

Reference related issues that we can't address in current provider due to compatibility concerns.

Related https://github.com/PowerShell/PowerShell/issues/5699

**Comment by iSazonov** [comment] 2018-01-04 08:54
I saw that .Net Core team is working on optimization in this area. I think we get these improvements in 2.1.0.

Also we already have #5002 - I've been looking into this and I think our globbing code is a weakness.

**Comment by lzybkr** [comment] 2018-01-04 16:46
If going down this route, you should consider making it easier to write any provider - the current interface is too difficult.

**Comment by SteveL-MSFT** [comment] 2018-01-04 16:52
@lzybkr agree, created https://github.com/PowerShell/PowerShell/issues/5789

**Comment by iSazonov** [comment] 2018-02-05 14:54
Note: in .Net Core 2.1 [File enumeration extensibility](https://github.com/dotnet/corefx/pull/26806). is expected.

**Comment by powercode** [comment] 2018-02-05 15:27
They have done a ton of work to make it both faster and more flexible. No more kernel roundtrips for each FileInfo.

**Comment by JoeSalmeri** [comment] 2019-10-22 22:04
@SteveL-MSFT 

Sorry, I did not mean to imply that the problem was your doing or something you created and I
certainly do appreciate all you have done since joining the team!

My issue is with the answers provided regarding the problem.

I have been in the field for 32 years and have programmed in at least 25 different programming
languages during my career.

In all cases, there is one common theme and answer to the question, "Why do we write programs?"

We program so that we can automate processes and produce reliable, consistent, and repeatable results.

There are very few cases or reasons why we would want to write code which produced results which were not repeatable or consistent (random number generator comes to mind) as that would defeat the purpose of automating the tasks.

If we were discussing what the expected behavior was versus what the actual behavior was that
is something that could be addressed (but maybe not desired) by changing your/my expectations
to match the actual behavior.

That is NOT the case here.  The same code run multiple times does not produce the same results.

Before taking the time to write up that bug and all the various situations, I spent CONSIDERABLE
time trying various syntax (trailing slashes, *, *.*, and others) to try and find a single syntax
that would produce a consistent result which could be used in code and did not one that would cover the use cases.

Any good developer is not going to write new code using existing code which does not produce repeatable results because then their code also becomes unreliable and unstable.

I'll bet that most PS developers have taken the route that I have which is to use external tools to
perform that functionality in their code so that they can get consistent repeatable results.

I take breaking code issues quite seriously too, however, when the original code is broke in the first
place, it makes sense to fix it regardless of whether it would break "other" code.

You can argue as to whether you want to label this as a bug or whether it was a design flaw, however, that does not change the fact that the existing code does NOT produce consistent results.

Imagine if the existing Copy-Item had a bug where it deleted the file after it copied it.  Using the
answer you provided, that would not be addressed because it might break existing code that depended on that bug.  I cannot imagine anyone considering that a good reason or answer.

It's been a while since I wrote all that up and reviewed it, however, there were also examples where
data loss occurs because there was no warning or confirmation.   That certainly goes against the
basic PS design principles of not doing harm without a warning.

While I appreciate that you opened the issue for FileSystemProvider V2, I am quite skeptical that it will ever occur based on your response here, your comment about "if #5785 ever gets done", and the fact that these issues have gone unaddressed pretty much since the beginning of PS.

Regardless of whether the existing code is fixed or whether a V2 is created, there should still
be a desired to provide this basic functionality in the product, especially one that is marketed
as the replacement for all of the other command shells.

I really hope that someone take up the task of addressing this most basic and core functionality.

Sincerely,

Joe

**Comment by SteveL-MSFT** [comment] 2020-12-07 19:16
Related https://github.com/PowerShell/PowerShell/issues/3575

**Comment by JoeSalmeri** [comment] 2020-12-07 22:28
@SteveL-MSFT 

Is FileSystemProvider v2 every going to be on the roadmap?

Seems like it just keeps getting bumped.

**Comment by iSazonov** [comment] 2020-12-08 10:34
I hope we resolve some perf issues with #12834 without waiting FSPv2. 

I believe FileSystemProvider v2 makes sense to overcome design limitations - simplify API, add cross provider file operations and so on.

**Comment by JoeSalmeri** [comment] 2022-06-03 14:38
@iSazonov @SteveL-MSFT

Any progress on FileSystem V2? Was hoping to hear some news as it's been 3 years.

If FileSystem V2 ever going to happen?

**Comment by iSazonov** [comment] 2022-06-03 17:59
>  as it's been 3 years

You need to multiply that by 5 to get the exact value. :-) And that will also answer your question - everyone just uses alternatives for many years that work quickly and correctly.

As for the many-many fixes in PowerShell itself, in fact, the code is spread out over four big parts - provider, globbing, session state, and the code of the cmdlets themselves. It would take months of systematic work to get this far. It would first require writing thousands of new tests to avoid destroying other providers. Then we would have had to accept dozens of breaking changes and changes to the public APIs. And finally rewriting a lot of code. Obviously nobody will do this.

**Comment by JoeSalmeri** [comment] 2022-06-03 18:24
@iSazonov 

If feels like 15 years :-)   Actually if I recall correctly the issues I reported all occur all the way back to at least PS 5.

With PS basically replacing cmd.exe you would think that making the basic functionality work would be important, I mean we are talking about copying files.

I also understand when bugs are hard to fix and how fixing them could break existing code but in the case of Copy-Item it is pretty much impossible to write code that can be run multiple times and produce the same results.   There are simple cases that work but when you start doing directories, using wildcards, and -Recurse then it flat out fails.

So the argument about breaking existing code kind of falls apart when it is so broken that nobody would write code using it because it does not work :-)

I responded to this because I was helping someone new learn PS and the Copy-Item issues came up in our discussion.

So does this mean that any thoughts on FileSystem V2 are dead?

**Comment by iSazonov** [comment] 2022-06-04 09:11
> So does this mean that any thoughts on FileSystem V2 are dead?

"FileSystem V2" is  a pro-trade mark. As I said, the work will inevitably involve four levels of code. If MSFT team were to do this, they would have to abandon all other work indefinitely. On the other hand, the effort on the community side would also remain frozen because MSFT team would not be able to review it.

**Comment by JoeSalmeri** [comment] 2022-06-04 16:26
Not sure what "FileSystem V2 is a pro-trade mark." is supposed to me.

"File System V2" was the term that SteveL-MSFT said about the issues I reported.

I get it the bad code will never be fixed and the V2 that I was told about is never going to happen.

It is no wonder why people get so angry with MS.

**Comment by doctordns** [comment] 2022-06-05 09:42
There is no point in getting angry. It is a classic problem that EVERY team that actually ships a product faces. Jeffrey Snover summed it is as: _To ship is to choose._  Sure a V2 Filesystem provider would be nice. But the resources of the team are finite and creating a new provider will be a lot of effort and would take some time.  Is that really the best use of the team's precious time? And if you do feel strongly, you (the royal you that is) are free to create an implementation and issue a PR.

**Comment by JoeSalmeri** [comment] 2022-06-05 16:41
@doctordns 

You may find a detailed review of the original bug report useful since if you are only read this ticket you are missing lots of information.

Here's the link:

    https://github.com/PowerShell/PowerShell/issues/10458

To be clear, I could care less about File System V2.

What I care about is the original problem being fixed.   

I was told it would have to wait for FileSystem V2.

Now I'm told that it is not going to happen either.

So basically the bug goes unfixed.

This is not a feature request, it is a bug where you cannot even run the same code twice and get the same results.

Who writes a program that cannot produce the same results with the same input?  

This is basic 101 computer software design.

I supported MS and MS Products during my 30+ year consulting career and I have seen plenty of good and some really bad.

I also recognize now much more clearly why people get so angry with MS.

**Comment by juvtib** [comment] 2022-06-06 04:49
I'm in the habit of telling people to use robocopy or rsync instead of Copy-Item. And I don't think this is a good place to be in. 

I think the right way to look at this is to look to the future. And look at the examples of .NET and Windows Terminal. They both had big jobs that were not popular. And after getting over the humps of open sourcing .NET and fixing the issues with cmd.exe, both projects have much brighter futures than their predecessors had.  

In part, I'm hopeful that learning from the current provider will make it easier to maintain and extend PowerShell in the future. 

The file system provider is a basic part of PowerShell. And the linked issues affect everyone to some degree. I would be happy if the PowerShell Team spent some time on this issue. 

-Mike

**Comment by JoeSalmeri** [comment] 2022-06-06 14:04
@juvtib 

I suspect a big part of the issue not being addressed is because Copy-Item handles all sort of providers like FileSystem, Environment, Variables, Functions, the registry, etc greatly complicating the situation.

I use robocopy or rsync too  and that is what I recommend to others but for something that was designed to be the shell replacement one would expect the basics to work.

One of the reasons given was that we cannot break existing code, but that kind of falls apart because Copy-Item cannot be used to write repeatable code in all but the most simple use cases.

I was hopeful when I was told about FS V2 but the focus seems to be on new features instead of making the basics solid.

**Comment by doctordns** [comment] 2022-06-07 12:44
Again - getting angry is pointless. Now that PowerShell is open source, you can see what the team is doing and what its priorities are. The bug you refer to is one I have never seen in practice - but I've only been using PowerShell for just short of 20 years. I can tell you, there are some tough tradeoffs that have to be made, but you can see the process (unlike in other WIndows components that are totally opaque in terms of the changer (The feedback hub is just a black hole).

The challenge here is that if the team 'fixes' this problem, it is likely to be a complex change (eg File System Provider (V2)) and would not be cheap, It also would almost certainly be a breaking change that could (would?) break a LOT of existing scripts that depend on the current behavior.  A targeted fix for just the original issue could be considered but this too has the potential to break stuff. And for me breaking stuff, without a really good reason, is just not acceptable.  Frankly, I would prefer to leave this as it is, with well-documented workarounds, than to try to fix it.  I do get that mileage may vary on this!

Like so many issues here in the repo, this is one I suspect we may just close as "won't fix - by design" which is what I am thinking today.  But can you convince the team that this is a bug that NEEDS fixing? Is there enough user demand for this change? Right now, I am not seeing the need to make this change today. But please convince me I am not looking in the right places.

**Comment by JoeSalmeri** [comment] 2022-06-08 16:48
@doctordns 

I too have been using PS for a very long time.

>>  The bug you refer to is one I have never seen in practice

I may certainly be wrong here but your comment leads me to believe that you didn't even read the bug report I referenced where I detailed *12* basic usage cases comparing and contrasting Copy-Item with, cmd copy, xcopy, and robocopy and how broken and unusable Copy-Item is for all but the most basic use case.

Closing an issue as by-design says that someone purposely designed Copy-Item to NOT be able to produce the same results when the same command and input is used.    You REALLY believe that someone would PURPOSELY do something like that?

Anyone that worked for my company that had that mentality would be fired.

Who writes programs that cannot produce the same consistent results?

Isn't the very reason we write programs is so that we can automate a process and produce the same results with the same input?

**Comment by theJasonHelmick** [comment] 2022-06-09 16:35
Hello everyone -- I appreciate the conversation.  Steve entered this issue as "We should consider " - which we continue to do.  This is complex work that raises many risks that could be far worse than the original problem.  @JoeSalmeri, I certainly appreciate the frustration this causes, however this is not work we have committed to yet until we understand the best path forward .  This work will continue to be evaluated by the Working group and I encourage folks to provide technical feedback that could support a solution. 

To help, I will discuss with the WG and get some current status information and report in the next couple of weeks.

**Comment by iSazonov** [comment] 2022-06-09 17:41
> I encourage folks to provide technical feedback that could support a solution.

In fact, the functionality is divided into four parts - cmdlets itself, Globbing, SessionState/SessionStateInternal.
Only Globbing could be easily isolated and replaced with new experimental code.
In addition, there are several classes that make internal APIs public to PowerShell SDK (like PathIntrinsics). This practically blocks changes of internal APIs if we strictly intend to avoid breaking changes.
As for cmdlets, I tried to strictly state PowerShell concepts in the RFC and found inconsistencies and deviations in the implementations. If we intend to conform strictly to PowerShell concepts and path manipulation rules, it will inevitably lead to a lot of breaking changes.
Among other things, there are performance problems which should have been solved if we are going to do anything in this area (i.e. path/file operations). This also requires changes on all four levels.
We could of course isolate the new code as an experimental feature starting with the cmdlet level, but as you understand we would have to re-design and write all four levels of code from scratch and this would inevitably affect all providers. So initially we should have written several thousand new tests for all providers and their cmdlets to avoid regressions. At the very least we need these new tests to open the door to innovation.

**Comment by JoeSalmeri** [comment] 2022-06-09 17:43
@theJasonHelmick 

Thank you Jason for your thoughtful reply, I really appreciate it.

I believe, but could certainly be wrong, that part of the complexity is because Copy-Item handles multiple providers which have some similarities are also very different.

For example, the env, and alias don't have the "directory" concept that the FileSystem Provider has.

When you discuss with the WG could you please present the items I provided in my bug report

    https://github.com/PowerShell/PowerShell/issues/10458

as it contains a detailed review of 12 use cases and compares Copy-Item, cmd copy, xcopy, and robocopy as well as a nice summary the findings for each use case and copy method.

Thank You!

**Comment by iSazonov** [comment] 2022-06-10 03:44
> > So initially we should have written several thousand new tests for all providers and their cmdlets to avoid regressions.
> 
> I agree about not breaking existing code with ONE exception.

My personal preference is to accept the inevitable.
This is reminiscent of the IE6 story. It was so popular that it was itself a standard, while violating all public standards. When its popularity declined, it became a serious problem. MSFT was forced to release 5 (!) versions of IE each introducing a new compatibility mode. This made IE so complicated that MSFT threw it out and said it would use Chrome!

Speaking of pwsh, there are about 50 breaking changes tagged in 2 1/2 years, plus probably as many more in the previous 2 1/2 years before 2016, plus things that were deliberately cut out (like workflow, etc.). As a result, we see a huge number of incompatibilities with Windows PowerShell. 
We accept this as inevitable.
The policy today is that all innovation is in pwsh only, Windows PowerShell is frozen.
Maybe it's time to take a new leap and say pwsh 7 is frozen, the last LTS will be 7.4 and all innovations will be in pwsh 8.
These innovations could modernize virtually all pwsh subsystems.
Of course, that would require a lot of effort. But I don't see how we could make it easier and cheaper within version 7. It's more of a dead-end way to transform IE6.

**Closed** 2022-07-07 21:01 UTC
Labels: Issue-Enhancement, Resolution-Won't Fix, WG-Engine-Providers, Needs-Triage, Area-FileSystem-Provider

**Comment by JoeSalmeri** [comment] 2022-08-18 17:08
@jdhitsolutions 

> The Cmdlet Working Group has reviewed this issue. While a new provider would/could provide benefits the costs of re-writing > the provider are high. We are marking this issue as Won't Fix

One would think that the FileSystemProvider is a key part of powershell and therefore it would be considered something that was important to make sure it worked properly in the basic use cases.

PowerShell is such a GREAT product overall but the desire to cram more features in when some of the basics are so badly broken defies logic.

**Comment by JamesWTruher** [comment] 2024-04-15 18:51
also this: #20651
