### ISSUE TITLE
text.encoding Invalid

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#17580] opened 2022-06-25 01:10 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
function UnescapeNonIsoChar($inputString) {
    Try {
        [regex]::replace($inputString, '(?:\\u[0-9a-f]{4})+', { 
            param($m) 
            $utf8Bytes = (-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])
            [text.encoding]::UTF8.GetString($utf8Bytes)
            
        })
    } Catch {
        [regex]::Unescape($inputString)
    }
}

@'
profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1
profile.header.customer=\u00e5\u00ae\u00a2\u00e6\u0088\u00b6\u00e5\u0090\u008d\u00e7\u00a8\u00b1
profile.header.account=\u00e5\u00b8\u00b3\u00e8\u0099\u009f/\u00e6\u00a2\u009d\u00e4\u00bb\u00b6\u00e4\u00bb\u00a3\u00e7\u00a2\u00bc
profile.header.description=\u00e6\u008f\u008f\u00e8\u00bf\u00b0
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user\u2019s layout cannot be updated.
'@ -split [System.Environment]::NewLine |
    ForEach-Object {
        UnescapeNonIsoChar -inputString $_
    }
Hit Variable breakpoint on '$string' (Write access)

At line:8 char:13
+             $string=[text.encoding]::UTF8.GetString($utf8Bytes)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[DBG]: PS C:\Users\he123>> [text.encoding]::UTF8.GetString($utf8Bytes)
檔案名稱
[DBG]: PS C:\Users\he123>> c
Hit Variable breakpoint on '$string' (Write access)

At line:8 char:13
+             $string=[text.encoding]::UTF8.GetString($utf8Bytes)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[DBG]: PS C:\Users\he123>> c
profile.header.profile=æªæ¡åç¨±
profile.header.customer=å®¢æ¶åç¨±
profile.header.account=å¸³è/æ¢ä»¶ä»£ç¢¼
profile.header.description=æè¿°
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user’s layout cannot be updated.
```

### Expected behavior

```console
profile.header.profile=檔案名稱 檔案名稱
profile.header.customer=客戶名稱 客戶名稱
profile.header.account=帳號 帳號/條件代碼 條件代碼
profile.header.description=描述 描述
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user’s layout cannot be updated.
```

### Actual behavior

```console
profile.header.profile=æªæ¡åç¨±
profile.header.customer=å®¢æ¶åç¨±
profile.header.account=å¸³è/æ¢ä»¶ä»£ç¢¼
profile.header.description=æè¿°
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user’s layout cannot be updated.
```

### Error details

```console
æªæ¡åç¨±
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment] 2022-06-25 01:23
I’ve yet to look at the full code but you are trying to convert the unicode codepoint to a byte and treat that as utf-8 bytes. This isn’t correct as the `\uxxxx` is a unicode codepoint and you can treat it as a representation of a char. For example instead of

```powershell
$utf8Bytes = (-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])
[text.encoding]::UTF8.GetString($utf8Bytes)
```

You should be doing

```powershell
[char][int]($m.Value -replace '\\u([0-9a-f]{4})', '0x$1') 
```

This should give you the hex representation of the codepoint (`0x00E6`), cast it to an integer, then finally cast that integer to the char. When it gets replaced back into the string it becomes a string.

This is untested so the code you need might be slightly different.

**Comment by jborean93** [comment] 2022-06-25 01:45
If we take a short snippet we can test this out

```powershell
'profile.header.profile=\u00e6\u00aa\u0094\u00e6' -replace '\\u([0-9a-f]{4})', {
    [char][int]($_.Value -replace '\\u([0-9a-f]{4})', '0x$1') 
}
```

This outputs

```
profile.header.profile=æªæ
```

It's not your expectation but it matches the `\u` escape values you have.

* [\u00e6](https://www.fileformat.info/info/unicode/char/00e6/index.htm) - `æ`
* [\u00aa](https://www.fileformat.info/info/unicode/char/00aa/index.htm) - `ª`
* [\u0094](https://www.fileformat.info/info/unicode/char/0094/index.htm) - `”` (seems to be a control character which is why it isn't shown)
* [\u00e6](https://www.fileformat.info/info/unicode/char/00e6/index.htm) - `æ`

I have noticed that the expectation is based on each codepoint being a raw byte. So my comments above do not apply.

What is weird is your reproducer does what you want, it is correctly encoding each `\uxxxx` as a byte and you are correctly encoding those bytes to the proper string character. When I run it in my console I get the expected result back.

**Comment by he852100** [comment] 2022-06-25 03:10
It is utf8 encoded
\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1
e6aa94：檔
\u00e6\u00a1\u0088 
e6a188：案
----
(-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])  
is:
\u00e6 to 0x00e6 to 230 byte(hex to dec)   

No problem with the code
  
![image](https://user-images.githubusercontent.com/26913892/175755988-06d020a9-fb45-44f8-b45b-4f358cd82fec.png)

You should note that it works during debugging，When it is saved as a PS1 file, it works properly

**Comment by kasini3000** [comment] 2022-06-25 13:58
> When it is saved as a PS1 file, it works properly It always uses iso-8859-1 no matter how you tweak it

try:
save ps1 file add BOM head,encoding any
ps1 内若含有中日韩等编码，必须保存成bom头，编码任意。
即bom+utf8可以，bom+utf16le也行。

**Comment by he852100** [comment] 2022-06-25 17:32
> > When it is saved as a PS1 file, it works properly It always uses iso-8859-1 no matter how you tweak it
> 
> try: save ps1 file add BOM head,encoding any ps1 内若含有中日韩等编码，必须保存成bom头，编码任意。 即bom+utf8可以，bom+utf16le也行。 bom头，bom头，有头无乱码。还支持中文变量名，韩文变量名，参数名，参数值，等。
> 
> 注意：你的代码，只要加上bom头保存。在powershell 5.1，powershell 7.3 preview中运行毫无问题，已经测试。
> 
> \u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7 ----这些东西在我眼中视为幺蛾子。你用任意编码的字符串，转成base64，继而传递，即可避免幺蛾子。避免编码转换，避免编码不识别。

求求你，不会，不懂不要乱说。

**Comment by kasini3000** [comment] 2022-06-25 18:56
Fake issue, just change the machine

**Comment by he852100** [comment] 2022-06-25 19:52
Omg, he wants to sell me software!  
His answer is off topic and makes no sense

**Comment by he852100** [comment] 2022-06-25 20:03
![image](https://user-images.githubusercontent.com/26913892/175788942-a8874351-5814-4870-895c-eb0e9f0bed10.png)
@kasini3000 还需要看什么版本我帮你测试哈。

**Comment by jborean93** [comment] 2022-06-26 05:41
When running on Linux I get your expectations (when running your code).

![image](https://user-images.githubusercontent.com/8462645/175799111-c8956290-3f29-4d50-967b-f511fd7ff24e.png)

I notice you are running on Windows whereas I am running on Linux. So this is mostly some problems dealing with the different environments. Looking at your code I see a few things that could be the problem.

### Splitting your String with -split [System.Environment]::NewLine

Technically Windows newlines are both the carriage return and newline `\r\n` but in your example you've input a string using a here string. In PowerShell (both WinPS and PowerShell) this results in it being just a newline

![image](https://user-images.githubusercontent.com/8462645/175799505-c397c3fa-90b7-4dfa-9a7c-a6901664ca0a.png)

This means `-split [System.Environment]::NewLine` won't work as you expect on Windows because the output will contain the full text rather than an array of each line

![image](https://user-images.githubusercontent.com/8462645/175799559-a3d207c6-f738-41a0-bb8e-f833226687a1.png)

If you compare that on a non-Windows host where `[System.Environment]::NewLine` is just the `\n` we see the value is safely split into each line

![image](https://user-images.githubusercontent.com/8462645/175799600-8ad6254b-28da-43e1-9261-c9ae550e5482.png)

Why this is important is explained in the final point.

### The `\u2019` example doesn't work with your encoding scheme

This goes into my original point where you are treating unicode codepoints as raw bytes that are UTF-8 encoded. This is not what you should be doing with raw unicode codepoints. We can notice this being a problem with the `\u2019` example in the last example. The `\u2019` is meant to represent [U+2019](https://www.fileformat.info/info/unicode/char/2019/index.htm) which is a smart right quote `’`. The 2019 is the raw unicode codepoint and you can easily get this value by just casting the hex value to a `[char]` like so

![image](https://user-images.githubusercontent.com/8462645/175799674-977a342f-2c4f-44c6-98ca-1c9f83542401.png)

This goes against your previous encoding scheme where the source text has encoded raw bytes as a `\uxxxx` format. The code you currently have will convert `2019` to `0x2019` and try to encode that to a byte which fails because it is too large. Even if you had the code to try and convert to the `[byte[]]@(0x20, 0x19)` and then try and decode that using UTF-8 you will get 2 characters; [U+0020 Space](https://www.fileformat.info/info/unicode/char/0020/index.htm) and [U+0019 End of Medium](https://www.fileformat.info/info/unicode/char/0019/index.htm). If you control the code that is generating your text you really need to fix it up so it encodes your characters correctly. For example if you want the first line to be `profile.header.profile=檔案名稱` the escaped string should be

```
profile.header.profile=\u6a94\u6848\u540d\u7a31
```

Each of the characters you have are represented by their Unicode codepoint values, rather than trying to smuggle in the UTF-8 byte representation. The code then simply becomes

```powershell
# This is whatever you want to unescape
$content = 'profile.header.profile=\u6a94\u6848\u540d\u7a31'

$content -replace '\\u([0-9a-f]{4})', {
    [char][int]"0x$($_.Groups[1])"
}
```

Ignoring that fact, the presence of this line causes the regex replace to fail because it's unable to cast the entry `\u2019`

> Cannot convert argument "item", with value: "0x2019", for "Add" to type "System.Byte": "Cannot convert value "0x2019" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte.

This brings me to my final point

### A failure on the regex replacement has a fallback

The function has a fallback if `[Regex]::Replace` fails by calling `[Regex]::Unescape($inputString)`. Because on Windows you are processing the entire content rather than per line it's always going to fail because it's trying to process `\u2019`. This means the entire content will be unescaped rather than the line entry.

Let's see the behaviour of

```powershell
[Regex]::Unescape("profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1")
```

On both Linux this becomes `profile.header.profile=æªæ¡åç¨±` (what you are getting) due to Regex unescaping the raw unicode codepoints as actual unicode codepoints rather than UTF-8 bytes being smuggled into the codepoints. This is directly related to my 2nd point where your input string isn't really done properly.

### Summary

All in all you should fix up whatever is generating this text to properly encode the Unicode characters rather than have it encode it as Unicode codepoints that represent the UTF-8 bytes of the character. For example:

```powershell
# The string should be this
'profile.header.profile=\u6a94\u6848\u540d\u7a31'

# But not this
'profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1'
```

If you cannot change this then you need to fix up the `-spit [System.Environment]::NewLine` to properly split by newlines on Windows. A very nice way to split by newline and not care whether it's `\r\n` or `\n` you can do `-split "\r?\n"`, so

```powershell
function UnescapeNonIsoChar($inputString) {
    Try {
        [regex]::replace($inputString, '(?:\\u[0-9a-f]{4})+', { 
            param($m) 
            $utf8Bytes = (-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])
            [text.encoding]::UTF8.GetString($utf8Bytes)
            
        })
    } Catch {
        [regex]::Unescape($inputString)
    }
}

@'
profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1
profile.header.customer=\u00e5\u00ae\u00a2\u00e6\u0088\u00b6\u00e5\u0090\u008d\u00e7\u00a8\u00b1
profile.header.account=\u00e5\u00b8\u00b3\u00e8\u0099\u009f/\u00e6\u00a2\u009d\u00e4\u00bb\u00b6\u00e4\u00bb\u00a3\u00e7\u00a2\u00bc
profile.header.description=\u00e6\u008f\u008f\u00e8\u00bf\u00b0
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user\u2019s layout cannot be updated.
'@ -split "\r?\n" | ForEach-Object { UnescapeNonIsoChar -inputString $_ }
```

I still want to stress you should fix up whatever is generating the strings to generate them properly rather than using this hack but the `-split "\r?\n"` is a workaround to ensure you process this line by line and any lines that cause a failure in the replacement code won't affect each other.

**Comment by he852100** [comment] 2022-06-26 06:10
> 
I'm feeding back bugs. Please note that it is a utf8 encoded character, not Unicode (utf16)

https://www.youtube.com/watch?v=hNNeldPcTfs

I don't need to replace methods, it's something they need to fix

**Comment by jborean93** [comment] 2022-06-26 06:17
>  Please note that it is a utf8 encoded character

I'm sorry but this is just incorrect, text has no explicit encoding until you make it bytes. In this case the `\uxxxx` represents the Unicode codepoint. This is not UTF-8, UTF-16-, UTF-32, or some other Unicode encoding scheme but where the character fits on the unicode character table. For example the character `檔` https://www.compart.com/en/unicode/U+6A94 is denoted by the Unicode codepoint U+6A94` and when escaped in a string becomes `\u6a94`. Notice how the codepoint `U+xxxx` directly corresponds to the `\uxxxx` value. We can see that yes when represented as UTF-8` the bytes are `0xE6, 0xAA, 0x94` but that does not mean the `\u` escape sequence for that character is `\u00e6\u00aa\u0094`, it is truly `\u6a94`. You can even see that by using builtin methods with .NET to escape that

![image](https://user-images.githubusercontent.com/8462645/175802080-df48559c-3506-43b8-a9d7-1589692692e5.png)

If you want to continue using the incorrect interpretation that `\uxxxx` is a way to interpret the UTF-8 encoded form of the codepoint then you need to fix up the `-split` logic so that a failure in 1 line doesn't affect the others. Put simply your code is mixing 2 different ways of doing things and your attempts at working around an error is causing the failure. Nothing PowerShell needs to do here as it's working correctly. I've even given you code that will work on both platforms.

**Comment by kasini3000** [comment] 2022-06-26 06:20
>我帮你测试

what ? you help me ?

----

this issue use new install vm test ,It's easy to spot and can't reproduce the problem.
is support ，not bug！

----

I see that your two issues are related to business. It looks like a Hong Kong banking institution.
 I don't recommend finding the ps community team for specific technical support. It is recommended to go to the forum to find FREE business technical support.

----

In general, the psteam community team does not provide support outside of powershell.
For Hong Kong business organizations, slqite libraries and scripts are provided. Is 15$ a lot?

**Comment by he852100** [comment] 2022-06-26 06:44
> If you want to continue using the incorrect interpretation that is a way to interpret the UTF-8 encoded form of the codepoint then you need to fix up the logic so that a failure in 1 line doesn't affect the others. Put simply your code is mixing 2 different ways of doing things and your attempts at working around an error is causing the failure. Nothing PowerShell needs to do here as it's working correctly. I've even given you code that will work on both platforms.`\uxxxx``-split`

![image](https://user-images.githubusercontent.com/26913892/175802531-d2ba8d5c-39aa-4ccb-8125-1f56ede937a2.png)


It was explained clearly in my first reply, actually this is just an example, this kind of thing happens quite often during transcoding

**Comment by he852100** [comment] 2022-06-26 17:47
> I'm sorry but this is just incorrect, text has no explicit encoding until you make it bytes. In this case the represents the Unicode codepoint. This is not UTF-8, UTF-16-, UTF-32, or some other Unicode encoding scheme but where the character fits on the unicode character table. For example the character https://www.compart.com/en/unicode/U+6A94 is denoted by the Unicode codepoint and when escaped in a string becomes . Notice how the codepoint directly corresponds to the value. We can see that yes when represented as UTF-8 the bytes are but that does not mean the escape sequence for that character is , it is truly . You can even see that by using builtin methods with .NET to escape that\uxxxx檔U+6A94\u6a94U+xxxx\uxxxx0xE6, 0xAA, 0x94\u\u00e6\u00aa\u0094\u6a94

It can be any form: 

\uxxxx,    
0x0000,    
0x00,     
000000    
or ababababab, it doesn't matter what form it is. \uxxxx, 0x0000, 0x00 will eventually become continuous characters like '000000', just convert it into a byte array. Here it is utf8 encoding.
You can make a valid judgment here by decoding the entire string, instead of decoding a single unicode character using something like '[char]', in this example you fall into a trap, and you end up with a messy string

**Comment by jborean93** [comment] 2022-06-26 21:25
This is my last try, if you don't understand what is wrong after this you are on your own.

Yes it can be any form but mostly languages go for the `\uxxxx` format where `xxxx` is the Unicode codepoint value. Using `檔` as an example again we can find the Unicode information at https://www.compart.com/en/unicode/U+6A94. It has the following properties

* The Unicode codepoint is `U+6a94`
* The UTF-8 byte representation is `0xE6, 0xAA, 0x94`
* The UTF-16-LE byte representation is `0x6A, 0x94`
* The UTF-32-LE byte representation is `0x00, 0x00, 0x6A, 0x94`

A few extra things I want to stress

* Unicode != UTF-16-LE
  * Microsoft products sometimes lumps them into the same thing but
  * Unicode is the standard
  * UTF-16 is an encoding scheme of how Unicode characters are encoded to bytes
* The Unicode codepoint `U+6a94` is pretty much the UTF-16-le byte representation but that's just a coincidence
  * Due to how UTF-16 was originally written, any Unicode characters in the `0x7FFF` range are encoded as their codepoint which is why they match
  * You don't really need to know this fact, just that when I talk about `\uxxxx` I am talking about the Unicode codepoint and not the UTF-16-LE byte representation

What you are doing is you are taking the UTF-8 byte representation and trying to smuggle it in using escaped Unicode codepoint sequences so it becomes `\u00e6\u00aa\u0094`. This is not strictly correct as this character when represented by the proper unicode codepoint is `\u6a94` (because it's `U+6a94`, the code you have technically works because you are interpreting `\uxxxx` as the UTF-8 bytes. Ignoring PowerShell and dotnet you can see that other language prove me correct in this statement, to display `檔` I need to use `\u6a94` and not `\u00e6\u00aa\u0094`

![image](https://user-images.githubusercontent.com/8462645/175833454-ce13526e-c998-4371-88e9-6485213bed32.png)

One thing I do need to mention, `U+6a94` is pretty much the equivalent of both of the UTF-16-LE bytes. This is just how UTF-16 works. Ignore that coincidence for now as UTF-16 was originally designed to map the Unicode codepoint values until they found out the space wasn't large enough. Just know that the value of the Unicode codepoint (what starts with `U+xxxx`) is what we are talking about.

Notice that I am running in Python which is completely unrelated to PowerShell and their documentation mentioned the `\uxxxx` https://docs.python.org/3/howto/unicode.html format

PowerShell even has it's own standard by using the backtick u escape sequence and the value hex value of the Unicode codepoint (not necessarily the UTF-16-LE byte representation).

```powershell
`u{xxxx}`
```

![image](https://user-images.githubusercontent.com/8462645/175833561-e065451c-2b12-49c4-8126-e67507b02175.png)

Notice how yet again only the Unicode codepoint `U+6a94` works in the scenario. Trying to use the UTF-8 bytes as the value for each codepoint results in that erroneous string you mentioned.

Hopefully this convinces you why I am saying doing `\u00e6\u00aa\u0094` to represent the character `檔` is incorrect. In saying that the code you've written does correctly escape the `\uxxxx` codepoints as UTF-8 bytes as I you can see by just running it against your first line

```powershell
function UnescapeNonIsoChar($inputString) {
    Try {
        [regex]::replace($inputString, '(?:\\u[0-9a-f]{4})+', { 
            param($m) 
            $utf8Bytes = (-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])
            [text.encoding]::UTF8.GetString($utf8Bytes)
            
        })
    } Catch {
        [regex]::Unescape($inputString)
    }
}

UnescapeNonIsoChar -inputString 'profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1'
```

![image](https://user-images.githubusercontent.com/8462645/175833375-fc0e7c61-29f0-4999-83d9-b29368adbd35.png)

Notice how this is the exact same code as what you have and the output is correct. This is even running on Windows to replicate the platform you are on.

Notice what happens when you try and do the first and last line

```powershell
function UnescapeNonIsoChar($inputString) {
    Try {
        [regex]::replace($inputString, '(?:\\u[0-9a-f]{4})+', { 
            param($m) 
            $utf8Bytes = (-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])
            [text.encoding]::UTF8.GetString($utf8Bytes)
            
        })
    } Catch {
        [regex]::Unescape($inputString)
    }
}

UnescapeNonIsoChar -inputString @'
profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user\u2019s layout cannot be updated.
'@
```

![image](https://user-images.githubusercontent.com/8462645/175833855-95da6ff2-0fcc-4c0b-8351-557e40f3613f.png)

The text that worked before is now failing. This is because of the entry `\u2019` in the last line causing the `[Regex]::Replace` call to fail and the input string falling back to `[Regex]::Unespace($inputString)` to be called. The reason why this is failing because `\u2019` cannot be converted to a single byte

![image](https://user-images.githubusercontent.com/8462645/175833933-7e8be393-6713-46c8-83d5-c63b0e66b54e.png)

In fact what `\u2019` presents is the [Right Single Quotation Mark](https://www.compart.com/en/unicode/U+2019). Notice how this codepoint is `u+2019` and it matches the same value as `\u2019` in the text. The presence of this value in the string causes the entire regex replacement to fail, moving it to the `[regex]::Unescape($inputString)` call in your catch block. This `Unespace` method is unescaping `\uxxxx` as per the rules I've talked about above which is why you get the different strings.

This is critical to understand, a failure in the `[Regex]::Replace` method causes it to go through `[Regex]::Unescape` which is why you get the wrong output back. When you combine this with the fact that the `-split [System.Environment]::NewLine` isn't actually splitting your here string you can notice that the whole function is being called on the full string rather than line by line. The full string contains the `\u2019` entry causing the failure with your logic which causes the `\uxxxx` entries in the previous lines to be escaped by their Unicode codepoint value.

To prove that the split doesn't work look at the result of this

```powershell
Function Test-PerLine {
    [CmdletBinding()]
    param (
        [Parameter(ValueFromPipeline)]
        [string]
        $InputObject
    )
    
    begin { $i = 0 }
    process {
        $i++
        "Line: $InputObject"
    }
    end {
        "Lines processed; $i"
    }
}

@'
line 1
line 2
'@ -split [System.Environment]::NewLine | Test-PerLine

@'
line 1
line 2
'@ -split "\r?\n" | Test-PerLine
```

![image](https://user-images.githubusercontent.com/8462645/175834145-3bf25ed1-3e27-48fc-aaf2-a93e526dd501.png)

Notice how when `-split [System.Environment]::NewLine` was used the function was only called once (`Lines process: 1`) whereas when `-split "\r?\n"` was used it was passed in line by line. If you were to adjust your code so it did `-split "\r?\n` you will notice it works

```powershell
function UnescapeNonIsoChar($inputString) {
    Try {
        [regex]::replace($inputString, '(?:\\u[0-9a-f]{4})+', { 
            param($m) 
            $utf8Bytes = (-split ($m.Value -replace '\\u([0-9a-f]{4})', '0x$1 ')).ForEach([byte])
            [text.encoding]::UTF8.GetString($utf8Bytes)
            
        })
    } Catch {
        [regex]::Unescape($inputString)
    }
}

@'
profile.header.profile=\u00e6\u00aa\u0094\u00e6\u00a1\u0088\u00e5\u0090\u008d\u00e7\u00a8\u00b1
profile.header.customer=\u00e5\u00ae\u00a2\u00e6\u0088\u00b6\u00e5\u0090\u008d\u00e7\u00a8\u00b1
profile.header.account=\u00e5\u00b8\u00b3\u00e8\u0099\u009f/\u00e6\u00a2\u009d\u00e4\u00bb\u00b6\u00e4\u00bb\u00a3\u00e7\u00a2\u00bc
profile.header.description=\u00e6\u008f\u008f\u00e8\u00bf\u00b0
layout.msg.updatePrimaryUsersLayout=Kindly save it as a New Layout as Primary user\u2019s layout cannot be updated.
'@ -split "\r?\n" |
    ForEach-Object {
        UnescapeNonIsoChar -inputString $_
    }
```

![image](https://user-images.githubusercontent.com/8462645/175834254-403ecd0a-1462-469e-b33c-0ed7230c1c84.png)

The reason why goes into all my points above. Each line is now being processed one by one (`UnescapeNonIsoChar` is called per line rather than the whole thing). Each line is being converted using your regex replace logic of treating `\uxxxx` as UTF-8 bytes. Even the last line where `\u2019` is failing to be replaced with your logic is falling back to the `[Regex]::Unescape` which will convert `\u2019` using the Unicode codepoint logic. This gives you exactly what you want. The only caveat will be if you have a line that contains both the logic where `\uxxxx` is a UTF-8 byte representation and the Unicode codepoint. This is why I am recommending that you fix up whatever is generating the text to do it properly.

If you don't believe me after this I'm not sure what else I can do to convince you. PowerShell is acting sane here. There is no bug here as other languages treat `\uxxxx` in the same manner as `[Regex]::Unescape` and what I am telling you. Good luck with your work.

**Comment by daxian-dbw** [comment] 2022-06-28 18:54
@jborean93 Thanks for your replies, I surely learnt something in this discussion 👍

**Comment by kasini3000** [comment] 2022-06-29 14:34
thanks @jborean93 ,
btw: my name is Usain.Bolt, would you like to learn to gone faster with me?  ;)

**Closed** 2022-07-01 00:01 UTC
Labels: Resolution-Answered

**Comment by he852100** [comment] 2022-07-01 05:44
@kasini3000 Thanks for your popular science, but you are stealing the concept. An error in the last line causes the previous conversion using [text.encoding]::UTF8.GetString() to become garbled, rather than requiring a large space to describe whether the encoding is correct.
I don't want to know if it gives an error, what I want to express is that it outputs garbled characters

@daxian-dbw 我说乱码了他给我解释一通如何编码。不知道编码我会这么写么。出错会导致输出编码改变（我的理解），但运行ps1没这问题。
