### ISSUE TITLE
Several Cmdlets from Microsoft.PowerShell.Utility are missing

### ISSUE THREAD

**Issue by ffeldhaus** [PowerShell/PowerShell#2123] opened 2016-08-29 21:31 UTC
The following Function and Cmdlets are missing from Microsoft.PowerShell.Utility

``` powershell
Function        ConvertFrom-SddlString                             3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          ConvertFrom-String                                 3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Convert-String                                     3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          ConvertTo-Html                                     3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Export-PSSession                                   3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Import-PSSession                                   3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Out-GridView                                       3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Out-Printer                                        3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Send-MailMessage                                   3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Show-Command                                       3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Unblock-File                                       3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Update-List                                        3.1.0.0    Microsoft.PowerShell.Utility
```

It would be great if at least the `Convert-FromString`, `Convert-String`, `ConvertTo-Html`, `Send-MailMessage` and `Update-List` Cmdlets get implemented. The `Out-GridView`and `Show-Command` Cmdlets may be difficult due to graphical interface requirements, similar for `Out-Printer` with external printer requirement. A removal notice (ideally including explanation) should be added to the release notes for the other Cmdlets if they will be permanantly removed.

**Comment by vors** [comment] 2016-08-31 11:51
[Command availability table](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#command-availability) need to be updated.

**Comment by MaximoTrinidad** [comment] 2016-09-04 18:40
I just coming up with these missing ones.  But specially I was need the ConvertTo-Html cmdlet.

**Comment by paxpacis** [comment] 2016-09-07 10:48
+1 on the missing ConvertTo-Html

**Comment by edvail** [comment] 2016-09-07 11:40
Missing Send-MailMessage

**Comment by paxpacis** [comment] 2016-09-07 11:45
This example from Technet to solve my issue with missing the ConvertTo-Html cmdlet does not work either.

`
$URL = Read-Host "Enter URL to Decode" 
$Encode = [System.Web.HttpUtility]::UrlEncode($URL) 
Write-Host "This is the Encoded URL" $Encode -ForegroundColor Green`

`
+   $Encode = [System.Web.HttpUtility]::UrlEncode($URL)
+             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Web.HttpUtility:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound`

**Comment by alanrenouf** [comment] 2016-09-08 04:40
+1 on the missing ConvertTo-Html

**Comment by westforkfab** [comment] 2016-10-06 23:02
I successfully build the PS module in Ubuntu 16.04 as shown in https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md

I am doing some tests and I have this error:

Unable to find type [System.Net.ServicePointManager].

Also I can't find [System.Web].

**Comment by SteveL-MSFT** [comment] 2016-11-03 00:07
@PowerShell/powershell-committee reviewed this, show-command, unblock-file, out-gridview, out-printer won't be in PowerShell Core.  ConvertFrom-String and Convert-String is dependent on MSR.  The other ones should be in PS Core.

**Comment by Liturgist** [comment] 2016-11-12 02:54
Is there any documentation I could read to get a better understanding of the planned structure? Is there a definition of PowerShell Core? Are there other PowerShell ??? kits defined?

Today I was looking for [System.Web.HttpUtility]::HtmlEncode(), but ended up using [uri]::EscapeDataString() mentioned in this issue. Not totally the same thing.

**Comment by pcgeek86** [comment] 2017-02-07 22:26
Are there plans to implement Send-MailMessage? Maybe this should be broken out into separate issues for specific cmdlet implementations.

**Comment by LeeSartorelli** [comment] 2017-09-12 03:22
Is ConvertFrom-String going to be added? I see in a comment above it is dependent on MSR.... what does this mean?

**Comment by SteveL-MSFT** [comment] 2017-09-12 03:56
No plans at this time to port ConvertFrom-String.  MSR means Microsoft Research.  That cmdlet uses code not planned to be Open Source.

**Comment by MathiasMagnus** [comment] 2017-11-05 15:18
I was wondering what is the fundamental opposition against `Unblock-File`. The problem is, that without it on Windows, PS Core as it is, is very hard to use. #2657 shows that there is a **major** perf difference when it comes to downloaded content, may that be from the browser or an installed module.

_(I suspect that the ~5 second startup time of PS6 versus ~0.7 second startup of PS5 is due to some similar difference, even though I unblocked the entire PS6 install dir and all downloaded modules already. Something must still remain unblocked I guess.)_

I really want to advocate PS6 at my institute for daily use not just by sysadmins, but also end users. Truth is, discrepancies like Unblock-File, the total absence of NetAdapter cmdlets really take a toll on its view. I must say things like:

"Well, if you're on Windows, you can configure your network like this. If you're on Linux, you still gotta go with the same config files and/or config utilities. If you're on Windows, you gotta unblock the downloaded content you trust; to do that, pop-open another shell with slightly different language rules (& operator vs. operator &) and issue that oneliner there."

These stuff breaks the workflow and generally give the picture, that PS6 is a hack. I will probably demo PS5 on Windows and PS6 on Linux and just silently omit the differences (and also not show any of the differing parts which hurts usability on both ends), and also one has to make do with stuff like: don't use Workflow Foundation, because that stuff is not portable, also don't use DSC, beause proper PowerShell DSC resources don't exist yet (OMI+Linux vs. WMI is a strange duality, I'd rather mention DSC only when it's properly portable), even if it did, the number of Linux resources **greatly** lack landscape. (User, Group, Package and File. Really??? No NetAdapter, DNS, PackageMirror, PXEServer, PXEClient, ApacheServer or any of the interesting stuff??)

Apologies for the lengthy ranting, I understand that PS6 is the first step on a very long journey, but missing core cmdlets that are part of the basic workflow doesn't paint a good picture. Download a zip from web, extract/expand, deploy and run.

- iwr recently caught up to browser/*nix wget speed (#2656)
- Unzipping itself is still 6X slower than 7zip ([issue](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/32))
- PS6 launches 7X slower than PS5 (mentioned before)
- PS6 cannot even unblock itself to omit triggering AMSE on **every** startup

How should I advocate PS6 with these issues? Any Linux sysadmin will think operning a terminal in 5 seconds is a joke already.

**Comment by MathiasMagnus** [comment] 2017-11-05 16:02
_Just to be fair, when no `$PROFILE` file exists, PS6 launches just as fast as PS5 (with a simple profile). If I create an empty `$PROFILE` file, (totally empty), it adds 4 seconds to the startup time._

**Comment by iSazonov** [comment] 2017-11-05 18:55
@MathiasMagnus We already have ` Unblock-File ` in PowerShell Core.  Microsoft.PowerShell.Archive is not in the repo.
Did you run startup tests on the latest version?

**Comment by iSazonov** [comment] 2017-11-05 19:05
Current status:

- [x] ConvertFrom-SddlString
- [ ] ConvertFrom-String    
- [ ] Convert-String        
- [x] ConvertTo-Html        
- [x] Export-PSSession      
- [x] Import-PSSession      
- [ ] Out-GridView          
- [ ] Out-Printer           
- [x] Send-MailMessage      
- [ ] Show-Command          
- [x] Unblock-File          
- [ ] Update-List

**Comment by MathiasMagnus** [comment] 2017-11-06 17:07
Well, it exists, it just doesn't work.

```PowerShell
PS C:\Users\Matty> Unblock-File $PROFILE
Unblock-File : A rendszer nem találja a megadott fájlt
At line:1 char:1
+ Unblock-File $PROFILE
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\Matty\...ell_profile.ps1:String) [Unblock-File], Win32Except
   ion
    + FullyQualifiedErrorId : RemoveItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.UnblockFileCommand

PS C:\Users\Matty> Test-Path $PROFILE
True
```

It throws an UnautorizedAccessError exception on my own profile, and any file I tested it with. How can my setup go wrong?

**Comment by SteveL-MSFT** [comment] 2017-11-06 17:32
@MathiasMagnus working for me on beta.9 using win-x64.zip release:

```powershell
unblock-file .\PowerShell-6.0.0-beta.9-win-x86.zip
```

However, if the file is not blocked, you will get that error message:

```powershell
#running second time
PS C:\Users\slee\Downloads> unblock-file .\PowerShell-6.0.0-beta.9-win-x86.zip
unblock-file : The system cannot find the file specified
At line:1 char:1
+ unblock-file .\PowerShell-6.0.0-beta.9-win-x86.zip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\Users\slee\D...a.9-win-x86.zip:String) [Unblock-File], Win32Exception
+ FullyQualifiedErrorId : RemoveItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.UnblockFileCommand
```

We should probably quietly succeed if that stream isn't available to remove.  Created issue https://github.com/PowerShell/PowerShell/issues/5353

**Comment by MathiasMagnus** [comment] 2017-11-07 12:57
@SteveL-MSFT Thanks for looking into it, and thanks to @iSazonov for the fix. Not being a .NET developer (C++ and GPGPU) I very often feel dumb when I try to debug anything PS related. I just use it as an interactive shell (and very little scripting) as a replacement for bash, but with an actual type system (something I feel home at).

**Comment by iSazonov** [comment] 2017-11-07 13:26
@MathiasMagnus We welcome any feedback. Not only bugs but also the most hot features.

**Comment by SteveL-MSFT** [comment] 2017-11-07 21:09
I'm prepping a PR to add `Update-List` the other cmdlets we don't have any plans to port

**Comment by christian-korneck** [comment] 2017-12-31 01:04
Just out of interest: What's the reason why `Out-GridView`  won't be part of PS Core?

**Comment by rkeithhill** [comment] 2017-12-31 01:14
The current implementation (in Windows PowerShell) uses WPF which isn't available on Linux or macOS.

**Comment by christian-korneck** [comment] 2017-12-31 01:29
@rkeithhill thanks for the explanation!

**Comment by iSazonov** [comment] 2017-12-31 07:46
We want and have plans to implement `Out-GridView` on another platform.

**Comment by MathiasMagnus** [comment] 2017-12-31 10:02
When did Test-Connection disappear and why? It was in RC1 I believe...

**Comment by iSazonov** [comment] 2017-12-31 13:49
`Test-Connection` was not ported (old Windows only code). Currently we have new ported version in #5328 but not jet merged.

**Comment by iSazonov** [comment] 2019-09-29 07:37
I updated current status in https://github.com/PowerShell/PowerShell/issues/2123#issuecomment-341996659
I believe we can close the issue.

**Closed by iSazonov** 2019-09-29 07:37 UTC
Labels: Area-Cmdlets, Issue-Enhancement, Up-for-Grabs
