### ISSUE TITLE
Some FileSystem and Navigation commandlets fail on paths with 8.3 components

### ISSUE THREAD

**Issue by arsing** [PowerShell/PowerShell#7760] opened 2018-09-11 17:55 UTC
Steps to reproduce
------------------

```powershell
New-Item -Type Directory .\a.bcde
New-Item -Type File .\a.bcde\f.txt
Get-ChildItem '.\A5055~1.BCD\f.txt' # succeeds
Get-Content '.\A5055~1.BCD\f.txt' # succeeds
Remove-Item '.\A5055~1.BCD\f.txt' # fails
Set-Location '.\A5055~1.BCD' # fails
```

Expected behavior
-----------------

`Remove-Item` and `Set-Location` work just like `Get-ChildItem` and `Get-Content` do.

Actual behavior
---------------

```none
Remove-Item : An object at the specified path C:\Users\arsing\Desktop\A5055~1.BCD does not exist.
At line:1 char:1
+ Remove-Item '.\A5055~1.BCD\f.txt' # fails
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand


Set-Location : An object at the specified path C:\Users\arsing\Desktop\A5055~1.BCD does not exist.
At line:1 char:1
+ Set-Location '.\A5055~1.BCD' # fails
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.SetLocationCommand
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---

This came up with one of our scripts that creates a file under `$env:TEMP` via `Invoke-WebRequest -OutFile` and subsequently tries to delete it via `Remove-File`. The user in question had a `.` in their Windows username, and apparently Windows sets such a user's `TEMP` env var to use a 8.3 name. So the script failed at the `Remove-Item`.

Eg if you create a new user named `a.bcde`, and `runas /u:a.bcde pwsh`, `$env:TEMP` will be `C:\Users\A5055~1.BCD\AppData\Local\Temp` and `cd "$env:TEMP"` will fail in the same way. I imagine a lot of PS scripts are broken for these users. (This issue also exists on PS 5.)

This happens at least on Windows 7 and Server 2012R2. Don't know about Windows 10 / Server 2016, but I assume it's for compat with some ancient programs so it might be there too.

---

One workaround is to round-trip every path that might have an 8.3 name through `[FileInfo]::FullName` which converts it back to the proper name.

```powershell
PS> $filename = ([System.IO.FileInfo]"$PWD\A5055~1.BCD\f.txt").FullName

PS> $filename

C:\Users\arsing\Desktop\a.bcde\f.txt

PS> Remove-Item $filename # succeeds
```

**Comment by bormm** [comment] 2021-01-25 17:53
This is a duplicate of this one #2369 it never got any interest from microsoft, even you find [530.000 pages](https://www.google.com/search?q=%22An+object+at+the+specified+path%22) with this error message and most seems to be related with this issue.

**Closed** 2021-01-25 18:41 UTC
Labels: Issue-Bug, WG-Engine-Providers
