### ISSUE TITLE
Distribution Support Request "PowerShell v7.1.2 Microsoft Store Version"

### ISSUE THREAD

**Issue by fuchanghao** [PowerShell/PowerShell#14800] opened 2021-02-14 13:40 UTC
## Details of the Distribution

- Name of the Distribution: PowerShell (https://www.microsoft.com/en-us/p/powershell/9mz1snwt0n5d)
- Version of the Distribution: Microsoft Store Version v7.1.1
- Package Types:  msixbundle / emsixbundle ?

## Progress

- I didn't receive an update of Powershell v7.1.2 of Store Version.

**Comment by jborean93** [comment] 2021-02-14 18:44
Looking at Twitter it looks like it requires authorisation from someone who doesn't have their computer to do so right now. Will probably have to wait https://twitter.com/Steve_MSFT/status/1360277465701052417?s=20.

**Comment by kilasuit** [comment] 2021-02-14 19:19
Please close this as this is already known & was already raised in #14772 - see this comment for more info https://github.com/PowerShell/PowerShell/issues/14772#issuecomment-778676249

**Comment by daxian-dbw** [comment] 2021-02-18 22:46
Close as a duplicate of #14772

**Closed by daxian-dbw** 2021-02-18 22:46 UTC
Labels: Distribution-Request, Needs-Triage
