### ISSUE TITLE
Array of hashtables to PSCustomObject conversion

### ISSUE THREAD

**Issue by aguzev** [PowerShell/PowerShell#19004] opened 2023-01-22 15:43 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Try converting an array of hashtables to string. Note each hashtable is consistently handled as a whole.

```PowerShell
PS> ( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} ) | % {[string]$_}
System.Collections.Hashtable
System.Collections.Hashtable
System.Collections.Hashtable

PS> [string]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )
System.Collections.Hashtable System.Collections.Hashtable System.Collections.Hashtable

PS> [string[]]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )
System.Collections.Hashtable
System.Collections.Hashtable
System.Collections.Hashtable
```

2. Try the same conversion to PSCustomObject. Note the difference to string conversion. For PSCustomObject the array of hashtables looks flattened to a sequence of key-value pairs.

```PowerShell
PS> ( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} ) | % {[PSCustomObject]$_}

 b  a
 -  -
42 13
 6  1
 9  0

PS> [PSCustomObject]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )

Name                           Value
----                           -----
b                              42
a                              13
b                              6
a                              1
b                              9
a                              0

PS> [PSCustomObject[]]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )

Name                           Value
----                           -----
b                              42
a                              13
b                              6
a                              1
b                              9
a                              0
```

### Expected behavior

```console
PS> ( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} ) | % {[PSCustomObject]$_}

 b  a
 -  -
42 13
 6  1
 9  0

PS> [PSCustomObject]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )

 b  a
 -  -
42 13
 6  1
 9  0

PS> [PSCustomObject[]]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )

 b  a
 -  -
42 13
 6  1
 9  0
```

### Actual behavior

```console
PS> ( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} ) | % {[PSCustomObject]$_}

 b  a
 -  -
42 13
 6  1
 9  0

PS> [PSCustomObject]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )

Name                           Value
----                           -----
b                              42
a                              13
b                              6
a                              1
b                              9
a                              0

PS> [PSCustomObject[]]( @{a=13;b=42}, @{a=1;b=6}, @{a=0;b=9} )

Name                           Value
----                           -----
b                              42
a                              13
b                              6
a                              1
b                              9
a                              0
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2023-01-23 00:27
Good point, but this is a duplicate of:
* #13838

**Closed** 2023-01-23 10:08 UTC
Labels: Needs-Triage
