### ISSUE TITLE
precedence of -and and -or is the same

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#8512] opened 2018-12-21 16:23 UTC
It's just surprising to me that Powershell doesn't give a greater precedence to -and over -or, like in other languages like C# or vbscript.  I guess there's some technical reason for it.

# Steps to reproduce

```powershell

```

# Expected behavior

```none
C:\> $true -or $true -and $false
True
```

# Actual behavior

```none
C:\> $true -or $true -and $false
False

C:\> $true -or ($true -and $false)
True
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment] 2018-12-21 17:51
Don't know the history behind this but it would certainly be a breaking change to change it

**Comment by mklement0** [comment] 2018-12-22 23:52
I agree that the behavior is surprising.

It is documented in [`about_Operator_Precedence`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operator_precedence), though without a design rationale.

As @SteveL-MSFT notes, changing it now would be a breaking change.

**Comment by E3V3A** [comment] 2018-12-23 00:46
:face_with_head_bandage: :face This is crazy! Not that this comment it will change anything, but certainly explains why I've had such random outcomes when trying to set/extract and pass various booleans/parameters. Since, I'm mostly using the Internal Preview Fast track, I have often blamed various boolean incoherent behavior on buggy builds and such. Now I know why! It would be interesting what crazy story is behind, not following the standard of most (java, js, ruby, python, c, c++ etc) languages since the invention of computers.

Perhaps it would be a welcome *break* one day. (*Legacy* is our enemy.)

**Comment by SteveL-MSFT** [comment] 2018-12-23 00:49
Perhaps add this to https://github.com/PowerShell/PowerShell/issues/6745

**Comment by vexx32** [comment] 2019-06-02 22:32
@SteveL-MSFT any chance of considering this for PS7, or is it still too soon? 😄

**Comment by dkaszews** [comment] 2022-07-28 11:09
Adding myself to the list of people badly bitten by it... Was porting simple cmdlet from C# to PowerShell, was not expecting such a breaking issue! Especially since both are so interoperable.

**Comment by dkaszews** [comment] 2022-07-28 12:31
What about making `Set-StrictMode -Version 4.0` error when `-or` is on the same level and to the left of `-and`? You could just put parentheses and make it work **without a breaking change**, but it would not report errors if putting parentheses does not change result:

```pwsh 
1 -or 1 -and 0    # Expected 1, actual 0, Strict error
(1 -or 1) -and 0  # Expected 0, actual 0, no Strict error
1 -or (1 -and 0)  # Expected 1, actual 1, no Strict error

# If `-and` is to left, it doesn't matter if its higher precedence or same ltr
1 -and 0 -or 1    # Expected 1, actual 1, no error
(1 -and 0) -or 1  # Expected 1, actual 1, no error
```

**Comment by doctordns** [comment] 2022-07-28 13:50
To change the default precedence order would be a major breaking change.  I would be reluctant ti see this change in PowerShell 7.x.

If this is worth changing, then perhaps in the PowerShell 8 timescales??

As an aside, I have been surprised by the order. like many on this issue - for me the solution is use parenthies so as to be explicit:
```powershell
# as opposed to this
$true -or $true -and $false
# I would use:
$true -or ($true -and $false)
```
This makes explicit what I am testing for and NOT relying on defaults. I started programming in Fortran IV in 1968, and afterprobably over 100 languages later - my expectations are not always realised ihn the next language. I learned to be more explicit, and workmanlike and spelling things out. I would hope the code that results has been easier for others to maintain. :-)

**Comment by SeeminglyScience** [comment] 2022-08-01 20:30
Marking as by design. This can't really be changed today as it would be a large breaking change. A separate mode for breaking changes is already tracked in the linked issue above.

**Closed** 2022-08-02 21:01 UTC
Labels: WG-Language, Resolution-By Design, Issue-Discussion
