### ISSUE TITLE
pwsh not working properly when run from a Linux pty

### ISSUE THREAD

**Issue by jclariviere** [PowerShell/PowerShell#14932] opened 2021-03-02 23:22 UTC
## Steps to reproduce

The easiest way to reproduce is by using `unbuffer`

```sh
$ unbuffer pwsh
```

It can also be reproduced by using python's `pty` module.

```python
import pty, os, select
​
​
def waitfor(fd, str):
    poll = select.poll()
    poll.register(fd, select.POLLIN)
    while True:
        evt = poll.poll()
        r = os.read(fd, 1024)
        print(r.decode())
        if str in r:
            return
​
​
pid, fd = pty.fork()
​
# executed in child
if pid == 0:
    os.execvp("pwsh", ["pwsh"])
​
# executed in parent
elif pid > 0:
    waitfor(fd, b"> ")
```

Or by using [pexpect](https://pexpect.readthedocs.io/en/stable/) (which is actually where I first found the issue):

```python
p = pexpect.spawn("pwsh", encoding='utf-8', timeout=60)
p.logfile_read = sys.stdout
p.expect("PS .+> ")
p.sendline("echo test")
p.expect("PS .+> ")
```

## Expected behavior

```sh
$ pwsh
PowerShell 7.1.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/vagrant>
```

## Actual behavior

It's a little hard to put here because the the screen gets overwritten at some point, but here's an example.

First it starts printing out some escape characters:

```sh
$ unbuffer pwsh
PowerShell 7.1.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

^[[8;1R^[[8;8RPS /home/vagrant> ^[[8;33R^[[8;41R
```

Then the top starts getting overwritten:

```sh
�@@� *�@@p_*�@@���U@@x�<�@@x�<�@@` *�@@y�K�@@@@@��@@@9����,8T@@@@���U@@@@@@@@@@h *�@@@@@@@@@@@8,J�mu�h *�@��U@@-��U@��U@@�-��@@�_*�@@��K�@@��
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

^[[8;1R^[[8;8RPS /home/vagrant> ^[[8;33R^[[8;41R
```

## Environment data

```powershell
PS /home/vagrant> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Linux 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment] 2021-03-03 07:55
What is `unbuffer`?

```
> Get-Command unbuffer
Get-Command: The term 'unbuffer' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

 > uname -a
Linux mymsi 5.10.15-172.current #1 SMP PREEMPT Fri Feb 12 16:35:57 UTC 2021 x86_64 GNU/Linux

 > lsb_release -a
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	4.2
Codename:	fortitude

 > (Get-Host).Version.ToString()
7.1.2
```

**Comment by jclariviere** [comment] 2021-03-03 15:18
It is a program that uses `expect` to remove the buffering from a program. It comes from the `expect` package. http://manpages.ubuntu.com/manpages/hirsute/en/man1/expect_unbuffer.1.html

I'm not 100% certain but I think `expect` spawns a TTY in order to do its magic. The same problematic behavior can be replicated by using `expect` at least.

Create this script:

```sh
spawn pwsh
expect '>'
```

Then run it: `expect test.sh`.

**Comment by SteveL-MSFT** [comment] 2021-03-04 01:06
This looks like a dupe of https://github.com/PowerShell/PowerShell/issues/11215?

**Comment by jclariviere** [comment] 2021-03-08 16:32
I think it's similar but in #11215 , the issue seems to happen when you start a subprocess from a powershell console. Here, the issue happens when you start a powershell console as a subprocess from another shell.

I have made two other observations that I think will help pinpointing the problem:

- I get similar issues if I connect to a Windows SSH server (connect to a Windows SSH server with python's pexpect for example). The remote shell type I get seems to be cmd.exe and not powershell, so it may not be a powershell-specific issue.
- I don't get the issue if the powershell subprocess is not in a TTY. So it works with python's `subprocess` module for example, but not with `pexpect`. So it seems to be an issue specific to TTYs.

**Comment by DHowett** [comment] 2021-03-11 04:30
The output here looks very similar to that caused by https://github.com/PowerShell/PSReadLine/issues/1376. Perhaps similar?

**Comment by jclariviere** [comment] 2021-03-11 16:59
It does seem very similar! TTYs likely don't control a cursor so it could be the same problem. That PSReadLine issue also points to it being a .NET problem and not powershell directly, which would confirm my earlier finding with a Windows SSH server.

**Closed** 2023-11-23 11:20 UTC
Labels: WG-Interactive-Console, Needs-Triage, Resolution-No Activity
