### ISSUE TITLE
Console output cleared with CTRL+L pops back into view when you start to type into the console.

### ISSUE THREAD

**Issue by reygoch** [PowerShell/PowerShell#8870] opened 2019-02-12 10:46 UTC
This problem appeared after the latest windows update was performed on my computer. Problem also appeared on PowerShell 5.1. Here is a tiny GIF which visualizes the problem.

![powershell-problem](https://user-images.githubusercontent.com/8524934/52630029-5d43d780-2ebb-11e9-9b19-15dbcb8983e9.gif)

# Steps to reproduce

```powershell
# Try typing some basic command e.g.
> git log

# Then try clearing the console screen with CTRL+L
> [CTRL+L]

# Now console clears (or rather moves the previous output outside our field of view),
# but if we start typing again everything that was cleared gets scrolled back down
# into view (incredibly annoying).
> some other command
```

# Expected behavior

Console stays cleared.

# Actual behavior

If I start typing new command after clearing the console, old console output pops back into the view.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by DHowett-MSFT** [comment] 2019-02-15 20:30
This is a duplicate of Microsoft/console#302, for which there should be a fix in the current Insiders' Fast releases.

**Comment by iSazonov** [comment] 2019-10-13 17:04
I can not repo with latest 7.0-Preview4 build.

**Closed by iSazonov** 2019-10-13 17:04 UTC
Labels: Issue-Question
