### ISSUE TITLE
Quirk behavior auto conversion string to integer (based on Get-UICulture instead of Get-Culture)

### ISSUE THREAD

**Issue by B-Art** [PowerShell/PowerShell#23826] opened 2024-05-21 09:01 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PS > `Get-UICulture`

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)

PS > `Get-Culture`

LCID             Name             DisplayName
----             ----             -----------
1043             nl-NL            Dutch (Netherlands)

PS > `1 - 10.000.000`
1
PS > `1 - 10000000`
-9999999
PS > `1 - 10.000`
-9
PS > `1 - 10,000`
InvalidOperation: Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.
PS > `1 - "10,000"`
-9999
PS > `1 - "10.000"`
-9
PS > `1 - "10.000,0"`
InvalidArgument: Cannot convert value "10.000,0" to type "System.Int32". Error: "The input string '10.000,0' was not in a correct format."
PS > `1 - "10,0"`
-99
PS >

### Expected behavior

```console
PS > Get-UICulture

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)

PS > Get-Culture

LCID             Name             DisplayName
----             ----             -----------
1043             nl-NL            Dutch (Netherlands)

PS > 1 - 10.000.000
-9999999
PS > 1 - 10000000
-9999999
PS > 1 - 10.000
-9999
PS > 1 - 10,000
-9
PS > 1 - "10,000"
-9
PS > 1 - "10.000"
-9999
PS > 1 - "10.000,0"
-9999
PS > 1 - "10,0"
-9
PS >
```

### Actual behavior

```console
PS > Get-UICulture

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)

PS > Get-Culture

LCID             Name             DisplayName
----             ----             -----------
1043             nl-NL            Dutch (Netherlands)

PS > 1 - 10.000.000
1
PS > 1 - 10000000
-9999999
PS > 1 - 10.000
-9
PS > 1 - 10,000
InvalidOperation: Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.
PS > 1 - "10,000"
-9999
PS > 1 - "10.000"
-9
PS > 1 - "10.000,0"
InvalidArgument: Cannot convert value "10.000,0" to type "System.Int32". Error: "The input string '10.000,0' was not in a correct format."
PS > 1 - "10,0"
-99
PS >
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

This is not something visual.

**Comment by rhubarb-geek-nz** [comment] 2024-05-21 16:32
Hi, it may look like quirks and I don't think it has anything to do with UICulture

#### First rule

PowerShell scripts are written in English. They use English words and the numbers are represented in English (effectively en-US)

#### Second rule

Cast operators also work in the PowerShell language, which is effectively en-US. On Unix it is sometimes referred to as LANG=C

#### Third rule

Parsing and presentation functions and methods normally use the current culture, so that includes Parse and outputting to the console

#### Fourth rule 

`ToString()` can do anything it wants, there is no law, it just does what ever is appropriate for the type.

#### Example

```
[CultureInfo]::CurrentCulture = New-Object -TypeName CultureInfo -ArgumentList 'nl-NL'

3.14159

[double]'3.14159'

[double]::Parse('3.14159')

[string]3.14159

(3.14159).ToString()
```

You get

```
3,14159
3,14159
314159
3.14159
3,14159
```

So casting a double to a string did it in English, using ToString() did it in the current locale. I hope that agrees with your findings.

**Comment by mklement0** [comment] 2024-05-21 21:53
To add to @rhubarb-geek-nz's comment:

* In number literals, implicit type conversions, string interpolation, and casts, PowerShell by design uses the [_invariant culture_](https://learn.microsoft.com/en-US/dotnet/api/System.Globalization.CultureInfo.InvariantCulture), which is based on, but distinct from, the US-English culture.

  * Specifically, behind the scenes, if a given type's `.ToString()` and `::Parse()` methods support passing an optional `System.IFormatProvider` instance to request culture-specific formatting, PowerShell passes `[cultureinfo]::InvariantCulture`

* By contrast, in _for-display_ output, the _current_ culture's formatting is used.

**Comment by B-Art** [comment] 2024-06-19 21:31
So if I want to reach my goal, I should rely on ::Parse and ToString().
I only wished that the standard separator was not a comma..
If the standard was ; dot-comma than it would have been easier for everyone.
Unix (and Algol68) used a different approach.
The first CHAR used would become the separator.
But that is only feasible if you use a compiler.

For the record:
`[double]::Parse('3,14159')`
Gives:
`3,14159`
And:
`[double]'3,14159'`
Gives:
314159
`[double]'3.14159'`
Gives:
`3,14159`

**Comment by mklement0** [comment] 2024-06-19 22:13
> I only wished that the standard separator was not a comma..

`,` isn't the standard separator, it is the [comma (array constructor) operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#comma-operator-).

By contrast, `;` is the _statement separator_.

Thus, while `1,2` and `1;2` and produce the same _display_ output, they're technically distinct: the former is an _array_, the latter comprises two separate statements.

At least in an English-language context, it is `,` that is customarily used as the _list separator_, and that's in effect how the `,` operator works.

It boils down to this:

* PowerShell-specific behaviors:

  * In number _literals_ in _source code_, it is only ever `.` that functions as the decimal mark (and a thousands-grouping mark such as `,` is _not_ supported).

  * In PowerShell's string interpolation, the same rules apply, culture-independently.

  * Ditto in PowerShell from-string casts, except that `,` is interpreted as the thousands-grouping mark and effectively _ignored_.

    * Regrettably, in the casts (type conversions) that may situationally be applied _implicitly_ in the context of _parameter binding_ to a _binary cmdlet_ (as opposed to an implemented-in-PowerShell `function` or script file), the _current culture_ is applied. This is an unfortunate inconsistency that won't be fixed, however, for the sake of backward compatibility: see https://github.com/PowerShell/PowerShell/issues/3348#issuecomment-337799446

  * By contrast, in _for-display rendering_ of numbers, the rules of the _current culture_ apply (but the default formatting doesn't use the thousands-grouping mark).

* .NET API behaviors:
  * `::Parse()` and `.ToString()` honor the _current culture_ by default - unless a different culture is explicitly specified (including the _invariant_ one).

**Comment by B-Art** [comment] 2024-06-22 20:56
.... 
[PowerShell use different logic, when converting passed value to parameter type, for compiled and script cmdlets #3348 (comment)](https://github.com/PowerShell/PowerShell/issues/3348#issuecomment-337799446)
.....
You refer to a problem with dates, that is a different topic.

With dates I go for big to small just like the international algebraic way that numbers are written.
(it is reversed because number came originally from Arabic language which is written from right to left.)

In dates always year/month/day/hour/minutes/seconds etc... it makes more sense than mixing things up like in the US and others.
(day/month/year and month/day/year are both illogical)

About separators
In MSDOS you could use any character as delimiter (it the first character used in a compare)
In batch (you can use any character for H here als long as it is not part of string that is tested):
```
Set Test=als
If HalsH==H%Test%H echo works
```
`works`

**Closed** 2024-06-22 20:57 UTC
Labels: Needs-Triage

**Comment by mklement0** [comment] 2024-06-22 21:07
> You refer to a problem with dates, that is a different topic.

#3348 isn't just about _dates_, specifically, but about a _fundamental_ difference in culture-sensitivity between parameter-binding in _binary_ cmdlets vs. their written-in-PowerShell analogs, _advanced functions_ as well as in _casts_.

> In MSDOS you could use any character as delimiter

Your `If HalsH==H%Test%H echo works` example doesn't use any characters that `cmd.exe` recognizes as _delimiters_ - it purely relies on the macro-like up-front string expansion that `cmd.exe` employs.

**Comment by B-Art** [comment] 2024-07-03 07:54
Reading #3348 I realized that Dates will be a pain in the ass for the rest of our lives. ;-)

That said,
I want to suggest an extra parameter that makes live easier.
First make the person delivering a date responsible for the interpretation.
How?
When giving a date also give a format hint.
(first column original input) (second column for insight) (Third YMD in yyyy-MM-dd) 
For instance:
11-1-12 YMD => 2011-01-12 => 2011-01-12
11-1-12 MDY => 11-01-2012 => 2012-11-01
11-1-12 DMY => 11-01-2012 => 2012-01-11

Unknown use but for consistency:
11-1-12 YDM => 2011-01-12 => 2011-12-01
11-1-12 MYD => 11-2001-12 => 2001-01-12
11-1-12 DYM => 11-2001-12 => 2001-12-01

**Comment by rhubarb-geek-nz** [comment] 2024-07-03 16:57
> I want to suggest an extra parameter that makes live easier.

I contend that the last thing in the world that we need is yet another date/time standard.

We have the existing ISO 8601, RFC 2822 and RFC 3339, current locales, time-zone databases etc. The problem of dates becomes far simpler if...

1. When programming, use a date/time type to represent the date/time. That way throughout the code you know it is a date/time.

2. When exchanging data with other computers or processes use the ISO or RFC standards to unambiguously specify the point in time. This includes across a network, in XML, JSON, CSV, whatever.

3. When using a database, use the database provided date/time/timestamp types.
 
4. When you accept input from the end user or display information to the end user use the user's current specified locale, time-zone, date/time preferences etc.

5. When programming a UI use existing input methods/widgets and display elements and avoid inventing the wheel again.

6. It is far simpler to do all of this correctly rather than trying to come up with work arounds for ambiguous data.

7. Existing languages, tools and systems already support all of this.

None of that is new, rocket science or surprising.
