### ISSUE TITLE
Unable to use PowerShell Transcription with Active Directory Administrative Console (ADAC)

### ISSUE THREAD

**Issue by Mirend** [PowerShell/PowerShell#3021] opened 2017-01-19 23:43 UTC
Steps to reproduce
------------------
Setup group policy to enable PowerShell Transcripting. From a machine that has that policy applied, launch ADAC. The error "Cannot connect to any domain. Refresh or try again when connection is available." pops up and ADAC can't be used. 

Expected behavior
-----------------
There should be no error so ADAC can continue to be used with transcripting enabled.

Actual behavior
---------------
ADAC cannot function unless the policy is disabled.

Environment data
----------------
Windows Server 2012 R2 or Windows Server 2016

Name                           Value                                                  
----                           -----                                                  
PSVersion                      5.1.14393.0                                            
PSEdition                      Desktop                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                
BuildVersion                   10.0.14393.0                                           
CLRVersion                     4.0.30319.42000                                        
WSManStackVersion              3.0                                                    
PSRemotingProtocolVersion      2.3                                                    
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment] 2017-01-20 05:43
If the Issue is ADUC specific it is better report on [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

**Comment by milesgratz** [comment] 2018-02-26 19:20
Hi - experiencing same issue 😢. Submitted to UserVoice.

**Comment by iSazonov** [comment] 2018-02-27 04:59
@milesgratz Please add the UserVoice link.

**Comment by milesgratz** [comment] 2018-04-07 12:30
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/33881269-unable-to-use-powershell-transcription-with-active

**Comment by MaximoTrinidad** [comment] 2018-04-07 14:25
Just wondering if this incident going to be close as is not a PowerShell Core issue?
:)

**Comment by markekraus** [comment] 2018-04-07 14:57
Closing issue. in lieu of open  UserVoice.

**Closed by markekraus** 2018-04-07 14:57 UTC
Labels: Resolution-External
