### ISSUE TITLE
Core dumped with beta 2 on Ubuntu 17.04

### ISSUE THREAD

**Issue by borgdylan** [PowerShell/PowerShell#3929] opened 2017-06-03 09:26 UTC
Steps to reproduce
------------------
Execute the ```powershell``` command in bash

Expected behavior
-----------------
PowerShell starts successfully.

Actual behavior
---------------
```powershell: pal_io.cpp:758: int64_t SystemNative_SysConf(SysConfName): Assertion `false && "Unknown SysConfName"' failed.```

Environment data
----------------

Linux ubuntu-server 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```powershell
> $PSVersionTable

```

**Comment by vors** [comment] 2017-06-03 17:52
What's the Linux distro you use and how did you install the package?

**Comment by borgdylan** [comment] 2017-06-03 19:30
Ubuntu. Got the update via APT.

**Comment by MaximoTrinidad** [comment] 2017-06-03 20:31
Just installed PowerShell Core Beta 2 on Ubuntu OS ver. 16.04.2 LTS and on Windows 10 Bash (Gui) via apt update/upgrade. Its working fine!

maxt@orion:~$ powershell
PowerShell 
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/maxt> cat /etc/issue                                                                                           
Ubuntu 16.04.2 LTS \n \l

PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-beta                                                                              
PSEdition                      Core                                                                                    
BuildVersion                   3.0.0.0                                                                                 
CLRVersion                                                                                                             
GitCommitId                    v6.0.0-beta.2                                                                           
OS                             Linux 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017                      
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0

**Comment by borgdylan** [comment] 2017-06-04 07:14
You are using translated syscalls on Windows. I am using the actual Ubuntu 17.04 running on Linux 4.10 x64.

**Comment by iSazonov** [comment] 2017-06-04 07:28
@borgdylan Please add the Environment data in the Issue description.

**Comment by borgdylan** [comment] 2017-06-04 08:14
I cannot do that as powerhsell will not start

**Comment by iSazonov** [comment] 2017-06-04 08:32
I meant the exact OS version.

**Comment by MaximoTrinidad** [comment] 2017-06-04 13:05
FYI 
I'm still having issues with Ubuntu 17.04: https://github.com/PowerShell/PowerShell/issues/3721

**Comment by borgdylan** [comment] 2017-06-04 13:05
Linux ubuntu-server 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joeyaiello** [comment] 2017-06-05 17:45
This is a dupe of #3721, 17.04 seems to be broken right now.

**Closed by joeyaiello** 2017-06-05 17:45 UTC
Labels: Issue-Discussion, OS-Linux, Resolution-Duplicate
