### ISSUE TITLE
start-process adds an extra space to command line '-args' (\x20) at the end

### ISSUE THREAD

**Issue by chr0meice2** [PowerShell/PowerShell#13097] opened 2020-07-04 18:33 UTC
Current behavior is extra invalid space is added to command line args in start-process

C++ code below demonstrates how \x20 is added to end of start-process -filepath C:\blah.exe -args Demo

Demo command line will have space added...  Joel and romero126 and jborean93 in the #powershell IRC chat on freenode have observed the issue.

The expected behavior is that the command line should be exactly what the person typed, no extra space at the end.  Extra spaces will break software where need exact params as cmd args (my tool stopped working randomly and I didn't know why-- spaces are an invalid input in the software I made)

powershell version:

PS C:\WINDOWS\system32> get-host |select-object version

Version
-------
5.1.19041.1

#include <winsock2.h>
#include <windows.h>
#include <winternl.h>
#include <ntstatus.h>
#include <tlhelp32.h>
#include <msi.h>
#include <sddl.h>
#include <wintrust.h>
#include <Softpub.h>
#include <shlobj.h>
#include <locale>
#include <algorithm>
#include <random>
#include <atomic>
#include <codecvt>
#include <wincrypt.h>
#include <vector>
#include <string>
#include <sstream>
#include <unistd.h>
 
using namespace std;
class ustring : public std::basic_string<unsigned char> {
public:
    using std::basic_string<unsigned char>::basic_string;  // import constructors
 
    ustring(const std::string &str) : basic_string(str.begin(), str.end()) {}
    ustring(const char *str) : ustring(std::string(str)) {}
   
    ustring &operator+=(const ustring &str) { append(str.begin(), str.end()); return *this; }
   
    operator std::string() const { return std::string(begin(), end()); }
};
 
ustring operator+(const ustring &left, const ustring &right) { ustring ret(left); return ret += right; }
 
 
static ustring str2numbers(const std::vector<unsigned char> &bin);
 
//  start-process -filepath C:\path\this.exe  -ArgumentList @('test')
// powershell will add an extra space (\x20) to the args for no reason
 
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{
 
 
 
    UNREFERENCED_PARAMETER(hInstance);
    UNREFERENCED_PARAMETER(nCmdShow);
    UNREFERENCED_PARAMETER(hPrevInstance);
    myHin=hPrevInstance;
   
    std::string mycmd =lpCmdLine;
 
    std::vector<unsigned char> vv (mycmd.size() +1 );
    vv.assign(mycmd.begin(), mycmd.end() );
 
    ustring hexx=str2numbers(vv);
 
    MessageBox(0,mycmd.c_str(),"asdf",0);
 
    MessageBox(0,reinterpret_cast<const char*>(hexx.c_str()),"asdf",0); /// Why is there a trailing space added in hex by powershell??
 
return 0;
 
}
 
 
static ustring str2numbers(const std::vector<unsigned char> &bin)
{
   
 
    std::ostringstream oss;
    oss << std::setfill('0');
    unsigned vsize=bin.size();
    for(unsigned g=0;g<vsize;++g)
    {
        oss << std::hex << std::setw(2) << static_cast<int>(bin[g]);
    }
   
    return oss.str();
 
   
}

**Comment by jborean93** [comment] 2020-07-04 21:50
Duplicate of https://github.com/PowerShell/PowerShell/issues/13094.

**Closed** 2020-07-05 23:00 UTC
Labels: Issue-Question, Resolution-Duplicate
