### ISSUE TITLE
Coercion with System.Drawing not working in PS7

### ISSUE THREAD

**Issue by jvierrajrv** [PowerShell/PowerShell#9815] opened 2019-06-04 14:09 UTC
PowerShell 5.1 and earlier

<b>[system.drawing.Pont]'10,20'</b>

PowerShell 7 - fails to perform the coercion and all point assignments in WinForms controls (location,size, etc) fail to coerce the assignment.

**Comment by vexx32** [comment] 2019-06-04 14:24
I'd say this is a likely to be an issue originating from the .NET Core side of things, given PowerShell was never really designed as a GUI tool first; it mostly likely only borrowed the existing defined casting operations provided in the .NET Framework which may be missing in Core.

**Comment by jvierrajrv** [comment] 2019-06-04 14:42
> I'd say this is a likely to be an issue originating from the .NET Core side of things, given PowerShell was never really designed as a GUI tool first; it mostly likely only borrowed the existing defined casting operations provided in the .NET Framework which may be missing in Core.

No.  PS has always used "coercion".  It is not a cast.  This is not something that happens in the Net assemblies.  How PS decides that the string is "coercible" is not documented but it has always worked even beyond WinForms.  System,Drawing is not really part of WinForms but is fundamental to using WinForms.  System.Drawing is the graphical class assembly used to manipulate images as well as other drawing primitives.

PowerShell has always been able to use WinForms assemblies.  The assemblies are also available in PS 7.

System.Windows.Forms.dll and System.Drawing.DLL are delivered with PowerShell 7 and are in the preview folder.  WinForms and the WinForms designer are part of PowerShell 7.

**Comment by vexx32** [comment] 2019-06-04 14:52
Yes, PS has its own conversion logic. But it has never had specialized logic for System.Drawing assemblies as far as I've ever seen.

It has a generic conversion routine when others fail, which can include (from memory) checking for Parse() methods that take the right argument type(s), looking for explicit or implicit operators, etc., etc.

Winforms isn't part of PowerShell. It's part of .NET Core 3, which is a dependency of PowerShell. PowerShell _might_ be able to manually fix this, but it would likely be better able to be fixed by [the folks who actually maintain the WinForms code](https://github.com/dotnet/corefx), is all. 🙂

**Comment by jvierrajrv** [comment] 2019-06-04 14:57
You miss the point.  WinForms is part of PowerShell 7.  

The coercion has always been done in PowerShell.  There has never been a constructor for System.Drawing.Point that takes a string.

**Comment by SeeminglyScience** [comment] 2019-06-04 16:04
That conversion path utilizes the `System.ComponentModel.TypeConverterAttribute` that `System.Drawing.Point` declares in full framework.  That attribute isn't declared on the version included with the Core assembly `System.Drawing.Primitives`.

**Comment by jvierrajrv** [comment] 2019-06-04 16:18
Yes.  This needs to be addressed to maintain compatibility with Windows PowerShell.  That is the purpose of this post.  PS 7 is set to replace WMF 5.1 on Windows and backwards compatibility is required.

**Comment by vexx32** [comment] 2019-06-04 16:25
The place to address it, based on @SeeminglyScience's information, is in .NET Core where the type and its attributes are declared, then. 🙂 

Please file the issue in [the .NET Core repo]9https://github.com/dotnet/corefx) so they can address the regression.

**Closed** 2019-06-05 18:00 UTC
Labels: Issue-Question, Resolution-External

**Comment by jvierrajrv** [comment] 2019-06-05 18:17
Issue posted to Net Core.

I thank everyone for the guidance.

**Comment by karelz** [comment] 2019-06-07 00:50
@vexx32 just FYI: dotnet/core repo is general incoming repo for random issues (no code). The code itself lives in CoreFx repo.

**Comment by vexx32** [comment] 2019-06-07 01:08
Thanks, @karelz! So users wanting to file issues should primarily file against dotnet/core repo?

**Comment by karelz** [comment] 2019-06-08 18:23
@vexx32 no, sorry for not being clear. dotnet/core is option for people who have no idea where to file an issue.
For close partner technologies like PowerShell that build closely on top of CoreFx, I would hope the community and maintainers know where their underlying APIs live - in dotnet/CoreFx repo. And that they should encourage repro steps without PowerShell when filing there.

The key reasons are:
1. It eliminates the chance it is something specific to PowerShell. (Avoids specialties like custom binding, Framework targeting, etc.)
2. It is more actionable as few (if any) devs in CoreFx know what PowerShell does under the hood and we have 0 knowledge about anything more complex/tricky/specific.

Note: Same approach is used for other higher-level technologies and frameworks like ASP.NET, WPF, WinForms, WCF, 3rd party libraries, etc. If we get repro steps from those, we first ask higher-level frameworks to be eliminated. Only in worst hard-to-repro-and-track-down issues we jump into investigations that involve the higher-level frameworks (and only if those are impacting multiple customers).

Does it make sense?
Is there any way we can help to spread the word about this in PowerShell repo community?
Thanks!

**Comment by vexx32** [comment] 2019-06-08 19:32
That makes sense, thanks!

Some of that maybe should be mentioned in the contributing docs / issue templates or something here, I'm not sure myself. @SteveL-MSFT might have more concrete ideas there.

I think we may potentially run into a decent number of cases where folks aren't really familiar with how to tests things that they're seeing without PowerShell, so it might be on the rest of us in the repo here to put together simplified repro steps for testing and submission to dotnet/corefx as issues.

**Comment by jvierrajrv** [comment] 2019-06-08 19:44
The PS guys claim it is a missing Interop in Core/FX.  I kind of doubt that but they should know.  thte above reference to the missing type sounds like a good start so someone should knock on Core/Fx to address this deficiency.

**Comment by vexx32** [comment] 2019-06-08 19:55
@SeeminglyScience since you seem to know where the regression happened, could you open the appropriate issue in dotnet/CoreFX to get this resolved? 💖

**Comment by SeeminglyScience** [comment] 2019-06-08 22:45
Thanks @vexx32, I've opened issue dotnet/corefx#38374

**Comment by karelz** [comment] 2019-06-09 05:29
Thanks @SeeminglyScience for your help! Your CoreFX bug report is pretty clear and should hopefully make it into .NET Core 3.0 (fingers crossed). Thanks!

**Comment by jvierrajrv** [comment] 2019-10-22 13:53
This is not in 3.0 - any chance it is in 3.1?  PS 7 Preview 4 die snot have it,  Some 3.1 seems to be in PS7 but this issue isn't.
