### ISSUE TITLE
Files created by PowerShell have execute bit on owner set

### ISSUE THREAD

**Issue by nocentino** [PowerShell/PowerShell#3450] opened 2017-03-29 13:13 UTC
Steps to reproduce
------------------
```
PS /home/demo> Get-Process > output.gp                                                   
PS /home/demo> ps > output.ps    
```

Expected behavior
-----------------
Create file based on umask for system

Actual behavior
---------------
File created by PowerShell cmdlets have execute bit set on file owner
```
-rwxrw-r--. 1 demo demo 21K Mar 29 08:10 output.gp
-rw-rw-r--. 1 demo demo 248 Mar 29 08:10 output.ps
```

Environment data
----------------
```
Name                           Value                                                    
----                           -----                                                    
PSVersion                      6.0.0-alpha                                              
PSEdition                      Core                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                  
BuildVersion                   3.0.0.0                                                  
GitCommitId                    v6.0.0-alpha.17                                          
CLRVersion                                                                              
WSManStackVersion              3.0                                                      
PSRemotingProtocolVersion      2.3                                                      
SerializationVersion           1.1.0.1             
```                                     

```

**Comment by SteveL-MSFT** [comment] 2017-03-29 16:44
Dupe of https://github.com/PowerShell/PowerShell/issues/2481

**Closed** 2017-03-30 00:55 UTC
Labels: Resolution-Duplicate
