### ISSUE TITLE
ForEach-Object -Parallel fails when current location is a custom PSDrive

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PowerShell#11033] opened 2019-11-11 13:18 UTC
# Steps to reproduce

```powershell
New-PSDrive -Name git -PSProvider FileSystem -Root ~\Git
cd Git:
1..5 | ForEach-Object -Parallel { "Hello $_"; sleep 1; } -ThrottleLimit 5
```

# Expected behavior

```none
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
```

# Actual behavior

```none
ForEach-Object: An unexpected error has occurred while processing ForEach-Object -Parallel input. This may mean that some 
of the piped input did not get processed. Error: System.Management.Automation.DriveNotFoundException: Cannot find drive. A drive with the name 'Git' does not exist.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2019-11-11 13:41
/cc @PaulHigin 

Most likely an issue with scoping; perhaps we need to make sure to copy PSDrives to the new runspace?

**Comment by PaulHigin** [comment] 2019-11-11 16:10
For Windows platform this can be mitigated by creating the PSDirve as persistent, but I see this isn't supported on non-Windows platforms.  I hesitate to transfer all drives from calling session to parallel sessions by default since performance is already an issue with most users.  But maybe it could be opt-in via a switch.  The workaround is to create the drive manually in the parallel script block.

**Comment by vexx32** [comment] 2019-11-11 16:42
All drives might be a bad idea / not worth it, but I think it makes sense to check that the drive used for the "current directory" is available in the new session and create it if it's missing. 🙂

**Comment by PaulHigin** [comment] 2019-11-11 17:26
There are other things that a user might expect to be set up in the parallel running script, as was discussed in the RFC.  Currently the "by design" behavior is to run each parallel script in new runspace sessions with default initialization.  But I am wondering if we should have a `-UseExistingSessionState` parameter switch that initializes each parallel session from the current running sessions: imported modules, function definitions, PSDrives, type definitions.  Variables would be a problem because of threading issues, but maybe readonly variables can be transferred.  But the default behavior would be performant with standard session intialization.

**Comment by janegilring** [comment] 2019-12-04 07:29
Some additional information:
My need is not to bring the current location into the parallel sessions.
I have a custom PSDrive defined in my PowerShell profile, and the location is set to this drive.
When the current location is set to this drive, calling ForEach-Object -Parallel fails. My desire is to have it not fail when current location is set to the custom drive.
Of course I can change current location to a different drive such as C: manually, but shouldn't ForEach-Object -Parallel work regardless of what the current location is? Custom drive or a generic FileSystemProvider such as C:

**Comment by PaulHigin** [comment] 2019-12-04 16:37
ForEach-Object -Parallel now works with a PSDrive, but only if you make it persistent:

```powershell
New-PSDrive -Name Z -PSProvider FileSystem -Root \\scratch\temp -Persist
PS Z:\> dir -r *.txt | foreach -Parallel { $_.Name }
```
Otherwise we need something like `-UseExistingSessionState` that I mention above, to initialize each parallel session to be the same as the current session, and would include custom PSDrives.

**Comment by hippman257** [comment] 2020-01-16 20:23
I agree that something like "- UseExistingSessionState" parameter is going to be needed to work with ConfigurationManager via PowerShell.

The "-Persist" open is only valid for Filesystems.  I am trying to attempting to work with user objects in parallel in my CM environment and it fails.

PS C:\> New-PSDrive -Name $SiteCode -PSProvider CMSite -Root $ProviderMachineName -Persist

_New-PSDrive: When you use the Persist parameter, the root must be a file system location on a remote computer._

**Comment by janegilring** [comment] 2023-11-16 07:21
It does not repro in PowerShell 7.3.9

**Closed** 2024-05-23 22:12 UTC
Labels: WG-Engine, Issue-Discussion, Resolution-No Activity
