### ISSUE TITLE
Debug: Should be able to Step-Into "Invoke-Command -Computername" 

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2697] opened 2016-11-17 00:07 UTC
This should provide a simple way to debug the scriptblock on the remotemachine.

**Comment by joeyaiello** [comment] 2016-12-05 18:53
Also need to eventually support this even if `-AsJob` is specified.

**Comment by daviwil** [comment] 2017-01-26 22:41
Paul has submitted a PR for this: https://github.com/PowerShell/PowerShell/pull/3015

**Comment by daxian-dbw** [comment] 2017-03-01 18:04
I'm resolving this issue as a duplicate of #2827

**Closed by daxian-dbw** 2017-03-01 18:04 UTC
Labels: Area-Debugging, Issue-Enhancement, Resolution-Duplicate
