### ISSUE TITLE
Wrong cursor positioning and text rendering when typing in Japanese

### ISSUE THREAD

**Issue by Hsn723** [PowerShell/PowerShell#3560] opened 2017-04-14 06:13 UTC
Steps to reproduce
------------------
Type `echo 日本語` in PS.

Expected behavior
-----------------
The text should appear exactly as typed and the cursor should be at the end of the input.

Actual behavior
---------------
Part of the input is clipped off (only the left half of 本 is showing) and the cursor rests in the clipped-off area instead of to the right of the last character (語).

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.138
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.138
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by iSazonov** [comment] 2017-04-14 13:27
@NatsumiHoshino Thanks for your report!
Is the Issue only on 5.1.15063.138 or on previous versions too?

**Comment by joeyaiello** [comment] 2017-04-14 17:02
Repros on alpha.18 w/ CentOS (and confirmed to not repo in the same terminal emulator w/ bash):

```
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by NatsumiHoshino** [comment] 2017-04-15 13:58
I tried on an older machine with PSVersion 5.1.14393.1066 and could repro the issue.

**Comment by SteveL-MSFT** [comment] 2017-04-15 14:43
Repros w/o PSReadLine?

**Comment by chuanjiao10** [comment] 2017-04-16 08:07
paste gif is best.
 @joeyaiello  no this problem on my alpha.18 CentOS.
no this problem on my win10-14393,win10-15063.
This question is related to the font. Do not change the default font.

**Comment by joeyaiello** [comment] 2017-04-17 17:47
@SteveL-MSFT on Windows at least, no it looks like a PSReadline thing. 

I genuinely can't remember on Linux, and I'm booted into my Windows partition right now....could someone verify?

**Comment by iSazonov** [comment] 2017-10-08 15:45
Should we fix/close this before RTM?

**Comment by lzybkr** [comment] 2017-10-08 16:26
I think so. I think it's fixed by this [commit](https://github.com/lzybkr/PSReadLine/commit/8edcf64663d7b7de3d9ef23435473e6529954b1e) - but I have some more work to do before this branch is ready for more general use.

**Comment by lzybkr** [comment] 2017-10-08 16:33
Resolving as duplicate of lzybkr/PSReadLine#289

**Closed by lzybkr** 2017-10-08 16:33 UTC
Labels: Area-Console, Issue-Bug
