### ISSUE TITLE
New-Item Creates File Symbolic Link File When Linking To Folders and using Relative path to Target

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell#9537] opened 2019-05-05 03:57 UTC
# Steps to reproduce

Open PowerShell with an account with Administrative privileges, enter the "C:\Users\NAME" directory, and run the following code:

```powershell
New-Item -Type SymbolicLink -Path abc -Value Documents\
```

# Expected behavior

```none
    Directory: C:\Users\Admin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----l       2019-05-04  11:55 PM                abc
```

# Actual behavior

```none
    Directory: C:\Users\Admin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l        2019-05-04 11:55 PM              0 abc
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**NOTE**: This works in PowerShell 5

The following issue might be related to this one:
#2915

**Comment by bigboy-pdb-spam** [comment] 2019-05-05 03:59
#2915

**Comment by iSazonov** [comment] 2019-05-05 13:13
Our test for New-Item says that we create dirsymlink. I guess it is a side effect of performance optimizations we did in previous milestone.
/cc @powercode

**Comment by SteveL-MSFT** [comment] 2019-05-05 14:18
There's a proposal in https://github.com/PowerShell/PowerShell/issues/9067 how to we can address this specific issue, so marking this one as dupe

**Comment by iSazonov** [comment] 2019-05-05 16:51
@SteveL-MSFT Could you please clarify that you mean?
We create directory symlinks
https://github.com/PowerShell/PowerShell/blob/2737e74d864de909c7a359fad31e75e2cf0db34b/test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1#L234-L250

I think the issue is about how "Mode" is displayed.

**Comment by SteveL-MSFT** [comment] 2019-05-06 21:52
@iSazonov the problem seems to be that if you provide an absolute path to `-Target`, it works.  You get a symlink to a directory you can use as a directory.  If you use a relative path, then the symlink is no longer a directory but a file.  This is distinct from #9067 so reopening and updating title.

**Comment by aetos382** [comment] 2020-02-18 02:25
This problem is a duplicate of #9127 ?

**Closed** 2020-02-19 05:00 UTC
Labels: Area-Providers, Issue-Question, Resolution-Duplicate
