### ISSUE TITLE
CentOS 8 + tmux + powershell 7.0.2 missing characters at the beginning of every line

### ISSUE THREAD

**Issue by Bit-Chaos** [PowerShell/PowerShell#13142] opened 2020-07-09 06:54 UTC
Running powershell core 7.0.2 on CentOS 8 inside a ssh-session from inside Windows Terminal (again Powershell Core 7.0.2).
Steps to reproduce:
- start Windows Terminal (1.0.1811.0)
- open terminal (Powershell core 7.0.2)
- connect to CentOS 8 machine using ssh
- inside the bash-session (at the CentOS host) start tmux
- inside tmux start powershell core (pwsh)

Observed behaviour:
- first character on every line is missing
- cursor is jumping 2 places to the right, when entering the first character

Expected behaviour:
- well, like any other shell: display the first character and then do not jump 
![image](https://user-images.githubusercontent.com/46462208/87006569-2dd4ef80-c1c1-11ea-9bbf-8bba7b0d604e.png)

green line: expected
red: current behaviour

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Linux 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Environment:
DOTNET_ROOT=/usr/lib64/dotnet
PWD=/home/sku
TMUX=/tmp/tmux-1001/default,1782,0
TERM=screen
TMUX_PANE=%0
SELINUX_LEVEL_REQUESTED=
XDG_SESSION_ID=1
SHLVL=2
LESSOPEN=||/usr/bin/lesspipe.sh %s
LANG=en_US.UTF-8
DOTNET_CLI_TELEMETRY_OPTOUT=1
SHELL=/bin/bash
SELINUX_USE_CURRENT_RANGE=
HISTCONTROL=ignoredups
SSH_CLIENT=10.244.251.68 65438 22
SSH_TTY=/dev/pts/0
SSH_CONNECTION=10.244.251.68 65438 10.80.1.120 22
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/sku/.cache/dotnet_bundle_extract
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
COLUMNS=156
_=/usr/bin/pwsh
HOME=/home/sku
PATH=/opt/microsoft/powershell/7-lts:/home/sku/.local/bin:/home/sku/bin:/home/sku/.local/bin:/home/sku/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/sku/.dotnet/tools:/home/sku/.dotnet/tools
LOGNAME=sku
PSModulePath=/home/sku/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7-lts/Modules

**Comment by Bit-Chaos** [comment] 2020-07-09 06:56
One more comment:
This doesn't happen when just logging in and using pwsh directly (i.e. without tmux)

**Comment by daxian-dbw** [comment] 2020-07-09 17:24
> This doesn't happen when just logging in and using pwsh directly (i.e. without tmux)

@Bit-Chaos thanks for the issue report. Does it work fine when logging in and use pwsh with tmux (no ssh involved)?

**Comment by Bit-Chaos** [comment] 2020-07-09 21:06
@daxian-dbw I can't test logging in directly (without using ssh), since this is a remote server I'm working on.

**Comment by daxian-dbw** [comment] 2020-07-09 23:15
> This doesn't happen when just logging in and using pwsh directly (i.e. without tmux)

Got it. I misunderstood this comment -- thought you meant logging in the box directly and use pwsh without ssh.

**Comment by daxian-dbw** [comment] 2020-07-09 23:30
> Steps to reproduce:
>- start Windows Terminal (1.0.1811.0)
>- open terminal (Powershell core 7.0.2)
>- connect to CentOS 8 machine using ssh
>- inside the bash-session (at the CentOS host) start tmux
>- inside tmux start powershell core (pwsh)

Just additional data: I have a Ubuntu 16.04 handy, so I tried the steps targeting it and couldn't reproduce the issue.

**Comment by iSazonov** [comment] 2020-07-10 08:24
For reference #3889

**Comment by Bit-Chaos** [comment] 2020-07-10 08:48
Just an update:
I removed the posh-git (https://github.com/dahlbyk/posh-git) module from the powershell init script and then everything works as expected. So this seems to be a problem with the combination of tmux+powershell+posh-git and is probably more related towards the posh-git module and not powershell itself.

**Comment by daxian-dbw** [comment] 2020-07-10 16:38
@Bit-Chaos Thanks for the update. You may want to file an issue in the posh-git repo then. I will close this issue as `Question-Answered`.

**Closed by daxian-dbw** 2020-07-10 16:38 UTC
Labels: Area-Remoting, Issue-Question
