### ISSUE TITLE
`0b11111111` returns `-1` instead of `255`

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#19218] opened 2023-02-24 21:20 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
[convert]::ToString(255,2)
0b11111111
[convert]::ToInt32(11111111,2)
```

```diff
11111111
-1 
255
```

### Expected behavior

```console
11111111
255
255
```

### Actual behavior

```console
0b11111111 returns -1
```

### Error details

```console
No Errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Linux 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


and 7.3.2
```

**Comment by rhubarb-geek-nz** [comment] 2023-02-24 21:44
If it was a signed 8 bit byte then it would make sense as it would be twos complement sign extension.

```
PS> (0b11111111).GetType().Name
Int32
PS> 0b11111111                 
-1
```

**Comment by 237dmitry** [comment] 2023-02-24 22:16
And 65535

**Comment by rhubarb-geek-nz** [comment] 2023-02-24 22:19
> And 65535

I raise you 4294967295 for an unsigned 32 bit all ones

**Comment by mklement0** [comment] 2023-02-25 03:38
Per [about_Numeric_Literals](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Numeric_Literals#working-with-binary-or-hexadecimal-numbers):

> If a binary string is some multiple of 8 bits long, the highest bit is treated as the sign bit.
> [...]
> Specifying an unsigned suffix on binary and hex literals ignores sign bits.

Therefore, use a `u` suffix to ensure that you get an _unsigned_ (positive) value:

```powershell
PS> 0b11111111u
255  # [uint32]

PS> 0b11111111uy
255  # [byte]

PS> 0b11111111us
255  # [ushort] == [System.UInt16]

PS> 0b11111111ul
255  # [ulong] == [System.UInt64]

```

**Comment by 237dmitry** [comment] 2023-02-25 05:24
> Therefore, use a `u` suffix to ensure that you get an unsigned (positive) value.

For 255 only? But for 254 and 256 this is not necessary.

**Comment by rhubarb-geek-nz** [comment] 2023-02-25 06:59
24 is a multiple of 8 but this rule is not applied

```
PS > 0b111111111111111111111111
16777215
PS > (0b111111111111111111111111).GetType().Name
Int32
```

**Comment by 237dmitry** [comment] 2023-02-25 07:57
> 4 is a multiple of 8 but this rule is not applied

the "rule" of 255, this bug is for 255 and 65535:

```powershell

for ($i = 1; $i -le ([int]::MaxValue * 2); $i *= 2)
{
    $m = ($n = $i - 1) % 255
    '{0,11}: {1,-11} {2}' -f $n, [int] $( '0b' + [convert]::ToString($n,2)), $m
}

```

**Comment by mklement0** [comment] 2023-02-25 17:58
I should have clarified that I was merely citing the documentation and showing a workaround,
but let me weigh in on what I think of this behavior:

It is certainly surprising, and the true rules are obscure (and currently incorrectly documented, as @rhubarb-geek-nz  points out) and inconsistent with the rules for _hex_ literals.

Let me try to document the current _de facto_ behavior (inferred from experiments - haven't looked at the source code):

* Binary literals without a type suffix or with _signed_ integer-type suffixes (`y`, `s`, `l`, `d`, `n`) that have `8`, `16`, `32`, or `64` binary digits (bits) and whose first digit is `1` (the high bit) become _negative_ numbers: they are treated as _bit patterns_ of a _signed_ integer type of that width (see [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement)). 

  * Note that this means that the high bit _alone_ decides whether the resulting number is negative; e.g., `0b10000000` is `-128`

* You would _think_ that the resulting number types map onto signed types `[sbyte]`, `[int16]` (`[short]`), `[int32]` (`[int]`) and `[int64]` (`[long`]), but binary numbers with `8`, `16` digits  are converted to `[int32]` too.
     *  _Hex_ literals:
        *  `[int32]` and `[int64]` are also the automatically chosen types used for non-suffixed _hex_ literals up to 64 bits.
        *  However, the _negativity rules differ_: only `32`-bit values and `64`-bit values with the high bit set  are negative _by default_ (e.g., `0xffffffff` and `0xffffffffffffffff`) and smaller numbers can only be negative with an _explicit type suffix_ for a smaller signed type (e.g,. `0xffy` (`[sbyte`]) and  `0xffffs` (`[short]`==`[int16]`)

* Type suffixes for _unsigned_ integer types prevent interpretation as a negative number, both for binary and hex literals: `uy` (`[byte]`), `us` (`[ushort]`==`[uint16]`), `u` (`[uint32]`, widened to `[uint64]` if needed), and`ul` (`[ulong]`==`[uint64`])

  * Beyond 64 bits, number literals fundamentally only work with suffixes `d` (`[decimal]`) and `n` (`[bigint]`) , both of which are _signed_ types, so the non-suffixed negativity rules apply them as well, _plus_ to _every additional `32` bits of width_, up to `96` for `[decimal]`, and open-ended for `[bigint]`, but for _binary_ literals only.
  The _only_ way by prevent negative numbers for these type is  by _prepending `0`_; e.g., `0b0111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111n` (`[decimal]`, `79228162514264337593543950335`, which is `[decimal]::MaxValue`)


     *  _Hex_ literals:
         *  With type suffix `d` (`[decimal]`):
            * Note: `[decimal]`, strictly speaking, isn't an _integer_ type, but it can be used like one and when parsing _binary_ literals, it seems to behave like a 96-bit signed integer.
            * _Unexpected behavior_ up to 64 bits, e.g., `0xfffffffD` (7 hex digits) is `-3`(!) and `0xffffffffD` (which without `D` would be `-1`) is `68719476733` (!).
            * _Broken_ beyond 64 bits (e.g., `0xffffffffffffffffffffffffD` (96 bits) fails to parse, even though it is the equivalent of binary `0b0111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111D`, which works.
        * With type suffix `n` (`[bigint]`):
           * Hex. literals In the _beyond-64-bit_ range are _always positive_, unlike binary literals; e.g., `0xffffffffffffffffffffffffN` is `79228162514264337593543950335`, whereas the equivalent binary literal, `0b111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111N`, is `-1` (and would require a leading `0` to be positive).

* Finally, there's an outright _bug_: 

  * Non-suffixed binary literals with `96`, `128`, ... digits should _break_ (the widest auto-selected type is `[int64]`, which cannot hold such numbers), but the parsing _quietly overflows_ and returns `-1` of type `[int32]`; e.g: `0b111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111`

**Comment by 237dmitry** [comment] 2023-02-25 20:15
Professional explanation. But this behavior, I believe, should be fixed. Maybe just by documenting and advising to add a zero to the `0b` prefix ( `0b0` ) ?

**Comment by mklement0** [comment] 2023-02-26 21:23
Thanks, @237dmitry; I think there are several actions needed:

* The outright bugs described should be fixed.

* The current behavior should be revisited, especially in light of the discrepancies between _binary_ and _hex_ literals:

  * Backward compatibility is a concern, though perhaps binary literals have seen so little use so far and current uses probably employ the workarounds needed to get a _positive_ number, so changes could fall into [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area), in which case they'd be acceptable.

  * Note that while the _hex_-literal behavior may be _less_ surprising, it still is (I think most people's expectation is to _never_ get a negative number), but that ship has probably sailed (a change was discussed pre-v6 - see https://github.com/PowerShell/PowerShell/issues/3313#issuecomment-297103481 - but it lead to the `U` suffix instead of changing the default behavior).

* The documentation should be amended either way, both to correct the existing inaccuracies and to provide clear guidance.
  * The `0b0` technique _is_ already mentioned, but it should certainly be made clearer when it is needed.
  * Using type suffix `u` is the better option as long as you're in the realm of 64-bit values (which, if I were to guess, applies to most use cases), because it also allows you to get an _unsigned_ 64-bit value up to `[uint64]::MaxValue`; that is, `0xffffffffffffffffU` and `0b1111111111111111111111111111111111111111111111111111111111111111u` work, while `0x0ffffffffffffffff` and `0b01111111111111111111111111111111111111111111111111111111111111111` do not.

**Comment by jhoneill** [comment] 2023-03-07 12:53
> > Therefore, use a `u` suffix to ensure that you get an unsigned (positive) value.
> 
> Exclusively for 255? But for 254 and 256 this is not necessary.

if 254 is written as a 0b11111110 it will come back as -2  , 256 is OK because you have 9th bit. 
Any number >= 128 written with exactly 8 bits becomes the 2's compliment negative (so does any number >= 32768 written with exactly 16 bits, or >= 2147483648 within with exactly 32 bits etc. )



> But this behavior, I believe, should be fixed. Maybe just by documenting and recommending to add a zero to the `0b` prefix ( `0b0` ) ?

This fixes one problem by ensuring that (e.g.) 128 is written with 9 bits and is seen as a 16 bit number implied leading zeros. It won't work for a 64 bit. ` (0b01000000000000000000000000000000000000000000000000000000000000000)` gives an error. (remove the first 0 and it works)


I get a different result from convert 
```
PS>  [convert]::ToString(255,2)
11111111
```
(no leading `0b`)  It seems to me that `convert` is wrong here.  It has received an `Int32` and  trimmed all the leading zeros from it.  If the high bit is 1 in really should pad with zeros.

**Comment by mklement0** [comment] 2023-03-07 22:27
@jhoneill, to set the stage for potential further discussion and to make it clearer where PowerShell "does its own thing":

.NET and C# play by different, arguably better (simpler) rules:

* C#:
  * All hex and binary _literals_ are invariably _positive_ numbers (except if you prefix them with `-`).

  * Without a type suffix, the type is automatically chosen, using the following on-demand widening: `Int32` (`int`) -> `UInt32` (`uint`) -> `Int64` (`long`) -> `UInt64` (`ulong`)
    * No integer literals beyond 64 bits are supported _except_ if you use a _decimal_ representation and use the `m` suffix to create a `Decimal` instance (e.g. `18446744073709551616m`). 

  * C# has _no_ `System.Numerics.BigInteger` (`[bigint]`) _literals_, but you can construct them from other types, including `Decimal`, in which case the sign of the argument is honored. Thus, you need the leading-zero-byte technique to force interpretation as a _positive_ number _only_ if the value to pass to a constructor is beyond the range of `Decimal`, in which case initialization via a _byte array_ is needed. E.g. (using a small number for brevity; note that due to little-Endian representation the leading `0` byte comes _last_), `[bigint] [byte[]] 0xff` yields `-1`, whereas `[bigint] [byte[]] (0xff, 0x0)` yields `255`.

* .NET:
  * `[Convert]::ToString($num, 2)`, `[Convert]::ToString($num, 8)`, and `[Convert]::ToString($num, 16)` (the only 3 number bases other than `10` that are supported):
    *  These calls create representations strictly based on the _bit pattern_ of the input number, _with leading `0`s omitted_. That is, the input type is _lost_ in the process, including whether or not the input number was _negative_. 
      * Note that the `base` parameter is supported only for `byte`, `short`, `int`, and `long`, and _unsigned_ types are quietly coerced to the next higher _signed_ type as needed, with `long.MaxValue` being the highest number supported (that is, you cannot pass a `ulong` instance with a value higher than `long.MaxValue`).

  * It is only with `[bigint]::Parse()` that the leading-zero-byte technique comes into play, and note that _all_ `Parse` methods of numeric types are limited to parsing _hex_ representations (in addition to the default _decimal_ ones): the [`System.Globalization.NumberStyles`](https://learn.microsoft.com/en-US/dotnet/api/System.Globalization.NumberStyles) enum has `AllowHexSpecifier` but _no_ <del>`AllowBinarySpecifier`</del>, i.e. parsing _binary_ string representations is _not_ supported.
    * Analogous to the `[byte[]]` constructor example above, `[bigint]::Parse('ff', 'AllowHexSpecifier')` yields `-1`, whereas `[bigint]::Parse('0ff', 'AllowHexSpecifier')` (leading `0`) yields `255`.

**Comment by jhoneill** [comment] 2023-03-08 12:00
@mklement0  thanks for filling all that in. 

I thought this was the crucial part.

> * These calls create representations strictly based on the _bit pattern_ of the input number, _with leading `0`s omitted_. That is, the input type is _lost_ in the process, including whether or not the input number was _negative_.

In other words we don't know if 1111 1111 was a signed byte -128, an unsigned byte (+255), or a positive number written with 16 or 32 bits _with the leading zeros dropped._  Similarly we don't know if  ffff was -1 in an int16 or 65535 in an int32.  Even if we had leading zeros we wouldn't know if the original was the signed or unsigned version of a type. 

However- `0xffff` returns 65535 - the **lack of leading zeros doesn't matter for hex but does for binary.** 8 digit hex numbers still follow 2s compliment so  I can see that this could be be misunderstood 
```
PS>  -0xff      
-255

PS>  -0xffff
-65535

PS>  -0xffffffff
1
```

TBH (1) I could argue for the behaviour of the binary conversion **if** 1-8 digits returned an `sbyte` and 9-16 digits returned an `int16` but they don't: they return `int32`s ; the hex conversion also returns `int32` but it assumes 2 and 4 digits are the non-zero part of a 32 bit number, unless they are suffixed to say otherwise (2) Even _if_ shorter numbers became smaller types, binary and hex would still be inconsistent, and I wouldn't argue for having both ways of working. So net, 0b handling just seems wrong.   (3) 0b notation is not in Windows PowerShell, so although changing it would be a breaking change, there aren't scripts out there which have depended on current behaviour for ages. (That's another argument for leaving 0x alone and changing 0b to match it)

**Comment by mklement0** [comment] 2023-03-08 13:41
I agree, and this has mostly already been [summarized above](https://github.com/PowerShell/PowerShell/issues/19218#issuecomment-1445471085), preceded by a detailed explanation of the [inconsistencies between `0b` and `0x` parsing](https://github.com/PowerShell/PowerShell/issues/19218#issuecomment-1445170164).

As for:
> So net [...] handling just seems wrong

I don't think `[Convert]::ToString()` is to blame here: its purpose is to create a _string representation_, not something that is guaranteed to round-trip as a _number literal_ in all .NET-based languages.(which inherently could have different syntaxes for number literals, leaving the obvious difference of prefixes, such as `0x` vs. `&H`, aside).

Creating a language-neutral round-trip representation at the .NET API level would require a new, opt-in  `[Convert]::ToString()` overload, combined with the introduction of a complementary `[Convert]::FromString()` method.

**Comment by jhoneill** [comment] 2023-03-08 15:30
@mklement0   as this has gone on I've changed my view a bit. Initially I thought that this was exclusively a problem with `[convert]` the more I've read (thanks) and tested it, the more I think it is only part of the issue, and the `0b` parsing is the bigger problem.  

You're right that anyone who doesn't write dates as least-significant in the middle probably knows convert to string is not guaranteed to convert back.    
```
PS>  $x=get-date   # today is the 8th day of march 
PS>  $y=[convert]::ToString($x)
PS>  $y
08/03/2023 15:13:03  # to string in least significant first date format
PS>  [datetime]$y              #  from string in least significant in the middle format. 
03 August 2023 15:13:03
```

IIRC [convert] uses local culture, and [datetime]"string" is culture invariant, and whilst the logic for doing this is sound, it is not always obvious. 

One can write ```[convert]::ToString(200,2).PadLeft(32,"0")``` to ensure the binary literal will convert back. In an ideal world this would be a parameter in `ToString`. 

Just as a we sloppily write "3:13:03" without specifying the timezone (or whether it is AM or PM), giving a meaningless time  0b11111111 without a suffix which says "signed/unsigned" and whether it is more than 8 bits is really not good practice.  I think the real answer is to tell people to use the suffix and be explicit - but I also think the default behaviour can be improved.

**Comment by mklement0** [comment] 2023-03-09 00:56
> and the `0b` parsing is the bigger problem.

I fully agree.
As you've previously observed, the only conceivable justification for the current behavior would be if the input bit width implied the specific (signed) data type to return, so that `0b11111111` would return an `[sbyte]`, for instance.
As it stands, the input bit pattern is effectively _modified_ through the type-widening to `[int]` (it effectively becomes `0b11111111111111111111111111111111`).

And, of course, there's the inconsistency with how _hex_ literals are parsed.

As discussed, we're probably stuck with the itself counterintuitive behavior of _hex_ literals, given its long history, but hopefully a bucket-3 argument can be made to align the behavior of _binary_ literals with that of hex literals, for at least _consistent_, less complex counterintuitiveness, if you will.

In the context of this alignment, ideally we'd get rid of the leading-`0` logic altogether:
 * For values > 64 bits - types `[decimal]`, `[bigint]` -  the leading `0` never made sense to begin with, given that neither type is a simple _bit field_; Instead:
   * Treat all values in this range as _positive_ numbers, the way _hex_ literals already do. 
   * If the intent is to get a _negative_ number, prefix the literal with `-`.
 * For values <= 64 bits, using type suffix `u` is the better choice (see below).

---

Separately (irrespective of whether `0b` parsing will change), we should offer the following guidance in the docs:

* If you need your number literal (whether decimal, hex, or binary) to be _a specific type_, use the appropriate type-specifier suffix (`y`/ `uy`, `s`/ `us`, (by default) / `u`, `l` / `ul`), or - beyond 64 bits - `d` (n/a to _hex_ literals)  or `n`

* If you simply want to ensure that your number literal is treated as a _positive_ value, irrespective of the specific resultant type, use suffix `u`, for values up to `UInt64` (`[ulong]`)

---

As for `[convert]::ToString()`:

There are two separate aspects that hamper round-tripping:

* Culture-sensitivity - this can be bypassed by passing `[cultureinfo] ''` (representing the _invariant culture_)  as the `System.IFormatProvider` argument; e.g. ` [convert]::ToString((Get-Date), [cultureinfo]  '')`
* Loss of accuracy / type identity - this would require _a new notation_, given that even preserving the exact _bit pattern_ doesn't preserve the exact _type identity_ (signed vs. unsigned).

**Comment by vexx32** [comment] 2023-04-03 21:15
WG-Engine discussed this today. We agree the current behaviour is unintuitive and it may be worth the breaking change in this instance.

We suggest the parsing should be modified to line up functionally with the hexadecimal parsing: all literals up to 32-bits wide should be considered effectively "unsigned" -- so that things like `0b11111111` should not resolve to a `-1`, and the only accepted sign bits should be 32, 64, and above that are currently accepted by the parsing.

Implementation wise this should be a relatively simple change, just removing these two `switch` cases from the binary parsing utility method:

https://github.com/PowerShell/PowerShell/blob/04b93af4ae333013e4fe00013a196268d314cb00/src/System.Management.Automation/engine/Utils.cs#L188-L189

**Closed** 2023-11-22 10:55 UTC
Labels: WG-Engine, Up-for-Grabs, Breaking-Change, Resolution-No Activity
