### ISSUE TITLE
Help on Linux says "Windows PowerShell Help"

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#3965] opened 2017-06-07 21:06 UTC

**Comment by SteveL-MSFT** [comment] 2017-06-08 16:44
related https://github.com/PowerShell/PowerShell/issues/3345

**Comment by SteveL-MSFT** [comment] 2017-06-08 16:45
Actually, this is a dupe of https://github.com/PowerShell/PowerShell-Docs/issues/1228

**Closed by SteveL-MSFT** 2017-06-08 16:45 UTC
Labels: Area-HelpSystem, Resolution-Duplicate
