### ISSUE TITLE
Mapping for Basic Environment Variables between platforms

### ISSUE THREAD

**Issue by mvadu** [PowerShell/PowerShell#3263] opened 2017-03-05 22:33 UTC
Is there a mapping to get the equivalent folders between platforms? Or what is the suggested method to reuse same script between Windows and Linux?

I have a script which downloads few executables (Influxdb) to temp folder. The  executable then creates a folder under `~/.<folder>` in Linux and `%UserProfile%\.<folder>` in Windows. I was hoping to reuse same Powershell script as part of my .Net Core application. However the scripts in Linux fails to get to `$env:UserProfile`.

Steps to reproduce
------------------
 test-path $env:USERPROFILE

Expected behavior
-----------------
True

Actual behavior
---------------
Works in Windows

Linux: Ubuntu 16.04
```powershell
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:12
+  test-path $env:USERPROFILE
+            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingVa
   lidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.TestPathCommand

 ```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.15
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by SteveL-MSFT** [comment] 2017-03-05 23:18
We should add this case to https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0019-PowerShell-Core-Interop-Module.md

**Comment by BrucePay** [comment] 2017-03-06 19:56
@mvadu Rather than depending on system-specific environment variables, you should use ~ which is supported on all platforms e.g. test-path ~  (~ support in paths has been in PowerShell since V1).
@SteveL-MSFT Are you suggesting that we add all of the Windows-specific environment variables to Linux and macOS and vise versa?

**Comment by SteveL-MSFT** [comment] 2017-03-06 20:04
@BrucePay not sure how you came to that conclusion, my point is that the RFC is about interop/portability and the discussion should happen there

**Comment by mvadu** [comment] 2017-03-06 23:17
@BrucePay `$env:UserProfile` was just an example, and for `~` I can as well use `$HOME` which works same across platform. My point was similar to @SteveL-MSFT stated, we need to have standard scripts which work across multiple platform with least amount of conditional (`if($IsLinux){}`) logic.

**Comment by andschwa** [comment] 2017-03-13 18:07
Related to (duplicate of?) #1262.

**Comment by dbussanich** [comment] 2017-04-11 18:24
$env:SystemRoot should be added to MacOS/Linux. Need some way to pragmatically determine the system root.

**Closed** 2017-05-15 18:54 UTC
Labels: Area-Portability, Resolution-Duplicate
