### ISSUE TITLE
[Copy-Item] MSDN Example 8 does not work

### ISSUE THREAD

**Issue by hayhay27** [PowerShell/PowerShell#3332] opened 2017-03-15 07:21 UTC
Steps to reproduce
------------------
Example 8: Copy a file to a remote computer and then rename the file

$Session = New-PSSession -ComputerName "Server04" -Credential "Contoso\PattiFul"
Copy-Item "D:\Folder004\scriptingexample.ps1" -Destination "C:\Folder004_Copy\scriptingexample_copy.ps1" -T
oSession $Session

Expected behavior
-----------------
Copy file with new name to folder on the remote computer

Actual behavior
---------------
Exception
Copy-Item : Destination folder 'C:\Temp\file.ps1' does not exist.
At line:1 char:1
+ Copy-Item F:\tmp\clean.ps1 -Destination "C:/Temp/file.ps1" -ToSession ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Temp\file.ps1:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : RemoteDirectoryNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Environment data
----------------
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ZonderP** [comment] 2017-04-05 11:20
I can confirm this bug for the exactly same PS version.
Just came across that issue myself.

**Comment by ZonderP** [comment] 2017-04-05 11:39
OK, same happens when remote machine runs with PS 5.1.:
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ZonderP** [comment] 2017-04-05 12:19
And last but not least:
This bug seems to be fixed in PS 5.1, since when I did this from a machine with PS 5.1 installed versus a remote machine with PS 5.0 installed then it worked!

**Comment by SteveL-MSFT** [comment] 2017-04-11 22:27
This doesn't repro with PSCore 6.0.  We're not planning on backporting the change to PSv5.

**Closed by SteveL-MSFT** 2017-04-11 22:27 UTC
Labels: Issue-Question, Resolution-Answered
