### ISSUE TITLE
Inconsistent support for converting number strings with binary-multiplier / number-type suffixes to numbers

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7710] opened 2018-09-05 16:13 UTC
Note:

* Changing this would technically be a breaking change and/or may be undesirable for performance reasons, in which case the issue should be _documented_.

When converting from _strings_, 

* PowerShell currently DOES recognize binary-multiplier suffixes such as `kb`, `mb`, ...:

  * in _expressions_ (e.g., `'1gb' / 1`)

* but DOES NOT recognize them:

  * during _implicit_ type conversion in then context of _parameter binding_ (e.g.,
`& { param([int] $foo) } '1gb'`)

  * (perhaps less surprisingly) in _explicit_ type conversions with _casts_ (e.g., `[int] '1gb'`)

_Update_: The same applies to PowerShell's _number-data-type suffixes_ such as `d` for `[decimal]` and `l` for `[long]`.

Environment data
----------------

Written as of:

```powershell
PowerShell Core 6.1.0-preview.4
```

**Comment by iSazonov** [comment] 2018-09-06 09:44
It is not type conversion. The multipliers is realy "multiplier" in parse time. Type conversion is done in run-time. So $($var)Kb doesn't work too.

**Comment by mklement0** [comment] 2018-09-06 14:04
@iSazonov: That applies to _unquoted number literals_ such as `1gb`.

By contrast, my expression example uses a _quoted string_, where type conversion is clearly performed _at runtime_:

```powershell
PS> $v="1gb"; $v / 1
1073741824
```

/cc @PetSerAl

**Comment by vexx32** [comment] 2018-09-06 14:11
I'm not really sure this *should* be a thing. How is PS supposed to distinguish cleanly between when you want something to cast as an integer (especially in implicit cases) and when you might want it to throw instead? 

I can see that it probably *ought* to happen for strongly-typed parameters and would make sense there, but in most cases you'll call a parameter like that... just as a number: `Do-Thing -Number 1gb` rather than as a string `Do-Thing -Number '1gb'` -- and I think that distinction is probably pretty sensible.

**Comment by mklement0** [comment] 2018-09-06 14:28
@vexx32:

Well, it already _is_ a thing, but only _partially_ (only in expressions), and that inconsistency prompted me to raise this issue.

> How is PS supposed to distinguish cleanly 

Just like with any "number strings": if the context explicitly requires a _number_, try to convert the string to one.

Yes, passing a string to something that expects a number is not the typical case, but it works with all other "number strings" - namely those that _.NET_ recognizes.

Note that the inconsistency is not limited to the binary-multiplier suffix, it also applies to the data-type suffixes:

```powershell
'1d' / 1  # OK -> 1, of type [decimal]

[int] '1d' # FAILS -> Cannot convert value "1d" to type "System.Int32". Error: "Input string was not in a correct format."
```

**Comment by iSazonov** [comment] 2018-09-06 15:02
@mklement0 I mean that '1Gb' and '1d' is strings and PowerShell have to parse the strings to convert to numerics. In runtime 'Gb' and 'd' would have to be operators.

**Comment by mklement0** [comment] 2018-09-06 15:13
@iSazonov: 

Yes, they are strings, and PowerShell converts them to numbers in _expressions_; by contrast, it doesn't do so when converting _implicitly_ during parameter binding - that is the inconsistency being discussed here.

I understand that _.NET_ (CoreCLR) doesn't know about _PowerShell's_ number-literal suffixes, but the question is whether _PowerShell_ should handle the conversion part consistently.

As I said, with explicit _casts_ the picture is not as clear, but there already is a precedent for PowerShell doing additional behind-the-scenes work, such as casts sometimes being translated in to `::Parse()` calls with the invariant culture.

**Comment by iSazonov** [comment] 2018-09-06 15:29
@mklement0 I see your point.
What about 
```powershell
$var = '1gb'
& { param([int] $foo) } $var
```

Seems we'll have to extra steps to process this.
And then what about:
```powershell
$var = '1gb'
$var + 1
```
is this string operation or numeric?

**Comment by mklement0** [comment] 2018-09-06 15:41
@iSazonov: 

Your 1st example is already in the OP, as an example of where the conversion _doesn't_ work (_implicit_  conversion in the context of _parameter binding_).

As for the 2nd example:

`+` - unlike `/` - does _not_ perform to-number conversion, so nothing would change there:

```powershell
'1' + 0 # -> '10'
'1gb' + 0 # -> '1gb0'
```

To summarize: The only potential change being discussed here is:

Should _all contexts where PowerShell currently already performs to-number conversion_ _consistently_ recognize [string representations of] PowerShell-only number-literal formats _too_?

**Comment by iSazonov** [comment] 2018-09-07 06:11
It is a question for PowerShell Committee.

**Comment by SteveL-MSFT** [comment] 2018-12-05 23:34
@PowerShell/powershell-committee reviewed this.  This is a breaking change where it used to fail and now works.  We agree that the desired behavior is acceptable.  However, this is likely a complex change that need to also work with recently introduced suffixes like `l` for LONG.

**Comment by vexx32** [comment] 2018-12-06 01:04
Would simply passing the string to one of the parser or tokenizer functions be an appropriate way to determine if it's a parseable number and the resultant type?

Side note: `L` is an old suffix, but there are several newer ones that do indeed need to be considered also :wink:

**Comment by SteveL-MSFT** [comment] 2019-01-12 04:11
cc @daxian-dbw @BrucePay

**Comment by vexx32** [comment] 2019-01-12 05:18
Thanks, Steve! I checked in with @TylerLeonhardt who passed it along to @rjmholt, and after some brief suggestions I traced the cached conversion methods that get called from string->integral types to here:

https://github.com/PowerShell/PowerShell/blob/e399b06cd23a8d9a7df9be5ed329471ba5b8eb82/src/System.Management.Automation/engine/LanguagePrimitives.cs#L2888-L2907

My initial thought so far is to add some kind of check in there to determine if the last two characters in this (possibly trimmed?) value are a multiplier or the last character is a type suffix, something kind of like...

```csharp
ScriptBlockAst result;
char lastChar = strToConvert[strToConvert.Length - 1];
if (!lastChar.IsTypeSuffix() ||
    lastChar == 'b' && strToConvert[strToConvert.Length - 2].IsMultiplierStart())
{
    result = Parser.ParseInput(strToConvert, out Token[] tokens, out ParseError[] errors);
}
```

And then I think I can grab `tokens[0].Value` to determine the numeric value and use that. _However_, I don't know that invoking `ParseInput()` here is the **best** available option. It also sort of bypasses the _need_ for the latter half of this conversion expression, because the token's `.Value` property seems to hold the appropriate data type coming out of it, at least where any type suffix may be concerned.

Would definitely appreciate some input from y'all on this, it's a fun little rabbit trail, but I don't want to get too far off track and in a direction that isn't useful to y'all. 😄

**Comment by rjmholt** [comment] 2019-01-17 19:17
> EDIT: Spoke a little with @SeeminglyScience this morning, and he and I think it might be better if we can somehow decouple portions of ScanNumberHelper and TryGetNumberValue from the tokenizer stepping logic and reuse that, so that we're guaranteed self-consistent results without having to create an entire parser and tokenizer during this conversion, which is almost certainly an expensive operation. How doable that is, I don't know yet. Interesting thought though.

My personal feeling is as you say; casting numbers from strings here should work in exactly the same was as they would in the tokenizer (the easiest way being to share the function). If that requires no state, or can be decoupled from the tokenizer state, then the method may as well be shared and used in both places.

I don't know how expensive it is to create a new tokenizer (or if it's possible to do outside of the parser with current type access) but to my mind, casting is often associated with some overhead, so it's not the end of the world if the first implementation is not as efficient as it could be.

I would favour doing it consistently over making it fast, since once it's released we can improve the latter but improving the former would be a breaking change.

**Comment by vexx32** [comment] 2019-01-17 19:36
@rjmholt I think I can agree with all your points there.

Currently you cannot instantiate the tokenizer without the parser, and the main method I know to parse the input would be the static `Parser.ParseInput()` method mentioned above. 

I've been looking at attempting to decouple the methods in the tokenizer, and while I believe it may be eventually worthwhile it may not be especially valuable at this point in time. It's not a small work item by any means; a _lot_ of the underlying logic is coupled tightly to the step-through methods. I can decouple portions of the methods, but I've yet to find any relatively clean ways to thoroughly decouple the methods without causing every possible number to be double-scanned anyway. It may well be simpler to just... invoke the parser on the suspected number and go from there.

If that sounds OK, I can tidy the code in that method and submit a PR?

**Comment by rjmholt** [comment] 2019-01-17 19:41
> Currently you cannot instantiate the tokenizer without the parser (that I can see, anyway), and the main method I know to parse the input would be the static Parser.ParseInput() method mentioned above.

Mmm, I thought that was the case. Bugger.

> I've been looking at attempting to decouple the methods in the tokenizer, and while I believe it may be eventually worthwhile it may not be especially valuable at this point in time. It's not a small work item by any means; a lot of the underlying logic is coupled tightly to the step-through methods.

I've wanted parser and tokenizer as nice, standalone objects for a while as well, but I think the likelihood of breakage to a critical (and currently very fault-tolerant) part of PowerShell means we need a large and compelling reason for the work.

**Comment by vexx32** [comment] 2019-01-17 19:51
Completely agree there. I think it's certainly _possible_ to handle this, but as you say... not really worth it until there's a real **need** for it.

I'll corral the code here and get it working properly, then submit the PR. 😄

**Comment by lzybkr** [comment] 2019-01-18 00:38
I think you're looking for this [code](https://github.com/PowerShell/PowerShell/blob/f1218bd3d9ba97ea13cc7e37a0c5a82ed9fa9556/src/System.Management.Automation/engine/parser/Parser.cs#L228). Note that it creates a parser which is not expensive.

**Comment by vexx32** [comment] 2019-01-18 00:43
@lzybkr Thank you! That saves me rewriting that code... _fantastic_. This'll be pretty straightforward. 😄 

Creating a parser _isn't_ expensive? That's... actually very surprising, looking at the size of those files. Good to know, though!

**Comment by lzybkr** [comment] 2019-01-18 01:12
If you look at just the [constructor](https://github.com/PowerShell/PowerShell/blob/f1218bd3d9ba97ea13cc7e37a0c5a82ed9fa9556/src/System.Management.Automation/engine/parser/Parser.cs#L52) you can see it does very little.

That said, because C# lets you initialize properties outside the constructor, there could be expensive work hiding elsewhere, but by design creating a parser was meant to be inexpensive and if that is not the case, it's something that should be fixed.

**Comment by vexx32** [comment] 2019-01-18 04:20
@lzybkr Got it halfway there with that; see the referenced PR.

As long as the value in the string is valid when it's parsed, we get the right value and type back (e.g., if you do `[int]"100y"` you _do_ get back 100 as an int, because 100 is a valid byte value, can be parsed, and then it gets converted.

But it just completely crashes PS with a `StackOverflowException` when the value in the string is an invalid number (e.g., `200y`, which would usually throw a parsing exception if you attempt to use it normally, just crashes PowerShell ).

**Comment by iSazonov** [comment] 2019-01-18 05:02
Can we reuse the parser and don't allocate it in every ScanNumber() call?

**Comment by vexx32** [comment] 2019-01-18 05:05
🤔 Potentially? I'm not sure how much gain there is in doing so, though, or how complicated it would end up being. I'll look into it tomorrow. 😄

**Comment by iSazonov** [comment] 2019-01-18 05:16
It is _engine_. If we can avoid an allocation we should do I believe.

**Comment by vexx32** [comment] 2019-01-19 23:47
@iSazonov I attempted to add a `static Parser` field to `LanguagePrimitives` but immediately this resulted in an `AMSI uninitialization error` as soon as the project was built and run; it could not even reach the console prompt.

```
The shell cannot be started. A failure occurred during initialization:
The type initializer for 'System.Management.Automation.Language.Compiler' threw an exception.
Assertion Failed
AMSI should have been uninitialized.
```

I'm not sure why this occurs, but I'm sure there's probably some reason for it.

**Comment by iSazonov** [comment] 2019-01-21 03:58
It come from `VerifyAmsiUninitializeCalled()`. I guess it is side effect. You could remove the assert temporary to find root cause.

**Comment by vexx32** [comment] 2019-01-21 04:15
Not a bad idea... What would I be looking for after it's disabled? I'm not at all familiar with that code.

**Comment by iSazonov** [comment] 2019-01-21 04:19
I expect that after you disable the assert you will see that process terminated and will need to research why.

**Comment by vexx32** [comment] 2019-01-21 05:35
Ah, my favourite kind! 😄 

I'll see if I can find some time to take a close look at it tomorrow. 🙂

**Comment by vexx32** [comment] 2019-01-22 13:52
@iSazonov Gave this a look, but it's not actually crashing.

It does however completely disable the error stream. $Error is never populated, errors never display. 

Very odd! Debugging time!

**Comment by lzybkr** [comment] 2019-01-22 17:37
My 2¢ - it's probably not worth the trouble to reuse the parser, but if you did, it would look something like [this](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/CoreLib/System/Text/StringBuilderCache.cs).

**Comment by vexx32** [comment] 2019-01-22 17:44
I may well have a crack at it and see if I can follow that example, but that will probably be in a followup PR. 😄 

Thank you! ❤️

**Comment by SteveL-MSFT** [comment] 2019-01-22 17:47
@vexx32 the AMSI assert is https://github.com/PowerShell/PowerShell/issues/6862

**Comment by vexx32** [comment] 2019-01-28 21:36
@SteveL-MSFT @lzybkr @iSazonov So I got curious and decided to see if I could put this together; this is what I came up with.

```csharp
internal static class ParserCache
{
    [ThreadStatic]
    private static Parser t_cachedInstance;

    internal static Parser Acquire()
    {
        Parser p = t_cachedInstance;
        if (p != null)
        {
            t_cachedInstance = null;
            return p;
        }

        return new Parser();
    }

    internal static void Release(Parser p)
    {
        if (p.ErrorList.Count > 0)
        {
            p._fileName = null;
            p._ungotToken = null;
            p.ErrorList.Clear();
            t_cachedInstance = p;
        }
    }
}
```

I ran a build with it, and it seems to work just fine. There are a handful of callsites in `Parser.cs` where `new Parser()` is called that I replaced with the methods here, and it seems to work just fine. Whether there's any performance benefit I'm not clear on.

Think it's worth including in #8681?

**Comment by vexx32** [comment] 2019-01-29 13:14
All very valid concerns, indeed! I appreciate the tips, thank you! 🙂 

I'm not familiar with much of reflection, but such a test doesn't seem overly complicated to do... just need to make sure to be thorough. 😄 

My thought is that pulling a parser from the cache should get you a parser in the exact same state as a newly-created parser. Doing a comparison between the two should be the best indicator, as well as being fairly future-proof in terms of ensuring it still properly covers the case that someone adds new members to the Parser class down the road. I think. 😄

**Comment by iSazonov** [comment] 2019-01-29 13:16
Why we need new Parser in ScanNumber?

**Comment by vexx32** [comment] 2019-01-29 13:18
@iSazonov all of the `static Scan*()` methods in the parser currently instantiate a new Parser object in order to perform their function. As to _why_ specifically, I'm not familiar with everything about the code (I'm sure Jason could speak to that far better than I, of course) but the tokenizer and parser are tied together; you literally _can't_ instantiate one without the other.

The only available constructor for the tokenizer class requires a Parser object as input. Certainly, perhaps this could be changed, but I don't know whether or not that is... wise. 🙂

**Comment by iSazonov** [comment] 2019-01-29 13:41
My thoughts is about possibility of using current Tokenizer and Parser. Perhaps they could be improved to support this and perhaps it is more simple.

**Comment by lzybkr** [comment] 2019-01-29 18:46
The tokenizer uses the parser for error reporting. There may be other important ties that I forget, but that's the big one.

Unless you have concrete data showing a performance problem, I'll suggest the risk isn't worth it.

I've suggested ways to mitigate the risk (and testing that a `Reset` parser is in the same state as a new Parser is also a good idea - not sure how that will look in code though), but in the end - I'd like data to justify the extra complexity and maintenance risks.

**Comment by iSazonov** [comment] 2019-01-30 04:44
@lzybkr Thanks! 

Initial request was to reduce garbage pressing. The parser state resetting is not resolve this. So I agree that the change is not worth it.

**Closed** 2019-02-04 20:22 UTC
Labels: Area-Language, Breaking-Change, Committee-Reviewed, Issue-Discussion, Up-for-Grabs
