### ISSUE TITLE
Release on Microsoft Store: Process for v7.x.x

### ISSUE THREAD

**Issue by khooz** [PowerShell/PowerShell#13458] opened 2020-08-16 20:34 UTC
## Summary of the new feature/enhancement

It is more convenient that PowerShell could update itself, with a prompt or automatically through a setting so that while it informs that there is a new update available, the user can update it on the fly and not by manually downloading a package or installer and go through a repetitive process.

## Proposed technical implementation details (optional)

This is more of a release process. I suggest that like Windows Terminal that has moved on to Microsoft store, the PowerShell does too, so updates get handled by an already familiar and growing platform for devs on windows (since many features like WSL distros did too).

As for other release targets, I suggest releasing the package for their package managers and to their repositories, like official apt or rpm repositories for Debian or RedHat respectively.

**Comment by vexx32** [comment] 2020-08-17 03:33
This is a duplicate of #7730

**Closed** 2020-08-18 05:00 UTC
Labels: Issue-Enhancement, Resolution-Duplicate
