### ISSUE TITLE
New-Item fails with a custom PSDrive when creating a Symbolic Link

### ISSUE THREAD

**Issue by KubaP** [PowerShell/PowerShell#14962] opened 2021-03-07 22:33 UTC
## Steps to reproduce

```powershell
New-PSDrive -Name "TestDrive" -PSProvider FileSystem -Root ~\Desktop # Set up a new PSDrive
New-Item -Path "TestDrive:\target" -ItemType Directory # Create a target.
New-Item -Path "TestDrive:\link" -Value "TestDrive:\target" -ItemType SymbolicLink # Try to create a symbolic link to the target; it fails.
```

## Expected behavior
A symbolic link at `~\Desktop\link` will be created pointing to `~\Desktop\target`.

## Actual behavior
The `New-Item` cmdlet fails, giving the error message:
```none
New-Item: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Kuba\TestDrive:\target'
```
Notice how for some reason, it prepends `C:\Users\Kuba` (my home directory) to the `"TestDrive:\target"` string.

If you instead surround the `-Value` parameter in a `Convert-Path`, it works correctly.
```powershell
New-Item -Path "TestDrive:\link" -Value (Convert-Path "TestDrive:\target") -ItemType SymbolicLink # This works instead
```

So it seems that giving a path using a "custom" PSDrive works correctly for the `-Path` parameter, but not for the `-Value`/`-Target` parameter. Whilst the current workaround (Convert-Path) works, this feels like a bug, and is very counter-intuitive; I only stumbled upon this workaround by chance.

## Environment data
```none
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment] 2021-03-07 22:44
Good catch. It seems like the `-Value` (alias `-Target`) parameter blindly assumes that its argument is a _file-system-native path_, instead of automatically resolving paths based on PowerShell-only drives to their underlying native paths.

**Comment by tkenvin** [comment] 2022-04-16 22:17
I couldn't reproduce this on system 1, instead the behaviour was as expected.
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

On system 2, the symlink was created but clearly incorrectly.
```
drwxr-xr-x 3 tkenvin tkenvin 4096 Apr 16 23:01 .
drwxr-xr-x 5 tkenvin tkenvin 4096 Apr 16 22:57 ..
lrwxrwxrwx 1 tkenvin tkenvin    6 Apr 16 22:58 correct -> target
lrwxrwxrwx 1 tkenvin tkenvin   17 Apr 16 22:57 link -> TestDrive:/target
drwxr-xr-x 2 tkenvin tkenvin 4096 Apr 16 22:59 target
```
```
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Closed** 2023-11-23 11:20 UTC
Labels: WG-Cmdlets-Management, Needs-Triage, Area-FileSystem-Provider, Resolution-No Activity
