### ISSUE TITLE
Split-Path Fails on UNC

### ISSUE THREAD

**Issue by dchristian3188** [PowerShell/PowerShell#2202] opened 2016-09-07 17:12 UTC
Steps to reproduce
------------------
```
Split-Path -Path "\\server1\Share"
Split-Path -Path "\\server1\Share" -Leaf
Split-Path -Path "\\server1\Share" -Parent
```

Expected behavior
-----------------
```
Split-Path -Path "\\server1\Share" should return "\\server1"
Split-Path -Path "\\server1\Share" -leaf should return "Share"
Split-Path -Path "\\server1\Share" -Parent should return "\\server1"
```
Actual behavior
---------------
Whenever split-pat is ran with a "2 level" UNC path it returns a null value. 
3 levels work as excepted. 
Example 
```
Split-Path -Path "\\server1\Share\folder1" -Parent returns \\server1\Share
and
Split-Path -Path "\\server1\Share\folder1" -Leaf returns folder1
```
Environment data
----------------

Name                           Value
----                           -----
PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by vors** [comment] 2016-09-08 04:37
Hi @dchristian3188 ! Thank you for reporting the issue.
I tried it on the latest pre-release (v6.0.0-alpha.9) and it works as expected.

I'm closing it for now.
If you can repro the problem on  v6.0.0-alpha.9, please reopen the issue with details.

**Comment by dchristian3188** [comment] 2016-09-16 02:33
Hi @vors ,

I was able to reproduce on the latest build.  I tracked it down to FileSystemProvider.cs. Looking at the comments it looks like returning the empty strings is intentional. 

[https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L4733](url)

[https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L5531](url)

What do you think about removing these restrictions? 

Expected output:
Split-Path -Path "\server1\Share" should return "\server1"
Split-Path -Path "\server1\Share" -leaf should return "Share"
Split-Path -Path "\server1\Share" -Parent should return "\server1"


BuildInfo:
Name                           Value
----                           -----
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      6.0.0-alpha
CLRVersion
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.10-1-g1c3c719521483b142e22bf93e62186db9eb5845a
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3

**Comment by vors** [comment] 2016-09-18 04:56
Hm, your original repro used two back-slashes `\\`, but GitHub displayed it as one `\` and that's what caused confusion!

See

```
Split-Path -Path "\server1\\Share"
Split-Path -Path "\server1\\Share" -Leaf
Split-Path -Path "\server1\\Share" -Parent
```

is rendered like this

Split-Path -Path "\server1\\Share"
Split-Path -Path "\server1\\Share" -Leaf
Split-Path -Path "\server1\\Share" -Parent

This is, because `\` is a markdown escaping character.
Please, what out for this in the future and [use code-blocks to preserve the formatting](https://github.com/PowerShell/PowerShell/issues/2144#issuecomment-243747540).
I'm going to update the issue to use the code-snippet, so we have an accurate repro.

**Comment by vors** [comment] 2016-09-18 04:59
Confirmed! 

```
Split-Path -Path "\\server1\Share"
```
On Windows returns `$null`
On Unix returns `//server1`

Note that `Split-Path -Path "\server1\Share"` (with 1 forward slash) returns the correct result on both.

**Comment by vors** [comment] 2016-09-18 05:05
@dchristian3188 according to the comment in the code that you referenced, it's expected:

> // For UNC paths we need to ensure that "\\server\share" is
> // maintained as a single unit. There is no child for "\\server\share"

And then in `IsUNCRoot()`

        /// <summary>
        /// Determines if the specified path is a root of a UNC share
        /// by counting the path separators "\" following "\\". If only
        /// one path separator is found we know the path is in the form
        /// "\\server\share" and is a valid UNC root.
        /// </summary>

According to [this documentation](https://msdn.microsoft.com/en-us/library/gg465305.aspx) share name is indeed a mandatory part of UNC part, so I would say that it's by design.

Meantime, the fact that result is platform specific needs further conversation.
cc @lzybkr

**Closed** 2016-09-18 05:11 UTC
Labels: Area-Cmdlets, Resolution - By Design
