### ISSUE TITLE
Add-Type not loading dll 

### ISSUE THREAD

**Issue by SenseiJoe** [PowerShell/PowerShell#19795] opened 2023-06-13 21:08 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using PWSH 7.3.4
Running command
Add-Type -Path "c:\windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Word\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Word.dll" -PassThru

I get errors telling me the file can not be found.

If I run this same command in Powershell 5 or Terminal with PWSH 7.3.4 It works fine

### Expected behavior

```console
Types to be added
```

### Actual behavior

```console
Depends on Version, dll not found to import types
```

### Environment data

```powershell
Terminal - Working
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Terminal - Not Working
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Administrator PWSH - Not Working
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Powershell 5 - Working
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![PWSH5-Working](https://github.com/PowerShell/PowerShell/assets/16339587/6934337a-139a-44cb-84cd-4f294e04e801)
![PWSH7-3-4 Not Working](https://github.com/PowerShell/PowerShell/assets/16339587/0a4726a3-216d-4aea-86b1-32017410f7cf)
![PWSH7-3-4 Terminal Not Working](https://github.com/PowerShell/PowerShell/assets/16339587/5eb01d0f-0d30-4721-a346-219ff929e58f)
![PWSH7-3-4 Terminal Working](https://github.com/PowerShell/PowerShell/assets/16339587/1d99e7cf-1509-4c71-bbd9-3a61af625796)

**Comment by ThomasNieto** [comment] 2023-06-14 23:12
I was not able to reproduce it working on 7.3.4. During your testing was that a clean session or did run other commands first?

I think the issue is related to PowerShell 7 running on .NET (no GAC) while PowerShell 5 uses .NET Framework (GAC). PowerShell 5 would be able to find the required DLL in the GAC while PowerShell 7 wouldn't know where to find it. That's why if you explicitly import the required DLL first it works.

```powershell
Add-Type -Path C:\WINDOWS\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll
Add-Type -Path C:\WINDOWS\assembly\GAC_MSIL\Microsoft.Office.Interop.Word\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Word.dll -PassThru

**Comment by ThomasNieto** [comment] 2023-06-20 00:24
@SenseiJoe good to hear it worked for you. Since this is now resolved would you be able to close the issue?

**Closed** 2023-06-28 00:00 UTC
Labels: Resolution-Answered, Needs-Triage
