### ISSUE TITLE
Certificate provider (PSDrive / PSProvider) on Mac OS X is missing

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3055] opened 2017-01-26 18:34 UTC
Steps to reproduce
------------------

- Log into a Mac OS X Sierra system
- Install PowerShell Core 6.0.0 Alpha 14
- Run `Set-Location -Path cert:`

Expected behavior
-----------------

PowerShell changes context into `cert` PSDrive.

Actual behavior
---------------

PowerShell throws an exception.

```
PS /Users/trevor> cd cert:
cd : Cannot find drive. A drive with the name 'cert' does not exist.
At line:1 char:1
+ cd cert:
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cert:String) [Set-Location], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

The `Get-PSDrive` command verifies that the `cert` drive does not exist.

```
PS /Users/trevor> Get-PSDrive | ft -AutoSize

Name     Used (GB) Free (GB) Provider    Root CurrentLocation
----     --------- --------- --------    ---- ---------------
/            88.54    376.24 FileSystem  /       Users/trevor
Alias                        Alias
Env                          Environment
Function                     Function
Variable                     Variable
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mirichmo** [comment] 2017-01-28 02:23
The Cert provider has not been ported. That is why it is missing

**Comment by SteveL-MSFT** [comment] 2017-02-22 19:22
@HemantMahawar we need to discuss the feasibility of this within beta timeframe

**Comment by TravisEz13** [comment] 2017-03-01 00:52
What would you expect to find in the certificate provider on MacOS?

**Comment by SteveL-MSFT** [comment] 2017-03-02 00:37
@PowerShell/powershell-committee for the scenarios targeted for 6.0.0, cert management isn't critical and this can be a large work item.  Decision is to revisit this post-6.0.0

**Comment by demosdemon** [comment] 2017-11-11 14:15
Seeing as this isn't a priority, what do you suggest as a means for signing powershell scripts from macOS?

**Comment by SteveL-MSFT** [comment] 2018-04-26 01:33
Dupe of https://github.com/PowerShell/PowerShell/issues/1865

**Closed by SteveL-MSFT** 2018-04-26 01:33 UTC
Labels: Area-Engine, Committee-Reviewed, OS-macOS, Porting, Resolution-Duplicate
