### ISSUE TITLE
Running powershell -command 'Get-FileHash' fails

### ISSUE THREAD

**Issue by 1480c1** [PowerShell/PowerShell#8635] opened 2019-01-13 19:08 UTC
# Steps to reproduce

```powershell
powershell -noprofile -command "(get-filehash $PSHOME\powershell.exe).hash"
```

# Expected behavior

```none
DE96A6E69944335375DC1AC238336066889D9FFC7D73628EF4FE1B1B160AB32C
```

# Actual behavior

```none
get-filehash : The term 'get-filehash' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ (get-filehash C:\Windows\System32\WindowsPowerShell\v1.0\powershell.e ...
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
# Actual behavior on a different computer

```none
get-filehash : The 'get-filehash' command was found in the module 'Microsoft.PowerShell.Utility', but the module could
not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Utility'.
At line:1 char:2
+ (get-filehash $pshome\powershell.exe).hash
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 1480c1** [comment] 2019-01-13 19:14
Additional notes:

- Running the command from command prompt gives the expected results.
- Running $PSVersionTable from both the default powershell and through `powershell -noprofile -command '$PSVersionTable'` in powershell core outputs:
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
- The hash from the first computer's powershell is different than the second computer's.

**Comment by kvprasoon** [comment] 2019-01-14 03:09
This fails when the call is from PS Core. From below results, I think the modules are not reloaded for `PowerShell.exe` when invoked from PS Core.

![image](https://user-images.githubusercontent.com/12897753/51094977-3ff5ed80-17d7-11e9-86b4-7a9fc48af312.png)

![image](https://user-images.githubusercontent.com/12897753/51094992-5f8d1600-17d7-11e9-9b21-9e2aeddc9445.png)

**Comment by 1480c1** [comment] 2019-01-14 15:06
> I only see the obscure not-found error message in preview.3.
> What was different on the other computer that caused the couldn't-import message? Different PS version?
There is no difference between the two computers that I am aware of as the $PSVersionTable matched under a cursory exam and I used the same Windows (x64) stable installer for both. The only difference that I can hypothesize is that the first computer had been updated to the october update during the first window and the second is still on the previous update.

**Comment by iSazonov** [comment] 2019-01-15 03:05
We discussed to have another env path for PowerShell Core .

**Comment by mklement0** [comment] 2019-01-15 03:35
@iSazonov: 

PowerShell Core already _does_ set its own `$env:PSModulePath` value, which is appropriate in principle (but needs tweaking - see #6850).

The issue at hand is that when _Windows_ PowerShell's CLI (`powershell.exe`) is called while PowerShell _Core_'s  `$env:PSModulePath` value is in effect - which it is by default, by virtue of any child process automatically _inheriting_ the calling process' environment variables - problems arise.

**Comment by iSazonov** [comment] 2019-01-15 04:00
I believe the issue should be addressed in RFC requested in #6850.
I think the problem in important and it would be nice if MSGT team forced the RFC.

**Comment by mklement0** [comment] 2019-01-15 04:10
@iSazonov: 

* #6850 discusses how PowerShell Core itself should determine its `$env:PSModulePath` value.

* However, resolving #6850 will _not_ resolve _this_ issue, which requires hiding Core-specific `$env:PSModulePath` values from child processes that invoke the _Windows PowerShell_ CLI, `powershell.exe`.

**Comment by iSazonov** [comment] 2019-01-15 04:15
@mklement0 There is a suggestion to introduce new `$ENV:PSModulePathCore`. Seems it'll resolve the issue too.

**Comment by mklement0** [comment] 2019-01-15 04:20
@iSazonov: Good point: If, ultimately, an edition-specific environment-variable such as `$env:PSModulePathCore` is chosen for PS Core, the problem discussed here would go away too.

**Comment by rjmholt** [comment] 2019-02-12 22:49
Hmmm, I thought we already had an open issue for this but can't find it.

When `pwsh` is started from `powershell`, it inherits the `PSModulePath` env var and the Windows PowerShell module directory ends up at the start, not the end, of the module path.

Some of the Windows PowerShell Microsoft.PowerShell.* modules were marked as Core-compatible to give access to functionality that we are unable to ship with the PowerShell Core versions (and those modules are indeed Core-compatible). *However*, this causes a collision with the existing PowerShell modules.

Although the module path RFC would alleviate this, I think another simple workaround would be to have a simple script module that imports the Windows modules as nested modules and exports only the commands we don't ship now. That wouldn't be very difficult, and when I get some free time it's on my list to do.

/cc @SteveL-MSFT and @daxian-dbw since we've discussed this issue before.

**Comment by MaximoTrinidad** [comment] 2019-02-12 23:37
Hum!! Origianl issue was about the Hash.

As of now... No issues!

![noissueswithhash_01_2019-02-12_18-32-53](https://user-images.githubusercontent.com/19892435/52675439-d1e73800-2ef4-11e9-86f2-4fdc99c64fe3.jpg)

PowerShell Core Preview
```
PowerShell 6.2.0-preview.4
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PowerShell Core User Profile
PS [7] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0-preview.4
PSEdition                      Core
GitCommitId                    6.2.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS [21] >
```

PowerShell Core GA
```
PowerShell 6.1.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PowerShell Core User Profile
PS [7] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS [22] >
```

**Comment by MaximoTrinidad** [comment] 2019-02-12 23:42
On the issue of calling Windows PowerShell from within PowerShell Core.  
It works too!

![pscorecallwinposh_01_2019-02-12_18-38-56](https://user-images.githubusercontent.com/19892435/52675746-c8120480-2ef5-11e9-9af7-d1d978001442.jpg)

![pscorecallwinposh_02_2019-02-12_18-38-56](https://user-images.githubusercontent.com/19892435/52675814-fabbfd00-2ef5-11e9-9f57-b72092e2a005.jpg)

**Comment by 1480c1** [comment] 2019-02-13 00:00
![image](https://user-images.githubusercontent.com/8345542/52676508-0278a300-2ef0-11e9-8021-8785e09e7d0e.png)
``` powershell
PowerShell 6.1.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Users\cddeg> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Users\cddeg> powershell -noprofile -command "(get-filehash $PSHOME\powershell.exe).hash"
get-filehash : The term 'get-filehash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:2
+ (get-filehash C:\Program Files\PowerShell\6\powershell.exe).hash
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\cddeg> powershell -noprofile -command "Get-command get-file*"

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-FileHash                                       3.1.0.0    Microsoft.PowerShell.Utility
Function        Get-FileIntegrity                                  2.0.0.0    Storage
Function        Get-FileShare                                      2.0.0.0    Storage
Function        Get-FileShareAccessControlEntry                    2.0.0.0    Storage
Function        Get-FileStorageTier                                2.0.0.0    Storage
Cmdlet          Get-FileHash                                       6.1.0.0    Microsoft.PowerShell.Utility
```

**Comment by 1480c1** [comment] 2019-02-13 00:09
![image](https://user-images.githubusercontent.com/8345542/52676889-4fa94480-2ef1-11e9-9da8-c25a2a4f0362.png)
``` powershell
PowerShell 6.2.0-preview.4
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Program Files\PowerShell\6-preview> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0-preview.4
PSEdition                      Core
GitCommitId                    6.2.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Program Files\PowerShell\6-preview> powershell -noprofile -command "(get-filehash $PSHOME\powershell.exe).hash"
get-filehash : The term 'get-filehash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:2
+ (get-filehash C:\Program Files\PowerShell\6-preview\powershell.exe).h ...
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Program Files\PowerShell\6-preview> powershell -noprofile -command "Get-command get-file*"

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-FileHash                                       3.1.0.0    Microsoft.PowerShell.Utility
Function        Get-FileIntegrity                                  2.0.0.0    Storage
Function        Get-FileShare                                      2.0.0.0    Storage
Function        Get-FileShareAccessControlEntry                    2.0.0.0    Storage
Function        Get-FileStorageTier                                2.0.0.0    Storage
Cmdlet          Get-FileHash                                       6.1.0.0    Microsoft.PowerShell.Utility
```

**Comment by 1480c1** [comment] 2019-02-13 00:16
This should give a better idea of what my original problem was.
# test.bat

``` batch
echo.1
powershell -noprofile -command "$PSVersionTable"
powershell -noprofile -command "(get-filehash $PSHOME\powershell.exe).hash"
powershell -noprofile -command "Get-command get-file*"
```

# Running test.bat under 6.2.0-preview.4

``` powershell
PS C:\Users\cddeg> .\test.bat

C:\Users\cddeg>echo.1
1

C:\Users\cddeg>powershell -noprofile -command "$PSVersionTable"

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



C:\Users\cddeg>powershell -noprofile -command "(get-filehash $PSHOME\powershell.exe).hash"
get-filehash : The term 'get-filehash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:2
+ (get-filehash $PSHOME\powershell.exe).hash
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


C:\Users\cddeg>powershell -noprofile -command "Get-command get-file*"

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-FileHash                                       3.1.0.0    Microsoft.PowerShell.Utility
Function        Get-FileIntegrity                                  2.0.0.0    Storage
Function        Get-FileShare                                      2.0.0.0    Storage
Function        Get-FileShareAccessControlEntry                    2.0.0.0    Storage
Function        Get-FileStorageTier                                2.0.0.0    Storage
Cmdlet          Get-FileHash                                       6.1.0.0    Microsoft.PowerShell.Utility
```
# Running under 6.1.2

``` powershell
PS C:\Users\cddeg> .\test.bat

C:\Users\cddeg>echo.1
1

C:\Users\cddeg>powershell -noprofile -command "$PSVersionTable"

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



C:\Users\cddeg>powershell -noprofile -command "(get-filehash $PSHOME\powershell.exe).hash"
get-filehash : The term 'get-filehash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:2
+ (get-filehash $PSHOME\powershell.exe).hash
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


C:\Users\cddeg>powershell -noprofile -command "Get-command get-file*"

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-FileHash                                       3.1.0.0    Microsoft.PowerShell.Utility
Function        Get-FileIntegrity                                  2.0.0.0    Storage
Function        Get-FileShare                                      2.0.0.0    Storage
Function        Get-FileShareAccessControlEntry                    2.0.0.0    Storage
Function        Get-FileStorageTier                                2.0.0.0    Storage
Cmdlet          Get-FileHash                                       6.1.0.0    Microsoft.PowerShell.Utility
```

**Comment by MaximoTrinidad** [comment] 2019-02-13 00:24
Ah!! I was running it from the DOS shell. and it works!  
I understand now.  My Bad!  Hehe 

In PowerShell Core 6.1.2 getting a different message:
```
PS [17] >  pwsh -noprofile -command "(get-filehash $PSHOME\pwsh.exe).hash"
Get-FileHash : Cannot validate argument on parameter 'Algorithm'. The argument "Files\PowerShell\6\pwsh.exe" does not belong to the set "SHA1,SHA256,SHA384,SHA512,MD5" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:26
+ (get-filehash C:\Program Files\PowerShell\6\pwsh.exe).hash
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Get-FileHash], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetFileHashCommand
```
![pwsh_issue_01_2019-02-12_19-19-14](https://user-images.githubusercontent.com/19892435/52677345-8421fe00-2efb-11e9-8393-1c5214a64353.jpg)

**Comment by 1480c1** [comment] 2019-02-13 00:29
pwsh -noprofile -command {(get-filehash "$PSHOME\pwsh.exe").hash}
Your thing will evaluate to "C:\Program" and "Files\Powershell\6\pwsh.exe" as two separate arguments.

**Comment by 1480c1** [comment] 2019-02-13 00:30
Also note, I'm calling powershell from pwsh, not pwsh from pwsh.

**Comment by MaximoTrinidad** [comment] 2019-02-13 00:38
@1480c1 

Even executing Get-filehash in Windows PowerShell in PowerShell Core.  Definitely a cmdlet confusion issue.  

Thanks for the Test.bat!

:)

**Comment by SteveL-MSFT** [comment] 2019-02-19 23:23
This is a dupe of https://github.com/PowerShell/PowerShell/issues/6850.  Current proposal is to have a separate env var for PSCore6 so WinPS and PSCore6 can work from within each other.

**Closed by SteveL-MSFT** 2019-02-19 23:23 UTC
Labels: Issue-Discussion, Resolution-Duplicate
