### ISSUE TITLE
Bug in the release pipeline: Does not find the new release 7.3.6: `winget upgrade Microsoft.PowerShell`

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#19979] opened 2023-07-15 14:32 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. You have an older release installed than: 7.3.6
2. Start: `winget upgrade Microsoft.PowerShell`
3. You'll get:
```
Kein verfügbares Upgrade gefunden.
In den konfigurierten Quellen sind keine neueren Paketversionen verfügbar.
```

### Expected behavior

```console
Of course, `winget upgrade Microsoft.PowerShell` should find the latest release.
```

### Actual behavior

```console
# List the installed version
winget list Microsoft.PowerShell
Name             ID                   Version Quelle
-----------------------------------------------------
PowerShell 7-x64 Microsoft.PowerShell 7.3.5.0 winget

# Show the source of the installed package
 winget show Microsoft.PowerShell
Gefunden PowerShell [Microsoft.PowerShell]
Version: 7.3.5.0
Herausgeber: Microsoft Corporation
Herausgeber-URL: https://github.com/PowerShell/PowerShell/
Herausgeber-Support-URL: https://github.com/PowerShell/PowerShell/issues
Autor: Microsoft Corporation
Moniker: pwsh
Beschreibung:
  PowerShell is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models.
  It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.
Startseite: https://microsoft.com/PowerShell
Lizenz: MIT
Lizenz-URL: https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt
Copyright: Copyright (c) Microsoft Corporation
Copyright-URL: https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt
URL der Versionshinweise: https://github.com/PowerShell/PowerShell/releases/tag/v7.3.5
Dokumentation:
  Product Documentation: https://learn.microsoft.com/powershell
  FAQ: https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md
Markierungen:
  command-line
  cross-platform
  open-source
  powershell
  pwsh
  shell
Installationsprogramm:
  Installertyp: wix
  Installer-URL: https://github.com/PowerShell/PowerShell/releases/download/v7.3.5/PowerShell-7.3.5-win-x64.msi
  Sha256-Installer: cf0c8bd757eec6434a5830352ea6f15ace237296bb7e4ae778f7707583023ac3
  Freigabedatum: 2023-06-27
# Start the upgrade
winget upgrade Microsoft.PowerShell
Kein verfügbares Upgrade gefunden.
In den konfigurierten Quellen sind keine neueren Paketversionen verfügbar.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bzm3r** [comment] 2023-07-16 02:23
I can confirm that I have the same issue. 

```
PowerShell 7.3.5

   A new PowerShell stable release is available: v7.3.6
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.3.6

B:\> winget update Microsoft.PowerShell
No available upgrade found.
No newer package versions are available from the configured sources.
```

```
19:20:53 B:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MR0205** [comment] 2023-07-16 07:47
Have the same problem:

```
No available upgrade found.
No newer package versions are available from the configured sources.
```

**Comment by jhoneill** [comment] 2023-07-16 11:22
There are multiple issues open for linking "the new version is available" message to _availability_ in winget and the MS-Store when those were used to the installation, instead of the present to link to a new version on github. 
There is a delay between the release triggering the new version message  ( 7.3.6 released at 10:30PM UTC on Thursday 13th July, so 1 working day ago, and users started seeing the message on Friday 14th)  while winget etc do their various processes. The solution is simply "wait" but the annoyance is understood and last I knew (a few weeks ago), people were looking for practical ways to improve it.

**Comment by dodexahedron** [comment] 2023-07-17 03:41
Well, today is 3 days later, but it's still not working as expected.

Why would a "working day" have anything to do with it? 🤔 Is human interaction required somewhere in the back-end?

**Comment by jhoneill** [comment] 2023-07-17 06:16
IIRC, yes there is a human step required to approve the update.

**Comment by kilasuit** [comment] 2023-07-17 18:43
Just as an FYI to those reading this issue.

This is a duplicate issue that I have seen that we get in this repo on every **single new release**
This doesn't matter on how PowerShell is installed & comes from people using winget, Microsoft Store or other installation methods on each release
This is due to the Update Notification being shown & whilst useful this can also be a frustration too. This is documented in [about_Update_Notifications](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.2) & can be disabled if you wanted as documented.

As @jhoneill mentioned there are steps where _some_ human interaction is unfortunately still needed for now in downstream feeds (like WinGet/MS Store/MS Update etc) which makes this a reoccurring issue. Some of this is not fully automatable and is already on the radar of the PowerShell Team, Maintainers & community as well as other partner teams like Winget, Microsoft Store, Microsoft Update & 3rd party teams like chocolately etc etc

This is a hard issue to solve & we can only ask for patience whilst all involved do our best to either resolve this or make it less frustrating going forward.

For now I think the 'resolution-duplicate' label is best as we know of this issue from previous releases, and I know from them all that the team are trying to get this to not be a reoccurring issue going forward, however this **will** take some time.

@StevenBucher98 What's your thoughts on the above? I did a search and found that you currently have #19528 assigned for releases to the MS Store but I think some of this is also contained more widely in #16370 which is currently assigned to @adityapatwardhan & likely lots of other overlap elsewhere too 

I added an issue in the winget-cli that may help going forward [Add a check for a PR for a listing of a tool installed by winget that is waiting to be merged in feeds packages repo](https://github.com/microsoft/winget-cli/issues/3443) - if you think that would help not only here but for other tools installed by winget then please upvote it 🙂

**Comment by kapsiR** [comment] 2023-07-17 18:57
@kilasuit Thanks for the explanation here. 

Is there anything in consideration to make the update notification depending on the installation method? (e.g. looking up winget packages instead the pwsh release on GitHub)

**Comment by kapsiR** [comment] 2023-07-18 05:33
Just to let anyone know, [the update is available now](https://github.com/microsoft/winget-pkgs/pull/112154).

**Comment by StevenBucher98** [comment] 2023-07-19 20:35
We will look at if there is a better automated way to publish to WinGet but it is correct that there is human steps for this release method which cause a slight delay from the GitHub Releases.

**Closed** 2023-07-20 23:07 UTC
Labels: Resolution-Duplicate, Needs-Triage

**Comment by HSouhaib** [comment] 2023-07-29 09:30
If you are downloaded both PowerShell and Powershell 7 from Microsoft Store just uninstall PowerShell and the problem will be solved 
PS : it worked for me .

**Comment by csrc** [comment] 2024-01-30 01:38
> If you downloaded both PowerShell and Powershell 7 from Microsoft Store just uninstall PowerShell and the problem will be solved PS : it worked for me .

+, uninstall 7.3 from control panel
