### ISSUE TITLE
Minimal view in Write-progress should not depend on code page settings

### ISSUE THREAD

**Issue by kimipsen** [PowerShell/PowerShell#18373] opened 2022-10-25 07:49 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When trying to output unicode characters with Write-Progress, they all show up as `?`-marks. Using the same text/variable with Write-Host works fine.

### Expected behavior

```console
$str = '🦄❤️🌈阳山伟伟'
$count = 1
While ($count -lt 100) {
	Write-Progress -Status $str -PercentComplete $count -Activity "`u{1F4A9}"
	$count++
	Start-Sleep -Milliseconds 10
}
```

### Actual behavior

```console
Both -Status and -Activity texts output `?` instead of the actual characters.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/11664553/197714416-b7989fcc-9847-4613-bac3-c8efe2c0fe40.png)

**Comment by 237dmitry** [comment] 2022-10-25 08:35
![Screenshot 2022-10-25 113418](https://user-images.githubusercontent.com/78153320/197725053-a38d977a-c875-42d1-b26a-8806d71046ab.png)

**Comment by jhoneill** [comment] 2022-10-25 09:02
There is  / was a known problem with percent complete in write progress  - IIRC it is fixed in 7.3 preview  and it causes strings to be truncated. This looks like 0x1f4a9  will be UTF 16 encoded over two 16-bit words and if the truncation happens in the wrong place I think it will give the result shown.   @237dmitry  Is it working for you on 7.3 preview ?

**Comment by 237dmitry** [comment] 2022-10-25 09:32
> Is it working for you on 7.3 preview ?

pwsh: 7.2.7
Window Terminal: 1.16.2642.0
OS: Win 11 22H2
OS locale: UTF8

In conhost works too but emojies are monochrome.

**Comment by jhoneill** [comment] 2022-10-25 10:36
Yeah I've just tried it in a couple of versions, I can't repro the original symptoms.

**Comment by kimipsen** [comment] 2022-10-25 16:43
I am really sorry to have waisted time on this issue - based on @237dmitry 's answer with extra debug information, it turns out I was missing this setting in windows for it to work:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/11664553/197832956-c4c838b9-6861-4665-b9b8-674e43bc6a9b.png">

Other than that, I was using a similar setup: 
Windows 11 (22H2, build 22623.870)
pwsh 7.2.7
Windows Terminal 1.15.2875.0. 
OS Locale: Danish.

**Comment by jhoneill** [comment] 2022-10-26 09:18
@kimipsen  Actually that does indicate a problem.  **Can you please edit the title** (see below) And thanks for doing the extra step to find the cause. 

This should not depend on the codepage selected. On one computer I have that setting and can't repro the issue. 
On the computer I am using now (provide by the client I'm working for and set up by their IT people without giving me admin rights) the issue DOES repro and chcp says I'm using code page 437 - just like I used on DOS 3.1 in the 1980s :-)  

There if I select **classic view** for progress
![image](https://user-images.githubusercontent.com/16209593/197982718-145d625c-b3bb-4994-9e44-8220410c7b4a.png)

all good. The terminal , powershell, and Write-Progress can all display UTF 16 strings correctly. 
If I switch to minimal view something like the € sign which is not in code page 437 or the ellipsis (…) which is a two-byte unicode character both cause failures with the **minimal view** 

![image](https://user-images.githubusercontent.com/16209593/197985849-d9767954-8ba0-47da-8913-19e294282be3.png)
 
This issue should be have title like **Minimal view in Write-progress should not depend on code page settings** . It can't output characters which classic view CAN output I would say that is a bug.

**Comment by kimipsen** [comment] 2022-10-26 11:23
@jhoneill Thanks for the great explanation. I did not realize that there are differing views for Write-Progress. I've been experimenting a bit further now that I've atleast gotten unicode characters to show, and ran into this: 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/11664553/198013369-05b30e6d-9f30-42e3-acbc-6ae2e99d16af.png">

```powershell
& {
	$args = @{
		Activity = "Demo"
		Status = "💃🕺💃🕺💃🕺💃🕺"
		PercentComplete = 10
	}

	While ($count -lt 100) {
		Write-Progress @args
		$count++
		Start-Sleep -Milliseconds 100000
	}
}
```
I have a feeling it's also somewhat related to this overall issue. It seems the Write-Progress does not like to draw unicode characters either, when the progress "overlaps".

**Comment by jhoneill** [comment] 2022-10-26 12:38
Yes that is going be part of the same problem.  
Internally .NET strings are UTF16 
Something like 💃 which  0x01f483  can't be represented as a 16 bit number so it becomes two 16 bit ones.  0xd83d
 and 0xdc83   - this range identifies numbers which need to be combined - the we subtract d800 from one and dc00 from the other and the output is 0x10000 + 0x400 * 3d + 83 

When the string with  [0xd83d] [0xdc83] is output it's merged back to  [0x01f483] and  💃  is printed. 
However if something says "I need to insert an ANSI escape Sequence after the first character" then we get  
``` `e[7m   [0xd83d]  `e[0m  [0xdc83]  ```
For reverse, first char,  reset, second char. Which gives nonsense output. This doesn't impact most unicode because most of the characters are 16 bit values, but it will hit unicode emojis

**Comment by SeeminglyScience** [comment] 2022-10-26 20:47
> Yes that is going be part of the same problem. Internally .NET strings are UTF16 Something like 💃 which 0x01f483 can't be represented as a 16 bit number so it becomes two 16 bit ones. 0xd83d and 0xdc83

That's true, but we could also use the `EnumerateRunes` API (or at least just check for surrogate pairs) to determine when to not split a rune with VT escapes. Opening to the Interactive WG

**Comment by theJasonHelmick** [comment] 2023-06-07 20:56
The Interactive Working Group has reviewed this issue and we think this needs further investigation.

**Closed** 2023-12-11 23:49 UTC
Labels: WG-Interactive-Console, Needs-Investigation, Resolution-No Activity
