### ISSUE TITLE
Get-Help on Linux litters remainder of shell space

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2300] opened 2016-09-18 01:40 UTC
Steps to reproduce
------------------

Start PowerShell 6.0.0-alpha.10 under Ubuntu 16.04 /bin/bash.
Get-Help about

Expected behavior
-----------------

List of about_* topics appears.

Actual behavior
---------------

Command line is overwritten and "searching" information is scattered from the command line to the bottom of the shell area.

PS /home/ubuntu> p for about ...                                                                             [ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]                                                                                                                Get-Help                                                                                                    Searching Help for about ...                                                                             [ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]      

Environment data
----------------

```powershell
Name                           Value                                                                    
----                           -----                                                                    
PSVersion                      6.0.0-alpha                                                              
PSEdition                      Core                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                  
BuildVersion                   3.0.0.0                                                                  
GitCommitId                    v6.0.0-alpha.10                                                          
CLRVersion                                                                                              
WSManStackVersion              3.0                                                                      
PSRemotingProtocolVersion      2.3                                                                      
SerializationVersion           1.1.0.1                           
```

**Comment by bcdady** [comment] 2016-10-22 06:08
I see the same symptom on Mac

**Comment by vors** [comment] 2016-10-22 06:24
It's a `Write-Progress` issue. Duplicate of #1625

**Closed by vors** 2016-10-22 06:24 UTC
Labels: Area-HelpSystem
