### ISSUE TITLE
[Pwsh7] Invoke-RestMethod/Invoke-WebRequest don't follow 302 redirects

### ISSUE THREAD

**Issue by RainbowMiner** [PowerShell/PowerShell#14643] opened 2021-01-20 17:19 UTC
## Steps to reproduce

```
Invoke-RestMethod "http://api.zergpool.com/api/status"
```
(same problem happens with `Invoke-WebRequest "http://api.zergpool.com/api/status" -UseBasicParsing`)

## Expected behavior

The functions should follow the 302 redirect to `http://api.zergpool.com:8080/api/status` and return a collection of objects. This works perfect with Powershell 5 and Powershell 6

## Actual behavior

Instead, the command throws an Exception with the following error:

```
302 Found
Found
The document has moved here.
```

I already have tried to set `-MaximumRedirection 5`, just in case, but no change.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment] 2021-01-20 18:45
Close as a duplicate of #14531

**Closed by daxian-dbw** 2021-01-20 18:45 UTC
Labels: Issue-Question
