### ISSUE TITLE
Modules in $PSHome\modules don't load in restricted execution policy

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#1733] opened 2016-08-11 19:31 UTC
## Steps to reproduce

ipmo psreadline
## Expected behavior

the module should load
## Actual behavior

Tells you that you need to change the execution policy.
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.7-378-g86c5d3e4c88fe1489dcb657132e64dd8535da6a1
SerializationVersion           1.1.0.1
PSVersion                      6.0.0-alpha

```

**Comment by mirichmo** [comment] 2016-08-18 17:32
Check if this is a duplicate of #1716

**Comment by mirichmo** [comment] 2016-08-18 18:20
@TravisEz13 Is this a duplicate of #1716?

**Comment by TravisEz13** [comment] 2016-08-18 22:52
No, on Windows PowerShell these modules load even in restricted execution policy.  So it is not a duplicate.

**Comment by charub** [comment] 2016-09-28 17:13
Closing as this is a duplicate of #1716

**Comment by TravisEz13** [comment] 2016-09-28 21:25
These issues are not duplicate.  Built-in Powershell modules should load even with restricted policy.  Even if it is not the duplicate.

**Comment by joeyaiello** [comment] 2017-05-23 21:56
This is fixed now on `6.0.0-beta.1`:

```powershell
Set-ExecutionPolicy Restricted
rmo psreadline
ipmo psreadline
Get-PSReadlineOption

EditMode                               : Windows
...
```

**Closed** 2017-05-23 21:56 UTC
Labels: Area-Engine, BVT/DRT, Resolution-Fixed
