### ISSUE TITLE
Custom foreground color for Write-Host

### ISSUE THREAD

**Issue by Kudostoy0u** [PowerShell/PowerShell#14588] opened 2021-01-10 03:29 UTC
## Be able to output text with any foreground color in the RGB spectrum. 

Here's an example.
Powershell supports basic colors such as red, blue, green, etc.
You can create dark gray text with `Write-Host "this is red text" -Fore DarkGray
But it isn't very dark in my opinion. What if you wanted it to be closer to the color of black?
Or what if you wanted a light red? Or just plain pink?
I would like this to be an easy to implement feature for powershell. 
Thank you.

**Comment by HumanEquivalentUnit** [comment] 2021-01-12 09:54
Possible duplicate of #11231 and thereby #2381

@Kudostoy0u it's possible - if you have a terminal which supports ANSI escape codes. It's not easy to implement for PowerShell because of backwards compatibility and terminal / Windows API / .Net / cross-platform compatibility.

ANSI escape codes are supported in [Windows 10 build 18298 console](https://devblogs.microsoft.com/commandline/new-experimental-console-features/) and [Windows Terminal](https://devblogs.microsoft.com/commandline/introducing-windows-terminal/) and there are some examples [here](https://duffney.io/usingansiescapesequencespowershell/#8-bit-256-color-foreground-background) and [here](https://stackoverflow.com/questions/56679782/how-to-use-ansi-escape-sequence-color-codes-for-psreadlineoption-v2-in-powershel) about using them for more colours and 24-bit colours.

e.g.

```powershell
PS C:\> $e = [char]0x1b
>> "$e[38;2;255;128;128;48;2;128;0;255;4mtest$e[0m"
test    # in pink and purple and underlined
```

**Closed** 2021-01-17 18:29 UTC
Labels: Issue-Enhancement, WG-Interactive-Console

**Comment by poidah** [comment] 2023-02-06 22:56
The request for HEX colours for the Write-Host command has been **around since 2016!**

In 7 years nothing has been done :(

If you want this please comment on the thread below....

[Link to related post](https://github.com/PowerShell/PowerShell/issues/16441#issuecomment-1419894235)

**Comment by Jaykul** [comment] 2023-02-09 04:29
Just download the PANSIES module, @poidah 😉
