### ISSUE TITLE
Notarization for PowerShell's macOS versions.

### ISSUE THREAD

**Issue by onePW** [PowerShell/PowerShell#16467] opened 2021-11-14 01:33 UTC
### Summary of the new feature / enhancement

Hello Devs and management:

I'm certain many macOS users would appreciate notarization of the macOS PowerShell installers and the resulting installed PowerShell files.

I realize this would mean troublesome additional financial cost and ongoing attention for the developer(s).

All this comes with some doubt this adds substantially to the security we need.

Thank you always for the macOS versions and for your consideration.

onePW

**Comment by daxian-dbw** [comment] 2021-11-15 20:26
Close as a duplicate of #10141

**Closed by daxian-dbw** 2021-11-15 20:26 UTC
Labels: Issue-Question, Area-Maintainers-Build, Needs-Triage
