### ISSUE TITLE
Space charter displayed as Unicode text

### ISSUE THREAD

**Issue by minecraftchest1** [PowerShell/PowerShell#13057] opened 2020-06-30 00:05 UTC
When typing in pwsh.exe, the space charter is displayed as what I believe is the Unicode code.
## Steps to reproduce

```
Download Powershell core binary archive to a windows machine, extract, run pwsh.exe, and type some commands including a space character. 
```

## Expected behavior

```
Space character is displayed as an empty space in input.

```

## Actual behavior

```
←[104m is displayed.
```
![image](https://user-images.githubusercontent.com/42992675/86067349-4ebb7900-ba3a-11ea-8192-719f62913620.png)

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 6.1.7601 Service Pack 1
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
The text is not removable with backspace.
Copying and pasting generates the same problem.
[Test-6.29.2020.zip](https://github.com/PowerShell/PowerShell/files/4848601/Test-6.29.2020.zip)
Open included file in IE.

**Comment by HumanEquivalentUnit** [comment] 2020-06-30 20:40
This `[104m` looks like an escape sequence used for terminal instructions like changing colour of text, e.g. "dotnet" is yellow in your screenshot, so there will be a "change colour to yellow" sequence before it, and a "change colour back to white" after it. This `[104m` is not being handled correctly and is breaking through where it shouldn't.

`\e[0;104m` is close to it, and would be setting an intense blue background, which you have as the background colour in your screenshot. So maybe that's what it is supposed to say, and has a missing `0;` in it, so it's not handled as a colour, and is being printed as text.

Tracking where it's coming from would help; things you could try:

- `Remove-Module PSReadline` - does it still happen after that? this enhances the prompt, and is involved in some colour settings. (This will only temporarily remove it, get it back by closing / restarting PowerShell).
- `Get-Module` will list running modules; can you share the list? One of them might be causing this.
- `Get-Content $Profile` is the scripts running at PowerShell startup, if you have customised it, it might be loading something which affects this.
- Starting a command prompt, and then running `pwsh` inside it and seeing if it still happens in a more basic terminal.

>  the space charter is displayed as what I believe is the Unicode code.

If it was a Unicode space, it would look the same as any other space; Unicode was built so that all the basic English letters, numbers and symbols from American (ASCII) computers would be the same.

**Comment by minecraftchest1** [comment] 2020-06-30 21:08
The problem only happens when running the executable directly. Changing to the binaries directory in cmd.exe, or powershell.exe, then running pwsh.exe does not give me the problem.

Removing the module PSReadline fixes the problem when running the executable directly.

I will fun the other commands and post the output when I get the time.

**Comment by HumanEquivalentUnit** [comment] 2020-07-01 00:41
Ah, it's a PS Readline thing; are you running Windows 8?   I think it's this issue: https://github.com/PowerShell/PSReadLine/issues/1508 and https://github.com/PowerShell/PowerShell/issues/11685#issuecomment-622335472

**Comment by minecraftchest1** [comment] 2020-07-01 00:43
Windows 7.
We will upgrade to 10 eventually when we get the money. We got most of our computers used after the free upgrade.

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-01 05:28
Both `\e[104m` and `\e[0;104m` should select blue as the background color. The difference is that `\e[0;104m` also resets the foreground color, font weight, underlining, etc. to defaults. But the console in Windows 7 supports neither of these.

**Comment by minecraftchest1** [comment] 2020-07-01 14:29
Ok. I will keep the module from loading on startup. I just think it's funny though that running it from a cmd or Windows Powershell session works just fine though. Maybe it's a bug. (Wink.)

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2020-07-01 14:30 UTC
Labels: Area-PSReadLine, Issue-Question

**Comment by eabase** [comment] 2020-10-17 23:11
Not sure why this was closed.

I have the same problem with latest `Pwsh 7.1.0-rc.1` on Win8.1, but with Pwsh 6.1.1 it works fine.

**Comment by minecraftchest1** [comment] 2020-10-17 23:30
If I remember right, I closed it because their was a workaround, or because it was because PWSH was using a feature not available in Windows 7.
But it has been a long time since I closed it.

**Comment by eabase** [comment] 2020-10-18 00:10
If you look at [here](https://github.com/PowerShell/PSReadLine/blob/219ffa17c2a4b4f5cb879b96b68c8662e1548ef7/PSReadLine/Cmdlets.cs#L1081) at the `BackgroundColorMap` , there is definitely something fishy with the `Blue` and perhaps the regex handling of `AnsiReset = "\x1b[0m";` which can be shorter (as `\x1b[m`) than the minimum as mentioned in code comments. 

https://github.com/PowerShell/PowerShell/issues/11685#issuecomment-711093883

**Comment by daxian-dbw** [comment] 2020-10-30 20:10
This should be a duplicate of https://github.com/PowerShell/PSReadLine/issues/1508
