### ISSUE TITLE
CLRVersion is missing in $PSVersionTable

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#1984] opened 2016-08-20 19:40 UTC
```
PS C:\Users\Joel> $PSVersionTable                          

Name                           Value                       
----                           -----                       
WSManStackVersion              3.0                         
PSRemotingProtocolVersion      2.3                         
PSEdition                      Core                        
BuildVersion                   3.0.0.0                     
GitCommitId                    v6.0.0-alpha.9              
CLRVersion                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}     
PSVersion                      6.0.0-alpha                 
SerializationVersion           1.1.0.1                                                                                
```

Really nothing more to say here. 😱

**Comment by rkeithhill** [comment] 2016-08-20 19:44
Also, that `GitCommitId` looks more like a `GitCommitTag` - minor but I guess I would expect an Id to be a SHA1 string.

**Comment by jpsnover** [comment] 2016-08-20 22:07
This is a test
http://giphy.com/gifs/editingandlayout-ly8G39g1ujpNm

**Comment by jpsnover** [comment] 2016-08-20 22:10
This is a test
![jim](https://cloud.githubusercontent.com/assets/6188114/17834136/3db2c810-66e8-11e6-965d-3a579510ffd0.gif)

**Comment by iSazonov** [comment] 2017-04-12 15:39
What is "CLRVersion'? In Windows PowerShel it is `[Environment]::Version`.  Today [it is hardcoded](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L360) "4.0.30319.42000"
I believe we should restore it for backward compatibility.
And the next question is whether we need something else useful here? 
- NetCoreApp ?
- real CLR version? There is no native way to get it https://github.com/dotnet/coreclr/issues/8815 
[Comment](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L360) : 
>Starting with 4.6 we switched to a file versioning

So we would read the version from coreclr.dll - how to find it?

**Comment by iSazonov** [comment] 2017-04-13 09:50
@SteveL-MSFT It seems a question for @powershell-committee

**Comment by SteveL-MSFT** [comment] 2017-04-13 17:57
Dupe of https://github.com/PowerShell/PowerShell/issues/1395

**Closed by SteveL-MSFT** 2017-04-13 17:57 UTC
Labels: Area-Engine, Resolution-Duplicate
