### ISSUE TITLE
Background color goes beyond prompt after program execution

### ISSUE THREAD

**Issue by Neur1n** [PowerShell/PowerShell#14686] opened 2021-02-01 14:21 UTC
## Steps to reproduce

```powershell
Invoke-Module 'PSReadLine'

function OnViModeChange {
  if ($args[0] -eq 'Command') {
    $script:vicolor = [ConsoleColor]::Red
  } else {
    $script:vicolor = [ConsoleColor]::Green
  }
  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}

Set-PSReadLineOption -EditMode Vi
Set-PSReadLineOption -ExtraPromptLineCount 2
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $Function:OnViModeChange

function Prompt {
  $Prompt = Write-Prompt "`n"
  $Prompt += Write-Prompt "`n DEBUG" -BackgroundColor $script:vicolor
  $Prompt += Write-Prompt ">" -ForegroundColor $script:vicolor
  if ($Prompt) { "$Prompt " } else { " " }
}
```

## Expected behavior

```none
Background color stops at the last character of the prompt.
```

## Actual behavior

```none
When I run a program (say "some_app.exe") in pwsh and quit, the background color goes beyond the prompt as shown:
```

![image](https://user-images.githubusercontent.com/17579247/106470574-9d068e00-64db-11eb-9cdd-70e198d1fa84.png)
![image](https://user-images.githubusercontent.com/17579247/106470540-8f510880-64db-11eb-96a3-c9138e6f30ef.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Neur1n** [comment] 2021-02-02 06:35
So I tested using different colors for the colored characters:
![image](https://user-images.githubusercontent.com/17579247/106561560-e00c4400-6563-11eb-8d84-6193a4dbf53c.png)

**Comment by daxian-dbw** [comment] 2021-02-02 17:49
@Neur1n The repro steps you provided don't work. `Invoke-Module` and `Write-Prompt` are both not defined. Please update your repro steps.

**Comment by Neur1n** [comment] 2021-02-03 01:30
Sorry, here is the minimal configuration:

```powershell
function Invoke-Module ($name) {
  if (Get-Module -ListAvailable -Name $name) {
    Import-Module $name
  } else {
    Write-Host 'Installing missinged module ' $name '...'
    Install-Module $name -Scope CurrentUser -AllowPrerelease -Force
  }
}

Invoke-Module 'posh-git'
Invoke-Module 'PSReadLine'

$script:indicator = ''  # u+e0b0
$script:vimode = '[I]'
$script:vicolor = [ConsoleColor]::Green

function OnViModeChange {
  if ($args[0] -eq 'Command') {
    $script:vimode = '[N]'
    $script:vicolor = [ConsoleColor]::Red
  } else {
    $script:vimode = '[I]'
    $script:vicolor = [ConsoleColor]::Green
  }

  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}

Set-PSReadLineOption -EditMode Vi
Set-PSReadLineOption -ExtraPromptLineCount 2
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $Function:OnViModeChange

function Prompt {
  $Prompt = Write-Prompt "`n"
  $Prompt += & $GitPromptScriptBlock
  $Prompt += Write-Prompt "`n $script:vimode" -BackgroundColor $script:vicolor
  $Prompt += Write-Prompt "$script:indicator" -ForegroundColor $script:vicolor
  if ($Prompt) { "$Prompt " } else { " " }
}
```

**Comment by mklement0** [comment] 2021-02-03 04:19
Having only glanced at this, I wonder if it is a duplicate of #14506

**Comment by Neur1n** [comment] 2021-02-03 07:57
I tried running `Write-Warning foo; 'bar'` as mentioned in #14506, but it did not reproduce my issue. Thanks though.

**Comment by stanciuadrian** [comment] 2021-05-08 18:00
Not sure if related but I get the same kind of behavior with C# code ran in a PowerShell (Core & Legacy) console. 

```csharp
Console.BackgroundColor = ConsoleColor.Red;
Console.ForegroundColor = ConsoleColor.Black;
Console.Write("Hello World!");
Console.ResetColor();
Console.WriteLine();
```

Executing `dotnet run` in PowerShell gives the expected behavior:

![image](https://user-images.githubusercontent.com/2334569/117548784-7ce8ec80-b03f-11eb-8970-0bacdff8b107.png)

After resizing the shell window I get a full red line:

![image](https://user-images.githubusercontent.com/2334569/117548805-a3a72300-b03f-11eb-8f3c-3d16862dc9ec.png)

**Comment by theJasonHelmick** [comment] 2023-01-18 21:21
@Neur1n - Thank you for reporting this issue.  The working group discussed this and .NET team has updated the terminal to resolve this type of error.  https://github.com/microsoft/terminal/issues/11742

After testing, we could not reproduce in the latest terminal and suggest you attempt the operation again with the latest version of Terminal.

**Comment by Neur1n** [comment] 2023-01-19 02:01
> @Neur1n - Thank you for reporting this issue. The working group discussed this and it turns out to be an issue with Windows Terminal, which has been fixed in the latest WT preview: [microsoft/terminal#11742](https://github.com/microsoft/terminal/issues/11742)
> 
> After testing, we could not reproduce in the latest terminal and suggest you attempt the operation again with the latest version of Terminal.

Thanks for your effort! However, it seems that this issue starts to occur when the prompt hits the last line of the terminal (I'm using WT preview `1.16.3463.0`):

1. Things go as expected so far
![image](https://user-images.githubusercontent.com/17579247/213337785-dae52a9d-7ebd-47dd-9cb0-14e7f98ebf96.png)
2. Issue starts to occur
![image](https://user-images.githubusercontent.com/17579247/213337911-0577d3ba-297d-490f-9d10-d8fc3577b8c4.png)
3. And continues
![image](https://user-images.githubusercontent.com/17579247/213337940-60f53c37-f0b9-4111-8711-518e705ddc2a.png)

**Comment by daxian-dbw** [comment] 2023-01-19 05:40
@Neur1n Had the issue always happened when the prompt hit the last line of the terminal, or that's only the case with the latest WT version? I'm asking because I want to understand whether this is still a variant of the linked Windows Terminal issue.

Your prompt configuration is too complex to reason what might be the cause -- several factors in play: `posh-git`, `PSReadLine`, the `VI` edit mode, and the Windows Terminal (_by the way, `Write-Prompt` and `$GitPromptScriptBlock` are still missing from your scripts above_). Can you maybe provide a simplified repro? For example, does this repro when not using `posh-git`? Or when not having PSReadLine imported (you can archive this by starting pwsh by `pwsh -noprofile -noninteractive`)?

**Closed** 2023-01-27 04:00 UTC
Labels: WG-Interactive-Console, Waiting on Author, Needs-Triage, Needs-Repro

**Comment by Fred-Vatin** [comment] 2023-01-27 20:53
Reopen

**Comment by Neur1n** [comment] 2023-01-28 01:54
Sorry about my late response. My minimal ps1 file to reproduce the issue:

```ps1
function Invoke-Module ($name) {
  if (Get-Module -ListAvailable -Name $name) {
    Import-Module $name
  } else {
    Write-Host 'Installing missinged module ' $name '...'
    Install-Module $name -Scope CurrentUser -AllowPrerelease -Force
  }
}

Invoke-Module 'PSReadLine'

$script:indicator = ''
$script:vimode = '[I]'
$script:vicolor = [ConsoleColor]::Green

function OnViModeChange {
  if ($args[0] -eq 'Command') {
    $script:vimode = '[N]'
    $script:vicolor = [ConsoleColor]::Red
  } else {
    $script:vimode = '[I]'
    $script:vicolor = [ConsoleColor]::Green
  }

  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}

Set-PSReadLineOption -EditMode Vi
Set-PSReadLineOption -ExtraPromptLineCount 2
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $Function:OnViModeChange

function Prompt {
  $Prompt = Write-Prompt "`n"
  $Prompt += & $GitPromptScriptBlock
  $Prompt += Write-Prompt "`n $script:vimode" -BackgroundColor $script:vicolor
  $Prompt += Write-Prompt "$script:indicator" -ForegroundColor $script:vicolor
  if ($Prompt) { "$Prompt " } else { " " }
}
```
