### ISSUE TITLE
Invoke-WebRequest does not return result for redirect

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/PowerShell#5748] opened 2017-12-27 15:01 UTC
Steps to reproduce
------------------

```powershell
Invoke-WebRequest http://www.example.com -MaximumRedirection 0 -ErrorAction SilentlyContinue
```

Expected behavior
-----------------

This is what I get on PS 5.1

```none
StatusCode        : 301
StatusDescription : Moved Permanently
Content           : <html>
                    <head><title>301 Moved Permanently</title></head>
                    <body bgcolor="white">
                    <center><h1>301 Moved Permanently</h1></center>
                    <hr><center>nginx/1.10.3 (Ubuntu)</center>
                    </body>
                    </html>

RawContent        : HTTP/1.1 301 Moved Permanently
                    Connection: keep-alive
                    Keep-Alive: timeout=5
                    Content-Length: 194
                    Content-Type: text/html
                    Date: Wed, 27 Dec 2017 14:53:23 GMT
                    Location: https://www.example.com/
                    Serv...
Forms             : {}
Headers           : {[Connection, keep-alive], [Keep-Alive, timeout=5], [Content-Length, 194], [Content-Type, text/html]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 194
```

Actual behavior
---------------

This is what I get on PS 6.0.0-rc2

It ignores the ErrorAction flag and fails to return the 301 page.

```none
Invoke-WebRequest :
301 Moved Permanently
301 Moved Permanently
nginx/1.10.3 (Ubuntu)
At line:1 char:1
+ Invoke-WebRequest http://www.example.com -MaximumRedirection 0 -ErrorAc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2017-12-27 15:03
This is a duplicate of #4534

**Comment by MartinSGill** [comment] 2017-12-27 15:56
Sorry... I did look for duplicates, but missed that one.

**Comment by markekraus** [comment] 2017-12-27 16:52
@MartinSGill No problem. The title on the other issue is a bit vague so it's easy to miss the correlation.

**Comment by iSazonov** [comment] 2017-12-27 17:30
Leave a comment

**Closed by iSazonov** 2017-12-27 17:30 UTC
Labels: Area-Cmdlets-Utility, Resolution-Duplicate
