### ISSUE TITLE
Crash with unhandled System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read

### ISSUE THREAD

**Issue by marryton007** [PowerShell/PowerShell#16159] opened 2021-09-27 04:08 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. run [scrcpy](https://github.com/Genymobile/scrcpy) in PowerShell command line.
2. close the  [scrcpy](https://github.com/Genymobile/scrcpy)  window
3. press the Enter key a few more times.
3. wait a few moments.
4. Powershell crashed

### Expected behavior

```console
Don't crash.
```

### Actual behavior

```console
It crashed.
```

### Environment data

```powershell
C:\Users\marry> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![powercore-error](https://user-images.githubusercontent.com/2311328/134844071-0594068f-4bc8-4328-886c-925c7c5e791a.png)

**Comment by iSazonov** [comment] 2021-09-27 04:52
Please check with latest PowerShell 7.2 Preview build.

**Comment by marryton007** [comment] 2021-09-27 09:19
I have tested on 7.2 Preview, it crashed too.

![image](https://user-images.githubusercontent.com/2311328/134880744-a11c8fc9-9a4d-4bca-accd-f706c1f8f27d.png)

**Comment by vexx32** [comment] 2021-09-27 12:24
That kinda sounds like the application you're running is closing the console handle when it shouldn't be 🤔 

Very odd behaviour.

**Comment by daxian-dbw** [comment] 2021-11-11 22:44
This is likely a duplicate of #11215, whose root cause lies in .NET: https://github.com/dotnet/runtime/issues/59059

**Closed** 2021-11-13 01:00 UTC
Labels: WG-Interactive-PSReadLine, Resolution-External, WG-Engine-Pipeline
