### ISSUE TITLE
While debugging, sometimes won't cancel, and "accepting"

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#5374] opened 2017-11-08 01:05 UTC
_From @lzybkr on November 2, 2015 18:52_

To repro:

```
PS> function foo {}
PS> sbp -command foo
PS> foo
[DBG]: PS>> (@($availableModules | ?{ $_.SessionState -eq $null
>> }).Count
>>
>> ^C
```

Important to this repro - hit enter _twice_ (so you have one blank line) before hitting Ctrl+c.

After doing this, the command line should be cancelled, but it isn't, and figuring out how to fix the error might be hard, it's sometimes easiest to just exit PowerShell at that point.

_Copied from original issue: lzybkr/PSReadLine#299_

**Comment by lzybkr** [comment] 2017-11-08 01:07
The bug is [here](https://github.com/PowerShell/PowerShell/blob/fe3e44f3055ccd57e19ce1d29a5320e2f3891705/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L2472) - the call to `Trim` removes whitespace at the end of the command line.

PSReadLine accepted the input because there were no `IncompleteParseException`s, but after the call to `Trim`, there will be an `IncompleteParseException`.

I'd just remove the call to `Trim`, but @PaulHigin should own this issue.

**Comment by PaulHigin** [comment] 2017-11-10 16:44
I don't recall any particular reason for the Trim() call.  So we can try just removing it.

**Comment by joeyaiello** [comment] 2019-01-02 21:43
@SteveL-MSFT or @PaulHigin : came across this one while investigating another issue, but it doesn't appear to repro in `6.2.0-preview.3`. 

Would one of you mind validating that and closing this? Thanks!

**Comment by lzybkr** [comment] 2019-01-03 00:58
The problematic code I pointed to is still present and the bug still repros with 6.2.0-preview-3.

**Comment by vexx32** [comment] 2019-01-03 01:54
@lzybkr is there any way to construct a test for this to prevent regressions? It looks like a pretty simple fix at the surface, but it might be a good idea to try to test for things like this... if we even _can_, that is.

**Comment by lzybkr** [comment] 2019-01-03 16:45
There's always a way, but sometimes it's more effort than it's worth.

Automated interactive testing is the obvious approach, maybe with something like [expect](https://www.tcl.tk/man/expect5.31/expect.1.html) or [await](https://www.powershellgallery.com/packages/Await/0.8).

An alternative is to simply call all of the right apis in sequence, I'm pretty sure that's possible. It might require simulating a little bit of PSReadLine, but maybe not.

**Closed** 2019-01-06 02:47 UTC
Labels: Area-Debugging, Issue-Bug
