### ISSUE TITLE
Some rows are invisible in output of long string of «Select-String»

### ISSUE THREAD

**Issue by u20221022** [PowerShell/PowerShell#19231] opened 2023-02-26 23:46 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Host

Name             : ConsoleHost
Version          : 7.3.3
InstanceId       : b895a510-c2ac-4215-92f1-de9fcfe0c309
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : ru-RU
CurrentUICulture : ru-RU
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


"12" + "1"*((((Host).UI.RawUI.WindowSize.Width - 1) * 3) - 2) | Select-String -Pattern "2"

12111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

"12" + "1"*((((Host).UI.RawUI.WindowSize.Width - 1) * 3) - 1) | Select-String -Pattern "2"

12111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

1
```

### Expected behavior

```console
All rows are visible.
```

### Actual behavior

```console
All rows are invisible except the first, second, and last rows.
```

### Error details

```console
Exception             :
    Type    : System.InvalidOperationException
    Message : You must specify an object for the Get-Member cmdlet.
    HResult : -2146233079
CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
InvocationInfo        :
    MyCommand        : Get-Member
    ScriptLineNumber : 1
    OffsetInLine     : 18
    HistoryId        : 31
    Line             : (Host).UI.Name | Get-Member
    PositionMessage  : At line:1 char:18
                       + (Host).UI.Name | Get-Member
                       +                  ~~~~~~~~~~
    InvocationName   : Get-Member
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![2023-02-27_2-28-12](https://user-images.githubusercontent.com/117870409/221444582-4e44391e-b7b9-4ff5-923a-5f2d378c25cb.png)

**Comment by mklement0** [comment] 2023-02-26 23:59
`Host` is an attempt to call a _command_ by that name (which doesn't exist by default on Windows). Did you mean to use `$host`?

Also, please format the code (in the "Steps to reproduce" section) properly.

**Comment by u20221022** [comment] 2023-02-27 00:04
> `Host` is an attempt to call a _command_ by that name (which doesn't exist by default on Windows). Did you mean to use `$Host`?

Yes.  My memory failed.

> please format the code (in the "Steps to reproduce" section) properly

I do not understand.

**Comment by mklement0** [comment] 2023-02-27 00:13
@u20221022  - sorry, my bad: `Host` _does_ work on Windows, because it calls `Get-Host` using the _default-verb_ feature, which, however is best avoided - see https://github.com/PowerShell/PowerShell/issues/3987#issuecomment-308279494. On _Unix_-like platforms, `host` refers to an _external program_, namely `/usr/bin/host` (a DNS lookup utility).

> I do not understand.

Look at the formatting of your commands in your initial post.
Use ```` ```....``` ```` code blocks, for instance.

**Comment by u20221022** [comment] 2023-02-27 00:20
So? I already have sclerosis.

**Comment by mklement0** [comment] 2023-02-27 02:09
> So? I already have [sclerosis](https://www.merriam-webster.com/dictionary/sclerosis).

I am sorry to hear that. I hope you feel better soon.

**Comment by u20221022** [comment] 2023-02-27 05:49
> I am sorry to hear that. I hope you feel better soon.

I am >60 years old. It is time already.
And I do not use the variable «$Host» very often.  Confused in a hurry.  First, I found this bug in Visual Studio in my script.  Then I noticed that the width of the window is important and began to remember how to determine it.

**Comment by 237dmitry** [comment] 2023-02-27 06:37
Perhaps some escape sequences are interrupting the output. The result is displayed in full with the `-Raw` switch.

**Comment by u20221022** [comment] 2023-02-27 07:03
The simple string `"1" * 999` is also normally displayed. But I will not figure it out on my own.
The first, second, and last rows are visible.  Why not the first and last?  Why not `[-2]`, if second?

**Comment by u20221022** [comment] 2023-02-27 07:13
Similarly:
`"1a", "2b", ("3c"+"f"*400), "4d", ("5e"+"g"*500) | Select-String -Pattern "\d"`

**Comment by 237dmitry** [comment] 2023-02-27 08:01
This happens if the output type is matchinfo. If a string, then there are no breaks in the output.
```
("12" + "1"*((((Host).UI.RawUI.WindowSize.Width - 1) * 3) - 2) | Select-String -Pattern "2").Line
"12" + "1"*((((Host).UI.RawUI.WindowSize.Width - 1) * 3) - 2) | Select-String -Pattern "2" -raw 
```

**Comment by kasini3000** [comment] 2023-02-27 09:25
![a1](https://user-images.githubusercontent.com/65390418/221524694-3148e7c4-353a-4183-a090-e684dca072fb.jpg)

![a2](https://user-images.githubusercontent.com/65390418/221524747-9b4908d8-ca1d-4522-837f-f1c57a9054bd.jpg)

**Comment by jhoneill** [comment] 2023-02-27 12:32
This looks to be a regression in 7.3.3 it seems OK in 7.3.2 (for reasons I don't understand - I haven't been prompted to upgrade). 

The 7.2.1. Version @kasini3000  posted a screen shot of appears not to allow for some characters being non printing which seems to to be fixed in 7.3.2 - the line missing only seems to come in after 7.3.2 - in 7.3.3 according to the OP and in 7.4 preview from @kasini3000 's screen shot.

**Comment by u20221022** [comment] 2023-02-27 12:32
@kasini3000
I did not pay attention to the places in the previous version that you marked with red arrows. Thank you.

**Comment by u20221022** [comment] 2023-02-27 12:40
> The 7.2.1. Version @kasini3000 posted a screen shot

7.2.10.  Zero is missing.

**Comment by u20221022** [comment] 2023-02-27 12:49
> This happens if the output type is matchinfo. If a string, then there are no breaks in the output.

I can not make the title that reflects all the details, sorry.  Make it, if you can.

**Comment by mklement0** [comment] 2023-02-27 13:36
@u20221022, just to clarify:

* I accidentally created a distraction regarding `host` vs. `$host` (`host` doesn't work on my macOS machine, because it refers to standard utility `/usr/bin/host` there). To close this tangent, as a general recommendation: it's both simpler and more robust to use `$host`. (On Windows, in the absence of a command that has this exact name, `host` is interpreted as `Get-Host`, which is simply the command equivalent of the automatic `$host` variable, but this default-verb logic is best avoided).

* What is implied by @237dmitry's observation is that the problem is related to the predefined formatting data associated with `Select-String`'s output data type,  [`Microsoft.PowerShell.Commands.MatchInfo`](https://learn.microsoft.com/en-US/dotnet/api/Microsoft.PowerShell.Commands.MatchInfo), which can be examined (although not in a friendly manner) with `Get-FormatData Microsoft.PowerShell.Commands.MatchInfo | Format-Custom -Depth 8`. 
  * By contrast, `[string]` instances (which is what you get with `-Raw` or `(...).Line`) always print as-is, with no formatting applied (the line breaks are then "soft" ones made by the _terminal_).

The strange thing is that I cannot reproduce the symptom, neither in 7.3.3 nor in v7.4.0-preview.1, neither with your command, nor with @kasini3000's (whose screenshot shows _correct_ behavior in these versions, and only a problem in v7.2.10).

I wonder if the what the _current culture_ is somehow plays a role.`$PSCulture` is `en-US` for me.

If I'm reading the formatting data correctly the implementation (which I haven't looked at) is at https://github.com/PowerShell/PowerShell/blob/fe5f43cdc30ae5e353d3dc6a18747b9d632df811/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L302

**Comment by u20221022** [comment] 2023-02-27 14:32
> I wonder if the what the _current culture_ is somehow plays a role.

As shown at first picture, `$Host.CurrentCulture` and `$Host.CurrentUICulture` is «ru-RU».  But what culture do decimal digits (from my example) belong to?

Host vs $Host
This is my mistake because of the rush. How many times do I need to apologize?

[String] vs [MatchInfo]
I do not need plain text. I want to see exactly where the found areas are located. This can be done in color by `Write-Host`, but `Select-String -AllMatches` is easier (if it does work).

**Comment by 237dmitry** [comment] 2023-02-27 15:36
> But what culture do decimal digits (from my example) belong to?

Culture describes the formats, not the numbers themselves.

> I do not need plain text. I want to see exactly where the found areas are located.

Default settings does this. Try without profile `pwsh -nop` and execute your example.

**Comment by mklement0** [comment] 2023-02-27 15:36
> This is my mistake because of the rush. How many times do I need to apologize?

You don't need to apologize. 
It was I who apologized, for having introduced a distraction, given that your command _does_ work on Windows. 
(In the context of clarifying that, I offered the suggestion to use `$host` in the future).

>  But what culture do decimal digits (from my example) belong to?

Yes, it seems counterintuitive - but it was the only conspicuous difference between your runtime environment and mine, which is why I mentioned it as a _guess_ - and indeed, the effective culture (but not the active code page) makes a difference, for reasons unknown to me: if I run `Set-Culture ru-RU` and then start a new session, I can now reproduce the problem (more on that later).

> I do not need plain text.

Understood. 
No one was suggesting you should switch to plain-text output.
I was merely explaining the difference between plain-text output and rich formatting of `MatchInfo` objects, so as to point out that the source of the problem must be the latter, in an effort to help diagnose the specific problem.

**Comment by mklement0** [comment] 2023-02-27 15:46
Here's a minimal example with specific reproduction steps, given that that the problem seems to be related to the relationship between the _string length_ and the _window width_, as well as the culture.
(I've tried a few cultures, and `ru-RU` was the only one that surfaced the problem for me. I also tried `Set-Culture zh-Hans`, but this fails to switch to that culture - not sure why.) 

The following reproduces consistently for me, in line with @jhoneill's observation: works in 7.2.x, but no longer in 7..3.3 and PowerShell Core 7.4.0-preview.1.

* Unless `$PSCulture` already reports `ru-RU`, run `Set-Culture ru-RU` and _start a new session_.

* Run the following, which makes the window 128 columns wide first (very curiously, using `[Console]::WindowWidth = 128` instead of `mode con cols=128` does _not_ produce the symptoms for me):

```powershell
mode con cols=128; '2' + '1' * 381 | Select-String 2
```

The output will unexpectedly show a blank line before the last line, and the last line ends in a single `1`.
The problem also occurs when `$PSStyle.OutputRendering = 'plaintext'` is in effect.

**Comment by jhoneill** [comment] 2023-02-27 16:05
Just out of curiosity 
if you do 
```
$x = '2' + '1' * 381 | Select-String 2
$x
$x.toString()
$x.ToEmphasizedString()
``` 
We expect the first and last to have the odd behaviour. 

what about 
```
$s = $x.ToEmphasizedString
$s
```
Because it is starting to look to me that the problem is processing certain strings, and by chance it was  `Select-String` that made one of those, not a problem with `Select-String` as such.  I don't like `ToEmphasizedString` - it's moved the formatting out of the format data and into the matchInfo class, BUT it doesn't appear to be the culprit - from looking at   
https://github.com/PowerShell/PowerShell/blob/fe5f43cdc30ae5e353d3dc6a18747b9d632df811/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L302

**Comment by mklement0** [comment] 2023-02-27 16:37
You're right, `$x.ToEmphasizedString('')` (note that it is a _method_ with a required `directory` path argument) does _not_ exhibit the problem, but, given that a `[string]` instance is returned, that is to be expected.

But you're right that that method can't be the culprit then - it must be whatever code ultimately prints the result to the console in the context of in-band formatting, possibly connected to the `CustomControl` formatting type in whose context the method is called.

Curiously, trying to construct a `MatchInfo`  instance from scratch also doesn't produce the symptom for me:

```powershell
$mi=[Microsoft.PowerShell.Commands.MatchInfo]::new(); $mi.Line = '2' + '1' * 381; $mi
```

**Comment by u20221022** [comment] 2023-02-27 19:38
> Try without profile `pwsh -nop` and execute your example.

Start «Cmd.exe», run `pwsh -nop` and my initial examples.  Got the same (with invisible rows) in the «Cmd.exe» window. I did not know it was possible, thank you.

> Culture describes the formats, not the numbers themselves.

Of course, thank you again.

**Comment by u20221022** [comment] 2023-02-27 19:42
> between the _string length_ and the _window width_

Have you noticed that in my example, the window width is 120 characters, and the maximum string length is 119 characters? In the first examples, I subtract one from the width of the window.
Plain text is displayed the full width of the window. I do not know why this is happening.

**Comment by u20221022** [comment] 2023-02-27 19:57
> Just out of curiosity
> if you do

Sorry, I do not know the method «ToEmphasizedString», but at me:
![2023-02-27_22-50-38](https://user-images.githubusercontent.com/117870409/221668772-e7958a51-fa23-40e1-ac29-5c286249f440.png)

**Comment by mklement0** [comment] 2023-02-27 22:15
> Have you noticed that in my example, the window width is 120 characters, and the maximum string length is 119 characters?

Yes, sorry: I see you were way ahead of me there. I got myself distracted over the `host` and culture issue. Your reproducing code works just fine, and doesn't require modifying the window width.

> I do not know why this is happening.

So far we've narrowed it down to (a) affecting the `ru-RU` culture and (b) the _for-display formatting_ associated with `MatchInfo` instances, as output by `Select-String`.

To call `.ToEmphasizedString()`, you must pass it a string (whose value is irrelevant in this case), as shown in my previous comment (e.g., `$x.ToEmphasizedString('')`), but that won't help us, given that strings, as previously explained, print as-is, so you won't see the symptom.

Someone will have to dig into the innards of the formatting system to find the problem, and the culture-sensitivity of the problem is puzzling.

I strongly suspect that the problem is related to the newlines that the formatting system inserts into the line text for line wrapping (which, as mentioned, directly printing the `.Line` property or calling `.ToEmphasizedString('...')` does _not_ do).

Generally speaking, the tricky part of injecting these newlines is to ensure that they're not accidentally injected _in the middle of ANSI escape sequences_ (which are used to highlight the matching part(s) of a line), which would break the formatting.

And, indeed, you can make the problem go away if you add `-NoEmphasis` to the `Select-String` call, which makes `.ToEmphasizedString()` not embed ANSI escape sequences to begin with.
(By contrast, `$PSStyle.OutputRendering = 'plaintext'`  does _not_ prevent their inclusion - it just strips them out later.)

(The absence of ANSI escape sequences in the return value of `.ToEmphasizedString()` is also why the manually constructed `MatchInfo` instance (`$mi=[Microsoft.PowerShell.Commands.MatchInfo]::new(); $mi.Line = '2' + '1' * 381; $mi`) didn't produce the symptom: it lacked matching-position information, which means that no ANSI escape sequences got embedded.)

**Comment by mklement0** [comment] 2023-02-28 15:52
Note that @SteveL-MSFT has fortunately tracked down the bug and submitted a PR: https://github.com/PowerShell/PowerShell/pull/19240

(The bug was an outright logic bug, and while the culture-sensitive aspect is still unclear, @SteveL-MSFT notes that the fix is effective with culture `ru-RU` in effect too.)

**Comment by daxian-dbw** [comment] 2023-03-01 01:18
> Couldn't figure out why ru-ru is affected as the code seems to should have been broken and nothing in the area was related to culture.

It turns out the formatting code does branch based on culture:

https://github.com/PowerShell/PowerShell/blob/d554d06f57829bdd5ab09072788e967c68bee3d1/src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs#L437-L444

[Six pre-selected cultures](https://github.com/PowerShell/PowerShell/blob/d554d06f57829bdd5ab09072788e967c68bee3d1/src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs#L336) will go with the `if` block, including `en-US`. For `ru-RU` and other cultures, it will go with the `else` block. So, this `VtSubstring` method is not hit for this repro in the `en-US` culture.

**Closed** 2023-03-01 01:24 UTC
Labels: Issue-Bug, In-PR

**Comment by mklement0** [comment] 2023-03-01 02:03
Thanks for clarifying, @daxian-dbw.

To spell it out: `s_cultureCollection` is statically initialized as:

```
            s_cultureCollection.Add("en");        // English
            s_cultureCollection.Add("fr");        // French
            s_cultureCollection.Add("de");        // German
            s_cultureCollection.Add("it");        // Italian
            s_cultureCollection.Add("pt");        // Portuguese
            s_cultureCollection.Add("es");        // Spanish
```

Can you explain the _design rationale_ behind this bifurcation?

Why would these specific cultures call for line wrapping, but not others?

**Comment by daxian-dbw** [comment] 2023-03-01 18:09
@mklement0 That's legacy code written before I joined the team, so I'm not sure why it was designed that way. My guess is that the word-wrapping algorithm is not perfect and the developer who wrote it thought it wouldn't work well with other cultures 🤷

**Comment by iSazonov** [comment] 2023-03-01 18:14
I think it can work with ru-RU well. 
(I doubt there are even languages that don't allow word splitting by space and tab.)

**Comment by daxian-dbw** [comment] 2023-03-01 20:16
Well, the CJK languages don't split words by spaces. Thinking about it, there is no need to have wrod-wrapping for CJK texts.

**Comment by mklement0** [comment] 2023-03-01 23:10
It's probably worth consulting a linguistics expert, but it looks like word-wrapping may be appropriate for all cultures for which `.TextInfo.ANSICodePage` is in the `12xx` range, which comprises the Latin, Cyrillic, Arabic, Hebrew scripts (the latter two being _right-to-left_ writing systems - not sure how this is being handled in PowerShell).

Notably, this excludes the CJK scripts (the `9xx` range) and the Thai script (`874`), which don't use spaces between words.
