### ISSUE TITLE
Start-Job damaged in 7.0.0-preview.6: gives warning about being loaded in compat session

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#11166] opened 2019-11-22 21:09 UTC
# Steps to reproduce

```powershell
start-job -ScriptBlock { echo 'hi' }     
```

# Expected behavior
(just a regular job)
```none

```

# Actual behavior

```none
WARNING: Module PSScheduledJob is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell Core please use 'Import-Module -SkipEditionCheck' syntax.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.19031
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by JustinGrote** [comment] 2019-11-22 21:45
Yeah looks like a dupe of https://github.com/PowerShell/PowerShell/issues/11164, mind closing it?

**Closed** 2019-11-24 04:00 UTC
Labels: Issue-Question, Resolution-Duplicate
