### ISSUE TITLE
Can't rename directory with the same name but different case 

### ISSUE THREAD

**Issue by ArturGudiev** [PowerShell/PowerShell#12483] opened 2020-04-24 21:06 UTC
# Steps to reproduce

```powershell
mkdir Mydir
Rename-Item .\Mydir\ MyDir
```

# Expected behavior
directory should be renamed

# Actual behavior

```none
Rename-Item: Source and destination path must be different.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jackdcasey** [comment] 2020-04-25 05:55
Looked into this a bit, I reckon this is a limitation from the `DirectoryInfo.MoveTo()` method being used to rename the directories. 

```csharp
if (ShouldProcess(resource, action))
{
    // Now move the file
    dir.MoveTo(newPath);

    result = dir;
    WriteItemObject(result, result.FullName, isContainer);
}
```
Looking over the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.moveto), this may be by design: 
```
The destination cannot be another disk volume or a directory with the identical name.
```

**Comment by ArturGudiev** [comment] 2020-04-26 09:30
@jackdcasey You mean it's ok ? It isn't a bug ?

**Comment by vexx32** [comment] 2020-04-26 14:00
It's by design in terms of the API we're using to rename/move the directory. Note that we're using a `MoveTo()` API as there is no specific renaming API on either the [DirectoryInfo](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.moveto?view=netcore-3.1) class, nor the [Directory](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.move?view=netcore-3.1) static class.

A workaround here may be to do a manual check to determine if the new path or name we're moving the item to is the same name as the original, and just differs by case. If this is the case, we can have a fallback method to move it to a temporary location before moving it back under the desired new name.

**Comment by ArturGudiev** [comment] 2020-04-29 05:36
But we have, for example, a mv command on Linux. There is also no special rename command there. And it works well with this case.

**Comment by vexx32** [comment] 2020-04-29 12:40
Sure. But this behaviour likely arose from the .NET behaviour originally on Windows. Rather than diverge the API surface, the .NET team probably elected to keep the current behaviour as-is even on Linux, to prevent the case where the same code behaves entirely differently depending on OS.

I don't know whether the underlying API could be improved on Windows as well, or if they could add a specific `Rename()` API for this kind of case; that question would be better directed at folks in the [dotnet/runtime](/dotnet/runtime) repository. 🙂

**Comment by ArturGudiev** [comment] 2020-04-29 14:09
@vexx32 Ok. I got it. 
 Thank you!

**Comment by mklement0** [comment] 2022-01-03 14:03
I suggest reopening this issue:

* The behavior is clearly a bug.

* The underlying .NET bug - reported in https://github.com/dotnet/runtime/issues/30479 - has since been fixed.

   * Unfortunately, it was only _partially_ fixed: only for `System.IO.Directory.Move()`, not also for `System.IO.DirectoryInfo.MoveTo()`
     * See follow-up bug report at https://github.com/dotnet/runtime/issues/63287

  * While PowerShel uses the still-broken `System.IO.DirectoryInfo.MoveTo()`, there is no strict need  to wait for the remaining bug to be fixed, given that `System.IO.Directory.Move()` could be used.

**Comment by mklement0** [comment] 2022-01-03 14:06
Related issue: 

* https://github.com/PowerShell/PowerShell/issues/14903

**Comment by iSazonov** [comment] 2022-01-03 18:27
I see IO.Directory.Move() was fixed (for leaves) but not IO.DirectoryInfo.MoveTo().
Main problem with .Net API is PowerShell has to work only with absolute paths (drive-rooted) because it uses Runspace CWD instead of OS (and .Net) CWD.

**Closed** 2023-11-23 12:01 UTC
Labels: Issue-Question, Resolution-No Activity
