### ISSUE TITLE
I want return an empty array in a function, but it return a null value.

### ISSUE THREAD

**Issue by abgox** [PowerShell/PowerShell#21547] opened 2024-04-28 11:21 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- I want return an empty array in a function, but it doesn't do it, which has an unintended effect.
- I also used the `[array]` cast type, which didn't work either.
- The problem is that since I explicitly specified its return type, it should not return any other type.

---
- Here, the `Compare-Object` error occurs because it does not return the expected array.
<img width="920" alt="test" src="https://github.com/PowerShell/PowerShell/assets/131574323/cc6e4c35-05de-4a4d-8081-468a655ec994">

---

- Here I used `-is` to see if it was an array, and returned false.
<img width="913" alt="test2" src="https://github.com/PowerShell/PowerShell/assets/131574323/785e1810-02e5-4bd0-975b-7a2564f5363e">

<img width="924" alt="test3" src="https://github.com/PowerShell/PowerShell/assets/131574323/21d75e31-0aa2-4817-bfda-8b7d7cae505d">

### Expected behavior

```console
- It should return an empty array.
```

### Actual behavior

```console
- It return null.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

**Comment by rhubarb-geek-nz** [comment] 2024-04-28 11:27
```
function test-function {
        return New-Object System.Collections.ArrayList
}

$arr = test-function

$arr.GetType()
```

gives

```
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ArrayList                                System.Object
```

**Comment by abgox** [comment] 2024-04-28 11:31
- Thanks, it can solve the problem.
- But, why  `@()` be a problem?

**Comment by rhubarb-geek-nz** [comment] 2024-04-28 11:34
> * But, why  `@()` be a problem?

You have my sympathy, PowerShell can be infuriating with lists of zero or one items where the list can magically evaporate.

**Comment by mklement0** [comment] 2024-04-28 14:33
There is no magic, only an initially perhaps surprising behavior that is fundamental to PowerShell:

In the PowerShell pipeline - which is invariably involved when producing output from a _command_ (function, script, cmdlet, script block) - (most) enumerables (such as arrays, ArrayLists, ...) are _auto-enumerated_; that is, an enumerable's _elements_ are sent _one by one_ to the success [output stream](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Output_Streams).

In other words: Unless you take extra steps (see below), the original enumerable is - predictably - _lost_, and in the success output stream you cannot tell the difference between outputting a single-element enumerable and the one element it contains, given that in _both_ cases it is only the latter that is sent to the output stream.

An empty enumerable - such as in your case - sends "nothing" to the success output stream (pipeline), which is technically the `[System.Management.Automation.Internal.AutomationNull]::Value` singleton, which in effect behaves like `$null` in _expression_ contexts and argument-based parameter binding (such as your case).

The success output stream is an open-ended stream of objects that itself has no notion of an array or a similar data structure: the objects in it can - and often are - processed _one by one_, as they are received, in which case the question of how to _collect_ them for later processing doesn't arise.

_Collecting_ stream output of necessity comes into play when you assign to a variable (e.g., `$arr = test-function`), or make command output participate in a larger expression (e.g., `'foo' + (test-function)`), including use of `$(...)` and `@(...)` (except with array _literals_). Collecting a _single_ object in the stream causes it to be collect _as-is_. It is only if _two or more_ objects in the stream that a _list-like_ data type is invariably needed for collection, in which case PowerShell invariably creates an `[object[]]`-typed array. For the reasons explained above, this array is unrelated to any originating enumerable type, which never participated as itself in the pipeline.

To send an instance of an enumerable type _itself_, _as a whole_ to the success output stream, you must _prevent auto-enumeration_:

* `New-Object` itself uses this technique, which is why @rhubarb-geek-nz's workaround is effective; `New-Object`'s behavior is _unusual_ among cmdlets (see below), but necessary in order to preserve the constructed instance as-is.
  * It is worth noting that the alternative, v5+ _expression_ syntax for calling .NET type constructors does _not_ exhibit this unusual behavior; that is, while `New-Object object[] 0` sends the resulting array _as itself_ to the success output stream, the otherwise equivalent expression `[object[]]::new(0)` _is_ subject to auto-enumeration
* The conceptually clearest expression of the intent to suppress auto-enumeration is to use `Write-Output -NoEnumerate`,
but an often-seen shortcut is to use the unary form of `,` the array-constructor operator to create a transient helper array that wraps the output enumerable in a single-element array whose auto-enumeration then sends the enumerable itself to the success output stream.

In other words: The following techniques all work to output an empty array as a whole from your function:

```powershell
# Using New-Object
function test-function { New-Object -object[] 0 }

# Using Write-Output -NoEnumerate
function test-function { Write-Output -NoEnumerate @() }

# Using a transitory single-element helper array wrapper
function test-function { , @() }
```

It is worth noting that auto-enumeration is a core PowerShell feature that you should generally _not_ deviate from, especially in public-facing functions / cmdlets / scripts.

On a higher level of abstraction, one of PowerShell's core strength is its consistency, of which consistent behavior in output streams / in the pipeline is one aspect.

To put it in concrete terms: Users justifiably expect commands to output objects _one by one_ rather than outputting list-like containers _as a whole_, especially given that the latter behavior will not behave as expected in the pipeline; e.g.:

```powershell
# Expected, auto-enumerating streaming behavior (element-by-element streaming).
# Where-Object's script block is invoked once for each element.
# -> 2, 3 
& { @(1, 2, 3) } | Where-Object { $_ -ge 2 }

# Unusual, array-as-a-whole output behavior.
# !! -> @(1, 2, 3) 
# !! Where-Object only receives *one* input object, which is the *array* as  while, in which
# !! case -ge acts as an array filter, that returns subarray @(2, 3), which Where-Object interprets
# !! as $true, and therefore *passes the input object (array) through*.
& { Write-Output -NoEnumerate @(1, 2, 3) } | Where-Object { $_ -ge 2 }
```

So as not to confound user expectations, _deviation_ from this behavior should make the target command require user _opt-in_, such as via the `-NoEnumerate` and `-AsArray` switches some built-in cmdlets (now) offer.

The legacy PowerShell edition, _Windows PowerShell_, neglects to exhibit this patterns in a few cases (i.e. outputs arrays-as-a-whole _by default or invariably_), which have since been corrected in PowerShell 7.

A prominent example is `ConvertFrom-Json`, which only in PowerShell 7 exhibits the expected behavior - see https://github.com/PowerShell/PowerShell/issues/3424 for the backstory.

Note that while PowerShell 7's built-in cmdlets now work consistently, from what I can tell, third-party code and even modules that ship with Windows may still exhibit the unexpected behavior; e.g., `Get-WinUserLanguageList`

If you encounter such a command and want to _force_ enumeration, simply enclose it in `(...)`

**Comment by rhubarb-geek-nz** [comment] 2024-04-28 20:50
Another trick to avoid PowerShell's collapsing of single elements is to capture the OutVariable itself which will contain all the elements of the output pipeline, so you can see it is the assignment doing collection.

```
$date = Get-Date -OutVariable datevar
$date.GetType()
$datevar.GetType()
```

gives

```
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     DateTime                                 System.ValueType
True     True     ArrayList                                System.Object
```

**Comment by mklement0** [comment] 2024-04-29 01:27
@rhubarb-geek-nz, while that is technically true, I consider this asymmetry between direct variable assignment and `-OutVariable` a bug, not a feature, as discussed many years ago in the following issue (nowadays, I would use slightly different framing and language, but the gist of the issue still applies):

* #3154

Consider the following pitfall:

```powershell
$null = Get-Item -OutVariable v $PROFILE

# !! ->  "The property 'LastWriteTime' cannot be found on this object. Verify that the property exists and can be set."
$v.LastWriteTime = [datetime]::now
```

Clearly, the intent of `Get-Item $PROFILE` is to retrieve a _single_ object; yet, `$v` is now an `ArrayList` instance, so that `$v.LastWriteTime` applies [member-access enumeration](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration), which is unsupported for _setting_ properties.

**Comment by rhubarb-geek-nz** [comment] 2024-04-29 05:50
As a general rule, avoid assignment in PowerShell when you are dealing with multiple items. It is problematic managing codes paths which sometimes run a single item or a list of items. Compare with an SQL query, a result can return zero items, one item or multiple items with no drama. Where as powershell can give you a null, a single item or a collection.

It is all water under the bridge, but my recommendation remains, avoid assignment operator when dealing with multiple items where the count may be 0, 1 or many. Use the output either in a pipeline or the OutVariable for consistent results.

**Comment by rhubarb-geek-nz** [comment] 2024-04-29 07:05
> Clearly, the intent of `Get-Item $PROFILE` is to retrieve a _single_ object

However

```
PS> get-command get-item -syntax

Get-Item [-Path] <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Force] [-Credential <pscredential>] [-Stream <string[]>] [<CommonParameters>]

Get-Item -LiteralPath <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Force] [-Credential <pscredential>] [-Stream <string[]>] [<CommonParameters>]
```

Your parameter goes to the path variable which can both take an array and expand the wildcards

```
PS> $FOO='*.ps1'
PS> get-item $FOO

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          29/04/2024    00:20            156 array.ps1
-a---          28/04/2024    20:31            120 empty.ps1
-a---          28/04/2024    21:57             91 error.ps1
-a---          28/04/2024    21:55            101 outvar.ps1
```

So your clearly is clearly not quite as clear as you suggest.

**Comment by mklement0** [comment] 2024-04-29 11:25
The "clearly" applied to  _the specific command_, where a literal, single path was provided as the input.

The point is that any cmdlet is free to _situationally_ "return" - i.e., emit to the output stream - zero, one, or more output objects.

Earlier we've discussed the stream _collection_ behavior that applies in direct variable. assignment, notably that a _single_ output object is collected _as-is_.

The point of my previous comment was:

* There is NO good reason for `$v = ...` to collect the output objects _differently_ than `... -OutVariable v`.

* This difference can lead to bugs / unexpected behavior that may be hard to understand.

Also, note that your framing wasn't correct:

>  avoid PowerShell's delisting of single elements is to capture the OutVariable itself 

`-OutVariable` has no impact on auto-enumeration, which happens regardless, unless explicitly suppressed.
It's simply  that the`-OutVariable` feature _unconditionally_ creates an `ArrayList` for the collected output, irrespective of the number of output objects. In concrete terms: 
* With zero output objects, direct variable assignment stores `[System.Management.Automation.Internal.AutomationNull]::Value` (the "enumerable null", which behaves like `$null` in an expression context, and like an empty enumerable in the pipeline), whereas `-OutVariable` creates an empty `ArrayList` instance.
* With one output object, direct variable assignment collects that object as-is, whereas `-OutVariable` creates a single-element `ArrayList`
* With two or more output objects, direct variable assignment creates a - fixed size - `[object[]]` array, whereas `-OutVariable` creates a (multi-element, resizable) `ArrayList` instance.

While you may choose to rely on this awkward inconsistency  (which the documentation only hints at, without spelling out the ramifications) in order to _always_ get an array-like result, I personally recommend avoiding it, both for the awkwardness of then having to suppress the success output (`$null = ... -OutVariable`) and the confusing discrepancy.

The short of it:

* In order to emit enumerables _as a whole_ from a PowerShell command, auto-enumeration must be suppressed (as an aside: in the `Cmdlet.WriteObject()` SDK function, the logic is _reversed_), using the techniques previously discussed.

* If you want to ensure that _at most one_ object is captured in a variable, pipe to `Select-Object -First 1` or - if you don't mind collecting all output first - use `(...)[0]` (assuming `Set-StrictMode` is at most at `-Version 2`).

* If you want to ensure that output is _always_ captured in an _array_, use `@(...)`, the [array-subexpression operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#array-subexpression-operator--) (`$v = @(...)`), or (with subtly different  behavior, `[array] $v = ....`).
  * However, thanks to the unified handling of scalars and lists, provided via [intrinsic members](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Intrinsic_Members) and [member-access enumeration](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration), it is often not necessary to force creation of an array.

**Comment by rhubarb-geek-nz** [comment] 2024-04-29 16:56
A common pattern that I have, which is why I have so much frustration with PowerShell's Schroedinger's OO model is that being able to round trip JSON data is of vital importance. If the original JSON was an array it needs to stays as an array even if it only has one contained object. Likewise if an object contains a property that was array of one object that needs to stay as an array after out processing. Yes ConvertFrom-JSON now has the -NoEnumerate, and that adds to the complexity when writing scripts that have to work on both Desktop and Core. In order to do that we have to have test cases where every array anywhere within an object can have zero, one or some items so we know we are using the right flags at each processing step and work with all combinations of data.

**Comment by mklement0** [comment] 2024-04-29 20:05
> ConvertFrom-JSON now has -NoEnumerate, and that adds to the complexity when writing scripts that have to work on both Desktop and Core.

That is unfortunate, but an unavoidable consequence of things getting improved / fixed in PS Core.

An array stored in a _property value_ should never pose any problem, however; e.g., the following round-trips properly, in both editions:

```powershell
[pscustomobject] @{ ArrayProp = @(1) } | ConvertTo-Json | ConvertFrom-Json
```

Also note that a simple way to avoid auto-enumeration is to pass an enumerable as an _argument_ to `ConvertTo-Json`:

```powershell
ConvertTo-Json @(1) -Compress # -> '[1]'
```

**Closed** 2024-05-01 05:44 UTC
Labels: Issue-Question, Resolution-Answered
