### ISSUE TITLE
Get-Module -ListAvailable not listing modules

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/PowerShell#2234] opened 2016-09-12 01:12 UTC
## Steps to reproduce

Install a module to a PSModulePath, look for it:

``` powershell
Install-Package -Name PoshRSJob, PSSlack `
                -Source https://www.powershellgallery.com/api/v2 `
                -ProviderName NuGet `
                -ExcludeVersion `
                -Destination ~/.local/share/powershell/Modules/ `
                -Force

Get-Module -ListAvailable
```
## Expected behavior

`Get-Module -ListAvailable` returns module information for modules in PSModulePath paths
## Actual behavior

Installed modules (PoshRSJob and WFTools in this case) are not listed.

Notes:
- Tab completion for Import-Module does list these modules
- Modules import by name alone (no need for full path) without issue
- Modules are listed with `Get-Module` after import
- Modules are still unlisted with `Get-Module -ListAvailable` switch after import
## Environment data

macOS (El Capitan):

``` powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Centos 7:

``` powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Cheers!

**Comment by kilasuit** [comment] 2016-09-12 05:01
Have you tried with the -Refresh Parameter
```powershell
Get-Module -ListAvailable -Refresh
```

**Comment by chuanjiao10** [comment] 2016-09-12 06:32
andschwa: reopen my issue #2210

**Comment by kilasuit** [comment] 2016-09-12 07:01
@chuanjiao10 - Please refrain from referencing issues that don't relate to the issue that you are commenting on.

**Comment by chuanjiao10** [comment] 2016-09-12 07:07
@kilasuit :I was treated unfairly.If you are just one person, you should also say something in #2210.

**Comment by RamblingCookieMonster** [comment] 2016-09-12 13:00
@kilasuit - that's more around command discovery, no?  I would assume `-ListAvailable` should always list every valid module in a PSModulePath path.

No dice on using `Get-Module -ListAvailable -Refresh` though - does it work for you if you download or just create a module in there?

More notes:

* Manually creating a 'wtf' module results in same behavior:

```
mkdir /Users/wframe/.local/share/powershell/Modules/wtf
New-ModuleManifest -Path /Users/wframe/.local/share/powershell/Modules/wtf/wtf.psd1
```

Cheers!

**Comment by damnsalvation** [comment] 2017-05-04 14:26
I also have this problem, but the modules I'm trying to load are Microsoft's - specifically Configuration Manager and Security Client (though I don't really care about that one).

My PSModulePath statement is:
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\;C:\Program Files\Microsoft Security Client\MpProvider\;C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin\;
(in $env:PSModulePAth it is prepended with (my profile)\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;)

Get-Module -ListAvailable shows everything through SQL, but not MpProvider or Config Manager.  

I saw elsewhere that the .psd1 or binary has to have the same name as the folder it's in to be listed.  This is the case for MpProvider.psd1, so by all rights it should show up.  It is not the case for the Config Manager module, which I take to be a silly mistake on the CM team's part or completely irrelevant because the security client module does conform but doesn't show.

Unlike the OP, importing by name without the full path does not work.

I wouldn't worry about it if it didn't take so dang long to type - import-module "c:\program files(x86)\microsoft configuration manager\adminconsole\bin\configurationmanager.psd1".

Oh, and if you had not guessed, I'm having this issue on Server 2012r2.

**Comment by MaximoTrinidad** [comment] 2017-05-04 14:45
Hum! I think the issue is that PowerShell Open Source is not meant to recognize any of the Windows PowerShell Modules as they are different. I don't think PowerShell OSS will be replacing Windows PowerShell as it will take a long time because of its differences.

:)

**Comment by damnsalvation** [comment] 2017-05-04 16:32
...Am I in the wrong place?
Crap.

**Comment by MaximoTrinidad** [comment] 2017-05-04 17:38
Hey @damnsalvation!

Not really!  If the cmdlet having issue is part of PowerShell Core Module then it matter to take a look at.  If the issues only relates to Windows PowerShell v5.x then is better to log the issue under Windows PowerShell UserVoice forum.    All issues will be looked at and taken care of in either UserVoice or GitHub respectively.

:) 

In case you need the UserVoice link, here it is: 
Windows PowerShell UserVoice:
https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by SteveL-MSFT** [comment] 2017-05-05 05:08
This is worth investigating.

**Comment by kilasuit** [comment] 2017-05-10 14:00
@SteveL-MSFT - I may be wrong but this looks to be due to the rework of the module analysis cache that came in with v5 and I think that Get-Command and Get-Module will not fully update until a new session gets opened but I'm stabbing at a guess there as I did look into this ages ago but then this dropped off the radar somewhere. 

@RamblingCookieMonster - this leads me to ask if you get the same issue on a v4 windows box at all? or a fresh v5/v5.1 windows box? If it doesnt happen on v4 then I'm betting that its likely to do with the module analysis cache but that's just my thoughts.

**Comment by SteveL-MSFT** [comment] 2017-05-10 17:01
@kilasuit yes, the analysis cache was reworked to improve performance in v5 by @lzybkr

**Comment by lzybkr** [comment] 2017-05-10 17:10
The performance work went into v5.1.

I don't think I'm seeing the problem with v5.1, though I ran `Install-Module` instead of `Install-Package` and I ran on Windows.

I also don't recall any old (before my changes) or new code that would explain the described behavior - which is my way of saying, it should just work, I'm surprised it didn't.

**Comment by joeyaiello** [comment] 2017-05-25 18:13
This doesn't repro anymore on `6.0.0-beta.1`, so I'm marking as fixed. (Plus, Install-Module works on Linux/macOS now.)

**Closed by joeyaiello** 2017-05-25 18:13 UTC
Labels: Area-Engine, Resolution-Fixed

**Comment by bergersn** [comment] 2018-10-22 14:55
I realize this issue is closed, however I currently encounter a (maybe?) similar problem.

I'm experimenting with Hosting PowerShell Core. I build a custom host (implementing PSHost, PSHostUserInterface, PSHostWarUserInterface). I am executing a script by loading it from a file and running it with `PowerShell.AddScript(...)` and `PowerShell.Invoke()`. I am glancing over most of the details, but I am happy to elaborate more. In short, executing works and I see the output of commads in my dontnetcore 2.1 console application.

This is the script

```
$PSVersionTable
"---"
$env:PSModulePath
"---"
Get-Command -Module "Microsoft.PowerShell.Core" | select modulename, name | ForEach-Object { "$($_.modulename).$($_.name)" }
"---"
Get-Module -ListAvailable | foreach {Get-Command -Module $_.name | select modulename, name} | ForEach-Object { "$($_.modulename).$($_.name)" }
"---"
```

This is what I get:
```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
---
D:\DEV\<...>\netcoreapp2.1\publish
---
Microsoft.PowerShell.Core.Add-History
... (omited)
Microsoft.PowerShell.Core.Where-Object
---
---
```

As you can see, there is just a "`null`"-line between the last two `---`. What I would have expected would a long list like I get when I execute the corresponding command in pwsh.exe:

```
CimCmdlets.Get-CimAssociatedInstance
... (omited)
PSReadLine.Set-PSReadLineOption
ThreadJob.Start-ThreadJob
```

My runspace is the created using `CreateRunspace(_host, InitialSessionState.CreateDefault())`. After I `Open()` the runspace, I change `PSModulePath` to only point to the directory where I publish my console app. All the referenced Powershell SDK DLLs are available there (Microsoft.PowerShell.Commansd.Diagnostics and so on).

Am I missing something? Is this intended behaviour? I can use all the Cmdlets from those Assemblies, f.ex. `Get-Process` or `Get-ItemProperty` just fine in my Host...

**Comment by bergersn** [comment] 2018-10-22 14:57
oh, and 
```
Get-Command -Module "Microsoft.PowerShell.Management" | select modulename, name | ForEach-Object { "$($_.modulename).$($_.name)" }
```
also doesn't output anything in my hosted PowerShell Core....

**Comment by vexx32** [comment] 2018-10-22 15:07
> After I Open() the runspace, I change PSModulePath to only point to the directory where I publish my console app. All the referenced Powershell SDK DLLs are available there 

Have you also moved the .PSD1 files for these modules into subfolders in this new location? Otherwise I doubt PowerShell has a means to obtain the metadata you're looking for. :)
