### ISSUE TITLE
Set and Get windows environment variables from powershell

### ISSUE THREAD

**Issue by KatsutoshiOtogawa** [PowerShell/PowerShell#18126] opened 2022-09-19 13:34 UTC
### Summary of the new feature / enhancement

I would like to add Set-WinEnvironmentVariable and Get-WinEnvironmentVariable cmdlets that work only in Windows environment so that I can manipulate environment variables from the terminal.

The existing ones require the use of setx.exe, which is inconvenient, and are not very compatible with powershell.

I have already written the source code to add them, including testing, and will send a pull request as soon as the proposal is accepted.

**Comment by 237dmitry** [comment] 2022-09-19 15:43
```powershell
 PS > [Environment]::SetEnvironmentVariable      

OverloadDefinitions
-------------------
static void SetEnvironmentVariable(string variable, string value)
static void SetEnvironmentVariable(string variable, string value, System.EnvironmentVariableTarget target)

PS > [Environment]::GetEnvironmentVariable      

OverloadDefinitions
-------------------
static string GetEnvironmentVariable(string variable)
static string GetEnvironmentVariable(string variable, System.EnvironmentVariableTarget target)

PS > [EnvironmentVariableTarget].GetEnumValues()
Process
User
Machine
```

**Comment by MartinGC94** [comment] 2022-09-19 22:52
@237dmitry It's worth noting that the environment variable handling in .NET is broken. It auto expands environment variables when you retrieve them and when you save them it changes the corresponding registry keys to regular strings instead of expandable strings.  
I think it would be great to have a command for this because even if the simple .NET APIs for this weren't completely broken, they are still not as convenient to call as a regular command and it seems like a relatively common task.

**Comment by KatsutoshiOtogawa** [comment] 2022-09-20 07:12
ex)

PS > Get-WinEnvironmentVariable

# If EnvironmentVariable is not specified

Name Value
---- -----
OS Windows_NT
USERNAME YourName
PROCESSOR_LEVEL 6
GOPATH C:\Users\YourName\go
SystemDrive C:
SystemRoot C:\Windows
HOMEPATH \Users\YourName
...

Given Delimiter and Name, it returns with a list of strings.
PS > Get-WinEnvironmentVariable -Name 

Anything in Windows that has a fixed delimiter as a system
Path, PATHEXT, etc.

PS > Get-WinEnvironmentVariable -Name Path


If you give -Raw and -Name, it will be displayed in one line.
PS > Get-WinEnvironmentVariable -Name Path -Raw


Overwrite and save
PS > Set-WinEnvironmentVariable -Name Path -Value "C:\Program Files\Go\bin;C:\Program Files\PowerShell\7;C:\Windows\system32"


Add the path to the Path environment variable
PS > "C:\Program Files\Go\bin" | Set-WinEnvironmentVariable -Name Path -Append

When Append or Array is passed, an error is generated if Delimiter is not specified.
(Prevention of op-mistakes)

PS > "C:\Program Files\Go\bin" | Set-WinEnvironmentVariable -Name foo -Append
Shuld be error




Set-WinEnvironmentVariable will only ask the user for confirmation by default for safety reasons, unless the EnvironmentVariableTarget is Process.
For safety reasons, the default is to ask the user for confirmation.

If Force is given, confirmation is skipped, but if administrative privileges are required, processing stops with an error.

**Comment by KatsutoshiOtogawa** [comment] 2022-09-20 07:23
@237dmitry 
As it is now with Powershell, users are confused by using dotnet objects, setx.exe which is supposed to be used with cmd, and Env:Path.

I think that Windows applications and api's that will be used frequently should be provided with dedicated cmdlets for them.

**Comment by 237dmitry** [comment] 2022-09-20 08:08
> users are confused by using dotnet objects

I disagree with this statement. Nevertheless, I agreed with your request for a feature.

**Comment by SteveL-MSFT** [comment] 2022-09-26 18:18
This is a dupe of https://github.com/PowerShell/PowerShell/issues/3108

**Comment by KatsutoshiOtogawa** [comment] 2022-09-27 06:27
@SteveL-MSFT 
It should not be put out in a module outside of Powershell.

There are two main ways for the user to manipulate environment variables.
1. dotnet's [Environment]::SetEnvironmentVariable()
2. the GUI's "Edit the System Environment Variable".

However, the handling of these two environment variables is clearly broken.

This is described in fixes <https://github.com/dotnet/runtime/issues/1442>. 

1.[Environment]::SetEnvironmentVariable() always overwrites an existing environment variable with REG_SG, no matter what its Type is. Therefore, if an environment variable in the form of %var% is saved with a Type of REG_EXPAND_SG, the value cannot be expanded.
2. "Edit the System Environemt" will always overwrite with REG_EXPAND_SG if an environment variable is saved that contains the string %." It is at the point of finding the "%", not the variable expansion "%var%". Therefore, if you have saved a string containing % in an environment variable as REG_SG, it will be changed to REG_EXPAND_SG by itself when you use "Edit the System Environment Variable" to overwrite any value.

This bug has existed since the .net framework days and has not been resolved even in the latest dotnet 7.0-rc1, requiring users to tinker with their systems based on the [Environment]::SetEnvironmentVariable() bug assumption.
Similarly, "Edit the System Environment Variable" has not been fixed in Windows 11 (21H1).

Therefore, Windows needs to add some functionality to allow ordinary users to manipulate environment variables without encountering bugs.
Currently, it would be most appropriate to add the functionality as a Powershell cmdlet.

Even if we create a cmdlet, it is not enough to just create a wrapper for [Environment]::SetEnvironmentVariable(). You need to manipulate the registry from dotnet in order to do so safely.

If you want to handle environment variables, you should not use [Environment]::SetEnvironmentVariable(), but use
Set-ItemProperty, Get-ItemProperty, and New-ItemProperty are still more appropriate.

However, Set-ItemProperty can set types other than REG_SG and REG_EXPAND_SG, which Windows probably does not expect as environment variables. ([Environment]::GetEnvironmemtVariable() cannot expand environment variables of Types other than REG_SG and REG_EXPAND_SG and returns null.)

In light of the above, other cmdlet should be provided just for manipulating environment variables apart from *-ItemProperty.

And since most of this process is Windows-only, it should be a Windows-only cmdlet (Linux and macos provide an easier way to change environment variables in the first place).
So the name *-WinEnvironmentVariable is more appropriate than *-EnvironmentVariable, which also supports Linux and macos.

**Comment by KatsutoshiOtogawa** [comment] 2022-09-27 06:35
@SteveL-MSFT 
I've searched the command red in PowershellGallery that manipulates Windows environment variables.
All of the cmdlets that come to the top of the search use [Environment]::GetEnvironmentVariable(), [Environment]::SetEnvironmentVariable().

If you are using EnvironmentVariableTarget.Process, these two functions are fine, but anything else is a breeding ground for bugs.

**Comment by KatsutoshiOtogawa** [comment] 2022-09-27 06:42
I am ashamed to say that I did not know about this [Environment]::SetEnvironmentVariable() bug when I submitted the pull request <https://github.com/PowerShell/PowerShell/pull/18155>,  so this pull request has the same bug as the others.

However, I have rewritten it in a way that manipulates the registry. This way you won't be bothered by the [Environment]::SetEnvironmentVariable() bug.

**Closed** 2022-09-28 08:01 UTC
Labels: Resolution-Duplicate, Issue-Enhancement, Needs-Triage
