### ISSUE TITLE
convert hash table

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12357] opened 2020-04-17 14:11 UTC
to convert hash table into an object representation we use import-LocalizedData cmdlet (not really meant  for this purpose)

it's better to have new cmdlet **ConvertTo-hashtable**  and **ConvertFrom-hashtable**

```
PS C:\> gcm  ConvertTo-hashtable -syntax

ConvertTo-hashtable [-InputObject] <Object> [-Path] [<CommonParameters>]

PS C:\> gcm  ConvertFrom-hashtable -syntax

ConvertFrom-hashtable [-InputObject] <string> [<CommonParameters>]
```

in powershell we have **ArgumentToConfigurationDataTransformation** attribute is used  to transform **(valid DSC)** hash table string into an object...but its  limit to validate DSC keys into hash table string before transformation...we can generalize this concept to validate and transform any hashtable   

why we need this feature ? because powershell love hash table and hash table love powershell  

```
PS C:\> Get-Command -ParameterType hashtable

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        TabExpansion2
Cmdlet          Add-Member                                         7.0.0.0    Microsoft.PowerShe…
Cmdlet          ConvertTo-Html                                     7.0.0.0    Microsoft.PowerShe…
Cmdlet          Get-Job                                            7.0.0.0    Microsoft.PowerShe…
Cmdlet          Invoke-Command                                     7.0.0.0    Microsoft.PowerShe…
Cmdlet          Invoke-RestMethod                                  7.0.0.0    Microsoft.PowerShe…
Cmdlet          Invoke-WebRequest                                  7.0.0.0    Microsoft.PowerShe…
Cmdlet          New-Object                                         7.0.0.0    Microsoft.PowerShe…
Cmdlet          New-PSRoleCapabilityFile                           7.0.0.0    Microsoft.PowerShe…
Cmdlet          New-PSSession                                      7.0.0.0    Microsoft.PowerShe…
Cmdlet          New-PSSessionConfigurationFile                     7.0.0.0    Microsoft.PowerShe…
Cmdlet          Remove-Job                                         7.0.0.0    Microsoft.PowerShe…
Cmdlet          Select-Xml                                         7.0.0.0    Microsoft.PowerShe…
Cmdlet          Set-PSReadLineOption                               2.0.0      PSReadLine
Cmdlet          Stop-Job                                           7.0.0.0    Microsoft.PowerShe…
Cmdlet          Wait-Job                                           7.0.0.0    Microsoft.PowerShe…


```
and maybe later 

test-hashtable to validate hash table string  keys same as **ArgumentToConfigurationDataTransformation**  or by **special schema** for example

```
PS>  Test-hashtable -Path c:\myresource.psd1 -schema c:\schema.psds1
True

PS> cat c:\schema.psds1
@{
    Key1name  = "'int"
   key2name  = "datetime"
   key3name = "" # optional
}
```

**Comment by rjmholt** [comment] 2020-04-17 14:28
I believe this is a duplicate of https://github.com/PowerShell/PowerShell/issues/11300

**Comment by vexx32** [comment] 2020-04-17 15:46
@p0W3RH311 if there are any details in this issue not fully captured in #11300, please feel free to add any missing ideas to that issue. 🙂

**Closed by vexx32** 2020-04-17 15:46 UTC
Labels: Issue-Enhancement, Resolution-Duplicate
