### ISSUE TITLE
'.\filename' (dot-path local execution) requirement not required for files '.file'

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#9468] opened 2019-04-25 19:51 UTC
Edit: Adding hints from the conversation

# Steps to reproduce

First, insure you do not have the test subject file in your path:

```PowerShell
.test.html # should produce a 'not recognized' error
```
If the above did not produce an error, change the command so that the file name still starts with a `.` but produces the said error, and change the below example accordingly.

If the above produced an error, then try the following:

```powershell
@'
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>foo</title>
  </head>
  <body>
    <div>Hello</div>
  </body>
</html>
'@ > .test.html # generate a sample file

.test.html # invoke sample file
```

# Expected behavior

I would expect an error saying '.test.html' is not recognized as … but does exist in the current location.

# Actual behavior

The default browser will open the file.

It appears that the '.' that begins the file name is enough to satisfy the 'dot path' rule for executing files in the current working directory.   I did not expect this.

# Environment data

PowerShell Core 6.2.0 on Windows 10 1809.  Also confirmed in Windows PowerShell 5.1, same OS.

**Comment by mklement0** [comment] 2019-04-25 21:03
You're not _executing_ `.test.html`, you're applying the Windows shell's _default verb_ to it - something that has always worked this way.

In other words: you're _opening document_ `.test.html`  rather than _invoking an executable_.

**Comment by msftrncs** [comment] 2019-04-25 21:11
But it doesn't work for 'test.html'  Instead I get an error saying not a command, but exists in the current location.   

Opening a document is the same as invoking an executable in Windows, for all intents and purposes.

**Comment by msftrncs** [comment] 2019-04-25 21:20
To be clear, if I have two files, '.test.html' and 'test.html',
```PowerShell
.test.html # succeeds opening default browser
test.html # reports 'not recognized, but exists in the current location'
.\test.html # succeeds opening default browser
```

**Comment by mklement0** [comment] 2019-04-25 21:30
Good point - I'd  used `*.txt` in my tests, which PowerShell happily opens even without the `.\` prefix.

I don't know what explains the difference (haven't looked at other extensions), but it's certainly an inconsistency, and from a security and predictability standpoint it makes sense to _always_ require an explicit path reference to open/execute a file in the _current_ location (tab completion assists with that by automatically prepending `.\` / `./` for a file that exists in the current dir.)

Complementarily, it makes sense to _only_ support locating _executables_ via `$env:Path` (as defined via `$env:PATHEXT`), not also _documents_ (i.e., files with names whose extensions aren't marked as executable).

**Comment by msftrncs** [comment] 2019-04-25 21:34
I am not seeing the behavior of `.txt' files acting any differently.  Without the `.\` prefix I get the same message, 'not recognized... but exists in the current location', unless the file name starts with a dot.

**Comment by mklement0** [comment] 2019-04-25 21:44
@msftrncs: 

You are correct: My mistake was that  I had a `t.txt` located somewhere in `$env:PATH`, which is what actually was opened, not my current-directory-local copy.

So to summarize:

* What your OP reports is indeed a bug: a filename starting with `.` bypasses the need to open/execute a file located in the current directory with a _path_ (whether relative or absolute).

* Separately, it is problematic that PowerShell allows opening even _non-executable_ files by filename only, as long as they're located in `$env:PATH`.

**Comment by msftrncs** [comment] 2019-04-25 21:45
I want to clarify that I tested deleting the `.test.html` file, and tried to run it, to validate that I did not have such a file on my PATH somewhere.  I wanted to make sure I wasn't making that mistake,

**Comment by mklement0** [comment] 2019-04-25 22:11
Understood, @msftrncs; re my 2nd point above: please see #9469.

**Comment by msftrncs** [comment] 2019-04-25 23:29
Also, confirming that the same issue occurs with the use of dot-source `.` or the call `&` operators or the `invoke-expression` cmdlet and a string value, in a variable or quoted literal.

```PowerShell
$a = '.test.html'
$b = 'test.html'
.$a # opens (not expected)
.$b # errors (as expected)
&$a # opens (not expected)
&$b # errors (as expected)
invoke-expression '.test.html' # opens (not expected)
invoke-expression 'test.html' # errors (as expected)
```

The fact that all invocation methods work the same would be expected.

**Comment by TravisEz13** [comment] 2019-04-26 23:21
As this is existing 5.1 behavior, this is considered an enhancement.  cc @iSazonov

**Comment by msftrncs** [comment] 2019-04-27 00:06
@TravisEz13, does it change it any if my example of an HTML file was replaced with a script file `.test.ps1`.   The same behavior happens, (and protective feature bypassed) if the example was a script file.  Fixing this would seem to be a defense-in-depth condition.

**Comment by iSazonov** [comment] 2019-04-27 08:47
@TravisEz13 It is not clear for me why it is "enhancement" if we see unexpected (and possibly dangerous) behavior. From my understanding "enhancement" is "add new useful functionality".

**Comment by vexx32** [comment] 2019-04-27 12:43
@iSazonov I think just meant that the request to fix this would be considered an enhancement of the existing behaviour, rather than a bug. Tricky wording.

**Comment by TravisEz13** [comment] 2019-04-27 18:02
I'm sorry.  I miss read the repro.  This is by design.  `./` or `.\` is not required to execute a file.  Not all scenarios work, but we have explicit tests to verify that this scenario actually works.

**Comment by TravisEz13** [comment] 2019-04-28 01:42
I thought about this more. This is not a good design.  I remember arguing for changing it myself when fixing a recent Defense in Depth issue.

**Closed** 2023-11-23 12:46 UTC
Labels: Issue-Enhancement, WG-Engine, Resolution-No Activity
