### ISSUE TITLE
PSScriptRoot variable is an empty string when filename extension is not .ps1

### ISSUE THREAD

**Issue by pszypowicz** [PowerShell/PowerShell#17323] opened 2022-05-12 11:34 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a script, saved once with `.ps1` file extension, and once without.

The script:
```
#!/usr/bin/env pwsh
Write-Host $PSScriptRoot
```

When I execute the script, I'm expecting to see proper Path of a file. Unfortunately it works only then the file is named with ps1 extension. 

Why is that?

### Expected behavior

```console
PS > ./test
/tmp
PS > ./test.ps1
/tmp
```

### Actual behavior

```console
PS > ./test

PS > ./test.ps1
/tmp
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Linux 5.13.0-1023-azure #27~20.04.1-Ubuntu SMP Mon Apr 25 22:39:07 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2022-05-12 12:38
Hey, thanks for reporting! I believe this is a duplicate of #4217 🙂

**Closed** 2022-05-13 14:00 UTC
Labels: Issue-Bug, Resolution-Duplicate
