### ISSUE TITLE
`WindowsCompatibility` module fails to import on PS 7.5.0-preview.3

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#23993] opened 2024-06-27 07:51 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`WindowsCompatibility` module fails to import on *PS 7.5.0-preview.3* due to an extra trailing dot in the namespace in the `WindowsCompatibility.psm1` file:
```pwsh
using namespace System.Management.Automation.
```

This **works** on *PowerShell 7.4.3*, so I guess we should allow for trailing dots in PS 7.5.0 as well.

### Expected behavior

```console
I should be able to import WindowsCompatibility module
```

### Actual behavior

```console
Import-Module WindowsCompatibility -Force
ParserError: The specified namespace in the 'using' statement contains invalid characters.
Import-Module: The module to process 'WindowsCompatibility.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program Files\PowerShell\Modules\WindowsCompatibility\1.0.0\WindowsCompatibility.psd1' was not processed because no valid module was found in any module directory.
```

### Error details

```console
Exception             :
    Type           : System.Management.Automation.PSInvalidOperationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The module to process 'WindowsCompatibility.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program
Files\PowerShell\Modules\WindowsCompatibility\1.0.0\WindowsCompatibility.psd1' was not processed because no valid module was found in any module directory.
            HResult : -2146233087
        TargetObject          : WindowsCompatibility
        CategoryInfo          : ResourceUnavailable: (WindowsCompatibility:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : Modules_ModuleFileNotFound
    TargetSite     :
        Name          : LoadModuleManifest
        DeclaringType : [Microsoft.PowerShell.Commands.ModuleCmdletBase]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : The module to process 'WindowsCompatibility.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program
Files\PowerShell\Modules\WindowsCompatibility\1.0.0\WindowsCompatibility.psd1' was not processed because no valid module was found in any module directory.
    InnerException :
        Type    : System.IO.FileNotFoundException
        Message : The module to process 'WindowsCompatibility.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program
Files\PowerShell\Modules\WindowsCompatibility\1.0.0\WindowsCompatibility.psd1' was not processed because no valid module was found in any module directory.
        HResult : -2147024894
    Source         : System.Management.Automation
    HResult        : -2146233079
    StackTrace     :
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData,
ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options,
Boolean& containedErrors) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs:line 3120
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData,
ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options,
Boolean& containedErrors) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs:line 3139
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,
ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs:line 5630
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String
prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs:line 5505
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(String moduleBase, ManifestProcessingFlags manifestProcessingFlags, ImportModuleOptions
importModuleOptions, Boolean& found) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs:line 455
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options,
ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ModuleCmdletBase.cs:line 381
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\Modules\ImportModuleCommand.cs:line 824
TargetObject          : WindowsCompatibility
CategoryInfo          : ResourceUnavailable: (WindowsCompatibility:String) [Import-Module], PSInvalidOperationException
FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        :
    MyCommand        : Import-Module
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 11
    Line             : ipmo WindowsCompatibility -Force
    Statement        : ipmo WindowsCompatibility -Force
    PositionMessage  : At line:1 char:1
                       + ipmo WindowsCompatibility -Force
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : ipmo
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
      0
      1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.3
PSEdition                      Core
GitCommitId                    7.5.0-preview.3-37-gec3840d6a1fffdbaca7173ededb4a4504b2f5b41
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/16168755/562c9dd3-1b87-4eeb-9522-88e0201cd604)

**Comment by mklement0** [comment] 2024-06-27 20:50
Note that the [WindowsCompatibility module](https://github.com/PowerShell/WindowsCompatibility) is obsolete (it was designed for  t PS _v6_ , and is now archived; arguably, it should be hidden from the PowerShell Gallery or clearly marked as obsolete).

Its functionality has been folded into PowerShell itself, so there is no longer a need for it.

And, in general, I think it's preferable that something like `using namespace System.Management.Automation.` _not_ be accepted.

**Comment by kborowinski** [comment] 2024-06-27 21:31
@mklement0:
1. Yeah, it makes sense. I have a function that exports *Scoop* environment from online system to disconnected system, that needs to run some code from *PS Core* session on *Windows PowerShell*, and I was using `Invoke-WinCommand` to accomplish that. I'll refactor this code to use `New-PSSession -UseWindowsPowerShell` instead.
2. I also agree that the `WindowsCompatibility` module should be retired, the only concern I have that there might be some code in the wild that has `using namespace` statements with extra trailing dot that _will_ fail to work on *PS 7.5.0* once it is released as stable - I guess that it should be clearly stated in the release docs as breaking change so users are aware.

**Comment by SteveL-MSFT** [comment] 2024-07-01 21:54
It's surprising for that trailing period to be there, but I see it in the psm1 source.  The WinCompat module is deprecated and the repo is archived and no longer supported.  As noted, there are other supported solutions.

**Closed** 2024-07-03 00:30 UTC
Labels: WG-Engine, Resolution-External, Breaking-Change, PowerShell-Docs needed

**Comment by lpdcunha** [comment] 2025-04-07 21:45
I'm getting a similar error. 
Seems to be **apostrophe** in my name on the path when doing **`Import-Module WindowsCompatibility`**

![Image](https://github.com/user-attachments/assets/b571ea64-6175-4a43-9e89-e5fff0f7fce1)
