### ISSUE TITLE
Pester fails to generate logs after changes to error format

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10809] opened 2019-10-16 19:34 UTC
# Steps to reproduce

cc @SteveL-MSFT 

https://powershell.visualstudio.com/PowerShell/_build/results?buildId=35225&view=ms.vss-test-web.build-test-results-tab

# Expected behavior

Pester logs should be generated

# Actual behavior

```none
Exception             : System.Management.Automation.MethodInvocationException:
                         Exception calling "WriteElementString" with "2" 
                        argument(s): "'', hexadecimal value 0x1B, is an 
                        invalid character."
                         ---> System.ArgumentException: '', hexadecimal value 
                        0x1B, is an invalid character.
                           at 
                        System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 
                        ch, Byte* pDst, Boolean entitize)
                           at System.Xml.XmlUtf8RawTextWriter.WriteElementTextB
                        lock(Char* pSrc, Char* pSrcEnd)
                           at 
                        System.Xml.XmlUtf8RawTextWriter.WriteString(String 
                        text)
                           at 
                        System.Xml.XmlWellFormedWriter.WriteString(String text)
                           at CallSite.Target(Closure , CallSite , XmlWriter , 
                        String , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps
                        .CheckActionPreference(FunctionContext funcContext, 
                        Exception exception)
                           at System.Management.Automation.Interpreter.ActionCa
                        llInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTry
                        CatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTry
                        CatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTry
                        CatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ArgumentException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Write-NUnitTestCaseAttributes, /Users/vsts/agent/2.1
                        58.0/work/1/a/bins/publish/Modules/Pester/4.8.0/Functio
                        ns/TestResults.ps1: line 423
                        at Write-NUnitTestCaseElement, /Users/vsts/agent/2.158.
                        0/work/1/a/bins/publish/Modules/Pester/4.8.0/Functions/
                        TestResults.ps1: line 342
                        at Write-NUnitTestSuiteElements, /Users/vsts/agent/2.15
                        8.0/work/1/a/bins/publish/Modules/Pester/4.8.0/Function
                        s/TestResults.ps1: line 212
                        at Write-NUnitTestSuiteElements, /Users/vsts/agent/2.15
                        8.0/work/1/a/bins/publish/Modules/Pester/4.8.0/Function
                        s/TestResults.ps1: line 190
                        at Write-NUnitTestResultChildNodes, /Users/vsts/agent/2
                        .158.0/work/1/a/bins/publish/Modules/Pester/4.8.0/Funct
                        ions/TestResults.ps1: line 138
                        at Write-NUnitReport, /Users/vsts/agent/2.158.0/work/1/
                        a/bins/publish/Modules/Pester/4.8.0/Functions/TestResul
                        ts.ps1: line 103

                        at Export-NUnitReport, /Users/vsts/agent/2.158.0/work/1
                        /a/bins/publish/Modules/Pester/4.8.0/Functions/TestResu
                        lts.ps1: line 72
                        at Export-PesterResults, /Users/vsts/agent/2.158.0/work
                        /1/a/bins/publish/Modules/Pester/4.8.0/Functions/TestRe
                        sults.ps1: line 38
                        at Invoke-Pester<End>, /Users/vsts/agent/2.158.0/work/1
                        /a/bins/publish/Modules/Pester/4.8.0/Pester.psm1: line 
                        1163
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      : 

```

# Environment data

```none

```

**Comment by SteveL-MSFT** [comment] 2019-10-21 21:27
I expect https://github.com/PowerShell/PowerShell/pull/10814 to workaround this for now.  The problem is that Pester isn't escaping the ESC character being used by VT escape sequences.

**Comment by iSazonov** [comment] 2019-11-26 10:19
Can we close this?

**Closed** 2019-11-26 22:54 UTC
Labels: Issue-Question, Resolution-Fixed
