### ISSUE TITLE
Custom prompt with newline on macOS gets corrupted on entry

### ISSUE THREAD

**Issue by eamodio** [PowerShell/PowerShell#2770] opened 2016-11-23 14:53 UTC
Steps to reproduce
------------------

1. Have a custom prompt with a new line:
  ```
~/foo
> |
  ```
1. All looks fine, but as soon as you start to type, the `>` will start being replaced by the line above (assuming you typed q):
  ```
~/foo
~/q
  ```

Expected behavior
-----------------

  ```
~/foo
> q
  ```

Actual behavior
---------------

  ```
~/foo
~/q
  ```

Environment data
----------------

macOS Sierra `10.12.1 (16B2555)`

```powershell
> $PSVersionTable
Name                           Value                                               
----                           -----                                               
PSVersion                      6.0.0-alpha                                         
PSEdition                      Core                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                             
BuildVersion                   3.0.0.0                                             
GitCommitId                    v6.0.0-alpha.13                                     
CLRVersion                                                                         
WSManStackVersion              3.0                                                 
PSRemotingProtocolVersion      2.3                                                 
SerializationVersion           1.1.0.1   
```

**Comment by astla42** [comment] 2016-11-27 23:57
I'm having a similar issue, with a custom prompt() function and Write-Output $outputStr -NoNewLine.

## Expected Behavior
`(0) /Users/aaron # <insert command here>`

## Actual Behavior
`PS>               <insert command here>`

## Steps to reproduce
Powershell profile with this prompt:

    function prompt() {
        $outputStr = '('
        $outputStr += $(Get-History).Count
        $outputStr += ') '
     
        $outputStr += $(Get-Location)
        $outputStr += ' # '

        write-output $outputStr -NoNewLine

       return ' '
    }

And then type a command.

## More Info
The prompt is getting replaced with PS> and enough spaces to put the cursor back in the right spot. 

## Versions
    Name                           Value                                                                                   
    ----                           -----                                                                                   
    PSVersion                      6.0.0-alpha                                                                             
    PSEdition                      Core                                                                                    
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
    BuildVersion                   3.0.0.0                                                                                 
    GitCommitId                    v6.0.0-alpha.13                                                                         
    CLRVersion                                                                                                             
    WSManStackVersion              3.0                                                                                     
    PSRemotingProtocolVersion      2.3                                                                                     
    SerializationVersion           1.1.0.1  

Also observed on v6.0.0-alpha.12.

OS X 10.11.6 (15G1108)

**Comment by rkeithhill** [comment] 2016-11-28 00:10
@astla42 I think you have an error in your prompt function  Write-Output does not take a -NoNewline parameter.  You probably meant to use Write-Host.  However, you can simplify your prompt to:
```powershell
function prompt {
    "($((Get-History).Count)) $(Get-Location) # "
}
```
Folks use Write-Host to get colored text in their prompt e.g.:
```powershell
function prompt {
    Write-Host "($((Get-History).Count)) " -NoNewline
    Write-Host "$(Get-Location)" -ForegroundColor Cyan -NoNewline
    Write-Host " # " -NoNewline
    ' '
}
```

**Comment by astla42** [comment] 2016-11-28 00:27
Yep, seems like I was doing that part wrong. The NoNewLine was leftover from other testing with my profile on Windows, which has more detail (such as connected vCenters, from PowerCLI) and colors for more readability. I was also testing between write-host and write-output, which is where that came from.

**Comment by lzybkr** [comment] 2016-11-28 23:19
@eamodio - this looks like https://github.com/lzybkr/PSReadLine/issues/468
If you're using `Write-Host`, I'll just close this as a duplicate.

**Closed** 2016-11-29 18:06 UTC
Labels: Area-PSReadLine, Resolution-Duplicate

**Comment by eamodio** [comment] 2016-11-29 18:38
@lzybkr Sorry but I forgot I had avoided Write-Host and just have the following:
```ps
function global:prompt {
    $realLASTEXITCODE = $LASTEXITCODE
    $p = Write-VcsStatus
    $global:LASTEXITCODE = $realLASTEXITCODE

    $path = $pwd.ProviderPath -replace $Env:HOME, "~"
    if ($GitPromptSettings.PromptOnNewLine) {
        return "$path$p`n> "
    }
    else {
        return "$path$p> "
    }
}
```

**Comment by daxian-dbw** [comment] 2017-05-26 19:18
The original issue should be fixed by https://github.com/PowerShell/PowerShell/pull/3867.
Please note that escape sequences are not supported by PSReadline on Unix (see the "`Additional Info`" section of the PR description body).
