### ISSUE TITLE
Cannot parse the JSON. eror

### ISSUE THREAD

**Issue by rhwork** [PowerShell/PowerShell#21338] opened 2024-03-13 11:47 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running the examples on: 
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json?view=powershell-7.4

Basic example:
"{'name': 'Ashley', 'age': 25}" | Test-Json

### Expected behavior

```console
As per the documentation:

"{'name': 'Ashley', 'age': 25}" | Test-Json

True
```

### Actual behavior

```console
Line |
   1 |  "{'name': 'Ashley', 'age': 25}" | Test-Json
     |                                    ~~~~~~~~~
     | Cannot parse the JSON.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment] 2024-03-13 13:20
Change the quote characters

```
'{"name": "Ashley", "age": 25}' | Test-Json
```

**Comment by mklement0** [comment] 2024-03-13 14:06
Yes, this behavior is unfortunate, and was first discussed in:

* #20782

In short:

* `Test-Json` was switched to using `System.Text.Json` to improve JSON schema support, in [PR #18141](https://github.com/PowerShell/PowerShell/pull/18141), which took effect in v7.4.0.

*  This introduced a problematic asymmetry, in that `Test-Json` now no longer accepts _nonstandard_ JSON (single quotes, barewords, comments), whereas the `NewtonSoft.Json`-based `ConvertFrom-Json` does; e..g, 
`'{ foo: 1 }' | ConvertFrom-Json` succeeds (property name is bareword), whereas 
`'{ foo: 1 }' | Test-Json` now fails.

* For details, see https://github.com/PowerShell/PowerShell/issues/20782#issuecomment-1827031354.

**Comment by 237dmitry** [comment] 2024-03-13 14:14
> '{ foo: 1 }' | Test-Json now fails

Because is it not valid?

**Comment by mklement0** [comment] 2024-03-13 14:22
@237dmitry, it isn't valid in a strict JSON sense, but the point is that _it is accepted by `ConvertFrom-Json`_ (and has always been in PS Core; also, `'{ foo: 1 }' | Test-Json` happily worked up to v7.3.x), and - needless to say - you want `Test-Json` and `ConvertFrom-Json` to use the _same_ rules for deciding what is valid / can be processed.
All the relevant information is in my previous comment and what it links to.

**Comment by 237dmitry** [comment] 2024-03-13 14:43
> it is accepted by ConvertFrom-Json

IMHO, validation and parsing are different tasks. If ConvertFrom-Json eats incorrect json, this is only a plus, an additional convenience.

```
$ '{ foo: 1 }' | ConvertFrom-Json | ConvertTo-Json
{
  "foo": 1
}
```

**Comment by rhwork** [comment] 2024-03-13 14:55
> Change the quote characters
> 
> ```
> '{"name": "Ashley", "age": 25}' | Test-Json
> ```

I eventually came to the same conclusion after playing around with it. It's a documentation issue then.

**Comment by mklement0** [comment] 2024-03-13 15:21
@237dmitry, we're dealing with a _massive breaking change_ between 7.3- and 7.4+ that was probably the _unintended_ fallout from the linked PR, which the fact that the docs still show the _old_ behavior also suggests.

> validation and parsing are different tasks

That is a false dichotomy:
* You want _symmetry_ between the JSON-processing cmdlets _by default_, as has always been the case prior to 7.4
* Yes, it would also be handy to do _strict_ validation, for validating JSON to be passed to consumers known to accept standard JSON only. `Test-Json` now _invariably_ does that. The linked issue discusses a potential `-Strict` switch as an _opt-in_.

If the team officially decides that they're fine with the breaking change, then this indeed becomes a mere _documentation_ issue.

So far, we don't know. 

That said, given that v7.4 is already released, at least the docs for _it_ should be updated to note the de-facto limitation:

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10950

**Comment by gregsdennis** [comment] 2024-03-27 01:12
> If the team officially decides that they're fine with the breaking change, then this indeed becomes a mere documentation issue.

The team have already decided that they're fine with the breaking change, as evidenced by the fact that it was released.  This particular issue was caused by the shift to _System.Text.Json_, which

- was needed in order to support JSON Schema (`Test-Json`) more fully, and
- was a desired direction anyway.

**Comment by mklement0** [comment] 2024-03-27 02:11
@gregsdennis 

>  as evidenced by the fact that it was released.

That in itself is _not_ evidence of a _deliberate decision_.

The absence of the latter  is - truly - evidenced by the fact that this - blatantly breaking - change _wasn't documented as such_ at the time the breaking change was accepted and - clearly insufficiently - documented _at the time_.

That https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10951/files _retroactively_ confirms the - originally inadvertent - side effects of the change provides further evidence.

It is disingenuous:

* not to acknowledge the blatantly breaking, previously unacknowledged breaking change.
* not to disclose the role you played in pushing for the breaking change.

**Comment by gregsdennis** [comment] 2024-03-27 02:45
I was perfectly clear with the Powershell team that there was a breaking change and what those changes were.

It was clearly documented in the release notes.

There is also https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10122 which does document breaking changes occurred, which while [its PR](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10126/files) was merged _after_ my PR, was still before the 7.4 release and very clearly indicates that the Newtonsoft JSON extensions will no longer be supported.

I'm sorry that you feel that it was _inadequately_ documented and that, yes, some corrections like that example were missed, but to say it wasn't considered or remained undocumented is incorrect.

**Comment by mklement0** [comment] 2024-03-27 03:05
> some corrections like that example were missed

Your response indicates that you are not aware of the magnitude of the breaking change and the troubling inconsistency with `ConvertFrom-Json` it introduced.

The issue isn't that you didn't notify the team and that there wasn't _some_ announcement of _a_ breaking change,
the issue is that it amounted to a _fundamental_ breaking change _whose scope seemingly no one was aware of at the time_.

While the [retroactive, coy, acknowledgement of this fundamentally breaking change](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10951/files) ("Only supports strictly conformant JSON") - way _after_ than the change you link to, and only in response to https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10950, prompted by _this_ issue  - is better than _not_ acknowledging it, it is still a troubling change that should be acknowledged as such.

**Comment by gregsdennis** [comment] 2024-03-27 03:14
> Your response indicates that you are not aware of the magnitude of the breaking change and the troubling inconsistency with ConvertFrom-Json it introduced.

I asked about updating the remaining JSON support to _System.Text.Json_ while I was constructing my PR, and their decision was to update the other cmdlets at a later time.

**Comment by mklement0** [comment] 2024-03-29 01:57
> I asked about updating the remaining JSON support to System.Text.Json while I was constructing my PR, and their decision was to update the other cmdlets at a later time.

* What happened _behind the scenes_ is ultimately immaterial with respect to addressing problems that need addressing.

* However, your statement again reinforces the suspicion that _no one was aware of the magnitude of the breaking change_, given that updating `ConvertFrom-Json` to use `System.Text.Json` would be an even _bigger_ unacceptable breaking change. (That not more people complained about the fundamentally breaking change in `Test-Json` is probably a testament to its infrequent use.)


Mistakes happen, such as missing the bigger picture when accepting a seemingly _narrowly_ breaking change that, as an unanticipated, unintended side effect - actually amounts to a much more fundamentally breaking one.

However, once such a mistake has happened and has been pointed out and understood as such, it is important to take responsibility and re-assess the situation.

**Comment by kartonrad** [comment] 2024-04-08 09:01
A script i am using hase stopped functioning, as Applications such as WIndows Terminal may output JSON with Trailing Commas.

IS there a way to turn off strict parsing or revert this change?

ConverFrom-Json has thrown an error on a trailing comma

**Comment by kartonrad** [comment] 2024-04-08 09:02
I am a bit taken aback that this was changed at all - seems like pushing for a fix to a fictional problem, that has now caused real problems

It doesnt even seem like there is a flag to revert the behaviour to a working state - is there a working tool i can install from somewhere that will work?

**Comment by mklement0** [comment] 2024-04-08 18:23
@kartonrad, as for _workarounds_ (which, to be clear, shouldn't be necessary):

* In case you only need _syntax_ validation - and not also validation against a _schema_ -  you can call `ConvertFrom-Json` and deduce validity based on whether the latter reports an error or not.

```powershell
& {
  param($json)
  try { $null = $json | ConvertFrom-Json; $true } catch { $false; $_ | Write-Error }
} '{ "foo": 42, }'
```

* If you need schema validation too, you'll essentially have to round-trip the input JSON to produce standard JSON first, which you can then pass to `Test-Json`:

```powershell
& {
    param($json, $schema)
    try {
      Test-Json -Schema $schema -Json ($json | ConvertFrom-Json | ConvertTo-Json -Compress -Depth 100)
    } catch { $false; $_ | Write-Error }
} '{ "foo": 42, }' '{ "properties": { "foo": { "type": "number" } } }'
```

**Comment by kartonrad** [comment] 2024-04-08 20:21
Thank you so much!! :)

**Comment by SteveL-MSFT** [comment] 2024-04-17 16:45
@PowerShell/wg-powershell-cmdlets reviewed this, we understand the user experience when using PowerShell to more naturally switch the single and double quotes in the JSON particularly when using variable expansion.  However, we also believe that `Test-Json` should adhere to the standards (making the JSON portable) while `ConvertFrom-Json` is more lenient allowing for a more pragmatic and user friendly approach.  Examples in the docs need to work and should be fixed.  There is an open [dotnet issue](https://github.com/dotnet/runtime/issues/32291) discussion enabling more lenient parsing which can be exposed as parameters to `Test-Json` in the future.

**Closed** 2024-04-18 23:50 UTC
Labels: Resolution-Won't Fix, WG-Cmdlets-Core, WG-Reviewed
