### ISSUE TITLE
Unexpected exception is thrown in PropertyAccessor.cs, line 138. 

### ISSUE THREAD

**Issue by lilyfang** [PowerShell/PowerShell#2205] opened 2016-09-07 23:29 UTC
Steps to reproduce
------------------
In CentOS7, Setup and run PSRP remote scenario by following instructions at https://github.com/powershell/psl-omi-provider. 

Expected behavior
-----------------
No exception is thrown. If needed, return a proper error.   

Actual behavior
---------------
Hit exception as below when trying to login remotely from a windows client, 
 PS C:\windows\system32> Enter-PSSession -ComputerName li-cent7 -Credential $cred -Authentication neg
otiate -SessionOption $o
Enter-PSSession : The type initializer for 'System.Management.Automation.ConfigPropertyAccessor'
threw an exception.
At line:1 char:1
+ Enter-PSSession -ComputerName li-cent7 -Credential $cred -Authenticat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enter-PSSession], TypeInitializationException
    + FullyQualifiedErrorId : RemoteRunspaceStateInfoReason

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

After debugging, the exception is thrown in PropertyAccessor.cs, line 138.  When PSRP tries to CreatDirectory /root/.config/powershell under root at GetCurrentUserConfigDirectory(). It is inconsistent that the logic catches the exception at JsonConfigFileAccessor(), but not GetCurrentUserConfigDirectory(). 

        internal JsonConfigFileAccessor()
        {
            //
            // Sets the system-wide configuration directory
            //
            Assembly assembly = typeof(PSObject).GetTypeInfo().Assembly;
            psHomeConfigDirectory = Path.GetDirectoryName(assembly.Location);

            //
            // Sets the per-user configuration directory
            //
            appDataConfigDirectory = Utils.GetUserConfigurationDirectory();
            if (!Directory.Exists(appDataConfigDirectory))
            {
                try
                {
                    Directory.CreateDirectory(appDataConfigDirectory);
                }
                catch (UnauthorizedAccessException)
                {
                    // Do nothing now. This failure shouldn't block initialization
                    appDataConfigDirectory = null;
                }
            }
        }

        /// <summary>
        /// Enables delayed creation of the user settings directory so it does 
        /// not interfere with PowerShell initialization
        /// </summary>
        /// <returns>Returns the directory if present or creatable. Throws otherwise.</returns>
        private string GetCurrentUserConfigDirectory()
        {
            if (null == appDataConfigDirectory)
            {
                string tempAppDataConfigDir = Utils.GetUserConfigurationDirectory();
                if (!Directory.Exists(tempAppDataConfigDir))
                {
                    Directory.CreateDirectory(tempAppDataConfigDir);
                    // Only assign it if creation succeeds. It will throw if it fails.
                    appDataConfigDirectory = tempAppDataConfigDir;
                }
                // Do not catch exceptions here. Let them flow up.
            }
            return appDataConfigDirectory;
        }

tempAppDataConfigDir is /root/.config/powershell at the failure case.

**Comment by andschwa** [comment] 2016-09-19 17:40
While this can be reproduced during remoting due to the higher likelihood of HOME not being set (or being set to a non-writable folder), this is not itself a remoting bug.

The `ConfigPropertyAccessor` logic that is meant to read PowerShell configuration values from JSON files *must not* require that user config directory can be created. If it cannot be written, PowerShell should not fail like this.

The XDG Base Directory Specification (which this `UserConfigDirectory` is for) states:

> If, when attempting to write a file, the destination directory is non-existant an attempt should be made to create it with permission 0700. If the destination directory exists already the permissions should not be changed. The application should be prepared to handle the case where the file could not be written, either because the directory was non-existant and could not be created, or for any other reason. In such case it may chose to present an error message to the user.

An error message is acceptable; crashing is not.

**Comment by andschwa** [comment] 2016-09-19 17:41
I'm assigning to @mirichmo for follow-up.

**Comment by damon-atkins** [comment] 2016-09-19 17:58
It would be nice if it check HOME was set, before trying to use it and if not set, display an error message saying please set environment variable home.  I was lucky to notice this was a difference between myself running it as a user and a service running it.

**Comment by andschwa** [comment] 2016-09-19 18:42
Ah but PowerShell should be able to run even without `HOME` being set, as there are applicable scenarios where this is the correct environment (say, running as a daemon, or started by cron under a user with a non-existent home directory). So instead of erroring, I think it should just run without a problem (and error gracefully when it needs to write something but can't).

**Comment by daxian-dbw** [comment] 2016-10-08 04:46
closed via #2387

**Closed by daxian-dbw** 2016-10-08 04:46 UTC
Labels: 3 - Working, Area-SideBySide, Issue-Bug, OS-Linux

**Comment by vinodc** [comment] 2017-01-11 06:37
@andschwa @mirichmo I'm continuing to encounter this error with the latest alpha release on Ubuntu 14.04 when HOME is unset. I expected running it with -NoProfile would prevent Powershell from attempting to load settings, but I could be mistaken on what that flag controls. Is this error still expected on Ubuntu 14.04 even though #2387 is merged in?

    $ unset HOME
    $ powershell
    PowerShell
    Copyright (C) 2016 Microsoft Corporation. All rights reserved.

    The shell cannot be started. A failure occurred during initialization:
    The type initializer for 'System.Management.Automation.ConfigPropertyAccessor' threw an exception.

Environment info:

```
PS /home/kloudless> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mirichmo** [comment] 2017-01-11 23:41
@vinodc Can you please attach the stack trace from the exception?

Based on code inspection, I suspect that this is the [offending line](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L237). My guess is that it is an ArgumentNullException stating that the argument to Path.Combine is null since "HOME" is not defined.

**Comment by andschwa** [comment] 2017-01-12 00:35
I believe that's #1794.

**Comment by vinodc** [comment] 2017-01-12 00:46
@mirichmo That's all the output that was provided. Was there a way to obtain the stack-trace from the alpha release? I'm not sure if it was compiled with debugging symbols. Would I need to compile it from source to generate a Debug build instead?

**Comment by mirichmo** [comment] 2017-01-12 00:58
Hmmmm... if PowerShell had started, you could use `$Error[0] | fl * -Force`. Debugging it in VS Code and stopping at the exception throw point would provide the answer.

With that said, I'm pretty certain that this is a simpler reproduction of #1794 and no additional information is needed.
