### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by microlaser** [PowerShell/PowerShell#14785] opened 2021-02-12 18:48 UTC
## Steps to reproduce

```powershell
If you run the command select-string -context and filter it with a pipe it will not let you run select-string -context again after the pipe.  This seems counter intuitive and if you could filter like that it would be useful 
```

## Expected behavior

Application of a second text filter 

```

## Actual behavior

I am told it is not allowed 

```

## Environment data

5.1.18362.1171
Desktop 

```

**Comment by mklement0** [comment] 2021-02-12 20:35
To be clear up front: You likely won't see improvements in _Windows PowerShell_  - please note that this repo is only for PowerShell Core 6 and PowerShell 7+ issues.

In a pinch, you can pipe to `Out-String -Stream` before piping to the 2nd `Select-String` call, but note that this will retain the formatting artifacts, notably the `>` before the matching line and a space before the context lines.

---

There are two related issues:

* `Select-Object -Context ... | Select-Object ...` causes the context information in the first command's output objects to be quietly ignored by the second command.

* Additionally, `Select-Object -Context ... | Select-Object -Context ...`, i.e. using `-Context` with _both_ commands causes the `-Context` parameter to also be ignored by the 2nd command, accompanied by warning `The option "Context" is not valid when searching results that are piped from Select-String output.`

I can't speak to the original design intent, but the behavior seems unhelpful.

The code at https://github.com/PowerShell/PowerShell/blob/ac560d8d320f3ba72e525825be2c64d9c5abdf2c/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L1740-L1757

* suggests that only looking at the `.Line` property of  incoming `Microsoft.PowerShell.Commands.MatchInfo`  instance - instead of also considering `.PreContext` and `.PostContext` -  is intentional.

* additionally restricting the use of `-Context` in the _receiving_ command seems curious, however: perhaps this was a _logic error_, where the actual intent was solely to warn about the _incoming_ context information getting ignored?

---

A similar issue arose in combination with the `-Raw` switch (not available in Windows PowerShell), which which outputs just the matching _lines_ rather than `Microsoft.PowerShell.Commands.MatchInfo` objects:

Here too the intuitive expectation is that combining `-Raw` with `-Context` would also output the context lines, which isn't the case either, unfortunately, as reported in #14350.

**Comment by mklement0** [comment] 2021-02-12 20:36
P.S., @microlaser, can you please give your issue a meaningful title, for better discoverability?

**Comment by mklement0** [comment] 2021-02-15 19:17
I realized I misinterpreted the current behavior and design intent, so here's the hopefully correct summary, based on https://github.com/PowerShell/PowerShell/blob/ac560d8d320f3ba72e525825be2c64d9c5abdf2c/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L1740-L1757 and experimenting with commands:

* By (debatable) design, when `Select-String` receives input from _another_ `Select-String` call, it acts as a filter on the `Microsoft.PowerShell.Commands.MatchInfo` _objects_ received as input rather than on the _text_ context_ they represent:

  * The filtering is solely based on the `.Line` property value of the input objects, not also on the lines contained in the `.Context` property, if present.

  * Due to this match-info-_object_-filtering approach, the receiving `Select-String` call doesn't support a `-Context` argument itself  so it is ignored, but a warning is issued.
    * While context resulting from a `-Context` argument passed to the _sending_ `Select-String` _is_ passed through - if the `.Line` property value matches the filter - there is a _display bug_, in that the context lines passed through do not show up in the formatted output anymore; e.g.:

         * `1..5 | Select-String 3 -Context 1 | Select-String 3` outputs just `> 3`, not `  2\n> 3\n  4`, as the original command would; the problem is connected to the `.Context.DisplayPreContext` and `.Context.DisplayPostContext` values not getting preserved on filtering.

---

The upshot is:

* The current behavior when chaining `Select-String` calls is unhelpful, in two respects:

  * It doesn't consider context lines when filtering in the receiving `Select-String` command.
  * The receiving `Select-String` command doesn't support `-Context` (your original complaint).

---

What _would_ be helpful if receiving `Select-String` calls solely operated on the _strings_ represented by the input objects, notably _including_ the context lines, but _without duplicates_ from overlapping contexts - as you currently already see in the _formatted_ output from non-chained calls (formatting markup aside).

A similar issue arose in combination with the `-Raw` switch (not available in Windows PowerShell; its purpose is to output just the matching _lines_ (text) rather than `Microsoft.PowerShell.Commands.MatchInfo` objects):

Here too the intuitive expectation is that combining `-Raw` with `-Context` should also output the context lines without duplicates, which isn't the case either, unfortunately, as reported in #14350.

---

To me, these changes would undoubtedly be helpful, but at least in the non-`-Raw` case they do amount to a _breaking change_, so the question is whether it is an _acceptable_ breaking change, namely one that falls into [bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).

**Comment by daxian-dbw** [comment] 2021-02-19 01:11
@mklement0 Can you please move your comment to a new issue with a meaning title? I will close this one given that the PR title and description are not helpful.

**Comment by mklement0** [comment] 2021-02-19 02:24
@daxian-dbw, please see #14850

**Comment by mklement0** [comment] 2021-02-19 13:00
@daxian-dbw, given that the current behavior is (mostly) by design (but somewhat unhelpful), the new issues is of type "Issue-Enhancement", not a bug report. I have adde sample commands that demonstrate the unhelpful behavior, however (in the context of the current behavior there is also a small bug, but fixing that will be moot, if the behavior is more fundamentally revised).

**Comment by daxian-dbw** [comment] 2021-02-22 19:14
Thank you @mklement0!

**Closed by daxian-dbw** 2021-02-22 19:14 UTC
Labels: Needs-Triage
