### ISSUE TITLE
Ctrl + C become unusable if when it was first used the keyboard wasn't on English

### ISSUE THREAD

**Issue by ili101** [PowerShell/PowerShell#17181] opened 2022-04-23 00:47 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Tested on Windows 10/11 with PS 7.2 and 5.1 with the default PS terminal, "Terminal" and VSCode.
Set your keyboard to a language that don't have the Latin alphabet, for example add Hebrew keyboard in the windows settings in addition to the English one.
1. Start PowerShell.
2. Set keyboard to the other language (like with `Alt + Shift` or in the taskbar).
3. Press `Ctrl + C` (or `Ctrl + <Any letter>`).
4. Terminal will print the letter (or something like � if the font doesn't have it) instead of the expected `^C`.
5. Even if you switch back to English and `Ctrl + C` it will still print the letter from the other language.

I didn't find a way to "fix" the session to make `Ctrl + C` work, only thing you can do is close it, open a new one and making sure the first  `Ctrl + C` you make is in English.

### Expected behavior
`^C` always executed no matter what is your current active keyboard or what keyboard was active when it was first typed. Like in CMD for example.
```console
PS C:\> ^C
PS C:\>
```

### Actual behavior
`Ctrl + C` become unusable for the rest of the session if when it first used the keyboard wasn't on English.
```console
PS C:\> ב
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Animation](https://user-images.githubusercontent.com/6960531/164839296-6110cbfe-e044-4983-aec7-6925f885ad99.gif)

**Comment by 237dmitry** [comment] 2022-04-23 12:12
It's hard to say this is the problem with pwsh or the terminal or Windows OS. For example, in tilix (linux) everything works regardless of the current keyboard layout (not latin based).

**Comment by daxian-dbw** [comment] 2022-05-05 21:52
This looks like a duplicate of https://github.com/PowerShell/PSReadLine/issues/1393.
It only occurs in some Cyrillic keyboard layout, but not all.

**Closed by daxian-dbw** 2022-05-05 21:52 UTC
Labels: Needs-Triage
