### ISSUE TITLE
Web Cmdlets strip ContentType header on GET requests even with -SkipHeaderValidation

### ISSUE THREAD

**Issue by rmbolger** [PowerShell/PowerShell#9574] opened 2019-05-09 19:49 UTC
I have an API that expects to receive a `Content-Type` header in a particular GET request. When it does not get that header, it returns an HTTP 415 'Unsupported Media Type' response. I realize this API is probably non-conforming to the HTTP spec. Under normal circumstances, it is probably correct that PowerShell strips the `Content-Type` header from GET requests. However, the [docs for `SkipHeaderValidation`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest) make it seem like that would be a workaround.

> This switch should be used for sites that require header values that do not conform to standards. Specifying this switch disables validation to allow the value to be passed unchecked. When specified, all headers are added without validation.

> This will disable validation for values passed to the -ContentType, -Headers and -UserAgent parameters.

It should be noted that the API call works and the Content-Type header is passed normally in Windows PowerShell 5.1 despite the lack of the SkipHeaderValidation parameter.

# Steps to reproduce

```powershell
(Invoke-WebRequest https://httpbin.org/get -ContentType 'application/force-download' -SkipHeaderValidation).Content

# or

(Invoke-WebRequest https://httpbin.org/get -Headers @{'Content-Type'='application/force-download'} -SkipHeaderValidation).Content
```

# Expected behavior

```none
{
  "args": {},
  "headers": {
    "Content-Type": "application/force-download",
    "Host": "httpbin.org",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.17134; en-US) PowerShell/6.2.0"
  },
  "origin": "xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx",
  "url": "https://httpbin.org/get"
}
```

# Actual behavior

```none
{
  "args": {},
  "headers": {
    "Host": "httpbin.org",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.17134; en-US) PowerShell/6.2.0"
  },
  "origin": "xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx",
  "url": "https://httpbin.org/get"
}
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

@markekraus

**Comment by vexx32** [comment] 2019-05-09 20:02
/cc @markekraus 

From what I remember of some recent issues, there's an issue (by design? I'm not sure) where the cmdlet ignores `Content-Type` headers and the parameter when `-Body` is not set on the request.

**Comment by markekraus** [comment] 2019-05-09 23:07
Duplicate of  #9473 closing

**Closed by markekraus** 2019-05-09 23:07 UTC
Labels: Issue-Question

**Comment by markekraus** [comment] 2019-05-09 23:08
For clarity, its the same underlying issue that causes both of these behaviors.

**Comment by rmbolger** [comment] 2019-05-09 23:44
Setting an empty body does indeed workaround the problem. Ironically, the empty body causes a ProtocolViolationException on Windows PowerShell 5.1. But I can work around that too.
