### ISSUE TITLE
 Could not load file or assembly 'mscorlib' on macOS

### ISSUE THREAD

**Issue by richardszalay** [PowerShell/PowerShell#4471] opened 2017-08-03 00:49 UTC
I'm setting up CI to ensure my assembly-based module ([PsHosts](https://github.com/richardszalay/pshosts)) runs on Linux and macOS. The process builds on Appveyor/Windows since I'm targetting .NET 4.0 (for compat back to PS3) - the TravisCI builds then install the module from a MyGet feed and run the pester tests.

The Appveyor and Travis _Linux_ builds are both fine, but on Travis macOS calling any of the Cmdlets inside the assembly throw an error:

> Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

Is this a known issue on macOS? Should I just hold off testing on macOS until a particular release/milestone?

I'm using PowerShell's `install-powershell.sh` to bootstrap PS in the Travis builds.

Links to build logs if you're interested:

- [Windows](https://ci.appveyor.com/project/richardszalay/pshosts/build/1.0.24)
- [Linux](https://travis-ci.org/richardszalay/pshosts/jobs/260027318)
- [macOS](https://travis-ci.org/richardszalay/pshosts/jobs/260027319)

**Comment by daxian-dbw** [comment] 2017-08-04 18:11
I downloaded the v1.2.1 from https://github.com/richardszalay/pshosts/releases, and it works fine on my MacBook with beta.5:
```
PS:3> Import-Module /Users/usr/Downloads/PsHosts                                                                   
PS:4> gmo                                                                                                                  

ModuleType Version    Name                                ExportedCommands                                                
---------- -------    ----                                ----------------                                                
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...} 
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}       
Binary     1.2.1      PsHosts                             {Add-HostEntry, Disable-HostEntry, Enable-HostEntry, Get-Host...
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSRea...

PS:5> $result = Add-HostEntry -Name "hostname" -Address "10.10.10.10"                                                      
PS:6> $result                                                                                                              

Name                             Address                          Enabled 
----                             -------                          ------- 
hostname                         10.10.10.10                      True    

PS:7> Get-HostEntry                                                                                                        

Name                             Address                          Enabled 
----                             -------                          ------- 
broadcasthost                    255.255.255.255                  True    
hostname                         10.10.10.10                      True    

PS:8> $PSVersionTable                                                                                                      

Name                           Value                                                                                      
----                           -----                                                                                      
PSVersion                      6.0.0-beta                                                                                 
PSEdition                      Core                                                                                       
GitCommitId                    v6.0.0-beta.5                                                                              
OS                             Darwin 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789....
Platform                       Unix                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                    
PSRemotingProtocolVersion      2.3                                                                                        
SerializationVersion           1.1.0.1                                                                                    
WSManStackVersion              3.0
```

/cc @TravisEz13 maybe something with the `install-powershell.sh` script and the environment setup?

**Comment by TravisEz13** [comment] 2017-08-04 21:30
I created a clean macOS VM and installed PowerShell using `install-powershell.sh` and it also worked.

**Comment by richardszalay** [comment] 2017-08-04 21:42
Strange. I'll try to follow it up with the Travis CI guys, but failing that I'll just have to list macOS as unsupported.

**Comment by TravisEz13** [comment] 2017-08-04 21:42
I went to try to run your CI to see if I can repro the problem but I cannot.  You don't seem to build your module in your CI (see [Practices of CI](https://martinfowler.com/articles/continuousIntegration.html#PracticesOfContinuousIntegration)).  You just get the module from a gallery here:
https://github.com/richardszalay/pshosts/blob/master/build/travis.ps1#L1
and the location isn't declared in the `travis.yml`

Perhaps there is a difference between the module in the releases section and in this gallery?

**Comment by richardszalay** [comment] 2017-08-04 21:58
Conceptually there could be a difference as the MyGet version is built in AppVeyor (despite using the can't build process). I think I'm using the VS2017 image in order to get access to WM5 (to patch the version number with Update-ModuleManifest). Could that be related?

The strange thing is it all runs fine in Travis' Linux build.

**Comment by richardszalay** [comment] 2017-08-04 22:00
(I can't build the module on Linux because I still support PS3, which is net40. I'll eventually drop that for a new major version)

**Comment by TravisEz13** [comment] 2017-08-04 22:12
What about having an AppVeyor build to build the net40 version and use their [project NuGet feed](https://www.appveyor.com/docs/nuget/#project-nuget-feeds) as a PowerShell Gallery to host the dev version of the module?  Then you could make the URL of the feed public.  We do this in our PS DSC Resource repos.

**Comment by richardszalay** [comment] 2017-08-04 22:25
I started in that direction but got blocked by the project feed being read only apart from automatically publishing .nupkg files, but no documented way of package a PS module as a nupkg (I dug through the PsGet source for an exported cndlet, but to no avail). If you can shoot me a link to docs or an example, I'm happy to do that instead.

Here's the public myget feed link if it helps: https://www.myget.org/F/pshosts

**Comment by richardszalay** [comment] 2017-08-04 22:26
(eventually the appveyor build will trigger the Travis build via a web hook, buy I'm just trying to get everything working to start with)

**Comment by TravisEz13** [comment] 2017-08-04 22:31
just `register-psrepository` a local path and then `publish-module` to that repository.  Then you can just publish as artifacts all the nupkg's from that folder.

**Comment by richardszalay** [comment] 2017-08-04 22:35
My understanding is that Appveyor won't let you do that, that you can only publish to the project feed by having a nupkg artifact from your build.

**Comment by TravisEz13** [comment] 2017-08-04 22:36
yes, do this during your build.

**Comment by richardszalay** [comment] 2017-08-04 22:39
Will give it a go, though I'm still unsure how this will resolve the macOS issue. I'll let you know how it goes.

**Comment by TravisEz13** [comment] 2017-08-04 22:42
I'm not sure it will solve the macOS issue, but having a public CI definition means that I can run it and repro your problem.  BTW, I tried the MyGe feed and still wasn't able to repro the issue.  We also use Travis-ci for macOS testing.  So, I'm confused at where the difference is.

**Comment by TravisEz13** [comment] 2017-08-04 23:08
We are basically chatting here.  How about we close this issue and chat on gitter (preferred) or twitter.

Gitter:  https://gitter.im/TravisEz13/home
twitter: travisplunk

**Comment by TravisEz13** [comment] 2017-08-05 02:38
Root cause was found, and filed issue #4505

**Closed by TravisEz13** 2017-08-05 02:38 UTC

**Comment by richardszalay** [comment] 2017-08-09 03:02
Confirmed that #4506 fixed the issue. Thanks Travis!
