### ISSUE TITLE
Search progress bar not clearing after the task is done.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2654] opened 2016-11-09 20:47 UTC
Steps to reproduce
------------------
Using following oneliner sample:
PS /home/maxt> Get-Help About* | Select name 

Expected behavior
-----------------
For the search progress bar to cleared after is done.

Actual behavior
---------------
It stay on screen even on the next line.
![searchbarstays](https://cloud.githubusercontent.com/assets/19892435/20154073/bf740022-a693-11e6-954a-9ca8f7d45e99.png)

Environment data
----------------
OS = Ubuntu 16.04.1 LTS Desktop

```powershell
PS /home/maxt> $PSVersionTable                                                  

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.12                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

```

**Comment by iSazonov** [comment] 2016-11-10 05:50
I tested this on _Windows_ with latest commits and there's no problem. So it's seems the issue is only Linux specific.

**Comment by MaximoTrinidad** [comment] 2016-11-10 16:35
Yes! Windows works fine.  But not on Ubuntu Linux. 
:)

**Comment by SteveL-MSFT** [comment] 2016-11-15 20:35
Dupe of #1625

**Comment by iSazonov** [comment] 2016-11-16 04:28
It would be good to check this with the latest builds (after #2640).

**Comment by MaximoTrinidad** [comment] 2016-11-23 00:02
Date: 11/22/2016 - 06:55am
Latest build = v6.0.0-alpha.13 
OS = Ubuntu 16.04.1

Running any command running the progress-bar it will clutter the screen without clearing.

Image showing I ran two oneliners:
Get-Help About* | Select Name
and
Update-Help -Force

The screen didn't cleared leaving previous progress-bar info.

![alph13_progbarissue](https://cloud.githubusercontent.com/assets/19892435/20546831/d5957550-b0e5-11e6-8961-7dfde3d530f1.png)

**Comment by joeyaiello** [comment] 2017-01-25 20:58
Closing as a dupe

**Closed by joeyaiello** 2017-01-25 20:58 UTC
Labels: Area-Cmdlets, OS-Linux, Resolution-Duplicate
