### ISSUE TITLE
在win11中启动powershell 7.2pre6经常会绿屏。

### ISSUE THREAD

**Issue by Thomitics** [PowerShell/PowerShell#15724] opened 2021-07-06 01:03 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1.打开文件夹
2.右键
3.在windows terminal打开

### Expected behavior

```console
正常打开
```

### Actual behavior

```console
绿屏

然后重启
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.7
PSEdition                      Core
GitCommitId                    7.2.0-preview.7
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by rjmholt** [comment] 2021-07-08 16:19
> Starting powershell 7.2pre6 in win11 often results in a green screen. 

Thanks for the bug report. I think we need more information to be able to investigate this on our end, for example the operating system version/build number.

Also, given that the two variables here are the PowerShell version and the Windows version, and that the same PowerShell version does not cause kernel panics on other versions of Windows, this sounds like the bug belongs to Windows rather than PowerShell. Even in the case where PowerShell is the cause of the bug, the operating system should be able to handle an application failure without a kernel panic.

With that in mind, I'll close this issue for now. If you're able to add more information (for example a dump), please let us know (particularly for a dump file, you might need to send that through by other means) and we'll be happy to revisit the issue.

**Closed by rjmholt** 2021-07-08 16:19 UTC
Labels: Needs-Triage
