### ISSUE TITLE
Ensure that all cmdlets that accept a PowerShell version parameter support -PowerShellVersion and -PSVersion interchangeably

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7026] opened 2018-06-08 16:31 UTC
This issue is about ensuring consistent naming of parameters with the same semantics across cmdlets.

Some cmdlets that accept a PS version as an argument have a `-PowerShellVersion` parameter, while others name that parameter `-PSVersion`.

All such cmdlets should accept _either_ name, via parameter aliases.

Only the following cmdlets currently support both names (they're not currently in PS Core):

* `Set-PSSessionConfiguration`, `Register-PSSessionConfiguration`

All others currently support only one _or_ the other:

`-PSVersion` only:

* `Start-Job`

`-PowerShellVersion` only:

* `Get-FormatData`
* `Update-ModuleManifest`
* `New-ModuleManifest`
* `New-PSSessionConfigurationFile` (not currently in PS Core).

Environment data
----------------

Written as of:

```powershell
Windows PowerShell v5.1 / PowerShell Core v6.1.0-preview.2
```

**Comment by BrucePay** [comment] 2018-06-09 00:31
For `Update-ModuleManifest`, `New-ModuleManifest` and `New-PSSessionConfigurationFile`, the parameter `PowerShellVersion` exactly corresponds to a property in the file called `PowerShellVersion`. Adding a `PSVersion` alias to these parameters is unnecessary and misleading.

**Comment by mklement0** [comment] 2018-06-09 01:31
@BrucePay:

>  Adding a PSVersion alias to these parameters is unnecessary and misleading.

I don't think so:

* Either you already _know_ what the resulting property name will be: then you'll use just that (`-PowerShellVersion`) and life is good.

* If you _don't_ know yet, you can use the `-PSVersion` familiar from other cmdlets and trust that the cmdlet will translate it into the correct value.

With respect to `New-PSSessionConfigurationFile` specifically, note that its "sibling" cmdlets `Set-PSSessionConfiguration` and `Register-PSSessionConfiguration` already _do_ accept `-PSVersion`.

Notably, the help for  `New-PSSessionConfigurationFile`'s `-PowerShellVersion` parameter states (emphasis added):

> The value of the **PSVersion** parameter of the Register-PSSessionConfiguration cmdlet takes precedence over the value of the **PowerShellVersion** key in the session configuration file.

**Comment by doctordns** [comment] 2022-05-04 17:16
Is this still an issue the WG should be looking at?  It;'s been nearly 4 years since the issue was raised and I've not seen much community indication that this is much of a problem.

**Comment by doctordns** [comment] 2022-06-01 16:12
The Cmdlet Working Group has reviewed this issue. It recognizes PSVersion should be the appropriate parameter name going forward. The Parameter names cited in the example were for the most part chosen by design. While the group recognizes the value of consistency in PowerShell, retro-fitting parameters, even with aliases, is not a worthwhile investment of development resources. We are marking this issue as won't fix.

**Closed** 2022-06-02 21:00 UTC
Labels: Resolution-Won't Fix, WG-Cmdlets, Issue-Discussion
