### ISSUE TITLE
Exiting pwsh kills the process that was started with Start-Process

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#21149] opened 2024-01-28 08:51 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Start an application from pwsh with Start-Process
2. Exit from pwsh

```
$ Start-Process mousepad   # starts mousepad
$ exit                     # will exit pwsh and kill mousepad
```

This behavior occurs on Linux and Windows.

On Windows it is not always possible to reproduce, depending on the application.

No problem:
```
$ Start-Process notepad
$ exit
```

Hangs console window (conhost), killing it (Ctrl-C) kills alacritty too:
```
$ Start-Process alacritty
$ exit    # hangs, Ctrl-C
```

### Expected behavior

```console
Process started with Start-Process should not depend on pwsh
```

### Actual behavior

```console
Process started with Start-Process terminates when pwsh closes
```

### Error details

```console
No errors
```

### Environment data

```powershell
On Linux: pwsh 7.5.0-preview.1
On Windows: pwsh 7.4.1
```

**Comment by mklement0** [comment] 2024-01-28 14:11
@jborean93 has more in-depth knowledge in this area, but I think this comes down to _platform differences_:

* On _Windows_, a `Start-Process`-launched lives on independently of the PowerShell session that launched it; the only exceptions I'm aware of are:
  * If you run a _console_ application directly in the caller's window with `-NoNewWindow`.
  * In _remoting_, where terminating the remote session also terminates any `Start-Process` launched processes.

* On Unix-like platforms, by contrast, a child process is always killed if its parent is killed (and `-NoNewWindow` is _invariably implied_, because launching a process in a new terminal window is not supported).

  * If you want a process to be detached from the caller, use `Start-Process nohup '...'`

**Comment by mklement0** [comment] 2024-01-28 14:36
Thanks, @rhubarb-geek-nz (the `nohup` example actually originated in the discussion in https://github.com/PowerShell/PowerShell/issues/16001).

Re console-subsystem applications: What you're describing applies to _direct_ invocation, but `Start-Process` by design creates a _new console window_ by default (as such it is the analog to `cmd.exe`'s built-in `start` command), and in local invocations these windows are detached from the caller.

**Comment by 237dmitry** [comment] 2024-01-28 14:48
This is not a good workaround with `/usr/bin/nohup`. Why `rofi`, `dmenu`, any launchers do start processes without nohup?

What about windows? The problem also exists.

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 14:48
> * On Unix-like platforms, by contrast, a child process is always killed if its parent is killed

Is this true? In UNIX you may have a process group sharing a common controlling terminal. When the controlling terminal is disconnected it sends SIGHUP to all processes with that controlling terminal. The default behaviour for SIGHUP is to terminate the process, the program "nohup" breaks this connection by preventing the SIGHUP signal.  Nohup does not actually remove the process from the controlling terminal

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 15:00
> Why `rofi`, `dmenu`, any launchers do start processes without nohup?

Most likely because they are UNIX programs without layers of dotnet and windows compatibility, and simply using [fork](https://man7.org/linux/man-pages/man2/fork.2.html)/[exec](https://man7.org/linux/man-pages/man3/exec.3.html).

**Comment by mklement0** [comment] 2024-01-28 15:08
Similarly, @237dmitry, it may be worth creating a separate feature request for building the functionality of `nohup` directly into `Start-Process` on _Unix_-like platforms - either by default or via a new switch.

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 15:14
If you are not looking for portable code then simply use `bash -c 'command... &'`

```
$ ps
  PID TTY          TIME CMD
30308 pts/0    00:00:00 bash
30578 pts/0    00:00:00 ps
$ pwsh
PowerShell 7.4.1
PS> bash -c 'sleep 10 &'
PS> exit
$ ps
  PID TTY          TIME CMD
30308 pts/0    00:00:00 bash
30607 pts/0    00:00:00 sleep
30654 pts/0    00:00:00 ps
```
shows sleep is still running after powershell exit

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 15:18
One downside of Windows itself is the assumption that everything needs Windows and that command line programs need console windows. Often on a Windows update or an installation of an MSI you get console windows flashing up for fractions of a seconds, it is rather sad.

**Comment by 237dmitry** [comment] 2024-01-28 15:21
> here is no problem on Windows that I'm aware

Conhost window wont be closed until I press `Ctrl-C`. After pressing conhost and alacritty windows close together.

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/869f7f1a-f4f2-46d9-9c24-9bdcfaf0bd5f)

**Comment by 237dmitry** [comment] 2024-01-28 18:46
> simply use bash -c 'command... &'

This works like Start-Process. I'm using a script to launch a new alacritty terminal instance with different profiles (bash, pwsh, mc, htop, musikcube). There are variables and Start-Process is a more convenient way to do this. Using nohup has disadvantages, since it outputs messages to the console, and I have not *__yet__* been able to redirect them to /dev/null.

**Comment by mklement0** [comment] 2024-01-28 18:52
@237dmitry, **what happens _on Windows_** is this:

* `alacritty.exe` is a _GUI_-subsystem application...
* ... which - unusually - _explicitly attaches to the caller's console_ (which allows it to print diagnostic messages to that console with the `--print-events` CLI option, for instance.
* When you `exit` the PowerShell session while the launched Alacritty process is still alive, the latter prevents the console from closing (because Alacritty is still attached to it).
* Forcefully terminating the console - whether via <kbd>Ctrl+C</kbd> or by simply closing the console window - then terminates the Alacritty process too.

The **workaround** is to launch via a hidden aux. console window; e.g.:

```powershell
Start-Process -WindowStyle hidden cmd '/c alacrity --config %APPDATA%\alacritty\pwsh.toml'
```

Pragmatically speaking, you could wrap the above in an `alacritty` function (which takes precedence over the external executable).

As for **what should be done**:

* I'm not sure whether `Start-Process` _can_ or even _should_ try to prevent this scenario.

**Comment by 237dmitry** [comment] 2024-01-28 18:57
@mklement0 

> Start-Process -WindowStyle hidden

Thank you. I'll definitely try this.

**Comment by mklement0** [comment] 2024-01-28 19:13
@237dmitry, as for a **_Unix_ workaround**:

You can silence `nohup`'s console output as follows (using `sleep` as a sample command to run detached, as in @rhubarb-geek-nz's demonstration) - however, there is no way I know of to prevent creation of / appending to file `nohup.out`

```powershell
sh -c '{ nohup sleep 30 & } >/dev/null'
```

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 19:18
On Linux nohup only writes to nohup.out if the stdout is directed at a terminal

```
$ nohup sleep 1
nohup: ignoring input and appending output to 'nohup.out'
$ nohup sleep 1 > /dev/null
nohup: ignoring input and redirecting stderr to stdout
```

**Comment by mklement0** [comment] 2024-01-28 19:23
Thanks, @rhubarb-geek-nz, so the solution that prevents use of `nohup.out` is (I've also updated the previous comment):

```
sh -c '{ nohup sleep 30 & } 2>/dev/null 1>&2'
```

**Comment by 237dmitry** [comment] 2024-01-28 19:24
I did not tried this yet in pwsh  scripts

```
nohup sleep 1 0</dev/null 2>&1 1>/dev/null
```

**Comment by mklement0** [comment] 2024-01-28 19:33
@237dmitry:

From PowerShell, `$null = nohup sleep 10 &` works in principle, but would require you to manually clean up the job later.

If you don't mind `nohup.out` getting created, a more efficient `Start-Process`-based command is:

```powershell
Start-Process nohup 'sleep 30' -RedirectStandardError /dev/null
```

The following _should_ work and would prevent creation of `nohup.out`, but currently doesn't due to the following bug:

* #8313

```powershell
Start-Process nohup 'sleep 30' -RedirectStandardOut /dev/null -RedirectStandardError /dev/null
```

**Comment by 237dmitry** [comment] 2024-01-28 19:37
> Start-Process nohup 'sleep 30' -RedirectStandardError /dev/null

Wau!!! Thank you very much!

```
start nohup -args "alacritty --config-file $HOME/.config/alacritty/htop.toml" -RedirectStandardError /dev/null
```
Works fine!

**Comment by mklement0** [comment] 2024-01-28 21:54
@rhubarb-geek-nz:

Re console-subsystem applications currently _invariably_ creating a visible console window unless attached to an existing console - which notably manifests as an inability to invoke _PowerShell itself_ hidden, see  #3028 - there's a pending PR for a _Console Application Policy_ (now 3+ years old, most recently amended in Dec 2023), proposing a way for applications to control their console-related behavior via their _manifest_: 
  * PR: https://github.com/microsoft/terminal/pull/7337
  * Direct link to the document: https://github.com/microsoft/terminal/blob/dev/duhowett/spec/console-allocation/doc/specs/%237335%20-%20Console%20Allocation%20Policy.md

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 22:02
Java solved the problem by having "java.exe" and "javaw.exe", so the first one was a console app, the second was a GUI app. However you may still want stdin/stdout/stderr attached.

**Comment by mklement0** [comment] 2024-01-28 22:08
@rhubarb-geek-nz, an express design goal of the linked PR is to avoid the need for _separate executables_ going forward (the `python.exe` / `pythonw.exe` pair is another example).
If I understand the PR correctly, an application using the `detached` policy would _implicitly_ attach to a caller's _existing console_ - if present.

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 22:18
If you use CreateProcess() with DETACHED_PROCESS it is the responsibility of the new process to call AllocConsole() if it wants a console window, rather than the parent making the assumption and using CREATE_NEW_CONSOLE.
To add to the confusion there is also the CREATE_NO_WINDOW flag which is mutually exclusive with the previously mentioned flags.

**Comment by mklement0** [comment] 2024-01-28 22:26
* According to the linked PR, it's not the _parent process_ making the decision as to whether to allocate a console for a console-subsystem executable: it is the _kernel_ ("every application that is stamped with the IMAGE_SUBSYSTEM_WINDOWS_CUI subsystem in its PE header will be allocated a console by kernel32.")

* The design goal appears to be: Via an application manifest specifying a  _console-allocation policy_ allow creation of executables that:
  * act like console-subsystem applications when called _from an existing console_ (including the _synchronous_ behavior that that entails in shells)
  * act like GUI-subsystem applications otherwise (possibly running invisibly)

**Comment by rhubarb-geek-nz** [comment] 2024-01-28 22:38
That seems very convoluted and not in the right place at all, creating console windows should have nothing to do with the kernel. In the UNIX world controlling terminals are either system configured for serial ports or pseudo-terminals are created on demand at login by either rlogind, telnetd or sshd, or created when a new terminal window is opened (eg xterm, dtterm, gnome-terminal etc).

**Comment by mklement0** [comment] 2024-01-28 22:52
I'm not disagreeing; Windows has a lot of historical baggage, stemming from questionable initial design choices coupled with a commitment to backward compatibility - arguably, PowerShell itself has the same affliction (and I'm saying this as someone who is a fan of the  _fundamentals_ of PowerShell).

**Closed** 2024-01-31 06:45 UTC
Labels: Resolution-Answered
