### ISSUE TITLE
v7.4.3 Release of PowerShell (Latest) - NOT YET AVAILABLE - via --source winget (PLEASE FIX) 

### ISSUE THREAD

**Issue by iCanHazConfetti** [PowerShell/PowerShell#23970] opened 2024-06-19 19:31 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

(v7.4.3) Release of PowerShell (Latest) - NOT YET AVAILABLE - via --source winget (PLEASE FIX) 
Attempt via ' PS (v7.4.2) ' in ' Windows Terminal (v1.20.11381.0) ' from ' --source (winget) ' 
It is (2024-06-16 @ 11:55 PDT) currently.

1. Receive NOTICE when I open a New Tab in Windows Terminal (v1.20.11381.0) that is PowerShell (v.7.4.2) (both are the 
    latest available via WinGet on my System. 
    Yes. Did a : 'winget source update' prior to a : 
    'winget upgrade -r -u --force --verbose --wait -s winget' ...

2. NOTICE LISTS : 
    '' A new PowerShell stable release is available: v7.4.3
    Upgrade now, or check out the release page at:
    https://aka.ms/PowerShell-Release?tag=v7.4.3 '' ...

3. WinGet can NOT find PowerShell (v7.4.3) via ' --name ' , ' --id ' , OR ' --version ' in the ' --source winget ' ?Repo? (is 
    that the correct term)?

4. PLEASE FIX the winget source so that ' PowerShell --tag v7.4.3 can be located/installed/upgraded via WinGet

5. FYI ' App Installer is already installed ' , ' (v1.22.11261.0) on Windows 10.

6. THANKS in advance!

### Expected behavior

```console
When I ' CRTL+SHIFT+L-CLICK ' the NOTIFICATION BANNER MESSAGE in a PS (v7.4.2) Session in Windows Terminal that displays the new PowerShell stable release version tag, I expect to be able to then click to open the github page for the latest stable release of PowerShell to see what was updated, and then also be able to find and upgrade the version of PowerShell on my PC via WinGet...
```

### Actual behavior

```console
When I attempt to perform : ' winget find Powershell ' I expect to find the version that is the latest stable release I was notified of by PowerShell's Notification Banner.

This is not possible. If I search : ' winget find --id Microsoft.PowerShell ' I only find my currently installed version --tag (v7.4.2.0) and no listing for the new --tag (v7.4.3.0)...

...so I request that the package for this Latest Release (v7.4.3.0) be added to the winget source.

Thanks In Advance...
```

### Error details

```console
No PS > Get-Error : to report...
```

### Environment data

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="386" alt="PS (v7 4 3) - WinGet Upgrade ERROR -  2024-06-19 = 12 30 00" src="https://github.com/PowerShell/PowerShell/assets/166200092/463fd1cf-f0e0-4957-8ba1-4f18d31c244a">

**Comment by RicardoGEsteves** [comment] 2024-06-19 20:13
Was about to create this issue to.

![powershell-issue](https://github.com/PowerShell/PowerShell/assets/30535937/4ae5b1ed-fa11-4f95-b26a-c31d9f07b40b)

**Comment by rhubarb-geek-nz** [comment] 2024-06-24 17:23
I suggest the package manifest for PowerShell in WinGet should automatically define POWERSHELL_UPDATECHECK=Off when installed. Then leave it to WinGet to do the update when it is ready and avoid the pointless nagging message.

**Comment by Flameancer** [comment] 2024-06-30 03:27
Hello I seem to have a similar issue. Albeit with mine, winget does say there is a new powershell update, but it fails to actually perform the updating. 

Prompt from Powershell stating there's an Update
![image](https://github.com/PowerShell/PowerShell/assets/7704604/075b0774-a730-45bf-a15d-0b409391f5cc)

Winget update shows that there is a new version of PowerShell available. v7.4.3.0 and the source is Winget:
![image](https://github.com/PowerShell/PowerShell/assets/7704604/2adeec44-5e83-49b5-a13c-fba199acda82)


Winget fails to update Powershell citing `No installed package found matching input criteria.` and even fails when you specify the version number. 
![image](https://github.com/PowerShell/PowerShell/assets/7704604/649d13b0-5151-4c56-bf40-4a87ffeb9f44)

**Comment by StevenBucher98** [comment] 2024-07-08 21:22
I am able to find 7.4.3 published to winget, closing as resolved

**Comment by jhribal** [comment] 2024-07-09 03:03
> I am able to find 7.4.3 published to winget, closing as resolved

Yes you can find it published on winget. The problem is the upgrade.

1. **Here we can see i have installed previous version (7.4.2) of powershell.**
![image](https://github.com/PowerShell/PowerShell/assets/8378597/55858114-7b4c-4cc0-996f-7eb1067680fe)
2. Now i check whether new version of powershell is available and it shows that 7.4.3 is there.
![image](https://github.com/PowerShell/PowerShell/assets/8378597/a2025214-44d6-4fff-92fb-b084e85b91c0)
4. I try to upgrade, but it shows i don't have powershell installed.
![image](https://github.com/PowerShell/PowerShell/assets/8378597/73fa3a4a-c27e-4820-9700-e489a28fc2d7)

So what is this behavior? Did i something incorrect? (I don't think so).

**Comment by Flameancer** [comment] 2024-07-13 03:55
Hello can this be reopened? This issue has not been fixed yet. 
![image](https://github.com/user-attachments/assets/1e554416-162a-4f5d-bc43-e0ffc57708d5)

**Comment by StevenBucher98** [comment] 2024-07-18 23:27
How did you originally get 7.4.2? Upgrading seems to work just fine for me.

![image](https://github.com/user-attachments/assets/23e58bc0-afbf-4191-a44c-3c4ecd445736)

**Comment by StevenBucher98** [comment] 2024-07-22 19:52
Update this actually does not work, whenever I restart the latest version is not there.

**Comment by StevenBucher98** [comment] 2024-07-23 04:36
Now it seems to be working again for me, seemingly no change to what I was doing...

**Comment by avernigora-clgx** [comment] 2024-07-23 23:10
no 7.4.4 is not available.

```
winget list --id Microsoft.PowerShell

Name             Id                   Version Source
-----------------------------------------------------
PowerShell 7-x64 Microsoft.PowerShell 7.4.3.0 winget
```

**Comment by mycloud1** [comment] 2024-08-05 06:53
I finally found a forum where others are reporting same this issue that to me for all intents and purposes clearly have a problem with this install/upgrade (to PowerShell version 7.4.4), via winget.

**Comment by StevenBucher98** [comment] 2024-08-05 20:24
@avernigora-clgx 7.4.4 should be available now, there may be a day or two delay after GH releases are published to get the correct WinGet packages available.

@mycloud1 can you please elaborate on the issues you are hitting? Please give details of your environment and reproduction steps, if it is easier please open up a new issue.

**Comment by mycloud1** [comment] 2024-08-06 02:35
> @avernigora-clgx 7.4.4 should be available now, there may be a day or two delay after GH releases are published to get the correct WinGet packages available. Please let me know if you are having any issues with upgrading it.
> 
> @mycloud1 can you please elaborate on the issues you are hitting? Please give details of your environment and reproduction steps, if it is easier please open up a new issue.

@StevenBucher98 I was to reply say briefly that I run Windows 11 Pro 22H2  and done same that has been successful for me with PowerShell 7.4.2 (Two) and before to run script, (or variations of) winget install --id Microsoft.Powershell --source winget and wondering if because I didn't have Windows Feature Pack 23H2 if this might be the reason (have .NET 8.0.303), but just today this update looks as though it's going to apply to my computer through Windows Update, as opposed to me running a Winget command per Windows screenshot. Little bit odd behaviour, but ok - thanks for your reply. PS it isn't a big issue for me.
![Screenshot 2024-08-06 123406](https://github.com/user-attachments/assets/0855d75c-49c8-4c77-b31c-1fe69468a917)

**Closed** 2024-08-07 07:28 UTC
Labels: Resolution-Fixed

**Comment by iCanHazConfetti** [comment] 2024-08-17 05:20
Since winget can not install the package  via the Windows Package Manager (winget/WinGet/whatever) via the PowerShell CLI ; ie : PS> winget upgrade --id Microsoft.PowerShell --version 7.4.4.0 --source winget ) via the Windows Package Manager (winget) Source Repository... I'd say this works terribly as it erodes the perception that the Source Repository for winget isn't 100% fool-proof. It's supposed to be installable via winget, not Windows Update.

Thankful that it was released for Windows Update, but, it's a fail for the Windows Package Manager from the perspective of "it just works" after the version Tag was released as a banner INSIDE PowerShell...

Thank you for making it available in all of the "other" available formats it can be installed by, though.
