### ISSUE TITLE
Get-ChildItem follows symlinks when it should not

### ISSUE THREAD

**Issue by lenihan** [PowerShell/PowerShell#13317] opened 2020-07-30 17:18 UTC
## Steps to reproduce

```powershell
#Requires -RunAsAdministrator
mkdir $HOME/repo/foodir -Force
New-Item $HOME/repo/foodir/foo.txt -Force
New-Item -Type SymbolicLink -Path $HOME/repo/symlinkdir -Target $HOME/repo/foodir -Force

# Case 1: returns 1 -> CORRECT
(Get-ChildItem $HOME/repo -r -File).count  

# Case 2: returns 2 -> WRONG, looking in symlinkdir
(Get-ChildItem $HOME/repo -r -File -Exclude dummy).count  

# Case 3: WORKAROUND returns 1; use second Get-ChildItem
(Get-ChildItem $HOME/repo -r -File|Get-ChildItem -Exclude dummy).count 
```

## Expected behavior

```none
First case finds one file
Second case finds one file
Third case finds one file
```

## Actual behavior

```none
First case finds one file, does not look in symlink directory...correct.
Second case finds TWO files because it looks in symlink directory....WRONG!
Third case finds one file. It is a workaround. It gets behavior of -Exclude without looking in symlink directory by using two calls to Get-ChildItem

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment] 2020-07-30 17:56
This looks like a duplicate of https://github.com/PowerShell/PowerShell/issues/9126

**Closed** 2020-08-01 17:00 UTC
Labels: Issue-Question, Resolution-Duplicate
