### ISSUE TITLE
Add #requires -Executable "<>"

### ISSUE THREAD

**Issue by pakrym** [PowerShell/PowerShell#14877] opened 2021-02-22 18:12 UTC

**Comment by p0W3RH311** [comment] 2021-02-22 18:17
```
#requires -ExecutionContext bypass 
echo hello
```

this pragma support enum `[Microsoft.PowerShell.ExecutionPolicy]`

**Comment by daxian-dbw** [comment] 2021-02-22 18:50
Close ad duplicate of #14879

**Closed by daxian-dbw** 2021-02-22 18:50 UTC
Labels: Issue-Enhancement, Needs-Triage
