### ISSUE TITLE
Introduce command update-powershell

### ISSUE THREAD

**Issue by peppekerstens** [PowerShell/PowerShell#11222] opened 2019-11-30 20:11 UTC
# Summary of the new feature/enhancement

Command is hopefully self-explanatory :)

# Proposed technical implementation details (optional)

**Comment by iSazonov** [comment] 2019-12-05 05:37
Most installations are performed using package managers. So the cmdlet could be useful only for SxS scenarios if zip package is used. Since we have new version notifications in 7.0 I think the cmdlet has very small value.
/cc @daxian-dbw Thoughts?

**Comment by peppekerstens** [comment] 2019-12-23 06:36
@iSazonov you are correct. This applies to the Windows variant only and would replace/enhance

iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -Preview"

I had the beginner/lazy in mind. But enhancing/improving the documentation [here](https://docs.microsoft.com/en-us/powershell), providing a more friendly manner like this script could/should suffice.

**Comment by iSazonov** [comment] 2019-12-23 10:26
@peppekerstens You could ask in https://github.com/PowerShell/PowerShell-Docs or pull a PR there.
Also I guess MSFT will promote AppX package from Store for beginners.

**Comment by TylerLeonhardt** [comment] 2020-12-04 19:03
Duplicate of https://github.com/PowerShell/PowerShell/issues/12678

**Comment by peppekerstens** [comment] 2020-12-10 11:02
@SteveL-MSFT and @TylerLeonhardt and @iSazonov 

Could we combine the MSIX PS versions with the [MSIX commands](https://docs.microsoft.com/en-us/windows/msix/desktop/powershell-msix-cmdlets) to create a more package-like install/update experience within the console environment of Windows (with the non GUI core versions in mind)?

On that note: why are the MSIX packages published to the MS store but not within Github anymore? 
https://github.com/PowerShell/PowerShell/issues/12009 - not really fixed this way...

**Comment by iSazonov** [comment] 2020-12-10 12:08
@peppekerstens Appx module does not compatible with current PowerShell 7.1 version.

I am not a proponent of a self-renewal approach. I believe this is a task for package managers and each distributive  vendor can have a different approach. We have a good compromise today in notifying users of new versions.

**Comment by peppekerstens** [comment] 2020-12-17 14:15
@iSazonov I totally agree on your perspective and 'get' the way it is being done within a *unix/*linux env . So maybe I am missing something here....

I am trying to move forward to that same principle within Windows... What is the preferred packagemanager within the Windows environment and in which way has that manager updating for PowerShell covered?

**Comment by iSazonov** [comment] 2020-12-17 16:46
> What is the preferred packagemanager within the Windows environment and in which way has that manager updating for PowerShell covered?

MSFT actively works on WinGet :-) but it is your preference which manager to use. In any case you could try WinGet and feedback in WinGet repository.

**Comment by jdhitsolutions** [comment] 2021-06-14 19:53
This looks like a duplicate of https://github.com/PowerShell/PowerShell/issues/8663.

**Closed** 2021-06-15 04:35 UTC
Labels: Area-Cmdlets, Area-Maintainers-Build, Issue-Enhancement, Resolution-Duplicate
