### ISSUE TITLE
v6 to v5 remoting errors on comands that have prompts

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShell/PowerShell#5318] opened 2017-11-02 23:34 UTC
Steps to reproduce
------------------

```powershell
Enter-PSSession $s 
[hv01]: PS C:\> Find-Module lability | Install-Module
Object reference not set to an instance of an object.
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException

[hv01]: PS C:\> Find-Module lability | Install-Module -Force
[hv01]: PS C:\>
```

Expected behavior
-----------------

```powershell
[hv01]: PS C:\> Find-Module lability | Install-Module
[hv01]: PS C:\>
```

Actual behavior
---------------

```powershell
[hv01]: PS C:\> Find-Module lability | Install-Module
Object reference not set to an instance of an object.
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
```

Environment data
----------------

```powershell
[hv01]: PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


[hv01]: PS C:\> exit
PS C:\Program Files (x86)\PowerShell\6.0.0-beta.9> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by SteveL-MSFT** [comment] 2017-11-03 00:45
Dupe of https://github.com/PowerShell/PowerShell/issues/4615

**Closed by SteveL-MSFT** 2017-11-03 00:45 UTC
Labels: Area-Remoting, Resolution-Duplicate
