### ISSUE TITLE
Recent powershell fails with MI_RESULT_FAILED connecting to outlook.office365.com

### ISSUE THREAD

**Issue by adaviel** [PowerShell/PowerShell#5372] opened 2017-11-07 23:44 UTC
I have CentOS 7.4.1708

In July, I installed powershell-6.0.0_beta.3-1.el7.x86_64 using Yum

I followed the documented procedure to connect to Office365, which worked, viz.
**PS /root> $UserCredential = Get-Credential**
**PS /root>  $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection**
**PS /root> Import-PSSession $Session**

I could then execute e.g. **Get-Mailbox**

Recently, after the system had auto-upgraded powershell to 6.0.0_beta.9-1.rhel.7, this failed

Enter your credentials.
User: andrew@xxxx
Password for user andrew@xxxx: ******

New-PSSession : [outlook.office365.com] Connecting to remote server 
outlook.office365.com failed with the following error message : 
MI_RESULT_FAILED For more information, see the about_Remote_Troubleshooting 
Help topic.
At line:1 char:13
+  $Session = New-PSSession -verbose -debug -ConfigurationName Microsof ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotin 
   gTransportException
    + FullyQualifiedErrorId : 1,PSSessionOpenFailed

If I downgrade to version 3.1, or powershell-6.0.0_beta.5-1.el7.x86_64, it works again.
If I upgrade to powershell-6.0.0_beta.6-1.el7.x86_64, it fails.

I deduce that something broke between version 5.1 and 6.1.

**Comment by SteveL-MSFT** [comment] 2017-11-08 00:09
Dupe of https://github.com/PowerShell/PowerShell/issues/5130

**Closed by SteveL-MSFT** 2017-11-08 00:09 UTC
Labels: Resolution-Duplicate
