### ISSUE TITLE
Garbage in TMPDIR resulting in Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by alexei-matveev** [PowerShell/PowerShell#15299] opened 2021-04-23 15:03 UTC
## Steps to reproduce

See comments in https://github.com/dotnet/runtime/issues/46462

Hm, it seems it is difficult to reproduce from an interactive Shell.
The automated Script is started from a daemon process, several times a minute ... 

```
...
ls -lrtd /tmp/????????-????-????-????-????????????
```

[Edited by @daxian-dbw] Remove the `Home` env variable, and then start PowerShell multiple times. You will see multiple temporary folder with GUID id names got created in `/tmp`.

## Expected behavior

Empty output

## Actual behavior

Garbage as this ist left:

            $ find 88a84cf3-05b5-40c3-a29e-52d611e919e7
            88a84cf3-05b5-40c3-a29e-52d611e919e7
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.cache
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.cache/powershell
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.cache/powershell/StartupProfileData-NonInteractive
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.cache/powershell/telemetry.uuid
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.local
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.local/share
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.local/share/powershell
            88a84cf3-05b5-40c3-a29e-52d611e919e7/.local/share/powershell/Modules

## Environment data

Same with the LTS 7.0.6 and non-LTS 7.1. CentOS 7 with MS Repo attached:

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.6
PSEdition                      Core
GitCommitId                    7.0.6
OS                             Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment] 2021-05-03 22:51
I believe this is related to https://github.com/PowerShell/PowerShell/pull/13239. PowerShell creates a temporary folder when the environment variable `Home` doesn't exist. Can you try setting the env variable `Home` and see if the issue is gone?

**Comment by alexei-matveev** [comment] 2021-05-06 20:59
Yep, looks like that. This works as expected:

```
mkdir xxx
TMPDIR=./xxx pwsh
```
This is the content wheil pwsh was running. They dissappear:

```
prwx------ 1 alexei alexei 0 May  6 22:52 clr-debug-pipe-4432-226815218-in
prwx------ 1 alexei alexei 0 May  6 22:52 clr-debug-pipe-4432-226815218-out
srwxrwxr-x 1 alexei alexei 0 May  6 22:52 CoreFxPipe_PSHost.D742B9AE.4432.None.pwsh
srw------- 1 alexei alexei 0 May  6 22:52 dotnet-diagnostic-4432-226815218-socket
```

If I run it like this:

    TMPDIR=./xxx HOME=/nowhere pwsh

Garbage remains in ./xxx:

```
$ find .
.
./b1409506-7aae-4211-b3c0-0d24ddbfbdf5
./b1409506-7aae-4211-b3c0-0d24ddbfbdf5/telemetry.uuid
./b1409506-7aae-4211-b3c0-0d24ddbfbdf5/StartupProfileData-Interactive
./b1409506-7aae-4211-b3c0-0d24ddbfbdf5/7.1.3
./b1409506-7aae-4211-b3c0-0d24ddbfbdf5/7.1.3/sentinel1-2021-5-6.done
```

**Comment by daxian-dbw** [comment] 2021-05-08 18:33
@JamesWTruher @rjmholt Any ideas on how to address this in code? Or, do we just document this behavior?
It's not uncommon for containers to not have `Home` defined.

**Comment by daxian-dbw** [comment] 2021-05-13 18:11
I thought about this issue more, and believe we should fix it in our code to make PowerShell work better in a container environment without the env variable `Home` defined. After all, it's not uncommon for a container to not have `Home` env var. I think it can be fixed by adding a well-known prefix to the temporary folder name, and next time PS session starts, it can just look for an folder under `tmp` with that well-know prefix and use that as the pseudo `Home` directory.

**Closed** 2021-11-22 18:44 UTC
Labels: Issue-Bug, WG-Engine, In-PR
