### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by nanonyme** [PowerShell/PowerShell#16114] opened 2021-09-16 15:36 UTC
### Name of the Distribution

Debian

### Version of the Distribution

11

### Package Types

- [X] Deb
- [ ] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

x86_64

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [x] Docker image created
- [x] Docker image published
- [x] Distribution tested
- [x] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by nanonyme** [comment] 2021-12-14 11:01
Hey, would it please be possible to get this progressed?

**Comment by partneroid-zz** [comment] 2021-12-15 12:04
+1 pretty please

**Comment by prakashguru** [comment] 2021-12-16 09:19
There is another issue https://github.com/PowerShell/PowerShell/issues/10923 which tracking debian 11.  most of the activities are done. just a few remaining. @partneroid-zz @nanonyme please send a request on that issue.

**Comment by adityapatwardhan** [comment] 2022-01-18 22:15
Duplicate of #10923

**Closed by adityapatwardhan** 2022-01-18 22:15 UTC
Labels: Distribution-Request, Review - Maintainer, Needs-Triage
