### ISSUE TITLE
Distribution Support - RHEL8

### ISSUE THREAD

**Issue by limershein** [PowerShell/PowerShell#12984] opened 2020-06-17 20:41 UTC
## Details of the Distribution
We saw support for powershell on RHEL 7 but not RHEL 8.  We see CentOS 8. and this does appear to work, but SQL Server on Linux customers want to know that RHEL 8 is supported.

- Name of the Distribution: Red Hat Enterprise Linux
- Version of the Distribution: 8.x (currently 8.0, 8.1, 8.2)
- Package Types
    - [ ] Deb
    - [X] RPM
    - [ ] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request):  x86
- [x] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker
- The following is a requirement for supporting a distribution **without exception.**
    - [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [X] The version of the Distribution is supported for at least one year.
    - [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [x] Docker image created
- [x] Docker image published
- [x] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by iSazonov** [comment] 2020-06-18 07:59
.Net 5.0 supports RHEL 7+ https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md

**Comment by TravisEz13** [comment] 2020-06-22 17:13
duplicate of #10632

**Comment by TravisEz13** [comment] 2020-06-22 17:16
This PR will be for updating updating the deployment and documentation only.   package creation, etc will use the centos8 package.

**Comment by mheslin** [comment] 2020-07-20 17:06
What is the current status? We're following this on the weekly RH+MSFT engineering calls and folks were asking about the doc status. Thanks.

**Comment by mheslin** [comment] 2020-08-17 21:11
Hi All. Friendly ping - both Red Hat+Microsoft are interested in this and looking for status on RHEL 8. Can someone give us an idea as to where this stands? Thanks!

**Comment by iSazonov** [comment] 2020-08-18 03:33
You can see Progress in first post above.

**Comment by mheslin** [comment] 2020-08-18 13:16
Yes, fully aware of .Net Core 5 and RHEL 8. Question is where does PowerShell stand today for customers on RHEL? Is this fully supported and just a question of bringing the documentation up to date to reflect that? This is what we're hearing from customers. Thanks!

**Comment by TravisEz13** [comment] 2020-08-19 18:05
>![image](https://user-images.githubusercontent.com/10873629/90672914-bf496f80-e20b-11ea-8903-78599fdfaf3c.png)

Once the distribution is tested, the distribution is supported, there may be changes as we finish the other steps.

**Comment by msLinuxNinja** [comment] 2020-08-24 16:52
This document needs to be updated to reflect support in RHEL 8:

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md

**Comment by HeyItsGilbert** [comment] 2020-12-04 16:56
Will this result in the package being available at https://packages.microsoft.com/rhel/8/prod/?

**Comment by janegilring** [comment] 2021-01-26 06:16
Great to see that support for RHEL 8 is coming - are there any ETA regarding availability/release?

**Comment by iSazonov** [comment] 2021-01-26 15:21
@janegilring This should work for current preview version. Next release is expected in November.

**Comment by TravisEz13** [comment] 2021-01-26 19:12
I opened the PR to add a release for both RHEL 8 and centos 8 for packages.microsoft.com (in a private repo.)

**Comment by hanneshayashi** [comment] 2022-05-11 05:56
RHEL 9 was just released today: https://www.redhat.com/en/about/press-releases/red-hat-defines-new-epicenter-innovation-red-hat-enterprise-linux-9

**Closed** 2023-11-23 11:59 UTC
Labels: Distribution-Request, Resolution-No Activity
