### ISSUE TITLE
Strange behaviour after cd into piped directory object

### ISSUE THREAD

**Issue by zivkan** [PowerShell/PowerShell#16469] opened 2021-11-14 14:48 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```text
C:\Users\zivkan> gci -Directory | Select-Object -First 1 | cd
C:\Users\zivkan\.android> dir \
Get-ChildItem: Cannot find path '' because it does not exist.
C:\Users\zivkan\.android> cd \
Set-Location: Cannot find path 'Microsoft.PowerShell.Core\FileSystem::' because it does not exist.
C:\Users\zivkan\.android> cd
C:\Users\zivkan> cd \
C:\>
```

I was trying to be cleaver, reducing keystrokes, when creating a directory that I was going to use to test something, hoping I could use `mkdir myTest | cd `, but some things just act weird. In particular tab completion of paths no longer works.

### Expected behavior

```console
`dir \` and tab completion of `\user` should work whether I `cd` into via a pipe or explicit argument.
```

### Actual behavior

```console
See error messages reported in steps to reproduce.
```

### Error details

```console
Exception             :
    Type                 : System.Management.Automation.ItemNotFoundException
    ErrorRecord          :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find path '' because it does not exist.
            HResult : -2146233087
        CategoryInfo          : ObjectNotFound: (:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PathNotFound
    SessionStateCategory : Drive
    TargetSite           :
        Name          : GetChildItems
        DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.2.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message              : Cannot find path '' because it does not exist.
    Source               : System.Management.Automation
    HResult              : -2146233087
    StackTrace           :
   at System.Management.Automation.SessionStateInternal.GetChildItems(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.GetChildItemCommand.ProcessRecord()
CategoryInfo          : ObjectNotFound: (:String) [Get-ChildItem], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
InvocationInfo        :
    MyCommand        : Get-ChildItem
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 60
    Line             : dir \
    PositionMessage  : At line:1 char:1
                       + dir \
                       + ~~~~~
    InvocationName   : dir
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment] 2021-11-14 23:44
This happens in multiple cases when you pipe a file or directory object into something, the PSPath parameter wins so you might think you have done 
`cd C:\Users\zivkan\.android"`
In fact you've done 
`cd microsoft.PowerShell.Core\FileSystem::C:\Users\zivkan\.android`

Frustrating but not hard to work round

**Comment by rkeithhill** [comment] 2021-11-14 23:53
Hmm, this used to work in Windows PowerShell 5.1.  Seems like a regression.

**Comment by jhoneill** [comment] 2021-11-15 10:25
@rkeithhill it doesn't work in 5.1 now

![image](https://user-images.githubusercontent.com/16209593/141764830-de3455b2-79d9-4f2c-b4eb-767119835be4.png)

That prompt is an immediate giveaway, and it happens whether you use set-location (usual cd) or push-location (which I have for cd)

**Comment by zivkan** [comment] 2021-11-15 14:23
> In fact you've done

I'm not sure why customers using powershell should care about that subtle difference. Especially n00bs like me. Is there a reason why powershell itself shouldn't special case all paths starting with `microsoft.PowerShell.Core\FileSystem::`, and strip it out?  Are there scenarios where `Set-Location` knowing the difference is actually useful?

> Frustrating but not hard to work round

I agree, but "as a customer I thought this should work", so I reported it. This gives the powershell team the opportunity to decide whether or not to fix it. Or maybe just improve the error message.

**Comment by jhoneill** [comment] 2021-11-15 18:41
> > In fact you've done
> 
> I'm not sure why customers using powershell should care about that subtle difference. Especially n00bs like me. 

TBH I agree with you. As an old hand rather than a self-identified n00b I learned the work round, usually use it and when I forget I say "doh, that's stupid why was it never fixed". 

It doesn't need to be that way either
``` 
[pscustomobject]@{path="c:\windows"} | set-location 
```
Shows that an object with a path property works for setting a location.  In fact it PATH has precedence over PSPath which is what CD is using, but files and directories have a `.fullname` property instead of `path`. 

You can save this as "mytypes.ps1xml"
```
<Types><Type><Name>System.IO.DirectoryInfo</Name><Members><AliasProperty><Name>Path</Name><ReferencedMemberName>FullName</ReferencedMemberName></AliasProperty></Members></Type></Types>
```
and then run `Update-TypeData -AppendPath .\mytypes.ps1xml` then directories support .Path , .Path trumps .PSPath and thing work the way they should. 

I've no idea why the onus is on you to do that, being broken for a long time turns into a reason to not fix I guess.

**Comment by daxian-dbw** [comment] 2021-12-09 23:52
Close this issue as a duplicate of https://github.com/PowerShell/PowerShell/issues/9293

**Closed by daxian-dbw** 2021-12-09 23:52 UTC
Labels: Issue-Bug, WG-Engine-Providers
