### ISSUE TITLE
Invoke-RestMethod High Memory Usage

### ISSUE THREAD

**Issue by javaptgl** [PowerShell/PowerShell#5609] opened 2017-12-02 12:59 UTC
Steps to reproduce
------------------
Call Invoke-RestMethod more than 1 million times.
```powershell
try
{
    $reader = New-Object System.IO.StreamReader("input.csv") # 5,000,000 Lines
    $writer = New-Object System.IO.StreamWriter("output.csv"), ([System.IO.FileMode]::Append)
    for($count = 0;;$count++)
    {
        $line = $reader.ReadLine()
        if($line -eq $null) { break }
        $data = $line.Split(",")
        $input_variable = $data[0]
        
        $result = Invoke-RestMethod -Uri http://localhost:5000/api/compute_something/$input_variable # Result of api is an integer number.
        if($result -gt 0)
        { $writer.WriteLine($line + ",$result") }
    }         
}
finally
{
    $reader.Close()
    $writer.Close()
}

```

Expected behavior
-----------------
Minimum memory usage.

Actual behavior
---------------
High memory usage. Uses 900MB-1GB for a 5 million line file.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                        
----                           -----                                                                                                                        
PSVersion                      6.0.0-rc                                                                                                                     
PSEdition                      Core                                                                                                                         
GitCommitId                    v6.0.0-rc                                                                                                                    
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64               
Platform                       Unix                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                      
WSManStackVersion              3.0  
```

**Comment by iSazonov** [comment] 2017-12-02 19:13
Is the problem only on MacOS?

**Comment by javaptgl** [comment] 2017-12-03 05:05
I'll check it on windows 8 and post the results here in a day,

**Comment by javaptgl** [comment] 2017-12-03 14:29
No issue on Windows 8. Average Memory Usage Was 40MB

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment] 2017-12-03 14:39
Does the problem reproduce for something simpler? Like maybe this:

```powershell
$Url = "http://localhost:5000/api/compute_something/1"
1..5000000 | ForEach-Object { 
    $result = Invoke-RestMethod -uri $Uri
}
```

Where you use the same URI every time and aren't trying to do any other logic. I would need something I can actually do myself to look into it.

**Comment by javaptgl** [comment] 2017-12-05 06:02
Yes. The issue can be reproduced for something simple as:
```powershell
for($count = 1;$count -le 5000000;$count++)
{
    $result=Invoke-RestMethod -Uri http://localhost:5001/api
}  
```

Web server in express.js
```javascript
const express = require('express')
const app = express()

app.get('/api', function (req, res)
{ 
    res.send('0')
})

app.listen(5001, function ()
{
    console.log('Example app listening on port 5001')
})
```

**Comment by markekraus** [comment] 2017-12-05 11:31
I'm not familiar with express.js. What character encoding and contet-type does it return for that? Does it do any content encoding (gzip, deflate, chunked?).

I'm testing with an ASP.NET Core 2.0 API app and memory usage is not rising fast enough to hit 1G. after about 30 minutes it's only at 150M. It could be that the encoding and content-type are different though which would make it hi different .NET APIs.

**Comment by javaptgl** [comment] 2017-12-05 12:28
Response Header
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 1

Memory usage 100-250MB after 1 Million Calls and hits 1GB after 4 Million Calls.
Issue does not exist for windows 8 but exists on MacOS. Don't know about linux.

**Comment by markekraus** [comment] 2017-12-05 12:49
@javaptgl thanks. I will set my test environment to match and test to the full 5 million requests when I can get back to my macOS system. In the meantime, can you see if the same thing happens with 

```powershell
$null = Invoke-RestMethod -Uri http://localhost:5001/api
```

I'm trying to narrow down where the issue is exactly and trying to eliminate as many as many variables as possible.

As another thing to try... This emulates the calls made under the hood skipping the JSON and XML conversion attempts and going straight to the string fallback:

```powershell
$Handler = [System.Net.Http.HttpClientHandler]::New()
$HttpClient = [System.Net.Http.HttpClient]::New($Handler)
$Response = $HttpClient.GetAsync('http://localhost:5001/api').GetAwaiter().GetResult()
$Stream = $Response.Content.ReadAsStreamAsync().GetAwaiter().GetResult()
$reader = [System.IO.StreamReader]::new($Stream)
$result = $reader.ReadToEnd()
$reader.Dispose()
```

If memory usage there is normal, that will point us to something in the JSON and XML conversion process.

**Comment by javaptgl** [comment] 2017-12-05 15:59
I ran the above two snippets simultaneously in separate processes for 2 hours.
The results were similar. 280MB and 300MB usage.

**Comment by markekraus** [comment] 2017-12-05 17:23
hmm but not the 1GB you were seeing with `$result=Invoke-RestMethod -Uri http://localhost:5001/api`?

**Comment by javaptgl** [comment] 2017-12-05 17:58
API calls on powershell are really slow. About 130/s. It'll take more than 10hrs unless I use some kind of concurrency like background jobs.

**Comment by markekraus** [comment] 2017-12-05 18:33
ok. So we need to go with a lower number than 5,000,000 so we can check across versions and platforms and not take an eternity then.

Was the 280MBB-300MB usage after 2 hours with the to the consumption in the first to hours of the 5,000,000 run? was it more? was it less?

**Comment by javaptgl** [comment] 2017-12-06 02:32
Both snippets finished with memory usage of around 900MB each. The memory wasn't released until I quit the powershell processes.

**Comment by markekraus** [comment] 2017-12-06 09:25
@javaptgl I'm still gathering data to try and track down where this is happening, but here are some observations so far.

* The raw C# .NET HttpClient calls do not grow in memory size
* running `pwsh -noni -nop -file` seems to only have negligible memory growth.
* adding a call to `[Microsoft.PowerShell.Commands.JsonObject]::ConvertFromJson($result,[ref]$null)` in the `[System.Net.Http.HttpClient]` example appears to grow at the same rate as `$result=Invoke-RestMethod`

These are the scripts I'm working with https://gist.github.com/markekraus/b16f0991a843d2d2459aa4178dfe55b5

**Comment by markekraus** [comment] 2017-12-06 13:23
@javaptgl how are you measuring memory usage on macOS? can you provide some output? I want to make sure we are not chasing a ghost by looking at the wrong numbers. My tests indicate that beetween 10,000 and 500,000 iterations there is no significant increase in resident memory. some methods use more than others, but between iterations it is fairly static per method. For example:


| Iterations | Invoke-RestMethod | HttpClient  | dotnet |
| ---------- | ----------------- | ----------- | ------ |
| 10,000     | 79.20             | 62.30       | 52.3   |
| 100,000    | 79.15             | 63.10       | 52.4   |
| 500,000    | 79.35             | 62.40       | 52.2   |

**Comment by javaptgl** [comment] 2017-12-06 16:07
I'm using the MacOS activity monitor (Equivalent of Windows Task Manager) to check the usage.

**Comment by iSazonov** [comment] 2017-12-06 18:01
You could use https://github.com/dotnet/coreclr/blob/027180d8ef4a8a0e50f4cba3ad985af38882f5ef/Documentation/coding-guidelines/cross-platform-performance-and-eventing.md

**Comment by markekraus** [comment] 2017-12-06 22:27
After learning that macOS has an "internal memory size" metric which doesn't map to anything in Windows or Linux, and figuring out how to reliably get the actual memory usage of `pwsh` in macOS, I'm satisfied that there is no memory leak here. 

The "internal memory size" of the process grows over time up to 1GB, however, the actual resident memory and virtual memory of the process do not grow past a certain peak. On my macOS at both 500,000 and 1,000,000 iterations of `$result = Invoke-RestMethod -uri $Uri` (with `$uri` is the uri of the express.js microservice), the actual usage never goes beyond ~80MB. There is no significant difference between 10,000 iterations, 100,000 iterations, 500,000 iterations, or 1,000,000 iterations. This memory usage is consistent with the same test in Windows, WSL ubuntu, and ubuntu server with a margin of about +/-2MB. Between all of them

@javaptgl either I'm not able to reproduce your problem, or, perhaps you are looking at this "internal memory size" that macOS reports as I was when initially trying to reproduce the issue. In `top` this is the `MEM` column. If that is the case, I do not believe this to be a reliably accurate view of the process's memory usage. instead use `ps` or `htop` to get the RSS/RES and VIRT/VSZ values.

**Comment by javaptgl** [comment] 2017-12-07 13:01
This was taken at 3,670,000th call. Activity Monitor "Memory" column reported 860MB Usage.
```
Apple:~ air$ ps v
PID STAT      TIME  SL  RE PAGEIN      VSZ    RSS   LIM     TSIZ  %CPU %MEM COMMAND
9170 S+   232:10.61   0   0      0  5758660 154564     -        0   8.4  3.7 pwsh irm_test.ps1
9695 S      0:00.17   0   0      0  2461044    984     -        0   0.4  0.0 -bash
3504 S      0:00.10   0   0      0  2461044    504     -        0   0.0  0.0 -bash
1108 S      0:00.07   0   0      0  2461044    428     -        0   0.0  0.0 -bash
```
Do you have a reference link to the "internal memory size" metric used in MacOS?

I posted this issue because I have run other powershell scripts(such as sql access and log parsing) for days and none have crossed 100MB Memory as reported by the activity monitor.

I'm going to post the screenshot  of the activity monitor window after completing 10 million calls.

**Comment by markekraus** [comment] 2017-12-07 13:51
@javaptgl ok so your `ps` is showing the RSS and VSZ are way higher than mine ever get. At 2 million I was still at ~80MB 
can you run your test with `pwsh -nop -file irm_test.ps1` to eliminate any potential profile issues?

Also, what version of macOS are you on? My test machine is at 10.13.1
Which install method did you use (brew, pkg, or Start-PSBuild)?
Can you please also run the code from this and post the results? https://github.com/markekraus/PowerShell/blob/TestMacosFails/test/powershell/Libcurl.Tests.ps1

> Do you have a reference link to the "internal memory size" metric used in MacOS? 

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/top.1.html

The description for `MEM` column. then just googling around to try and find out what that is and coming across people trying and failing to compare it to metrics in linux and windows. However, that's not a concern now. Your RSS and VSZ are what I was suing to test with myself and yours are way higher than mine.

**Comment by javaptgl** [comment] 2017-12-08 06:38
I'm using MacOS Sierra, Version 10.12.6

> Which install method did you use (brew, pkg, or Start-PSBuild)?

A month ago I installed Powershell v6.0.0-beta.7 for the first time on my mac using the mac pkg and found this issue. A week ago I uninstalled this and installed the v6.0.0-rc using homebrew cask.

> Can you please also run the code from this and post the results? https://github.com/markekraus/PowerShell/blob/TestMacosFails/test/powershell/Libcurl.Tests.ps1
```
LIBCURl=====================================================
LIBCURL GetSslVersionDescription(): SecureTransport
LIBCURL GetSupportedFeatures(): CURL_VERSION_IPV6, CURL_VERSION_SSL, CURL_VERSION_LIBZ, CURL_VERSION_NTLM, CURL_VERSION_ASYNCHDNS, CURL_VERSION_SPNEGO, CURL_VERSION_LARGEFILE, CURL_VERSION_NTLM_WB, CURL_VERSION_GSSAPI, CURL_VERSION_KERBEROS5, CURL_VERSION_UNIX_SOCKETS
LIBCURL GetSupportsHttp2Multiplexing(): False
LIBCURL GetVersionDescription(): 7.54.0
LIBCURl=====================================================
```

> can you run your test with pwsh -nop -file irm_test.ps1 to eliminate any potential profile issues?

Just started with the script now.

**Comment by markekraus** [comment] 2017-12-08 09:24
@javaptgl thank you!

can you please also do a test with the following:

```bash
brew install openssl
brew install curl --with-openssl --with-gssapi
export DYLD_LIBRARY_PATH=/usr/local/opt/curl/lib:/usr/local/opt/openssl/lib:${DYLD_LIBRARY_PATH};
pwsh irm_test.ps1
```

I have recently seen some issues with 10.12.6's system supplied 7.54.0 libcurl, which is what your pwsh appears to be using based on the output. This forces pwsh to use the libcurl+openssl+gssapi installed by brew.

**Comment by javaptgl** [comment] 2017-12-09 14:52
```
LIBCURl=====================================================
LIBCURL GetSslVersionDescription(): OpenSSL/1.0.2n
LIBCURL GetSupportedFeatures(): 3064733
LIBCURL GetSupportsHttp2Multiplexing(): False
LIBCURL GetVersionDescription(): 7.57.0
LIBCURl=====================================================
```

After 6,860,000 calls:
```
Apple:~ air$ ps v
  PID STAT      TIME  SL  RE PAGEIN      VSZ    RSS   LIM     TSIZ  %CPU %MEM COMMAND
11740 R+   436:07.64   0   0      0  6360868  27564     -        0   6.4  0.7 pwsh -nop -file irm_test.ps1
34581 S+     0:00.10   0   0      0  2461044   3244     -        0   0.0  0.1 -bash
```

![activity_monitor_mem_use](https://user-images.githubusercontent.com/20641653/33796622-86e61142-dd1e-11e7-99c9-179ae726c296.png)

**Comment by markekraus** [comment] 2017-12-09 22:19
Here is mine after 6,000,0000.

![2017-12-09-macoutput](https://user-images.githubusercontent.com/6509955/33799807-ac449402-dcf8-11e7-8cbf-3926992d6310.png)

I'm not sure. it could be something in your environment that is different than mine. You are basically seeing the same memory increase over time no matter what method we've tried too. So I'm not even sure where to look. If you would be willing to install the .NET Core 2.0.2 SDK (https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.2-sdk-download.md) and then run

```bash
mkdir MemLeakRepro
cd MemLeakRepro
dotnet new console
```

Then replace the contents of `Program.cs` with this https://gist.github.com/markekraus/b16f0991a843d2d2459aa4178dfe55b5#file-program-cs
then run

```bash
dotnet restore
dotnet run http://localhost:5001/api 6000000
```

and watch the memory usage. that will eliminate anything to do with PowerShell.

Also, just to be sure, you're not outputting anything to the console in these tests, right? Output to the console could skew the results.

**Comment by javaptgl** [comment] 2017-12-11 06:09
```
Apple:MemLeakRepro air$ dotnet run http://localhost:5001/api 6000000
Start: 12/10/2017 09:23:05
End: 12/11/2017 01:11:15
Run: 15:48:10.0077740
Memory: 491.00 mb
Press any key to exit...
Apple:MemLeakRepro air$
```

![memleakrepro](https://user-images.githubusercontent.com/20641653/33817860-cde3f8ee-de67-11e7-90d9-0bb0066cd29c.png)

**Comment by markekraus** [comment] 2017-12-11 09:52
@javaptgl Thanks! This makes it clear to me that the problem is not with PowerShell or the web cmdlets. You see the same behavior with a simple .NET app. That leads me to believe there is an issue with either .NET Core or your environment. I recommend taking this simple program and opening an issue on [dotnet/corefx](https://github.com/dotnet/corefx/issues/). There is no reason for that program to balloon like that. On my 10.13.1 mac it never gets above 55mb.

**Comment by javaptgl** [comment] 2017-12-11 12:38
Thank you. I'll be linking this issue to the dotnet/corefx repo.

**Comment by markekraus** [comment] 2017-12-11 14:11
@javaptgl You're welcome! Since we have determined the problem is outside of PowerShell I'm closing this issue. We can always reopen it later if the situation changes.

**Closed by markekraus** 2017-12-11 14:11 UTC
Labels: Area-Cmdlets-Utility, Area-Performance, Resolution-External

**Comment by benaadams** [comment] 2017-12-11 14:36
The [`HttpResponseMessage`](https://github.com/PowerShell/PowerShell/blob/f5f3fab1ea8a51dd2e5d34e0e580ab39176eb696/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebRequestPSCmdlet.CoreClr.cs#L546) in `WebRequestPSCmdlet.ProcessRecord` should be disposed?

**Comment by markekraus** [comment] 2017-12-11 14:44
@benaadams my understanding is that `reader.Dispose()` disposes the reader, the content stream, and the HttpResponseMessage.

**Comment by benaadams** [comment] 2017-12-11 14:58
The [Stream returned from `GetResponseStream`](https://github.com/PowerShell/PowerShell/blob/f5f3fab1ea8a51dd2e5d34e0e580ab39176eb696/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebRequestPSCmdlet.CoreClr.cs#L565) via [`response.Content.ReadAsStreamAsync()`](https://github.com/PowerShell/PowerShell/blob/f5f3fab1ea8a51dd2e5d34e0e580ab39176eb696/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs#L479) doesn't look like it necessarily has a link to the Content or Message [e.g. it can just be a MemoryStream over an array](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L280-L286)

**Comment by markekraus** [comment] 2017-12-11 15:23
https://github.com/dotnet/corefx/blob/6b5ef121ebea45b14f489a177e2e3f27fce86781/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L203

HttpResponseMessage.Dspose() calls `Dispose()` on `HttpResponseMessage.Content` which gets called when `reader.Dispose()` is called because it is the stream from `HttpResponseMessage.Content`.

**Comment by benaadams** [comment] 2017-12-11 16:10
The stream returned from `HttpResponseMessage.Content` is usually either a `LimitMemoryStream` or a `MemoryStream` and has no reference to anything else, so Disposing it doesn't Dispose the classes that create it (e.g. `HttpContent` or `HttpResponseMessage`) and only disposes the stream.

**Comment by markekraus** [comment] 2017-12-11 16:39
`HttpResponseMessage.Dspose()` Calls `HttpContent.Dispose()` Which calls `HttpContent.Dispose(bool disposing)` which creates the content stream if it hasn't already been created, then calls dispose on the content stream. Every thing points to  `HttpResponseMessage.Dspose()` being no different than calling `reader.Dispose()` which disposes the exact same stream.
