### ISSUE TITLE
[BUG] Using Write-Host in custom promt function causes prompt to break.

### ISSUE THREAD

**Issue by pavelbraginskiy** [PowerShell/PowerShell#5630] opened 2017-12-05 16:53 UTC
Steps to reproduce
------------------

Set a custom prompt function that uses `Write-Host` in `$PROFILE`, which is commonly done to have colorful prompts.

```powershell
# Here's the $PROFILE
function prompt
{
	Write-Host ">" -nonewline
	return ""
}
```

Expected behavior
-----------------
Prompt appears as `>`

Actual behavior
---------------
Prompt appears as `>PS>>`.  Upon entering text after the prompt, it changes to `PS>`. Hitting enter for the next command causes `>PS>>` to appear again.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                         
----                           -----                                         
PSVersion                      6.0.0-rc                                      
PSEdition                      Core                                          
GitCommitId                    v6.0.0-rc                                     
OS                             Linux 4.13.16-300.fc27.x86_64 #1 SMP Mon No...
Platform                       Unix                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                       
PSRemotingProtocolVersion      2.3                                           
SerializationVersion           1.1.0.1                                       
WSManStackVersion              3.0            
```

**Comment by MaximoTrinidad** [comment] 2017-12-05 20:33
I'm sure this is by design as you'll get the same results in Windows PowerShell. I would not recommend using Write-Host in the prompt option.

But, you could be creative and try something like this: (one of my old scripts)

```
function prompt
{
	## - This function will change the PS Console to enumerate each 
	##   line preventing long pathnames:
	if ($host.UI.RawUI.CursorPosition.Y -eq 0)
	{
		"< $pwd > `n`r" + "PS [" + $host.UI.RawUI.CursorPosition.Y + "] > "
	}
	Else
	{
		"PS [" + $host.UI.RawUI.CursorPosition.Y + "] > "
	}
};
```

At least, will give you some ideas.

**Comment by markekraus** [comment] 2017-12-05 20:47
I believe This is lzybkr/PSReadLine#468 and is a bug in PSReadLine that will be fixed in a future version.

**Closed** 2017-12-05 20:47 UTC
Labels: Area-PSReadLine, Resolution-External

**Comment by markekraus** [comment] 2017-12-06 16:41
@pavelbraginskiy a Prerelease of PSReadline has beem added tot he PS Gallery which fixes this issue: https://www.powershellgallery.com/packages/PSReadline/2.0.0-beta1

**Comment by pavelbraginskiy** [comment] 2017-12-06 17:50
@markekraus Thanks a bunch!
