### ISSUE TITLE
Selection does not work properly when completing arguments

### ISSUE THREAD

**Issue by eosfor** [PowerShell/PowerShell#7164] opened 2018-06-25 09:49 UTC
![2018-06-25_12-48-02](https://user-images.githubusercontent.com/9363027/41843430-3038b446-7876-11e8-84f2-62a26fa9f590.gif)

**Comment by mklement0** [comment] 2018-06-25 17:36
Just to confirm: not all completions are being cycled through?

I don't see the problem on PowerShell Core v6.1.0-preview.3 / PSReadLine v2.0.0-beta2.

Can you update to the latest PS Core version and/or PSReadLine version (`Install-Module -Name PSReadLine -AllowPrerelease` from an elevated session) and see if you still have the problem?

**Comment by vexx32** [comment] 2018-06-26 17:28
I think the issue is actually that OP is expecting the ability to select multiple options?

**Comment by mklement0** [comment] 2018-06-27 03:37
@vexx32: 

I don't think so, given that the parameter (`-first`) is declared as a _scalar_.

(If it were declared as an _array_, asking for multiple selections would make more sense, but it would raise questions about the keyboard interface: how would you mark a selection without submitting it at the same time? Currently, each array element must be specified / tab-completed individually.)

@eosfor: Please clarify.

**Comment by lzybkr** [comment] 2018-06-27 16:19
This was fixed in PSReadLine 2.0.0-beta1. Beta2 is included with the current preview of PowerShell, or you can install the beta as @mklement0 suggests.

**Closed by lzybkr** 2018-06-27 16:19 UTC
Labels: Area-Intellisense, Issue-Discussion
