### ISSUE TITLE
Text Block Removal Does not work

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/PowerShell#9169] opened 2019-03-19 19:32 UTC
When you select a text block in pwsh 6.2.0-rc.1 with ```Ctrl+Shift+Arrow``` and ```Delete``` it just cancels selection and will not delete anything:

![image](https://user-images.githubusercontent.com/5260172/54635953-63b70780-4a96-11e9-9776-42c20d01789a.png)

# Steps to reproduce

1. type any multi word command in powershell
2. select text with  ```Ctrl+Shift+Arrow```
3. hit "Delete"
4. 

# Expected behavior
Selected text gets deleted

# Actual behavior
Selected text will not get removed

# Environment data

```none
Name             : ConsoleHost
Version          : 6.2.0-rc.1
InstanceId       : 20ad1bf2-69de-44e5-9baa-0321535fb2dd
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by vexx32** [comment] 2019-03-19 19:39
I think this and #9168 are very likely both to be related to PSReadLine missing for some reason. I commented in that issue. 🙂

**Comment by YuriySamorodov** [comment] 2019-03-19 19:45
@vexx32 , it looks like you are correct. ```F4``` has started working again
![image](https://user-images.githubusercontent.com/5260172/54636992-a4b01b80-4a98-11e9-9a8c-b23f15281400.png)

**Comment by SteveL-MSFT** [comment] 2019-03-20 16:22
Dupe of #9168

**Closed by SteveL-MSFT** 2019-03-20 16:22 UTC
Labels: Area-PSReadLine, Issue-Question, Resolution-Duplicate
