### ISSUE TITLE
Error OSX Get-DSCResource

### ISSUE THREAD

**Issue by rwfleming** [PowerShell/PowerShell#3482] opened 2017-04-04 18:13 UTC
Steps to reproduce
------------------
I receive the error below when running Get-DSCResource.

Run the command below
```
get-dscresource
```

Expected behavior
-----------------
List of available DSC resources

Actual behavior
---------------
I receive the error below:

```
PS /Users/rwfleming/Projects/DSCFiles> get-DSCResource
Exception calling "LoadDefaultCimKeywords" with "2" argument(s): "Value cannot be null.
Parameter name: path1"
At /usr/local/microsoft/powershell/6.0.0-alpha.17/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1:3897 char:9
+         [Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscC ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

You cannot call a method on a null-valued expression.
At /usr/local/microsoft/powershell/6.0.0-alpha.17/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1:3817 char:5
+     $listPSModuleFolders = $env:PSModulePath.Split(";")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Module : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At /usr/local/microsoft/powershell/6.0.0-alpha.17/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1:3927 char:47
+ ...   $modules = Get-Module -ListAvailable -Name (Get-DSCResourceModules)
+                                                  ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Module], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetModuleCommand
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.17
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment] 2017-04-05 20:52
This is a dupe of #2337.

**Closed by joeyaiello** 2017-04-05 20:52 UTC
Labels: Area-DSC, Resolution-Duplicate
