### ISSUE TITLE
Invoking external command lines (utilities) is broken with respect to quoting on Unix

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3734] opened 2017-05-08 21:45 UTC
<sup>Related: #3733</sup>

Steps to reproduce
------------------

```powershell
/bin/sh -c "echo 'hi, mom'"
/bin/sh -c 'echo "hi, mom"'
```

Expected behavior
-----------------

```
hi, mom
hi, mom
```

Actual behavior
---------------

```
hi, mom
hi,
```

The following literals _should_ be passed through to `sh` (there's nothing for _PowerShell_ to interpret here):

```none
echo 'hi, mom'
echo "hi, mom"
```

To a POSIX-like shell, these two commands are _equivalent_ (not _generally_, but with the given strings).

Unexpectedly, in the case of the 2nd command, _2_ arguments are passed (`$<n>` represents the n-th positional parameter):

```none
$1=[echo hi,]
$2=[mom]
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on macOS 10.12.4
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Ubuntu 16.04.1 LTS
```

**Comment by TSlivede** [comment] 2017-05-24 13:54
Am I wrong, or is this a duplicate of https://github.com/PowerShell/PowerShell/issues/1995 and https://github.com/PowerShell/PowerShell/issues/3049 ?

I hope that this will be solved, RFC:
https://github.com/PowerShell/PowerShell-RFC/pull/90

**Comment by SteveL-MSFT** [comment] 2017-05-24 14:46
@TSlivede you're right, resolving as dupe and making the original higher priority

**Closed by SteveL-MSFT** 2017-05-24 14:46 UTC
