### ISSUE TITLE
Touch equivalent

### ISSUE THREAD

**Issue by 1Dragoon** [PowerShell/PowerShell#17096] opened 2022-04-01 21:13 UTC
### Summary of the new feature / enhancement

Powershell is great, but there's a lot of very simple things that ideally shouldn't be quite as verbose as powershell requires. One of these is 'touch'

One thing for example is when I wanted to create the profile for my admin account, I would like to have been able to just do this:

```powershell
@'
$PSReadLineOptions = @{
    EditMode = "Emacs"
    HistoryNoDuplicates = $true
    HistorySearchCursorMovesToEnd = $true
                ShowToolTips = $true
}
Set-PSReadLineOption @PSReadLineOptions
'@ > $profile
```

But that's a no go, because several paths along the way to where $profile pointed didn't exist. So instead you have to go through this:

```powershell
mkdir -p $profile # Creates the entire path as a directory, including the very last item that should be just a file
rmdir $profile # Deletes the very last bit that should have been a file

@'
$PSReadLineOptions = @{
    EditMode = "Emacs"
    HistoryNoDuplicates = $true
    HistorySearchCursorMovesToEnd = $true
                ShowToolTips = $true
}
Set-PSReadLineOption @PSReadLineOptions
'@ > $profile
```

Would be nice if I could just do 'touch $profile' and be done with it, or if > would create the path and file if needed. Or even better: Both. Yes, I know you can just create an alias for it, but aliases don't really help all that much in a lot of cases, particularly in this situation. In cases like this where you're setting up an account you haven't used before, or even logging into a system you haven't used that particular account on before.

**Comment by vexx32** [comment] 2022-04-01 21:56
Duplicate of #8621, #13054 #13572, and #11677

Please add any additional comments / requests to the latter issue. 🙂

**Closed by vexx32** 2022-04-01 21:56 UTC
Labels: Issue-Enhancement, Needs-Triage

**Comment by kasini3000** [comment] 2022-04-03 17:46
pwsh -c 'mkdir -p "$env:HOME/.config/powershell" '
$a= @'
$PSReadLineOptions = @{
    EditMode = "Emacs"
    HistoryNoDuplicates = $true
    HistorySearchCursorMovesToEnd = $true
                ShowToolTips = $true
}
Set-PSReadLineOption @PSReadLineOptions
'@

Set-Content -LiteralPath $PROFILE -Value $a

are you looking for a batch way to do this on every linux node?
use kasini3000 on windows master push linux version powershell to linux node,then run ps1 script batch.

----

[kasini3000](https://gitee.com/chuanjiao10/kasini3000)    
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline) 
Open source, free, cross-platform 
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

[kasini3000_agent_linux](https://gitee.com/chuanjiao10/kasini3000_agent_linux) Shell script,one click install powershell on linux,modify sshd_config for PsRemote.
