### ISSUE TITLE
New-AzPolicyDefinition: Length cannot be less than zero. (Parameter 'length')

### ISSUE THREAD

**Issue by emilguden** [PowerShell/PowerShell#15377] opened 2021-05-11 10:40 UTC
Getting the above error when running the deploy from PowerShell 7.2.0 preview 5.
PowerShell 7.1.3 works as expected.

1. Installed PowerShell 7.2.0 preview 5
2. Logged into Azure
3. Selected my subscription.
2. Tried to deploy the new Azure Policy Definition.

```powershell
New-AzPolicyDefinition -Name "allowed-locations3" `
    -DisplayName "Allowed locations3" `
    -Policy 'https://raw.githubusercontent.com/Azure/azure-policy/master/samples/built-in-policy/allowed-locations/azurepolicy.rules.json' `
    -Parameter 'https://raw.githubusercontent.com/Azure/azure-policy/master/samples/built-in-policy/allowed-locations/azurepolicy.parameters.json' `
    -Mode Indexed
```

## Expected behavior

```none

 ~\Desktop >  New-AzPolicyDefinition -Name "allowed-locations3" `
    -DisplayName "Allowed locations3" `
    -Policy 'https://raw.githubusercontent.com/Azure/azure-policy/master/samples/built-in-policy/allowed-locations/azurepolicy.rules.json' `
    -Parameter 'https://raw.githubusercontent.com/Azure/azure-policy/master/samples/built-in-policy/allowed-locations/azurepolicy.parameters.json' `
    -Mode Indexed

Name               : allowed-locations3
ResourceId         : /subscriptions/XXXXXX-XXXX-XXXX-XXXX-XXXXXX/providers/Microsoft.Authorization/policyDefinitions/allowed-locations3
ResourceName       : allowed-locations3
ResourceType       : Microsoft.Authorization/policyDefinitions
SubscriptionId     : XXXXXX-XXXX-XXXX-XXXX-XXXXXX
Properties         : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Policy.PsPolicyDefinitionProperties
PolicyDefinitionId : /subscriptions/XXXXXX-XXXX-XXXX-XXXX-XXXXXX/providers/Microsoft.Authorization/policyDefinitions/allowed-locations3

```

## Actual behavior

```none

C:\Program Files\PowerShell\7-preview> New-AzPolicyDefinition -Name "allowed-locations3" `
>>     -DisplayName "Allowed locations3" `
>>     -Policy 'https://raw.githubusercontent.com/Azure/azure-policy/master/samples/built-in-policy/allowed-locations/azurepolicy.rules.json' `
>>     -Parameter 'https://raw.githubusercontent.com/Azure/azure-policy/master/samples/built-in-policy/allowed-locations/azurepolicy.parameters.json' `
>>     -Mode Indexed
New-AzPolicyDefinition: Length cannot be less than zero. (Parameter 'length')

C:\Program Files\PowerShell\7-preview>  Get-Error

Exception             :
    Type       : System.ArgumentOutOfRangeException
    Message    : Length cannot be less than zero. (Parameter 'length')
    ParamName  : length
    TargetSite :
        Name          : HandleException
        DeclaringType : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase
        MemberType    : Method
        Module        : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll
    StackTrace :
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
    Source     : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager
    HResult    : -2146233086
CategoryInfo          : CloseError: (:) [New-AzPolicyDefinition], ArgumentOutOfRangeException
FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicyDefinitionCmdlet
InvocationInfo        :
    MyCommand        : New-AzPolicyDefinition
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : New-AzPolicyDefinition -Name "allowed-locations3" `

    PositionMessage  : At line:1 char:1
                       + New-AzPolicyDefinition -Name "allowed-locations3" `
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-AzPolicyDefinition
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :

```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by daxian-dbw** [comment] 2021-05-11 16:54
@emilguden Did you use the same version of Az PowreShell module when trying on 7.1.3 and 7.2.0-preview.5?

@cormacpayne and @markcowl, can you please take a look?

**Comment by emilguden** [comment] 2021-05-11 19:59
> @emilguden Did you use the same version of Az PowreShell module when trying on 7.1.3 and 7.2.0-preview.5?
> 
> @cormacpayne and @markcowl, can you please take a look?

Hi @daxian-dbw ,

Yes, it's the same:

PowerShell 7.1.3
``` none
PS C:\>  Get-Module Az

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     5.9.0                 Az

PS C:\>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

PowerShell 7.2.0 Preview 5
``` none
PS C:\>  Get-Module Az

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     5.9.0                 Az

PS C:\>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dingmeng-xue** [comment] 2021-05-12 03:30
I thought I was looking into the issue in Azure/azure-powershell repo. So, I created a separate one to PowerShell.

**Comment by daxian-dbw** [comment] 2021-05-12 16:39
@dingmeng-xue Thanks for confirming this is a another case of the minimal progress rendering issue.
So this is a duplicate of #15251, and the PR is out #15264. I will close this one as duplicate and get the PR merged soon.

**Closed by daxian-dbw** 2021-05-12 16:39 UTC
Labels: Needs-Triage
