### ISSUE TITLE
ConvertTo-Html incorrectly labels default single column

### ISSUE THREAD

**Issue by TimCurwick** [PowerShell/PowerShell#2185] opened 2016-09-04 16:14 UTC
Previously documented on UserVoice https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11522970-convertto-html-incorrectly-labels-default-single-c

When the -Property parameter is not used (and it thereby defaults to match string '*') or when a match string is used with the -Property parameter, and the result is only a single property, ConvertTo-Html uses the match string as the column header instead of the property name.
## Steps to reproduce

``` powershell
$X = [pscustomobject]@{ Name = 'Joe' } 
ConvertTo-Html -InputObject $X -Fragment
''
$X = [pscustomobject]@{ Name = 'Joe'; ID = 27 } 
ConvertTo-Html -InputObject $X -Property N* -Fragment
```
## Expected behavior

<table>
<colgroup><col/></colgroup>
<tr><th>Name</th></tr>
<tr><td>Joe</td></tr>
</table>

<table>
<colgroup><col/></colgroup>
<tr><th>Name</th></tr>
<tr><td>Joe</td></tr>
</table>

## Actual behavior

<table>
<colgroup><col/></colgroup>
<tr><th>*</th></tr>
<tr><td>Joe</td></tr>
</table>

<table>
<colgroup><col/></colgroup>
<tr><th>N*</th></tr>
<tr><td>Joe</td></tr>
</table>

## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9-248-g2b3f79345f83c42a1b45cfd860dc364d33300883
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> $PSVersionTable
Name                           Value                                                                                                                                                                 
----                           -----                                                                                                                                                                 
PSVersion                      5.1.14393.103                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                               
BuildVersion                   10.0.14393.103                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                   
SerializationVersion           1.1.0.1 
```

**Comment by rjmholt** [comment] 2018-03-08 03:01
Looks like this was fixed by #4276 -- just tested it and can't reproduce. @SteveL-MSFT

**Closed** 2018-03-08 03:01 UTC
Labels: Area-Cmdlets, Issue-Bug
