### ISSUE TITLE
Compress-Archive File size Limitation

### ISSUE THREAD

**Issue by Bearstonk** [PowerShell/PowerShell#17360] opened 2022-05-17 12:39 UTC
### Summary of the new feature / enhancement

The Compress-Archive cmdlet uses the Microsoft .NET API [System.IO.Compression.ZipArchive](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive) to compress files. The maximum file size is 2 GB because there's a limitation of the underlying API.

This presents an issue with file compression using native/non-third party tools. With popular tools like 7Zip being found lacking on the security side of the house, it would be wonderful to have native tools within PowerShell handle this common task without such a major limitation.

### Proposed technical implementation details (optional)

the Microsoft .NET API [System.IO.Compression.ZipArchive](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive   needs updating or replacement to permit file sizes greater than 2GB.

**Comment by kilasuit** [comment] 2022-05-17 13:23
This is a duplicate of an existing issue that I've commented on that @SteveL-MSFT raised in the Archive Module Repo https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19 and as such should be tracked there & this issue closed.

**Comment by kasini3000** [comment] 2022-05-17 16:39
Hi fans :
I wrote several scripts in KASINI 3000. It uses the 7zip library, welcome to use, feedback questions.

c:\ProgramData\kasini3000\node_ script\7z\
l7za2zip. PS1 --- compressed into ZIP under Linux
l7zu2zip. PS1 ---- update zip under Linux
l7za27z. PS1 --- compressed into 7z under Linux
l7zu27z. PS1 ---- update 7z under Linux
l7zx. PS1 --- Linux decompression

w7za2zip. PS1 --- compressed into ZIP under win
w7zu2zip. PS1 --- update zip under win
w7za27z. PS1 --- compressed to 7z under win
w7zu27z. PS1 --- update 7z under win
w7zx. PS1 --- decompress under win

----

[kasini3000](https://gitee.com/chuanjiao10/kasini3000) site mirror:(https://github.com/kasini3000/kasini3000)   
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline) 
Open source, free, cross-platform 
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

[kasini3000_agent_linux](https://gitee.com/chuanjiao10/kasini3000_agent_linux) Shell script,one click install powershell on linux,modify sshd_config for PsRemote.

**Closed** 2022-05-18 19:00 UTC
Labels: Issue-Enhancement, Resolution-External
