### ISSUE TITLE
Powershell DSC does not work on OSX 

### ISSUE THREAD

**Issue by jdcc2** [PowerShell/PowerShell#10782] opened 2019-10-12 20:02 UTC
Anything related to DSC does not seem to work on OSX because of a dependency problem. Related to https://github.com/PowerShell/MMI/issues/33 

It is not a problem with Publish-AzVMDscConfiguration, but this happens with anything DSC related. 

# Steps to reproduce 

```powershell
Publish-AzVMDscConfiguration ".\configuread.ps1" -OutputArchivePath ".\configuread.ps1.zip"
```

# Expected behavior

```none
No errors
```

# Actual behavior

```none
Publish-AzVMDscConfiguration : Configuration script '/Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1' contained parse errors:
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:1 char:15
+ Configuration NewADForest
+               ~~~~~~~~~~~
System.IO.DirectoryNotFoundException: Unable to find DSC schema store at /etc/opt/omi/conf/dsc/configuration. Please ensure PS DSC for Linux is installed.
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Collection`1 errors)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token configurationToken)
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:2 char:1
+ {
+ ~
Unexpected token '{' in expression or statement.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:8 char:52
+         [System.Management.Automation.PSCredential]
+                                                    ~
Missing closing ')' in expression.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:9 char:9
+         $Credential,
+         ~~~~~~~~~~~
Unexpected token '$Credential' in expression or statement.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:18 char:5
+     )
+     ~
Unexpected token ')' in expression or statement.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:63 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:6 char:9
+         [Parameter(Mandatory = $true)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected attribute 'Parameter'.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:7 char:9
+         [ValidateNotNullOrEmpty()]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected attribute 'ValidateNotNullOrEmpty'.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:12 char:9
+         [Parameter(Mandatory = $true)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected attribute 'Parameter'.
At /Users/jhk/Workspace/tf-azure-dsc/dsc/configuread.ps1:13 char:9
+         [ValidateNotNullOrEmpty()]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected attribute 'ValidateNotNullOrEmpty'.
At line:1 char:1
+ Publish-AzVMDscConfiguration ".\configuread.ps1" -OutputArchivePath " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ParserError: (:) [Publish-AzVMDscConfiguration], ParseException
+ FullyQualifiedErrorId : DscConfigurationParseError,Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand
```

# Environment data

I tried both the stable version and the preview.

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PleaseStopAsking** [comment] 2019-11-04 15:31
@amitsara Is this issue being investigated? Travis Plunk mentioned you were looking into this under https://github.com/PowerShell/MMI/issues/33 and while that issue was closed as OMI is obsolete, the issues still exist and make editing DSC configs on MacOS difficult.

**Comment by raandree** [comment] 2020-02-06 22:53
Running into this in Azure Cloud Shell. How can I use DSC in the cloud shell then?

**Comment by PleaseStopAsking** [comment] 2020-02-19 15:05
This is still an issue on the most recent RC. 

![image](https://user-images.githubusercontent.com/35308946/74846852-3191d380-52ff-11ea-8952-da6f1b602e1b.png)

![image](https://user-images.githubusercontent.com/35308946/74846874-36ef1e00-52ff-11ea-9a80-1bcbbf5998d1.png)

**Comment by PleaseStopAsking** [comment] 2020-04-07 13:17
Any update on this? Dsc on MacOS is unusable at this point.

**Comment by raandree** [comment] 2020-04-07 14:35
@mgreenegit, @nitinbps, is this something you can help?

**Comment by thecherrytree** [comment] 2020-07-10 14:17
This is an issue for us as well. @mgreenegit @nitinbps

**Comment by thecherrytree** [comment] 2020-07-10 17:05
@PleaseStopAsking  - the way the token errors are showing up makes me think this is more of a unix conversion issue. Have you tried running unix2dos or dos2unix on your .ps1 before running the Start-DscConfiguration? I've seen that the DSC configuration when using an ARM Template will error out with a vanilla configuration file developed on a Mac, but will work fine with one developed on a windows device. The extra line breaks in the configuration file might actually be the cause of the weird schema and parsing errors.

**Comment by tigerdeccan** [comment] 2020-07-11 21:54
same issue with me , updated Az modules and powershel7 as well. still no luck. My understanding is OMi is not used on Mac but for somereason it still expects it , 
System.IO.DirectoryNotFoundException: Unable to find DSC schema store at /etc/opt/omi/conf/dsc/configuration. Please ensure PS DSC for Linux is installed.
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Collection`1 errors)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token configurationToken)PowerShell
Peek Problem (⌥F8)

**Comment by PleaseStopAsking** [comment] 2020-07-13 13:14
@thecherrytree I am actually not even getting to the point of executing them when I get the error. I am seeing the error when simply viewing my .ps1 files within VSCode. I don't currently execute them on MacOS, just develop them there and then execute on Windows boxes elsewhere.

**Comment by MikeCantCode** [comment] 2020-08-14 02:47
Here's output when running a good ol fashioned 'Get-DscResource'. 

MacOS Catalina (10.15.6) running PowerShell 7.0.3

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> Get-DscResource

PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ImportCimKeywordsFromModule" with "5" argument(s): "Unable to load shared
                        library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
                        dlopen(liblibmi, 1): image not found"
                         ---> System.DllNotFoundException: Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems,
                        consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibmi, 1): image not found
                           at Microsoft.Management.Infrastructure.Native.NativeMethods.MI_Application_InitializeV1(UInt32 flags, String applicationID, IndirectPtr
                        extendedError, DirectPtr application)
                           at Microsoft.Management.Infrastructure.Native.MI_Application.Initialize(String applicationId, MI_Instance& extendedError, MI_Application& application)
                           at Microsoft.Management.Infrastructure.Internal.CimApplication.GetApplicationHandle()
                           at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Lazy`1.CreateValue()
                           at Microsoft.Management.Infrastructure.Internal.CimApplication.get_Handle()
                           at Microsoft.Management.Infrastructure.Serialization.CimMofDeserializer..ctor()
                           at Microsoft.Management.Infrastructure.Serialization.CimMofDeserializer.Create()
                           at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser..ctor(OnClassNeeded onClassNeeded)
                           at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.ImportClasses(String path, Tuple`2 moduleInfo, Collection`1 errors, Boolean
                        importInBoxResourcesImplicitly)
                           at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.ImportCimKeywordsFromModule(PSModuleInfo module, String resourceName,
                        String& schemaFilePath, Dictionary`2 functionsToDefine, Collection`1 errors)
                           at CallSite.Target(Closure , CallSite , Type , Object , Object , PSReference , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName,
                        Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Type , Object , Object , PSReference , Object , Object )
                           at ImportCimAndScriptKeywordsFromModule(Closure , FunctionContext )
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : DllNotFoundException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at ImportCimAndScriptKeywordsFromModule, /usr/local/microsoft/powershell/7/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1: line
                        2527
                        at Get-DscResource<Begin>, /usr/local/microsoft/powershell/7/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1: line 3980
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

It would be great to be able to develop DSC Configurations for Windows on a Mac.

**Comment by iSazonov** [comment] 2021-01-15 18:29
See ##13399 about cross-planform DSC implementation.

**Closed by iSazonov** 2021-01-15 18:29 UTC
Labels: Area-DSC, Issue-Question

**Comment by gaelcolas** [comment] 2021-02-04 11:06
Just in case someone is looking at this for other distro, the same issue seems to affect SLES and Alpine, using pwsh 7.1.1 and `PSDesiredStateConfiguration` module version 2.0.5.

**Comment by iSazonov** [comment] 2021-02-04 11:21
#13399 was merged recently!

**Comment by brwilkinson** [comment] 2021-09-03 00:30
Any status updates on this one ?

**Comment by iSazonov** [comment] 2021-09-03 02:51
@brwilkinson See #13399 description.

**Comment by brwilkinson** [comment] 2021-09-03 03:02
So is the TL;DR that with latest preview psdesiredstateconfiguration module 3+ class based resources should be supported ?

I would like to be able to package up the DSC zips that are used for the VM DSC Extension on Mac or Linux. 

i.e. support to run Publish-AzVMDscConfiguration

**Comment by iSazonov** [comment] 2021-09-03 04:13
> So is the TL;DR that with latest preview psdesiredstateconfiguration module 3+ class based resources should be supported ?

Yes, they haven't MMI dependency.

**Comment by mgreenegit** [comment] 2021-09-03 11:09
Yes. This issue is resolved in DSCv3. Also, you no longer need to use the DSC extension. You can start testing in Guest Config.

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration-custom

**Comment by brwilkinson** [comment] 2021-09-03 17:37
@mgreenegit definitely looking forward to be able to use the fresh new guest config goods.

For now, many customers still have full ecosystems of deployment templates, 50% of which are push mode, with established MOF based resources.

I have found that many customers deploying Windows Operating Systems in Azure, have easily been able to deploy from Linux or MAC via PowerShell 7, without problems for 98% of the lifecycle (being: Terraform/Templates/ARM/Bicep/DSC/Script extension Etc.)

I found that 'Publish-AzVMDscConfiguration' was the 1 blocker to packaging the zips for push mode deployments, i.e. staging them on the storage account for deployment, So I had to roll my own version with Compress-Archive to create these packages (on Mac or Linux) to get around this issue.

**Comment by brwilkinson** [comment] 2021-09-03 17:56
I feel like 'Publish-AzVMDscConfiguration' should be updated to work anywhere powershell 7 runs.

Since it just reads the configuration.ps1, then reads the import-dscresource list and packages the resource folders into the zip with the json manifest, along with the configuration.

**Comment by mgreenegit** [comment] 2021-09-06 07:50
Yep. We made a huge investment in the authoring module to address that issue and others such as making it easy to test.

https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create

https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create-test

https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create-publish

GC is like push mode with reporting and multiple configs.
________________________________

**Comment by brwilkinson** [comment] 2021-09-07 02:42
Not talking about GC, talking about what customers are already using.

We should make 'Publish-AzVMDscConfiguration' work with Powershell 7. Since the rest of the Azure modules work with Powershell 7. It just needs to package the zips.

**Comment by AnAncientAlien** [comment] 2021-10-06 11:06
Please open the issue as we can't create a zip file!!!

**Comment by mgreenegit** [comment] 2021-10-06 11:24
@AnAncientAlien have you tried with the new-guestconfigurationpackage command?

**Comment by AnAncientAlien** [comment] 2021-10-06 12:25
> @AnAncientAlien have you tried with the new-guestconfigurationpackage command?

Yes, result is the same with different error. I want only create a zip file for dsc!!

**Comment by abkkr** [comment] 2022-03-18 14:20
Same as of 7.2.2

```
Name                           Value                                                                                    
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
System.IO.DirectoryNotFoundException: Unable to find DSC schema store at /etc/opt/omi/conf/dsc/configuration. Please ensure PS DSC for Linux is installed.    at
     | Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)    at
     | Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1
     | modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)    at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1
     | customAttributes, Token configurationToken)
```

Get-DscResource returns

```
MethodInvocationException: Exception calling "LoadDefaultCimKeywords" with "2" argument(s): "Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems,
```
