### ISSUE TITLE
Channel-specific update notices

### ISSUE THREAD

**Issue by khooz** [PowerShell/PowerShell#14780] opened 2021-02-12 17:11 UTC
## Summary of the new feature/enhancement

Since PowerShell is distributed through different channels now (eg. installer, package manager or Store); it's more convenient that new version release notices appear per channel; or it's rather inconvenient that an update notice appears when there's no new release for a specific channel.

Currently, as I have opted in for Microsoft Store distribution channel, I get the notice to update PowerShell to v7.1.2 while the latest release on MS Store is v7.1.1 as stated below:

![image](https://user-images.githubusercontent.com/8382714/107799344-8c270980-6d72-11eb-9ec6-bdcc2ac58649.png)

## Proposed technical implementation details (optional)

Check the version availability with the channel provider with for target build, or create different channels on where the queries are made and send installed version properties (like current version and package manager) with the query.

**Comment by daxian-dbw** [comment] 2021-02-18 22:47
This is more of a release pipeline issue that we will have to solve, to make the packages generally available before publishing the release. Will resolve this as a duplicate of #14772.

**Closed by daxian-dbw** 2021-02-18 22:47 UTC
Labels: Issue-Enhancement, Needs-Triage
