### ISSUE TITLE
v7.4.2 not in Ubuntu 22.04 Linux package repository for Microsoft products

### ISSUE THREAD

**Issue by Peperud** [PowerShell/PowerShell#23784] opened 2024-05-11 20:46 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

It has been a month since 7.4.2 was released, but it seems it still hasn't made it to the Ubuntu 22.04 repository. 
If 7.4.2 is manually installed, it get's downgraded back to 7.4.1 with the next ```apt upgrade```.

### Expected behavior

```console
v7.4.2 should be available in the Ubuntu 22.04 repository.
```

### Actual behavior

```console
v7.4.2 is not available in the Ubuntu 22.04 repository.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             KDE neon 6.0
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PhilippNaused** [comment] 2024-05-13 17:06
Looks like a duplicate of #21493.

**Closed** 2024-05-14 20:44 UTC
Labels: Resolution-Duplicate
