### ISSUE TITLE
Get-ItemPropertyValue is not honoring -ErrorAction Ignore

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#13901] opened 2020-10-26 22:19 UTC
## Steps to reproduce

```powershell
 Get-ItemPropertyValue HKCU:\SOFTWARE\ -Name Foo -ErrorAction Ignore
```

## Expected behavior

We should not see the error indicating that the Foo property does not exist.  Note that `Get-ItemProperty HKCU:\SOFTWARE\ -Name Foo -ErrorAction Ignore` behaves correctly (there is no error).

## Actual behavior
`-ErrorAction Ignore` is itself ignored
```none
PS> Get-ItemPropertyValue HKCU:\SOFTWARE\ -Name Foo -ErrorAction Ignore
Get-ItemPropertyValue: Property Foo does not exist at path HKEY_CURRENT_USER\SOFTWARE\.
```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment] 2020-10-26 22:47
Good point, but this is a duplicate of #5906; in short: The error that is reported when a value (property) by a given name isn't found should be a _non-terminating error_ (`PSCmdlet.WriteError()`), not a (statement-)terminating one (`PSCmdlet.ThrowTerminatingError()`, as it currently is.

**Closed** 2020-10-28 11:00 UTC
Labels: Area-Cmdlets-Management, Issue-Question, Resolution-Duplicate
