### ISSUE TITLE
Powershell Core doesn't load the right assemblies

### ISSUE THREAD

**Issue by tessierp** [PowerShell/PowerShell#6757] opened 2018-04-27 17:16 UTC
I recently came accross a problem designing a powershell core cmdlet where it couldn'T load an assembly. The CmdLet I designed uses a package that requires Newtonsoft Json version 11.0.2. When I ran the command, I got this error message :

An exception occured while processing : <Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)>, <System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.

So I thought, it must be seeing another version somewhere somehow or it is not executing the Cmdlet in the directory where my assembly is. So I proceeded to set the working directory but that didn't help at all.

After doing some research I found out that Powershell Core uses Newtonsoft Json version 10.0.3. When I replaced that DLL with version 11.0.2, my CmdLet worked perfectly.

So it would see that when we Import a module, it will first look in the powershell core's executable path first for the DLLs it needs and then my assembly's directory.  I haven't seen anywhere a way to override this.

Or perhaps there is a better way I could solve this problem. I would appreciate to have some feedback regarding this.

Thanks

**Comment by SteveL-MSFT** [comment] 2018-04-27 18:51
Dupe of https://github.com/PowerShell/PowerShell/issues/2083

**Closed by SteveL-MSFT** 2018-04-27 18:51 UTC
Labels: Resolution-Duplicate
