### ISSUE TITLE
Error in Install posh-git into ubuntu 14

### ISSUE THREAD

**Issue by rabeesh** [PowerShell/PowerShell#2012] opened 2016-08-22 12:22 UTC
Error in Install posh-git into ubuntu 14.

Steps to reproduce
------------------
Install-Module posh-git

Expected behavior
-----------------
Install correctly

Actual behavior
---------------
```
PackageManagement\Install-Package : Could not compare "6.0.0-alpha" to "5.0". 
Error: "Cannot convert value "5.0" to type "System.Management.Automation.SemanticVersion". 
Error: "Cannot process argument      
Installing package 'posh-git' 
because the value of argument "version" is not valid. 
Change the value of the "version" argument and run the operation again.""
At /opt/microsoft/powershell/6.0.0-alpha.9/Modules/PowerShellGet/PSModule.psm1:1706 char:21oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo] + ...          
$null = PackageManagement\Install-Package @PSBoundParameters                                                                                                                                  +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ComparisonFailure,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
$PSVersionTable  
-------------------
```
>           $PSVersionTable                                                                                                                                                                                  

Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      6.0.0-alpha                                                                                                                                                                  
PSEdition                      Core                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   3.0.0.0                                                                                                                                                                      
GitCommitId                    v6.0.0-alpha.9                                                                                                                                                               
CLRVersion                                                                                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1       
```

**Comment by lzybkr** [comment] 2016-08-22 16:40
Duplicate of #1622, also see workaround #1927.

**Closed by lzybkr** 2016-08-22 16:40 UTC
