### ISSUE TITLE
Import-Module: Operation is not supported on this platform. (0x80131539)

### ISSUE THREAD

**Issue by andrewbaker-uk** [PowerShell/PowerShell#15157] opened 2021-04-05 11:57 UTC
## Steps to reproduce

```powershell

PS C:\Users\Andre> Get-AppxPackage Microsoft.GamingServices
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
PS C:\Users\Andre> import-module appx
Import-Module: Operation is not supported on this platform. (0x80131539)

```

## Expected behavior

When running the same command on PowerShell 5, the command runs as expected

```powershell

PS C:\Users\Andre> Get-AppxPackage Microsoft.GamingServices


Name              : Microsoft.GamingServices
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 2.51.29001.0
PackageFullName   : Microsoft.GamingServices_2.51.29001.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.GamingServices_2.51.29001.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.GamingServices_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe,
                    Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

```

## Actual behavior

```powershell

PS C:\Users\Andre> Get-AppxPackage Microsoft.GamingServices
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
PS C:\Users\Andre> import-module appx
Import-Module: Operation is not supported on this platform. (0x80131539)

```

## Environment data

```powershell

Name                           Value
----                           -----
PSVersion                      5.1.21343.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.21343.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by SeeminglyScience** [comment] 2021-04-05 12:08
Duplicate of #13138

**Closed** 2021-04-06 14:00 UTC
Labels: Resolution-Duplicate
